### ISSUE TITLE
Firefox: The character encoding of the HTML document was not declared

### ISSUE THREAD

**Issue by kavaro** [webpack/webpack-dev-server#1]
I just love webpack ...

Small issue I am sure many people will walk into and that is super easy to fix once and for all,
in firefox, webpack-dev-server generates the following warning whenever the page reloads:

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must to be declared in the document or in the transfer protocol."

To fix this: 

in the head of client/live.html add: 

``` javascript
<meta charset="utf-8"/>
```

**Comment by awanjila** [comment]
Lol! Thank you..

**Comment by Davecalix** [comment]
Thanks!...

**Comment by rwever-316** [comment]
<meta charset="UTF-8">

**Comment by webster124507** [comment]
d

**Comment by DharshanJS** [comment]
Thanks!

**Comment by Evan2804** [comment]
Thanks.

**Comment by mullinsr** [comment]
+1

**Comment by LandonFerg** [comment]
Thanks!

**Comment by gorakhnathlad** [comment]
Thanks.

**Comment by amineboos** [comment]
thanks ;)

**Comment by arihajix** [comment]
Cool! Tnx pal!

**Comment by DMTrooper3** [comment]
Thank you 🐱‍🐉

**Comment by gisellevqz** [comment]
it worked!  Thanks for sharing

**Comment by ravisoni6262** [comment]
thanks

**Comment by mohammed1997010** [comment]
lol man :D

**Comment by haddad142** [comment]
Thanks dude!

**Comment by samsep0il** [comment]
Thank You !

**Comment by geradseth** [comment]
Didn't work for me I am using WebSocket class to connect to my server with index.php javascript code seems to alright I don't know what happen on my php file with html code like
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title>PHP Chat With Mteule</title>
    </head>
    <body>
        <div>
            <span>Write Message to Send Here</span>
            <textarea placeholder="Message is public don't abuse"></textarea>
        </div>
        <footer>
            <script type = "text/javascript">

                var conn = new WebSocket('ws://192.168.1.116:2700');
                conn.onopen = function(e){
                    console.log("Connectio Established");
                    conn.send("I got in my Self as Agent");
                };
                conn.onmessage = function(e){
                    console.log(e.data);
                };

            </script>
        </footer>
    </body>
</html>
