### ISSUE TITLE
Can't resolve 'sockjs-client' in webpack-dev-server 2.6.0

### ISSUE THREAD

**Issue by vincent-cm** [webpack/webpack-dev-server#1003]
ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client' in '.../node_modules/webpack-dev-server/client'
 @ (webpack)-dev-server/client/socket.js 1:13-37
 @ (webpack)-dev-server/client?http://0.0.0.0:8888
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8888 ./src/polyfills.browser.ts

**Comment by SpaceK33z** [comment]
Does this also happen in the previous version?

**Comment by vincent-cm** [comment]
Closed upgrade to 2.6.1

**Comment by rubencodes** [comment]
This happens to be in 2.7.1 (though it worked in 2.6.1)

**Comment by zskovacs** [comment]
It happened to me as well when i upgraded from 2.6.1 to 2.7.1.
You should try to delete the node_modules folder and run `npm install` again. It solved the problem for me.

**Comment by rubencodes** [comment]
This worked, thanks!

**Comment by paviad** [comment]
Why does deleting node_modules sometimes help?

**Comment by AlexTo** [comment]
Deleting "node_modules" and "npm install" doesn't work for me. But clearing cache before "npm install" works. Here are the steps
1. Delete node_modules
2. npm cache clear --force
3. npm install

I tried several times with only step 1 and 3 with no luck until I tried to clear cache then install. Somehow, npm messed up my cache too :(

**Comment by TaylorPzreal** [comment]
Same **v2.8.2**,
delete ***node_modules*** 
and ```npm i```

**Comment by acusti** [comment]
Quick note for those on node v8.x: I also had to delete my `package-lock.json` file (in addition to `node_modules`) before running `npm install`

**Comment by aykutyararbas** [comment]
Added  "sockjs-client": "^1.1.4", 

It has the dist folder and js.

**Comment by charliebrink** [comment]
@aykutyararbas your suggestion did the trick for me.

**Comment by aykutyararbas** [comment]
@charliebrink Wonderful!

**Comment by goofballLogic** [comment]
I had to `chmod 777` the file in question :(

**Comment by sikanderrafiq** [comment]
> Added "sockjs-client": "^1.1.4",
> 
> It has the dist folder and js.

Where you have added this file??
