### ISSUE TITLE
Errors when running webpack-dev-server

### ISSUE THREAD

**Issue by hectopod** [webpack/webpack-dev-server#1008]
ERROR in (webpack)-dev-server/client/overlay.js
Module not found: Error: Can't resolve 'ansi-html' 

ERROR in (webpack)-dev-server/client/overlay.js
Module not found: Error: Can't resolve 'html-entities' 

ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Can't resolve 'sockjs-client'

Latest version of webpack-dev-server
Latest version of npm

I have this errors when I run webpack-dev-server

**Comment by hectopod** [comment]
Working after fresh install

**Comment by jjrchrds** [comment]
What do you mean by fresh install? I keep getting these errors.

thank you
