### ISSUE TITLE
[bug] WDS@2.6.0 incompatible with webpack@2.7.0 ?

### ISSUE THREAD

**Issue by animesh10** [webpack/webpack-dev-server#1009]
Hi,
 While running webpack with hot module reload i get the following error: 

``` 
ERROR in (webpack)-dev-server/client?http://localhost:2992
Module not found: Error: Can't resolve 'webpack/hot' in '/node_modules/webpack-dev-server/client'
 @ (webpack)-dev-server/client?http://localhost:2992 79:15-65
 @ multi (webpack)-dev-server/client?http://localhost:2992 ./app.jsx 
```

Upon further investigation I noticed that the above error is due to 

https://github.com/webpack/webpack-dev-server/commit/6da2f38bb24b99fa0eceb10d5ee63259d02e6c8a

Which in-turn depends on `webpack/hot/log.js` file being present. 
That file is only available in webpack 3.
Does that mean I will have to upgrade to webpack 3 when using wds@2.6.0 or greater ?

Webpack@2.7.0
webpack-dev-server@2.6.1
MAC OS Sierra: 10.12.6

**Comment by jchip** [comment]
> That file is only available in webpack 3.
> Does that mean I will have to upgrade to webpack 3 when using wds@2.6.0 or greater ?

If that's the case then it's a breaking change for WDS, which may have been better to get a major release.

**Comment by shellscape** [comment]
> If that's the case then it's a breaking change for WDS, which may have been better to get a major release.

Yeah, that's true. There may be some monkeypatching that can be done in a patch release to resolve this. Investigating.

**Comment by shellscape** [comment]
I've tried to reproduce this about every way I can think of. I you're able to put together a repo that consistently reproduces the issue, we can take another look at it. But at the moment I'm afraid we have to chalk this up to an edge case due to something specific with your system. I'm happy to reopen if needs be.

**Comment by jchip** [comment]
@shellscape thanks for looking into this.  Turns out we have a custom resolver plugin that's causing `require.context` to fail.

**Comment by shellscape** [comment]
@jchip no problem. glad you found the root cause!

**Comment by AdamDrobotij** [comment]
@jchip How did you resolve this? I'm getting this odd output from webpack:
```[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built][./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]```

and the `webpack/hot` modules are not getting bundled. I believe my issue is related to this line:
https://github.com/webpack/webpack-dev-server/blob/da188a6359b372d7885bde1fe204b5b835ff3466/client/index.js#L79 

Using webpack@3.5.2 and webpack-dev-server@2.7.1

**Comment by jchip** [comment]
@AdamDrobotij My problem was different.  I had a custom resolver plugin that simply broke `require.context`.  After I fixed that, I get the same thing as you.  I think that's just how webpack does it.  Since WDS is dev only, it shouldn't be an issue.
