### ISSUE TITLE
Log something to the shell from js code

### ISSUE THREAD

**Issue by timkelty** [webpack/webpack-dev-server#101]
Instead of `console.log`ing and checking the browser, it would be cool to be able to log something directly to the shell.

Is there a way to do this?

Would also be nice if it could tie in with something like `grunt-notify` to log and get a notification with the result.

**Comment by steida** [comment]
Or gulp-notify. I tried almost everything, and it seems it's impossible to hook webpack-dev-server errors in gulp.

**Comment by SpaceK33z** [comment]
Could be a nice feature. What exactly would you want logged to the CLI? All `console.log`'s, `console.warn`'s `console.error`'s?

**Comment by SpaceK33z** [comment]
Anyone still interested in this? I can implement this, but will need some feedback...

**Comment by geowarin** [comment]
Yep, I think it would be a really cool feature.
I got a similar request for my plugin: https://github.com/geowarin/friendly-errors-webpack-plugin/issues/7.

I think it would be very interesting to have React warnings (I think they use `console.error` for those) show up in the CLI.

Maybe @gaeron would agree here?

Those logs would be really useful if emitted as webpack errors, is that possible?

**Comment by SpaceK33z** [comment]
We _could_ override `console.log`, `warn`  and `error` to send it to the websocket. I think that should not be enabled by default though. Also, we'd need to make sure some webpack errors aren't reported twice.

**Comment by SpaceK33z** [comment]
An alternative would be to provide a hook that lets you write logs to the websocket, and let the application decide what exactly to log to it. The advantage of this is that it is way more flexible; you could make a plugin that automatically passes `console.logs` to it.

**Comment by gaearon** [comment]
We will be showing React warnings in a modal soon so it doesn’t seem to be important to us.

**Comment by SpaceK33z** [comment]
@geowarin, what do you think of the two options above?

**Comment by SpaceK33z** [comment]
I am closing this since this will be very difficult to implement properly, and I don't think that's worth it for now. Especially now React is going to show these warnings in a modal, it is probably better to find (or make) a package that displays these errors in a model for you.
