### ISSUE TITLE
Feature proposal: requestCert field for authenticating client certificate

### ISSUE THREAD

**Issue by dbk91** [webpack/webpack-dev-server#1011]
I was using create-react-app, which relies on webpack-dev-server to deliver content in development, and wanted to propose adding the requestCert configuration field. Client certificate authentication (2-way PKI) is a must have for an application I am working on. While I can get this working for production with Nginx as the proxy server, it would be really nice to have the same or similar behavior for development. In order to do so, I believe webpack-dev-server would have to support the requestCert field as an https option so that it could grab the client's certificate for authentication.

If this would be an unnecessary feature due to the fact that http-proxy-middleware already supports this, please let me know. I have yet to find a way to get it working by means of passing configuration to http-proxy-middleware.

Here are the changes in my forked repository: https://github.com/webpack/webpack-dev-server/compare/master...dbk91:request_cert_support

Thanks!

**Comment by shellscape** [comment]
We'd happily review a pull request to add this feature.
