### ISSUE TITLE
refresh 404s when using package.json proxy settings

### ISSUE THREAD

**Issue by drewwells** [webpack/webpack-dev-server#1013]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
1. setup a proxy configuration in package.json

```
  "proxy": {
    "/api": {
      "target": "http://localhost:8000"
    }
```

2. load up a page other than root ie. localhost:3000/settings, it will 404
3. Remove proxy configuration, localhost:3000/settings can be loaded directly

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
With the proxy configuration, we should be able to hit paths other than root directly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

**Comment by shellscape** [comment]
Closing as issue is 90 days stale without activity.
