### ISSUE TITLE
You are not working at webpack@3.3.0+

### ISSUE THREAD

**Issue by donggw2030521** [webpack/webpack-dev-server#1015]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

**Comment by asborisov** [comment]
webpack@3.4.1 + webpack-dev-server@2.6.1 work fine for me

**Comment by skipjack** [comment]
@donggw2030521 yeah works fine for me as well although I am seeing some issues when using v2.7.0 of this package. You may want to provide more details...

Will create a separate issue for the issues I'm seeing with 2.7.0.

**Comment by shellscape** [comment]
Closing for the following reasons:

* empty issue template
* confirmation that the module is working with webpack 3.3+
