### ISSUE TITLE
Bug: https + ws doesn't work at the dev server

### ISSUE THREAD

**Issue by pigareva** [webpack/webpack-dev-server#1016]
**Do you want to request a *feature* or report a *bug*?**

I think it's a bug

**What is the current behavior?**
I have the following error 
`WebSocket connection to 'wss://127.0.0.1:8083/rtu/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED`
Websocket does not work

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is my config: https://gist.github.com/pigareva/0ae61d127de6b6a22812b377e8c3e193 

**What is the expected behavior?**
I would like to have Hot Module Replacement for my app, where both types of requests, websocket and http, work. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
"webpack": "3.4.1",
 "webpack-dev-server": "2.6.1"
macOS Sierra 10.12.5

Many thanks!

**Comment by shellscape** [comment]
Since this was asked before we started enforcing the issue template question notice...

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

... we let this stay up here for discussion. However, we're going to close due to inactivity. Please do try StackOverflow or the Webpack Gitter.
