### ISSUE TITLE
No compatible version found: ip@^1.1.5

### ISSUE THREAD

**Issue by DamienLB** [webpack/webpack-dev-server#1022]
When installing webpack-dev-server@^2.5.0 I get the following error:
bug: No compatible version found: ip@^1.1.5

See messages from the npm error log below:

34648 error node v4.5.0
34649 error npm  v4.0.5
34650 error code ETARGET
34651 error notarget No compatible version found: ip@^1.1.5
34651 error notarget Valid install targets:
34651 error notarget 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
34652 error notarget This is most likely not a problem with npm itself.
34652 error notarget In most cases you or one of your dependencies are requesting
34652 error notarget a package version that doesn't exist.
34652 error notarget
34652 error notarget It was specified as a dependency of 'webpack-dev-server'

**Comment by shellscape** [comment]
2.5.0 is quite old. I'd guess that a fix for that branch probably won't get released if there is indeed an issue with that version of `ip`. I'd highly recommend upgrading to a newer version.

**Comment by DamienLB** [comment]
Isn't 2.7.1 the latest release for webpack-dev-server? If I am installing ^2.5.0 doesn't that include the latest minor release - which would be 2.7?

In any case, I just ran an install with "webpack-dev-server": "^2.7.0" and I received the same message that ip@^1.1.5 does not exist. (Which is odd b/c 1.1.5 appears to exist as the latest ip package release on npm - https://www.npmjs.com/package/ip)

37364 error Darwin 15.6.0
37365 error argv "/usr/local/bin/node" "/.npm-packages/bin/npm" "install"
37366 error node v4.5.0
37367 error npm  v4.0.5
37368 error code ETARGET
37369 error notarget No compatible version found: ip@^1.1.5
37369 error notarget Valid install targets:
37369 error notarget 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
37370 error notarget This is most likely not a problem with npm itself.
37370 error notarget In most cases you or one of your dependencies are requesting
37370 error notarget a package version that doesn't exist.
37370 error notarget
37370 error notarget It was specified as a dependency of 'webpack-dev-server'

**Comment by shellscape** [comment]
Yeah, I missed the caret. Not sure what would be causing that. Definitely not getting that error on this end. I see that you're on node 4.5.0. I just tried with 4.8.2 (npm 2.15.11), the latest in the 4.x branch, and all went well. Note that `package.json` does have:

```json
  "engines": {
    "node": ">=4.7"
  },
```

**Comment by DamienLB** [comment]
Thanks shellscape. I thought we had just a little while longer before we needed to do a major update to node/ npm, but we'll do it now to get it over with..
