### ISSUE TITLE
Version 2.7.0 no longer available on npm?

### ISSUE THREAD

**Issue by pinoniq** [webpack/webpack-dev-server#1033]
Hey,

We are using yarn with a lock-file. And before 2 days ago, the webpack-dev-server was locked to 2.7.0

That version is however no longer available/published on npm. It skips from 2.6.1 to 2.7.1.

Expected behavior: version's not dissappearing

Is this an issue with the npm registry?

**Comment by shellscape** [comment]
There's good reason for that: #1021.

2.7.0 contained a nasty regression and was unpublished. 2.7.1 was published _before_ the unpublish was performed. That sort of thing isn't uncommon when things go sideways with a release.
