### ISSUE TITLE
Error: Cannot find module '../lib/util/addDevServerEntrypoints'

### ISSUE THREAD

**Issue by IsmaelEzequiel** [webpack/webpack-dev-server#1035]
I'm trying to run webpacker with rails and when I try to run the command "./bin/webpack-dev-server" I receive this error... :/

19:03:11 web.1 | started with pid 29719
19:03:11 webpacker.1 | started with pid 29721
19:03:13 webpacker.1 | yarn run v0.27.5
19:03:14 webpacker.1 | $ "/vagrant/node_modules/.bin/webpack-dev-server" "--progress" "--color" "--config" "/vagrant/config/webpack/development.js"
19:03:15 webpacker.1 | module.js:487
19:03:15 webpacker.1 | throw err;
19:03:15 webpacker.1 | ^
19:03:15 webpacker.1 |
19:03:15 webpacker.1 | Error: Cannot find module '../lib/util/addDevServerEntrypoints'
19:03:15 webpacker.1 | at Function.Module._resolveFilename (module.js:485:15)
19:03:15 webpacker.1 | at Function.Module._load (module.js:437:25)
19:03:15 webpacker.1 | at Module.require (module.js:513:17)
19:03:15 webpacker.1 | at require (internal/module.js:11:18)
19:03:15 webpacker.1 | at Object. (/vagrant/node_modules/.bin/webpack-dev-server:9:33)
19:03:15 webpacker.1 | at Module._compile (module.js:569:30)
19:03:15 webpacker.1 | at Object.Module._extensions..js (module.js:580:10)
19:03:15 webpacker.1 | at Module.load (module.js:503:32)
19:03:15 webpacker.1 | at tryModuleLoad (module.js:466:12)
19:03:15 webpacker.1 | at Function.Module._load (module.js:458:3)
19:03:15 webpacker.1 | error Command failed with exit code 1.
19:03:15 webpacker.1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:03:16 webpacker.1 | exited with code 1
19:03:16 system | sending SIGTERM to all processes
19:03:16 web.1 | terminated by SIGTERM

**Comment by IsmaelEzequiel** [comment]
I solved this problem installing webpack-dev-server manually. XD

**Comment by sheldonoreilly** [comment]
Worked for me as well
