### ISSUE TITLE
New to React.js getting error like below

### ISSUE THREAD

**Issue by rajeesmca** [webpack/webpack-dev-server#1037]
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle monitor-dashboard@1.0.0~prestart: monitor-dashboard@1.0.0
6 silly lifecycle monitor-dashboard@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle monitor-dashboard@1.0.0~start: monitor-dashboard@1.0.0
8 verbose lifecycle monitor-dashboard@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle monitor-dashboard@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rperiasamy/node_dev/monitor-dashboard/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle monitor-dashboard@1.0.0~start: CWD: /Users/rperiasamy/node_dev/monitor-dashboard
11 silly lifecycle monitor-dashboard@1.0.0~start: Args: [ '-c', 'node node_modules/.bin/webpack-dev-server' ]
12 silly lifecycle monitor-dashboard@1.0.0~start: Returned: code: 255  signal: null
13 info lifecycle monitor-dashboard@1.0.0~start: Failed to exec start script
14 verbose stack Error: monitor-dashboard@1.0.0 start: `node node_modules/.bin/webpack-dev-server`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid monitor-dashboard@1.0.0
16 verbose cwd /Users/rperiasamy/node_dev/monitor-dashboard
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error monitor-dashboard@1.0.0 start: `node node_modules/.bin/webpack-dev-server`
22 error Exit status 255
23 error Failed at the monitor-dashboard@1.0.0 start script 'node node_modules/.bin/webpack-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the monitor-dashboard package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/.bin/webpack-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs monitor-dashboard
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls monitor-dashboard
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shellscape** [comment]
@rajeesmca Please note that issue templates usually aren't optional. removing their content is generally frowned upon. Unfortunately this issue will be closed citing the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.
