### ISSUE TITLE
clientLogLevel=none do not show errors as described in the docs

### ISSUE THREAD

**Issue by sapegin** [webpack/webpack-dev-server#1038]
**Do you want to request a *feature* or report a *bug*?**

Bug in webpack-dev-server or docs.

**What is the current behavior?**

Docs about `clientLogLevel` option say:

 > Note that the console will *always* show bundle errors and warnings. This option only effects the message before it.

Which is not how it works now. When clientLogLevel is `none` it doesn’t print anything when I make an error in one of source files when dev-server is running. It shows an error only when I refresh the page. `clientLogLevel=error` works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set clientLogLevel to `none`.
2. Make a typo in any source file.
3. See that nothing was printed to browser console.

**What is the expected behavior?**

Either print an error or don’t say in the docs that it will print an error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

webpack@3.5.3, webpack-dev-server@2.7.1

**Comment by shellscape** [comment]
Thank you for pointing this out. Please feel free to correct the documentation in a Pull Request by going to https://github.com/webpack/webpack.js.org/edit/master/content/configuration/dev-server.md

**Comment by sapegin** [comment]
Done: https://github.com/webpack/webpack.js.org/pull/1523

Closing this issue.
