### ISSUE TITLE
9090 is not listened

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack-dev-server#104]
According to the docs, assets will be served at `localghost: 9090`:
```js
output: {
    path: 'build',
    publicPath: 'http://localhost:9090/assets/',
    filename: '[name].js'
  },
```
http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server
But surprisingly I found my assets are actually at http://localhost:8080/assets/main.js ,

And when I update my code, there's logs in console saying:
```
[WDS] App updated. Recompiling... main.js:34
[WDS] App hot update... main.js:76
[HMR] Checking for updates on the server... main.js:163
GET http://localhost:9090/assets/061dc05016b75eca1400.hot-update.json net::ERR_ADDRESS_UNREACHABLE vendor.bundle.js:49
[HMR] Update check failed: Error: Manifest request to http://localhost:9090/assets/061dc05016b75eca1400.hot-update.json timed out. 
```
again, I found code here rather than at `localhost:9090`
```
http://localhost:8080/assets/061dc05016b75eca1400.hot-update.json
```

and the verison
```
➤➤ npm ls -g 
/usr/local/lib
├── webpack@1.5.3
└─┬ webpack-dev-server@1.7.0
  └── webpack@1.5.3
```

**Comment by jiyinyiyong** [comment]
Fixed by changing  port to `8080`:
```
publicPath: 'http://localhost:8080/assets/',
```
Still feeling change.. so it's not a bug, probably something a bit confusing...

**Comment by zzz6519003** [comment]
it work !
