### ISSUE TITLE
webpack-dev-server breaks on changing folder structure or renaming files and requires restart

### ISSUE THREAD

**Issue by ingelity** [webpack/webpack-dev-server#1040]
When I rename some file or change folder structure the webpack starts showing "...Module build failed: Error: ENOENT: no such file or directory,...", and it doesn't recover from that, so I have to restart webpack dev server in order to have the hot reloading working again. The documentation suggests explicitly setting watchOptions but didn't work. Is there some cache invalidation that I have to configure or...? I'm using webpack 3.3.0 and webpack-dev-server 2.6.1.

```
const devServer = new WebpackDevServer(webpack(webpackConfig), {
  hot: true,
  watchOptions: { poll: true },
  host: 'localhost',
  port: 9001,
  publicPath: 'http://localhost:9001/',
  compress: true,
  noInfo: true,
  stats: { colors: true, errorDetails: true },
  headers: { 'Access-Control-Allow-Origin': '*' },
  historyApiFallback: true,
});

devServer.listen(9001);
```
And this is webpack dev config:
```
const path = require('path');
const webpack = require('webpack');
const config = require('../config');

module.exports = {
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:9001',
    'webpack/hot/only-dev-server',
    path.join(config.projectPath, 'src', 'reactApp'),
  ],
  output: {
    path: path.join(config.projectPath, 'assets'),
    filename: 'bundle.js',
    publicPath: 'http://localhost:9001/',
  },
  devtool: 'cheap-module-eval-source-map',
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin({
      __DEV__: true,
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
    new webpack.ProvidePlugin({ Promise: 'bluebird' }),
  ],
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  module: {
    noParse: /node_modules\/aws-sdk\/dist\/aws-sdk/,
    rules: [...],
  },
};
```

**Comment by shellscape** [comment]
@ingelity removing issue templates is generally frowned upon, as they're usually required when opening a new issue.

we're going to begin enforcing a note that has been within the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

I'm sorry, but this will be closed. Please try the other two options for support.

**Comment by ingelity** [comment]
@shellscape  Ok, I can put it in issue templates if you prefer that form, but this still seems like a bug.
I asked the question on stackoverflow a few days ago but no one answered so far.
https://stackoverflow.com/questions/45634664/webpack-dev-server-breaks-on-changing-folder-structure-or-renaming-files-and-req

**Comment by shellscape** [comment]
I've never personally used a hot reload method that supported changing the file structure mid-stream. If that's a feature that you want to see happen, the first stop is the main webpack project's [HotModuleReplacementPlugin](https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js).

It's safe to assume that if you see an issue template in a repo, it's required and one should stick to the format in the template.
