### ISSUE TITLE
Overlay remains if warnings are present during HMR

### ISSUE THREAD

**Issue by gcangussu** [webpack/webpack-dev-server#1042]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
The error overlay doesn't disappear during the hot module replacement **if** there are warnings on the webpack compilation.

**If the current behavior is a bug, please provide the steps to reproduce.**
You need to configure HMR and to show overlays on errors only, then 

1. introduce a warning in your code (e.g. eslint's no-console with the eslint loader and Airbnb's preset). You should see the warning on the console but no overlay.
2. Introduce an error in your code. You should see the error in your console and in the overlay that appeared.
3. Remove the error from your code. The warning will appear on console, the error won't appear on console, but the **overlay won't disappear**.

My config is:
```javascript
devServer: {
  contentBase: false,
  overlay: {
    warnings: false,
    errors: true,
  },
  publicPath: '/',
  https: true,
  hot: true,
  hotOnly: true,
},
```

**What is the expected behavior?**
I expect the error overlay to disappear, like it does when no warning is present.

**Please mention your webpack and Operating System version.**
webpack 3.5.4
webpack-dev-server 2.7.1
Running on Ubuntu 16.04

**Comment by shellscape** [comment]
I think we're going to need a link to a simple app in a repo that we can use to reproduce this bug. In prelim tests I wasn't able to reproduce, so it could be something in your codebase specifically. If you can get a simple app going that reproduces this (so we're not chasing a goose of an issue caused by something custom), we can look into it further.

**Comment by gcangussu** [comment]
Sure @shellscape, should've done this from the beginning. Here it is https://github.com/gcangussu/webpack-overlay-bug/tree/master

See readme for detailed instructions of how I did to reproduce the error.

**Comment by shellscape** [comment]
@gcangussu this is an outstanding sample app and readme. thank you for putting that together, we'll have a look.

**Comment by shellscape** [comment]
@gcangussu confirmed that we have an issue here, I was able to reproduce the error using your example.
