### ISSUE TITLE
stats: 'errors-only' not working

### ISSUE THREAD

**Issue by MegaUITeam** [webpack/webpack-dev-server#1045]
```coffeescript
runWebpackDevServer = (html, script, build, port)->
	config = createWebpackConfig(html, script, build)
	config.entry.unshift('webpack/hot/dev-server')
	config.entry.unshift("webpack-dev-server/client?http://0.0.0.0:" + port)

	return new WebpackDevServer(webpack(config), {
		hot        : on
		# https    : on
		stats      : 'errors-only'
		publicPath : '/'
		contentBase: build
		stats: 'errors-only'
		noInfo     : on

	}).listen(port, '0.0.0.0')
```

but i have:

![image](https://user-images.githubusercontent.com/30184325/29343458-e46bea0c-8239-11e7-82ba-f6b64b8ea3d8.png)

how to
===
how i can disable logging on HMR and WDS?

**Comment by shellscape** [comment]
@MegaUITeam the issue templates are not optional and removing their content is generally frowned upon. from the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

As such, we'll be closing this issue. Please try one of the other outlets for your question.
