### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by jonhue** [webpack/webpack-dev-server#1048]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

```
Jonas@JONAS-PC /c/Sites
$ cd ~/app_name

Jonas@JONAS-PC ~/app_name
$ ./bin/webpack-dev-server

Jonas@JONAS-PC ~/app_name
yarn run v0.27.5
$ "c:\Users\Jonas\app_name\node_modules\.bin\webpack-dev-server" "--progress" "--color" "--config" "c:/Users/Jonas/app_name/config/webpack/development.js"
The filename, directory name, or volume label syntax is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ rails new app_name --webpack
$ cd app_name
$ ./bin/webpack-dev-server
```

**What is the expected behavior?**
No errors.

**Please mention your webpack and Operating System version.**
webpacker: 2.0
webpack: 3.5.5
Windows 10 latest updates

**Comment by shellscape** [comment]
Thanks for taking the time to open an issue. 

There's a lot of important information missing, however. Does the file exist? Have you tried executing that command that feedback suggests the file is missing for?

We've seen similar problems with webpacker and the rails env. I'd suggest debugging your installation locally and looking for the issue on your filesystem first and foremost. This isn't something we've seen with any frequency with webpack-dev-server independently.

We'll leave this open in the event that some edge case bugbear is responsible for this, but my money is on a user-specific environment issue of some kind.

**Comment by jonhue** [comment]
I did debug my local installation. But this happens to with the lastest Rails release as well as all my other installations. All files exist as they should. I spend an entire day debugging already before opening this issue.














From: Andrew Powell 


Sent: Sunday, August 20, 3:11 AM 


Subject: Re: [webpack/webpack-dev-server] The filename, directory name, or volume label syntax is incorrect. (#1048) 


To: webpack/webpack-dev-server 


Cc: Jonas Hübotter, Author 






Thanks for taking the time to open an issue. 


There's a lot of important information missing, however. Does the file exist? Have you tried executing that command that feedback suggests the file is missing for? 


We've seen similar problems with webpacker and the rails env. I'd suggest debugging your installation locally and looking for the issue on your filesystem first and foremost. This isn't something we've seen with any frequency with webpack-dev-server independently. 


We'll leave this open in the event that some edge case bugbear is responsible for this, but my money is on a user-specific environment issue of some kind.

**Comment by soundasleep** [comment]
This issue can also occur if you are running Yarn pre-1.0 on Windows. Make sure that `yarn -v` returns 1.0 or greater. See: https://github.com/yarnpkg/yarn/issues/3773

(If you installed Yarn on Windows through the MSI you'll need to reinstall Yarn [from the download site](https://yarnpkg.com/lang/en/docs/install/).)
