### ISSUE TITLE
Webpack Dev Configuration Does Not Inject Bundles into Sub-directory HTML Pages

### ISSUE THREAD

**Issue by chrisalexander55** [webpack/webpack-dev-server#1067]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug.

**What is the current behavior?**
So let me state that I have no issues when transpiling my production bundles, things are just fine. However, when using html-webpack-plugin with webpack-dev-server (with or without the HotModuleReplacementPlugin) only index.html has injected bundles. HTML docs in pages/ have nothing injected. So, is this a html-webpack-plugin or webpack-dev-server or both (synergized) config issue even though I am using publicPath: '/' per [html-webpack-plugin issue 665](https://github.com/jantimon/html-webpack-plugin/issues/665) guidance where I originally reported the behavior?

**If the current behavior is a bug, please provide the steps to reproduce.**

The following gist are based on my personal [ecmapscript-sass-webpack-starter](https://github.com/chrisalexander55/ecmascript-sass-webpack-starter) repo:

[dev.common.config.js](https://gist.github.com/chrisalexander55/93580aeca84dae22c2928371d4c141d9)
[dev.config.js](https://gist.github.com/chrisalexander55/9f7fd363d67da32f0e89a6b4bcb4a70f)

**What is the expected behavior?**
Inspection of pages/*.html files should have the correct inject JS bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not applicable

**Please mention your webpack and Operating System version.**
Webpack 3.1.0
OSX, 10.12.6

**Comment by shellscape** [comment]
Interesting issue. I'd recommend putting a breakpoint in webpack-dev-server at the point at which it tells the `compiler` to compile, and examining what the options look like. My guess is that this is come kind of config collision, overwrite, or in-process modification. If everything looks good there, this could just be a WDS limitation that we haven't run into before.

**Comment by chrisalexander55** [comment]
@shellscape 

I moved excessive stater/boilerplate <head> comments from HTML docs and all works as expected. This appears to be an issue with html-webpack-plugin rather than webpack-dev-server or some sort of synergized defect. Closing this issue. Thanks for looking into this.

**Comment by shellscape** [comment]
@chrisalexander55 hey thanks for taking the time to investigate it, I'm really glad you were able to resolve it and I'm sure this will help out other folks in the future.
