### ISSUE TITLE
Add option for providing own SSL certificate 

### ISSUE THREAD

**Issue by pstoica** [webpack/webpack-dev-server#107]
Right now it's hardcoded to use the self-signed one in the repo. Would be nice to easily swap that out.

**Comment by jasonkenneth** [comment]
I hate to reopen the discussion, but we have a slightly different requirement. Basically, we're using a pfx file for the certs and slightly different options. And we need these https options in three different places: the main web server, webpack-dev-server, and livereload. 

One option to support this would be to behave [like livereload](https://github.com/napcs/node-livereload/blob/master/lib/livereload.js#L207-L211) and pass-thru the https options. Webpack-dev-server could then supply a couple of defaults folks could use:

`new Server(webpack(config), {https: Server.defaultHttps})`;


Another option is to look for a property on the https options called something like 'overrideDefault' to signal a need to override all https options:
[like so](https://github.com/webpack/webpack-dev-server/compare/master...jasonkenneth:186c7fe).
