### ISSUE TITLE
webpack-dev-server Inline mode on CLI hot module reload page will refresh for change dom

### ISSUE THREAD

**Issue by ymqy** [webpack/webpack-dev-server#1071]
**Do you want to request a *feature* or report a *bug*?**

-No
**What is the current behavior?**
-When I change dom, page will refresh, but change css, hmr works, page not refresh, will hot replacement.
**If the current behavior is a bug, please provide the steps to reproduce.**

-not bug
**What is the expected behavior?**
I want the page will not refresh instead of hot replacement when i change dom
**If this is a feature request, what is motivation or use case for changing the behavior?**
-no 
**Please mention your webpack and Operating System version.**
global webpack version 3.3.0
Mac OS  10.11.6

this is my `package.json` file:
```
{
  "name": "demo-hmr",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --hot --inline webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "css-loader": "^0.28.7",
    "style-loader": "^0.18.2",
    "webpack": "^3.5.6",
    "webpack-dev-server": "^2.7.1"
  }
}
```
this is my `webpack.config.js` file:
```
module.exports = {
  entry: './main.js',
  output: {
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      }
    ]
  }
}
```
this is my `main.js` file:
I change dom in this file, just change innerHTML of divv, then page will refresh, not i want for.
```
import app from './app.css'

var divv = document.createElement('div')
divv.innerHTML = "Hello webpack"
document.body.appendChild(divv)
```
this is my `app.css` file:
```
body {
	background-color: yellow;
}
```
this is my `index.html` file:
```
<html>
	<body>
	  <h1>Hello World!</h1>
    <script type="text/javascript" src="bundle.js"></script>
	</body>
</html>
```

sorry about my simple question and my terrible english.

**Comment by ymqy** [comment]
![image](https://user-images.githubusercontent.com/22427967/30149655-03f4ad3e-93db-11e7-9789-119e6f37a513.png)
this is my directory

**Comment by shellscape** [comment]
@ymqy I'm sorry, but issues are only for reporting bugs or requesting features. they're not for support. please see the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed

Closing as a question.
