### ISSUE TITLE
_stats.toJson() invoked on every xhr-streaming request and blocks event loop

### ISSUE THREAD

**Issue by apkrasny** [webpack/webpack-dev-server#1072]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When SockJS falls back to xhr-streaming the [sockServer connection callback](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L502) is fired for every poll request. This callback invokes stats.toJson() which can be a lengthy operation in projects with a large amount of modules. I measured this function to take over 500ms on my configuration with 50 entry points and 500+ files and debug enabled. This blocks the server's event loop and causes all requests to be very slow. Using proxy functionality of webpack-dev-server only exacerbates the issue as all requests end up taking over 2 seconds.

**If the current behavior is a bug, please provide the steps to reproduce.**
Disable or block websockets in the browser and watch how the connection handler is invoked on every request. I did this by simply setting `WebSockets = undefined` at the very top of my html file.

**What is the expected behavior?**
It looks like the Session object on the connection has a `session_id` field which is persistent across requests. If a polling fallback is used then it makes sense to only send stats once per session id. This may also be a bug in SockJS because it doesn't make sense for the `connection` event to be emitted on every request, but since it has session information I'm not sure.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
webpack: 3.5.6
webpack-dev-server: 2.7.1
operation system: MacOS

**Comment by shellscape** [comment]
@apkrasny really appreciate you investigating and reporting this bug. it's definitely a problem we'd like to see fixed. for v3 of this module, we're going to be replacing sockjs with a native solution, which will hopefully circumvent this problem. we'd happily accept a temporary fix for the v2.8.x branch, but it likely won't see core team development, due to the afore mentioned work on sockets for v3.

**Comment by janosjanka** [comment]
Temporary workaround is to patch the socket.js:
\node_modules\webpack-dev-server\client\socket.js

```
sock = new SockJS(url);
sock._transportTimeout = function() {};
```

**Comment by shellscape** [comment]
Closing as abandoned after 30 days stale.
