### ISSUE TITLE
Trigger a manual page refresh on a WebpackDevServer instance

### ISSUE THREAD

**Issue by MarlBurroW** [webpack/webpack-dev-server#1073]
Hello,

I'm working on a fullstack project with a NodeJs express backend.

In development mode, I would like the WebpackDevServer perform a simple refresh when I save a "pug/jade" template (these templates are not compiled by webpack, it's just served and rendered by express).

To summarize, I need this: 

```javascript
const compiler = webpack(config)
const server =  new WebpackDevServer(compiler, {...})

// Here I watch changes in my backend templates folder and want to 
// perform something like this when a template changes:

server.refresh() // Perform a simple page reload without run the webpack compilation
```
Is there a way to do this in the current version ?

Thanks

**Comment by MarlBurroW** [comment]
Ok found this reading the sources:

```javascript
 server._watch('./backend/views/**/*')
```
It's an internal method so probably not the "clean" way, but it does the job :)

**Comment by shellscape** [comment]
@MarlBurroW please note that when you see an issue template, it's typically required. be cool and fill it out in the future please. our template states:
> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

Closing as question
