### ISSUE TITLE
Route name's with a trailing slash makes dev server serve static files with the route name prepended

### ISSUE THREAD

**Issue by geeofree** [webpack/webpack-dev-server#1074]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Trailing slashes on some route name makes dev server serve static files along with the given route name.

**No trailing slash**
![webpack-working](https://user-images.githubusercontent.com/17492631/30304062-2629a9b0-979e-11e7-9d20-c3c752e7667b.png)

**With trailing slash**
![webpack-fail](https://user-images.githubusercontent.com/17492631/30304080-472472b2-979e-11e7-99b1-a52b9e723780.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

I am simply just using React Router along with webpack-dev-server with historyApiFallback turned on and was trying to make a component route have a dynamic url name path which I could not make a GET request onto because of the aforementioned issue. [My webpack config and a snippet of my package.json](https://gist.github.com/geeofree/3b6ce0634b7488f7cbbd6fcd873eb2f9)

**What is the expected behavior?**
Trailing slash on dev server should not serve the static files with a prepended route name

**Please mention your webpack and Operating System version.**
**Webpack**: v3.5.6
**OS**: Ubuntu 16.04LTS

**Comment by fumblehool** [comment]
@shellscape I would like to work on this. Is anyone currently working on this?

**Comment by shellscape** [comment]
@fumblehool not to my knowledge, please do give it a go

**Comment by shellscape** [comment]
@geeofree @fumblehool this issue is now past the 30 day stale marker. if it doesn't see any additional activity we'll be closing soon.

**Comment by fumblehool** [comment]
@shellscape I've followed the steps to reproduce this issue but It is working fine on my machine.

**Comment by geeofree** [comment]
@shellscape  Hello! Sorry for replying just now, I've actually forgotten about this issue and have actually moved on from this after a week or so of publishing this. Uhm, I don't really have that much info to give and don't know what info to give even to help with the issue, so I think I'd be okay with it being closed. Thanks for trying to help though @fumblehool!

**Comment by yackSpillsaps** [comment]
I believe I was having this problem. It was solved by adding `publicPath: '/'` to the `output` configuration.
