### ISSUE TITLE
When I change file, Webpack reloads page before server starts.

### ISSUE THREAD

**Issue by Develofrog** [webpack/webpack-dev-server#1077]
```
-> Recompiling...

...
webpack: Compiled successfully.

-> Page Reloaded.

[HPM] Error occurred while trying to proxy request ... (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request ... (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request ... (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request ... (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request ... (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[19:39:28] [HPM] Proxy created:...
[19:39:28] [HPM] Proxy created: ...
[19:39:28] [HPM] Proxy created:...
[19:39:28] [HPM] Proxy rewrite rule created: ...
[19:39:28] The server is running at ...

-> Server is on.
```

So Page changes to `Error occured while trying to proxy to: localhost:3001/page-1` instead of new same page.

![screen shot 2017-09-13 at 8 12 42 pm](https://user-images.githubusercontent.com/23724355/30374451-f7cb4128-98bf-11e7-9a9b-08b1762cdb75.png)

How can I control reload event after server starts?

**Comment by shellscape** [comment]
hey there. please note that if you see an issue template, it's probably not optional. ours falls into that category and we ask everyone to fill it out. we also close general questions, which this issue is. from the issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

Closing as question. Please try one of the other outlets listed above for your question.
