### ISSUE TITLE
Don't you let a console.log in the latest 2.8.0 version?

### ISSUE THREAD

**Issue by kud** [webpack/webpack-dev-server#1078]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/655838/30391355-57a01760-98b9-11e7-9b2a-57f37f120618.png">

(didn't happen in the previous one)

It hapens everytime I restart the website in my browser.

**Comment by shellscape** [comment]
@kud Looks like it. We'll take a look at the linting rules, as it should have caught this.

Please please please use the issue template in the future. We ask that everyone does.

**Comment by kud** [comment]
Yes. Sorry. :)

**Comment by shellscape** [comment]
No worries at all. I have a fix ready to go for that. Waiting to see what else folks report for 2.8.0 before I push a patch.
