### ISSUE TITLE
Getting sockjs-node connection errors in console with v2.8.0

### ISSUE THREAD

**Issue by tardis10** [webpack/webpack-dev-server#1081]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using v2.8.0 I get a long list of http://localhost/sockjs-node/info?t=1505327195079 404 (Not Found) messages in the console, and reloading on changes no longer works.  I am running this on port 16384 which appears to be the issue.  On v2.7.1 the port number is correctly specified as in: http://localhost:16384/sockjs-node/info?t=1505327195079.  No other modules need to be altered.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply switching between v2.8.0 and v2.7.1 shows the issue.

**What is the expected behavior?**
Correct port number should be specified.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
webpack 3.5.6
Linux Mint 17.2
Chrome 61

**Comment by shellscape** [comment]
Thanks for the report. This issue is being tracked here: #1079
