### ISSUE TITLE
新版本2.8.1 在window上运行缺少各种依赖

### ISSUE THREAD

**Issue by bohaochen** [webpack/webpack-dev-server#1083]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**

**Comment by shellscape** [comment]
@bohaochen I'm sorry, but this is a valid issue. Please try again using the issue template.
