### ISSUE TITLE
Failed at the webpack-demo@1.0.0 start script 'webpack-dev-server --open'.

### ISSUE THREAD

**Issue by gin93r** [webpack/webpack-dev-server#1085]
Just following the guide.

Windows 10.
Node v6.11.1

I did come across [this post](https://github.com/webpack/webpack-dev-server/issues/706) which did end up working for me, though I thought calling it directly was supposed to work for v7 rather than v6.

Though it only works from the command line, not from the package.json file.

Scripts section of `package.json`
```
"scripts": {
    "start": "http-server",
    "watch": "webpack --progress --watch",
    "start": "webpack-dev-server --open",
    "build": "webpack"
  },
```

`webpack.config.js`
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
	entry: {
		app: './src/index.js',
		print: './src/print.js'
	},
	output: {
		filename: '[name].bundle.js',
		path: path.resolve(__dirname, 'dist')
	},
	devServer: {
		contentBase: './dist',
	},
	plugins: [
		new CleanWebpackPlugin(['dist']),
		new HtmlWebpackPlugin({
			title: 'Output Management'
		})
	],
	devtool: 'inline-source-map'
}
```

**Comment by shellscape** [comment]
@gin93r thanks for creating an issue, however when you see an issue template, that usually means they aren't optional and you should fill it out/in, rather than removing its contents. also from our issue template:

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed. 

Closing as question. Please try one of the other two suggested outlets for support.

**Comment by gin93r** [comment]
@shellscape Whoops. Sorry about that. I'll ask around SO and Gitter first, but all of my research thusfar has been fruitless.
