### ISSUE TITLE
yargs "Too many arguments" with v2.8.x

### ISSUE THREAD

**Issue by deedubbu** [webpack/webpack-dev-server#1087]
* Operating System: MacOS 10.12.6
* Node Version: v7.10.0
* NPM Version: 4.2.0
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.8.0 and 2.8.1

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

Sample code [here](https://gist.github.com/deedubbu/0c898f79a0808a6be9d8698624c2065b)

### Expected Behavior
The dev server should start cleanly.

### Actual Behavior

Startup of the webpack-dev-server is producing the following error:

```
YError: Too many arguments provided. Expected max 2 but received 3.
    at module.exports (.../node_modules/webpack-dev-server/node_modules/yargs/lib/argsert.js:31:13)
    at Object.Yargs.self.alias (.../node_modules/webpack-dev-server/node_modules/yargs/yargs.js:244:5)
    at module.exports (.../node_modules/webpack/bin/config-yargs.js:12:4)
    at Object.<anonymous> (.../node_modules/webpack-dev-server/bin/webpack-dev-server.js:56:36)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```
I'm guessing the yargs bump from `^6.0.0` to `^8.0.2` [here](https://github.com/webpack/webpack-dev-server/commit/69239ce854dd0a4bdb752fbd78c47c348aa9f900#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R66) caused this regression.

### How can we reproduce the behavior?

1. Download files from [gist](https://gist.github.com/deedubbu/0c898f79a0808a6be9d8698624c2065b)
2. `npm install`
3. `npm build`
4. `npm start`
5. See error in terminal

I understand that updating to webpack `3.5.x` would resolve this but I feel this was an unnecessary breaking change.

**Comment by shellscape** [comment]
@deedubbu could you explain in more verbose detail why you believe that yargs and a dependency on webpack@3.5.x is breaking this?

**Comment by PatrickMcGrath29** [comment]
Also getting this behavior

**Comment by shellscape** [comment]
@PatrickMcGrath29 please avoid "me as well" replies on issues. rather, please use the reaction buttons on the OP https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by shellscape** [comment]
We discussed it and will downgrade for the next patch release. However, it's important to note that webpack-dev-server v3 will leverage webpack@3.

**Comment by deedubbu** [comment]
Do you know a timeframe for the next patch release?

The code I posted was just a minimal scenario and not my actual app. The `package.json` uses a `>=` range for the node engine version. As indicated in the issue, I'm currently using `v7.10.0` locally but am using the LTS of `v6.11.3` in production for the real app. For this issue the version of node is irrelevant.

**Comment by deedubbu** [comment]
I see 2.8.2 was released. Fixes the issue. Thanks! 👍
