### ISSUE TITLE
Option to console.log only important stuff

### ISSUE THREAD

**Issue by steida** [webpack/webpack-dev-server#109]
It is planned or should I send PR?

We don't care about these messages:
```
[HMR] Waiting for update signal from WDS...
client:14 [WDS] Hot Module Replacement enabled.
```

There should be an option (default) to log only warnings and errors.

**Comment by maxdow** [comment]
+1

**Comment by smussell** [comment]
I agree the following are not useful logs and they are cluttering up my console making it more difficult to sort through and find my own logs.

```` 
[WDS] App updated. Recompiling...
[WDS] Nothing changed.
````

There should be some way for me to disable these logs.  This same issue was filed on the react-hot-loader, but it is apparently a webpack issue.

**Comment by elektronik2k5** [comment]
+1

**Comment by fusepilot** [comment]
Would like this option as well. The logs are a bit verbose after everything is setup correctly.

**Comment by luisrudge** [comment]
:+1:

**Comment by FlorentD** [comment]
+1 as well

**Comment by dalhundal** [comment]
As a very messy temporary work around, I have a script, `development.js` which i conditionally append to the `entry` in `webpack.config.js`.

````
"use strict";

// This is a workaround used alongside the webpack-dev-server hot-module-reload feature
//  - it's quite chatty on the console, and there's no currently no configuration option
//    to silence it. Only used in development.
// Prevent messages starting with [HMR] or [WDS] from being printed to the console
(function(global) {
    var console_log = global.console.log
    global.console.log = function() {
        if (!(
            arguments.length == 1 &&
            typeof arguments[0] === 'string' &&
            arguments[0].match(/^\[(HMR|WDS)\]/)
        )) {
            console_log.apply(global.console,arguments)
        }
    }
})(window)
````

It overloads `console.log` - skipping any messages starting with `[HMR]` or `[WDS]`

**Comment by SpaceK33z** [comment]
Can you guys check if PR #579 works for you?

**Comment by SpaceK33z** [comment]
PR #579 was merged, check that out for more info. Note that it hasn't been released yet.

**Comment by SpaceK33z** [comment]
Released in `2.1.0-beta.3`.

**Comment by ibrahima** [comment]
Quick question, I see that this was merged and is in v1.16, and seems to remove the [WDS] logs, but I still see `[HMR] Waiting for update signal from WDS...` in my console. Is there a different setting for HMR?

**Comment by lgdexter** [comment]
Thanks for this @SpaceK33z

**Comment by felipenmoura** [comment]
Hi
Out of nothing, I started seeing these messages in my terminal every time I update a file:

```
webpack built c6aa9a16a68277967229 in 3390ms
webpack built 3fdedc302da408daa8dd in 341ms
```

I narrowed it down to realize it only happens when I have `webpackHotMiddleware` enabled, even if I have `noInfo: true, quiet: true` set.

Any idea?

**Comment by alexeypetrushin** [comment]
Same issue, still see the logs with `noInfo: true, quiet: true`

**Comment by alexeypetrushin** [comment]
Also, you need to patch `info` also, the hack

```
(function(console) {
        ['log' | 'info'].forEach(function(name) {
            var original = console[name]
            console[name] = function() {
              if (!(
                  arguments.length == 1 &&
                  typeof arguments[0] === 'string' &&
                  arguments[0].match(/^\[(HMR|WDS)\]/)
              )) original.apply(console, arguments)
            }
        })
      })(window.console)
```

**Comment by alansutherland** [comment]
Thought it was bad form to leave console.log() lines in your production code...
