### ISSUE TITLE
Const causing IE9 bundle to break.

### ISSUE THREAD

**Issue by syte** [webpack/webpack-dev-server#1091]
* Operating System: Windows 10
* Node Version: 4.3.1
* NPM Version: 5.0.3
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.8.1

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code
Const in https://github.com/webpack/webpack-dev-server/blob/master/client/index.js is breaking IE9. Const is unsupported in ie9. It seems like the error was introduced here: https://github.com/webpack/webpack-dev-server/commit/69239ce854dd0a4bdb752fbd78c47c348aa9f900#diff-895656aeaccff5d7c0f56a113ede9662

### Expected Behavior
Const shouldn't be used
### Actual Behavior
Const is being used and breaking IE9.
### For Bugs; How can we reproduce the behavior?
Running a bare config using webpack-dev-server with hot reloading.

**Comment by teod** [comment]
It breaks IE11 as well.

**Comment by shellscape** [comment]
@syte old-IE support ended in January 2016. Please see https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support. Unfortunately you'll have to use an older version (2.7) if you'd like to continue to support old IE. Old IE support has been discontinued for so long that this can't be considered a breaking change, rather just catching up with the times.

@teod Hm I think you're mistaken on `const` breaking IE11. Please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

This isn't one we're going to be fixing I'm afraid. For those that still need to run this on old IE, you'll have to set your dependencies to 2.7.1.

**Comment by srgpqt** [comment]
`const` breaks iOS 9 too.
