### ISSUE TITLE
'open' option in Node.js API

### ISSUE THREAD

**Issue by wesleymostien** [webpack/webpack-dev-server#1092]
* Operating System: OS X 10.11.6
* Node Version: 8.4.0
* NPM Version: 5.4.2
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.8.2

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code
```js
  // webpack.config.js
...
const WebpackDevServer = require('webpack-dev-server')
const config = require('./webpack.config.js')
const compiler = webpack(config)
const server = new WebpackDevServer(
  compiler, {
    open: true
  }
)
...
```
### Expected Behavior
open the browser (like CLI option)

### Actual Behavior
nothing happens

### For Features; What is the motivation and/or use-case for the feature?
is it possible to do this currently ? Can't find out how.

**Comment by shellscape** [comment]
Thanks for the feature request! This is fairly easily accomplished in your local project by examining the source for `bin/webpack-dev-server.js`.

[Line 486](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L486) demonstrates how to use the [opn module](https://www.npmjs.com/package/opn) to open a specified URL. Given that webpack-dev-server runs on port 8080 by default, or that you'll know the port that you're specifying in `webpack.config.js`, you should be able to open the url with ease using the same method. Build this into a reusable file in your tooling, or as a one-off inside of the file that launches webpack-dev-server via the API.

But unfortunately, given the ease by which folks can add this to their tooling, this isn't a feature that we're going to expand the API with.

**Comment by wesleymostien** [comment]
ok thanks for the update. btw using webpack-browser-plugin will do the trick easily.
