### ISSUE TITLE
No Node.js 4 support

### ISSUE THREAD

**Issue by ai** [webpack/webpack-dev-server#1100]
* Operating System: Linux
* Node Version: 4.8.3
* NPM Version: 2.15.11
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.8.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

(Travis CI build)[https://travis-ci.org/ai/nanoid/jobs/276267022]

### Expected Behavior

`yarn install` is finished without errors.

### Actual Behavior

```
$ yarn
error internal-ip@2.0.2: The engine "node" is incompatible with this module. Expected version ">=6".
```

### For Bugs; How can we reproduce the behavior?

Run `yarn install` on Node.js 4.

**Comment by ai** [comment]
### Notes

1. Node.js 4 is still [Maintenance LTS](https://github.com/nodejs/LTS)
2. Errors happen because `webpack-dev-server` has `internal-ip` in dependencies.
3. `webpack-dev-server` supports `"node": ">=4.7"`.
4. @sindresorhus [recommended downgrading](https://github.com/sindresorhus/internal-ip/issues/12) `internal-ip` for all Node.js 4 users.

**Comment by shellscape** [comment]
@ai I see that internal-ip 2.0.3 supports Node 4 now. that mean we're good on this issue?

**Comment by ai** [comment]
Yea[pp. I tested 2.0.3 and everything is fine right now.
