### ISSUE TITLE
Webpack Dev Server No Longer Runs On Older Browsers

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack-dev-server#1105]
* Operating System: Mac Sierra
* Node Version: 8.5
* NPM Version: 5.4.2 (But I use yarn 1.0.2)
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.8.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code

```js
  // webpack.config.js
  anything will have this issue as long as you run webpack dev server
```

### Expected Behavior
I can run my dev server in chrome 30, the latest browser supported on an old tablet that I'm trying to support, the samsung tab 4

### Actual Behavior
It crashes with `Uncaught SyntaxError: Use of const in strict mode.`

### For Bugs; How can we reproduce the behavior?
Run webpack dev server on chrome 30.

I believe the issue originated with this PR https://github.com/webpack/webpack-dev-server/pull/1058, because the const that causes the error is in https://github.com/webpack/webpack-dev-server/blob/master/client/index.js

**Comment by shellscape** [comment]
@bdwain thanks for creating an issue. buuuuuut please do try searching the issues (or if you have, maybe a few different terms) before hand. we've had a few issues on this already (#1091), and I closed one today (#1104) 😄 

Please see those issues for an explanation, but unfortunately supporting really old/behind browsers isn't in the cards.

**Comment by shellscape** [comment]
Providing a transpiled version of the script would imply support for older browsers, I'm afraid. Chrome 30 was **_released in 2014_** and is a full [30 versions](http://caniuse.com/#feat=const) behind the latest release. webpack-dev-server being a _development_ tool, it's completely reasonable that we support a variety of recent browsers, and move on from the very old versions. I apologize if this causes you issues with your testing, but please do consider a different vector for testing with webpack/webpack-dev-server on very old browsers.

**Comment by lkiarest** [comment]
From product feedbacks we got, several browsers of android phone are still using very old version, they even don't support 'let/const' identifier now.

**Comment by shellscape** [comment]
@lkiarest unfortunately you'll have to use a pre-v2.8.0 version of the module to test on unsupported browsers.

**Comment by mrdulin** [comment]
save issue. 
`SyntaxError: Use of const in strict mode.`


I fallback `webpack-dev-server` from `^2.9.1` to `^2.7.1`.
The error gone.

**Comment by shellscape** [comment]
@mrdulin this is already documented on the README and at webpack.js.org. Also, please do not post "me too" replies on an issue.
