### ISSUE TITLE
console.log() left in lib/Server.js

### ISSUE THREAD

**Issue by harryfino** [webpack/webpack-dev-server#1106]
* Operating System: Mac OS 10.12.6
* Node Version: 8.5.0
* NPM Version: 5.4.1
* webpack Version: 3.5.6
* webpack-dev-server Version: 2.8.0

- [ ] This is a **feature** request
- [X] This is a **bug**

### Code

Errant log message in lib/Server.js added during pull-request #1060.
![image](https://user-images.githubusercontent.com/1643512/30613871-9556a4d2-9d57-11e7-884b-089795313834.png)

### Expected Behavior

The console.log() line that outputs "connection.remotePort" to the command line would be configurable, listen to "noInfo" flag in webpack.config.js, or not be output at all.

### Actual Behavior

Every connection causes a command line console output of "connection.remotePort" with the port number and there is no way to get rid of it.

### For Bugs; How can we reproduce the behavior?

Call `webpack-dev-server --open` to start the server and make a connection in your browser. When your browser connects, the message will appear in the command line output.

**Comment by shellscape** [comment]
@harryfino thanks for checking in. that was cleaned up and you'll find it removed in 2.8.2. I'd recommend adding a tool like [david](https://www.npmjs.com/package/david) to your build process to alert you of newer versions of modules. It's also a good idea to search a repo for a keyword; searching for `remotePort` yields no results, meaning that it was already removed 😉  The "Blame" function on a file is also a great way to see when something was added, and in this case removed.
