### ISSUE TITLE
TypeError: this.hostname.indexOf is not a function

### ISSUE THREAD

**Issue by penggy** [webpack/webpack-dev-server#1109]
* Operating System: Windows7
* Node Version: 6.10.0
* NPM Version: 5.3.0
* webpack Version: 3.5.3
* webpack-dev-server Version: 2.8.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### devServer config

```js
    devServer: {
        host: '0.0.0.0',
        useLocalIp: true,
        open: true,
        openPage: "",
        proxy: {
            "*": {
                target: 'http://localhost:10011/',
                secure: false
            }
        }
    }
```
### the error report 
![image](https://user-images.githubusercontent.com/4045867/30634579-29f5cc1a-9e22-11e7-8bca-7621d54720ed.png)

I found this at version 2.8.2 and then found webpack-dev-server version > 2.7.1 have this problem.

Now, I rollback to 2.7.1 , it works fine.

**Comment by shellscape** [comment]
@penggy what's the command you're using to launch webpack-dev-server from the command line?

**Comment by penggy** [comment]
@shellscape the command is 

`npm run start` 

the script in package.json is 

`"start": "cross-env NODE_ENV=development webpack-dev-server"`

if set `useLocalIp: false` error info disappear

**Comment by shellscape** [comment]
This is another errant package update from the cleanup effort I'm afraid. We definitely need some better testing around the different options. I'll push a commit to change the `internal-ip` dependency back to 1.2.0, which is the module update that broke this option.

**Comment by paztis** [comment]
In version 1.2.0, internalIp.v4() was returning the ip.
In version 2.0.0, internalIp.v4() returns a Promise. That's not the same at all.

It fails during: `const hostname = options.useLocalIp ? internalIp.v4() : options.host;` in createDomain.js

**Comment by shellscape** [comment]
@paztis much appreciate the extra hand there, but per previous comments and the referenced commit in the issue, we identified the issue with this and there has been a commit pushed. versions are released when we're able to. please feel free to reference the git repo directly in your package.json in the meantime

**Comment by infantito** [comment]
I have the same trouble. 👎 

![image](https://user-images.githubusercontent.com/9045302/30881571-e2d45c94-a2cb-11e7-8ff4-eda753712e26.png)

**Comment by shellscape** [comment]
@infantito please avoid posting "me too" or "same" replies on an issue, especially once it's been addressed. instead, you can add reactions to the original post for the issue https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
