### ISSUE TITLE
Getting `Uncaught NotFoundError` when hitting `React.render` after fetching external resource

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-dev-server#111]
I have a setup like this (simplified but still reproducible):

**index.js**

```javascript
var React = require('react');
var Router = require('react-router');

var routes = require('./routes.jsx');


routes().then(function(routeDefinition) {
    React.render(<div>hello</div>, document.body);
}).catch(function(res) {
    console.error(res);
});
```

**routes.jsx**

```jsx
'use strict';

var React = require('react');
var Promise = require('es6-promise').Promise;

var url = 'http://localhost:3000'; // TODO: move this to configuration
var api = require('./api');


module.exports = function() {
    return new Promise(function(resolve, reject) {
        api(url).then(function(api) {
            resolve();
        }).catch(function(res) {
            reject(res);
        });
    });
};
```

***api.js**

```javascript
var Promise = require('es6-promise').Promise;
var axios = require('axios');


module.exports = function(url) {
    return new Promise(function(resolve, reject) {
        axios.get(url + '/v1/schema').then(function() {
            resolve();
        }).catch(function(res) {
            reject(res);
        });
    });
};
```

As you can see I hit an external API before I render anything. The full code constructs an API based on an external resource but it seems it is possible to trigger the glitch only by doing that call to an external API.

A setup like this yields `socket.io.js:2695 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`.

If I get rid of the call to an external API, the error goes away. Any idea what might be causing the problem? Could it have to do something with the fact that both resources are at `localhost`? How could that mess up `socket.io`? Is there a way to run the dev server that gives more debug info?

If you want to see the issue in action, check out [koodilehto-crm-frontend](https://github.com/koodilehto/koodilehto-crm-frontend/tree/v0.1.0). You'll also need [a backend](https://github.com/koodilehto/koodilehto-crm-backend) to run against.

**Comment by SpaceK33z** [comment]
Hey @bebraw! Do you still have this issue? We don't use socket.io anymore, so perhaps that fixed the issue? Glad to help if you still have it.

**Comment by bebraw** [comment]
Yeah, it has been too long since I opened this issue. Better close. I'll re-open if this comes around again.
