### ISSUE TITLE
Webpack-dev-server reloads on every save.

### ISSUE THREAD

**Issue by Arpit1294** [webpack/webpack-dev-server#1112]
* Operating System: Linux 16.04
* Node Version: 8.1.2
* NPM Version: 5.0.3
* webpack Version: 3.6
* webpack-dev-server Version: 2.8.2

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code
```js
  // webpack.config.js
const path = require("path");

const webpack = require("webpack");
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var BUILD_DIR = path.resolve(__dirname, "dist");
var APP_DIR = path.resolve(__dirname, "src");

const VENDOR_LIBS = [
  "lodash",
  "react",
  "react-dom",
  "react-router",
  "react-redux",
  "redux",
  "redux-form"
];

const HtmlWebpackPlugin = require("html-webpack-plugin");

const config = {
  entry: {
    bundle: APP_DIR + "/index.js",
    vendor: VENDOR_LIBS
  },
  output: {
    path: BUILD_DIR,
    filename: "js/[name].[hash].js"
  },
  resolve: {
    modules: [path.resolve("./src"), path.resolve("./node_modules")]
  },
  module: {
    rules: [
      {
        use: "babel-loader",
        test: /\.js$/,
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ["css-loader", "postcss-loader", "sass-loader"]
        })
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("css/styles.[hash].css"),
    new webpack.optimize.CommonsChunkPlugin({
      name: ["vendor", "manifest"]
    }),
    new HtmlWebpackPlugin({
      template: "src/templates/index.html"
    })
  ]
};

module.exports = config;
```

### Expected Behavior
On every save action the whole page reloads even if I didn't have made any changes to the file. The page should not reload if I haven't explicitly mentioned it in my script.

### Actual Behavior
The browser reloads.

**Comment by shellscape** [comment]
@Arpit1294 thanks for opening an issue. 

> The page should not reload if I haven't explicitly mentioned it in my script.

I'm afraid I don't know what you mean by that. Can you elaborate?

We're also going to need a simple sample repo that reproduces your issue to triage.

**Comment by Arpit1294** [comment]
https://github.com/Arpit1294/React-Redux-Boiler-Plate 
I have updated my comment and this is my repo. 
My question is that why does the browser refreshes my app on save even when I haven't made any changes in the files?

**Comment by shellscape** [comment]
> My question is that why does the browser refreshes my app on save even when I haven't made any changes in the files?

I'm still not sure what you're saying there. You're saying that you're saving the file, but there aren't any changes to a file? That's a bit contradictory.

My suggestion for you would be to start with one of our examples, and slowly add bits of your app to the example, checking to make sure it works along the way. That'll probably reveal where in your app the issue lies. 

I'll keep this open for a bit longer in the event it reveals an actual bug in webpack-dev-server, but this sounds a lot like a config issue and a general support question.

**Comment by Arpit1294** [comment]
ok I did the same using webpack 2.2 and everything was okay the problem is observed in 3.6. Even when nothing is changed the page refreshes when using webpack 3.6.

**Comment by shellscape** [comment]
That would suggest an issue with webpack versus webpack-dev-server

**Comment by Arpit1294** [comment]
Yes, Thanks for suggesting. Will look into it. Closing this issue.
