### ISSUE TITLE
How to run dev server in debug mode (which VScode)

### ISSUE THREAD

**Issue by wangxiexe** [webpack/webpack-dev-server#1114]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System:
MacOS
* Node Version:
8.1.3
* NPM Version:
5.3.0
* webpack Version: 
3.6.0
* webpack-dev-server Version:
2.7.0

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior
I want to start my dev server in debug mode and allow VScode to debug 
### Actual Behavior
I did not find any doc mentioning this.
### For Features; What is the motivation and/or use-case for the feature?
It would be great the debug the dev server so I can add new feature to it.

**Comment by Arpit1294** [comment]
Can you be more clear about your question?
Do you want to debug an app?

**Comment by shellscape** [comment]
@wangxiexe thanks for checking in. unfortunately it looks like you might have missed the little bit in our issue template that states:

> Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). General questions, how-to
questions, and support requests will be closed.

Closing as question
