### ISSUE TITLE
"Setup" is deprecated warning

### ISSUE THREAD

**Issue by jarodtaylor** [webpack/webpack-dev-server#1121]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: Mac OS 10.11.6
* Node Version: 8.2.1
* NPM Version: 5.3.0
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.0

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

/* create array of vendor libs to use in split from bundle */
const VENDOR_LIBS = [
  'react',
  'react-dom'
]

module.exports = {
  entry: {
    bundle: './src/app.js', /* bundle.js will contain everything from app.js */
    vendor: VENDOR_LIBS /* vendor.js will contain all VENDOR_LIBS */
  },
  output: {
    path: path.resolve(__dirname, 'dist'), /* output all files to /dist directory */
    filename: '[name].[chunkhash].js' /* add a hash to each filename for caching and cache busting */
  },
  devServer: {
    contentBase: path.join(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      }
    ]
  },
  plugins: [
    /*
      Create an index.html file from the src/index.html file
      and add our <script> and <link> tags to it
    */
    new HtmlWebpackPlugin({
      template: './src/index.html'
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor'
    })
  ]
};

```

When running `webpack-dev-server --open` I get the following:

```bash
Using "setup" is deprecated and will be removed in the next major version. Please use the "before" and "after" hooks instead. 
If "setup" was working fine for you until now, simply replace it with "before".
```
This is a very barebones React/Webpack boilerplate: https://github.com/jarodtaylor/react-boilerplates/tree/master/barebones

**Comment by shellscape** [comment]
Upgrade to 2.9.1.

**Comment by jarodtaylor** [comment]
@shellscape interesting, I got 2.9.0 from running a fresh `npm install --save-dev webpack-dev-server`. Thanks for the response, I'm good to go, now.
