### ISSUE TITLE
Security update of mime?

### ISSUE THREAD

**Issue by cordoval** [webpack/webpack-dev-server#1123]
* Operating System: Docker Alpine
* Node Version: 8.5.0
* NPM Version:  yarn 1.1.0
* webpack Version: "webpack": "2.7.0",
* webpack-dev-server Version:    "webpack-dev-server": "2.6.1",

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
```
There is a vulnerability on mime that was fixed on latest release https://github.com/broofa/node-mime/commit/f2d859eb53607b909cca03858429035bb025b21a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R47 can we bump up whoever is using it?
```
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ mime                                                            │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ CVSS          │ 7.5 (High)                                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 1.3.4                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ < 1.4.1 || > 2.0.0 < 2.0.3                                      │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                    │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ system@2.0.0 > webpack-dev-server@2.9.1 > expr… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/535                          │
└───────────────┴────────────────────────────────────────────────────────────────
```

```js
  // additional code, remove if not needed.
```

**Comment by shellscape** [comment]
@cordoval few things; this isn't a bug but a modification request. that's an important distinction. you can track down who is using mime by inspecting the package-lock.json. and lastly, your webpack and wepback-dev-server versions are very out of date. we haven't received any security notifications about the latest version, so we're closing this one.

**Comment by cordoval** [comment]
thanks i will upgrade 👍

**Comment by cordoval** [comment]
i use yarn run secure "secure": "nsp check"
yarn nsp check but not sure if this package gets screened like this
