### ISSUE TITLE
webpack-dev-server@2.9.1 has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0"

### ISSUE THREAD

**Issue by alansouzati** [webpack/webpack-dev-server#1126]
* Operating System: 10.x
* Node Version: 6.11.2
* NPM Version: 3.10.10
* webpack Version: 3.4.1
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior

No warning to show when using webpack 3.4.

### Actual Behavior

Showing warning.

### For Bugs; How can we reproduce the behavior?

Run `yarn install` when webpack version is set to 3.4.1.

Maybe the peerDependency should be updated to the following?

```
  "webpack": ">= 2.2.0 < 3 || 3.x"
```

**Comment by shellscape** [comment]
@alansouzati the peer dep works as expected using `npm`. perhaps this is another `yarn` bug?

**Comment by alansouzati** [comment]
thanks for the quick answer here. Let me try `npm install`, I will follow up with yarn on this.

I would expect the caret to allow for 3.4. So I agree with you this sounds like a yarn bug.
