### ISSUE TITLE
Latest version of express 4.16.x breaks serving static files

### ISSUE THREAD

**Issue by johanlajili** [webpack/webpack-dev-server#1130]
* Operating System: OSX
* Node Version: v7.9.0
* NPM Version: 4.2.0
* webpack Version: 1.15.0
* webpack-dev-server Version: 1.16.5

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

5 days ago, express released 4.16.0 and 4.16.1, which made a breaking change (an API was working by accident before where it should not) detailed here https://github.com/expressjs/express/issues/3436.
I'm not entirely sure this is the cause of the issue I'm seeing, but it sounds very probable. I did manage to see that by forcing express 4.15.4 (the latest version), it fixes the issue.

The issue in itself: an iframe pointing towards an html element first send a HEAD request. If the HEAD request replies with a connection: keep-alive, it then makes a GET request.
But with express 4.16.1 it receives a connection:close and so does not try the GET request. 
The github issue on Express specifies a fix:
```javascript
app.use('/*', express.static('path/to/file.html'))
```
to
```javascript
app.use('/*', (req, res) => res.sendFile(path.resolve('path/to/file.html'))
```
Which needs to be necessary in your Server.js.

We are currently investigating using Shrinkwrap to force the subdependency, but it would be nice to not have to do that.
Cheers.

**Comment by shellscape** [comment]
@johanlajili thanks for bringing this to our attention. From the issue you linked to:

> After tracking it down, it turns out there may be some apps (I don't know how common / uncommon yet) that **were providing a file name as the first argument of express.static instead of a file path.** This combined with a app.use path that would match the entire URL (like /* for example) seems to have been accidentally serving that file to all URLs in prior Express.js versions.

As you can see via the lines linked below, we're using only paths with `express.static` and should be immune from that particular change.

https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L274

https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L298

It also looks like express@4.16.1 was released, which was supposed to revert the breaking change. Also tested 4.16.1 locally and it seems to be working on my end. I'll leave this open in case you track down a specific culprit on an edge, but I'm not sure this is an issue with webpack-dev-server.

**Comment by shellscape** [comment]
@johanlajili please check out my previous comment and let us know if you've had the chance to try the latest version of express.

**Comment by shellscape** [comment]
We're over 30 days without a comment from the OP. Marking this one as stale and closing.
