### ISSUE TITLE
Content base should have precedence over proxy

### ISSUE THREAD

**Issue by jacobp100** [webpack/webpack-dev-server#1131]
If I have a proxy set up for `/`, I would expect it to take all unrecognised requests. However, the proxy has precedence over `contentBase`, so my requests are going to the proxy, which serves a 404 page.

Is this the intended behaviour? 

https://github.com/webpack/webpack-dev-server/blob/5a7f26b54081f5ff5a4bbcdd4e0deb131332095e/lib/Server.js#L354-L355

**Comment by shellscape** [comment]
@jacobp100 if you see an issue template, they're usually not optional. it's also always a good idea to read their contents. closing as invalid.
