### ISSUE TITLE
Client is written in ES6 without transpile step

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack-dev-server#1136]
* Operating System: macOS
* Node Version: 8.6.0
* NPM Version: 5.4.2
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior

webpack-dev-server injects a JS client into the browser. #1058 converted this client to ES6, but did not add any sort of transpile step. Therefore, the dev server breaks in older browsers, making it useless for testing an app in these browsers.

Was this intentional? I would expect the client to continue to work in older browsers, even if the server is upgraded to ES6.

### Actual Behavior

Any bundle crashes when loaded in an older browser because of the client inject, e.g. old FF fails with `SyntaxError: let is a reserved identifier in the console on widgets`.

### For Bugs; How can we reproduce the behavior?

Run the server for any bundle and open it in an older browser, e.g. Firefox 38.

**Comment by shellscape** [comment]
Please do make sure you're perusing all of the info on the README 😉 https://github.com/webpack/webpack-dev-server#caveats

There are also several issues which address this which have enjoyed discussion and have been closed (#1101, #1104, #1084). Please try the search function on issues before creating another in the future 🔎

**Comment by billyjanitsch** [comment]
Sorry -- I had searched through issues with "Firefox" as a keyword, but the existing issues happen to run into this issue in IE and Uglify.

**Comment by shellscape** [comment]
No worries. FWIW I plugged in "ES6" to pull those three up.
