### ISSUE TITLE
Const declarations present in generated code

### ISSUE THREAD

**Issue by cozmo8691** [webpack/webpack-dev-server#1144]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: Windows 8.1
* Node Version: v6.10.1
* NPM Version: 4.0.3
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.9.1

- [x ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

barebones project [here](https://github.com/cozmo8691/webpack-test)

### Expected Behavior

When running webpack-dev-server code should be transpiled to run in older browsers.

### Actual Behavior

When running webpack-dev-server the generated code contains 'const' declarations which are causing errors in older browsers e.g. Safari on Ipad Air.

### For Bugs; How can we reproduce the behavior?

npm i
npm start

**Comment by shellscape** [comment]
@cozmo8691 please do try a search before creating a new issue. I just closed an issue with the same exact report 42 minutes ago: https://github.com/webpack/webpack-dev-server/issues/1143

Closing as duplicate.
