### ISSUE TITLE
how to run a simple production server

### ISSUE THREAD

**Issue by awb99** [webpack/webpack-dev-server#1146]
* Operating System: debian
* Node Version:8.7
* NPM Version:5.4.2
* webpack Version: 1.15.0
* webpack-dev-server Version:1.16.5

I dont understand a feature:
I read all the docs, and cannot find how I could server the bundle.js file once I have built the bundle for production. I tried this but it does not work:

```
var fs = require('fs'),
    path = require('path'),
    express = require('express'); 

var app = express();
app.use(express.static('public')); 

// http
var http = require('http');
var httpServer = http.createServer(app);
var port = 9090;
httpServer.listen(port);
console.log('cititrip priccing  starting http-port: ' + port );
```
It loads the index.html, but then I dont know how it gets the react router to work.

I am somehow forced to do this, because there is an issue in serving bigger bundles via the webpack-dev-server. https://github.com/webpack/webpack-dev-server/issues/1044

**Comment by shellscape** [comment]
@awb99 thanks for checking in. unfortunately this isn't the right forum for support questions. citing the issue template:

> Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._

Please give one or both of those options a try. It's also super uncool to remove portions of an issue template, and makes the baby seals cry. Templates are always there to help both yourself and the dev teams working on a project.
