### ISSUE TITLE
Runtime error when `node.global` is set to false.

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack-dev-server#1147]
* Operating System: Windows 10
* Node Version: 6.11.1
* NPM Version: 5.3.0
* webpack Version: 3.7.1
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

A reproduction can be found at https://github.com/filipesilva/webpack-dev-server-global.

```js
  // webpack.config.js
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');


module.exports = {
  entry: './src/main.js',
  devtool: 'source-map',
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html'
    })
  ],
  node: {
    global: false
  }
};

```

```js
  // main.js
console.log('hello');
```

### Expected Behavior

Using `webpack-dev-server` on a browser app with `node.global = false` should not break at runtime.

### Actual Behavior

`webpack-dev-server` has a runtime error:
```
Uncaught ReferenceError: global is not defined
    at Object.<anonymous> (browser-crypto.js:3)
    at __webpack_require__ (bootstrap 46c9e79f3cb14d538cb2:19)
    at Object.<anonymous> (random.js:4)
    at __webpack_require__ (bootstrap 46c9e79f3cb14d538cb2:19)
    at Object.<anonymous> (event.js:3)
    at __webpack_require__ (bootstrap 46c9e79f3cb14d538cb2:19)
    at Object.<anonymous> (websocket.js:3)
    at Object.<anonymous> (websocket.js:99)
    at __webpack_require__ (bootstrap 46c9e79f3cb14d538cb2:19)
    at Object.<anonymous> (transport-list.js:5)
```

This happens because `webpack-dev-server` is bundling `sockjs-client` from source, and `sockjs-client` sources assume a node environment with `global` available.

For more details about how this behaviour is problematic, see angular/angular-cli#5804,  https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888 and https://github.com/sockjs/sockjs-client/issues/401#issuecomment-336904363.

### For Bugs; How can we reproduce the behavior?

```
git clone  https://github.com/filipesilva/webpack-dev-server-global
cd webpack-dev-server-global
npm install
npm run serve
```

**Comment by shellscape** [comment]
Holy hiding edge, batman! I award you 10 points for finding that obscure error. I'd say that first and foremost, that should be addressed with the SockJS team, which it looks like you're well on your way to doing.

I'm focusing my time on the v3 effort and rollout at the moment. Of which one of the major changes is a move away from SockJS and to native `WebSocket`. I can't speak for all of the contributors of course, but this won't be something I'll be prioritizing for a fix. 

Normally I'd suggest that this be closed, citing the move away from SockJS and the open issue tracking the problem with the SockJS project, but I'm good to leave it open for discussion in the event that another contributor or dev finds and submits a fix.

**Comment by filipesilva** [comment]
Thanks for the quick reply @shellscape! I did find a fix but didn't add a test. Will add one now to make sure everything is fine.

**Comment by filipesilva** [comment]
Done, added test.
