### ISSUE TITLE
Support clean urls

### ISSUE THREAD

**Issue by Andersos** [webpack/webpack-dev-server#1149]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: irrelevant
* Node Version: irrelevant
* NPM Version: irrelevant
* webpack Version: irrelevant
* webpack-dev-server Version: irrelevant

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
config.devServer = {
...,
cleanUrls: true
}
```

### Expected Behavior
Visiting a url like `http://localhost:8080/someplace/settings` will return the file `someplace/settings.html`

### Actual Behavior
Visiting a url like `http://localhost:8080/someplace/settings` will return a 404

### For Features; What is the motivation and/or use-case for the feature?
Have the option to have cleaner urls to make the dev environment work more like the production environment. Giving people the option to link to files without specifying the filetype.

**Comment by shellscape** [comment]
@Andersos thanks for checking in. it looks like what you're asking for is "rewrites." rewrites should already be available via the [history-api-fallback](https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback) options. you can read more about that feature [here](https://github.com/bripkens/connect-history-api-fallback#rewrites). 🍻

**Comment by Andersos** [comment]
Thanks for pointing me in the right direction!
