### ISSUE TITLE
Set CLI options from the config file

### ISSUE THREAD

**Issue by hokkos** [webpack/webpack-dev-server#115]
Hi,
Currently it is not possible to set the CLI options (like host, port, ...) from the config file, it would be very handy to be able to do that, because I want to set the host to the current local ip without having to change my npm run command.
This is probably [where it happens](https://github.com/webpack/webpack-dev-server/blob/9dff89ac02d3f5a932c0668ffe2b231165795313/bin/webpack-dev-server.js#L48).
Thanks.

**Comment by troutowicz** [comment]
I ran into the same problem. I ended up creating a new JS file to launch the server, providing a way to dynamically set IP and port.

https://gist.github.com/troutowicz/bfd0e4eb0633ed77834e

**Comment by troutowicz** [comment]
After writing up that gist, I realized there was a simpler way \o/

**Comment by SpaceK33z** [comment]
@hokkos, in your config file, you can specify the port or host like this:

```
devServer: {
     port: 9000
},
```

Closing this for now, but feel free to re-open.
