### ISSUE TITLE
Proxy should add a option to allow change Referer header

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack-dev-server#1150]
Some server will check csrftoken with Referer, if Referer: localhost is provided, the request will be rejected by the server.

Now I use this as a temp solution.
```js
        bypass: (req, res) => {
          if (req.headers && req.headers.referer)
            req.headers.referer = req.headers.referer.replace('localhost:4000', 'THE TARGET SITE')
        }
```

**Comment by shellscape** [comment]
Closing as invalid. Please re-read the issue template.
