### ISSUE TITLE
Rename "historyApiFallback" to "wantYourRoutesToWork" with default value set to "true" instead of "false"

### ISSUE THREAD

**Issue by zhanwenchen** [webpack/webpack-dev-server#1158]
* Operating System: macOS High Sierra 10.13
* Node Version: v8.7.0
* NPM Version: 5.5.1
* webpack Version: 3.7.1
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [x] This is a **feature** request
- [x] This is a **modification** request

### Code

<details>
  <summary>webpack.config.js</summary>

```js
  // webpack.config.js
var webpack = require('webpack');
var path = require('path');

// Webpack uses `publicPath` to determine where the app is being served from.
// In development, we always serve from the root. This makes config easier.
var publicPath = '/';

module.exports = {
  entry: './src/index.js',
  output: {
    path: __dirname + '/build',
    filename: 'bundle.js',
    // publicPath = '/build' because index.html requires a ./build/bundle.js
    publicPath: '/build',
  },
  devServer: {
    // contentBase = '~/public/' so that index.html becomes the default html at GET '/'
    contentBase: path.join(__dirname, 'public'),
    inline: true,
    port: 8080,
    proxy: {
      '/api/**': {
        target: 'http://[::1]:3000/',
        pathRewrite: {'^/api' : ''},
      }
    },
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react']
        }
      },
      {
        test: /\.css$/,
        loaders: [
          require.resolve('style-loader'),
          require.resolve('css-loader')
        ]
      }
    ]
  }
}
```
</details>

<details>
  <summary>App.js</summary>

```js
  // App.js
import React from 'react';
import { Switch, Route } from 'react-router-dom';

export default class App extends React.Component {
  render() {
    return (
      <div className="container app" id='app'>
        <Switch>
            <Route path="/" exact component={()=>(<p>Home</p>)} />
            <Route path="/any_route" exact component={()=>(<p>not an Express error message that says "Cannot GET /any_route"</p>)} />
        </Switch>
      </div>
    );
  }
}
```
</details>

### Expected Behavior

localhost:8080/any_route does NOT render an Express 404 message that says "Cannot GET /any_route"

### Actual Behavior

localhost:8080/any_route does render an Express 404 message that says "Cannot GET /any_route"

### For Bugs; How can we reproduce the behavior?

Run App.js inside alongside an index.js that looks like

<details>
  <summary>index.js</summary>

```js
//index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter } from 'react-router-dom';
import App from './App';

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root'));
```
</details>

### For Features; What is the motivation and/or use-case for the feature?

All routes work when you add a 'historyApiFallback: true' to the webpack.conf.js 'devServer' config object (but then you need to manually restart the webpack dev server). Why not rename "historyApiFallback" because it literally means nothing for debugging (note that the Express 404 is not debuggable through React, so people might attribute the error to React, React-Router, or Babel-Loader caching) and set it to "true" by default, because presumably people expect routing to, well, work?

**Comment by shellscape** [comment]
@zhanwenchen there's so much snark in this one I'm not sure where to begin 😆 

we've got tests for routing that pass, and an example for the `historyApiCallback` feature that work. citing that, I think what you're looking for is some support at configuring your app correctly. And for that we ask folks to swing by StackOverflow or stop by the webpack Gitter first. you're also kind of on an island in this case; this isn't something we see reported. for those reasons, we're going to close this one. unfortunately the issues here aren't a support forum. if you can create a PR with a simple test that reproduces the issue and fail, following the examples that exist as a pattern, without the using additional third party modules, we'd happily reopen the issue and examine the pull request.

**Comment by TheLarkInn** [comment]
👍👌
