### ISSUE TITLE
How to run npm run dev on Linux centOS as background service?

### ISSUE THREAD

**Issue by jakub-wisniewski** [webpack/webpack-dev-server#1162]
I am running vue.js app with npm run dev on Linux CentOS. However I would like to run this app as background service without open console. 

How shall I run it?

**Comment by shellscape** [comment]
@jakub-wisniewski thanks for checking in. unfortunately you've chosen remove and not to read, or ignore the header of the issue template, which contains important info. for that reason, and for the reasons cited in the issue template, we're closing your issue.
