### ISSUE TITLE
package files should not contain es6 syntax "const"

### ISSUE THREAD

**Issue by MarvinXu** [webpack/webpack-dev-server#1170]
* Operating System: window 7 x64
* Node Version:  v6.10.2
* NPM Version: 3.10.10
* webpack Version: 2.5.1
* webpack-dev-server Version: 2.9.3

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior
no es6 syntax in package files
### Actual Behavior
contains "const" in `client/overlay.js`
### For Bugs; How can we reproduce the behavior?
npm install webpack-dev-server

**Comment by shellscape** [comment]
Please do review the documentation in the README https://github.com/webpack/webpack-dev-server#caveats

**Comment by MarvinXu** [comment]
But this way  I couldn't test my https website  even in an IOS9 machine, how should I fix this if I want to use the latest version of webpack-dev-server?

**Comment by shellscape** [comment]
@MarvinXu you can't use the latest version if you need to support browsers that don't support `const` and `let`. [iOS 9 was released in 2015] (https://en.wikipedia.org/wiki/IOS_version_history#iOS_9) and oldIE support was killed in 2016. As the README states, you'll have to use v2.7.1 if you want to support platforms that old.
