### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by MizardX** [webpack/webpack-dev-server#1171]
The certificate included in version 2.9.3 of the npm package expired 2017-10-31 21:57:23 GMT. If the package was installed less than 30 days ago, it will not be replaced automatically.

Package info: https://www.npmjs.com/package/webpack-dev-server
Direct link: https://registry.npmjs.org/webpack-dev-server/-/webpack-dev-server-2.9.3.tgz

Would it break anything if the certificate was excluded from the npm package?

**Comment by d3viant0ne** [comment]
In the short term, you can define your own SSL certs & you won't get the expired cert issues.

**Comment by MizardX** [comment]
Just deleting the certificate is enough to get it to work. But this is not obvious.

**Comment by d3viant0ne** [comment]
That SSL cert is generated when you enable the HTTPS option.

I generally define my own using selfsigned

**Comment by shellscape** [comment]
@d3viant0ne yeah that was a mistake. I've got a patch release to do so I'll include that fix. 

@MizardX please note that issue templates *are not* optional, and as stated in ours, if you remove it or ignore it the next time, your issue will be closed without examination. it is not cool to remove an issue template. always fill them out.
