### ISSUE TITLE
Upgrade sockjs to 0.3.19

### ISSUE THREAD

**Issue by fwielstra** [webpack/webpack-dev-server#1177]
I was running [auditjs](https://www.npmjs.com/package/auditjs) on my project which came across one vulnerability in the version of sockjs used by `webpack-dev-server` ([issue](https://github.com/sockjs/sockjs-node/issues/217), [fix](https://github.com/sockjs/sockjs-node/pull/218), which was resolved in the 0.3.19 release (from about a year ago). I've searched and couldn't find this issue having been raised yet.

PR incoming.

**Comment by SpaceK33z** [comment]
Looks to have been fixed a while ago, so closing.
