### ISSUE TITLE
watching is failed when Uppercase letter is in absolute path on OS X

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack-dev-server#118]
```
➤➤ uname -a
Darwin Air.local 14.0.0 Darwin Kernel Version 14.0.0: Tue Sep 23 23:01:41 PDT 2014; root:xnu-2782.1.97~6/RELEASE_X86_64 x86_64
➤➤ node -v
v0.10.33
```
```js
    "webpack": "^1.5.3",
    "webpack-dev-server": "^1.7.0"
```
My project path was:
```
/Users/chen/repo/Cirru/editor
```
after I save a file in `src/main.cirru`, there was no log or compiling.
It began to work after I changed path to:
```
/Users/chen/repo/cirru/editor
```

**Comment by haustraliaer** [comment]
I too can confirm strange errors with uppercase folder names for relative requires...

It's a bit hard to explain, but I'll do my best and report back with some more concrete examples.

I thought I may have hit some kind of module limit - I was getting all sorts of weird behavior with a specific group of modules when I added them, such as:

- webpack-dev-server compiling correctly... but then hanging when I manually refreshed (and giving strange 404 messages and such).
- hot reloader not applying updates and then hanging in the CLI
- The whole webpack build process failing to this error:

```
fs.js:1056
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EMFILE
    at errnoException (fs.js:1024:11)
    at FSWatcher.start (fs.js:1056:11)
    at Object.fs.watch (fs.js:1081:11)
    at processItem 

...
```

But then saw this issue, changed my relatively linked folder names to lowercase, and it works fine.

**Comment by haustraliaer** [comment]
Hmmm I'm not so sure that was the problem now - just seems like I hit a limit on modules with the hot-reloader.

Switching to standard dev-server (reload whole app on change) fixes the problem.

**Comment by arlair** [comment]
I had a similar issue where no files updated in a folder with a starting uppercase letter. I was merging two example projects together and they were using different folder conventions.

I noticed in the webpack bundling log the folder was showing as lowercase. Once I renamed the folder with a lowercase letter it started working.

Using OS X as well.

**Comment by arlair** [comment]
Actually, after further investigation, it seems like the folder was uppercase, but the ES6 import statement was lowercase. The page loaded the first time, but subsequent changes did not reload.

I tested making the folder uppercase and the ES6 import uppercase and it was reloading on changes. Sorry about that.

**Comment by SpaceK33z** [comment]
@jiyinyiyong, do you still have this issue? I can't reproduce it on my OS X machine.

**Comment by jiyinyiyong** [comment]
@SpaceK33z not configuring Webpack by myself for long. So, can't reproduce.

**Comment by SpaceK33z** [comment]
Okay, I'll close this issue because no-one else seems to have it.
