### ISSUE TITLE
Prevent high CPU on MacOS by installing fsevents

### ISSUE THREAD

**Issue by hanxue** [webpack/webpack-dev-server#1180]
* Operating System: MacOS 10.10.5
* Node Version: 8.4.0
* NPM Version: 5.4.2
* webpack Version: 3.4.1
* webpack-dev-server Version: 2.9.4

- [X] This is a **bug**
- [X] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior

webpack-dev-server should not use excessive CPU to monitor file changes

### Actual Behavior

Running webpack-dev-server on Intel Core i7-3615QM machine uses 40-70% CPU consistently, even when there are no client request and no changes to the project directory. 

### Reproduce Bug

1. Install `webpack-dev-server` on MacOS and `fsevents` is not installed as dependency
2. Run `webpack-dev-server` on a project with some files

### Feature / Suggestion

This problem can be solved if  `fsevents` is installed as a dependency. Although it is an optional dependency for `chokidar`, which is in turn used by `watchpack`, `fsevents` does not get installed. 

Consider adding `"os" : [ "darwin" ]` to `fsevents` to make sure it is installed on MacOS?

Related issues:
https://github.com/webpack/webpack-dev-server/issues/172
https://github.com/webpack/webpack/issues/701

**Comment by shellscape** [comment]
I'm leaning toward not approving this PR for a couple of reasons:

1. it seems that this would be better suited as a PR for `webpack` itself, as WDS depends directly on it and cannot function without it.
3. Several issues within the `chokidar` repo cite having a "wrong" version installed that doesn't behave as expected. The project is referencing the version it knows will work with the module, and that'd be easy to get out of sync with.
2. `chokidar` has explicitly set this to an `optionalDependency` and it [has been discussed](https://github.com/paulmillr/chokidar/issues/568) at length [many times](https://github.com/paulmillr/chokidar/search?p=3&q=fsevents&type=Issues&utf8=%E2%9C%93) in that project.

I'm open to being convinced that this is a needed change, but the reasons need to be compelling.
