### ISSUE TITLE
'Cannot GET /path/to/reach' error when opening application from an external link

### ISSUE THREAD

**Issue by Gehbrial** [webpack/webpack-dev-server#1184]
* Operating System: Ubuntu 16.04.3 LTS
* Node Version: 7.10.1
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
 // webpack.common.js
module.exports = {
    entry: ["babel-polyfill", path.join(__dirname, '../src/index.js')],

    output: {
        filename: "bundle.js",
        path: path.join(__dirname, '../dist'),
        publicPath: '/'
    },
[...]
resolve: {
        modules: ["node_modules", path.join(__dirname, 'src')]
    },

    plugins: [
        new HtmlWebpackPlugin({
            template: path.join(__dirname, '../index.html'),
            filename: "index.html",
            inject: "body"
        }),
        new ExtractTextPlugin({
            filename: 'bundle.css'
        }),
        new CleanWebpackPlugin(["dist"], {
            root: path.join(__dirname, "../")
        }),
        new webpack.NoEmitOnErrorsPlugin (),
        new webpack.NamedModulesPlugin()
    ]
};
```
```js
  // webpack.dev.js
module.exports = merge(common, {
    devtool: "inline-source-map'",

    devServer: {
        port: 3000,
        proxy: {
            "/api": {
                target: 'http://localhost:5000'
            }
        },
        historyApiFallback: true,
        noInfo: true
    }
});
```

```js
  // index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel='stylesheet' href='dist/bundle.css'>
        <link rel="shortcut icon" type="image/png" href="./src/images/LS_LOGO_3couleur_Verti.png"/>
    </head>

    <body>
        <div id="root"></div>
    </body>
</html>
```

### Expected Behavior
When accessing http:://localhost:3000/path/to/access from an external link, I would expect the application to be loaded correctly.
### Actual Behavior
With the application up and running using the webpack-dev-server, the application is unreachable through a confirmation e-mail's link. The server is started with the following command: 'webpack-dev-server --inline --hot --config ./webpack/webpack.dev.js'
### For Bugs; How can we reproduce the behavior?
By accessing the application through a link in an e-mail.

Thank you so much for your help :)

**Comment by shellscape** [comment]
@Gehbrial thanks for stopping by. this looks a lot like a support request, more so than a bug report. we ask that users not post support requests here, but rather one of the options listed in the issue template. a bug is something that can be pinpointed to a particular cause, and reproducible outside of your system.

there's nothing in WDS that would differentiate between opening a link from a particular source. it also looks like you have an extra colon in the url you say doesn't work; `http:://localhost:3000/path/to/access`. it sounds a lot like you have a typo somewhere or have a particular issue with your specific environment.

If you can put together a test repo that reproduces this consistently (even somewhat consistently), then we'll reopen this one. Rest assured we'll see comments posted.
