### ISSUE TITLE
Refresh tab instead of opening new one on start

### ISSUE THREAD

**Issue by PengyuanZhao** [webpack/webpack-dev-server#1185]
If a tab with the same url such as localhost:3000 already exists on a browser tab, is there any way to refresh it instead of opening a new tab when using `--open`?

Thanks,

**Comment by shellscape** [comment]
Closing as invalid. See Issue Template.

**Comment by IhorVimmi** [comment]
share a link please)))

**Comment by dennisja** [comment]
@shellscape Can you provide a link to the Template issue?

**Comment by shellscape** [comment]
@dennisja get to know github and where issue templates live. https://github.com/webpack/webpack-dev-server/blob/master/.github/ISSUE_TEMPLATE.md

_Note: I no longer maintain this repository._
