### ISSUE TITLE
Build time got too high after upgrade versions

### ISSUE THREAD

**Issue by cmargulhano** [webpack/webpack-dev-server#1187]
After upgrading to the versions:
  - "typescript": "2.6.1"
  - "webpack-dev-server": "2.9.4",
  - "webpack-merge": "4.1.1"
  - "webpack": "3.8.1"

The build time got very high and in our project it took about 20 minutes to finish.

When we downgrade to the versions:
  - "typescript": "2.5.1"
  - "webpack-merge": "1.1.1"
  - "webpack-dev-server": "2.6.1"
  - "webpack": "3.4.1"

The build time back to normal which in our case is approximately 7 minutes.

* Operating System: Linux Ubuntu 16.04
* Node Version: v8.6.0
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

Could you check this problem please?

**Comment by shellscape** [comment]
Closed as support request/invalid. Please see the issue template.

**Comment by cmargulhano** [comment]
Its ok now?
https://github.com/webpack/webpack-dev-server/issues/1188
