### ISSUE TITLE
Build time got too high after upgrade versions

### ISSUE THREAD

**Issue by cmargulhano** [webpack/webpack-dev-server#1188]
* Operating System: Linux Ubuntu 16.04
* Node Version: v8.6.0
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Expected Behavior

When we downgrade to the versions:

"typescript": "2.5.1"
"webpack-dev-server": "2.6.1"
"webpack": "3.4.1"
The build time back to normal which in our case is approximately 7 minutes.

### Actual Behavior

After upgrading to the versions:

"typescript": "2.6.1"
"webpack-dev-server": "2.9.4",
"webpack": "3.8.1"

The build time got very high and in our project it took about 20 minutes to finish.

### For Features; What is the motivation and/or use-case for the feature?

The build time is too high, please consider to review this problem.

**Comment by michael-ciniawsky** [comment]
Does the build time also increase with `webpack v3.4.1` && `webpack-dev-server v2.9.4` ? If there is any perf regression I assume this is in `webpack` itself and unrelated to `webpack-dev-server` in particular. I any case a reproduction repo is needed for debugging since perf often depends on your particular project and is non-trivial to debug, nearly impossible without any code tbh. A starting point would be using `webpack --progress` and observe where it more or less 'hangs' for some time

**Comment by michael-ciniawsky** [comment]
```
node --inspect --debug-brk ./node_modules/webpack/bin/webpack.js
```

Chrome DevTools

**Comment by cmargulhano** [comment]
clean-webpack-plugin: /home/claudio/Koradi/Projects/WPS/enterprise-webapp/dist has been removed.
-> building modules [==                  ] 10%  (0.0 seconds) 
Project is running at http://0.0.0.0:9000/
webpack output is served from /

[at-loader] Using typescript@2.6.1 from typescript and "tsconfig.json" from /home/claudio/Koradi/Projects/WPS/enterprise-webapp/tsconfig.json.

webpack: wait until bundle finished: /
-> building modules [===                 ] 15%  (10.9 seconds) 
[BABEL] Note: The code generator has deoptimised the styling of "/home/claudio/Koradi/Projects/WPS/enterprise-webapp/node_modules/@angular/core/esm5/core.js" as it exceeds the max of "500KB".
-> building modules [====                ] 20%  (19.6 seconds) 
-> building modules [=====               ] 25%  (31.1 seconds) 
-> building modules [======              ] 30%  (37.4 seconds) 
-> building modules [=======             ] 35%  (63.7 seconds) 
-> building modules [========            ] 40%  (64.4 seconds) 
-> building modules [=========           ] 45%  (68.2 seconds) 
-> building modules [==========          ] 50%  (68.5 seconds) 
[BABEL] Note: The code generator has deoptimised the styling of "/home/claudio/Koradi/Projects/WPS/enterprise-webapp/node_modules/brace/index.js" as it exceeds the max of "500KB".
-> building modules [===========         ] 55%  (71.8 seconds) 
-> building modules [============        ] 60%  (72.3 seconds) 
-> building modules [=============       ] 65%  (72.7 seconds) 
-> building modules [=============       ] 64%  (73.1 seconds) 
-> building modules [=============       ] 65%  (73.2 seconds) 
-> building modules [=============       ] 64%  (73.2 seconds) 
-> building modules [=============       ] 65%  (73.2 seconds) 
-> building modules [=============       ] 64%  (73.2 seconds) 
-> building modules [=============       ] 65%  (73.2 seconds) 
[BABEL] Note: The code generator has deoptimised the styling of "/home/claudio/Koradi/Projects/WPS/enterprise-webapp/node_modules/@angular/compiler/esm5/compiler.js" as it exceeds the max of "500KB".
webpack: wait until bundle finished: /
[BABEL] Note: The code generator has deoptimised the styling of "/home/claudio/Koradi/Projects/WPS/enterprise-webapp/node_modules/highcharts/highcharts.src.js" as it exceeds the max of "500KB".
-> sealing [==============      ] 71%  (188.1 seconds) 
-> basic chunk optimization [===============     ] 76%  (188.1 seconds) 
-> advanced chunk modules optimization [================    ] 81%  (188.1 seconds) 
-> chunk order optimization [=================   ] 86%  (188.2 seconds) 
-> additional chunk assets processing [==================  ] 91%  (189.6 seconds) 

[at-loader] Checking started in a separate process...

[at-loader] Ok, 1.73 sec.
->  [====================] 100%  (201.1 seconds) 


Build completed in 201.148s

Hash: c68d2561c3333cbaf794
Version: webpack 3.8.1
Time: 201151ms

**Comment by shellscape** [comment]
@michael-ciniawsky  Please correct me if I'm wrong, but this is a `webpack` issue, not a `webpack-dev-server` issue.

@cmargulhano your previous issue was closed because it was also a support request, which we don't use the issues in this repos for. it's also a better idea to edit an existing issue rather than create a duplicate.

**Comment by cmargulhano** [comment]
I'm not requesting support. The problem is that the build time is bad. If you do not even want to know, explain at least how to proceed according to your policies.

**Comment by shellscape** [comment]
@cmargulhano I literally told you how to proceed in my last reply. 

> Please move the issue over to [webpack](webpack/webpack) to address build time issues. webpack-dev-server doesn't handle compilation (webpack-dev-middleware triggers it, webpack does the actual compilation). Closing for now.

**Comment by cmargulhano** [comment]
my bad ok thanks

**Comment by d3viant0ne** [comment]
@cmargulhano - You may also want to run `top` while a build is running to make sure you aren't memory starved ( depending on how large you project is ).

**Comment by michael-ciniawsky** [comment]
@shellscape Yep, if it is an regression chances are high it's `webpack 3.4.1...3.8.1` + this project and very unlikely to be the related to `webpack-dev-server`, but who knows for sure ¯\_(ツ)_/¯

> 201151ms

@cmargulhano ~3min isn't that bad at all ? 🙃

**Comment by cmargulhano** [comment]
Yes is not so bad, but the results was from my dev machine :(
On gitlab server is ~20 min.
