### ISSUE TITLE
Accessing webpack dev server from other hardware when combining with backend server

### ISSUE THREAD

**Issue by colindresj** [webpack/webpack-dev-server#119]
I'm currently running the webpack dev server in combination with a backend server. My backend reads the paths to entries from `output.publicPath` and `output.[entry name]`. Normally, when I want to test on a phone, I'll access localhost via IP address or tunnel in.

Since assets are being served up by webpack dev server, but requests are handled by my backend server, when I access my dev site from other devices I obviously don't get assets. Any ideas how to use webpack dev server in combo with a backend server with access from other (locally-connected) hardware?

**Comment by sokra** [comment]
You can change the listening interface of the dev-server with `--host <ip>`.

There is also a proxy option which allows the dev-server to act a proxy, when you could only tunnel one port.

**Comment by troutowicz** [comment]
Take a look at PR #116

**Comment by colindresj** [comment]
Great thanks guys. @sokra any chance we can get @troutowicz commit published to NPM? It would be great to be able to do this from the config instead of cli.
