### ISSUE TITLE
Feature: Have "open" command to launch browser after build is completed

### ISSUE THREAD

**Issue by EvHaus** [webpack/webpack-dev-server#1192]
#> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: Mac OS
* Node Version: 8.9.1
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior

When using the `--open` command, I would like the browser to launch when the build has completed (not when it has started), and only if the build is without errors. For reference, this plugin currently have the behavior I'm after (https://github.com/baldore/open-browser-webpack-plugin), but given that `webpack-dev-server` I think it would be nice if this was a built-in feature instead of requiring an extra plugin.

### Actual Behavior

The `--open` command currently launches the browser immediately, and if the build happens to fail you get stuck with an empty browser tab.

### For Features; What is the motivation and/or use-case for the feature?

I think it would create a better dev experience.

**Comment by shellscape** [comment]
Thanks for checking in and for the interest in the project. Unfortunately, this isn't a feature we'll be adding at the moment, and probably not in the future unless there is high demand. I would recommend looking into the `overlay` option which will show you errors in the browser tab, if there are any.

**Comment by sanalpanicker** [comment]
why is this closed? it's definitely annoying

**Comment by En777** [comment]
if you want open browser after webpack build(all compile done), you can use this plugin:
https://www.npmjs.com/package/webpack-open-browser-plugin
it has a better experience, it's work with webpack compiler.hooks.done .

**Comment by n1kk** [comment]
For future generations who also ended up here after a google search, you can add this simple inline plugin into your dev config:
 ```js
plugins: [{
    apply: compiler => {
        compiler.hooks.afterEmit.tap("MyAwesomeOpenAfterBuildPlugin", compilation => {
            open("https://google.com");
        });
    }
}]
```
Uses https://www.npmjs.com/package/open package, webpack uses it under the hood so it should be available, but if you use TypeScript you might need to install it.

**Comment by maogongzi** [comment]
> For future generations who also ended up here after a google search, you can add this simple inline plugin into your dev config:
> 
> ```js
> plugins: [{
>    apply: compiler => {
>        compiler.hooks.afterEmit.tap("MyAwesomeOpenAfterBuildPlugin", compilation => {
>            open("https://google.com");
>        });
>    }
> }]
> ```
> 
> Uses https://www.npmjs.com/package/open package, webpack uses it under the hood so it should be available, but if you use TypeScript you might need to install it.

Thank you bro, saved my day!
