### ISSUE TITLE
can I use wds to quickly serve my local static files?

### ISSUE THREAD

**Issue by bochen2014** [webpack/webpack-dev-server#1196]
I just have a folder contains a whole bunch of static files, and I want to use `wds` to host them so that I can access them via `http://localhost:8080`. I don't have a `index.js` or any script files in my folder, and I don't want to create a `webpack.config.js` either.  I just want to use `wds` as a quick express server. 

It worked for a long time with `webpack@^1` and `webpack-dev-server@^1` but I recently find it doesn't work anymore. 

Do you any any suggestions? thanks

**Comment by shellscape** [comment]
This isn't a support forum. Please see the info in the issue template.

**Comment by bochen2014** [comment]
this a regression. something worked before now isn't working anymore
I'm talking about webpack-dev-server@^1

**Comment by bochen2014** [comment]
@SpaceK33z  do you have any idea?

**Comment by bochen2014** [comment]
I'm switching to https://github.com/indexzero/http-server as it seems to fit the purpose  better 
(server static files with zero configuration. I just think that `wds` should provide the same functionality -- which it did on wds@^1 -- but I understand it's more a `webpack` issue)

**Comment by shellscape** [comment]
@bochen2014 it's generally considered poor form to continually post replies when editing a single reply will suffice. your comment about a regression is invalid because you are a full major version and several minor versions behind, whilst misusing WDS in an albeit inventive way.
