### ISSUE TITLE
Allow specifying suburl for assets

### ISSUE THREAD

**Issue by jvanbruegge** [webpack/webpack-dev-server#1202]
* Operating System: Arch Linux
* Node Version: 9.2
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior
I can specify to serve assets from a suburl (like the `publicPath` option, but for assets too)

### Actual Behavior
`publicPath` does not work for static assets

### For Features; What is the motivation and/or use-case for the feature?
I am building an app that will live on a suburl on the main site (like http://example.com/app/). My server serves assets accordingly. But for development, all static assets like images are missing in my site, because webpack dev server ignores the `publicPath` option for static content.

**Comment by shellscape** [comment]
@jvanbruegge thanks for checking in. you can use the [`before`](https://webpack.js.org/configuration/dev-server/#devserver-before) option to add additional static middleware (for example; `express.static`) to suit your needs.

**Comment by jvanbruegge** [comment]
Thanks, that works. The option is not really prominent in the docs, so I missed it.

**Comment by shellscape** [comment]
Hm in fairness it kind of is, given it's only the 3rd option listed on the page and in the tree :)

![Imgur](https://i.imgur.com/qbT13zO.png)

**Comment by jvanbruegge** [comment]
I saw the option, but did not know I could use it that way. I never use express normally

**Comment by shellscape** [comment]
That's fair. If you have suggestions for how to improve the docs, we'd welcome a PR at https://github.com/webpack/webpack.js.org
