### ISSUE TITLE
open option with host set to 0.0.0.0 opens page that won't load in browser

### ISSUE THREAD

**Issue by MajorBreakfast** [webpack/webpack-dev-server#1204]
I'm setting `host = '0.0.0.0` to test the page on devices on my local network (iPhone, iPad, etc.). I'm also using `open = true` (default setting) to automatically open a browser window on startup. Unfortunately it opens the window at `0.0.0.0:8000` instead of `localhost:8000`. And consequently no page loads. I can fix this by setting `useLocalIp = true`, but I think that's counter-intuitive and works slightly different to what I really want (`localhost`). Could you improve this? Maybe set it to `localhost` automatically if the host is `0.0.0.0`.

**Comment by shellscape** [comment]
Closing as invalid. Please see the issue template.

**Comment by ipengyo** [comment]
I also encountered the same problem hate bad

**Comment by MajorBreakfast** [comment]
@ipengyo Would you open another issue that follows their "template"?

**Comment by fenixphp** [comment]
"webpack": "4.16.1"

``` javascript

  devServer: {
    hot: true,
    host: '0.0.0.0',
    port: 3000,
    open: true,
    openPage: 'dashboard/',
    publicPath: '/dashboard/',
    contentBase: path.join(__dirname, 'Build'),
    historyApiFallback: true
  },

```

in browser :  http://0.0.0.0:3000/dashboard/

---

``` javascript

  devServer: {
    hot: true,
    host: '0.0.0.0',
    port: 3000,
    open: true,
    openPage: 'dashboard/',
    public: 'localhost:3000',
    publicPath: '/dashboard/',
    contentBase: path.join(__dirname, 'Build'),
    historyApiFallback: true
  },

```
work.

**Comment by wakefun** [comment]
webpack5 this helped：
https://github.com/vuejs/vue-cli/issues/6834#issuecomment-1168167395
