### ISSUE TITLE
Open Google chrome with --open=chrome on all platforms

### ISSUE THREAD

**Issue by eugenesaenko** [webpack/webpack-dev-server#1205]
* Operating System: OSX 10.13.1
* Node Version: v6.11.5
* NPM Version: 5.4.2
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.9.0

- [x] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

```bash
 webpack-dev-server --progress --color --open=chrome
```

### Expected Behavior

Opens Google chrome browser on start compiling.

### Actual Behavior

Throws error `Unable to open browser: chrome. If you are running in a headless environment, please do not use the open flag`.

### For Bugs; How can we reproduce the behavior?

Start webpack-dev-server on OSX with `--open=chrome` flag.

### For Features; What is the motivation and/or use-case for the feature?

It would be nice to have general names for browsers across all platforms.

**Comment by shellscape** [comment]
`webpack-dev-server` uses the [`opn`](https://github.com/sindresorhus/opn) module to open a browser specified. please take the issue up with that project.
