### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by lileilei** [webpack/webpack-dev-server#1206]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* webpack-dev-server Version:

- [ ] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

### For Features; What is the motivation and/or use-case for the feature?

I'd like to add a routing, data simulation.But I don't want to restart a service.By exposing the app and middle to add the routing and middleware. Is a good idea?

**Comment by shellscape** [comment]
@lileilei I'm sorry, but you left a ton blank on the issue template and I'm really not sure what you're trying to ask.
