### ISSUE TITLE
how to run the examples?

### ISSUE THREAD

**Issue by adamchenwei** [webpack/webpack-dev-server#1207]
I dont know how to run it, can't find the readme how to run it either... any help? Thanks

**Comment by adamchenwei** [comment]
specifically this one https://github.com/webpack/webpack-dev-server/tree/master/examples/general/proxy-simple

**Comment by shellscape** [comment]
Just totally ignored the issue template there didn't ya. Closing as invalid.

**Comment by adamchenwei** [comment]
So basically you do not understand the question I assume? If I wirte in a format you indicated there, what else to add? @shellscape?
