### ISSUE TITLE
How to manually shut down server?

### ISSUE THREAD

**Issue by binarykitchen** [webpack/webpack-dev-server#121]
In my gulp task I run the webpack dev server before running any jasmine based end-to-end tests.

But there is no function to shut down the webpack dev server once the tests have ended. How can I do that?

(And by the way, how can I disable watching for this scenario? Such an option seems to be missing)

**Comment by Chrazy** [comment]
server.close()

**Comment by binarykitchen** [comment]
thanks but sorry, i picked something else ...

**Comment by pixels4nickels** [comment]
@binarykitchen could you please share your solution?
I need to stop the server (and selenium) from my npm script. So using `server.close() `will not work for me either.

**Comment by cy6erGn0m** [comment]
a shutdown port or shutdown via REST would be helpful
