### ISSUE TITLE
browser reloads the page multiple times

### ISSUE THREAD

**Issue by aaroncass** [webpack/webpack-dev-server#1214]
* Operating System: Ubuntu 16.04
* Node Version: 8.9.1
* NPM Version: 5.5.1
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.9.5

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

Barebones repo (based on official getting started tutorial) can be found here: https://github.com/aaroncass/webpack-test

```js
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  devServer: {
    contentBase: './dist'
  }
};
```

### Expected Behavior
Changes to src/index.js should result in the browser reloading the page once.

### Actual Behavior
Changes to src/index.js result in the browser reloading the page multiple times. The number of times appears random - between 2 and 12 times.

### For Bugs; How can we reproduce the behavior?
The bug only appears in chrome or chromium.   

1. Clone the repo at https://github.com/aaroncass/webpack-test
2. run "npm start" 
3. visit http://localhost:8080/webpack-dev-server/bundle
4. make a small change to src/index.js

**Comment by shellscape** [comment]
Duplicate. Closing in favor of #1210
