### ISSUE TITLE
DevServer.before to monkey patch Express res.send function. it doesn't work.

### ISSUE THREAD

**Issue by Chan-Chun** [webpack/webpack-dev-server#1215]
``` javascript
devServer: {
    before: app => {
      app.use((req, res, next) => {
        if (req.headers && req.headers.accept && !!~req.headers.accept.indexOf('text/html')) {
          var send = res.send;
          res.send = function(string) {
            });
            send.call(this, string);
          };
        }
        next();
      });
    },
}
```

Normally,this monkey patch function could fetch the `string` in `res.send`, but the function doesn't be called. 

And I debbug in the `express` which in `webpack-dev-server ` node_module my project use.
```
res.send = function send(body) {
  
  console.log("res.send")

  var chunk = body;
  var encoding;
  var req = this.req;
  var type;

   ···
}
```

And i found res.send couldn't be called.

I just wanna to insert some HTML the body of  res.send .   and monkey patch is the best way.

**Comment by shellscape** [comment]
@Chan-Chun please note that the issue template is not optional, as stated in the issue template. Also as stated in the issue template that this is not a support forum. Closing as invalid.
