### ISSUE TITLE
DevServer.before to monkey patch Express res.send function. it doesn't work.

### ISSUE THREAD

**Issue by Chan-Chun** [webpack/webpack-dev-server#1216]
* Operating System: MacOS 10.12.6
* Node Version: 8.9.1
* NPM Version: 5.5.1
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.1

- [x] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Code

```js
  devServer: {
    before: app => {
      app.use((req, res, next) => {
        if (req.headers && req.headers.accept && !!~req.headers.accept.indexOf('text/html')) {
          var send = res.send;
          res.send = function(string) {
            });
            send.call(this, string);
          };
        }
        next();
      });
    },
}
```

And I debbug in the express which in webpack-dev-server node_module my project use.
```js
  res.send = function send(body) {
  
  console.log("res.send")

  var chunk = body;
  var encoding;
  var req = this.req;
  var type;

   ···
}
```
### Expected Behavior
1. the `res.send` function should be called when i request the `text/html`
2. and the `res.send` function in the webpack-dev-server node_module should be called .

### Actual Behavior.
this monkey patch doesn't work. so I Couldn't insert any HTML in the body of `res.send` .

### For Bugs; How can we reproduce the behavior?

and i print the time of each function. i found `devServer` `before` hook is called later than the actual `express res.send`

**Comment by shellscape** [comment]
We already commented on #1215. Creating duplicate issues is frowned upon. Your issue is not a bug, it's a support request. Please use one of the sources mentioned in the issue template for support.
