### ISSUE TITLE
Memory is not serving the compiled stuff

### ISSUE THREAD

**Issue by binarykitchen** [webpack/webpack-dev-server#122]
I just found out that with this configuration the webpack dev server is not serving the assets from memory but is serving the outdated ones from the file system :(

```coffee
  devServer = new WebpackDevServer(compiler,
    publicPath:  "#{__dirname}/#{paths.public}"
    contentBase: "#{__dirname}/#{paths.public}"
    port:        config.port
    host:        config.host
    lazy:        !watch
    noInfo:      true
  )
```

Why is this happening? When I visit `http://localhost:3000/` to test my work, I still see older assets.

**Comment by sokra** [comment]
`publicPath` is wrong. `contentBase` is not needed.
Check `http://localhost:3000/webpack-dev-server` to see where assets are served from.

**Comment by binarykitchen** [comment]
sorry but we are picking gulp-connect for the dev server because we do not like the idea serving assets from memory
