### ISSUE TITLE
unhandledrejection not working in webpack-dev-server

### ISSUE THREAD

**Issue by githoniel** [webpack/webpack-dev-server#1222]
* Operating System: win 10.0.15063
* Node Version: v8.4.0
* NPM Version: 5.5.1
* webpack Version: 2.7.0
* webpack-dev-server Version: 2.7.1

- [x] This is a **bug**

### Code
when i switch to `babel-preset-env`,  remove `Promise` polyfill and using Chrome's native Promise.
`onunhandledrejection` not working in webpack-dev-server. but it works in simple html file or single html using <script> tag.
close chrome devTools make no different.
```js
window.onunhandledrejection = ({ reason }) => {
    alert(reason)
}
Promise.reject({})
```
create event and dispatch does work.
```js
var unhandledRejectionEvent = new Event('unhandledrejection');
 window.dispatchEvent(unhandledRejectionEvent)
```

### Expected Behavior
onunhandledrejection event should fire

### Actual Behavior

onunhandledrejection not fire

### For Bugs; How can we reproduce the behavior?
my babelrc config
```.babelrc
{
        "presets":[
                [ "env", {
                    "targets": {
                        "browsers": ["last 2 Chrome versions"]
                    },
                    "modules": false
                }]
            ]
}
```

**Comment by shellscape** [comment]
@githoniel thanks for checking in. unfortunately `webpack-dev-server` doesn't do anything with `Promises`, `babel`, nor `onunhandledrejection`. I believe you're looking at the wrong cause for your particular issue. You're also using a _very_ outdated version of webpack-dev-server. If you can pinpoint the culprit in webpack-dev-server, we'll be happy to reopen. But it looks like you've found a red herring.
