### ISSUE TITLE
Module not found: Error: Can't resolve 'css-loader'

### ISSUE THREAD

**Issue by yamafaktory** [webpack/webpack-dev-server#1224]
* Operating System: macOS - High Sierra
* Node Version: v8.7.0
* NPM Version: 5.5.1
* webpack Version: v4.0.0-alpha.0
* webpack-dev-server Version: 3.0.0-alpha3

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

Go to https://github.com/yamafaktory/rust-wasm-webpack, drop the `--no-inline` flag in https://github.com/yamafaktory/rust-wasm-webpack/blob/master/package.json#L46 and run `yarn wasm:setup && yarn build && yarn start`.

### Expected Behavior

No error.

### Actual Behavior

```sh
ERROR in (webpack)-dev-server/lib/client/js/overlay.js
Module not found: Error: Can't resolve 'css-loader' in '/Users/yamafaktory/dev/rust-wasm-webpack/node_modules/webpack-dev-server/lib/client/js'
 @ (webpack)-dev-server/lib/client/js/overlay.js 3:0-54
 @ (webpack)-dev-server/lib/client/js?http://localhost:9000
 @ multi (webpack)-dev-server/lib/client/js?http://localhost:9000 ./src/main.js
```

@shellscape You fixed another similar issue (in *3.0.0-alpha3*) after I reached you on Twitter 👍.

**Comment by shellscape** [comment]
thanks for the issue. should be resolved in `alpha5`
