### ISSUE TITLE
Should always run portfinder even when port is defined within config or cli option

### ISSUE THREAD

**Issue by robert-prib-polestar** [webpack/webpack-dev-server#1226]
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-dev-server Version: 2+

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?
* Currently portfinder is only run when no port defined in config, however, it would make sense to always run portfinder to create a server in case the port is in use.
* The main use case is that for my projects I have a port defined to be used and need to run multiple instances locally for testing/comparing branches.

**Comment by shellscape** [comment]
@robert-prib-polestar thanks for checking in and for the request. But I have to disagree there. By fulfilling your request, we'd be creating an environment of expected unknown quantities. That is to say, the user would never be able to count on what port to expect. Whereas with a strictly defined port, the known value can be counted upon, and if there's an error or the server isn't available on the port specified, a system can react reasonably to that error. 

If you need dynamic ports, then it's not unreasonable to suggest using the system in place and leaving port undefined. You can count on the first port to be checked/used to be the default of `8080` per https://github.com/webpack/webpack-dev-server/blob/0a8f8965fba4a46a862497f6e7d1ad9377040a15/bin/webpack-dev-server.js#L70. And subsequent ports to be searched and opened from that port. If a base of 8080 isn't preferable for your project, you can always use portfinder in a script on your end to start at a base port more to your liking, and pass the value along for each instance you spawn via the CLI or API.

**Comment by robert-prib-polestar** [comment]
> If a base of 8080 isn't preferable for your project, you can always use portfinder in a script on your end to start at a base port more to your liking, and pass the value along for each instance you spawn via the CLI or API.

@shellscape That workaround sounds reasonable, thanks for the quick reply.

I think to make more of case for this change;
* You could display a warning to terminal output that the defined port was in use and allow the system to still work.
* Or you could allow the default port to be defined as an option, or a config flag to allow dynamic port assignment or something along those lines.

**Comment by shellscape** [comment]
Yeah it's been considered in the past, but the demand for the feature just hasn't been there. We took a look at express and koa et al as a model to follow, given that we use express under the hood - neither allow automatic port finding and recommend using a third party lib (portfinder) for doing so. We kind of dip the toe in by doing that automagically if a port just straight up isn't defined. But we try very hard not to include every option under the sun, because that just makes a project a maintenance nightmare. When demand is low and a workaround exists, we point folks to the workaround.
