### ISSUE TITLE
Upgrade to webpack-dev-middleware 2.0.0

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack-dev-server#1229]
_(Internal tracking issue for the Version 3 Milestone)_

We need to update to `webpack-dev-middleware@2.0.0`. At present there is a conflict with the logger that needs to be resolved, as outlined here https://github.com/pimterry/loglevel/issues/117

Until that fix is in place, or another suitable logger module is chosen, we're blocked on updating.

**Comment by SpaceK33z** [comment]
I updated WDM to 2.0.0 in the latest beta, so closing this. But feel free to re-open if I missed something.
