### ISSUE TITLE
config.devServer.hot doesn't work as expected

### ISSUE THREAD

**Issue by skozin** [webpack/webpack-dev-server#123]
Documentation states that `config.devServer` [can be used](http://webpack.github.io/docs/configuration.html#devserver) to configure `webpack-dev-server`, and that `webpack-dev-server` [accepts the `hot` option](http://webpack.github.io/docs/webpack-dev-server.html#api). However, this `webpack.config.js` doesn't work:

```js
module.exports = {
  entry: [ 'webpack/hot/dev-server', './src/main' ],
  devServer: {
    hot: true
  }
}
```

**Expected result:** Hot Replacement Mode is enabled and working.

**Actual result:** the `Uncaught Error: [HMR] Hot Module Replacement is disabled` message is printed to the browser console.

The cause is probably [this check in `webpack/convert-argv.js`](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L270) that adds `HotModuleReplacementPlugin` only when `--hot` command-line option is present.

**Comment by skozin** [comment]
Ah, now I see this line in the comments:

```js
// Note: this does _not_ add the `HotModuleReplacementPlugin` like the CLI option does.
```

What's the reason for this behaviour?

**Comment by MrOrz** [comment]
Probably because API has no access to the webpack config:

https://github.com/webpack/webpack-dev-server/issues/106#issuecomment-74278863

**Comment by skozin** [comment]
@MrOrz, thanks! I'm closing this issue in favor of that one you linked.
