### ISSUE TITLE
question about proxy

### ISSUE THREAD

**Issue by lzl124631x** [webpack/webpack-dev-server#1231]
Hi,

I have a question about using webpack-dev-server proxy. Posted [here](https://github.com/vuejs-templates/webpack/issues/1173). I'm not sure the reason of my failure is more relevant to webpack-dev-server or vuejs-templates/webpack, so I posted in both places. Looking forward to response! Thanks!

**Comment by shellscape** [comment]
@lzl124631x as stated in the issue template, the issue template is not optional and this is not the proper forum for support questions. Closing as invalid.
