### ISSUE TITLE
How load i18n json files in webpack-dev-server

### ISSUE THREAD

**Issue by zhangwei8607** [webpack/webpack-dev-server#1232]
As title, please help

**Comment by zhangwei8607** [comment]
var CopyWebpackPlugin = require('copy-webpack-plugin');

plugins: [
        new CopyWebpackPlugin([{ from: 'src/assets/', to: 'assets' }])
    ],

**Comment by shellscape** [comment]
@zhangwei8607 as states in the issue template, the issues page here is not a support forum. please use one of the suggested support methods instead in the future.
