### ISSUE TITLE
Support IPv6 (for `--open`)

### ISSUE THREAD

**Issue by ferrybig** [webpack/webpack-dev-server#1233]
* Operating System: Windows 10 64 bit
* Node Version: v9.2.0
* NPM Version: 5.5.1
* webpack Version: ^3.9.1
* webpack-dev-server Version: ^2.9.5

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
//package.json
{
  "name": "test projec",
  "version": "1.0.0",
  "keywords": [  ],
  "author": "Fernando van Loenhout",
  "dependencies": {  },
  "directories": {
    "test": "test"
  },
  "devDependencies": {
    "webpack": "^3.9.1",
    "webpack-dev-server": "^2.9.5"
  },
  "scripts": {
    "dev": "webpack-dev-server --progress --colors --hot --content-base dist/ --open --config ./webpack.config.js --inline --watch --host :: --disableHostCheck",
  },
}

```

### Expected Behavior
Webpack dev server starts, hosts server on all ip addresses (because of `::`), then opens localhost to view the website

### Actual Behavior
Webpack dev server starts http://[::]:8080/ in browser what is an invalid ip, what goes against the examples shown here: [CLI: Host and Port Options](https://github.com/webpack/webpack-dev-server/blob/master/examples/cli/host-and-port/README.md)

### For Bugs; How can we reproduce the behavior?
Start the dev server using `--host :: ` and ` --open`

**Comment by shellscape** [comment]
@ferrybig thanks for reporting the issue. 

> Webpack dev server starts http://[::]:8080/ in browser what is an invalid ip, what goes against the examples shown here: CLI: Host and Port Options

I'm struggling a little to understand the English here. Can you try to rephrase?

**Comment by evilebottnawi** [comment]
@ferrybig  it is mean - allow to start server on IPv6, but valid use `[::]`?
@ferrybig use 0.0.0.0 to start on all IPs

**Comment by ferrybig** [comment]
@shellscape 
1. I run `webpack-dev-server --host :: --open` from the terminal
2. Since `--open` is passed, it will open my webbrowser
3. The url opened in the webbrowser is `[::]:8080`
4. The browser complains that `[::]` is not a valid ip address

I expect that the localhost ip address of `[::]` is opened, similar to what happens when you use `0.0.0.0`, for IPv6, the equivalent is `[::1]`.

@evilebottnawi I need support for connecting over ipv6, if I start the server with `0.0.0.0`, I cannot connect to my server from my other device using its ip

**Comment by shellscape** [comment]
@ferrybig my experience with IPv6 is very limited and I'm afraid we're going to need a PR to resolve this one.

**Comment by evilebottnawi** [comment]
> The browser complains that [::] is not a valid ip address
Wrong, it is valid (try to open http://[::]:8080/)

Note:
- Using `::1` means use localhost only for IPv6
- Using `::` mean use all available interfaces (include IPv6)

`opn` (`open`) package works find with IPv4 and IPv6 so i am closing this issue
