### ISSUE TITLE
Specifying Stats.all causes API schema validation to fail

### ISSUE THREAD

**Issue by niedzielski** [webpack/webpack-dev-server#1235]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: Ubuntu v17.10
* Node Version: v9.2.1
* NPM Version: v5.5.1
* webpack Version: v3.10.0
* webpack-dev-server Version: v2.9.7

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
  export default {
    devServer: { stats: { all: true } },
    ... // The rest of the Webpack configuration.
  }
```

### Expected Behavior
webpack-dev-server Stats is [expected to be API-compatible with Webpack](https://webpack.js.org/configuration/dev-server/#devserver-stats-). [Webpack v3.9.0](https://github.com/webpack/webpack/releases/tag/v3.9.0) added `Stats.all` and webpack-dev-server is expected to accept it.

### Actual Behavior
When `Stats.all` is defined, webpack-dev-server fails:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.stats should be one of these:
   object { all?, context?, hash?, version?, timings?, performance?, depth?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warnings?, errors?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? } | boolean | "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"
   -> Used by the webpack CLI program to pass stats options.
   Details:
    * configuration.stats.colors should be a boolean.
      -> `webpack --colors` equivalent
    * configuration.stats.colors has an unknown property 'level'. These properties are valid:
      object { bold?, red?, green?, cyan?, magenta?, yellow? }
    * configuration.stats.colors has an unknown property 'hasBasic'. These properties are valid:
      object { bold?, red?, green?, cyan?, magenta?, yellow? }
    * configuration.stats.colors has an unknown property 'has256'. These properties are valid:
      object { bold?, red?, green?, cyan?, magenta?, yellow? }
    * configuration.stats.colors has an unknown property 'has16m'. These properties are valid:
      object { bold?, red?, green?, cyan?, magenta?, yellow? }
    * configuration.stats should be a boolean.
    * configuration.stats should be one of these:
      "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"
```

### For Bugs; How can we reproduce the behavior?
Specify `Stats.all` as `true`.

### For Features; What is the motivation and/or use-case for the feature?
There are numerous output options for many aspects of Webpack. Please avoid introducing a new API.

**Comment by shellscape** [comment]
@niedzielski thanks for the issue. I'd give `webpack-dev-server@next` a try and see if that solves the issue first. it's like an issue with `optionsSchema.json` in the 2.x/master branch. As always we'd welcome a PR.

**Comment by niedzielski** [comment]
@shellscape, thanks for the reply! I tried `@next` but there are some big API changes my project isn't quite ready for (in my case, I get `Unknown arguments: config, d, w` and I didn't see these covered under the [breaking changes readme](https://github.com/webpack/webpack-dev-server/blob/next/breaking-changes.md) or how to specify the config file elsewhere). I then tried adding a `publicPath` and `stats.all` property to the `devServerOptions` specified in [examples/api/simple/server.js](https://github.com/webpack/webpack-dev-server/blob/next/examples/api/simple/server.js#L9) but unfortunately that's failing for unrelated reasons. I switched back to the master branch with the same change and `stats.all` as well as arbitrary `stats` properties pass. I tried [examples/cli/progress](https://github.com/webpack/webpack-dev-server/blob/master/examples/cli/progress/webpack.config.js#L11) too but couldn't get it to fail either. I'll have to circle back on this another time :/

**Comment by shellscape** [comment]
If i had to venture a guess, it's probably something to do with the schema definition: https://github.com/webpack/webpack-dev-server/blob/master/lib/optionsSchema.json#L282

**Comment by niedzielski** [comment]
This was my mistake. As mentioned in the error message, it seems that `stats.colors` is required by webpack-dev-server. What led me to the wrong conclusion is that the following works:

```js
const STATS = {all: false, errors: true, errorDetails: true, moduleTrace: true, warnings: true}
export default {
  devServer: { stats: { ...STATS, all: undefined } },
  ... // The rest of the Webpack configuration.
}
```

..And `devServer: { stats: STATS },` fails. Only later did I realize `devServer: { stats: { ...STATS } },` passes. I've added `STATS.colors` and webpack-dev-server works fine with `all`. to My apologies for the red herring!

**Comment by shellscape** [comment]
no worries!
