### ISSUE TITLE
[next] `log is not a function` when using `--progress`

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack-dev-server#1244]
https://github.com/webpack/webpack-dev-server/blob/24630302dc975437a43a0b9a63ede2140cba21b9/lib/cli/util.js#L51

**Comment by shellscape** [comment]
@JounQin I think I might have mentioned this to you before, but the issue template isn't optional. you **MUST** fill it out.

@next is no longer being worked on. The team has decided in a change of direction. More info to follow, but you should consider the alpha versions of 3.0.0 unsupported.

**Comment by JounQin** [comment]
Sorry for not filling the issue template, that's my fault for thinking that's an obvious problem there although I didn't remember you've mentioned this to me before.

Sorry again.
