### ISSUE TITLE
[3.0.0-alpha6] Connection reset crash when manually refreshing page

### ISSUE THREAD

**Issue by TeffenEllis** [webpack/webpack-dev-server#1245]
> **Please note that this template is not optional.** If you proceed with this form,
please fill out _all_ fields, or your issue may be closed as "invalid."
Please do not delete this template. Please ask questions on StackOverflow or the
webpack Gitter (https://gitter.im/webpack/webpack). _General questions, how-to
questions, and support requests will be closed._
**Please do remove this header to acknowledge this message.**

* Operating System: macOS Sierra 10.12.6
* Node Version: v8.1.4
* NPM Version: 5.5.1
* webpack Version: 3.10.0
* webpack-dev-server Version: **3.0.0-alpha6**

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
const compiler = webpack(config)
const server = new WebpackDevServer(compiler, {
  historyApiFallback: {
    index: config.output.publicPath,
    disableDotRule: true
  },
  publicPath: config.output.publicPath,
  https: {
    key: fs.readFileSync(path.join(__dirname, '../certs/local.key')),
    cert: fs.readFileSync(path.join(__dirname, '../certs/local.crt'))
  },
  hot: true,
  host: routes.frontend.hostname,
  headers: { 'Access-Control-Allow-Origin': '*' },
  port: routes.frontend.port
})

server.listen(error => {
  if (error) {
    console.log(error)
  }
})
```

### Expected Behavior
The page refreshes and loads the content.

### Actual Behavior
Upon refreshing the page, the dev server crashes with the following error:

```bash
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:610:25)
```

HMR works as expected. This issue seems to be limited to manual refreshes and chunks that are not hot reloaded.

### For Bugs; How can we reproduce the behavior?
This can be reproduced on the **3.0.0-alpha6** release with any configuration.

### For Features; What is the motivation and/or use-case for the feature?

Cheers 🍻

**Comment by derrickpelletier** [comment]
I'm getting this pretty consistently on `3.0.0-alpha5` _without_ a manual refresh.
Just a rebuild being triggered via file watching. Unable to find an explicit action that's causing it to crash

**Comment by dev357** [comment]
Seems to be an unhandled error(ECONNRESET) in the websocket connection in [DevServer.js](https://github.com/webpack/webpack-dev-server/blob/next/lib/DevServer.js#L128)

You can add this on line 128 to fix it for now:
```javascript
ws.on("error", err => {
  log.error(err);
});
```

**Comment by KatFishSnake** [comment]
@dev357 the above solution "on error", is theres any reason not to introd a temporary fix for the next release?, I find it a bit troublesome to update DevServer.js after each "npm install" i do in-between branch switching

To reiterate: would you greenlight a PR for it ?

**Comment by dev357** [comment]
I have no affiliation with the wds team so cant greenlight any PRs :)
But i think you could create a "fixed" version for yourself on github and use that in package.json until they get this fixed?
Thats how i'm using someones version of html-webpack-plugin that works with webpack 4 for now atleast!
```js
"devDependencies": {
  "html-webpack-plugin": "Graham42/html-webpack-plugin#feat/webpack-4"
}
```

**Comment by lpinca** [comment]
Yes, an `'error'` listener should always be added.
Ref: https://github.com/websockets/ws/issues/1256

**Comment by shellscape** [comment]
All, @next is no longer being worked on. The team has decided in a change of direction. More info to follow, but you should consider the alpha versions of 3.0.0 unsupported.

**Comment by derrickpelletier** [comment]
@shellscape thanks for the update, where's a good spot we could follow updates (re: more info to follow)

**Comment by akatechis** [comment]
Any update available as to the plans for this project? Will there be some other branch? Another project altogether?

Thanks for all your hard work, WDS team :)

**Comment by ljani** [comment]
@akatechis: Please see [v3.0.0-beta.1](https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0-beta.1).
