### ISSUE TITLE
Removing Prior DOM element

### ISSUE THREAD

**Issue by nelsieborja** [webpack/webpack-dev-server#1246]
* Operating System: Mac
* Node Version: NA
* NPM Version: 5.5.1
* webpack Version: 3.6.0
* webpack-dev-server Version: 2.9.7

- [x] This is a **bug**
- [x] This is a **feature** request
- [ ] This is a **modification** request

### Code

```
// Webpack config
js
module.exports = {
  entry: "./src/app.js",
  output: {
    publicPath: "/dist/",
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js",
    chunkFilename: "[name].chunk.js"
  },

  devServer: {
    hot: true,
    port: 3000
  },

  devtool: "inline-source-map",
...
plugins: [
    ...
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin()
  ]
}


// Entry file
...
if (module.hot) {
  module.hot.accept();
}
...
```

Hot Module does not clear DOM prior events, texts, etc. instead it will keep them. Same issue is discussed [here](https://stackoverflow.com/questions/45794993/webpack-hot-module-replacement-does-not-remove-prior-dom-element). In React this is easy, but this a frameworkless project and it's using jQuery

**Comment by shellscape** [comment]
Closing as question. Please see the Issue Template. Clearing DOM events is not the responsibility of this module.
