### ISSUE TITLE
[3.0.0-alpha6] Websocket tries to connect to 0.0.0.0

### ISSUE THREAD

**Issue by dev357** [webpack/webpack-dev-server#1247]
* Operating System: Windows 10
* Node Version: 9.3.0
* NPM Version: 5.4.2
* webpack Version: 4.0.0-alpha.2
* webpack-dev-server Version: 3.0.0-alpha6

- [x] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Webpack config
```js
devServer: {
  // listen on all interfaces
  host: "0.0.0.0"
}
```

### Expected Behavior
When setting the host to "0.0.0.0" the websocket should connect to window.location.hostname

### Actual Behavior
websocket tries to connect to 0.0.0.0 and fails

### For Bugs; How can we reproduce the behavior?
set the host option in devServer to "0.0.0.0"

### Suggested fix in lib/client/js/socket.js
```js
//old
const socketUrl = url.format({
    protocol: options.https ? "wss" : "ws",
    hostname: options.host,
    port: options.port
  });

//new & fixed ;)
const socketUrl = url.format({
    protocol: options.https ? "wss" : "ws",
    hostname: options.host === "0.0.0.0" ? window.location.hostname : options.host,
    port: options.port
  });
```

**Comment by shellscape** [comment]
All, @next is no longer being worked on. The team has decided in a change of direction. More info to follow, but you should consider the alpha versions of 3.0.0 unsupported.
