### ISSUE TITLE
[3.0.0-alpha6] Only the last websocket client gets messages

### ISSUE THREAD

**Issue by dev357** [webpack/webpack-dev-server#1248]
* Operating System: Windows 10
* Node Version: 9.3.0
* NPM Version: 5.4.2
* webpack Version: 4.0.0-alpha.2
* webpack-dev-server Version: 3.0.0-alpha6

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Expected Behavior
when connecting multiple clients to the server all of them should receive updates through the websocket connection

### Actual Behavior
only the client that connected last will receive updates

### For Bugs; How can we reproduce the behavior?
connect two clients to the devserver. Update a file that should cause a refresh. Only the client that was connected last will receive the reload event.

### Notes
from what i can tell, the DevServer class can only save a single socket connection. It is overwritten when a new connection is established.

**Comment by shellscape** [comment]
All, @next is no longer being worked on. The team has decided in a change of direction. More info to follow, but you should consider the alpha versions of 3.0.0 unsupported.
