### ISSUE TITLE
upgrading socket.io completely broke hot module replacement

### ISSUE THREAD

**Issue by jlongster** [webpack/webpack-dev-server#125]
This commit: https://github.com/webpack/webpack-dev-server/commit/cf126c021f61490294dc2be1b93755b984ba9240

It upgrades socket.io, but the client file [here](https://github.com/webpack/webpack-dev-server/tree/master/client/web_modules) is still a really, really old version. Trying to use this newer server with the older version completely breaks (I see "unknown transport", and when I manually fixed that, I saw other errors).

I looks like this was published to npm, so HMR should be broken for everyone right now... Downgrading to 1.6.4 fixes it.

**Comment by troutowicz** [comment]
I am receiving the same error since the socket.io update

**Comment by sokra** [comment]
> This commit: cf126c0

That's not published yet...

**Comment by troutowicz** [comment]
I didn't realize broken commits were being pushed to master.

**Comment by jlongster** [comment]
> This commit: cf126c0
> 
> That's not published yet...

How do you tag versions? It wasn't clear to me how to check what 1.7.0 is.

Because I just did `npm install webpack-dev-server@1.7.0`, see here:

```
% npm ls webpack-dev-server
jlongster.com@ /Users/james/projects/jlongster4
└── webpack-dev-server@1.7.0 
```

With this version, I definitely hit this bug. I have to downgrade to 1.6.4 to fix it.

**Comment by jlongster** [comment]
Oh my gosh. I just hit a terrible npm bug that I've heard about before. You know what fixed it?

```
npm cache clear
```

I've heard from others that if you `npm install` something straight from a local git repo, sometimes the cache gets confused and doing a `npm install webpack-dev-server` later will still install the local git repo instead of actually downloading the latest version of npm.

My problems are gone now and installing the latest version works. OMG. Can't believe how much time that just wasted. Sorry for the noise here. :)

**Comment by sokra** [comment]
no problem...

the current master version is still broken. socket.io was upgraded in #105.
