### ISSUE TITLE
resolve proxy url wrong

### ISSUE THREAD

**Issue by TaylorPzreal** [webpack/webpack-dev-server#1252]
* Operating System:
arch

* Node Version:
v9.3.0

* NPM Version:
v5.6.0

* webpack Version:
3.10.0

* webpack-dev-server Version:
2.9.7

I'm not sure.

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
devServer: {
    compress: true,
    port: 63342,
    historyApiFallback: true,
    overlay: true,
    proxy: {
      '/proxy/*': {
        target: 'http://192.168.1.151/',
        changeOrigin: true,
        pathRewrite: {
          '^/proxy': ''
        }
      },
    }
  },
```

```js
  // additional code, remove if not needed.
  this.baseURL = '/proxy/api-portal';
  // all request base this url.
```

### Expected Behavior
Expected url is:
http://192.168.1.151/api-portal/account/loginByPassword

### Actual Behavior
http://localhost:63342/proxy/api-portal/proxy/api-portal/account/loginByPassword

Thx very much.

**Comment by shellscape** [comment]
Closing as support question. Please see the Issue Template.

**Comment by xiaoyueyue165** [comment]
@TaylorPzreal  Hey, brother, is this problem solved? I have the same problem as you now. Can you tell me how to solve it? thank you very much!

**Comment by TaylorPzreal** [comment]
@xiaoyueyue165 

```json
devServer: {
    compress: true,
    port: 9000,
    historyApiFallback: true,
    overlay: true,
    proxy: [{
      target: 'https://www.honeymorning.com/',
      changeOrigin: true,
      context: [
        '/api',
      ],
    }],
  },
```
