### ISSUE TITLE
webpack Multiple Targets

### ISSUE THREAD

**Issue by sanonz** [webpack/webpack-dev-server#1256]
### Code

```js
// webpack.config.js
module.exports = [
  {
    entry : {
      app: './src/app'
    },
    output: {
      path: path.resolve(__dirname, 'dist/')
      filename: 'assets/js/app.js',
      chunkFilename: `assets/js/${getAssetName('[hash]', '[name]')}.js`
    },
    devServer: {
      hot: true
    }
  },
  {
    entry : {
      app: './src/app.server'
    },
    output: {
      path: path.resolve(__dirname, 'dist/server')
      filename: 'app.js',
      chunkFilename: '[name].js',
      libraryTarget: 'commonjs2'
    },
    target: 'node'
  }
];
```
### Run
```shell
npx webpack-dev-server
```

### Expected Behavior
- ~~_The client app entry add `webpack/hot/only-dev-server` `webpack/hot/dev-server` etc._~~
- The client app entry add https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js file, from at line: https://github.com/webpack/webpack-dev-server/blob/master/lib/util/addDevServerEntrypoints.js#L23
- The server app entry no add.

### Actual Behavior
All added.

### For Bugs; How can we reproduce the behavior?
Example edit: https://github.com/webpack/webpack-dev-server/blob/master/lib/util/addDevServerEntrypoints.js#L22
```diff
    [].concat(webpackOptions).forEach((wpOpt) => {
+     if (wpOpt.target === 'node') return;
      if (typeof wpOpt.entry === 'object' && !Array.isArray(wpOpt.entry)) {
        Object.keys(wpOpt.entry).forEach((key) => {
          wpOpt.entry[key] = devClient.concat(wpOpt.entry[key]);
        });
      } else if (typeof wpOpt.entry === 'function') {
        wpOpt.entry = wpOpt.entry(devClient);
      } else {
        wpOpt.entry = devClient.concat(wpOpt.entry);
      }
    });
```

### For Features; What is the motivation and/or use-case for the feature?
server side rendering

**Comment by sanonz** [comment]
Turned out to be such, no add:

// webpack.config.js
```diff
{
+    entry: (devClient) => {
+      return {
+        app:  './src/setup.server',
+      };
+    },
    output: {
      path: path.resolve(__dirname, 'dist/server')
      filename: 'app.js',
      chunkFilename: '[name].js',
      libraryTarget: 'commonjs2'
    },
    target: 'node'
  }
```

The update cannot be used:
[https://github.com/webpack/webpack-dev-server/commit/f4f14cec31f25ffb46898d1e281fe9569a8569ae#diff-6a9b3dfc5b6956a454f4233ea7a4992cR24](https://github.com/webpack/webpack-dev-server/commit/f4f14cec31f25ffb46898d1e281fe9569a8569ae#diff-6a9b3dfc5b6956a454f4233ea7a4992cR24)

**Comment by SpaceK33z** [comment]
So for the Node target it shouldn't auto-add the `webpack/hot` scripts? Seems fair enough I think. However this could potentially be a breaking change to some. Are there any use cases where you would need it to work like before?

**Comment by sanonz** [comment]
I want to implement an isomorphic apps, which contains two webpack configuration files,  one for client app and one for server-side app. The server side app runs in a node environment, so the `webpack/hot` script is not required.

**Comment by SpaceK33z** [comment]
Yes, but I was wondering if there are valid use cases where you do need these `webpack/hot` scripts in a node environment. If there are none, this isn't really a breaking change. If there are, it might be a breaking change.

**Comment by sanonz** [comment]
The Node target add [https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L180) file.
The runs in node environment throw error `self not defined` at line: [https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L180](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L180)
Node environment need client code?

**Comment by SpaceK33z** [comment]
Okay thanks for finding out. Could you make a PR and add a test for this?

**Comment by sanonz** [comment]
Sorry, I question write wrong. I make PR and test at tomorrow. Thanks!

**Comment by sethomas** [comment]
+1 I am also experiencing the same thing.

@SpaceK33z what's the status on merging @sanonz PR?

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/webpack/webpack-dev-server/pull/1775
