### ISSUE TITLE
Absolute URL in devServer.publicPath is ignored and breaks HMR

### ISSUE THREAD

**Issue by vvolodin** [webpack/webpack-dev-server#1257]
* Operating System: Windows 10
* Node Version: 6.10.3
* NPM Version: 5.6.0
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.9.7

- [x] This is a **bug**
- [ ] This is a **feature** request
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
output: {
    publicPath: '/build/'
}
devServer: {
        headers: {
            "Access-Control-Allow-Origin": '*',
            "Access-Control-Allow-Methods": 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
            "Access-Control-Allow-Headers": 'X-Requested-With, content-type, Authorization'
        },
        stats: {
            colors: true
        },
        inline: true,
        https: true,
        hot: true,
        port: 8080,
        publicPath: 'https://localhost:8080/build/',
        historyApiFallback: {
            disableDotRule: true,
            htmlAcceptHeaders: ['text/html', 'application/xhtml+xml']
        }
    }
```

### Expected Behavior
Download hot update manifest using the absolute URL.

### Actual Behavior
Is using my relative output.publicPath (set to '/build/') only to download the manifest, which resolves to another server (localhost:44320) which is running my backend project.

**Comment by shellscape** [comment]
This isn't a bug. It's by design. Please use a relative URL.

**Comment by vvolodin** [comment]
What is the reasoning behind this design decision? If I'm allowed to override publicPath for webpack-dev-server, why can't I use absolute URL? How do I use hot webpack-dev-server with a different backend serving the HTML?

**Comment by werkzeugh** [comment]
i ran into the same problem.

 ➜ my workaround is to proxy  the request with the "requestly"-extension in chrome:

![image](https://user-images.githubusercontent.com/1092088/44949706-3dea4e00-ae37-11e8-948c-4a5602d5e22b.png)


and i set the CORS-headers in my setup as well.

**Comment by stephan-v** [comment]
The Webpack community never ceases to amaze me with its stupidity.
