### ISSUE TITLE
webpack-dev-server not working

### ISSUE THREAD

**Issue by SrikanthChebrolu** [webpack/webpack-dev-server#1261]
npm install --save-dev webpack-dev-server
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/srikanthchebrolu/.npm/_logs/2018-01-06T20_54_28_968Z-debug.log

**Comment by 4ltugh** [comment]
same issue +1

**Comment by eugene-gavriloff** [comment]
join, same problem +

**Comment by SpaceK33z** [comment]
There is a partial npm outage: https://status.npmjs.org/

**Comment by SrikanthChebrolu** [comment]
Issue resolved, NPM outage affected it
