### ISSUE TITLE
Did WDS drop the "config" arg?

### ISSUE THREAD

**Issue by drcmda** [webpack/webpack-dev-server#1264]
* Operating System: MACOS High Sierra
* Node Version: 9.3.0
* NPM Version: 5.6.0
* webpack Version: 3.0.0-alpha6
* webpack-dev-server Version: 4.0.0-alpha.4

- [x] This is a **bug**
- [ ] This is a **modification** request

```
$ webpack-dev-server --config .dev/webpack.config.js --colors

webpack-dev-server 3.0.0-alpha6
webpack 4.0.0-alpha.4
Usage: https://webpack.js.org/configuration/dev-server/

Unknown argument: config
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It doesn't even show up any longer on `npx webpack-dev-server --help`. Did it move somewhere else or was the name changed?

**Comment by shellscape** [comment]
@drcmda per #1259 we're having yargs issues. also note that the peerDeps for this module don't state support for the webpack@next versions. consider it unsupported at this time.
