### ISSUE TITLE
2.10.0 not working in Internet Explorer due to template strings

### ISSUE THREAD

**Issue by Q-Man** [webpack/webpack-dev-server#1265]
Webpack Dev Server 2.10.0 uses template strings (\`abc${x}\`), this syntax not supported by Internet Explorer. So Webpack Dev Server not working in IE any more ("Invalid character" errors).

For example (but not only) in this function (type: \`webpack${type}\`):
```
// Send messages to the outside, so plugins can consume it.
function sendMsg(type, data) {
  if (
    typeof self !== 'undefined' &&
  (typeof WorkerGlobalScope === 'undefined' ||
  !(self instanceof WorkerGlobalScope))
  ) {
    self.postMessage({
      type: `webpack${type}`,
      data
    }, '*');
  }
}
```

**Comment by shellscape** [comment]
Closing as invalid. See the issue template.

**Comment by luisbelloch** [comment]
Duplicates #1268
