### ISSUE TITLE
webpack-dev-server doesn't start after upgrading

### ISSUE THREAD

**Issue by Ky6uk** [webpack/webpack-dev-server#1266]
* Operating System: OS X
* Node Version: 9.3.0
* NPM Version: 5.6.0
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.10.0

- [x] This is a **bug**

I have tried to upgrade dependencies today and `webpack-dev-server` crashed with message

> Missing argument values: config-name, context, entry, module-bind, module-bind-post, module-bind-pre, output-path, output-filename, output-chunk-filename, output-source-map-filename, output-public-path, output-jsonp-function, output-library, output-library-target, records-input-path, records-output-path, records-path, define, target, watch-aggregate-timeout, devtool, resolve-alias, resolve-extensions, resolve-loader-alias, optimize-max-chunks, optimize-min-chunk-size, prefetch, provide, plugin, open-page

I guess this is happening because `yargs` and `yargs-parser` packages have been updated (that why dependencies should be stricted).

Running command is `webpack-dev-server --config ./webpack.config.dev.js --progress`

**Comment by anymost** [comment]
so do I!

**Comment by 5angel** [comment]
Yup, had to downgrade to 2.9.7, this is a pretty common problem now judging by responses from my collegues

**Comment by Ky6uk** [comment]
Ahh. It seems to be duplicate of #1259
