### ISSUE TITLE
Watch detects changes after just opening a file in Windows 10

### ISSUE THREAD

**Issue by AKArchy** [webpack/webpack-dev-server#1274]
* Operating System: Windows 10 Pro
* Node Version: v8.9.4
* NPM Version: v5.6.0
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.10.1

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

Can be reproduced on the project here (specifically version 7.0.0): https://github.com/gdi2290/angular-starter

### Expected Behavior

Webpack should reload only after a file is actually changed (saved/created/moved) in Windows 10.

### Actual Behavior

Webpack (v2.10.1) reloads when a file is just opened/accessed in Windows 10.
(This does not happen in Mac OS X, or when using an older version of webpack-server-dev like 2.7.1.)

This will also a trigger a loop of repeated compilations as it flags other files as "changed" because they were accessed during compilation. It will eventually stop the loop because it doesn't trigger the file change event if the file has been accessed very recently.

### For Bugs; How can we reproduce the behavior?

1) On Windows 10, clone a project with webpack and webpack-dev-server where watch is enabled, such as the starter project here (specifically version 7.0.0):
https://github.com/gdi2290/angular-starter
2) In package.json, update the webpack-server-dev version ("webpack-dev-server": "~2.7.1") to the latest version ("webpack-dev-server": "~2.10.1",) and save file.
3) Install and start the project.
4) Once it's up and running, open files that haven't been opened recently in the src directory, such as src/meta/robots.txt
5) Webpack will detect a change and reload/compile.

**Comment by HippieJosh** [comment]
I am having the same issue with Windows 7.

**Comment by nskarakoc** [comment]
I manged to overcome this issue by using this command: `webpack-dev-server --hot --inline`. Hope it works for you also.

**Comment by KlausKu** [comment]
Same here, under Windows 10.
on one Laptop it works correct, on a second Laptop - same Project - webpack updates if i open only a html file.

**Comment by michael-ciniawsky** [comment]
Does this also happen with `webpack-dev-server >= v3.0.0` ?

**Comment by KlausKu** [comment]
yes, on my laptops (both) 3.12.0

**Comment by jtavarez** [comment]
FWIW, I have a similar issue with Windows 7 and VS Code, but the issue comes up only with VS Code. There's something happening with the file watchers that it creates (related: https://github.com/Microsoft/vscode/issues/49683). Have you tried using Sublime or another editor?

For VS Code, limiting and opening a subset of the project folder seems to help, though it does still happen intermittently in my case.

**Comment by chen88** [comment]
It doesn't happen with Sublime. I'm also maintaining an outdated **grunt** project using VSCode which uses different live reload plugin, and that project has no such problem.

**Comment by AKArchy** [comment]
The code editor I'm using is Notepad++ (currently v7.5.8), opening individual files. (I can also reproduce the issue with plain old Windows 10 Notepad.)

**Comment by chen88** [comment]
I've updated to the latest Window 10 version through **Windows Update**, and it stops the recompiling/reload

**Comment by evilebottnawi** [comment]
@chen88 what editor you are use?

**Comment by chen88** [comment]
Visual Studio Code

**Comment by evilebottnawi** [comment]
@chen88 Can you try run dev server and change file using other editor?

**Comment by chen88** [comment]
I'm not saying it doesn't recompile on file save. Just saying the new windows update helps with the issue of random recompiling/reloading which the original poster and others are facing.

**Comment by evilebottnawi** [comment]
@AKArchy problem still exist? Can you create minimum reproducible test repo?

**Comment by shirleyR** [comment]
I get the same problem in Windows 10 when using VS Code 1.26.1,  sublime seems fine. webpack version is "webpack": "3.8.1" and  "webpack-dev-server": "2.11.1"

**Comment by evilebottnawi** [comment]
We already added tests for content base so we can close this.
