### ISSUE TITLE
Compilation Hangs

### ISSUE THREAD

**Issue by micahlmartin** [webpack/webpack-dev-server#128]
I'm trying to upgrade to iojs `1.5.1` from `1.2.0`. I'm running into an issue where it gets part way throught the precompilation and then just hangs.

```
$ webpack-dev-server --content-base public/ --config config/webpack/webpack.server.js --hot --port 25001 --inline --progress

 70% 3/3 build moduleshttp://localhost:25001/
webpack result is served from http://localhost:25001/assets/
content is served from /Users/micah/trackr/app/public
 69% 707/710 build modules
```

Here are the webpack modules I'm running:

```
"webpack-dev-server": "^1.7.0"
"webpack": "^1.7.3",
```

**Comment by prayerslayer** [comment]
Do you happen to have `sass-loader` in your configuration? Because I had the same issue and as soon as I changed `loaders: [style', 'css', 'autoprefixer', 'sass']` to `loader: 'file'` it didn’t hang anymore.

Of course the problem could also be any permutation of the other loaders, but I had issues with `sass-loader` before and dropping any one of the others doesn’t help.

**Comment by alexduan** [comment]
@prayerslayer I have sass-loader in my configuration and it is definitely causing my webpack to hang. Were you able to get past this? I'm using sass-loader 1.0.2 and node-sass 3.1.1.

**Comment by prayerslayer** [comment]
Not really, no. I converted my code to LESS in one project and in the other I stayed on `sass-loader@0.4.2` and `node-sass@2.0.1`—no problems there.

**Comment by eldh** [comment]
Also been getting this lately, also using sass-loader (1.0.1 & node-sass 3.0.0). Doesn't happen every time though.

**Comment by piotrf** [comment]
I have similar issue. It appens when I import one file (say `config.scss` holding all my variables) in differing modules’ .scss files (`header.scss`, `footer.scss` and so on…). Weirdly enough, it hangs when I load that `config.scss` in 3-4 places (and more) whereas it works alrite when loading it just in a couple of places.

Plus, when I load my `config.scss` in 2 module stylesheets, run the server, import that config in more stylesheets—it works and the bundle is recompiled. It doesn’t work after restarting the server. Hope that’s useful in some way.

**Comment by piotrf** [comment]
PS. Seems to be relate to [this](https://github.com/jtangelder/sass-loader/issues/100).

**Comment by mmahalwy** [comment]
Any updates on this?

**Comment by brandondurham** [comment]
Oh boy. Just added one new module and it's stalling. Works fine if I remove it.

**Comment by m00s** [comment]
+1

**Comment by yuzhenmi** [comment]
I ran Into this problem and found out that I had a typo in my import statement in some scss files, where I accidentally pointed to the wrong path. It no longer hanged after I fixed those.

**Comment by thiagopnts** [comment]
uh, same thing here

**Comment by nkbt** [comment]
`process.env.UV_THREADPOOL_SIZE = 100 webpack` works for me

**Comment by 9nix00** [comment]
@nkbt +1 

this works for me. thanks!

**Comment by aj0strow** [comment]
@nkbt thanks! Works for me too.

**Comment by nkbt** [comment]
New version of `node-sass` seems to fix the problem. At least on our projects we removed `UV_THREADPOOL_SIZE` completely. Update your `sass-loader` to >2.0.0

If it works fine for you too, then issue could be closed.

**Comment by brandondurham** [comment]
Updating worked for me!

**Comment by m00s** [comment]
Worked for me too updating `sass-loader`

**Comment by alexilyaev** [comment]
I'm still having an issue with this after updating `sass-loader` to `2.0.1`.
https://github.com/jtangelder/sass-loader/issues/100#issuecomment-143749823

**Comment by elsigh** [comment]
I still have this issue after updating `sass-loader` to `2.0.1` as well

**Comment by mark-norgate** [comment]
Anyone got a fix for this issue? I don't know if it's the sass-loader that is causing the issue; it seems to hang during/just after ts compilation. Don't seem to be able to get logs out of webpack to see what's upsetting it. --loglevel verbose doesn't seem to output much more.

**Comment by liebowitz** [comment]
@mark-norgate Try removing @import statements from your stylesheets one by one. This worked for me...

**Comment by mark-norgate** [comment]
I discovered a remedy for the problem; even if it is a bit smelly.

I changed this:

./node_modules/.bin/webpack-dev-server --display-reasons --display-chunks --watch --loglevel verbose

To this:

env UV_THREADPOOL_SIZE=128 ./node_modules/.bin/webpack-dev-server --display-reasons --display-chunks --watch --loglevel verbose

Works a treat. It’s the sass-loader that is having problems. Giving it more breathing room like this helps, but it’s still painfully slow.

Mark

**Comment by SpaceK33z** [comment]
Closing this issue because it doesn't seem to be a problem in webpack-dev-server. I'll gladly re-open if anyone can provide a reduced case where it fails.

**Comment by elsurudo** [comment]
I don't have a minimal case for this right now, but for what it's worth, I'm still encountering this issue.

**Comment by martinbliss** [comment]
@SpaceK33z This is an active issue. Issuing `webpack` alone works just fine (all files are processed and the process exits successfully) but `webpack-dev-server` hangs after the webpack compilation step but before the files actually get dumped to disk (I know this because I have a `CleanWebpackPlugin` step that gets executed causing the destination folder to get erased before the build.)

**Comment by chuckhacker** [comment]
Also experiencing this problem with a fairly minimal configuration with nothing too crazy in it.

[webpack.config.js.txt](https://github.com/webpack/webpack-dev-server/files/1142950/webpack.config.js.txt)

**Comment by chuckhacker** [comment]
This really needs re-opened.

**Comment by virtualfunction** [comment]
Still a **BIG** issue on on docker under OS X. Seems to be fine in native OS X or Linux (be it native or docker). For me webpack compiles but gets stuck when an asset get modified - It seems to be stuck in a deadlock (using low CPU)

**Comment by tfrijsewijk** [comment]
Same here inside docker on windows

**Comment by mohammedgqudah** [comment]
same :(

**Comment by peteromano** [comment]
+1 For re-opening.

This is happening with Windows WSL Ubuntu, as well. Mac OS X doesn't have an issue.

**Comment by sadortun** [comment]
Got the same issue on docker alpine. Anyone found a fix to this ?

**Comment by olegpopadko** [comment]
Compilation hangs for me on OSX host. @sadortun What host do you use?

**Comment by sadortun** [comment]
@olegpopadko i am building from a terminal

**Comment by evilebottnawi** [comment]
@peteromano can you create minimum reproducible test repo
@sadortun do you use wsl too?

**Comment by aizen3** [comment]
same issue with me with vue cli

**Comment by ChristopherHaws** [comment]
I'm having this issue as well, but it seems to be caused by `CleanWebpackPlugin`. When I remove it, webpack-dev-server no longer hangs.

**Comment by jchook** [comment]
For me using `https: true` caused `webpack-dev-server` to hang indefinitely.

**Comment by sadortun** [comment]
@evilebottnawi No, i am building in an alpine image

**Comment by ARtSSt** [comment]
> @evilebottnawi No, i am building in an alpine image

were able to resolve this, I am having the same issue
I am getting no error or logs, it's hanging in Docker
