### ISSUE TITLE
request location don't request server

### ISSUE THREAD

**Issue by TongDaDa** [webpack/webpack-dev-server#1280]
i config proxy in webpackServer.js, but request location don't to server;

//webpack-dev-server version :  "^2.5.0"
```js
  // server.js

let server = new WebpackDevServer(compiler, {
    publicPath: "/",
    stats: {colors: true,chunks:false},
    proxy: {
	    "/api": {
            target: REQUEST_URL, //http://120.78.12.39:8090
            changeOrigin: true
        }
    }
}).listen(8080);


in borwser request 

ERROR : main.0102bdce72f47612cd7a.js:104561 POST http://127.0.0.1:8080/api/materiel/list 404 (Not Found)

```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
