### ISSUE TITLE
Add support for not having to pin strip-ansi

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-dev-server#1286]
Currently we've had to pin @sindresorhus's strip-ansi because of the use of arrow functions. We should essentially make whatever changes needed to allow us to use that code (transpilation etc.) so that it still works for strip-ansi@4+ but without breaking IE 11 compat. 

See https://github.com/webpack/webpack-dev-server/pull/1273

**Comment by evilebottnawi** [comment]
@TheLarkInn need patch release after merge, otherwise `babel` would be a more rational solution

**Comment by lydell** [comment]
See #1279 for a potential solution of running node_modules through Babel.

**Comment by TheLarkInn** [comment]
I have an issue to add this but for now since it's breaking current
implementations I'd like to see pin and patched.

**Comment by wayofthefuture** [comment]
Broke the entire build

**Comment by kaiyoma** [comment]
This is causing issues with our project too. If I try to upgrade to the latest version, I start getting yarn errors:

```
error "nyc#string-width#strip-ansi" is wrong version: expected "4.0.0", got "3.0.1"
warning "nyc#string-width#strip-ansi#ansi-regex@^2.0.0" could be deduped from "2.1.1" to "ansi-regex@2.1.1"
error "nyc#strip-ansi#ansi-regex" is wrong version: expected "3.0.0", got "2.1.1"
error Found 2 errors.
```

We're currently on version 2.10.0 and would like to upgrade as the dev server is broken in IE11 in this version.

**Comment by robvree** [comment]
This is also breaking our dev build in IE11. Running node_modules through babel is not a solution. Everything in node_modules should already be transpiled.

**Comment by robvree** [comment]
Update: Updating from 2.11.0 to 2.11.1 (which uses v3 of strip-ansi) and moving my polyfill for es6-object-assign above the first import in my entry point (not sure if this is related) has fixed my IE11 build.

```
// polyFills for IE11 that need to run before the imports
require("es6-object-assign").polyfill();

// react-hot-loader must come before importing React
import "react-hot-loader";
import * as React from "react";
import { render } from "react-dom";
import App from "./staffhub/sh-application/components/App";
import DateUtils from "sh-application/utility/DateUtils";
import StringsStore from "sh-strings/store";
import { loadTheme } from "@uifabric/styling";
import { preinitApplication } from "sh-application";
import { initializeIcons } from "@uifabric/icons";

// polyFills for IE11
require("es6-promise").polyfill();
require("string.prototype.startswith");
require("element-closest");
require("ie-array-find-polyfill");
require("array.from").shim();
require("array.prototype.findIndex").shim();
```

**Comment by evilebottnawi** [comment]
Done for v4
