### ISSUE TITLE
Webpacker can't find hello-world-bundle.js ..please help me

### ISSUE THREAD

**Issue by luandevpro** [webpack/webpack-dev-server#1288]
Webpacker can't find hello-world-bundle.js in /home/luandevpro/Music/my-app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).
