### ISSUE TITLE
can I use myself process argv in cli

### ISSUE THREAD

**Issue by shangxinbo** [webpack/webpack-dev-server#1290]
How can I transfer myself process argv in cli. like this :
```
webpack-dev-server --myargv --config build/webpack.dev.conf.js
```
of that , `myargv` is myself argv to use in webpack.dev.conf.js

**Comment by shangxinbo** [comment]
now it throw an error like this :
```
Unknown argument: myargv 
```

**Comment by SpaceK33z** [comment]
You can use environment variables for this use-case.
