### ISSUE TITLE
webpack + docker

### ISSUE THREAD

**Issue by Drewster727** [webpack/webpack-dev-server#1291]
I'm currently trying to spin up a docker container using the following stack:
asp.net core 2
angular 5+

* Operating System: Win10
* Node Version: 8.9.3
* NPM Version: 5.5.1
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.11.1

I have posted on the aspnetcore docker issues board, but to no avail. I'm basically running into an issue where I'm spinning up a docker container, installing all npm dependencies, but at the very end it fails out saying it can't find a webpack-dev-server folder under node_modules. It's confusing. I have tried many different things to try and fix this. I don't care to hot-reload inside of a container, I'm just trying to get my web app into a container so I can make sure it works before pushing up to other environments (stage/prod).

Webpack appears to be what's holding me up. Any ideas?

update: I just noticed that if I specify npm install webpack-dev-server in my package.json, then run the docker build again, it complains about another dependency. Why is this not happening in my local environment? These aren't global packages.

### Expected Behavior
I expect the docker container  to spin up.

Dockerfile
```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY package.json ./
RUN curl -sL https://deb.nodesource.com/setup_8.x |  bash -
RUN apt-get install -y build-essential nodejs
RUN npm install -g @angular/cli@1.6.3 webpack@3.10.0
RUN npm install
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "XYZ.Web.dll"]
```

### Actual Behavior

  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
  npm ERR! Linux 4.9.60-linuxkit-aufs
  npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
  npm ERR! node v6.12.3
  npm ERR! npm  v3.10.10
  npm ERR! path /app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug
  npm ERR! code ENOENT
  npm ERR! errno -2
  npm ERR! syscall rename

  npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug' -> '/app/node_modules/babel-traverse/node_modules/debug'
  npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/webpack-dev-server/node_modules/expand-brackets/node_modules/debug' -> '/app/node_modules/babel-traverse/node_modules/debug'
  npm ERR! enoent This is most likely not a problem with npm itself
  npm ERR! enoent and is related to npm not being able to find a file.
  npm ERR! enoent

  npm ERR! Please include the following file with any support request:
  npm ERR!     /app/npm-debug.log
/app/XYZ.Web.csproj(108,5): error MSB3073: The command "npm install" exited with code 254.

**Comment by aikrez** [comment]
Might check versions out:
Versions used in docker
> npm ERR! node v6.12.3
> npm ERR! npm v3.10.10

And you want

> Node Version: 8.9.3
> NPM Version: 5.5.1

**Comment by Drewster727** [comment]
@aikrez thanks man -- I eventually got this working (not long after I posted), I did upgrade my node and npm as you said. Forgot to close this!
