### ISSUE TITLE
Document available CLI flags/Options

### ISSUE THREAD

**Issue by gDelgado14** [webpack/webpack-dev-server#1294]
I'd like to submit a PR linking from the README to the [Options Schema](https://github.com/webpack/webpack-dev-server/blob/master/lib/optionsSchema.json).

The schema already documents everything well, no need to rewrite it. Simply having a link to the optionsSchema.json would suffice. 

Is this PR welcome?

**Comment by evilebottnawi** [comment]
@gDelgado14 PR welcome, also please don't remove issue template

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-dev-server/pull/1632
