### ISSUE TITLE
webpack-dev-server not build file

### ISSUE THREAD

**Issue by starcwl** [webpack/webpack-dev-server#1298]
webpack.config.js:
```
  devServer:{
    inline: true,
    contentBase:'./',
    port:3000
  },
```
after I change about.js in my project. It outputs:
```
webpack: Compiling...
Hash: ba77a3145fee91718778
Version: webpack 3.10.0
Time: 28ms
          Asset       Size  Chunks             Chunk Names
about.bundle.js  444 bytes       1  [emitted]  about
 + 2 hidden assets
  [23] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {2} [built]
  [27] ./dist/about.js 188 bytes {1} [built]
    + 34 hidden modules
webpack: Compiled successfully.
```

after I changed the code. The calculation of the size of "about.bundle.js" in the log seems right. But the file "about.bundle.js" not changed.   So the page not refresh and reload.

How could I debug this bug?  

below is the project file link:
[https://dev.whosdog.com/webpack.zip](url)

* Operating System:  
* Node Version: v6.11.2
* NPM Version: 3.10.10
* webpack Version: 3.10.0
* webpack-dev-server Version:2.11.1

- [X] This is a **bug**

**Comment by bhatnagardivyanshu** [comment]
Did you get it fixed?
