### ISSUE TITLE
404 on bundle

### ISSUE THREAD

**Issue by jehoshua02** [webpack/webpack-dev-server#130]
To reproduce the issue:

```shell
git clone https://github.com/jehoshua02/react-scaffold.git
cd react-scaffold
npm install
npm run serve
```

Open the console and you'll see the 404:

```console
Failed to load resource: the server responded with a status of 404 (Not Found)
```

I'm still pretty new to the React ecosystem so I'm having a hard time understanding why this isn't working. Otherwise I'd have a pull request for you. I had it working earlier today (I think, or at least I'm pretty sure, unless I'm crazy). But now it's not working because the browser can't find the bundle.

**Comment by sokra** [comment]
your `output.filename` is wrong. add `output.path`.
