### ISSUE TITLE
My webpack configuration is too slow on large project

### ISSUE THREAD

**Issue by nimatullah** [webpack/webpack-dev-server#1300]
* Operating System Ubuntu
* Node Version: 6.3.0
* NPM Version: 5.6.0
* webpack Version: 3.1.0
* webpack-dev-server Version: 2.11.1

- [ ] This is a **bug**
- [ ] This is a **modification** request

I had three projects, which was running on three different port. I have merged all project, and it is running on one port now.

It is a large project, which has more than 2k files, but when I run npm start, it takes 10 to 60 minutes at the beginning. It start faster when I run npm start for the second time.

The same thing happens with build.
### Code

Link : https://github.com/nimatullah/job-minimal

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

**Comment by SpaceK33z** [comment]
This is not webpack-dev-servers fault. All bundling logic is in the https://github.com/webpack/webpack repository. Be sure to try out the latest webpack v4 beta, that should be a lot faster.
