### ISSUE TITLE
"Unknown argument: env" with webpack-dev-server@next

### ISSUE THREAD

**Issue by esausilva** [webpack/webpack-dev-server#1304]
* Operating System: macOS 10.12.6
* Node Version: v8.9.1
* NPM Version: 5.6.0
* webpack Version: 4.0.0-beta.1
* webpack-dev-server Version: ^3.0.0-alpha6

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Links to webpack configurations

[webpack.dev.js](https://github.com/esausilva/react-starter-boilerplate-hmr/blob/webpack4/build-utils/webpack.dev.js)
[webpack.common.js](https://github.com/esausilva/react-starter-boilerplate-hmr/blob/webpack4/build-utils/webpack.common.js)

[package.json](https://github.com/esausilva/react-starter-boilerplate-hmr/blob/webpack4/package.json)

### Actual Behavior

I get `Unknown argument: env` when I run my project with `yarn dev`

```
$ yarn dev
yarn run v1.3.2
$ webpack-dev-server --env.env=dev
webpack-dev-server 3.0.0-alpha6
webpack 4.0.0-beta.1
Usage: https://webpack.js.org/configuration/dev-server/

Connection options:
  --allowed-hosts       A comma-delimited string of hosts that are allowed to
                        access the dev server                           [string]
...

Unknown argument: env
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### For Bugs; How can we reproduce the behavior?

```
git clone https://github.com/esausilva/react-starter-boilerplate-hmr.git
git checkout webpack4
yarn
yarn dev
```

**Comment by AMar4enko** [comment]
@esausilva unless PR has been merged (or fixed different way) feel free to use 
https://github.com/AMar4enko/webpack-dev-server#5c4892dd77e88d0c269912525e2ed717f0dd3c3e

Fix is dead simple

**Comment by esausilva** [comment]
@AMar4enko it works thanks.

**Comment by SpaceK33z** [comment]
Please test the latest beta, `webpack-dev-server@3.0.0-beta.1`. Also be sure to read [the changelog](https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0-beta.1).

**Comment by esausilva** [comment]
@SpaceK33z Updated to the latest beta, it is now accepting the `--env` and `--config` flags. Thanks.
