### ISSUE TITLE
Browser automatically open can't be disabled

### ISSUE THREAD

**Issue by vzorge** [webpack/webpack-dev-server#1305]
* Operating System: Windows 10
* Node Version: 8.9.3
* NPM Version: 4.5.0
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.11.1

- [x] This is a **bug**
- [ ] This is a **modification** request

When I set the open flag to false, it does not prevent the browser from opening.
In my webpack.config.js:
devServer: { open: false }

### Expected Behavior
I expect the browser NOT to open

### Actual Behavior
The browser opens

### For Bugs; How can we reproduce the behavior?
Self explanatory. Even a simple server with 'open:false' will still have this bug.

**Comment by vzorge** [comment]
Ok turned out someone had started the webserver with the --open option.

**Comment by kasaiee** [comment]
I have webpack 4 but this is not working

**Comment by xgqfrms** [comment]
@kasaiee try this

> modify your `package.json` file, like below code shows

```js
{
  "scripts": {
    "dev": "webpack-dev-server --open --config ./build/webpack.config.js",
  }
}
```
