### ISSUE TITLE
OutPath is not valid in the configuration property

### ISSUE THREAD

**Issue by vibingopal** [webpack/webpack-dev-server#1306]
Hi Team,

I have upgraded my webpack versions in my angular project. But now after the upgrade iam getting the below error in the webpack-dev-server configuration. Could you please let me know anything iam missing after upgrade?

> > Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the AP
> I schema.
>  - configuration has an unknown property 'outputPath'.

* Node Version:6.10.1
* NPM Version:4.4.1
* webpack Version:3.10.0
* webpack-dev-server Version:2.9.7

- [x ] This is a **bug**
### Code

```js
  // webpack.config.js
   devServer: {
            port: METADATA.port,
            host: METADATA.host,
            historyApiFallback: true,
            watchOptions: {
                aggregateTimeout: 300,
                poll: 1000
            },
          outputPath: helpers.root('dist')
        },

```

**Comment by evilebottnawi** [comment]
@vibingopal webpack-dev-server don't have `outputPath` option. Example:
```
module.exports = {
       output: { 
           path: helpers.root('dist')
       },
       devServer: {
            port: METADATA.port,
            host: METADATA.host,
            historyApiFallback: true,
            watchOptions: {
                aggregateTimeout: 300,
                poll: 1000
            }
        }
}
```
