### ISSUE TITLE
Proxy bypass PUT/POST not as expected

### ISSUE THREAD

**Issue by leegee** [webpack/webpack-dev-server#1307]
* Operating System: OS X 10.13.3
* Node Version: v6.12.3
* NPM Version: 3.10.10
* webpack Version: 3.10.0
* webpack-dev-server Version: 2.11.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Relevant config:

https://gist.github.com/leegee/5e44b0205ef820925d2e659cf6f33991

### Expected Behavior

When the bypass option is provided and is a function, its return value should either act as a new URL if a string, or be ignored if false.

### Actual Behavior

Works beautifully for GET requests, but the returned string seems to be ignored for POST and PUT requests.

### For Bugs; How can we reproduce the behavior?

Please use the proxy bypass function to rewrite a URL by returning a string — compare the resulting behaviour for GET and POST / PUT requests.

**Comment by SpaceK33z** [comment]
Are you interesting in submitting a PR?

**Comment by leegee** [comment]
Perhpas I misconfigured?

**Comment by evilebottnawi** [comment]
@leegee friendly ping, problem still exists? If yes, please create minimum reproducible test repo, thanks

**Comment by leegee** [comment]
Sorry I don't know, I moved on from that shortly afterwards. But thanks for checking.

**Comment by evilebottnawi** [comment]
@leegee thanks for answer, let's close issue, if somebody will has same problem feel free to create new issue
