### ISSUE TITLE
/webpack-dev-server serves directory listing instead of application

### ISSUE THREAD

**Issue by ivan** [webpack/webpack-dev-server#131]
http://webpack.github.io/docs/webpack-dev-server.html#hot-mode-with-indication tells me to navigate to `localhost:8080/webpack-dev-server`, but that URL serves me a very sparse directory listing instead of my application.  I have to add a trailing slash and navigate to `localhost:8080/webpack-dev-server/` instead to see my application.

Not sure if the docs need to be fixed, or if the slash-free path needs to redirect.

**Comment by sokra** [comment]
Docs need to be fixed...

**Comment by jasonlam0619** [comment]
Say you wanted to render the `index.html` under `/public` in the first place.

Try add configs below into your `webpack.config.js`:

    devServer: {
        contentBase: "./public",
        hot: true
    },

And it shall work.
