### ISSUE TITLE
devServer.public from window.location

### ISSUE THREAD

**Issue by zerkms** [webpack/webpack-dev-server#1312]
The documentation https://webpack.js.org/configuration/dev-server/#devserver-public at says

> When using inline mode and you're proxying dev-server, the inline client script does not always know where to connect to. It will try to guess the URL of the server based on window.location, but if that fails you'll need to use this.

Is it still the case? It looks like if `public` is not specified it reverts to `http://localhost:8080`.

At least the webpack generates `/* WEBPACK VAR INJECTION */}.call(exports, "?http://localhost:8080"))` for the `webpack-dev-server` client.

I also could not find any relevant traces of `window.location` in the source code.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
