### ISSUE TITLE
Allow --entry to be specified

### ISSUE THREAD

**Issue by eddyw** [webpack/webpack-dev-server#1314]
* Operating System: MacOS
* Node Version: v9.3.0
* NPM Version: 5.5.1
* webpack Version: 4.0.0-beta.2
* webpack-dev-server Version: 3.0.0-alpha6

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
const webpack = require('webpack')
const babel_presets = [
	'@babel/env',
	'@babel/react',
]
const babel_plugins = [[
	'transform-class-properties',
	{ 'spec': true },
]]
const babel_rule = {
	test: /.js$/,
	exclude: /node_modules/,
	use: {
		loader: 'babel-loader',
		options: {
			presets: babel_presets,
			plugins: babel_plugins,
		},
	},
}
module.exports = {
	output: {
		filename: 'app.js',
	},
	mode: 'development',
	module: { rules: [babel_rule] },
}
```
Running `webpack-dev-server --entry file` displays:
```js
Unknown argument: entry
```

### Expected Behavior
It should use the provided file as entry.

### Actual Behavior
Displays an error

### For Features; What is the motivation and/or use-case for the feature?
Be able to use a single Webpack configuration file to run on multiple SPAs. For instance:
```
.
├── src 
     ├── 1.HelloWorld 
          └── hello.js 
     └── 2.Example 
          └── example.js 
├── webpack.config.js
└── package.json 
```
If allowed to do:
```
webpack-dev-server --entry ./src/1.HelloWorld
webpack-dev-server --entry ./src/2.Example
```

**Comment by evilebottnawi** [comment]
Partially implemented, you can use `injectClient` and `injectHot` options to control what entry should have client code or hot code

**Comment by evilebottnawi** [comment]
We move our CLI to `webpack-cli` for future version, also it is impossible to build only one entry point. Options above should be enough for some non-standard configurations. Anyway feel free to feedback if you disagree. Thanks for using webpack.
