### ISSUE TITLE
webpack-dev-sever HMR do not works, only working full reload behavior 

### ISSUE THREAD

**Issue by hg-pyun** [webpack/webpack-dev-server#1315]
* Operating System: MacOS
* Node Version: 8.9.0
* webpack Version: 3.11.0
* webpack-dev-server Version: 2.11.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: [
        'react-hot-loader/patch',
        path.resolve(__dirname, '../src/index.js')
    ],
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, "../dist"),
        publicPath: "/"  // different
    },
    devServer: {
        hot: true,
        publicPath: '/js',   // different
        contentBase: path.join(__dirname, '../src/html/index.html'),
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: [{
                loader: "babel-loader",
                options: {
                    presets: ['env', 'stage-2', 'react'],
                    plugins: [                    
                        'react-hot-loader/babel',
                        'transform-runtime'
                    ]
                }
            }]
        },]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
}
```
### Expected Behavior
HMR works. 

### Actual Behavior
When the code is modified, the whole is reloaded.

### For Bugs; How can we reproduce the behavior?
I have found that the HMR does not work properly if the publicPath of the output field and the publicPath of devServer do not match. I hope it will work even if the 'output' and 'devServer' public paths are different.

**Comment by engalar** [comment]
use 2.11.0 instead (just workaround)

**Comment by haegul** [comment]
Matching 'publicPath' works fine.

**Comment by FLighter7** [comment]
I have the following structure:
```
dest
    index.html
node_modules
src
    index.css
    index.js
package-lock.json
package.json
webpack.config.js
```
And code:
**package.json**
```
{
    "name": "test",
    "author": "test",
    "license": "MIT",
    "version": "1.0.0",
    "main": "index.js",
    "devDependencies": {
        "css-loader": "^0.28.9",
        "extract-text-webpack-plugin": "^3.0.2",
        "webpack": "^3.11.0",
        "webpack-cli": "^2.0.9",
        "webpack-dev-server": "^3.0.0"
    }
}
```
**index.html**
```
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div>Hello world!</div>
    <script src='script.js'></script>
</body>
</html>
```
**index.css**
```
div{
    color: red;
}
```
**index.js**
```
import './index.css';
```
**webpack.config.js**
```
const ExtractCSS = new (require('extract-text-webpack-plugin'))('style.css');

module.exports =
{
    entry:      `${__dirname}/src/index.js`,
    output: {
        path:       `${__dirname}/dest`,
        filename:   'script.js?[hash]',
        publicPath: '/',
    },
    module: {
        rules: [{
            test: /\.css$/,
            use: ExtractCSS.extract('css-loader')
        }]
    },
    plugins: [ExtractCSS],
    devServer: {
        contentBase: `${__dirname}/dest`,
        publicPath: '/',
    }
}
```

If I use `webpack` - OK
If `webpack-dev-server` - OK, with full page reloading
If `webpack-dev-server --inline` - OK, with full page reloading
If `webpack-dev-server --inline --hot` or `webpack-dev-server --inline --hot --hot-only` - Error, because HMR doesn't work. Only full page reloading, if I change `index.js`. But if `index.css` was changed `webpack-dev-server` compiles a new bundle, but in Chrome console I see:
```
[HMR] Checking for updates on the server...
[HMR] Nothing hot updated.
[HMR] App is up to date.
```
Why "nothing" ?
**Does someone know the solution?**

P.S. `webpack`, `webpack-dev-server`, `webpack-cli` are installed in global and local scope.

**Comment by haegul** [comment]
@FLighter7 
You should use HMR Plugin.
https://webpack.js.org/guides/hot-module-replacement/
```
 plugins: [
+     new webpack.NamedModulesPlugin(),
+     new webpack.HotModuleReplacementPlugin()
    ],
```

**Comment by FLighter7** [comment]
The problem was in `extract-text-webpack-plugin`.
Based on [No Hot Module Replacement #222](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/222)
With `style-loader` everything is okay.

**Comment by codepushr** [comment]
**Getting another error with version 3.1.2**
(using standard style-loader + css-loader)

Changing the background color from `red` to `blue`:
```
[Info] [WDS] App updated. Recompiling... (bundle.js, line 27131, x2)
[Info] [WDS] App hot update... (bundle.js, line 27274)
[Error] TypeError: undefined is not an object (evaluating 'lastHash.indexOf')
	upToDate (bundle.js:27651)
	(anonymous function) (bundle.js:27695)
	emit (bundle.js:1176)
	reloadApp (bundle.js:27277)
	ok (bundle.js:27190)
	onmessage (bundle.js:27494)
	dispatchEvent (bundle.js:20222)
	(anonymous function) (bundle.js:20935)
	forEach
	_transportMessage (bundle.js:20933)
	(anonymous function)
	emit (bundle.js:20138)
	onmessage (bundle.js:23009)
```

However everything is working with version 3.0.0:
```
[Info] [WDS] App hot update... (bundle.js, line 27274)
[Log] [HMR] Checking for updates on the server... (bundle.js, line 27804)
[Log] [HMR] Updated modules: (bundle.js, line 27804)
[Log] [HMR]  - ./src/style.css (bundle.js, line 27796)
[Log] [HMR]  - ./node_modules/css-loader/index.js!./src/style.css (bundle.js, line 27804)
[Log] [HMR] App is up to date. (bundle.js, line 27804)
```

**Comment by createdbyjurand** [comment]
in
`package.json`
change
`"serve": "vue-cli-service serve",`
to
`"serve": "vue-cli-service serve --host localhost",`

**Comment by jayarjo** [comment]
Shouldn't HMR work with modules too? I thought that's what hype was about, why it only works for CSS?

**Comment by martinchristov** [comment]
Had the same (or very similar) issue. My resolution was to add a:
```
<base href="/project-directory/" />
```
to the index.html

**Comment by NickWoodward** [comment]
I had a similar problem with full page reloading.

Using `devServer: { watchContentBase: true }` was the cause for me. Which I guess makes sense?
