### ISSUE TITLE
Loading the app from subroutes works only when publicPath is /

### ISSUE THREAD

**Issue by arloduff** [webpack/webpack-dev-server#1325]
* Operating System:
* Node Version: 9.4.0
* NPM Version: 5.6.0
* webpack Version: 3.7.1
* webpack-dev-server Version: 2.9.2

- [ x ] This is a **bug**
- [ ] This is a **modification** request

### Code

https://gist.github.com/arloduff/e8fa0b1a54e379bad356c940c231d5d7

### Expected Behavior
Developing single-page apps using React or Angular requires the server to always deliver the root `/index.html` page. For example, if a user navigates to `/foo/bar`, the `index.html` page should still be hit, so that the application can be loaded and its built-in router can determine how to handle the `/foo/bar` request. Otherwise, the request would result as a 404, even though `/foo/bar` may be a valid route in the application.

### Actual Behavior
With the above configuration, I've found that only hitting `/bar/` works. If I try to hit a route I've defined within my Angular application, such as `/bar/foo`, I get the standard `Cannot GET /bar/foo` Express server error. The dev server should be able to load any pages within the `publicPath`.

I have discovered that setting the `publicPath` to `/` results in desired behavior; however, this is not suitable for my project, as I want this application to be able to live inside a subdirectory when it goes to production.

### For Bugs; How can we reproduce the behavior?
This should be reproducible by using the configuration above, and creating a basic Angular app.

**Comment by SpaceK33z** [comment]
How exactly would you propose that it works then? As I see it, this just means you need to change the `publicPath` based on whether you are building for development and production.

**Comment by arloduff** [comment]
I'm currently trying to do that as a workaround, but my thinking is that if the `publicPath` is `/foo` then anything inside `/foo` such as `/foo/bar` or `/foo/bar/goo` should also redirect to that `index.html`. Or if that's not one of the purposes of `publicPath`, then perhaps another variable to specify what the home route of your application is.

**Comment by SpaceK33z** [comment]
You can configure this already in great detail, see the docs: https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

**Comment by arloduff** [comment]
Thanks, had been looking at that, but maybe I had misunderstood the documentation.
