### ISSUE TITLE
Wrong Hot Module Replacement

### ISSUE THREAD

**Issue by uuhan** [webpack/webpack-dev-server#1328]
* Operating System: mac
* Node Version: v9.6.1
* NPM Version: v5.6.0
* webpack Version: v4.0.1
* webpack-dev-server Version: v3.1.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
 module.exports = {
      mode: 'development'
      ...
}
```

### Expected Behavior

Done right.

### Actual Behavior

SyntaxError: missing ) after argument list

I looked into the detailed produced bundle and found that there were some different codes (compared to the bundle generated by webpack-3.10.0):

webpack-4.0.1, webpack-dev-server-3.1.0:

```js
// Hot Module Replacement
if(true) {
	// When the styles change, update the <style> tags
	if(!content.locals) {
		module.hot.accept(/*! !../../../../css-loader!../../../../less-loader/dist/cjs.js!./index.less */ "./node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/antd/lib/alert/style/index.less"/*! !../../../../css-loader!../../../../less-loader/dist/cjs.js!./index.less */ "./node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/antd/lib/alert/style/index.less", function(__WEBPACK_OUTDATED_DEPENDENCIES__) { (function(__WEBPACK_OUTDATED_DEPENDENCIES__) { (function() {
			var newContent = __webpack_require__(/*! !../../../../css-loader!../../../../less-loader/dist/cjs.js!./index.less */ "./node_modules/css-loader/index.js!./node_modules/less-loader/dist/cjs.js!./node_modules/antd/lib/alert/style/index.less");
			if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];
			update(newContent);
		})(__WEBPACK_OUTDATED_DEPENDENCIES__); })(__WEBPACK_OUTDATED_DEPENDENCIES__); });
	}
	// When the module is disposed, remove the <style> tags
	module.hot.dispose(function() { update(); });
}
```

webpack-3.10.0, webpack-dev-server-2.11.0:

```js
// Hot Module Replacement
if(true) {
	// When the styles change, update the <style> tags
	if(!content.locals) {
		module.hot.accept(285285, function() {
			var newContent = __webpack_require__(285);
			if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];
			update(newContent);
		});
	}
	// When the module is disposed, remove the <style> tags
	module.hot.dispose(function() { update(); });
}
```

**As you can see, there is a syntax error in **line 5** of the bundle file produced by webpack-4.0.1**

**If I dont set the webpack mode to *development*, there is no HMR code in the bundle, then, everything goes well**

**Comment by SpaceK33z** [comment]
webpack-dev-server doesn't do anything related to generating code, so I'm pretty sure this is a bug in webpack itself.

**Comment by kjellski** [comment]
I've got the exact same issue, just updated all packages to the very latest versions:

    "react-hot-loader": "^4.0.0",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.10",
    "webpack-dev-server": "^3.1.0"

**Comment by JannesMeyer** [comment]
In another issue it was mentioned that this is happens when you include the `HotModuleReplacementPlugin` twice. Apparently the `--hot` flag adds it to your plugins automatically.

**Comment by uuhan** [comment]
@JannesMeyer Thanks, it works fine when I remove the HotModuleReplacementPlugin.
