### ISSUE TITLE
Publish 2.7.1 as differently named npm module

### ISSUE THREAD

**Issue by dave-irvine** [webpack/webpack-dev-server#1336]
So this might be a bit of a long shot, but I need to debug my apps in old IE (pity me), but I'd like to use newer webpack-dev-server version for other browsers.

Due to npm restrictions, I can't list two versions of webpack-dev-server in my package.json, so what I'm requesting is that you publish webpack-dev-server@2.7.1 to npm as a separate package name (webpack-dev-server-old or similar) so that I can add both to my package.json and then use the relevant one depending on which environment I'm debugging.

I know the Caveats section of the readme, but I'm not really asking for a code change and this should be a one-time job as the 2.7.1 release is locked.

Thanks for reading!

**Comment by ooflorent** [comment]
You can add the following to your `package.json`:

```json
{
  "devDependencies": {
    "webpack-dev-server-old": "npm:webpack-dev-server@2.7.1"
  }
}
```

**Comment by dave-irvine** [comment]
@Ooflorent that only works in yarn, not npm

**Comment by ooflorent** [comment]
`github:` is also supported

**Comment by ooflorent** [comment]
Hmm, you are right. `npm` does not support package renaming. However, we won't publish the package under a different name. The remaining options are:

1. use `yarn` (best)
1. create a local package `webpack-dev-server-old` which has a dependency to `webpack-dev-server@2.7.1` so npm will install both
1. publish `webpack-dev-server-old` for yourself (worst)
