### ISSUE TITLE
auto reload doesn't reload javascript

### ISSUE THREAD

**Issue by acthp** [webpack/webpack-dev-server#134]
The server reloads the application frame after a rebuild (by calling location.reload, looks like), however this doesn't result in fresh javascript in the browser. Is there some trick to making the reload actually load the new build? An http header that should be set, a file hash, or something?

**Comment by acthp** [comment]
Turning *off* chrome's "Disable cache (while DevTools is open)" feature allows it to reload properly.

I don't understand the root cause, though I note that with "Disable cache" the request from chrome includes "pragma no-cache", while without "Disable cache" it includes "Cache-control max-age=0". Perhaps "no-cache" is affecting the express server in a perverse fashion.

I thought express included etags by default, but I don't see etags in the header in either case.

**Comment by acthp** [comment]
Testing FF, reloading works with or without their "Disable cache" dev option. Still not sure of the root cause of the problem on Chrome. I note that FF in "Disable cache" mode sets both "pragma no-cache" and "cache-control no-cache".

**Comment by MrOrz** [comment]
As far as I know, Google Chrome caches static files quite aggressively. If you spin up other web servers (like `python -m SimpleHTTPServer`) and browse it using Chrome, you may also need to hit reload several times to get the modified JS come into play.

**Comment by SpaceK33z** [comment]
Closing because this is a Chrome issue and the dev-server already does what it can (setting no-cache headers) to prevent this.
