### ISSUE TITLE
Live bundle not loading again on V3.1.0, due to Jquery.

### ISSUE THREAD

**Issue by iliran11** [webpack/webpack-dev-server#1340]
* Operating System: Windows 10
* Node Version: 8.9.3
* NPM Version: 5.51
* webpack Version: 4.1.1
* webpack-dev-server Version: 3.1.0

- [X] This is a **bug**
- [ ] This is a **modification** request

This Issue is related to this Issue: https://github.com/webpack/webpack-dev-server/pull/1329
getting an error `jQuery.Deferred exception: n(...) is not a function TypeError: n(...) is not a function`

While `3.0.0-alpha6` is installed, this issue is resolved.
However, while upgrading to `3.1.0` this issue still persist.

**Comment by SpaceK33z** [comment]
Published `webpack-dev-server@3.1.1` with the fix.
