### ISSUE TITLE
how web-pack communicate in different application have dependency??

### ISSUE THREAD

**Issue by dileepkumar19** [webpack/webpack-dev-server#1349]
if two different applications dependent on one another how web pack will load the modules ??
if i try to add reference of one web-pack application output file in another application its showing error to inject dependent module .

**Comment by SpaceK33z** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
