### ISSUE TITLE
"Syntax error: Unexpected token <" with webpack-dev-server and HotModuleReplacingPlugin

### ISSUE THREAD

**Issue by voronianski** [webpack/webpack-dev-server#135]
Duplicating https://github.com/babel/babel-loader/issues/43 here too, 'cause I really cannot figure out what's causes that issue and it looks like webpack's stuff.

**Comment by gaearon** [comment]
Can you compare your setup with https://github.com/gaearon/react-hot-boilerplate?

**Comment by voronianski** [comment]
@gaearon I've did it.. The only difference is that I'm using CLI instead of Node.js API.

**Comment by voronianski** [comment]
@gaearon @sokra demo repo with reproducible bug might help - https://github.com/voronianski/webpack-trouble-demo

**Comment by gaearon** [comment]
I just realized you have two servers. Here's your problem: your app runs on other port than WebpackDevServer but the publicPath is `/build/`, so Webpack runtime requests hot updated script at `/build/`, which is served by your Express app.

Setting `publicPath` explicitly to `http://localhost:8080/build/` should help. I think there's also some other more idiomatic way of doing this but this is what I can help with.

**Comment by voronianski** [comment]
@gaearon yep, setting `publicPath` explicitly to `http://localhost:8080/build/` solved this error :+1:

**Comment by gaearon** [comment]
Added to troubleshooting. https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#syntax-error-unexpected-token-

**Comment by voronianski** [comment]
@gaearon thanks! Probably now issue can be closed.

**Comment by highdali** [comment]
`<script src="/bundle.js"></script>` not <script src="bundle.js"></script>`

**Comment by imtmh** [comment]
@voronianski , I got the similar issue on production, I don't think the same approach works here for me. Any help?

**Comment by sunlee-newyork** [comment]
I had to delete the bundled file after everything else and rerun the build, if anyone else is experiencing issues.
