### ISSUE TITLE
Just create a single normal HTML file

### ISSUE THREAD

**Issue by joeyhub** [webpack/webpack-dev-server#1352]
Is is possible to have web pack simply make a normal HTML file with one style tag and one script tag while not using webpack's require system?

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).
