### ISSUE TITLE
Recompile from file system when loader dependency updates.

### ISSUE THREAD

**Issue by cmseaton42** [webpack/webpack-dev-server#1354]
* Operating System: Windows
* Node Version: 9.8.0
* NPM Version: 5.7.1
* webpack Version: 4.1.1
* webpack-dev-server Version: 3.1.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  ...
  module: {
   rules: [
   ...
   {
     test: /\.docthat$/, // config file that specifies site directory and other info
     use: [
       {
          loader: path.resolve(__dirname, "./loaders/doc-loader")
       }
     ]
  },
  ]}
  ...
  devServer: {
        contentBase: "dist",
        overlay: true,
        historyApiFallback: true,
        hot: true,
        watchContentBase: true
   }
   ...
```
snipped of loader below...
```js
const dirTree = require("directory-tree");
const path = require("path");

module.exports = function(source) {
    const src = JSON.parse(source);
    const site_path = path.resolve(src.site_root);

    this.addDependency(site_path);
	
    // reads from file system
    src.content = dirTree(site_path, { extensions: /\.md$/ }).children;

    let config = {
        name: src.name,
        repo_link: src.repo_link,
        version: src.version,
        files: src.content
    };

    return `export default ${JSON.stringify(config)}`;
};
```

### Expected Behavior
Rerun loader when files in `site_path` change.

### Actual Behavior
The module doesnt reload

### What is the motivation and/or use-case for the feature?
I am trying to build a site for another project's documentation that pulls all markdown files from the `site` directory and uses that information to render the site. Similar to how jekyll works. It works well so far when running webpack to build. For more info, see [this](https://github.com/cmseaton42/node-ethernet-ip-docs) repo.

**Comment by cmseaton42** [comment]
Has anyone had time to consider this or help me understand how I might replicate this feature with the existing module?

**Comment by ChrisBAshton** [comment]
Similar issues noticed in external file watcher plugins:

https://github.com/sap9433/filewatcher-webpack-plugin/issues/7
https://github.com/Fridus/webpack-watch-files-plugin/issues/6

**Comment by ChrisBAshton** [comment]
I would also like to raise this feature request.

I have made a custom Webpack plugin for my project which loops through all source files and adds them to the `this.fileDependencies` array, with the expectation that if I run `webpack-dev-server` or `webpack --watch` and any of those files change, the entire Webpack build is re-run.

It looks as though anything that really _is_ a dependency, _does_ trigger the build. Anything that is not directly pulled into the entrypoint in Webpack, _doesn't_ trigger the build.

Consider this dir structure:

```
app.js
widget.js
data/
    cats.json
    dogs.json
templates/
    main.hbs
```

And imagine `app.js` contains this:

```js
import 'data/cats';
// do something
```

When I run `webpack-dev-server`, if I edit `app.js` or `data/cats.json`, it recompiles. If I edit `data/dogs.json` or `templates/main.hbs`, it doesn't compile.

In my case, I need `templates/main.hbs` to trigger a rebuild as my custom Webpack plugin compiles the Handlebars into HTML used by the application (the HTML, in turn, pulls in the application JS).

I've tried all manner of watcher plugins (see above comment) but they seem incompatible with Webpack v4 and/or with multi-entry Webpack configs (in my case, I need to compile `app.js` _and_ `widget.js` separately!). I've also tried manually watching for filechanges myself and calling the `done` callback in `compiler.plugin('emit')` if I detect a filechange - but that only seems to run part of the build process, not the Handlebars compilation!

**Comment by michael-ciniawsky** [comment]
> Rerun loader when files **in** site_path change.

@cmseaton42 The loader code looks correct to me so far, but in case you meant to watch the `*.md` files and trigger a rebulld when one of those files changes you need to add each of them to the watcher individually via `this.addDependency(file.md)`  aswelll
