### ISSUE TITLE
Allow writeToDisk as a middleware option

### ISSUE THREAD

**Issue by tech4him1** [webpack/webpack-dev-server#1357]
* Operating System: Win10
* Node Version: 9.2.0
* NPM Version: Yarn 1.5.1
* webpack Version: 4.4.1
* webpack-dev-server Version: 3.1.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?
`writeToDisk` was added to webpack-dev-middleware as an option. Can it be passed through so that the option can be set directly on the dev server?

Assuming the option can just be passed through, it should be a very simple change:
https://github.com/webpack/webpack-dev-server/blob/ef5598440ebf6847ac02a2d44d7fec70efee0aa1/lib/Server.js#L95

cc/ @shellscape

**Comment by VijayKrish93** [comment]
I facing the same issue.I was wondering when WDM supports this option why wont WDS support it ? and I end up here . I Would be pleased to see this simple thing shipped in the next release. As mentioned in 'Readme' I believe no features will be accepted until the maintenance work is complete

**Comment by evilebottnawi** [comment]
@VijayKrish93 because `webpack-dev-server` in maintenance mode (https://github.com/webpack/webpack-dev-server#project-in-maintenance) and only bug/security fixes accepted. My recommendation is migration on `webpack-serve`. Thanks!

**Comment by Binarytales** [comment]
Given that this project is no longer in maintenance mode (https://github.com/webpack/webpack-dev-server/commit/6c1d8d8ea1c06831a4360cdb661cc58bb52d77ec#diff-04c6e90faac2675aa89e2176d2eec7d8) could this issue be reopened as this functionallity would be _very_ handy for me right now.

**Comment by evilebottnawi** [comment]
@Binarytales feel free to send PR
