### ISSUE TITLE
auto refresh config

### ISSUE THREAD

**Issue by wghust** [webpack/webpack-dev-server#1358]
I set the proxy by apache:
```
<VirtualHost *:80>
  ServerName xd.xxx.com
  ProxyRequests off
  Header set Access-Control-Allow-Origin *
  <Proxy *>
    Order deny,allow
    Allow from all
  </Proxy>
  <Location /borrower>
    ProxyPass http://localhost:8897/
    ProxyPassReverse http://localhost:8897/
  </Location>
</VirtualHost>
```

if I want to set auto refresh. how can I set the config?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
