### ISSUE TITLE
`import webpack from 'webpack'` throws an error in a config

### ISSUE THREAD

**Issue by catamphetamine** [webpack/webpack-dev-server#1361]
When I supply a config like this:

```
webpack-dev-server --mode development --hot webpack/webpack.config.client.development.babel.js
```

And in the `webpack/webpack.config.client.development.babel.js` file:

```js
import webpack from 'webpack'
export default { ... }
```

Then it throws all kinds of weird errors.
For some reason it doesn't like `require('webpack')` inside a config which is passed to `webpack-dev-server`.

> ERROR in (webpack)/node_modules/schema-utils/dist/validateOptions.js
Module not found: Error: Can't resolve 'fs' in 'c:\dev\webpack-react-redux-isomorphic-render-example\node_modules\webpack\node_modules\schema-utils\dist'
 @ (webpack)/node_modules/schema-utils/dist/validateOptions.js 11:10-23
 @ (webpack)/node_modules/schema-utils/dist/index.js
 @ (webpack)/node_modules/schema-utils/dist/cjs.js
 @ (webpack)/lib/BannerPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./webpack/webpack.config.client.development.babel.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./webpack/webpack.config.client.development.babel.js

> ERROR in (webpack)/lib/NormalModule.js
Module not found: Error: Can't resolve 'module' in 'c:\dev\webpack-react-redux-isomorphic-render-example\node_modules\webpack\lib'
 @ (webpack)/lib/NormalModule.js 8:21-38
 @ (webpack)/lib/AutomaticPrefetchPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./webpack/webpack.config.client.development.babel.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./webpack/webpack.config.client.development.babel.js

> ERROR in (webpack)/lib/node/NodeTargetPlugin.js
Module not found: Error: Can't resolve 'module' in 'c:\dev\webpack-react-redux-isomorphic-render-example\node_modules\webpack\lib\node'
 @ (webpack)/lib/node/NodeTargetPlugin.js 10:1-18
 @ (webpack)/lib/WebpackOptionsApply.js
 @ (webpack)/lib/webpack.js
 @ ./webpack/webpack.config.client.development.babel.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./webpack/webpack.config.client.development.babel.js

Same is without Babel and ES6

**Comment by evilebottnawi** [comment]
Don't try to include webpack in your bundle, it is invalid.

**Comment by catamphetamine** [comment]
I'm not "including webpack in my bundle", read my post again.

**Comment by catamphetamine** [comment]
And there's no reopen button.
Whatever.
I don't care at all since I'm not using `webpack-dev-server` now because it's buggy.

**Comment by evilebottnawi** [comment]
@catamphetamine please create reproducible test repo

**Comment by michael-ciniawsky** [comment]
```diff
- webpack-dev-server --mode development --hot webpack/webpack.config.client.development.babel.js
+ webpack-dev-server --mode development --hot --config webpack/webpack.config.client.development.babel.js
```
