### ISSUE TITLE
webpack4 webpack-dev-server only first time work!

### ISSUE THREAD

**Issue by lyboy2012** [webpack/webpack-dev-server#1364]
Hash: 8eb87e4e5ff95fe468e1                                                         
Version: webpack 4.5.0
Time: 295ms
Built at: 2018-4-7 16:25:41
    Asset     Size  Chunks             Chunk Names
jquery.js  304 KiB  jquery  [emitted]  jquery
Entrypoint jquery = jquery.js
   [0] dll jquery 12 bytes {jquery} [built]
    + 1 hidden module
(node:79624) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wds｣: Project is running at http://192.168.0.107:9753/
ℹ ｢wds｣: webpack output is served from /__build/
ℹ ｢wds｣: Content not from webpack is served from ./
ℹ ｢wdm｣: Hash: 6899b12baa8cc3c8d985
Version: webpack 4.5.0
Time: 1157ms
Built at: 2018-4-7 16:25:44
              Asset       Size  Chunks             Chunk Names
           index.js    399 KiB   index  [emitted]  index
       index.js.map    438 KiB   index  [emitted]  index
        favicon.ico   1.12 KiB          [emitted]  
lib/polyfill.min.js   99.6 KiB          [emitted]  
      lib/jquery.js    304 KiB          [emitted]  
          home.html  731 bytes          [emitted]  
         index.html  739 bytes          [emitted]  
Entrypoint index = index.js index.js.map
[./node_modules/babel-runtime/helpers/createClass.js] 904 bytes {index} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {index} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {index} [built]
[./node_modules/url/url.js] 22.8 KiB {index} [built]
[./node_modules/webpack-dev-server/client/index.js?http://192.168.0.107:9753] (webpack)-dev-server/client?http://192.168.0.107:9753 7.75 KiB {index} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {index} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {index} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {index} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.66 KiB {index} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {index} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 KiB {index} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.03 KiB {index} [built]
[./src/scripts/entry/index.js] 56 bytes {index} [built]
[./src/scripts/index/index.js] 584 bytes {index} [built]
   [0] multi (webpack)-dev-server/client?http://192.168.0.107:9753 webpack/hot/dev-server ./src/scripts/entry/index.js 52 bytes {index} [built]
    + 45 hidden modules
Child html-webpack-plugin for "home.html":
     1 asset
    Entrypoint undefined = home.html
    [./node_modules/handlebars/dist/cjs/handlebars.runtime.js] 4.5 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/base.js] 8.21 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/decorators.js] 1000 bytes {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/exception.js] 4.63 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers.js] 2.85 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers/lookup.js] 860 bytes {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers/with.js] 2.94 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/logger.js] 3.75 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/no-conflict.js] 1.55 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/runtime.js] 34.7 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/safe-string.js] 1.14 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/utils.js] 10 KiB {0} [built]
    [./node_modules/handlebars/runtime.js] 167 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/home.html] 1.28 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
        + 6 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/handlebars/dist/cjs/handlebars.runtime.js] 4.5 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/base.js] 8.21 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/decorators.js] 1000 bytes {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/exception.js] 4.63 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers.js] 2.85 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers/lookup.js] 860 bytes {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/helpers/with.js] 2.94 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/logger.js] 3.75 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/no-conflict.js] 1.55 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/runtime.js] 34.7 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/safe-string.js] 1.14 KiB {0} [built]
    [./node_modules/handlebars/dist/cjs/handlebars/utils.js] 10 KiB {0} [built]
    [./node_modules/handlebars/runtime.js] 167 bytes {0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 1.29 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
        + 6 hidden modules
ℹ ｢wdm｣: Compiled successfully.

who can help me?
mac
webpack: 4.5.0
webpack-dev-server:3.1.1
html-webpack-plugin:3.2.0

when change code, find index.js size from 339kb to 27.8kb?

**Comment by evilebottnawi** [comment]
@lyboy2012 please use issue template and recreate issue. Thanks!
