### ISSUE TITLE
Usage of `new WebAssembly.Instance` rather than `WebAssembly.instantiate` causes errors with wasm files > 4K

### ISSUE THREAD

**Issue by fitzgen** [webpack/webpack-dev-server#1365]
* Operating System: linux
* Node Version: v9.10.0
* NPM Version: 5.6.0
* webpack Version: 4.4.1
* webpack-dev-server Version: 3.1.1

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/fitzgen/wasm_game_of_life/tree/f918506143e8a19429a1a9468639cf4a7709fb5a

### Expected Behavior

The wasm is loaded OK.

### Actual Behavior

The wasm is loaded OK in Firefox, but in Chromium there is an error because `new WebAssembly.Instance` is used rather than `WebAssembly.instantiate`:

```
wasm_game_of_life_bg.wasm:4 Uncaught (in promise) RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.
    at eval (wasm_game_of_life_bg.wasm:4)
    at Object../wasm_game_of_life_bg.wasm (0.bootstrap.js:78)
    at __webpack_require__ (bootstrap.js:58)
    at eval (wasm_game_of_life.js:18)
    at Object../wasm_game_of_life.js (0.bootstrap.js:67)
    at __webpack_require__ (bootstrap.js:58)
    at eval (index.js:2)
    at Object../index.js (0.bootstrap.js:11)
    at __webpack_require__ (bootstrap.js:58)
```

### For Bugs; How can we reproduce the behavior?

* clone the linked repo
* checkout `f918506143e8a19429a1a9468639cf4a7709fb5a`
* `npm run serve`
* navigate to localhost:8080 in Chromium

**Comment by fitzgen** [comment]
Closing in favor of https://github.com/webpack/webpack/issues/6475

**Comment by scottjmaddox** [comment]
@fitzgen I think this should be reopened. This is still an issue with `webpack-dev-server`, but no longer with normal `webpack` builds. Building with webpack and then hosting with a separate file server works fine, but hosting with `webpack-dev-server` results in the same old `RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.`.

**Comment by fitzgen** [comment]
@scottjmaddox I suggest filing a new issue with STR and test case. I'm not a maintainer for webpack-dev-server or familiar with its internals at all, but that is probably the best way to push forward on the issue.
