### ISSUE TITLE
webpack with webpack-dev-server@3.1.3 can't get /index.html  generat by html-webpack-plugin

### ISSUE THREAD

**Issue by elsitlte** [webpack/webpack-dev-server#1374]
* Operating System:Windows 8 x64
* Node Version: v8.4.0
* NPM Version: v5.5.1
* webpack Version: v4.5.0
* webpack-dev-server Version: 3.1.3

- [x] This is a **bug** 
- [ ] This is a **modification** request
### Code

```js
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin=require('html-webpack-plugin');
const CleanWebpackPlugin=require('clean-webpack-plugin');
module.exports = {
	entry: [
		path.join(__dirname,  "/src/index.js"),
	], //已多次提及的唯一入口文件
	output: {
		path:path.join(__dirname,  "dist"),
		filename: "bundle-[hash].js"
	},
	resolve :{
		extensions:[".js",".jsx"]
	},
	devtool: 'hidden-source-map',
	devServer: {
		contentBase: "/", //本地服务器所加载的页面所在的目录
		historyApiFallback: true, //不跳转
		inline: true,
		hot: true,
		hotOnly:true
	},
	plugins: [
		new CleanWebpackPlugin(['dist']),
		new webpack.BannerPlugin('版权所有，翻版必究'),
		new HtmlWebpackPlugin({
			title:"cesss",
			template:path.join(__dirname ,"/src/index-tpl.html")//new 一个这个插件的实例，并传入相关的参数
		}),
		new webpack.NamedModulesPlugin(),
		new webpack.optimize.OccurrenceOrderPlugin(),
		new webpack.HotModuleReplacementPlugin(),
	]
};
```
```js
//packet.json
{
  "name": "",
  "version": "",
  "devDependencies": {
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "html-webpack-plugin": "^3.1.0",
    "style-loader": "^0.20.3",
    "webpack": "^4.4.1",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "^3.1.1"
  },
  "scripts": {
    "build": "webpack",
    "start": "webpack-dev-server --open "
  }
}

```
```js
// /src/index.js
console.log("1,22,3");
document.body.appendChild(document.createTextNode("hello webpack-dev-server"));
```
```js
//  /src/index-tpl.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>
  <body>
  </body>
</html>
```

### Expected Behavior
In  webpack-dev-server @3.1.3
When I visit http://localhost:8080/(default port used by webpack-dev-server), it should display the index.html page generated by HtmlWebpackPlugin.show "hello webpack-dev-server”！

### Actual Behavior
When I visit http://localhost:8080/, I receive a 404: Cannot GET /
In  webpack-dev-server @3.1.1
When i degrade webpack-dev-server to 3.1.1.it is goes well. "hello webpack-dev-server” page show successfully.

### For Bugs; How can we reproduce the behavior?
you can refer the code above. it is just show a "hello webpack-dev-server",very simple.
it is easily to  reproduce the behavior for when u update you webpack-dev-server to 3.1.3.
in fact .server days ago when i work with webpack-dev-server to 3.1.1. there are none such problems!

**Comment by ejnu** [comment]
propably You have space in project path - check this - https://github.com/webpack/webpack-dev-server/issues/1373

**Comment by michael-ciniawsky** [comment]
Closing in favor of https://github.com/webpack/webpack-dev-server/issues/1373
