### ISSUE TITLE
proxy.bypass function does not work as expected

### ISSUE THREAD

**Issue by Rody-Kirwan** [webpack/webpack-dev-server#1387]
* Operating System: OSX Sierra
* Node Version: 9.8.0
* NPM Version: 5.6.0
* webpack Version: 4.1.0
* webpack-dev-server Version: 3.0.0

- [ x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  devServer: {
    port: 3200,
    noInfo: true,
    proxy: {
      '*': {
        target: 'http://localhost:3000',
        bypass: (req, res, proxyOptions) => {
          if (req.url.includes('/.')) {

            return  req.url+'kjh'
          }
        }
      }
    },
```

### Expected Behavior
A request to api/.foo will bypass the proxy and send a request to http:3200/api/.fookjh

### Actual Behavior
The proxy IS bypassed - however the new req.url is not applied - request is still sent to http:3200/api/.foo

### For Bugs; How can we reproduce the behavior?
Use the above devServer config to test

### For Features; What is the motivation and/or use-case for the feature?
Currently on out BE system we have some API endpoints that use a dot notation pattern. `/api/.template`
These requests are being blocked by a regex in the matching lib in http-proxy-middleware and always return a 404. I would like to bypass the proxy for these requests and use my own custom proxy.

**Comment by evilebottnawi** [comment]
@Rody-Kirwan problem still exists?

**Comment by Rody-Kirwan** [comment]
@evilebottnawi I'm not sure - moving to webpack-serve solved any issues I was having.

**Comment by evilebottnawi** [comment]
@Rody-Kirwan `webpack-serve` is deprecated and doesn't maintenance anymore

**Comment by Rody-Kirwan** [comment]
@evilebottnawi Since when?
There is no mention of that here:
https://www.npmjs.com/package/webpack-serve

**Comment by evilebottnawi** [comment]
@Rody-Kirwan https://github.com/webpack-contrib/webpack-serve

**Comment by Rody-Kirwan** [comment]
Hah - That is not good news!
Thanks for the update @evilebottnawi.

**Comment by evilebottnawi** [comment]
@Rody-Kirwan `webpack-server` is very buggy, better avoid to use this even it looks good and works

**Comment by Rody-Kirwan** [comment]
@evilebottnawi Yep, I can try to do that ASAP. It may be a couple of days before I can get to it though. Still need to switch back from webpack-serve. Thanks

**Comment by Rody-Kirwan** [comment]
@evilebottnawi - HI, I've recreated the issue on a repo here:

https://github.com/Rody-Kirwan/webpack-single-runtime

Please excuse the repo name . - It was initially created to display another webpack issue.

I'm not a fan of this `/.endpoint` pattern on the BE - but it's unfortunately outside my control.

When I was investigating the issue previously, I located the issue to regex matching pattern used by `http-proxy-middleware`. Oddly - `webpack-serve` also uses this dependency but didn't have the same issue.

**Comment by Rody-Kirwan** [comment]
@evilebottnawi Is there any update on this - completely blocked from updating webpack because of the issue.

**Comment by evilebottnawi** [comment]
@Rody-Kirwan A lot of issue and work, feel free to investigate and send a PR with fix

**Comment by Rody-Kirwan** [comment]
@evilebottnawi okay thanks. Think the issue is with micromatch dependency of http-proxy-middleware. Will investigate further

**Comment by doowb** [comment]
@Rody-Kirwan try setting the [dot option](https://github.com/micromatch/micromatch/#optionsdot) to `true` in `http-proxy-middleware`. It looks like `http-proxy-middleware` does not pass any options through to `micromatch`, so you'd have to manually do this in your `node_modules` to test.

**Comment by Rody-Kirwan** [comment]
@doowb - Thank you. Never spotted that. Works perfectly, so I will create an issue with http-proxy-middleware.
Really appreciate it :)

**Comment by Rody-Kirwan** [comment]
@evilebottnawi Yup. Closing now. Thanks
