### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by eayan** [webpack/webpack-dev-server#1389]
* Operating System: Linux Mint
* Node Version: Node.js 9.11.1
* NPM Version: npm@5.6.0
* webpack Version: 3.1.3
* webpack-dev-server Version: 3.1.3

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

### Expected Behavior
I want to install webpack but it came up with the following error.
### Actual Behavior
![selection_065](https://user-images.githubusercontent.com/5304822/39296348-f951170c-4940-11e8-8c3e-f79116d688e7.png)

**Comment by evilebottnawi** [comment]
@eayan Why you install `webpack-dev-server` inside `webpack-dev-server` package?

**Comment by evilebottnawi** [comment]
It is expected behavior from `npm`.

**Comment by eayan** [comment]
@evilebottnawi exactly I do not know where I should install that. Whenever I want to install npm, it comes up with the same error. What is the solution for that?
