### ISSUE TITLE
Chrome Dev Tools

### ISSUE THREAD

**Issue by chrismcv** [webpack/webpack-dev-server#139]
Hi, 
Not sure if this is the right place, but my app is showing `<Top Level></Top Level>` in the React Tab of chrome dev tools.  I read elsewhere that this meant the server was using server side rendering. I can't see any config that I'm missing.  

Could you please advise?

Thanks, 
Chris

``` devServer = new WebpackDevServer(webpack(webpackConfig),
    contentBase: './public/'
    hot: true
    watchDelay: 100
    noInfo: true
    lazy: true,

  )```

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    "webpack-dev-server/client?http://localhost:3333",
    "font-awesome-webpack!./font-awesome.config.js",
    'webpack/hot/dev-server',
    './app/initialise'
  ],
  devtool: "eval-source-map",
  debug: true,
  output: {
    path: path.join(__dirname, "public"),
    filename: 'bundle.js'
  },
  path: '/',
  resolveLoader: {
    modulesDirectories: ['node_modules']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.IgnorePlugin(/vertx/) // https://github.com/webpack/webpack/issues/353
  ],
  resolve: {
    root: path.resolve(__dirname, './app'),
    extensions: ['', '.jsx', '.js', '.cjsx', '.coffee', '.css', '.styl']
  },
  module: {
    loaders: [
      { test: /\.jsx$/, loaders: ['react-hot', 'babel'], exclude:/node_modules/},
      { test: /\.styl$/, loaders: ['react-hot', 'style', 'css', 'stylus']},
      { test: /\.css$/, loaders: ['react-hot', 'style', 'css']},
      { test: /\.cjsx$/, loaders: ['react-hot', 'coffee', 'cjsx']},
      { test: /\.coffee$/, loader: 'coffee' },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
    ]
  }
};

```

**Comment by jhnns** [comment]
The webpack-dev-server is basically just an http server with some special functionality on certain routes. It does not render your app :wink:

**Comment by sokra** [comment]
closing as not related to webpack.

**Comment by PinkyJie** [comment]
Hi @chrismcv, is that issue fixed? I also encounter this issue, don't know how to fix it.
http://stackoverflow.com/questions/33760288/css-url-path-in-additional-chunk-of-webpack-can-not-be-resolved-correctly
