### ISSUE TITLE
Webpack 4 Proxy (How to set up proxy url in webpack 4)

### ISSUE THREAD

**Issue by orensaldanha** [webpack/webpack-dev-server#1393]
I am basically a webpack newbie and here's the issue I have come accross. I was following a tutorial on how to set up a proxy url in webpack and used this syntax:

```
 proxy: {
'/api/*': {
    target: 'http://localhost:5000',
    secure: false
}
},
```

But this gives me the following error!

[https://i.stack.imgur.com/mTXEM.png](url)

The tutorial i was following was before webpack 4 came out so I think webpack 4 has some other way of doing it.

Heres what i want to achieve: * I have a webpackdev server on port 8080 and my express backend is listening on port 5000 i want fetch requests like api/ to go to 5000/api instead of 8080/api.

I hope you guys can help

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
