### ISSUE TITLE
show listing directory when working under "D:\Program Files"

### ISSUE THREAD

**Issue by TheBegining** [webpack/webpack-dev-server#1394]
* Operating System:win10 16299
* Node Version:8.11.1
* NPM Version:5.6.0
* webpack Version:4.6.0
* webpack-dev-server Version:3.1.3

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    mode: 'development',
    entry: {
        index: "./src/index.js",
        // login: "./src/Login.jsx"
    },
    output: {
        path: path.join(__dirname, '/dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [{
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: ['babel-loader?cacheDirectory=true'],
                include: path.join(__dirname, 'src')
            }, {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            }, {
                test: /\.(png|jpg|gif|woff|woff2|ttf|svg|eot)$/,
                use: {
                    loader: 'url-loader',
                    options: {
                        limit: 1024
                    }
                }
            }

        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './src/index.html'
        })
    ],
    devServer: {
        proxy: {
            '/api/*': {
                target: 'http://localhost:3001',
                changeOrigin: true,
            }
        }
    },
}
```

```js
//index.js
import React, { Component } from 'react'
import ReactDom from 'react-dom';
import App from './App.jsx';
ReactDom.render(<App/>,document.getElementById('app'));
//App.jsx
import React, { Component } from 'react'
class App extends Component {
    constructor(props) {
        super(props);
    }
    render() {
        return (
            <div>
                <h1>hi webpack</h1>
            </div>
        )
    }
}
export default App
  // additional code, remove if not needed.
```

### Expected Behavior
show index page
![image](https://user-images.githubusercontent.com/17702287/39505743-10169ac8-4e07-11e8-9cf3-7ebc4fd17b43.png)
![image](https://user-images.githubusercontent.com/17702287/39505749-1b9b574e-4e07-11e8-90a6-77f655c0db2c.png)

### Actual Behavior
Hi ,I create a simple project with webpack-dev-server. It works fine when the project located in "D:\".
But copy it to "D:\Program Files"，it will shows me listing directory page.
Actually，it shows listing directory page in any folder with space like“D:\folder with space”
maybe there is a bug?
show listing directory
![image](https://user-images.githubusercontent.com/17702287/39505789-5500648e-4e07-11e8-8f27-912ca5232cbd.png)
![image](https://user-images.githubusercontent.com/17702287/39505796-5f0eca9c-4e07-11e8-8871-205f5fa4fcd6.png)
![image](https://user-images.githubusercontent.com/17702287/39505849-a9147f60-4e07-11e8-88e0-2c88a567690a.png)

### For Bugs; How can we reproduce the behavior?
create a simple project with react ,then move to "D:\Program Files",then start server.

**Comment by tanjaChristina** [comment]
i investigated further - the escaping is done within webpack-dev-middleware (util.js) especially for Windows. When i enter a path with `%20` to escape empty spaces, it does not work any more for my Windows 10 machine! Seems like Microsoft changed something... 
For instance, also a common path like `C:\Program%20Files` does not work any more.
Windows 10 Version 1709, build 16299

**Comment by TheBegining** [comment]
it works fine under webpack-dev-server 3.1.4,thanks.

**Comment by anikolaevski** [comment]
This repeats under Yarn with  webpack-dev-server 3.10.2
