### ISSUE TITLE
Reset Content-Type

### ISSUE THREAD

**Issue by VadyaVL** [webpack/webpack-dev-server#1395]
Hi all.
I am using:
`before(app){`
`        app.disable('x-powered-by');`
`        app.get(/[^\s]*.js$/, function(req, res, next) {`
`            console.log('before');`
`            res.set({`
`                'Content-Type': 'text/javascript; charset=UTF-8',`
`                'Cache-Control': 'public, max-age=31536000, immutable',`
`                'x-content-type-options': 'nosniff'`
`            });`
`            next();`
`        });`
`    },`
..but Content-type for js equals application/javascript.
Please, help me anybody. Thanks.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
