### ISSUE TITLE
Content does not change using HotModuleReplacementPlugin.

### ISSUE THREAD

**Issue by rosnk** [webpack/webpack-dev-server#1405]
* Operating System: macOS Sierra version: 10.12.6
* Node Version:  v10.0.0
* NPM Version: 5.8.0
* webpack Version: "webpack": "^4.6.0",
* webpack-dev-server Version:  "webpack-dev-server": "^3.1.4",

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js

//webpack.common.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
  context: __dirname,
  entry: {
    app: './src/main.jsx'
  },
  output: {
    filename: '[name].[chunkhash].bundle.js',
    path: path.resolve(__dirname, 'dist')
    // publicPath: '/dist/'
  },
  resolve: {
    extensions: ['.js', '.jsx', '.json']
  },

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  },

  plugins: [
    new CleanWebpackPlugin(['dist']),
    new HtmlWebpackPlugin({
      template: './src/html_template/index.html'
    })
  ]
};

//webpack.dev.js
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const webpack = require('webpack');

module.exports = merge(common, {
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist',
    hot: true,
    overlay: true
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      }
    ]
  },
  plugins: [new webpack.NamedModulesPlugin(), new webpack.HotModuleReplacementPlugin()]
});


```

```js
  // additional code, remove if not needed.
// package.json
{
  "name": "boilerplate",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build:dev": "webpack --config webpack.dev.js",
    "start": "webpack-dev-server --open --config webpack.dev.js",
    "build": "webpack --config webpack.prod.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "csv-loader": "^2.1.1",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "lodash": "^4.17.10",
    "mini-css-extract-plugin": "^0.4.0",
    "node-sass": "^4.9.0",
    "optimize-css-assets-webpack-plugin": "^4.0.1",
    "sass-loader": "^7.0.1",
    "style-loader": "^0.21.0",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.1.2",
    "webpack-dev-server": "^3.1.4",
    "webpack-merge": "^4.1.2",
    "xml-loader": "^1.2.1"
  },
  "dependencies": {
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  }
}


```

### Expected Behavior
HMR to load changes without browser refresh but its not working. 

### Actual Behavior
**Content does not change using HotModuleReplacementPlugin.**

My entryfile "main.js" along with output i get in google chrome debugger can be found in 
 this stackoverflow link: 
[https://stackoverflow.com/questions/50291515/content-does-not-change-using-hotmodulereplacementplugin](https://stackoverflow.com/questions/50291515/content-does-not-change-using-hotmodulereplacementplugin) . Full description of the bug is also described in the stackoverflow link. 

### For Bugs; How can we reproduce the behavior?
Use my "webpack.common.js",  "webpack.dev.js" file" along with package.json file. 
Use my code shared in stackoverflow .

**Comment by whatsupdev** [comment]
Disabling module transformation in .babelrc finally worked. This line did the trick :  **"modules": false**

**I am still not sure why its not working without that line. Is it due to babel transforming code to commonJs syntax and HMR does not work in commonJS syntax ??** 

My current .babelrc file looks like this: 

    {
      "presets": [
        [
          "env",
          {
            "targets": {
              "chrome": 52
            },
            "modules": false,
            "loose": true
          }
        ]
      ],
      "plugins": ["transform-object-rest-spread"]
    }

Please close this issue, before that if any explanation on this behaviour will be greatful.

**Comment by evilebottnawi** [comment]
Not all code support HRM also you should use `react.hot-loader` for react component
