### ISSUE TITLE
Allow the output filename to be a function

### ISSUE THREAD

**Issue by berthertogen** [webpack/webpack-dev-server#1408]
* Operating System: Win 10
* Node Version: 9.7.1
* NPM Version: 5.6.0
* webpack Version: 4.7.0
* webpack-dev-server Version: 3.1.4

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
entry: {
    vendors: './vendors.js',
    bundle: './bundle.js',
    bundlepreview: './bundle.preview.js',
},
output: {
    filename: (data) => data.chunk.name === "bundlepreview" ? '[name].js' : '[name].[chunkhash].js',
    path: buildPath
},
```

### Expected Behavior
`webpack-dev-server` command starts the server and creates a bundlepreview.js without the chunkhash
### Actual Behavior
`webpack-dev-server` command fails with the message:
```
× ｢wds｣: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
- configuration.filename should be one of these:
   RegExp | string
   The filename that needs to be requested in order to trigger a recompile (only in lazy mode).
   Details:
    * configuration.filename should be an instance of RegExp.
    * configuration.filename should be a string.
```
### For Features; What is the motivation and/or use-case for the feature?
In optionsSchema.json allow filename to be a function:

```
"filename": {
      "description": "The filename that needs to be requested in order to trigger a recompile (only in lazy mode).",
      "anyOf": [
        {
          "instanceof": "RegExp"
        },
        {
          "type": "string"
        },
        {
          "instanceof": "Function"
        }
      ]
    },
```

**Comment by evilebottnawi** [comment]
Please note that webpack-dev-server is presently in a maintenance-only mode and will not be accepting any additional features in the near term. Most new feature requests can be accomplished with Express middleware; please look into using the before and after hooks in the documentation.

Use **webpack-serve** for a fast alternative. Use webpack-dev-server if you need to test on old browsers.

From https://github.com/webpack/webpack-dev-server#project-in-maintenance

**Comment by stoykostanchev** [comment]
Could you reopen this, now that webpack-dev-server is maintained again?

**Comment by evilebottnawi** [comment]
@stoykostanchev :+1: PR welcome

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack/webpack-dev-server/pull/1409
