### ISSUE TITLE
Unmet peer dependency - webpack@^4.0.0-beta.1

### ISSUE THREAD

**Issue by stoicsquirrel** [webpack/webpack-dev-server#1411]
* Operating System: macOS 10.13.1
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 3.12.0
* webpack-dev-server Version: 3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
`yarn install` should install without warning about not having met peer dependency `webpack@^4.0.0-beta.1`.

### Actual Behavior
`webpack-dev-server@3.1.4` patch version (in commit https://github.com/webpack/webpack-dev-server/commit/a02c0839fb50b59fee089f19d3e18e3c6e603695) increased the version required for webpack from `^2.2.0 || ^3.0.0` to `^4.0.0-beta.1`. This was a change from version 3.1.3 to 3.1.4, and I believe it may have been done in error, because it was released in a patch version, and there doesn't seem to have been a functional reason in this commit to increase the requirement.

### For Bugs; How can we reproduce the behavior?
Run `yarn install` and you will see the following:
`warning " > webpack-dev-server@3.1.4" has unmet peer dependency "webpack@^4.0.0-beta.1".`

**Comment by evilebottnawi** [comment]
@stoicsquirrel PR welcome :+1:
