### ISSUE TITLE
Suggestions for  static method addDevServerEntrypoints

### ISSUE THREAD

**Issue by rzyanhao** [webpack/webpack-dev-server#1413]
#### My code:
`

        const compiler = webpack(config);

        const devServerOptions = Object.assign({}, config.devServer);
        const port = devServerOptions.port || 8080;
        const host = devServerOptions.host || '127.0.0.1';

        WebpackDevServer.addDevServerEntrypoints(config,  devServerOptions);

        const server = new WebpackDevServer(compiler, devServerOptions);

        server.listen(port, host,  () => {
            console.log(`dev server start on ${host}:${port}`);
        });
`

**Comment by evilebottnawi** [comment]
@rzyanhao please use issue tempmate, otherwise your problem will be ignored or deleted, thanks!
