### ISSUE TITLE
Dropped requests when run through reverse proxy

### ISSUE THREAD

**Issue by kasvtv** [webpack/webpack-dev-server#1418]
* Operating System: W10
* Node Version: 8.9.3
* NPM Version: 6.1.0-next.0
* webpack Version: 4.10.2
* webpack-dev-server Version: 3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
https://github.com/kasvtv/webapck-dev-server-issue

### Expected Behavior
When behind a reverse proxy, devServer reliably serves files and the `sockjs-node` requests are sent through either the host + protocol of the devServer itsself or through the host + protocol of the reverse proxy

### Actual Behavior
First of all, great plugin, HMR makes my days at the office so convenient and I can imagine many others'. DevServer has a little weird behaviour behind a reverse proxy though. It randomly drops requests when accessed through a reverse proxy! Especially when a handful of medium-sized files are transferred, this issue shows itself more often, but in the small example it does happen with at least 25% of all page loads for me. When the request finally times out (10s in the example), it seems to reattempt and it does work.

Furthermore, the `sockjs-node` calls are sent through the protocol that the proxy uses (HTTPS) instead of the devServer itsself (HTTP), which wouldn't be a problem, if it weren't that they go to the port number of the devServer and not of the remote proxy through which I visit the page with my browser.

Before and after:
![webpack dev server issue](https://user-images.githubusercontent.com/1628729/40808677-36884d86-6528-11e8-93eb-c0fa5a1b8f58.png)

### For Bugs; How can we reproduce the behavior?
Clone my repository. Set up NGINX with included config file. Hit `npm i` `npm run dev`. Open localhost through Chrome 67. I have to say that it happens on a multitude of browsers, module versions and NGINX versions.

### For Features; What is the motivation and/or use-case for the feature?
I'm a front-end dev and I run a local development instance that needs to connect to a remote staging back-end. Because of our fragmented microservice architecture and strict resource sharing policies, I must use a reverse proxy that routes requests from `https://localhost/api` to `https://stage.domain.com/api` with the same rules as the remote would do internally. Currently, this gives me the above problems and is hard to work with. It does eventually load after the timout finishes, but this slows me down in my work since I can't set the timeout too low.

**Comment by martyanov** [comment]
The very same problem. I've updated `Webpack` and related dependencies to the latest version, the result is the same.

Options we use:
```proxy: {
            '/api/*': {
                target: util.format('http://%s:%s', apiHost, apiPort),
                secure: false
            },
            '/ws/*': {
                target: util.format('http://%s:%s', websocketHost, websocketPort),
                secure: false,
                ws: true
            }
        }```

**Comment by kasvtv** [comment]
OP here. For my dev environment I ended up dropping using a separate reverse proxy alltogether and use the reverse proxying of the webpack dev server. Obviously this solves the problem of dropped requests, but suboptimal as this is yet another point at which my dev environment is going to differ from production.

**Comment by LiamKarlMitchell** [comment]
Still a problem today.

Having this issue in a dev environment where we have 2 frontend Quasar apps (Admin & Client) & API wanting them to be on subfolders behind a reverse proxy (Traefik & docker) maybe I should just ditch subfolders for the frontends and use subdomains?

SockPath should be /admin/socket or /client/socket for example.

**Comment by alexander-akait** [comment]
For webpack-dev-server v4 you can specify `client.webSocketURL: 'ws://cumstom.com:8090/path'`, so I think it should be solved
