### ISSUE TITLE
plugins.HtmlWebPackPlugin.filename is not being respected

### ISSUE THREAD

**Issue by dduraipandian91** [webpack/webpack-dev-server#1424]
* Operating System: Windows 10
* Node Version: v8.11.1
* NPM Version: 5.6.0
* webpack Version:  "webpack" - 4.12.0, "webpack-cli": 3.0.7
* webpack-dev-server Version: 3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
Git Repository code - https://github.com/dduraipandian91/test_reactapp.git

### Expected Behavior
In the repository, src/app.html displays simple "hello world". it only works when the name is set to index.html and respected configuration in webpack.config.js

### Actual Behavior
"hello world" is displayed in the browser.

### For Bugs; How can we reproduce the behavior?
1. change the /src/app.html to /src/index.html
2. update the app.html to index.html in plugins.HtmlWebPackPlugin.filename, template. 

Above setup will work. But when you keep the html file name as app.html or any name. It is not working.

### For Features; What is the motivation and/or use-case for the feature?
N/A

**Comment by dduraipandian91** [comment]
Actually files being created as per output configuration. But somehow server is looking for index.html which was default and fails.

Thanks in advance for helping with this issue.

Regards,
Durai Pandian

**Comment by michael-ciniawsky** [comment]
https://webpack.js.org/configuration/dev-server/#devserver-index :)
