### ISSUE TITLE
example for api/simple can't compile successfully 

### ISSUE THREAD

**Issue by 404157386** [webpack/webpack-dev-server#1428]
* Operating System:  Windows 10
* Node Version:  v7.10.1
* NPM Version:  4.2.0
* webpack Version:  ^4.1.1
* webpack-dev-server Version: 3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

https://github.com/webpack/webpack-dev-server/blob/master/examples/api/simple/webpack.config.js

```js
  module.exports = setup({
  context: __dirname,
  entry: ['./app.js', '../../../client/index.js?http://localhost:8080/'],
  output: {
    filename: 'bundle.js'
  }
});
```

### Expected Behavior
 Compiled successfully and server starts up.

### Actual Behavior

hit error:

> ERROR in multi ./app.js ../../../client?http://localhost:8080/
> Module not found: Error: Can't resolve '../../../client/index.js?http://localhost:8080/' in 'C:\Users\kaiwen\webpack-dev-server-example\examples\api\simple'
>  @ multi ./app.js ../../../client?http://localhost:8080/

I can't find './../../client/index.js' at the code.
Is it deleted or renamed after an upgrade?

The server can run successfully, if remove this path:
`entry: ['./app.js'],`

Should the cli file is included?

### For Bugs; How can we reproduce the behavior?
run `node server.js` at path **examples\api\simple**

**Comment by hiroppy** [comment]
I think we should use `path` module.(because it does not occur in mac)
Currently, I don't have windows pc so could you please submit PR?

**Comment by evilebottnawi** [comment]
@hiroppy don't have pr also, let's use `path` and just fix example with `path`
