### ISSUE TITLE
devServer not works on files required in HtmlWebpackPlugin options

### ISSUE THREAD

**Issue by pldg** [webpack/webpack-dev-server#1431]
* Operating System: Windows 10
* Node: 8.11.1
* NPM: 6.1.0
* webpack: 4.12.0
* webpack-cli: 3.0.8
* webpack-dev-server: 3.1.4
* html-webpack-plugin: 3.2.0

- [X] This is a **bug**

### Code

I require *page1.js* inside `HtmlWebpackPlugin` options:

```js
new HtmlWebpackPlugin({
  template: './html-template.ejs',
  appMount: require('./src/views/page1')
})
```

Then I use a custom ejs template *html-template.ejs* to import the generated html contents:

```ejs
<%= htmlWebpackPlugin.options.appMount %>
```

*page1.js* looks like this:

```js
const h1 = (text) => `<h1>${text}</h1>`;

module.exports = h1('Hello World');
```

### Expected Behavior

When I run `webpack-dev-server` and edit *page1.js* I expect the browser to HMR (or at least reload) the page and updates the changes.

Note that *page1.js* is not set as entry point. The only entry point is *src/index.js* (which only have a `console.log` statement inside). If I edit *index.js* `devServer` works fine.

### Actual Behavior

Require *page1.js* inside `HtmlWebpackPlugin` options doesn't connect it to HMR / `devServer`. When I edit *page1.js* the browser doesn't update the changes.

**Comment by pldg** [comment]
### Solution / Workaround

Require *page1.js* directly inside *html-template.ejs* like so  `<%= require('./src/views/page1.js') %>` will solve the problem.

#### Notes

I still don't understand why require *page1.js* inside `HtmlWebpackPlugin` options doesn't connect it to HMR, is this a bug or an expected behavior?

**Comment by jantimon** [comment]
This seems to be a feature request for html-webpack-plugin to support hmr for template files.
The only way the webpack-dev-server could help here would be to provide an easier interface for plugin developers.
