### ISSUE TITLE
Preventing Addressbar Autohide

### ISSUE THREAD

**Issue by AdamAtri** [webpack/webpack-dev-server#1435]
* Operating System: Ubuntu 16.10
* Node Version: v8.10.0
* NPM Version:  6.1.0
* webpack Version: ^4.6.0
* webpack-dev-server Version: ^3.1.3

- [ ] This is a **bug**
- [ ] This is a **modification** request
- [x] This is an **inquery** about webpack-dev-server

### Code
No Code

### Expected Behavior
I'm testing my application on chrome mobile (ver 67) and noticed that you guys have figured out how to prevent chrome's super annoying behavior of autohiding the address bar when scrolling. 
Since the same code running on a simple `express` instance does not prevent the autohide behavior, I assume it's something you've done. 
So I was wondering if you could point me toward the part of your code that accomplishes this. 

Thanks.

**Comment by evilebottnawi** [comment]
It is internal behavior of browser, we can't solve this and it is out of scope `webpack-dev-server`
