### ISSUE TITLE
devServer.open is true, but it not work in nodeJs

### ISSUE THREAD

**Issue by wocaatm** [webpack/webpack-dev-server#1436]
devServer: {
    contentBase: path.join(__dirname, '../static'),
    proxy: config.dev.proxyTable, 
    hot: true, 
    quiet: true,
    open: true
 }

This is my devServer's options.  Then I use it in nodeJs

================

webpackDevServer.addDevServerEntrypoints(webpackConfig, webpackConfig.devServer);

var compiler = webpack(webpackConfig)

var server = new webpackDevServer(compiler, webpackConfig.devServer);

server.listen(process.env.PORT || config.dev.port, 'localhost', () => {
	console.log('server listening on port 8090')
})

=======

I has a question that why the options open dot not open the browser auto ??

**Comment by wocaatm** [comment]
I read the code, but i can't find the options.open in Server.js??

**Comment by bastienrobert** [comment]
Same here but for hot reload too.

**Comment by jslq** [comment]
Same here but for overlay too

**Comment by evilebottnawi** [comment]
Problem still exists? Somebody can create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/1510 .Close this issue due not issue template and test repo
