### ISSUE TITLE
1.8.0 not published to npm

### ISSUE THREAD

**Issue by MrOrz** [webpack/webpack-dev-server#144]
The latest version on npm is still 1.7.0.

Please publish webpack-dev-server 1.8.0 to npm so that we can use it without `cd node_modules/webpack-dev-server && npm i`.

By the way, [npm install runs prepublish implicitly](https://github.com/npm/npm/issues/3059). Some repositories renamed the publishing task to avoid "package not found" error during `npm i`. For now I always rename `prepublish` before calling `npm i` in webpack-dev-server project folder :P

**Comment by dqdinh** [comment]
1.8.0 is currently on npm.

**Comment by MrOrz** [comment]
:+1:
