### ISSUE TITLE
3d model textures from images disappear when moving in 2d

### ISSUE THREAD

**Issue by nasriachref** [webpack/webpack-dev-server#1448]
when you choose any  cataloge item that has image texture (example "bookcase") and placed in 2d viewer then switch between 2d and 3d  while moving it the texture disappear 

steps to reproduce :

1. choose catalogue item "bookcase" and placed in 2D viewer.
2. go to 3D viewer  ( the model is fine here)
3. return to 2d viewer and move it in 2d space with the mouse 
4.  go back to the 3d veiwer  => texture image is gone the model is white no texture

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
