### ISSUE TITLE
reloading not working with babeljs

### ISSUE THREAD

**Issue by LeonardoHabitzreuter** [webpack/webpack-dev-server#1450]
* Operating System: Ubuntu 16.04
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.16.3
* webpack-dev-server Version: 3.1.5

- [x] This is a **bug**
- [ ] This is a **modification** request

webpack.config:
```
const webpack = require('webpack')
const { join } = require('path')

const paths = {
  src: join(__dirname, 'src'),
  modules: join(__dirname, 'node_modules')
}
module.exports = {
    mode: process.env.NODE_ENV,
    entry: './src/index.js',
    output: {
        filename: 'main.js',
        path: __dirname + '/public'
    },
    devServer: {
        contentBase: "./public",
        port: 9000
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: paths.modules,
            include: paths.src,
            use: ['babel-loader']
        }, {
            test: /\.s?[ac]ss$/,
            use: [
		 'style-loader',
                'css-loader',
                'sass-loader',
            ]
        }, {
            test: /\.(png|svg|jpg|gif)$/,
            use: ['file-loader']
        }]
    }
}
```

index.js
```
  import './button.scss'
```

index.html
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>My boilerplate</title>
</head>
<body>
    <div id="app"></div>
    <button class="btnTest">Test</button>
    <script src="main.js"></script>
</body>
</html>
```

.babelrc
```
{
  "presets": ["env", "react"]
}
```

### Expected Behavior
When changing the button.scss content the server should update the assets

### Actual Behavior
The server can't update the files when I'm using the babel-loader for .js files.
If I remove the babel-loader from the webpack config the server get back working properly

### How to reproduce the behavior
clone this repo: https://github.com/LeonardoHabitzreuter/webpack4-babel
run: npm start

**Comment by neo7official** [comment]
I am having the same issue.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, looks you have invalid configuration

**Comment by LeonardoHabitzreuter** [comment]
evilebottnawi Do you have checked the reproducible test repo? This certainly not looks like an invalid config

**Comment by evilebottnawi** [comment]
@LeonardoHabitzreuter You reproducible test repo not consistent with what you wrote - no `scss` files in repo. 

For JS add this in you config in `watch`:
```js
plugins: [
  new webpack.HotModuleReplacementPlugin()
]
```
