### ISSUE TITLE
Scrambled output

### ISSUE THREAD

**Issue by philiparvidsson** [webpack/webpack-dev-server#1453]
* Operating System: **Windows 10 x64 (b1803)**
* Node Version: **8.11.3**

* NPM Version: **6.3.0**
* webpack Version: **4.16.5**
* webpack-dev-server Version: 3.1.5**

- [x] This is a **bug**
- [ ] This is a **modification** request

### Reproduction Steps

1. Run webpack-dev-server
2. Look at output

### Actual Behavior

Scrambled output:
![image](https://user-images.githubusercontent.com/1163299/43710531-344e0250-9970-11e8-8337-c88e996f9380.png)

### Expected Behavior

Unsure, possibly `webpack:` or similar.

### More Info

This happens on two computers with two different projects created entirely from scratch. I've tried blank projects, rewriting webpack.config.js and more, but I still get this. Also, this is with `webpack-cli` if that is relevant. This only happens with weback-dev-server, not webpack.

**Comment by evilebottnawi** [comment]
@philiparvidsson looks something wrong with your shell, what shell you use?

**Comment by philiparvidsson** [comment]
@evilebottnawi http://cmder.net/ (conemu). I've never seen it anywhere else. What is it supposed to say?

**Comment by evilebottnawi** [comment]
@philiparvidsson can you test this with standard shell?

**Comment by philiparvidsson** [comment]
@evilebottnawi Same thing:

![image](https://user-images.githubusercontent.com/1163299/43770986-244191dc-9a3e-11e8-88e5-57516b9c04bb.png)

**Comment by B3zo0** [comment]
It has nothing to do with webpack-dev-server. The charset is set to OEM or something. You change that in the main options in cmder. You should use **ANSI**.

**Comment by philiparvidsson** [comment]
@B3zo0 last screenshot is cmd.exe with win10 defaults

**Comment by B3zo0** [comment]
for me it also uses OEM by default ![oem charset](https://content.screencast.com/users/Bezoo/folders/Jing/media/838e7250-43d3-4865-9a4c-0341a4f78894/2018-08-07_1450.png)

**Comment by philiparvidsson** [comment]
what's the scrambled string supposed to say? I never recall having to change that before

**Comment by B3zo0** [comment]
it is just fancy border characters ``` ｢wds｣: Project is running at http://localhost:8080/ ```

**Comment by philiparvidsson** [comment]
it's correct that cmd.exe is set to oem, however cmder is set to ansi.

anyway, shouldn't it work fine with default settings=

**Comment by evilebottnawi** [comment]
I closed it, because not related to dev server, feel free to feedback
