### ISSUE TITLE
Webpack dev server not reloading browser on any change made to html, js file

### ISSUE THREAD

**Issue by neo7official** [webpack/webpack-dev-server#1454]
* Operating System: Windows 10
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: ^4.16.5
* webpack-dev-server Version:^3.1.5

- [x] This is a **bug**
- [ ] This is a **modification** request

I am trying to build a plugin for multiple entry points so that one does not have to mention any entry point to webpack.config.js file at all. My plugin loops through the files in "src/js/" folder and set found (i.e. index.js, about.js) javascript files as entry points and then it checks for html files of same name (i.e. index.html, about.html) in "src/" folder if found it push that into html-webpack-plugin as template and generate compiled version of html file too in dist folder or if there is not such html file found then html-webpack-plugin will generate its own basic html file to dist folder.

**Now, the problem is, is working perfectly when I am running "npm run build", but when I am running "npm run start" and then if I modify any file then its not reloading the page in browser, I had to reload browser myself and then modification shows.**

**I have created a github repo with a minimal version of this . The plugin I have written is in  "/multiple_entry_point_plugin/" folder.**

https://github.com/neo7official/multiple-entry-point-plugin

### Code

```js
  // webpack.config.js
const path = require("path");
const src_path = path.resolve('src/');
const dist_path = path.resolve('dist/');

const multipleEntryPoints = require("./multiple_entry_point_plugin/multipleEntryPoints");
const webpackDevServer = require("webpack-dev-server");


module.exports = {
	mode:"development",
	output:{
		filename:"js/[name].js",
		path:dist_path,
		publicPath:"/",
	},
	plugins:[
		new multipleEntryPoints()
	],
	devServer:{
		port:3000,
		overlay: true,
		historyApiFallback: true,
		open:true,
		hot:false,
		watchOptions: {
	      poll: true
	    }
	}
}
```

```js
  // This is my plugin code.
const fs = require("fs");
const path = require("path");
const htmlWebpackPlugin = require("html-webpack-plugin");
const weblog = require('webpack-log');
const log = weblog({ name: 'MEP' });
const chalk = require("chalk");

 


class multipleEntryPoints{

	constructor(options){

		this.options = Object.assign({
			srcFolder:"./src",
			distFolder:"./dist",
			commonsChunk:true,
		}, options);


		this.build_html = this.build_html.bind(this);
		this.create_bundle = this.create_bundle.bind(this);
	}

	create_bundle(item, name, compiler){
		log.info(chalk.bgGreen.black(`Entry point mounted - ${item}`));
			compiler.options.entry[name] = item;
	}

	build_html(html_path, name, compiler){
		if(fs.existsSync(html_path)){
			new htmlWebpackPlugin(
				{
					filename:`${name}.html`,
					template:html_path,
					chunks:[`${name}`]
				}
			).apply(compiler);
		}else{
			new htmlWebpackPlugin({filename:`${name}.html`, chunks:[`${name}`]}).apply(compiler);
		}
	}
	normalize(name){
		return name.split(".")[0].replace("_", "-");
	}

	apply(compiler){

		compiler.options.entry = {};
		
		compiler.hooks.entryOption.tap("multipleEntryPoints", (compilation, entries) => {
			var item, name;
			log.info(chalk.bgYellow.black("**** MultipeEntryPoints Starts ****"));
			

					fs.readdirSync(path.resolve(this.options.srcFolder, "js/")).forEach(file =>{
						if(file.split(".").length > 1){ //ignoring folder names
							
							item = path.resolve(this.options.srcFolder, `js/${file}`);
							name = this.normalize(file);
							this.create_bundle(item, name, compiler);
							
							var html_path = path.resolve(this.options.srcFolder,`${name}.html`);
							this.build_html(html_path, name, compiler);					
						};
					});


			log.info(chalk.bgYellow.black("***** MultipeEntryPoints Ends *****"));
		});

	}
}

module.exports = multipleEntryPoints;
```

### Expected Behavior
Browser should reload if any of html, css, js file get modified.
### Actual Behavior
Console shows its compiling but browser does not reloading the page on html/css/js file modification.
### For Bugs; How can we reproduce the behavior?
https://github.com/neo7official/multiple-entry-point-plugin

**Comment by robbyemmert** [comment]
I'm getting the same issue on MacOS High Sierra

**Comment by mahmoudafifi414** [comment]
if the webpack not serving code changes to the browser so
in webpack.congif.js write :

module.exports = {
//...
devServer: {
watchOptions: {
poll: true
}
}
};

for further information see this link:
https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

**Comment by evilebottnawi** [comment]
@robbyemmert you can't get same issue, because this problem related how plugin insert new entries. 
@neo7official It is not bug, you don't have webpack-dev-server client code in you entry

**Comment by neo7official** [comment]
@evilebottnawi will you please explain what you did mean by 'webpack-dev-server client side code'

**Comment by a-m-dev** [comment]
same here

**Comment by evilebottnawi** [comment]
@a-m-dev Please create reproducible test repo

**Comment by evilebottnawi** [comment]
Your rewrite webpack-dev-server entrypoints (where we added client code). 

My commendations:
- use https://github.com/webpack/webpack/tree/master/examples/multi-compiler (you can use `fast-glob` to collect required entrypoints)
- adding client code using:
```js
log.info(chalk.bgGreen.black(`Entry point mounted - ${item}`));
compiler.options.entry[name] = [
  require.resolve('webpack-dev-server/client/index.js') + '?http://your_host:your_port',
  require.resolve('webpack/hot/dev-server.js'),
  item
];
```
+ setup multiple content bases for wathing html files
