### ISSUE TITLE
ERROR in multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ./app/index.js

### ISSUE THREAD

**Issue by dinesh22** [webpack/webpack-dev-server#1456]
* Operating System: Ubuntu 16.04
* Node Version: 10.6.0
* NPM Version: 1.7.0
* webpack Version: 4.16.5
* webpack-dev-server Version: 2.11.1

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js

var webpack = require('webpack');

var config = {

     entry: "./app/index.js",

  resolve: {
  extensions: ['.ts', '.js']
},
  output: {
    path: __dirname + '/dist', // `dist` is the destination
    filename: 'bundle.js',
  },
};

module.exports = config;

```

### Expected Behavior

Need to run Webpack-dev-server.

### Actual Behavior

Getting the below error whenever i try to run webpack-dev-server:

ERROR in multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ./app/index.js
Module not found: Error: Can't resolve './app/index.js' in '/home/dinesh/Shopify_Test_New/shopify_app/bin'
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ./app/index.js

**Comment by michael-ciniawsky** [comment]
https://webpack.js.org/configuration/entry-context/#context

**Comment by noontz** [comment]
It is closing an issue like this with out any kind of clue on how to fix it that makes developing in js such a pain when it comes to tooling. After an hour of try and error I ended up uninstalling webpack-dev-server and settled with the live server plugin..  A shame though.

**Comment by BillMeyerRSA** [comment]
Yeah tried --host 0.0.0.0 and this error comes up.
It is *literally* the first thing you want to do... dev on a VM or other box and access the app in a browser not on localhost... and there seem to be NO sane answer for this. 
It is like building a car with no doors. Insane.
