### ISSUE TITLE
Server can't be accessed via IP

### ISSUE THREAD

**Issue by aputinski** [webpack/webpack-dev-server#147]
In `1.7.0` the following command:

```
webpack-dev-server --port 3000 --hot
```

would allow the server to be accessed at:

`http://localhost:3000` and
`http://10.0.1.4:3000` (my local IP).

In `1.8.0` accessing `http://10.0.1.4:3000` no longer works.

Not sure if this has to do with `webpack-dev-server` or one of the dependencies.

I'm using node `0.12.2` and running OSX `10.10.2`

**Comment by pdillon** [comment]
1.8.0 appears to be defaulting to "localhost' now. You can open it up by passing the --host option.
         `webpack-dev-server --port 3000 --hot --host 0.0.0.0`

**Comment by aputinski** [comment]
Ahh. Good to know. Thanks!

**Comment by liyatang** [comment]
thanks。

**Comment by honger05** [comment]
thanks。

**Comment by mikhuang** [comment]
If you're using WebpackDevServer, be aware that the host argument is part of `server.listen` as follows:

```
  var server = new WebpackDevServer(webpack(webpackConfig), {
    ...
  });
  server.listen(port, "0.0.0.0", function(err) { ...
```

**Comment by BUPT-HJM** [comment]
thanks

**Comment by Robin-front** [comment]
ty : )

**Comment by CodingJoker** [comment]
thanks

**Comment by honger05** [comment]
How did I use express to do?

````js
var devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  hot: true,
  stats: {
    colors: true,
    chunks: false
  }
})

// use express
app.use(devMiddleware)

app.listen(port, function (err) {
  if (err) {
    console.log(err)
    return
  }
  console.log('Listening at ' + port + '\n')
})
````

**Comment by cunjieliu** [comment]
thanks a lot!

**Comment by meastes** [comment]
@honger05 It'm not sure where the host and port are being set in your code, but you would want to make sure host is set to '0.0.0.0' instead of 'localhost'.

**Comment by caisah** [comment]
It can also be set from the *webpack* file by setting `devServer.host` to `0.0.0.0`.
```javascript
devServer: {
    host: '0.0.0.0',
    port: 8080,
    ...
  }
```

**Comment by Mr111222** [comment]
oh    my   god

**Comment by anchengjian** [comment]
```
  devServer: {
    historyApiFallback: true,
    noInfo: true,
    contentBase: './dist',
    host: '0.0.0.0',
    hot: true,
    open: true,
    historyApiFallback: true,
    inline: true
  }
```
I turn on the `open` switch, then the browser will open 'http://0.0.0.0:8080/'. But 0.0.0.0 is not accessible.

**Comment by CodingJoker** [comment]
@anchengjian  Here are some piece code of my server.js
<pre><code>
const compiler = webpack(config);
new WebpackDevServer(compiler, config.devServer)
.listen(config.port, '0.0.0.0', (err) => {
  if (err) {
    console.log(err);
  }
  console.log('Listening at localhost:' + config.port);
});
</code></pre>

In listen function ,the second param set '0.0.0.0' , maybe can solve this problom.

**Comment by zzwfe** [comment]
@caisah good to know.ths

**Comment by cotyembry** [comment]
I had to do the following to get mine to work with the help from @pdillon and his comment

I have Windows 7 so I did

    ipconfig

Then went up to LAN and found the ipv4 address
Mine was

    192.168.0.12

So I edited my npm run start command to be

    "start": "webpack-dev-server --inline --port 8080 --host 192.168.0.12 --content-base ."

I was then able to access the content that is being served on

    localhost:8080

Will be available as the web on another computer by going to

    192.168.0.12:8080

In the web browsers URL field on the other computer that was connected to the same wifi network

**Comment by sebfindling** [comment]
just FYI, you can just type `0` instead of `0.0.0.0` for ease of use :)

**Comment by ArminSheng** [comment]
@honger05  Add **host: '0.0.0.0'** to your devMiddleware  config, just like blew, it works to me.

~~~
var devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  hot: true,
  host: '0.0.0.0',
  stats: {
    colors: true,
    chunks: false
  }
})
~~~

**Comment by peacechen** [comment]
Using `host: '0.0.0.0'` in the devServer section of webpack.config does run, but iOS Safari complains with "Invalid Host header".  The only way to get Safari to load is to hard code the IP :(

**Comment by erikyuzwa** [comment]
the hardcoded IP wouldn't work for me @peacechen - I was able to get mine to work by disabling `disableHostCheck`. 
eg.
```
devServer: {
    contentBase: '.',
    host: '0.0.0.0',
    port: 3000,
    disableHostCheck: true
  },
```

**Comment by akemando** [comment]
pdillon ... you are the man!! Thanks a bunch

**Comment by ChenPt** [comment]
@erikyuzwa thanks

**Comment by codingedward** [comment]
goodness, thanks

**Comment by joetidee** [comment]
Is there a way to dynamically generate the `--host` IP address in the `package.json` file or with a setting in `webpack.config.js`? I am currently using `0.0.0.0`, but it has been suggested that this is insecure.

**Comment by tomholford** [comment]
Thanks @pdillon, just got gatsby `1.1.11` to work with:
```
gatsby develop --host 0.0.0.0
```

**Comment by ZengTianShengZ** [comment]
thanks

**Comment by jwenjian** [comment]
For anyone who are using vue webpack template, this issue can be solved by config the `config/index.js`, find the config of `host` then change the value to `0.0.0.0`, like below:

```javascript
module.exports = {
  dev: {

    // Paths
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {},
    

    // Various Dev Server settings
    host: '0.0.0.0', // can be overwritten by process.env.HOST
    port: 8080, // can be overwritten by process.env.PORT, if port is in use, a free one will be determined
    autoOpenBrowser: false
  }
  // ... ... other config ignored here
}
```

**Comment by vijaykumar91** [comment]
Its working for me thanks

**Comment by jessevdp** [comment]
Perhaps it's worth to point out that in order to access the webpack-dev-server from other devices on your local network you need to pass `--public your-host:port` **since version 2.4.3**.

See https://github.com/webpack/webpack-dev-server/issues/882.

Maybe add this to the top of this thread if possible?

**Comment by sytpb** [comment]
how to change with the create-react-app and express code ,it didn't work.
