### ISSUE TITLE
Response code is 404 and content-type is wrong

### ISSUE THREAD

**Issue by ryanburnette** [webpack/webpack-dev-server#1476]
* Operating System: macOS 10.13
* Node Version: 10.9.0
* NPM Version: 6.4.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.6

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
var path = require('path')

module.exports = {
  entry: {
    index: './index.js',
  },
  output: {
    path: path.resolve(__dirname, 'public.built/assets'),
    publicPath: '/assets/',
    filename: '[name].bundle.js'
  },
  module: {
  },
  mode: 'development'
}
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

I expected the response code to be 200 and for the content-type header to be application/json.

### Actual Behavior

```
$ curl localhost:8080/assets/index.bundle.js -I
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 162
Date: Mon, 27 Aug 2018 22:39:52 GMT
Connection: keep-alive
```

The response code in 404, but it's serving the bundle. Shouldn't the content-type be application/json?

### For Bugs; How can we reproduce the behavior?

```bash
$ git clone https://code.ryanburnette.com/ryanburnette/webpack-dev-server-issue-28304
$ npm install
$ node_modules/.bin/webpack-dev-server
$ curl localhost:8080/assets/index.bundle.js
$ curl localhost:8080/assets/index.bundle.js -I
```

### For Features; What is the motivation and/or use-case for the feature?

I'd like the response code to be correct because I'm trying to proxy webpack-dev-server through something that requires it to be 200. I'd also like the content-type to be correct.

It's not part of this issue, but I wish I could control the x-content-type header as well.

**Comment by RobinClowers** [comment]
@ryanburnette did you solve this? I ran into the same issue.

**Comment by ryanburnette** [comment]
I wish I remembered.

**Comment by RobinClowers** [comment]
In my case, I was using the HtmlWebpackPlugin, and had the `inject` property set to `true`. I also had script tag in my html template file, which was incorrect, since inject adds it for you automatically.
