### ISSUE TITLE
The page width is not equal the window width

### ISSUE THREAD

**Issue by linlinyang** [webpack/webpack-dev-server#1477]
* Operating System: win7
* Node Version:
* NPM Version: 6.4.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.6

### Bug
The width of my webpage preview in chrome will be equal to auto width(window width),but when my window width is 1663px ,my webpage document width just 336px or 1000px in diffirent  computer has diffirent screen;But this bug will not in firfox or edge or other browser;

**Comment by michael-ciniawsky** [comment]
Sry I can't help you with the information provided, currently this sounds like a bug with your CSS ?

**Comment by linlinyang** [comment]
I just write a empty page,no css  and just write a console.log in my entry js.And the config is also the base config;This code 
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no,maximum-scale=1,minimum-scale=1"> 
in my HTML has no useful.But my page document's width just 336px while my window's width is 1663px.
This bug hasn't show in firfox and edge or other browser,just in chrome.

**Comment by linlinyang** [comment]
How to resolve it

**Comment by michael-ciniawsky** [comment]
> But my page document's width just 336px while my window's width is 1663px.

I honestly don't know whats happening there :D, but I still can't help really help you with that provided info. Do you add CSS via JS in your `index.js` file? If not then that's likely the browsers default stylesheet your are seeing and yes they are sadly different between browsers.
