### ISSUE TITLE
why watch files only in the same folder?

### ISSUE THREAD

**Issue by franklion** [webpack/webpack-dev-server#1480]
* Operating System: MacOS High Sierra 10.13.6
* Node Version: v8.11.0
* NPM Version: 5.6.0
* webpack Version: 4.8.3
* webpack-dev-server Version: 3.1.4

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack-dev-server/lib/Server.js
Server.prototype._watch = function (watchPath) {
  // duplicate the same massaging of options that watchpack performs
  // https://github.com/webpack/watchpack/blob/master/lib/DirectoryWatcher.js#L49
  // this isn't an elegant solution, but we'll improve it in the future
  const usePolling = this.watchOptions.poll ? true : undefined; // eslint-disable-line no-undefined
  const interval = typeof this.watchOptions.poll === 'number' ? this.watchOptions.poll : undefined; // eslint-disable-line no-undefined
  const options = {
    ignoreInitial: true,
    persistent: true,
    followSymlinks: false,
    depth: 0,
    atomic: false,
    alwaysStat: true,
    ignorePermissionErrors: true,
    ignored: this.watchOptions.ignored,
    usePolling,
    interval
  };

  const watcher = chokidar.watch(watchPath, options).on('change', () => {
    console.log('content-changed')
    this.sockWrite(this.sockets, 'content-changed');
  });

  this.contentBaseWatchers.push(watcher);
};
```

### Expected Behavior
I want to watch many pug files in different folders, like this `src/pug/**/*.pug`

### Actual Behavior
It's only watching files in the same folder, like this  like this `src/pug/pages/*.pug` or `src/pug/components/*.pug`

### For Features; What is the motivation and/or use-case for the feature?
I don't know why to set depth to 0 in the options. it is possible to modify depth to be default, then chokidar can watch files in different folders.

**Comment by michael-ciniawsky** [comment]
This instance of chikidar is for watching the [content base](https://webpack.js.org/configuration/dev-server/#devserver-contentbase) **only**. Do you bundle your `pug` files with `webpack` or do you intend to serve them as static files ? `webpack` itself will only watch the files which are imported

**Comment by franklion** [comment]
@michael-ciniawsky ok, actually I want to implement MHR, and then I have many pug pages as static files. So when I modify one of pug file, I want dev-server to reload browser. At the same time, I modify sass file, It can be Hot reload(not reload browser).

I found the same issue here (https://github.com/webpack/webpack-dev-server/issues/1271).
The last developer @cloudratha commented
```
before(app, server) {
    server._watch(`some/path/to/watch/*/**.html`);
}
```

I try to implement it, but it doesn't work. because one of the options depth is 0.
```
before(app, server) {
    server._watch(`some/path/to/watch/*/**.pug`);
}
```

**Comment by glen-84** [comment]
@evilebottnawi Closed by #1697?

**Comment by evilebottnawi** [comment]
@glen-84 no, we just relax depth in public directory, but developers want to watch files in other directories. I am wrong what we need major here.

**Comment by glen-84** [comment]
@evilebottnawi You *can* watch in other directories, but the API is private (`server._watch`). The OP was asking for the `depth` option to be changed, and that has now been implemented.

Can you make `server._watch` public?

**Comment by evilebottnawi** [comment]
@glen-84 better do this using option

**Comment by evilebottnawi** [comment]
Oh, i was wrong, you can set array of `contentBase` and now we don't have limits so you can watch what you want
