### ISSUE TITLE
Unable to start multiple servers using `--bonjour`

### ISSUE THREAD

**Issue by jharwig** [webpack/webpack-dev-server#1481]
* Operating System: macOS High Sierra (10.13.6) 
* Node Version: 10.3.0
* NPM Version: 6.1.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.6

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// Run dev server in 2 different projects with bonjour
webpack-dev-server --hot --inline --bonjour
```

Steps:
1. Clone [Example Repo](https://github.com/jharwig/webpack-bonjour-error-example)
1. `npm install`
1. `cd project-1 && ../node_modules/.bin/webpack-dev-server --hot --inline --bonjour`
1. In another terminal (without stopping first server): 

        cd project-2 && ../node_modules/.bin/webpack-dev-server --hot --inline --bonjour

### Expected Behavior

Both servers would start successfully, and broadcast a bonjour message.

### Actual Behavior

The second server will fail because of bonjour name is duplicated `Webpack Dev Server`.

```
ℹ ｢wds｣: Broadcasting "http" with subtype of "webpack" via ZeroConf DNS (Bonjour)
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Service name is already in use on the network
    at /usr/local/lib/node_modules/webpack-dev-server/node_modules/bonjour/lib/registry.js:47:31
```

https://github.com/webpack/webpack-dev-server/blob/1896fcff8c64390481ad366dd554a8c09c4d1725/bin/utils.js#L94-L99

### Feature

Possible resolutions:
1.  Change the broadcast name to include something unique (publicPath?) This would be a breaking change as the name would have to change – but possible only for the subsequent servers that failed.
2. Allow configuration of the broadcast name, default to current "Webpack Dev Server".

**Comment by evilebottnawi** [comment]
@jharwig please provide steps and reproducible test repo

**Comment by jharwig** [comment]
@evilebottnawi done

**Comment by jharwig** [comment]
Closing as I can just implement my own broadcast in before event, per your other [comment](
https://github.com/webpack/webpack-dev-server/issues/1482#issuecomment-417064895)

**Comment by evilebottnawi** [comment]
@jharwig Better do https://github.com/webpack/webpack-dev-server/issues/1482#issuecomment-417064895
