### ISSUE TITLE
The server never closes, even after ^C and closing the terminal

### ISSUE THREAD

**Issue by nebrelbug** [webpack/webpack-dev-server#1489]
* Operating System: Windows 10
* Node Version: 8.9.0
* NPM Version: 6.3.0
* webpack Version: 4.17.1
* webpack-dev-server Version: 3.1.7

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
  ...
 devServer: {
    contentBase: path.join(__dirname, '')
 },
```

### Expected Behavior
When I press ^C, the server stops
### Actual Behavior
The server keeps on running! I'm on Git Bash, and even when I close the terminal, the server is still running. I ran it on localhost:9000, localhost:9003, and localhost:8081, and I can access the server on all 3 of them, even though I tried to end localhost:9000 and localhost:9003
### For Bugs; How can we reproduce the behavior?
Try and close the server in Git Bash

**Comment by evilebottnawi** [comment]
@nebrelbug do you use `webpack-dev-server` or `webpack-serve`?

**Comment by nebrelbug** [comment]
@evilebottnawi I use `webpack-dev-server`

**Comment by evilebottnawi** [comment]
@nebrelbug please create minimum reproducible test repo, thanks

**Comment by nebrelbug** [comment]
I think it would work on any repo with Git Bash, probably

**Comment by aprilmintacpineda** [comment]
I'm experiencing this same error, but in my case the process exits after a while after ctrl+c.

This is the output I get after `CTRL+C`:

![image](https://user-images.githubusercontent.com/21032419/48344293-9481cd00-e6af-11e8-809c-4c865bafbed5.png)

I know that the dev-server is still running because when I run the server again, it would complain that the port is already occupied and I have to manually kill that process.

**Comment by evilebottnawi** [comment]
@aprilmintacpineda Looks problem in `babel-node` here

**Comment by aprilmintacpineda** [comment]
I see, after doing only `webpack-dev-server --config webpack/start.js` it exited with no error. But then would need to refactor my codes for the build script to work without `babel-node`. Any suggestion?

**Comment by evilebottnawi** [comment]
@aprilmintacpineda better create issue in `babel-node`, we just listen `process` on `CTRL+C` and looks babel don't pass this to `webpack-dev-server` process

**Comment by ninofiliu** [comment]
I've got more or less the same behavior:

1. `webpack-dev-server --open`
2. Everything works fine when dev-serving the project
3. Hit Ctrl+C
4. `localhost:8080` doesn't serve anything anymore, however the node task launched by the dev server is still running (30% of the CPU power + ~400MB of RAM)

OS: Windows
Config: HMR enabled

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-dev-server/issues/1479#issuecomment-442492922
