### ISSUE TITLE
Equal socketUrl creation behavior for both local and remote environments

### ISSUE THREAD

**Issue by mike392** [webpack/webpack-dev-server#1490]
* Operating System: Win Server 2008
* Node Version:8.11.3
* NPM Version: 6.1.0
* webpack Version:4.16.5
* webpack-dev-server Version:3.1.5

In Webpack Dev Server, in index,js file, the url for sockjs-node mounting is assembled equally both for localhost and productive environment.

`var socketUrl = url.format({
  protocol: protocol,
  auth: urlParts.auth,
  hostname: hostname,
  port: urlParts.port,
  pathname: urlParts.path == null || urlParts.path === '/' ? '/sockjs-node' : urlParts.path
});`

I'm using Quasar as a framework, so it has a more or less but not totally customizable webpack.config. For instance, the devServer config looks like this:
` devServer: {
      https: false,
      port: 8080,
      publicPath: '/',
      open: true, // opens browser window automatically
      proxy: {
        '/oauth': {
          target: 'http://localhost:8081',
          secure: false,
          changeOrigin: true
          // pathRewrite: { '^/auth': '' }
        },
        '/api': {
          target: 'http://localhost:8081/api',
          secure: false,
          changeOrigin: true
          // pathRewrite: { '^/something': '' }
        },
        '/socket': {
          target: 'http://localhost:8081',
          secure: false,
          changeOrigin: true
          // pathRewrite: { '^/something': '' }
        }
      }
    }`

Thus, the WS is on /socket endpoint and handshakes to backend go well. But aprat from that there are also executed requests to **/sockjs-node** based on socketUrl.

Obviously, on remote environment I have only 80 port open. Thus, when there is assembled something like <hostname>/8080/sockjs-node** - it doesn't respond (given that <hostname>/sockjs-node** actually RESPONDS)

Honestly, I don't know how to set the nginx given that I have only 80 port opened and the requests are going to 8080 and thus are wasted even before being proxied by nginx.

Anyway, introduction of the change below in the **index,js** of webpack-dev-server module solved the problem for me but it seems to be really ugly.
`var socketUrl = url.format({
  protocol: protocol,
  auth: urlParts.auth,
  hostname: hostname,
  port: hostname === 'localhost' ? urlParts.port : '',
  pathname: urlParts.path == null || urlParts.path === '/' ? '/sockjs-node' : urlParts.path
});`

### Expected Behavior
Console has errors when connecting to sockjs-node nodes
![image](https://user-images.githubusercontent.com/16647651/45087613-35339980-b10f-11e8-9b35-553c7772b24a.png)

### Actual Behavior
There should be no errors both on local and remote environments

**Comment by evilebottnawi** [comment]
@mike392 it is hard and maybe impossible, why don't develop all locally?

**Comment by mike392** [comment]
@evilebottnawi, well thank you for the notice... I guess the best option here would be manually turn off the Hot Module Reloading on remote server like this:
`devServer: {
   hot: false
}`

**Comment by evilebottnawi** [comment]
@mike392 maybe, feel free to experiment with option, it is hard to give advice in you case
