### ISSUE TITLE
output.publicPath ignored when module.exports = [{}, {}];

### ISSUE THREAD

**Issue by xpepermint** [webpack/webpack-dev-server#150]
Example here https://github.com/webpack/webpack/tree/master/examples/i18n, when using webpack-dev-server.

**Comment by MrOrz** [comment]
@xpepermint I've also encountered this issue. `devServer`, as well as `output.publicPath`, are ignored when `webpack.config.js` exports an *array*. Currently I am doing stuff like this to get around:

```js
// Altered version of:
// https://github.com/webpack/webpack/blob/master/examples/i18n/webpack.config.js
//
// All edits are appended with "// EDIT:".

var path = require("path");
var I18nPlugin = require("i18n-webpack-plugin");
var languages = {
    "en": null,
    "de": require("./de.json")
};
module.exports = Object.keys(languages).map(function(language) {
    return {
        name: language,
        entry: "./example",
        output: {
            path: path.join(__dirname, "js"),
            filename: language + ".output.js",
            publicPath: "/some-public-path/" // EDIT: Populates __webpack_public_path__ for file-loader
        },
        plugins: [
            new I18nPlugin(
                languages[language]
            )
        ]
    };
});

// EDIT: Extend the exported array with additional keys:
//
module.exports.output = {
  publicPath: "/some-public-path/" // EDIT: for webpack-dev-server to serve files under /some-public-path/
};
module.exports.devServer = {/* devServer configurations */}
```

**Comment by xpepermint** [comment]
Huuum... that actually works (array with additional keys)? Nice hack @MrOrz. Thanks!
I hope this will be fixed in the near future.

**Comment by MrOrz** [comment]
Yeah it seems like when webpack-dev-server loads config, it didn't consider the case that the config is an array.

Speaking of fixing it, given an array of configurations (whose `publicPath` and `devServer` may vary), which config should webpack-dev-server take? There can be multiple bundles from an array of configuration, but there should be only one running dev-server.

**Comment by xpepermint** [comment]
@MrOrz I see your point. Good question. I guess the expected behavior would be to get different routes. I see `devServer` option as `route` configuration option.

**Comment by appsforartists** [comment]
I encountered a similar problem.  [In my case](https://gist.github.com/appsforartists/98e05f957f6bf47d58908d806e8de39e), I'd like to serve one file from `/dist/` and another from `/static/`.  As you can see, webpack serves both from `/dist/`, the value in the first config in my list.

**Comment by SpaceK33z** [comment]
This was fixed a while back, only the first item in the array with `devServer` will be selected now.

**Comment by precious** [comment]
Looks like the first element of array is selected unconditionally (even if it does not contain `devServer `).
