### ISSUE TITLE
Update doc: if filesystem has noatime option - watching doesn't work

### ISSUE THREAD

**Issue by Perlover** [webpack/webpack-dev-server#1500]
Brief: if filesystem has `noatime` (from **man** of Linux for example: *Do not update inode access times on this filesystem (e.g., for faster access on the news spool to speed up news servers). This works for all inode types (directories too), so implies nodiratime.*) you watch mode doesn't work - it doesn't see any changes.

This option to be suggested in many articles as optimization for SSD disks.

Related problem here too:
https://github.com/webpack/webpack/issues/2297#issuecomment-419966839

**Comment by evilebottnawi** [comment]
@Perlover Thanks for issue, but we use `chokidar` in `watchpack` (https://github.com/webpack/watchpack) for track fs events, looks better create this issue in `chokidar` repo. Sorry, we can't fix it on our side.
