### ISSUE TITLE
disableHostCheck true is not working

### ISSUE THREAD

**Issue by dineshmaths1** [webpack/webpack-dev-server#1507]
Am using Angular CLI: 6.2.2 , Node: 8.11.1 and OS: darwin x64 This is my etc hosts 127.0.0.1 dinesh.mysocialapi.com

This is my comment node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disableHostCheck true

am getting this error how to fix ? Loading failed for the with source “http://dinesh.mysocialapi.com/vendor.js”. dinesh.mysocialapi.com:34

**Comment by hg-pyun** [comment]
May be..  it related to #883 ?

**Comment by SpaceK33z** [comment]
Yep see #883.
