### ISSUE TITLE
README is not sufficient for new users to set up

### ISSUE THREAD

**Issue by lpender** [webpack/webpack-dev-server#1508]
The README is insufficient--it doesn't mention that an html template is required to serve your bundle, and that even if you have a template, the files are somehow served from memory and not actually built. This was quite confusing and time wasting for me. 

It should probably mention possibility of using `HtmlWebpackPlugin` to serve the basic HTML, or provide other options.

**Comment by ematipico** [comment]
Actually, HtmlWebpackPlugin is not needed. A index.html is enough.

But I agree that there should be a small paragraph about that!

**Comment by lpender** [comment]
If using an `index.html`, do you add a `script` reference to you bundle? Or does `webpack-dev-server` serve it from memory?

**Comment by michael-ciniawsky** [comment]
You need to add those manually if you're not using the `HTMLWebpackPlugin` which is unfeasable long-term. We need to document usage of the `HTMLWebpackPlugin`  as an example and eventually add a warning aswell

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/pull/2813
