### ISSUE TITLE
What are the equivalent of webpack-serve's "on" hooks?

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack-dev-server#1509]
Sorry if this is a question, but I can't find a solution.

I found myself migrating back to webpack-dev-server after [webpack-serve](https://github.com/webpack-contrib/webpack-serve) was deprecated. I found really useful to attach hooks in the webpack.config.js without having to touch node at all.

The hooks I used were `on.listening`, `on.build-finished`, `on.compiler-error` to show custom stats to the console. What are the equilvalent hooks in webpack-dev-server? I only found `after` that could substitute the `on.listening`, how do I attach hooks to the remaining two events, without having to run webpack from node?

Another thing I was doing:
```js
on: {
  listening: ({ server, options }) => {
    // try to open into the already existing tab
    openBrowser(`http://localhost:${options.port}`)
  },
},
```
How do I do this in webpack-dev-server? How do I get the port from the arguments in `after`?

**Comment by evilebottnawi** [comment]
@marcofugaro it is feature,  can you describe use case for this?

**Comment by marcofugaro** [comment]
Sure thing! Basically I was using these hooks to show only the information I need to the console (same thing I was using webpack-command for).

Here is config I was using, take a look at the comments:
```js
const formatWebpackMessages = require('react-dev-utils/formatWebpackMessages')
const openBrowser = require('react-dev-utils/openBrowser')
const prettyMs = require('pretty-ms')

module.eports = {
  serve: {
    port: 8080,
    // don't show all the default webpack stuff
    logLevel: 'silent',
    hotClient: {
      logLevel: 'silent',
    },
    devMiddleware: {
      logLevel: 'silent',
    },
    on: {
      listening: ({ options }) => {
        // try to open into the already existing tab
        openBrowser(`http://localhost:${options.port}`)
      },
      'build-finished': ({ stats }) => {
        if (stats.hasErrors()) {
          return
        }
        
        const time = prettyMs(stats.endTime - stats.startTime)
        console.log(`Compiled successfully in ${time}`)
      },
      'compiler-error': stats => {
        // format the errors in a nicer way
        const messages = formatWebpackMessages(stats.json)
        console.log(messages.errors[0])
      },
    },
  },
}

```

**Comment by aszmyd** [comment]
Check out this plugin: https://www.npmjs.com/package/event-hooks-webpack-plugin

**Comment by polco** [comment]
what about the solution given in this issue: https://github.com/webpack/webpack-dev-server/issues/132 ?

**Comment by marcofugaro** [comment]
@polco as I already specified, I don't want to call webpack from node, I have a simple webpack.config.js and want to keep it that way.

**Comment by polco** [comment]
My bad

**Comment by evilebottnawi** [comment]
PR welcome, it is should be not diffucult

**Comment by atilkan** [comment]
@evilebottnawi Could you stop writing PR welcome on every issue.

**Comment by evilebottnawi** [comment]
@atilkan What is the problem?

**Comment by alexander-akait** [comment]
I want to close this issue in favor of webpack's built-in hooks, also we have some callbacks, like `before`/`after`, so I think it should be enough to implement the same behaviour, anyway if you really need something new feel free to open an issue with example what is missing
