### ISSUE TITLE
Port seems to be open, but connection refused

### ISSUE THREAD

**Issue by 11111000000** [webpack/webpack-dev-server#151]
if I access via localhost:2015 - all works fine, but 192.168.7:2015 (my IP in local net) - CONNECTION REFUSED

**Comment by 11111000000** [comment]
one of the previous version 1.7.0 - work's ok

**Comment by 11111000000** [comment]
Maybe something like that http://serverfault.com/questions/78048/whats-the-difference-between-ip-address-0-0-0-0-and-127-0-0-1

**Comment by 11111000000** [comment]
Yes, when I set --host 0.0.0.0  - all start workin, please add this to Documentation

**Comment by gsklee** [comment]
+1

**Comment by gsklee** [comment]
For reference: https://github.com/webpack/webpack-dev-server/issues/147

**Comment by troutowicz** [comment]
Not sure why this should have to be added to the documentation. The 0.0.0.0 address is not a feature of webpack-dev-server, it is part of IPv4. A basic knowledge of networking is kind of expected when configuring a web application.

**Comment by 11111000000** [comment]
ok

**Comment by steida** [comment]
Pardon my ignorance, but what exactly I should do to prevent this message? It worked with previous webpack. Do I have something wrong in my settings? https://github.com/steida/este/tree/master/webpack

**Comment by troutowicz** [comment]
I'm not sure why it would have worked in a previous version, but your dev server config is currently written to only listen on the device's loopback interface [here](https://github.com/steida/este/blob/master/webpack/devserver.js#L29).

Try something like:
```js
new WebpackDevServer(webpack(webpackConfig), options).listen('8888', callback);
```

**Comment by steida** [comment]
Didn't help, same behavior :(

**Comment by troutowicz** [comment]
What behavior are you referring to? More information would be helpful.

**Comment by steida** [comment]
I think I got it. Piping is restarting server, and it seems also webpack-dev-server is restarted.  https://github.com/steida/este/blob/master/src/server/index.js#L3

Thank you for directing me.

**Comment by gsklee** [comment]
> Not sure why this should have to be added to the documentation

@troutowicz I disagree. The official documentation currently has 0 mentions regarding this newly added `host` config option, and some people will need this option to make things work in 1.8.0 again. Can't expect everyone to come up here and dig for clues for solutions.

**Comment by troutowicz** [comment]
http://webpack.github.io/docs/webpack-dev-server.html#cli

I added the `--host` flag to the docs a while back. I am with you that that should be in the docs. I interpreted @11111000000's comment as a request for an explanation on the meaning of `0.0.0.0`.

**Comment by ScreenDriver** [comment]
`--host 0.0.0.0` should be added to the docs. Only a little hint that `0.0.0.0` is enough to access the machine from other machines like mobile devices.

**Comment by deepkolos** [comment]
problem still after add --host 0.0.0.0 to cli, but i solved by use another hotspot share software `wifi共享大师` 

before that i use `小度WIFI`

just mark the solution who may use `小度WIFI` still got connection refused
