### ISSUE TITLE
WDS not opening a browser tab when `open: true` is set (Node API)

### ISSUE THREAD

**Issue by aryzing** [webpack/webpack-dev-server#1510]
* Operating System: Ubuntu 18.04
* Node Version: v10.11.0
* NPM Version: 6.4.1
* webpack Version: 4.20.2
* webpack-dev-server Version: 3.1.9

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

You can check out this [barebones repo](https://github.com/aryzing/reproducing-WDS-no-broswer-open) reproducing the issue.

The WDS is using via it's Node API with `open: true`.

### Expected Behavior

Browser tab should open

### Actual Behavior

No browser tab is opened

### For Bugs; How can we reproduce the behavior?

You can check out this [barebones repo](https://github.com/aryzing/reproducing-WDS-no-broswer-open) reproducing the issue.

**Comment by hiroppy** [comment]
`open`(https://github.com/webpack/webpack-dev-server/blob/master/bin/utils.js#L91-L95) seems to be called only by webpack-dev-server.js(https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js) (as `status`). 
package.json calls `"lib/Server.js"`.

**Comment by evilebottnawi** [comment]
@hiroppy yep, we should move all starting with https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L172 in `lib/Server`, it is fix when you use Node API, it is architecture bug and will be great fix it.
