### ISSUE TITLE
Document the supported options for starting WebpackDevServer directly

### ISSUE THREAD

**Issue by kevinburke** [webpack/webpack-dev-server#1517]
It is difficult to figure out which configuration options the WebpackDevServer constructor supports directly. It would be good to provide a list without requiring people to spelunk through the source code.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
