### ISSUE TITLE
contentBase: Expose Watch Options

### ISSUE THREAD

**Issue by araphiel** [webpack/webpack-dev-server#1518]
https://github.com/webpack/webpack-dev-server/blob/ddc1e2c6d266823fcb9be1a018f8beeb4de4ab1c/lib/Server.js#L672-L683

Issue: 
    1. watchContentBase only watches the top level folder
    2. contentBase doesn't seem to work with path globs.

For larger static projects, this means hot reloading will not work after the top level path ie:

- /index.html - will cause change
- /foobar/index.html - won't trigger change

Is it possible to expose the chokidar options or depth level so we can access it?

```
// webpack.config.js
devServer: {
    host: '0.0.0.0',
    publicPath: '/assets/dist',
    contentBase: '_site',
    hot: true,
    inline: true,
    open: true,
    watchContentBase: true,
    before(app, server) {
        server._watch(extraPath, options)
    }
},

```

**Comment by araphiel** [comment]
Turns out contentBase was enough for my usecase but this could be worth a gander

**Comment by marcofugaro** [comment]
@araphiel how did you solve this issue for your project??

**Comment by araphiel** [comment]
Hi @marcofugaro,

Honestly, I misunderstood Webpack + WDS.

In my instance, I used Webpack to compile CSS & JS for use with my static site generator.
Setting `contentBase` to the root directory used for my dev build - was enough to handle this.

However, if you needs are more comprehensive - you can manually run an additional callback that uses chokidar with more depth settings using `devServer.before` or `devServer.after`. However,  I wouldn't recommend this if possible.
