### ISSUE TITLE
How to use proxy.bypass function to change from POST to GET

### ISSUE THREAD

**Issue by cfkxzsat** [webpack/webpack-dev-server#1521]
Seems like here is the more appropriate place to ask...
[https://github.com/chimurai/http-proxy-middleware/issues/302](https://github.com/chimurai/http-proxy-middleware/issues/302)
Appreciated!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
