### ISSUE TITLE
Failed to serve over https when using ECDSA cert on node 8

### ISSUE THREAD

**Issue by nekolab** [webpack/webpack-dev-server#1529]
* Operating System: macOS 10.14
* Node Version: v8.12.0
* NPM Version: 6.4.1
* webpack Version: 4.18.0
* webpack-dev-server Version: 3.1.9

- [x] This is a **bug**
- [ ] This is a **modification** request

### For Bugs; How can we reproduce the behavior?
Use OpenSSL generate an ECDSA certificate, then run dev server with `--https` `--key` and `--cert`

Visit the generated resource url (like: https://127.0.0.1:1234/js/common.js) in browser

### Expected Behavior
Browser load generated resource

### Actual Behavior
Browser, curl and any http client says `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

This is a node 8 only issue (compared with node 6 and 10), I believe it is related with https://github.com/nodejs/node/issues/16196

**Comment by evilebottnawi** [comment]
@nekolab Any ideas how we can fix it?

**Comment by evilebottnawi** [comment]
Also can you create minimum reproducible test repo to ensure it is problem for node, not in local environment?

**Comment by nekolab** [comment]
A really simple repro on: https://github.com/nekolab/repro-webpack-dev-server-1529

Run `npm run dev` on different version of nodejs (6/8/10),  and visit https://localhost:8081/ , you will see only node 8 will cause `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`

Not dig into how wds server content now, but `require("tls").DEFAULT_ECDH_CURVE = "auto"` may helps, if you guys use third-party library to do the job, maybe we should fill an upstream issue for this

**Comment by nekolab** [comment]
Hi @evilebottnawi 

A quick test confirm adding `require("tls").DEFAULT_ECDH_CURVE = "auto";` to the first line of `Server.js` can slove this issue.

If you think this way is acceptable to webpack dev server, I can create a pull request for it

**Comment by nekolab** [comment]
Fixed in https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.10

Pull Request: https://github.com/webpack/webpack-dev-server/pull/1531
