### ISSUE TITLE
forward build time error to client

### ISSUE THREAD

**Issue by queckezz** [webpack/webpack-dev-server#153]
Not sure if I'm doing something wrong but as of right now, if you create say a syntax error in your code, you get an error in the console:

![screenshot from 2015-04-12 22 36 51](https://cloud.githubusercontent.com/assets/2580598/7107388/87fd0c60-e164-11e4-9bb4-df59657202ba.png)

I'm using *webpack-dev-server* together with [react-hot-loader](https://github.com/gaearon/react-hot-loader).

On the client side however, you can't see the error message and it seems that everything is working fine. It's always taking me quite some time to finally realize that there could be a compile error. Is there something similar like [browserify has](https://github.com/zertosh/errorify)? Basically just forwards the error from the console to the client and displaying it there.

**Comment by 3went2** [comment]
+1

**Comment by 3went2** [comment]
+1

**Comment by sokra** [comment]
We already do this. Errors are forwarded to the client via socket.io and displayed in the browser console.

**Comment by queckezz** [comment]
While testing I'll forgot to remove:
```js
new webpack.NoErrorsPlugin()
```
