### ISSUE TITLE
Set a process.env to see if webpack-dev-server was used

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack-dev-server#1532]
* Operating System: Mac OS
* Node Version: 8 LTS
* NPM Version: I use yarn
* webpack Version: 4
* webpack-dev-server Version: 3.1.9

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

[Old `WEBPACK_SERVE` usage in our config.](https://github.com/Mercateo/ws/blob/cd81606d5c0704dc2a74d6c3310d3ce95d0c87c1/packages/ws/src/configs/webpack.ts#L49)

### For Features; What is the motivation and/or use-case for the feature?

I try to migrate to this package from `webpack-serve`. We previously used `process.env.WEBPACK_SERVE` to see, if a project asks for a watch config or not. We'd like to keep a similar functionality without having every project to do add a process env on their own, before they call `webpack-dev-serve`. Maybe there could be a `process.env.WEBPACK_DEV_SERVER` flag.

https://github.com/webpack-contrib/webpack-serve#setting-the-config-mode

---

FYI: This template says _" Please note that we are NOT accepting FEATURE requests at this time."_ while in https://github.com/webpack-contrib/webpack-serve it's said _"Please use webpack-dev-server (he is in support and update mode again). Feel free to create a issue if some features are not implemented in webpack-dev-server."_ ⚠

**Comment by evilebottnawi** [comment]
@donaldpipowitch PR welcome
