### ISSUE TITLE
Inline: true prevents a script from running

### ISSUE THREAD

**Issue by YonatanKra** [webpack/webpack-dev-server#1536]
* Operating System: Windows 10
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 4.22.0
* webpack-dev-server Version: 3.1.9

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/YonatanKra/web-components-ui-elements/tree/webpack-dev-server-case
The config is inside the `config` folder.

### Expected Behavior

I'd expect web-pack-dev-server to run the script in demo/index.js in `inline` mode.

### Actual Behavior

The script is never run in `inline` mode.

### For Bugs; How can we reproduce the behavior?

1. Clone and checkout the `webpack-dev-server-case` branch.
2. yarn
3. npm run build
4. npm run serve
5. Open in chrome browser: `localhost:8080`

Checking results:
1. Note that on localhost:8080 the inline code is run, but the actual `demo/index.js` code is never run 
2. Open the `dist/index.html` in the browser - see it runs the demo/index.js
3. Change the `inline` property of the dev-server config (inside `config/webpack.dev.js`) to `false` and see that the script runs as usual.

**Comment by evilebottnawi** [comment]
@YonatanKra Why you use `inline`?

**Comment by evilebottnawi** [comment]
@YonatanKra i.e. without `inline` it is not work as expected?

**Comment by YonatanKra** [comment]
@evilebottnawi yes. I don't usually use `inline`. It just didn't work, so I tried to pinpoint the issue and found out that when I use `inline: false` it is OK (e.g. when it uses the iFrame to reload the page).

**Comment by YonatanKra** [comment]
@evilebottnawi were you able to reproduce the issue?

**Comment by evilebottnawi** [comment]
@YonatanKra i will see in this in near future

**Comment by maclockard** [comment]
FWIW I was running into this issue as well, but bumping to the latest version webpack-dev-server resolved it.

Version: 3.2.1

**Comment by evilebottnawi** [comment]
Latest version works find, just update to the latest version
