### ISSUE TITLE
Live reloading not work in Node.js API

### ISSUE THREAD

**Issue by felixcatto** [webpack/webpack-dev-server#1544]
* Operating System: Ubuntu 16.04
* Node Version: v10.12.0
* NPM Version: 6.4.1
* webpack Version: 4.22.0
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I created a simple repo https://github.com/felixcatto/wds-test
[webpack.config.js](https://github.com/felixcatto/wds-test/blob/master/webpack.config.js)
[server.js](https://github.com/felixcatto/wds-test/blob/master/server.js)

I try to run Node.js API example, but seems that live reloading not work. When i use `npx webpack-dev-server` live reloading work. When i use Node.js API `node server.js`, wds compile my code but does not live reload page :'(

**Comment by evilebottnawi** [comment]
@felixcatto you need `hot: true` in `devServer` and `new webpack.HotModuleReplacementPlugin()`, here docs https://webpack.js.org/guides/hot-module-replacement/.
