### ISSUE TITLE
cli double dash question

### ISSUE THREAD

**Issue by uxweb** [webpack/webpack-dev-server#1545]
Hi!

Just a quick question:

What does the double dash (`--`) option for the cli means? I've seen it on all the cli examples.

```
npm run webpack-dev-server -- --open
```

**Comment by michael-ciniawsky** [comment]
`npm` will pass all the arguments after the `--` directly to your script (e.g `webpack-dev-server`)

**Comment by evilebottnawi** [comment]
@uxweb Answer is above. Thanks!
