### ISSUE TITLE
macOS: sometimes can't work

### ISSUE THREAD

**Issue by mzpuu** [webpack/webpack-dev-server#1550]
* Operating System:macOS Mojave (10.14) & macOS High Sierra (10.13)
* Node Version:v10.6.0
* NPM Version:6.1.0
* webpack Version:3.10.0
* webpack-dev-server Version:2.9.7

- [√] This is a **bug**
- [ ] This is a **modification** request

### Code

   Problem Description:  Sometimes the browser does not automatically refresh after the file in a folder has been modified.After modifying the file name, it does work again.Or re-execute npm run dev.I don't know how to reproduce it.

**Comment by evilebottnawi** [comment]
> I don't know how to reproduce it.

We don't know how to fix it, sorry. People create minimum reproducible test repo and recreate issue.
