### ISSUE TITLE
I don't want to open index.html by default。Is there any other way?

### ISSUE THREAD

**Issue by wangzhigang** [webpack/webpack-dev-server#1551]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* webpack-dev-server Version:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  // webpack.config.js
```

```js
  // additional code, remove if not needed.
```

**Comment by evilebottnawi** [comment]
Use `open: false`, in future use issue template, it is bug tracker not `stackoverflow`

**Comment by wangzhigang** [comment]
Such as:
page:
    index.html
    about.html
    news.html
    ......

I want to select the page I want to preview instead of opening page's folder and open index.html by default。

but，Configure index:'' to report an error。
devServer: {
        contentBase: [
            path.join(ROOT, 'src/')
        ],
        index:''
}
