### ISSUE TITLE
Do not want to open a folder, automatically jump to index.html。Is there any other way?

### ISSUE THREAD

**Issue by wangzhigang** [webpack/webpack-dev-server#1554]
I want to select the page I want to preview instead of opening page's folder and open index.html by default。Because I'm a multi-page project, I want to be able to select the file I want to preview. Instead of automatically opening index.html

Such as:
The entry page，page folder:
index.html
about.html
news.html
......

but，Configure index:'' to report an error。
devServer: {
contentBase: [
path.join(ROOT, 'src/')
],
index:''
}

**Comment by evilebottnawi** [comment]
Please use issue template, feel free to recreate issue using issue template
