### ISSUE TITLE
Do not want to open a folder, automatically jump to index.html。Is there any other way?

### ISSUE THREAD

**Issue by wangzhigang** [webpack/webpack-dev-server#1556]
Operating System: mac
    Node Version: 10.9.0
    NPM Version: 6.2.0
    webpack Version: 3.11.0
    webpack-dev-server Version: 2.8.2

This is a bug
This is a modification request

### `Code`
```
devServer: {
	contentBase: [
		path.join(ROOT, 'src/')
	],
	open:false,
	disableHostCheck: true, 
	hot: false,
        index:'',
	host: '0.0.0.0',
	port: 6060
}
```

### Expected Behavior
go to http://0.0.0.0:6060/view/page/ will open the default index. HTML。
I want to select the page I want to preview instead of opening page's folder and open index.html by default。Because I'm a multi-page project, I want to be able to select the file I want to preview. Instead of automatically opening index.html

Such as:
The entry page，page folder:
index.html
about.html
news.html
......

### Actual Behavior
but，Configure index:'' to report an error。
```
devServer: {
contentBase: [
path.join(ROOT, 'src/')
],
index:''
}
```

### For Features; What is the motivation and/or use-case for the feature?
It's a multi-page project

**Comment by evilebottnawi** [comment]
@wangzhigang Please create minimum reproducible test repo, can't reproduce

**Comment by GaryHos** [comment]
` devServer: {
        openPage: './pages/login/index.html', 
    }`

**Comment by evilebottnawi** [comment]
@GaryHos Thanks for answer and helping
