### ISSUE TITLE
Hot module: ERR_INVALID_CHUNKED_ENCODING 

### ISSUE THREAD

**Issue by xtx1130** [webpack/webpack-dev-server#1561]
* Operating System: MAC OS 10.12.6
* Node Version: v9.2.0
* NPM Version: v5.5.1
* webpack Version: ^4.16.0
* webpack-dev-server Version:^3.1.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
The code is almost build with vue-cli:
```js
devServer: {
    clientLogLevel: 'warning',
    historyApiFallback: {
      // rewrites: [
      //   { from: /^\/search($|\/$|\/.*)/, to: path.posix.join(config.dev.assetsPublicPath, 'search.html') },
      //   { from: /.*/, to: path.posix.join(config.dev.assetsPublicPath, 'index.html') },
      // ],
      rewrites: Object.keys(routers)
        .sort((key1, key2) => routers[key2].priority - routers[key1].priority)
        .map((key) => {
          return {
            from: routers[key].from,
            to: path.posix.join(config.dev.assetsPublicPath, routers[key].to ?  `${routers[key].to}.html`: `${key}.html`)
          }
       })
    },
    disableHostCheck: true,
    hot: true,
    contentBase: false, // since we use CopyWebpackPlugin.
    compress: true,
    host: HOST || config.dev.host,
    port: PORT || config.dev.port,
    open: config.dev.autoOpenBrowser,
    overlay: config.dev.errorOverlay
      ? { warnings: false, errors: true }
      : false,
    publicPath: config.dev.assetsPublicPath,
    proxy: config.dev.proxyTable,
    quiet: true, // necessary for FriendlyErrorsPlugin
    watchOptions: {
      poll: config.dev.poll,
    }
  }
```
### Expected Behavior
I choose `Slow  3G` mode in chrome inspector. I hope my `main.js` can request successfully.
npm scripts: `npm run dev`

### Actual Behavior
![image](https://user-images.githubusercontent.com/5475069/47988768-15741e00-e11e-11e8-92e6-d4102313d200.png)
But it got an error, and I use charles to catch the request:
![image](https://user-images.githubusercontent.com/5475069/47988901-68e66c00-e11e-11e8-9e12-83373e91ffa4.png)

### For Bugs; How can we reproduce the behavior?
I think it can reproduce by using `vue-cli` create an app. At least I reappear like this.

**Comment by evilebottnawi** [comment]
@xtx1130 Please create minimum reproducible test repo, thanks!

**Comment by xtx1130** [comment]
@evilebottnawi  I have tried to use pure `vue-cli` to  reshow this bug, but I failed. May be `nginx` caused this error.I will close this issue, thanks for you reply :)
