### ISSUE TITLE
No way to have multiple remote IPs have different headers on proxied requests

### ISSUE THREAD

**Issue by cinderblock** [webpack/webpack-dev-server#1570]
* Operating System: `Windows 10`
* Node Version: `v8.11.2`
* NPM Version: `5.6.0`
* webpack Version: `4.25.1`
* webpack-dev-server Version: `3.1.10`

- [ ] This is a **bug**
- [x] This is a **modification** request

### Problem

Currently, there seems to be no easy way to programmatically use different headers for different remote clients. This is critical for testing certain backend features, especially if multiple clients are connecting to the same devserver for testing. Currently you are forced to use static strings for any extra headers and this does not allow for more than one remote IP to be tested with concurrently.

```webpack.config.js
// webpack.config.js
module.exports = {
  // ...
  devServer: {
    proxy: {
      '/path': {
        target: 'http://localhost:8000',
        headers: {
          'X-Forwarded-*': '...',
        },
      },
    },
  },
};
```

### Suggestion

Add an option to `proxy` objects called something like `addForwardedHeaders` that accepts:

 - `true` - The equivalent of `['For', 'Proto', 'Port']`
 - List - Specify list of standard headers that get automagically filled with the correct values
 - Object - Allows limited control over which actual headers get set to what values
   ```js
   {
     For: 'client.ip',
     Proto: 'client.protocol',
     Port: 'client.port',
   }
   ```
 - Function - Allows complete programmatic control when setting headers on every request

### Alternative

I suppose this would be possible by adding a `before` middleware but I haven't explored that and feel like this would be a useful and easier to use feature regardless.

**Comment by evilebottnawi** [comment]
@cinderblock can you describe use case more verbosely with examples?

**Comment by cinderblock** [comment]
I see webpack-dev-server in a development environment as an equivalent to nginx in a full production environment.

In nginx, there is a special variable [`$proxy_add_x_forwarded_for`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#variables) just for the purpose of informing a proxied application who is actually connected.

Configurations usually look something like this:

```nginx
server {
  listen 80;
  server_name my.server.com;
  location /api {
    # api backend that we're proxying
    proxy_pass http://localhost:8000;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # Other headers omitted
  }
}
```

*Note, I'm ignoring the new [RFC 7239 `Forwarded` header](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/) for now, but the same ideas still apply.*

So in a production environment, proxied requests to the api running at port 8000 will have headers that accurately reflect the remote IP of each client that is connected.

In webpack-dev-server, there is currently no equivalent feature to this making it impossible to test having multiple different clients connected to the same backend while connecting through webpack-dev-server.

----

#### Example use case

`Client 1` and `Client 2` have different IPs. The api backend needs to be able to differentiate the clients based on IP.

```
Client 1 -\                                 /- index.html (and other webpacked files)
           >-- nginx/webpack-dev-server ---<
Client 2 -/                                 \- /api (some other backend)
```

**Comment by cinderblock** [comment]
Ooops. I don't know how I missed that.

----

This is all I needed:
```webpack.config.js
module.exports = {
  // ...
  devServer: {
    proxy: {
      '/path': {
        target: 'http://localhost:8000',
        xfwd: true,
      },
    },
  },
};
```
