### ISSUE TITLE
Build and live Reload

### ISSUE THREAD

**Issue by ItamarShDev** [webpack/webpack-dev-server#1571]
* Operating System: Ubuntu 18.10
* Node Version: 8.11.3
* NPM Version: 5.6.0
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior
Ability to build the app and live reload it
### Actual Behavior
no happening (or otherwise, unknown how to achieve is

### For Features; What is the motivation and/or use-case for the feature?
It would help to run the app from the server's port on local for various features
We have RoR server.

When using the dev-server, we need to run on different port, which blocks us from using some server features on local.

currently we build it and run it from server with manual refresh if we need to check the behavior.

> This issue is merely a question of feasibility.

**Comment by evilebottnawi** [comment]
@ItamarShDev just setup you port, what is problem i can't understand

**Comment by ItamarShDev** [comment]
@evilebottnawi which port?
if i set the webpack to be same as the server, then they are conflicted.

**Comment by evilebottnawi** [comment]
@ItamarShDev it is hard to understand what you want, maybe you can create minimum reproducible test repo and what you expected?

**Comment by ItamarShDev** [comment]
I will try.
What i want is to be able to run production compilation in dev-server, with hot reload.
Its sounds to me like an unfeasible idea, and I wanted to just ask

**Comment by evilebottnawi** [comment]
Don't use this server for `production`.

**Comment by ItamarShDev** [comment]
Not what I've meant.
I use it to develop.
