### ISSUE TITLE
Retry port finding

### ISSUE THREAD

**Issue by u9520107** [webpack/webpack-dev-server#1572]
* Operating System: Windows 10
* Node Version: 10.12.0
* NPM Version: 6.4.1 (yarn 1.12.1)
* webpack Version: 4.21.0
* webpack-dev-server Version: 3.1.9

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
  // Not really config related issue
```

### Expected Behavior
When I start 2 instances of dev servers without specifying port, both instances can figure out available ports and start up correctly.

### Actual Behavior
During the findPort phase, both instances will find the same port that is not being used, then both instances will try to use the same port to start the server, resulting in one of them inevitably errors out.

### For Features; What is the motivation and/or use-case for the feature?
I am not sure how often people try to fire up multiple instances like this, so I'd consider this a feature request. And I think for a workbench like monorepo setup to quickly prototype ideas, this feature can be helpful.
It is possible add a retry port finding procedure when starting servers, so that when this kind of race condition occurs, the instance that lost the race would find the next available port and try again?
I know is is potentially bad if there is no limit to the retry mechanism, perhaps a new parameter for specifying the allowed port ranges would be helpful?

**Comment by evilebottnawi** [comment]
@u9520107 Feel free to send a PR
