### ISSUE TITLE
Can webpack-dev-server serves compiled assets on disk?

### ISSUE THREAD

**Issue by weaponhe** [webpack/webpack-dev-server#1573]
In general, webpack-dev-server serves webpack assets in memory, but the compilation is time-consuming When I need to start webpack-dev-server on different machine for various purposes, for example, e2e test. Can webpack-dev-server serves compiled assets on disk so that I can complied once and run anywhere as well as taking advantage of some options of webpack-dev-server like devServer.proxy?

**Comment by evilebottnawi** [comment]
@weaponhe use this option https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L57, need documentation, feel free to create issue about this in webpack docs repo, thanks!
