### ISSUE TITLE
Hostname Mapping in Dev-Server

### ISSUE THREAD

**Issue by killemth** [webpack/webpack-dev-server#1581]
How can you define different entry points in the dev-server based on hostname?

For example, host1.localhost should serve content from the folder /entry1, and host2.localhost should serve content from the folder /entry2.

**Comment by killemth** [comment]
It seems that the dev-server can be manipulated to change the content it serves by intercepting the request as per below.

`    before: function (app, server) {
      app.get('/', function (req, res, next) {
        console.log(req.hostname);
        if (req.hostname.indexOf('host1') === 0) {
          console.log('changing route');
          res.sendFile(path.resolve(__dirname, '../dist/entry1/index.html'));
        } else {
          res.sendFile(path.resolve(__dirname, '../dist/index.html'));
        }
      });
    },`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
