### ISSUE TITLE
Sockjs instances keeps piling up - creating multiple reload each time

### ISSUE THREAD

**Issue by ashleymoogle** [webpack/webpack-dev-server#1582]
* Operating System: MacOs Mojave 10.14.1
* Node Version: 9.4.0
* NPM Version: 5.6.0 / Yarn 1.6.0
* webpack Version: 4.25.1
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

webpack-dev-server keeps adding instances of sockjs each time I make a modification in the code and HMR is triggered which in turn causes the app to reload each time more and more the more instance there is.
Here is a gif of what happens in the network:
https://imgur.com/a/CjnhGT9

```js
  devServer: {
            port: 3030,
            hot: true,
            inline: true,
            stats: "errors-only",
            contentBase: 'assets',
            publicPath: '/dist/'
        }
```

### Expected Behavior
Having only one stream of sockjs
### Actual Behavior
Multiple WS stream are added at each HMR which trigger multiple rendering each time
### For Bugs; How can we reproduce the behavior?
No idea :(

**Comment by evilebottnawi** [comment]
Try to don't use `inline`, without reproducible test repo i can't help and issue will be closed

**Comment by ashleymoogle** [comment]
I found the issue:
I have a plugin that inject the js bundle in my html entry point and for some reasons it keeps injecting the bundle and the bundle bundle.hot-update.js so it keeps piling up

**Comment by evilebottnawi** [comment]
@ashleymoogle looks problem in plugin, maybe you can create minimum reproducible test repo with plugin

**Comment by yuri-sakharov** [comment]
Also got polling after update to 3.1.11 and higher. There is no polling on version 3.1.10. Downgraded.

**Comment by evilebottnawi** [comment]
@yuri-sakharov what? polling !== multiple reloading

**Comment by evilebottnawi** [comment]
@yuri-sakharov do you solve problem?

**Comment by yuri-sakharov** [comment]
solved via downgrade to 3.1.10

**Comment by yuri-sakharov** [comment]
@evilebottnawi I will try

**Comment by yuri-sakharov** [comment]
I just checked it in v3.2.1 and see that problem with polling was fixed.

**Comment by evilebottnawi** [comment]
Closing, feel free to feedback, if somebody has problem feel free to create new issue
