### ISSUE TITLE
Map is undefined in ie9

### ISSUE THREAD

**Issue by kwzm** [webpack/webpack-dev-server#1583]
* Operating System: win7 64bit
* Node Version: 8.12.0
* NPM Version:  6.4.1
* webpack Version:  4.9.1
* webpack-dev-server Version: 3.1.9

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

use create-react-app

### Expected Behavior

webpack-dev-server can run in ie9

### Actual Behavior

I use create-react-app init a application, and view the page in ie9 in dev environment, but found this error:

![default](https://user-images.githubusercontent.com/16114101/49213081-6c5bd300-f3fe-11e8-9155-07201201b0ba.PNG)

in English is Map is undefined

I know webpack-dev-server from 2.8.0 use es6 syntax, so I want use babel to translate it:

1. I use babel-loader to compile it:

![default](https://user-images.githubusercontent.com/16114101/49213706-d759d980-f3ff-11e8-9071-500223123385.PNG)

2. I try to use @babel/polyfill
`import '@babel/polyfill'`

3. I try to use core-js
`import 'core-js/es/array/map'`

But never work, the error is still there.

### For Bugs; How can we reproduce the behavior?

use create-react-app init a app and `npm start` then open ie9 view the page

**Comment by montogeek** [comment]
Try with `https://github.com/zloirock/core-js#map` not `Array.prototype.map`

**Comment by evilebottnawi** [comment]
Please post this issue in `create-react-app`

**Comment by kwzm** [comment]
@montogeek Thanks I will try.

**Comment by kwzm** [comment]
@montogeek I tried it, but didn't work, I guess maybe is create-react-app's bug as @evilebottnawi  said.

![default](https://user-images.githubusercontent.com/16114101/49263202-7aeccd80-f484-11e8-96b2-9032c022ca63.PNG)
