### ISSUE TITLE
Missing module dependency between shared and async bundles causing code updates to disappear

### ISSUE THREAD

**Issue by AnujRNair** [webpack/webpack-dev-server#1584]
* Operating System: Mac
* Node Version: 10.1.0
* NPM Version: 6.0.1
* webpack Version: 4.26.1
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Overview
I'm not sure if this is a webpack or a webpack dev server bug, but it looks like there might be a missing module dependency between async and shared bundles in some edge cases.

At @slackhq, we've run into an interesting bug where changing code, and allowing webpack-dev-server to recompile the code, has resulted in code simply disappearing from the updated bundles! 

I've narrowed this down to the relationship between shared bundles and async bundles which webpack / webpack-dev-server eventually creates - if you have a long dependency tree where you reexport modules over and over, webpack updates the import definitions for code in the shared bundle, but not in the async bundle. This means that there is a mismatch in variable names, and so that variable becomes undefined.

### Code
The bug has been replicated in this minimal reproducible repo here: https://github.com/AnujRNair/webpack-missing-module-dependency

### Expected Behavior
Both the shared bundle and the async bundle should be updated to reflect the latest code changes.

### Actual Behavior
Only the shared bundle is updated. The async bundle remains the same.

### For Bugs; How can we reproduce the behavior?
Follow the instructions in the repo linked above.

### For Features; What is the motivation and/or use-case for the feature?
N/A

**Comment by evilebottnawi** [comment]
@AnujRNair i think better create issue in `webpack`, we just webpack server and run `webpack` using api

**Comment by AnujRNair** [comment]
@evilebottnawi thanks! I posted an issue there: https://github.com/webpack/webpack/issues/8455
