### ISSUE TITLE
Installed 3.1.10 and now my application won't compile

### ISSUE THREAD

**Issue by markleppke** [webpack/webpack-dev-server#1587]
* Operating System: Windows 10 : version 1803
* Node Version: 10.14.1
* NPM Version: 6.5.1
* webpack Version:
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Application would compile

### Actual Behavior
Fails to compile and gives the following error
Module not found: Error: Can't resolve 'loglevel' in 'C:\Source\Portal\Portal\Outsell.Dep.Web.Client\node_modules\webpack-dev-server\client'

Previous versions 3.1.9 and 3.1.8 compile.

**Comment by evilebottnawi** [comment]
@markleppke `npm cache clean`/`yarn cache clean`
