### ISSUE TITLE
Allow absolute URL as the `openPage` option

### ISSUE THREAD

**Issue by runarberg** [webpack/webpack-dev-server#1594]
* Operating System: Ubuntu 18.04
* Node Version: 11.2.0
* NPM Version: 6.4.1
* webpack Version: 4.26.1
* webpack-dev-server Version: 3.1.10

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
  // webpack.config.js
{
    entry: './src/index.js',
    output: {
        filename: 'main.[hash].js',
        path: path.resolve(__dirname, 'dist'),
    },
    devServer: {
        contentBase: path.resolve(__dirname, 'dist'),
        historyApiFallback: true,
        open: true,
        openPage: 'http://test.example/',
        allowedHosts: [
            'test.example',
        ],
    },
}
```

### Expected Behavior

Browser should open a page at http://test.example/

### Actual Behavior

Browser opens a page at http://localhost/http://test.example/

### For Features; What is the motivation and/or use-case for the feature?

The app that I am developing has a different behavior based on the hostname that it runs on. I never test it on `localhost` as it does not have a specific behavior under that hostname. It is kind of annoying to have to change the host name each time I start the server. Hence I would like to specify an absolute URL as the `openPage`.

**Comment by evilebottnawi** [comment]
It is bug, we need fix it, feel free to send a PR

**Comment by misterdev** [comment]
@evilebottnawi are you sure this is a bug?

I read this in the [documentation](https://webpack.js.org/configuration/dev-server/#devserver-openpage): 

> devServer.openPage 
> Specify a page to navigate to when opening the browser.

The correct option to use in this case is [host](https://webpack.js.org/configuration/dev-server/#devserver-host)

> devServer.host 
> Specify a host to use. By default this is localhost

Reading again the issue, this is not a bug, but a feature request.
From my understanding, absolute URLs in openPage shouldn't be allowed and I don't get how this would be different from using the `host` option :)


I think my [PR](https://github.com/webpack/webpack-dev-server/pull/1600) should be closed

**Comment by runarberg** [comment]
@misterdev You are right. I didn’t know you could use the `host` option that way.

closing
