### ISSUE TITLE
allow us to exclude certain files from the HMR

### ISSUE THREAD

**Issue by aprilmintacpineda** [webpack/webpack-dev-server#1595]
* Operating System: MacOS
* Node Version: 11.3.0
* NPM Version: 6.5.0
* webpack Version: 4.27.1
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

Sorry for not posting my config, I don't think it's related to that.

I'm using [worker-loader](https://github.com/webpack-contrib/worker-loader) which basically allows us to turn certain files into separate web worker with fallback capability for devices that does not support web workers.

But once your server starts up, you'll see this error on the console:

![image](https://user-images.githubusercontent.com/21032419/49852829-2ea87280-fe20-11e8-9e01-aedee773a580.png)

![image](https://user-images.githubusercontent.com/21032419/49853099-09683400-fe21-11e8-9202-42db71c8811e.png)

The error is coming from the web worker because `window` is not available on web workers.

Turning off HMR will fix the error BUT I want to be able to use HMR for other stuff. Maybe allow us to provide an option where we could exclude certain files from HMR?

**Comment by evilebottnawi** [comment]
@aprilmintacpineda problem in `worker-loader`, anyway you need reproducible test repo

**Comment by spencer-brown** [comment]
web worker's can't use `window`; this isn't an issue in `worker-loader`. there's a related issue [here](https://github.com/webpack/webpack/issues/6642).

**Comment by masx200** [comment]
output: {
       path: path.join(__dirname, 'dist'),
       filename: 'bundle.js'
       publicPath: 'http://localhost:3000',
       globalObject: 'this'
},

**Comment by masx200** [comment]
> * 操作系统：MacOS
> * 节点版本：11.3.0
> * NPM版本：6.5.0
> * webpack版本：4.27.1
> * webpack-dev-server版本：3.1.10
> 
> * [x] 这是一个**错误**
> * [x] 这是一个**修改**请求
> 
> ### 码
> 很抱歉没有发布我的配置，我认为这与此无关。
> 
> 我正在使用[worker-loader](https://github.com/webpack-contrib/worker-loader)，它基本上允许我们将某些文件转换为单独的Web worker，并为不支持Web worker的设备提供回退功能。
> 
> 但是，一旦您的服务器启动，您将在控制台上看到此错误：
> 
> ![图片](https://user-images.githubusercontent.com/21032419/49852829-2ea87280-fe20-11e8-9e01-aedee773a580.png)
> 
> ![图片](https://user-images.githubusercontent.com/21032419/49853099-09683400-fe21-11e8-9202-42db71c8811e.png)
> 
> 该错误来自Web工作者，因为Web worker `window`上不可用。
> 
> 关闭HMR将修复错误但我希望能够将HMR用于其他内容。也许允许我们提供一个选项，我们可以从HMR中排除某些文件？


https://github.com/webpack/webpack-dev-server/issues/1595


https://github.com/webpack/webpack/issues/6642

https://github.com/webpack-contrib/worker-loader/issues/174

**Comment by evilebottnawi** [comment]
@masx200 use English language, first warning

**Comment by kumar303** [comment]
Here is a "minimal" example built with [create-react-app](https://facebook.github.io/create-react-app/): 

https://github.com/kumar303/worker-loader-issue174

The readme has instructions. The app gives me: `ReferenceError: window is not defined`

Other folks have had luck with setting `output: { globalObject: 'this' }` in a webpack config but it would be nicer if it just worked.

**Comment by dangreen** [comment]
Hi there 👋

This is my solution to disable HMR for workers:
https://github.com/TrigenSoftware/hmr-filter-webpack-plugin#usage

**Comment by evilebottnawi** [comment]
Fixed in `worker-loader` repo, I don't think we really need to exclude some modules, we should fix compatibility with webpack-dev-server, anyway if you still think we need this, please open an issue in webpack repo, we can't implement this on our side
