### ISSUE TITLE
Error: EPERM: operation not permitted, stat 'D:\System Volume Information'

### ISSUE THREAD

**Issue by lolz42** [webpack/webpack-dev-server#1597]
* Operating System: Windows 10.0.17134
* Node Version: 11.4.0
* NPM Version:  6.5.0
* webpack Version: 4.26.0
* webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  const webpack = require("webpack");
const path = require("path");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const pathsToClean = ["dist", "*.html", "*.css"];

const cleanOptions = {
  root: path.resolve(__dirname),
  exclude: ["shared.js"],
  verbose: true,
  dry: false
};

module.exports = {
  entry: {
    main: "./src/js/index.js"
    // second: './src/js/helper.js',
  },
  output: {
    filename: "js/[name].[hash].js",
    path: path.resolve(__dirname, "dist"),

    publicPath: "dist/"

    // nOTE: UP FOR DEVELOPMENT
    // publicPath: '/'
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-env"]
          }
        }
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              publicPath: "../"
            }
          },
          {
            loader: "css-loader",
            options: {
              // url: false,
              sourceMap: true
            }
          },
          {
            loader: "resolve-url-loader",
            options: {
              debug: true,
              sourceMap: true,
              engine: "rework"
            }
          },
          {
            loader: "sass-loader",
            options: {
              sourceMap: true
            }
          },
          {
            loader: "postcss-loader"
          }
        ]
      },

      {
        test: /\.html$/,
        loader: "html-loader"
      },

      {
        test: /\.(png|jpe?g|gif|svg)$/i,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "images/[name]-[hash].[ext]"
            }
          }
        ]
      }
    ]
  },

  plugins: [
    new CleanWebpackPlugin(pathsToClean, cleanOptions),
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery"
    }),
    new MiniCssExtractPlugin({
      filename: "css/[name].[contenthash].css",
      chunkFilename: "css/[id].[contenthash].css"
    }),

    new webpack.HashedModuleIdsPlugin(),
    new HtmlWebpackPlugin({
      template: "src/index.html",
      filename: "../index.html",
      // nOTE: UP FOR DEVELOPMENT

      // filename: 'index.html',
      minify: {
        collapseWhitespace: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        useShortDoctype: true
      }
    }),

    new MiniCssExtractPlugin({
      filename: "css/[name].[contenthash].css",
      chunkFilename: "css/[id].[contenthash].css"
    }),

    new webpack.HotModuleReplacementPlugin()
  ]
};

```

```js
  const path = require("path");

const merge = require("webpack-merge");
const base = require("./webpack.base.js");

module.exports = merge(base, {
  mode: "development",
  devtool: "inline-source-map",

  devServer: {
    contentBase: "/",
    compress: true,
    port: 8080
    // hot: true
  }
});

```

### Expected Behavior
Seeing website on localhost: 9000 (or other port)
### Actual Behavior
Seeing "Error: EPERM: operation not permitted, stat 'D:\System Volume Information"
### For Bugs; How can we reproduce the behavior?
/
![eperm_error](https://user-images.githubusercontent.com/31371916/49867909-28100000-fe0c-11e8-9d0a-3c261322fac1.png)
![internal_server_error](https://user-images.githubusercontent.com/31371916/49867914-2ba38700-fe0c-11e8-9758-1a718b1107b5.png)

### For Features; What is the motivation and/or use-case for the feature?
/

**Comment by evilebottnawi** [comment]
Looks like you have virus or Trojan in you environtment

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by lolz42** [comment]
`
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const webpack = require("webpack");

module.exports = {
  entry: {
    main: "./src/index.js"
    // second: './src/js/helper.js',
  },
  output: {
    filename: "js/[name].[hash].js",
    path: path.resolve(__dirname, "dist"),
    publicPath: "dist/"
  },

  devServer: {
    contentBase: "/",
    compress: true,
    port: 9000
  },

  module: {
    rules: [
      {
        test: /\.html$/,
        loader: "html-loader"
      }
    ]
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: "src/index.html",
      filename: "../index.html",

      // filename: 'index.html',
      minify: {
        collapseWhitespace: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        useShortDoctype: true
      }
    })
  ]
};

`
![minimal_error_terminal](https://user-images.githubusercontent.com/31371916/49869405-9951b200-fe10-11e8-8b91-cc5bf975a347.png)
![minimal_browser_error](https://user-images.githubusercontent.com/31371916/49869442-aec6dc00-fe10-11e8-9c33-e56519e5faad.png)
![antivirus](https://user-images.githubusercontent.com/31371916/49870070-92c43a00-fe12-11e8-8dcc-8d040d2eaf41.png)

**Comment by evilebottnawi** [comment]
@lolz42 **minimum reproducible test repo**, no need copy/paste config here, because it is unreadable

**Comment by lolz42** [comment]
Is there any fix for this or I should reinstall my OS?

**Comment by evilebottnawi** [comment]
@lolz42 i don't know, you need investigate who touch your system files and fix problem(s), maybe use antivirus or reinstall os, i am not computer doctor, sorry.
