### ISSUE TITLE
Responding to localhost as well as dev IP address

### ISSUE THREAD

**Issue by subblue** [webpack/webpack-dev-server#160]
Is there a way to get the webpack-dev-server to serve content from both `localhost` but also requests from my local dev machine's IP address, or the `name.local` OSX address (for when testing from mobile devices)?

At the moment I have to specifically set the `host` option, which is a little cumbersome when my IP address changes and I don't want to hard code these details in the config script.

Thanks.

**Comment by nkbt** [comment]
If you set server's listen address to 0.0.0.0 it will listen to whatever address is resolved on your machine. Not secure of course, but if you are only accessible from local network, then you should be ok.

**Comment by talmobi** [comment]
Exactly what I was looking for, thanks you all.

**Comment by SpaceK33z** [comment]
Closing because it has been answered a while ago.
