### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by KishanIos007** [webpack/webpack-dev-server#1601]
I am running the old ionic 1 project in winodws and when I installed all the dependencies via yarn it successfully installed but when I run the project using `npm start ` I got this 

```
> ionic-project@0.3.0 start D:\test\kel_ionic-1.0.2
> node ./node_modules/.bin/webpack-dev-server --env.browser --env.remote

D:\test\kel_ionic-1.0.2\node_modules\.bin\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-project@0.3.0 start: `node ./node_modules/.bin/webpack-dev-server --env.browser --env.remote`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-project@0.3.0 start script 'node ./node_modules/.bin/webpack-dev-server --env.browser --env.remote'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/.bin/webpack-dev-server --env.browser --env.remote
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\kel_ionic-1.0.2\npm-debug.log
```

* Operating System:Windows
* Node Version: 6.11.2
* NPM Version:3.10.10
* webpack Version:
* webpack-dev-server Version:

I don't know whats wrong.. can anyone help me out please ?

**Comment by evilebottnawi** [comment]
Something wrong in your environment, maybe something in `bashrc` or related files. We don't have this lines in our code base. Sorry i can't help you here.

**Comment by evilebottnawi** [comment]
@KishanIos007 please use `stackoverflow` or `gitter` for this ,it is bug tracker, i don't know what is wrong with your environment

**Comment by KishanIos007** [comment]
Okay Thanks actually I go through many stackoverflow questions but I am confused whether they are related to my question or not .. Thant's why posted question over here.. bcz its related to this package..

**Comment by evilebottnawi** [comment]
@KishanIos007 we don't have provided code in our code so i can't help, how i can reproduce problem?

**Comment by evilebottnawi** [comment]
@KishanIos007 just imagine yourself in my place, what would you do?

**Comment by KishanIos007** [comment]
yeah u r right my frd .. :) I don't know how u can reproduce .. I have one of client's project that I need to setup in mu system I can give u zip u just extract it and install the dependencies using yarn when I tried to run using `yarn start` .. then I got error

**Comment by KishanIos007** [comment]
I really appreciate your efforts :)

**Comment by evilebottnawi** [comment]
@KishanIos007 please provide zip and instruction how i can reproduce problem

**Comment by evilebottnawi** [comment]
Also i see what you use `windows`, can you try it on `linux`?

**Comment by KishanIos007** [comment]
yeah sure let me try on linux.. https://drive.google.com/file/d/1VDN70GTK8BxrzCM4FY5Dw1BVGspomV-j/view?usp=sharing

**Comment by KishanIos007** [comment]
just extract it and run following command
1) yarn
2) yarn start
