### ISSUE TITLE
"Invalid Host/Origin Header" warning

### ISSUE THREAD

**Issue by ravshansbox** [webpack/webpack-dev-server#1604]
# PLEASE READ

We are working on this problem. It is regression problem after fixing security error. Security issues are always high priority and we would not want to revert it, but it is require some changes in https://github.com/sockjs/sockjs-node/pull/247, we have workaround for this problem https://github.com/webpack/webpack-dev-server/pull/1608, but need some feedback. Feel free to feedback.

Fast workaround (put it in your `devServer` property in config):
```
disableHostCheck: true
```

<br>
<br>
<br>
<br>

We apologize for the situation. Thanks for helping us do `webpack` better. :star: :star: :star: 

---
* Operating System: macos 10.14.2
* Node Version: 11.5.0
* NPM Version: 6.4.1
* webpack Version: 4.28.1
* webpack-dev-server Version: 3.1.11

- [x] This is a **bug**

### Code

```js
  // webpack.config.js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  entry: [
    './src/main.css',
    './src/main.js'
  ],
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'index.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/main.html'
    }),
    new MiniCssExtractPlugin({
      filename: 'index.css'
    })
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader'
        ]
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader'
      }
    ]
  },
  stats: {
    children: false,
    modules: false
  },
  devServer: {
    proxy: {
      '/api': 'http://localhost:3000'
    },
    stats: {
      children: false,
      modules: false
    }
  }
};
```

### Expected Behavior
No warnings

### Actual Behavior
Getting "Invalid Host/Origin Header" warning in browser console

### For Bugs; How can we reproduce the behavior?
install webpack-dev-server@3.1.11 and run (v3.1.10 working as expected).

![image](https://user-images.githubusercontent.com/1499188/50357191-e3f0ce00-0576-11e9-8075-659d3ae3ca85.png)

**Comment by evilebottnawi** [comment]
@ravshansbox it is security fix, looks you origin than you use in config, you can use `disableHostCheck: true` in you case, anyway can you create minimum reproducible test repo?

**Comment by ravshansbox** [comment]
@evilebottnawi yes, sure, here you are: https://github.com/ravshansbox/webpack-dev-server-sample

**Comment by ravshansbox** [comment]
with `disableHostCheck: true` there is no warning.

**Comment by evilebottnawi** [comment]
@ravshansbox thanks, i will look in near future, but if original is not same it is normal have this error

**Comment by pkk82** [comment]
I have the same issue. Problem here is that browser does not send origin header at all. Here my debug of connection object

`
SockJSConnection {
  _session: 
   Session {
     session_id: undefined,
     heartbeat_delay: 25000,
     disconnect_delay: 5000,
     prefix: '/sockjs-node',
     send_buffer: [],
     is_closing: false,
     readyState: 1,
     timeout_cb: [Function],
     to_tref: 
      Timeout {
        _called: false,
        _idleTimeout: 25000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 1740,
        _onTimeout: [Function],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(asyncId)]: 6686,
        [Symbol(triggerAsyncId)]: 6679 },
     connection: [Circular],
     emit_open: null,
     recv: 
      WebSocketReceiver {
        ws: [Object],
        connection: [Object],
        heartbeat_cb: [Function],
        thingy: [Object],
        thingy_end_cb: [Function],
        session: [Circular] } },
  id: 'da07ccdf-4d74-4fed-a48b-6d76247e97af',
  headers: 
   { host: 'localhost:8080',
     'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36',
     'accept-language': 'pl,en;q=0.9,en-US;q=0.8,fr;q=0.7' },
  prefix: '/sockjs-node',
  remoteAddress: '127.0.0.1',
  remotePort: 37412,
  address: { address: '127.0.0.1', family: 'IPv4', port: 8080 },
  url: '/sockjs-node/599/ngnhxajl/websocket',
  pathname: '/sockjs-node/599/ngnhxajl/websocket',
  protocol: 'websocket' }`
`

**Comment by bwigs** [comment]
I am seeing this issue as well with 3.1.11.  Rolling back to 3.1.10 fixes it.

**Comment by rpang77** [comment]
Also, got this issue after upgrading to 3.1.11

**Comment by lambcode** [comment]
I also am getting this error in Firefox 64.0 with version 3.1.11. Reverting to 3.1.10 fixes it.

**Comment by Akiyamka** [comment]
I confirm, the same problem, I roll back too.

**Comment by juank11memphis** [comment]
Same problem here

**Comment by evilebottnawi** [comment]
Please read https://github.com/webpack/webpack-dev-server/issues/1604#issuecomment-449465737

**Comment by evilebottnawi** [comment]
Please try https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.12

**Comment by ravshansbox** [comment]
I can confirm that the issue still exist.

**Comment by davidpelayo** [comment]
I can also confirm that the issue still exists

**Comment by evilebottnawi** [comment]
Please don't spam `Same problem here` or `issue still exists`, better create minimum reproducible test repo, it is allow to fix all edge cases, thanks!

**Comment by 3846masa** [comment]
Sockjs remove `Origin` header.
Ref. https://github.com/sockjs/sockjs-node/pull/247

**Comment by 3846masa** [comment]
In my opinion, it is better to revert #1603 until sockjs/sockjs-node#247 is merged.

**Comment by evilebottnawi** [comment]
@3846masa let's wait some time and revert it, maybe we can implement workaround on our side, need investigate, feel free to do it, thanks

**Comment by 3846masa** [comment]
I tried to add workaround (#1608).
It works and resolve this issue in my environment. Please check it.

**Comment by evilebottnawi** [comment]
@ravshansbox Can you test https://github.com/webpack/webpack-dev-server/pull/1608 PR?

Any who can test PR please leave feedback

**Comment by evilebottnawi** [comment]
@lbogdan `3.1.12` only fix compatibility with `node@6`, please check https://github.com/webpack/webpack-dev-server/pull/1608

**Comment by carlosgeos** [comment]
#1608 is working for me (Node 11.5.0 and SockJS 0.3.19)

**Comment by jjjjose** [comment]
@vue/cli afectado, que pasooooooooooooo

**Comment by evilebottnawi** [comment]
Please tests https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.14

**Comment by alan-agius4** [comment]
Looks like the issue has been solved. Thanks

**Comment by kamilbrk** [comment]
I'm on 3.1.14 and one could argue that my setup is a bit extreme.

I'm using `public: 'mydomain.dev'` and `port: 8070` setting in `devServer` section of the config file. Charles Proxy rewrites all requests from `mydomain.dev`, `subdomain1.mydomain.dev`, `subdomain2.mydomain.dev` etc to `localhost:8070`.

This way I have a multi-tenant environment locally, with one web app, but the behaviour is different depending on the hostname. Main hostname (without subdomains) is a lookup page to choose a tenant. Choosing one redirects to one of the subdomains - same web app bootstraps, but discovers different hostname and loads selected tenant's data accordingly.

With latest updates (3.1.14) this setup does not work anymore. I can either set `mydomain.dev` OR `subdomain1.mydomain.dev` in settings. Setting one breaks sockets for the other.

Yes, doing `disableHostCheck` works, I never noticed that option before. My issue is sorted, I thought that it could lead some people with similar setup here, so this is more of an FYI.

**Comment by evilebottnawi** [comment]
@kamilbrk thanks for feedback, can we setup very minimum reproducible test repo? Maybe we can solve on our side without `disableHostCheck`

**Comment by ravshansbox** [comment]
The issue has been resolved. Great thanks for support. 👍👏

**Comment by evilebottnawi** [comment]
@ravshansbox let's keep it open for feedback some time :+1:

**Comment by carlosgeos** [comment]
@3846masa said:

> When sockjs/sockjs-node#247 is merged, this workaround is not necessary.

So I tested `webpack-dev-server` version 3.1.13 and changed  
`webpack-dev-server/node_modules/sockjs/lib/transport.js` to include `origin` in the `ref` array:

```js
    Session.prototype.decorateConnection = function(req) {
      var address, headers, i, key, len, ref, remoteAddress, remotePort, socket, x;
      if (!(socket = this.recv.connection)) {
        socket = this.recv.response.connection;
      }
      try {
        remoteAddress = socket.remoteAddress;
        remotePort = socket.remotePort;
        address = socket.address();
      } catch (error) {
        x = error;
      }
      if (remoteAddress) {
        this.connection.remoteAddress = remoteAddress;
        this.connection.remotePort = remotePort;
        this.connection.address = address;
      }
      this.connection.url = req.url;
      this.connection.pathname = req.pathname;
      this.connection.protocol = this.recv.protocol;
      headers = {};
      ref = ['referer', 'x-client-ip', 'x-forwarded-for',
             'x-forwarded-host', 'x-forwarded-port', 'x-cluster-client-ip',
             'via', 'x-real-ip', 'x-forwarded-proto', 'x-ssl', 'dnt', 'host',
             'user-agent', 'accept-language', 'origin']; // <-- here !
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        if (req.headers[key]) {
          headers[key] = req.headers[key];
        }
      }
      if (headers) {
        return this.connection.headers = headers;
      }
    };
```

Therefore I guess that if sockjs includes that small change as proposed in sockjs/sockjs-node#247, this issue would also be resolved.

**Comment by show-me-code** [comment]
god , i got the same problem and it confused me, maybe i have to roll back

**Comment by evilebottnawi** [comment]
@show-me-code what you have? Problem will be solved, please check you deps version and if problem exists please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@carlosgeos yes, please tests `3.1.14` version, we implement workaround on our side

**Comment by show-me-code** [comment]
@evilebottnawi  okay, now I may have to roll back to version 3.1.10

**Comment by evilebottnawi** [comment]
@show-me-code what? Issue was fixed in `3.1.14`

**Comment by show-me-code** [comment]
@evilebottnawi OH, I checked my version and find my version is 3.1.11, that's the reason caused problem , thanks a lot

**Comment by evilebottnawi** [comment]
Fixed in `webpack-dev-server@3.1.14`, please your deps before write, anyway feel free to feedback, thanks for helping

**Comment by SharakPL** [comment]
I think this fix caused another problem. I'm using `webpack-dev-server@3.1.14` in 2 new projects and both show the same high severity vulnerability:

> High            Missing Origin Validation
> Package         webpack-dev-server
> Patched in      >=3.1.11
> Dependency of   webpack-dev-server [dev]
> Path            webpack-dev-server
> More info       https://nodesecurity.io/advisories/725

**Comment by cc616** [comment]
webpack-dev-server@3.1.14 is not fixed this issue

**Comment by carlosgeos** [comment]
@SharakPL https://www.npmjs.com/advisories/725/versions says all versions are affected so I think this fix had little to do with it:
![screenshot_20190101_154644](https://user-images.githubusercontent.com/5300711/50573876-9547fd00-0ddc-11e9-8210-849b2e1059d8.png)

My guess is that the npm security team judged that the package still has the vulnerability. What is weird is that in their website, they say the remediation is to update to version 3.1.6 (when the "presumed" fix for the origin checking vulnerability came in 3.1.11):

![screenshot_20190101_155059](https://user-images.githubusercontent.com/5300711/50573975-911cdf00-0dde-11e9-9e6c-39bea5fac637.png)


And in the report of `npm audit` it says the patch happened in 3.1.11 but still reports it even though the package has version 3.1.14:

```
                      === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.1.11                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 3441 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

---

@cc616 You mean 3.1.14 has not fixed the infinite `Invalid Host/Origin header` message ? I think it has

**Comment by pauldraper** [comment]
Yes, it seems the npmjs security team does not know what is going on.

Reported https://npm.community/t/advisory-725-inconsistently-marks-affected-versions/4333

**Comment by khalwat** [comment]
@davidpelayo yes, it is happening for me as well with the latest versions of both `webpack-cli` and `webpack-dev-server`

For now, I've added:

```
disableHostCheck: true,
```

...which skirts around the issue.

**Comment by mrbbm** [comment]
> 
> 
> @davidpelayo yes, it is happening for me as well with the latest versions of both `webpack-cli` and `webpack-dev-server`
> 
> For now, I've added:
> 
> ```
> disableHostCheck: true,
> ```
> 
> ...which skirts around the issue.

Where could I add this `disableHostCheck: true,` ?

**Comment by carlosgeos** [comment]
Hi, I have no problem with this minimal example (with the latest versions of `webpack-cli` and `webpack-dev-server`): https://github.com/carlosgeos/simple-webpack-repo

@mrbbm in the webpack config like this:
```js
module.exports = {
  // ...
  devServer: {
    disableHostCheck: true
  }
  // ...
};

```

**Comment by mrbbm** [comment]
@carlosgeos 
> 
> 
> Hi, I have no problem with this minimal example (with the latest versions of `webpack-cli` and `webpack-dev-server`): https://github.com/carlosgeos/simple-webpack-repo
> 
> @mrbbm in the webpack config like this:
> 
> ```js
> module.exports = {
>   // ...
>   devServer: {
>     disableHostCheck: true
>   }
>   // ...
> };
> ```

Thanks for your reply. I would like to know where could I add in my Angular project, there won't be any file namely webpack.config

**Comment by dstj** [comment]
@mrbbm I just had that very problem after upgrading my project to angular 7.2.0. I fixed it by modifying my `package.json` file as so:

    {
	  ...
      "scripts": {
        "ng": "ng",
        "start": "ng serve --disableHostCheck=true",    <===== HERE
        "build": "ng build --extract-css",
       ...

**Comment by karolyi** [comment]
I got `devServer: { disableHostCheck: true },` in my config and it still fails with `3.1.14`.

**Comment by karolyi** [comment]
Why is this closed if it still doesn't work?

**Comment by neverblued** [comment]
Even with disableHostCheck now after updating I can not get rid of these errors.

**Comment by gander** [comment]
Are there any chances to solve this problem soon?

**Comment by simeyla** [comment]
If you're using [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) try this:

```
// custom-webpack.config.js
module.exports = {

  devServer: {
    disableHostCheck: true
  },

   plugins: []
};
```

**Comment by variable** [comment]
I am running 3.11.0 webpack-dev-server and still having this problem after specifying `disableHostCheck: true`

**Comment by Logopher** [comment]
I see this message consistently when I run my project via Fiddler at localhost.fiddler:4200 and not when I use localhost:4200.

**Comment by testacode** [comment]
This is happening now on webpack 5 and disableHostCheck is not part of the api anymore. Any thoughts?

**Comment by kevinmu17** [comment]
Using webpack-dev-server 4.0.0 `disableHostCheck: true` is not available anymore.
```js
headers: {
        'Access-Control-Allow-Origin': '*'
},
```
This is also not working

**Comment by snitin315** [comment]
@kevinmu17  the`disableHostCheck: true` option was removed in favor of `allowedHosts: "all"`, for more information please refer to our migration guide - https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by kevinmu17** [comment]
> @kevinmu17 the `disableHostCheck: true` option was removed in favor of `allowedHosts: "all"`, for more information please refer to our migration guide - https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

This link should be available on [https://webpack.js.org/configuration/dev-server/](https://webpack.js.org/configuration/dev-server/) This was a live saver, I was banging my head, the information is very well explained and it took me a few hours to migrate. Thank you very much for pointing this out!
