### ISSUE TITLE
Proxy is extermely slow

### ISSUE THREAD

**Issue by grahamb** [webpack/webpack-dev-server#161]
I am using the `proxy` option to proxy API requests while using webpack-dev-server. The proxy is extremely slow, to the point where it's useless. I'm trying to test a type-ahead component, and proxying the API request is resulting in 5+ second response times.

webpack-dev-server: 1.8.2
node: 0.12.2

Request through proxy: 5.08 seconds
![screen shot 2015-04-23 at 14 55 14](https://cloud.githubusercontent.com/assets/146111/7308379/c99218ca-e9c8-11e4-90a0-2e34d77b6ae0.png)

Request direct to API endpoint: 0.03 - 0.06 seconds
![screen shot 2015-04-23 at 14 54 58](https://cloud.githubusercontent.com/assets/146111/7308388/d853dc68-e9c8-11e4-8164-e109d9348673.png)

My `webpack.config.js` is below:

```javascript
const webpack = require('webpack');
const path = require('path');
const config = require('config');
const hostname = config.get('dev_server_hostname');
const port = config.get('dev_server_port');

var pragmas = new webpack.DefinePlugin({
  __DEV__: 'true',
  __CANVAS_API_TOKEN__: JSON.stringify(config.get('api_token'))
});

module.exports = {
  devtool: 'eval',

  entry: [
    'webpack-dev-server/client?http://' + hostname + ':' + port,
    'webpack/hot/only-dev-server',
    './src/js/index.js',
  ],

  output: {
    filename: 'canvas_spaces.js',
    path: './dist',
    publicPath: 'http://' + hostname + ':' + port + '/dist/'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: ['react-hot', 'babel-loader'],
        include: path.join(__dirname, 'src')
      },
      {
        test: /\.scss$/,
        loader: "style!css!sass"
      }
    ]
  },

  plugins: [
    pragmas,
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.ProvidePlugin({
      'es6-promise': 'es6-promise',
      'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    })
  ],

  resolve: {
    extensions: ['', '.js', '.jsx'],
    root: __dirname + '/src/js'
  },

  devServer: {
    hot: true,
    host: hostname,
    port: port,
    historyApiFallback: true,
    proxy: {
      '/api/v1/*': config.get('api_proxy'),
      '/font/*': config.get('api_proxy'),
    }
  }
}

```

**Comment by grahamb** [comment]
Never mind, this looks like it's a DNS-related problem. I'm proxying to a vagrant box; when I change to using its IP address everything is snappy.

**Comment by zorji** [comment]
I have the same issue, thanks for your finding, it helped me too.

**Comment by PaddyMann** [comment]
Same issue experienced using recommend instructions with `create-react-app`. Thanks for sharing solution :)

**Comment by neilning-xc** [comment]
> Never mind, this looks like it's a DNS-related problem. I'm proxying to a vagrant box; when I change to using its IP address everything is snappy.

Thanks for sharing solution. It works
