### ISSUE TITLE
Question regarding webpack-dev-server and Ghost

### ISSUE THREAD

**Issue by matt-d-rat** [webpack/webpack-dev-server#162]
Hi, was wondering if someone would be able to help me. I am fairly new to webpack (less than 24 hours at the time of writing), I've got webpack setup for my project, and now want to leverage the webpack-dev-server for hot module deployment.

The project in question is a theme for [Ghost](https://github.com/tryghost/Ghost), and what to achieve is the reloading of the webpack assets on that Ghost server.

The project is setup like so:
* ```~/Sites/ghost/``` - hosts the installation of the Ghost platform
* ```~/Sites/ghost/content/themes/my-theme/``` - is where my files live for my theme and where webpack runs to bundle my assets etc..

I run the ghost server by: 
```
$: cd ~/Sites/ghost
$: npm start
```
This starts the server at ```http://localhost:2368```, processing the handlebars templates located in the themes folders.

What do I need to add to my webpack.config.js to facilitate using webpack-dev-server with the live-reloading functionality?

Thanks for your help!

**Comment by tmerse** [comment]
Same issue for me. Answers would be appreciated, in the meantime i'll try to work on a solution and try to come up with something usefull by myself.

**Comment by SpaceK33z** [comment]
This is a fairly old question, but there is an [article about this now](https://medium.com/@tranvu/integrating-webpack-into-the-casper-theme-ghost-b68b49a073b4). Let me know if you still have issues.
