### ISSUE TITLE
How can I tell dev server to stop serving old bundles and unload them from memory?

### ISSUE THREAD

**Issue by germn** [webpack/webpack-dev-server#1623]
* Operating System: Windows 10 x64
* Node Version: v10.13.0
* NPM Version: 6.4.1
* webpack Version: 4.27.1
* webpack-dev-server Version: 3.1.10

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Quiestion

1) I start web server, it compiles and serves `bundle.123.css`
2) I change source and server re-compiles and serves `bundle.456.css` now
3) But `bundle.123.css` can still be accessed by url (even though it's outdated)

Can I somehow stop serving (and unload from memory) old bundles on recompiling?

**Comment by evilebottnawi** [comment]
@germn please create reproducible test repo, looks you have invalid configuration

**Comment by germn** [comment]
@evilebottnawi done:

https://github.com/germn/webpack_dev_server_issue_1623

To reproduce, after cloning:

- `npm install`
- `npm run static-dev-server`
- open compiled file url, for example `http://localhost:9001/static/bundle.1e074de3.js`
- change something in `./static_src/app/index.js`
- open new file url and refresh outdated file url: both will work

Same true for css.

I tried to comment out some sections of config to see where problem is, but without luck so far. Thank you for taking the time to look into this.

**Comment by evilebottnawi** [comment]
@germn yep, we don't remove old assets due perf reason, anyway it may cause some memory leaks so i think it is bug, PR welcome

**Comment by skyFi** [comment]
Looking forward to fix this

**Comment by evilebottnawi** [comment]
@skyFi What is it?

**Comment by skyFi** [comment]
@evilebottnawi Web pages memory usage in development mode

**Comment by evilebottnawi** [comment]
@skyFi This problem not related directly to this issue, many of loaders and plugins have memory leak so i don't think it is problem `webpack-dev-server`

/cc @hiroppy i think we should investigate this, just create big file (100mb as example) change multiple time and see on memory usage, can you take care about this, don't have time on this right now

**Comment by daniil-orlov** [comment]
Same issue here. Outdated bundles are still accessible via urls. Investigated _all_ loaders and plugins, those don't cause memory to leak. Pinned issue down to webpack-dev-server (or might be webpack itself, but not probably). Hot rebuilds cause memory footprint to increase by around 50-100Mb each time.
Any news, fixes, or workarounds?

**Comment by evilebottnawi** [comment]
PR welcome, we should fix it

**Comment by alexander-akait** [comment]
Now, you can do it using https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder, it will remove empty files from fs or memory fs
