### ISSUE TITLE
Incomplete Changelog

### ISSUE THREAD

**Issue by LilSebastian5000** [webpack/webpack-dev-server#1624]
* Operating System: Windows
* Node Version: Doesn't matter
* NPM Version: Doesn't matter
* webpack Version: 3.10.0
* webpack-dev-server Version: Looking to upgrade 2.9.1 to a version supported in Webpack 3

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior
A complete list of changes for each version of this project.

### Actual Behavior
The Changelog only goes back as far as version 3.1.6

### For Features; What is the motivation and/or use-case for the feature?
My project still runs on Webpack 3 and I'm not sure when this project started supporting v4. I'm currently at version 2.9.1, and I would like to see a list of breaking changes.

**Comment by evilebottnawi** [comment]
Please read here https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0 . We can't describe all changes in CHANGELOG so we describe only necessary stuff. Better to start update and see documentation. Also no big changes between `2.9` and `3.14`

**Comment by LilSebastian5000** [comment]
> Please read here https://github.com/webpack/webpack-dev-server/releases/tag/v3.0.0 . We can't describe all changes in CHANGELOG so we describe only necessary stuff. Better to start update and see documentation. Also no big changes between `2.9` and `3.14`

Actually, when I upgrade to version 3.0, NPM warns me that Webpack 4 is required. So that seems like a breaking change to me that should be logged?

**Comment by evilebottnawi** [comment]
@LilSebastian5000 you need use `webpack@4` for `webpack-dev-server@3`
