### ISSUE TITLE
Add simple webpack-dev-server API example to readme

### ISSUE THREAD

**Issue by kryptokinght** [webpack/webpack-dev-server#1625]
The page [here](https://webpack.js.org/configuration/dev-server/#devserver) redirects to the [webpack-dev-server API](https://github.com/webpack/webpack-dev-server/tree/master/examples/api/simple) example. On entering the page, a user may expect to see a sample code in the README file.
It can look like this:
![pr](https://user-images.githubusercontent.com/21311242/50938913-86c6a900-14a0-11e9-80b0-5c69f41fe8c0.png)

I request submitting a PR on this issue if this seems reasonable.

**Comment by evilebottnawi** [comment]
@kryptokinght We already have examples here https://webpack.js.org/configuration/dev-server/#devserver, feel free to send a PR to webpack docs repo if you think what something misleading or missing
