### ISSUE TITLE
electron: `events` var is empty object => no handlers for webpackHotUpdate

### ISSUE THREAD

**Issue by rvion** [webpack/webpack-dev-server#1635]
* Operating System: win10
* Node Version: 10.13.0
* NPM Version: 6.4.1
* webpack Version: 4.28.4
* webpack-dev-server Version: 3.1.14

- [x] This is a **bug**

### Code

![image](https://user-images.githubusercontent.com/2150990/51594624-264e5780-1ef5-11e9-9236-f92e7eb2370f.png)

```js
{

    mode: 'development',
    entry: relative('./view'),
    devtool: 'none',
    target: 'electron-renderer',
    ...
    devServer: {
        index: relative('index.html'),
        clientLogLevel: 'info',
        contentBase: path.join(__dirname, 'dist'),
        port: 9001,
        hot: true,
        disableHostCheck: true,
    },
}
```
```sh
webpack-dev-server --hot --config tools/cli-ui/webpack.dev.js
```

### Expected Behavior

perform hot reload

### Actual Behavior

Log that it will do hot reload, but fail silenlty because of improperly initialized internal variable.

```
main.js:1512 [WDS] App updated. Recompiling...
main.js:1656 [WDS] App hot update...
// does nothing
```

**Comment by evilebottnawi** [comment]
@rvion please check you deps, we doesn't contains events or reflect in our code

**Comment by rvion** [comment]
@evilebottnawi it's in lib/events.js.EventEmitter code
the hot module plugin doesn't seem to register correctly its handlers on electron, and internally do not respond to it's own `webpackHotUpdate`.

with almost no configuration beside what is here, `target: 'electron-renderer'` makes hot reload fail to send fetch request for updated blob

**Comment by evilebottnawi** [comment]
@rvion webpack doesn't use `event` too in code, please provide minimum reproducible test repo

**Comment by rvion** [comment]
@evilebottnawi 
1. thanks for your quick responses
2. you can find a minimal repro here: https://github.com/rvion/electron-webpack-failure (all files are as minimal as it can be)
3. webpack-dev-server hot-reload related code seems to use events, as this shown in below picture
4. to see how things go wrong, adding a breakpoint here, and going steps by step is useful
![image](https://user-images.githubusercontent.com/2150990/51601727-70d7d000-1f05-11e9-82ab-a8541f7c2296.png)

can I do anything else to help ?

**Comment by rvion** [comment]
@evilebottnawi I simplified the minimal repo a bit more

here are all files content to ease reading this thread:

### view.js

```js
console.log("CHANGE-ME2");

if (module.hot) {
  module.hot.accept(() => {
    console.log("==== Reload ====");
  });
}
```
### main.js

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
let mainWindow = null;
function createWindow() {
    mainWindow = new electron_1.BrowserWindow({ width: 1200, height: 900 });
    mainWindow.webContents.openDevTools();
    mainWindow.loadURL("http://localhost:9001/index.html");
    mainWindow.webContents.openDevTools();
    mainWindow.on("closed", () => (mainWindow = null));
}
electron_1.app.on("ready", createWindow);
electron_1.app.on("window-all-closed", () => {
    if (process.platform !== "darwin")
        electron_1.app.quit();
});
electron_1.app.on("activate", () => {
    if (mainWindow === null)
        createWindow();
});
```
### webpack.dev.js

```
const { join } = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  mode: "development",
  entry: join(__dirname, "view.js"),
  devtool: "source-map",
  target: "electron-renderer",
  externals: [require("webpack-node-externals")()],
  output: { path: join(__dirname, "dist"), publicPath: "" },
  plugins: [
    new HtmlWebpackPlugin({ template: join(__dirname, "./index.html") })
  ],
  devServer: {
    index: join(__dirname, "index.html"),
    clientLogLevel: "info",
    contentBase: join(__dirname, "dist"),
    port: 9001,
    hot: true
  }
};
```

### package.json

```json
{
  "name": "electron-webpack-failure",
  "version": "1.0.0",
  "description": "",
  "author": "Rémi Vion",
  "main": "main.js",
  "scripts": {
    "dev-webpack": "webpack-dev-server --hot --config webpack.dev.js",
    "dev-electron": "electron ."
  },
  "devDependencies": {
    "electron": "^4.0.2",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {}
}
```

### index.html

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

### readme.md


```md

## ELECTRON-WEBPACK-FAILURE

1. run:

```sh
# setup:
npm install

# then in 2 terminals, run:
npm run dev-webpack
npm run dev-electron
```

2. in `view.js`, change `CHANGE-ME` to any string

3. BUG:

   - in electron browser window: console shows:

   ```
    [WDS] App updated. Recompiling...
    [WDS] App hot update...
   ```

   - nothing is updated, no error
```

**Comment by evilebottnawi** [comment]
@rvion Can reproduce, no `events` package in my code

**Comment by rvion** [comment]
@evilebottnawi I don't believe you: the webpack-hot-middleware code is here and use `.emit()` from the events module from either the `events` node package or the https://nodejs.org/api/events.html native node module: https://github.com/webpack-contrib/webpack-hot-middleware/search?q=emit&unscoped_q=emit

there is no two-way about it.

Did you even clone my project and run the two commands shown in the readme ? 

If you clone my repository, run both electron and webpack, then update the string in the view.js file, you'll notice the bug.

**Comment by evilebottnawi** [comment]
@rvion we don't use `webpack-hot-middleware`, please create issue in `webpack-hot-middleware` repo

**Comment by rvion** [comment]
@evilebottnawi also, technically, you use webpack-hot-middleware in some way, since you're instantiating it in webpack-dev-server when `--hot` is present.

eg1. https://github.com/webpack/webpack-dev-server/search?q=HotModuleReplacementPlugin&unscoped_q=HotModuleReplacementPlugin

eg2. https://github.com/webpack/webpack-dev-server/search?q=hot&unscoped_q=hot

I understand that I'm a bit stubborn here, but chances are that the bug is related to how this plugin is instantiated when targeting electron. 

anyway, if you think this issue really has nothing to do with `webpack-dev-server`, then **thanks** for your help

**Comment by evilebottnawi** [comment]
@rvion i think better wait answer in `webpack-hot-middleware`, i am not familiar with `webpack-hot-middleware` code and how they implement `hot`

**Comment by rvion** [comment]
thanks !

**Comment by rvion** [comment]
@evilebottnawi 

found the problem. the culprit was a mix of 
 - `webpack-node-external` 
 - target: `electron-renderer`
 - leading `events` to be required the wrong way

replacing webpack-node-external by some explicit filter list fixed it.

-------

As a final note, one can find below the list of required modules induced by webpack-dev-server --hot.
(`events` module/package is always loaded with 'hot')

```js
const { join } = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const f = (...path) => join(__dirname, ...path);

module.exports = {
  mode: "development",
  entry: f("view.js"),
  devtool: "source-map",
  target: "electron-renderer",
  externals: function(context, request, callback) {
    console.log(context.replace(__dirname, "- .").replace(/\\/g, "/"), request);
    callback();
  },
  output: { path: f("dist"), publicPath: "" },
  plugins: [new HtmlWebpackPlugin({ template: f("./index.html") })],
  devServer: {
    index: f("index.html"),
    clientLogLevel: "info",
    contentBase: f("dist"),
    port: 9001,
    hot: true
  }
};
```

The list of modules required are as follow (`- <context> <import>`)
- ./node_modules/webpack-dev-server/client url
- ./node_modules/webpack-dev-server/client strip-ansi
- ./node_modules/webpack-dev-server/client loglevel
- ./node_modules/webpack-dev-server/client ./socket
- ./node_modules/webpack-dev-server/client ./overlay
- ./node_modules/webpack-dev-server/client webpack/hot/emitter <===== 🔔 
- ./node_modules/webpack/hot ./log
- ./node_modules/webpack/hot ./log-apply-result
- ./node_modules/webpack/hot ./emitter
- ./node_modules/webpack/hot ./log
- ./node_modules/webpack/hot ./log
- ./node_modules/webpack/hot events<===== 🔔 
- ./node_modules/webpack-dev-server/client sockjs-client/dist/sockjs
- ./node_modules/webpack-dev-server/client ansi-html
- ./node_modules/webpack-dev-server/client html-entities
- ./node_modules/strip-ansi ansi-regex
- ./node_modules/html-entities ./lib/xml-entities.js
- ./node_modules/html-entities ./lib/html4-entities.js
- ./node_modules/html-entities ./lib/html5-entities.js
