### ISSUE TITLE
Webpack dev-server refused connexion on localhost 

### ISSUE THREAD

**Issue by dlepaux** [webpack/webpack-dev-server#1636]
* Operating System: OSX 10.14
* Node Version: 10.10.0
* NPM Version: 6.6.0
* webpack Version: ^4.27.1
* webpack-dev-server Version: ^3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
import webpack           from 'webpack';
import merge             from 'webpack-merge';
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import { resolve }       from 'path';

import common            from './webpack.common.babel.js';
import router            from './router.js';


process.on('uncaughtException', function (err) {
  console.log(JSON.stringify(err));
  console.trace(err);
  console.error(err.stack);
  console.log("Node NOT Exiting...");
});

export default merge(common, {
  mode: 'development',
  devtool: 'source-map',
  devServer: {
    before: (app) => {
      app.use(router);
    },
    disableHostCheck: true,
    logLevel: 'debug',
    watchContentBase: true,
    https: true,
    hot: true,
    inline: true,
    historyApiFallback: true,
    contentBase: './public',
    port: 3000,
    overlay: {
      errors: true,
      warnings: true
    },
  },
  module: {
    rules: [{
      test: /(\.css|\.scss)$/,
      use: [{
        loader: 'css-hot-loader'
      }].concat(ExtractTextPlugin.extract({
        use: [{
          loader: 'css-loader',
          options: { sourceMap: true }
        }, {
          loader: 'sass-loader',
          options: { sourceMap: true }
        }],
        // use style-loader in development
        fallback: 'style-loader'
      }))
    }]
  },
  plugins: [
    new ExtractTextPlugin({
      filename: (getPath) => getPath('css/app.css'),
      allChunks: true
    }),
    new webpack.HotModuleReplacementPlugin()
  ]
});

```

### Expected Behavior
`webpack-dev-server` should not refuse connexion from itself. Like in my production env.

### Actual Behavior
I use `webpack-dev-server` to work locally but instead of production environment (simple express instance), the m.request() of `mithril` is refused and trigger an Unhandled error (but not in production !)

Here the error handled by `process.on('uncaughtException')` and detailed with console.trace.
```
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443}
[object Object]
    at process.<anonymous> (/Users/dlepaux/code/eeloo/webpack.dev.babel.js:12:11)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process._fatalException (internal/bootstrap/node.js:485:27)
Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

### For Bugs; How can we reproduce the behavior?
Here an exemple with webpack, the error is trigged if you follow instruction on readme.md
https://github.com/dlepaux/webpack-dev-server-issue-exemple

Thank you in advance

**Comment by evilebottnawi** [comment]
Don't use `extract-text-webpack-plugin`, it is doesn't work with `webpack@4`, switch on `mini-css-extract-plugin`, also you don't need `extract-text-webpack-plugin` in development mode and don't use `webpack-dev-server` in production. 

Something wrong with `mithril`, `axios` works as expected:
```
app.get('/helloworld', async (req, res, next) => {
        const axios = require('axios');
        const data = await axios.get('https://localhost:3000/api/v1/efforts').catch((e) => {
          console.log('dawm', e);
        });
        res.send('OK');
});
```

Problem not on our side.

**Comment by evilebottnawi** [comment]
Maybe you need more configuration for `mithril`, when you do `https` request, i am not familiar with `mithril` so documentation can help with this.

**Comment by dlepaux** [comment]
Thank you @evilebottnawi for your quick answer I'll check it out.
Have a nice day

**Comment by evilebottnawi** [comment]
Hm, i get original error:
```
Error: write EPROTO 140317656524608:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252
```

Something wrong with https

**Comment by evilebottnawi** [comment]
Ref: https://github.com/openssl/openssl/issues/6289 maybe help

**Comment by evilebottnawi** [comment]
With `NODE_TLS_REJECT_UNAUTHORIZED=0` and `axios`/`fetch` all works fine. But with `mithril` not, better ask in their repo how do request with self signed cert.

**Comment by dlepaux** [comment]
You are amazing @evilebottnawi thank you very much
