### ISSUE TITLE
Automatically add hostname, specified in --public parameter, to self-signed certificate

### ISSUE THREAD

**Issue by mrigne** [webpack/webpack-dev-server#1637]
For ex. if webpack-dev-server started with --public=mylocalhostname - add DNS name 'mylocalhostname' to resulting generated self-signed certificate

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
