### ISSUE TITLE
Question: how to make hot reload work also with [express server] ?

### ISSUE THREAD

**Issue by DemonCloud** [webpack/webpack-dev-server#1639]
Example ``webpack.config.js``

```javascript
const mockApp = require('./someMockData');

module.exports = {
    ...

   devServer: {

    before(app) {
      // setup mock server App
      mockApp(app);
    },

  },
  ...
}
```

when I was changed ``someMockData``, I hope webpack-dev-server live reload express server.

In this way, the latest interface to the Mock service will take effect immediately, without restarting the Webpack dev server service.

Is there a good solution or documentation? please~

**Comment by evilebottnawi** [comment]
@DemonCloud 
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Also it is bug tracker please use `stackoverflow` or `gitter` for questions.

You should use `loader` or plugin for this purpose. https://webpack.js.org/api/loaders/#this-adddependency
