### ISSUE TITLE
How to access the dev server from remote

### ISSUE THREAD

**Issue by MichaelCereda** [webpack/webpack-dev-server#164]
I'm trying to access the hot dev server from remote (to check my app from other devices) but without any luck.
Any advice?
Thanks

**Comment by nkbt** [comment]
1. Run it with the IP-address accessible from remote (like 192.168.1.10). If you are brave or local-only, use 0.0.0.0 to accept connections on any IP.
2. Check if you port is not blocked by firewall.

**Comment by MichaelCereda** [comment]
Thank you, i discovered that the problem was related to a misconfiguration in the package react-starter.
Everything runs smoothly now

**Comment by SpaceK33z** [comment]
Closing because it no longer seems to be an issue.
