### ISSUE TITLE
Webpack-dev-server doesn't work on Node 10.15.1

### ISSUE THREAD

**Issue by daryn-k** [webpack/webpack-dev-server#1648]
Webpack-dev-server doesn't make a bundle on Node 10.15.1 which realised a couple days ago. But everything works well on Node 8.11.3.

It's stucking on this:

```
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from http://localhost:8080/assets/
ℹ ｢wds｣: Content not from webpack is served from /Users/blah/blag/blag
```

* Operating System: MacOS Mojave / Windows 8.1
* Node Version: 10.15.1
* NPM Version: 6.4.1
* webpack Version: 4.16.0
* webpack-dev-server Version: 3.1.14

**Comment by evilebottnawi** [comment]
@daryn-k yep, please create reproducible test repo

**Comment by daryn-k** [comment]
Well, I figured out the problem is in another place, but I don't know where exactly. Yes, everything works good in my minimal config on the newest Node. Sorry.

**Comment by daryn-k** [comment]
I found where is the problem. Node.js v.10 made mandatory to pass callback on fs.writeFile(). One of my plugin used fs.writeFile().
