### ISSUE TITLE
mkcert ruined my webpack-dev-server / localhost:8080

### ISSUE THREAD

**Issue by tr1s** [webpack/webpack-dev-server#1651]
I had to run [these commands](https://shopify.github.io/slate/docs/create-a-self-signed-ssl-certificate) in order to get [slate](https://shopify.github.io/slate/docs/create-a-self-signed-ssl-certificate) to work, it never worked... Then I found some hacks in the github issues of slate, it finally worked by creating some keys in my project. So now my slate project works, no need to show you pictures of that cause it's fine. But,

Now when I run webpack-dev-server on my own personal projects using my [boilerplate](https://github.com/tr1s/tris-webpack-boilerplate), localhost:8080 doesn't work anymore, none of them do. I tried doing mkcert install and mkcert localhost and it created my keys, but still nothing.. I get this below.

<img width="1680" alt="cleanshot 2019-02-05 at 11 51 43 2x" src="https://user-images.githubusercontent.com/19172250/52289637-6cb3a580-293c-11e9-8048-a67e24b68d49.png">

How do I get things back to normal? I don't want all these extra steps just to run my personal projects. All I had to do before was type "npm start" and everything was ready to go. Ever since me setting up _one_ slate project everything else is ruined so far.

Any ideas? How can I fix this? 

- Operating System: macOS 10.14.3
- Node Version: 10.5.0
- NPM Version: 6.5.0
- webpack Version: 4.27.1
- webpack-dev-server Version: 3.1.10

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.common.js
const path = require('path');

const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const ScriptExtHtmlWebpackPlugin = require("script-ext-html-webpack-plugin");

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  module: {
    rules: [{
        test: /\.txt$/,
        use: 'raw-loader'
      },
      {
        test: /\.html$/,
        use: [{
          loader: 'html-loader',
          options: {
            minimize: true
          }
        }]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        use: [{
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'images/',
            publicPath: 'images/'
          },
        }]
      },
      {
        test: /\.(woff|woff2|ttf|otf)$/,
        use: [{
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'fonts/',
            publicPath: 'fonts/'
          },
        }]
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true
            }
          }
        ]
      },
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new HtmlWebpackPlugin({
      title: 'home',
      filename: 'index.html',
      template: './src/index.html',
      inject: 'head'
    }),
    new HtmlWebpackPlugin({
      title: '404',
      filename: '404.html',
      template: './src/404.html',
      inject: 'head'
    }),
    new ScriptExtHtmlWebpackPlugin({
      defaultAttribute: 'defer'
    }),
    new MiniCssExtractPlugin({
      filename: 'webpack-bundle.css',
      chunkFilename: '[id].css'
    }),
  ],
  output: {
    filename: 'webpack-bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  externals: {
    $: 'jquery',
    jquery: 'jQuery',
    'window.$': 'jquery',
  }
};
```

```js
// webpack.dev.js
const merge = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist/'
  }
});
```

### Expected Behavior
Project works

### Actual Behavior
Project doesn't work, localhost:8080 sends invalid responce

### For Bugs; How can we reproduce the behavior?
Make a slate project, run their commands for mkcert, then trying to run webpack-dev-server again like usual on other projects.

**Comment by evilebottnawi** [comment]
Please create reproducible test rrepo

**Comment by evilebottnawi** [comment]
`mkcert` is not related to `webpack-dev-server`, we don't use this tool, you need to read documentation how it is works, we provide option like `ca`, `pfx`, `key` and `cert` for `https`. 

Problem looks like you generated invalid certificate, maybe missing some arguments or somethings else, anyway you get some problems with any servers (`nginx`, `apache` and etc). So we can't help you here, sorry.

**Comment by philipbordallo** [comment]
@tr1s make sure your config for `devServer` is correct and you are pointing to the certs you made with `mkcert`.

For example,
```js
// webpack.dev.js
const merge = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist/',
    https: {
      key: fs.readFileSync('./$DOMAIN-key.pem'),
      cert: fs.readFileSync('./$DOMAIN.pem'),
      ca: fs.readFileSync('/Users/$USERNAME/Library/Application Support/mkcert/rootCA.pem'),
    }
  }
});
```

See [the documentation](https://webpack.js.org/configuration/dev-server/#devserverhttps) for more.

**Comment by tr1s** [comment]
@philipbordallo thank you! I missed that. I'll remember this when I try it again. I ended up having to reset my laptop to the hour before I installed mkcert 😒

I don't really see the advantages of going through all this trouble though. I only needed it for Slate, but I thought the point of https was for live websites, not local development.

Guess I need to look into it more.

**Comment by skywinston** [comment]
The solution to this problem can be found here:
https://github.com/Shopify/slate/issues/726#issuecomment-431372434
