### ISSUE TITLE
dev server index (was: redirect loop)

### ISSUE THREAD

**Issue by tcurdt** [webpack/webpack-dev-server#167]
I am trying to setup a `webpack-dev-server` with multiple entry points.

  https://github.com/tcurdt/base-web/blob/master/webpack/config.js#L36

    git clone https://github.com/tcurdt/base-web && npm install
    gulp watch

~~While the non-dev server build works I am having a hard time figuring out how to get it running with the dev server.~~

~~I presume at least the 'webpack-dev-server/client?http://localhost:8888' must be different for the entry points - but I am struggling with docs on how to set it up correctly. It does not complain when compiling the chunks - but when I go to `localhost:8888/build/client.js` all I get is a redirect loop.~~

**Comment by tcurdt** [comment]
I got much further. So the files are available as

  - http://localhost:8888/build/index
  - http://localhost:8888/build/details/index

they are linked from http://localhost:8888/webpack-dev-server

Questions left for now:

  - Why "/build/index" and not "/build/index.html"?
  - Why doesn't "/build/" show "/build/index.html"

**Comment by tcurdt** [comment]
Hm. Also seems to use boilerplate html - not mine.

**Comment by tcurdt** [comment]
Should one always wrap the webpack-dev-server with it's own proxy?
The only way I could think of getting around this.

**Comment by sokra** [comment]
Set contentBase to a fs path to use your own html file.
