### ISSUE TITLE
proxy.bypass return false does not work

### ISSUE THREAD

**Issue by jsmith-sapient** [webpack/webpack-dev-server#1677]
- Operating System: MacOS High Sierra
- Node Version: 11.0.0
- NPM Version: 6.4.1
- webpack Version: 4.29.5
- webpack-dev-server Version: 3.2.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

does *not* work:
```js
// webpack.config.js

module.exports = {
  devServer: {
    proxy: {
      '**': {
        bypass(req) {
          if (!req.headers.accept.includes('application/json'))
            return false; // ← does nothing
        },
        target: `http://localhost:${yargs.proxyPort}`,
      },
    },
  },
  entry: './app',
}
```

*does* work:
```js
// webpack.config.js

module.exports = {
  devServer: {
    proxy: {
      '**': {
        bypass(req) {
          if (!req.headers.accept.includes('application/json'))
            return req.url;
        },
        target: `http://localhost:${yargs.proxyPort}`,
      },
    },
  },
  entry: './app',
}
```

### Expected Behaviour

Based on the [vague explanation in the docs](https://webpack.js.org/configuration/dev-server/#devserverproxy)

>It must return either `false` or a path that will be served instead of continuing to proxy the request.

I expect `return false` to skip the proxy

### Actual Behaviour

`return false` does nothing.

### For Bugs; How can we reproduce the behaviour?

Minimal example: https://github.com/jsmith-sapient/local-api-mocker

```sh
npm run start:dev
```

**Comment by evilebottnawi** [comment]
Can you try return `null` or something else? Looks like regression in `http-proxy`/`http-proxy-middleware`

**Comment by evilebottnawi** [comment]
Anyway PR welcome

**Comment by jsmith-sapient** [comment]
@evilebottnawi I tried `null`: No difference to `false` (it does nothing).

I'll try to find some time this weekend to take a look. I might be posting as @jshado1 (my personal account, not a catfish).

**Comment by evilebottnawi** [comment]
@jsmith-sapient i will look on this in near future, anyway we glad any help

**Comment by evilebottnawi** [comment]
@jsmith-sapient reproducible test repo works fine, i am use `/test` and it is return `json`. What expected?

**Comment by jsmith-sapient** [comment]
@evilebottnawi see the [commit history](https://github.com/jsmith-sapient/local-api-mocker/commits/webpack-devsrv):

>
>[…]
>
>[using webpack-dev-server with `return req.url` (working)](https://github.com/jsmith-sapient/local-api-mocker/commit/eebebb0d5e70ce21bcf01688e6dc2e1f3e3baeca)
>
>[using webpack-dev-server (`return false` not working)](https://github.com/jsmith-sapient/local-api-mocker/commit/a6cb6dcd06b40ca84cf4285cfb6eaf99158b822c) ← checkout this commit

**Comment by evilebottnawi** [comment]
@jsmith-sapient thanks, it si very strange because we have tests on this case and tests passed :confused:

**Comment by jsmith-sapient** [comment]
@evilebottnawi could you link me to the test case? that might help.

**Comment by jsmith-sapient** [comment]
@evilebottnawi I think you're talking about [this case](https://github.com/webpack/webpack-dev-server/blob/master/test/Proxy.test.js#L116-L118):

```js
it('should pass through a proxy when a bypass function returns null', (done) => {
  req.get('/foo.js').expect(200, /Hey/, done);
});
```

If so, the function does not return null:

```js
  '/foo': {
    bypass(req) {
      if (/\.html$/.test(req.path)) {
        return '/index.html';
      }
    },
  },
```

**Comment by evilebottnawi** [comment]
@jsmith-sapient we return nothing in this test, i think `null`, `undefined`, `false` is same in this context :confused:

**Comment by jsmith-sapient** [comment]
I don't think so. I would expect no return to mean "go ahead, proxy, do your thing". How else would that be signalled?

**Comment by evilebottnawi** [comment]
@jsmith-sapient in previous versions all works fine, right?

**Comment by jshado1** [comment]
I haven't used `bypass` with previous versions.

**Comment by jsmith-sapient** [comment]
I'm having trouble finding where this is in the source code. Could you point me in the right direction?
