### ISSUE TITLE
https config is broken

### ISSUE THREAD

**Issue by martinoppitz** [webpack/webpack-dev-server#1687]
webpack.conf.json
```js
devServer: {
      ...
      https: {
        key: `-----BEGIN PRIVATE KEY-----
```

I believe the fs.readSync is now inside webpack-dev-server ... we configured the key inline.

```bash
\webpack-dev-server.js:169
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '-----BEGIN CERTIFICATE-----
```

**Comment by martinoppitz** [comment]
is that the new feature?

```js
https: {
  key: './https/server.key',
  cert: './https/server.crt',
  ca: './https/ca.pem'
}
```

**Comment by langri-sha** [comment]
There's some documentation already up:

https://webpack.js.org/configuration/dev-server/#devserver

**Comment by evilebottnawi** [comment]
@martinoppitz already fixed in master, we accept `key`, `cert` and `ca` as `path`, `string` and `Buffer`, it was regression
