### ISSUE TITLE
Problems with idb-connector

### ISSUE THREAD

**Issue by arthureggert** [webpack/webpack-dev-server#1689]
Since the upgrade to internal-ip@4.0.0, that was done [here](https://github.com/webpack/webpack-dev-server/pull/1668), some people have issues on running npm-ci [here](
https://github.com/webpack/webpack-dev-server/issues/1681), checked that the origin of the problem is the default-gateway package, that is used by the internal-ip, but the 2 projects already resolve this problem and revealed a new version [here](https://github.com/silverwind/default-gateway/issues/10) and [here](https://github.com/sindresorhus/internal-ip/pull/25). 

Said that I believe we can upgrade internal-ip to version 4.2.0 to resolve this issue.

**Comment by evilebottnawi** [comment]
@arthureggert let's do it

**Comment by arthureggert** [comment]
@evilebottnawi I open a PR to fix this.
If anything is needed please let me know.
