### ISSUE TITLE
Trying to enable hot loading through the config file doesn't work

### ISSUE THREAD

**Issue by gsklee** [webpack/webpack-dev-server#169]
I have this in my `webpack.config.js`:

```javascript
devServer: {
  ...
  inline: true,
  hot: true
}
```

It doesn't enable the hot loading feature when I do `$ webpack-dev-server --config .webpack.config.js`. Instead I have to do `$ webpack-dev-server --config .webpack.config.js --inline --hot`. But from what I read on the documentation I was expecting the `devServer` config to work.

**Comment by bestic** [comment]
same here

**Comment by gsklee** [comment]
@sokra any idea what's causing the issue? I may be able to land a fix if given the right pointer.

**Comment by sokra** [comment]
http://webpack.github.io/docs/webpack-dev-server.html#webpack-dev-server-cli

`--hot --inline` is not equal to (only) `hot: true`

**Comment by gsklee** [comment]
@sokra I thought it exists just that the documentation missed it. Does that means the proper way to fix this (instead of just leaving it as is) is to add an `inline` option to `devServer`?

**Comment by gsklee** [comment]
@sokra Looked again closer and am now really puzzled. The documentation clearly says:

```
webpack-dev-server CLI

...

--inline: embed the webpack-dev-server runtime into the bundle;

...

The additional options above can be set in devServer option in webpack.config.js.
```

That makes your comment about `inline: true` doesn't exist not really making any sense. Please consider reopen this issue.

**Comment by troutowicz** [comment]
@gsklee Looks like the docs are wrong. If you look in the [code](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L106), it only checks for the CLI option. You could submit a PR, or update the docs. :)
