### ISSUE TITLE
Add option to make watchContentBase recursive or expose chokidar options

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack-dev-server#1694]
- Operating System: OSX
- Node Version: v11.7.0
- NPM Version: 6.5.0
- webpack Version: 4.29.5
- webpack-dev-server Version: 3.2.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code 
I have a public folder like this
```
public/
├── assets
│   ├── image.png
│   ├── video.mp4
├── css
│   └── style.css
└── index.html
```

And my config like this

```js
devServer: {
  publicPath: '/',
  contentBase: './public/',
  watchContentBase: true,
  // don't watch node_modules
  watchOptions: {
    ignored: /node_modules/,
  },
},
```

### Actual Behavior
Right now the `watchContentBase` acts only on the root folder, because of this chokidar options:

https://github.com/webpack/webpack-dev-server/blob/cb10f83ac811aedb783b8b8fa644c63af99fcdf8/lib/Server.js#L943

### Expected Behavior
I would like for `watchContentBase: true,` to trigger a reload whenever a file in my public folder changes.

It was also discussed in #1227, but I don't this is a good solution to start another chokidar instance. Plus this is a really common use-case.

It would be really useful to have an option `recursive: true` in the `watchOptions: {}`, or more simply a `depth: undefined` option which goes to override the default chokidar options.

I am willing to make a PR if we decide what direction to take.

**Comment by evilebottnawi** [comment]
Yep, we should avoid this limitation, feel free to send a PR with remove this `depth`. Question for `depth: 0` in `watchpack` not related to `contentBase` option

**Comment by marcofugaro** [comment]
Done!

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/1697
