### ISSUE TITLE
Generated SSL Certificate is not valid (has no CA), and cannot make it as valid and accepted

### ISSUE THREAD

**Issue by marisveide** [webpack/webpack-dev-server#1695]
- Operating System: MacOS Mojave 10.14.3
- Node Version: v11.9.0
- NPM Version: 6.5.0
- webpack Version: 4.0.0-rc.7
- webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpacker.yml
  dev_server:
    https: true
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'
```

### Expected Behavior
When starting the `webpack-dev-server` it should generate the SSL certificate which is valid, with the CA, so that when it gets accepted, it doesn't expire each time.
Or, at least allow passing my own certificate from the file, so that I can generate it on the required domain name, and make it valid like 100 years or so.

### Actual Behavior
When starting the `webpack-dev-server` it generates the SSL certificate which is invalid because it has no CA included. When accepting it manually, the webpack re-generates that certificate several times per day, and each time the certificate needs to be re-accepted in the browser.
That is quite inconvenient.
Also, when trying to pass the self-generated certificates, those parameters get ignored:
`./bin/webpack-dev-server -- --open --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key`

## Reproduce the invalid CA:
1. Start the `webpack-dev-server` so that it generates the SSL certificate.
2. Open the browser and view the certificate.
It says: "localhost" certificate is not trusted.
<img width="1336" alt="1 - certificate not trusted" src="https://user-images.githubusercontent.com/17713131/53519494-17eaf100-3adc-11e9-9be4-c44fe3c6007f.png">

If I look into the code, file `webpack-dev-server/lib/utils/createCertificate.js`, I see the line:
```
extensions: [
      {
        name: 'basicConstraints',
        cA: true,
      },
```
(notice the lowercase "c" on the "cA".

I can see it gets better when I do the following:
1. I change this "cA" to "CA" in the `createCertificate.js` file.
2. Delete the generated pem file:
`rm node_modules/webpack-dev-server/ssl/server.pem`
3. Start the `webpack-dev-server`

Then I see the warning that the certificate is not verified:
<img width="1282" alt="2 - ca not verified" src="https://user-images.githubusercontent.com/17713131/53519683-787a2e00-3adc-11e9-866a-7aa38f20de7f.png">

This is one part of the solution.

Still, the issue persists that when I restart the `webpack-dev-server`, the certificate is expiring often, and I need to re-approve it.

## Reproduce the ignoring of certificate parameters
1. Generate my own SSL Private Key and Certificate.
2. Start the Webpack Dev Server with parameters which should read that file:
`./bin/webpack-dev-server -- --open --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key`
3. See that it still generates its own certificate and ignores the parameters.

----

I have looked into several online resources for this, but they seem to be outdated, as I can't make any of the solutions work to just have the SSL with the valid certificate which allows to develop normally.

**Comment by evilebottnawi** [comment]
It is expected, you should accept self-signer certificate, anyway we can skip regeneration certificates if they already exists to avoid this problem, feel free to send a PR, it is feature

**Comment by marisveide** [comment]
Having to accept the self-signed certificate is only one part of an issue.
The main issue is that I cannot add my own certificate which I can make valid for a longer period. Or am I missing something - how to use my own certificate?

That would be really awesome if I could...
Thank you!

**Comment by evilebottnawi** [comment]
> how to use my own certificate

See second example https://webpack.js.org/configuration/dev-server/#devserverhttps

What is real problem? 
Each run require accept certificate?

**Comment by marisveide** [comment]
That's right - this is an issue: running the command line like this (as explained in the link you sent):
`webpack-dev-server --https --key /path/to/server.key --cert /path/to/server.crt --cacert /path/to/ca.pem`

It just ignores those parameters, and still generates its own certificate. It doesn't use my passed certificate.
The concrete command I am running, is this:
`./bin/webpack-dev-server --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key`

I have the certificate issued there on the different domain - not the `localhost`.
And my generated certificate is set to be valid for 10 years.
Here's how my certificate looks like in KeyChain:
<img width="600" alt="screenshot 2019-03-04 at 14 56 17" src="https://user-images.githubusercontent.com/17713131/53734911-057f0780-3e8e-11e9-9b36-f464c1312b44.png">

But when I run the command to use that certificate with WebPacker
`./bin/webpack-dev-server --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key`
, I still get the localhost certificate, which is valid not 10 years, but 25 days:
<img width="494" alt="screenshot 2019-03-04 at 14 58 00" src="https://user-images.githubusercontent.com/17713131/53734962-25aec680-3e8e-11e9-80fc-0f81586ca785.png">

Can you tell that you have tried to replicate this, but for you, it accepts your custom certificate?

**Comment by evilebottnawi** [comment]
What version `webpack-dev-server` you use? We fix problem with CLA in previously patch release

**Comment by evilebottnawi** [comment]
Also please create reproducible test repo, something wrong in your config/env

**Comment by marisveide** [comment]
I am using `webpack-dev-server` version `Version: webpack 4.29.5` (upgraded to latest).

Here is the reproducible steps:
```
# I delete the current Webpack generated SSL certificate:
maris$ rm node_modules/webpack-dev-server/ssl/*
# I start the webpacker with my own certificate
maris$ ./bin/webpack-dev-server --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key
ℹ ｢wds｣: Generating SSL Certificate
ℹ ｢wds｣: Project is running at https://######.dev:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /#########/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
```

Notice the line `ℹ ｢wds｣: Generating SSL Certificate`
It generates its own SSL certificate and ignores the command line arguments to use my own certificate.

**Comment by evilebottnawi** [comment]
@marisveide can you run `npm ls webpack-dev-server`?

**Comment by marisveide** [comment]
@evilebottnawi , sure!

```
maris$ npm ls webpack-dev-server
project@ /Users/maris/...
└── webpack-dev-server@3.1.14 
```

**Comment by evilebottnawi** [comment]
@marisveide you have old version, latest `3.2.1` https://github.com/webpack/webpack-dev-server/blob/master/package.json#L3, please update version and check again

**Comment by marisveide** [comment]
Oh, I see where the issue is.
We need this package `@rails/webpacker` (https://github.com/rails/webpacker), and the `webpack-dev-server` comes as a dependency for that one.
So actually, looks like I need to wait/ask them to support the latest `webpack-dev-server`.

**Comment by evilebottnawi** [comment]
@marisveide problem solved? Because we solve this issue for `3.2` version

**Comment by marisveide** [comment]
Sorry, nope, the problem is not solved.

Look - I have the `webpack-dev-server@3.2.1` now.
Still, when I run the following commands:
```
$ rm node_modules/webpack-dev-server/ssl/*
$ ./bin/webpack-dev-server --https --cert ~/.ssl/private.pem --key ~/.ssl/private.key
```

I see the following output:
```
ℹ ｢wds｣: Generating SSL Certificate
ℹ ｢wds｣: Project is running at https://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
```

When I look in the code of the latest version of this package, in the file `node_modules/webpack-dev-server/lib/Server.js` I see the following code:
```
if (!options.https.key || !options.https.cert) {
        // Use a self-signed certificate if no certificate was configured.
        // Cycle certs every 24 hours
        const certPath = path.join(__dirname, '../ssl/server.pem');

        let certExists = fs.existsSync(certPath);

        if (certExists) {
          const certTtl = 1000 * 60 * 60 * 24;
          const certStat = fs.statSync(certPath);

          const now = new Date();

          // cert is more than 30 days old, kill it with fire
          if ((now - certStat.ctime) / certTtl > 30) {
            this.log.info(
              'SSL Certificate is more than 30 days old. Removing.'
            );

            del.sync([certPath], { force: true });

            certExists = false;
          }
        }

        if (!certExists) {
          this.log.info('Generating SSL Certificate');

          const attrs = [{ name: 'commonName', value: 'localhost' }];

          const pems = createCertificate(attrs);

          fs.writeFileSync(certPath, pems.private + pems.cert, {
            encoding: 'utf8',
          });
        }

        fakeCert = fs.readFileSync(certPath);
      }
```

Notice the code `const certPath = path.join(__dirname, '../ssl/server.pem');` - it has hardcoded `server.pem` file path, so there is no way how it could use the passed parameters of my custom .pem file. Or am I not understanding something, how could it work with those parameters of my own PEM file?

Also, you can see that it removes the generated PEM file if it is more than 24 hours old.

**Comment by evilebottnawi** [comment]
@marisveide for `.pem` files you should use `--cacert` arg. From docs:
```
webpack-dev-server --https --key /path/to/server.key --cert /path/to/server.crt --cacert /path/to/ca.pem
```

We don't generate certificate if you provide `key` or `cert`.

**Comment by marisveide** [comment]
@evilebottnawi - so sorry, but when I pass the arguments as you show, it still generates the certificate.

I am generating the key, crt and ca.pem according to this doc:
https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309

If I update the SSL parameter file paths to something non-existing, it doesn't complain about that either, so that gives a hint it won't even try to locate those files.

Can you confirm that when you run it yourself with those parameters, it indeed reads from those files?

**Comment by marisveide** [comment]
Oh, @evilebottnawi - since that all is linked through the Rails "webpacker" gem, I think that is the issue. I managed to put the key/cert/ca into the webpacker.yml file, and it took the certificates, and that part is working fine.
It looks like the `./bin/webpack-dev-server` is actually not passing the correct command line arguments to the real `webpack-dev-server` NPM package.

Just now the Rails app "webpacker" part doesn't work properly, but it's not your issue.

Thank you so much for your time helping find where the issue is.
I really appreciate that.

**Comment by evilebottnawi** [comment]
@marisveide What version `webpacker` uses `webpack-dev-server`? So we can close issue?

**Comment by marisveide** [comment]
I have `rails/webpacker` v4.0.2.

Basically, when I set the correct keys, and actually see that SSL certificate is ok, then there is an issue with the Rails - it doesn't find the _"compiled"_ .js files.

Interestingly, when the SSL certificate is generated by `webpack-dev-server`, then everything works, it finds the compiled .js files. It's just when SSL certificate is properly generated, then it doesn't. 🤔 

But that is not your area, right?

**Comment by evilebottnawi** [comment]
@marisveide yep, it is not our area

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/rails/webpacker/issues/1758
