### ISSUE TITLE
Callbacks on state change

### ISSUE THREAD

**Issue by kigorw** [webpack/webpack-dev-server#170]
How to run some my code when I see in terminal:
webpack: bundle is now INVALID.
webpack: bundle is now VALID.

For example https://github.com/tonsky/AnyBar

**Comment by airwin** [comment]
I think you can try this in your task script (gulpfile?).
compiler.plugin('compile', someFunc)

**Comment by max-mykhailenko** [comment]
@airwin Your advice doesn't work :( Every callback run only on complete compiling by wepack. I can't find hot reloading compiling callback

**Comment by max-mykhailenko** [comment]
@airwin @kigorw But i find this:

```
compiler.plugin('done', function() {
  console.log('i here');
});
```

It's work!

**Comment by SpaceK33z** [comment]
Closing because of unclear question, but it seems to be fixed.
