### ISSUE TITLE
Pass mimeTypes options to webpack-dev-middleware

### ISSUE THREAD

**Issue by dmohns** [webpack/webpack-dev-server#1700]
- Operating System: macOS 10.14.3
- Node Version: `v11.10.0`
- NPM Version: `6.8.0`
- webpack Version: `4.29.6`
- webpack-dev-server Version: `3.2.1`

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

`webpack-dev-middleware` exposes an option to set custom mime types via passing a `mimeType` object, see https://github.com/webpack/webpack-dev-middleware#mimetypes

Currently, there is no easy way to define custom mime types used in DevServer just from `webpack.config.js`. 

### Expected Behavior

It would be nice if the user was able to set (for example) `devServer.mimeType` in `webpack.config.js` to pass custom mimes types to `webpack-dev-middleware`.

### Actual Behavior

The user has to one level lower and use `webpack-dev-middleware` directly to customize mimeTypes.

### For Features; What is the motivation and/or use-case for the feature?

Feature is handy in cases where custom mime types are required. No negative impact for all other cases.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by dragonDScript** [comment]
I need this. I can't load bundle.js because of this
