### ISSUE TITLE
'node-forge' security alert

### ISSUE THREAD

**Issue by yingliang33h** [webpack/webpack-dev-server#1702]
- Operating System: Mirosoft Windows 10
- Node Version: 8.11.1
- NPM Version:5.6.0
- webpack Version:3.10.0
- webpack-dev-server Version:3.2.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### For Features; What is the motivation and/or use-case for the feature?
The latest version of webpack-dev-server depends on node-forge@0.7.5. During our latest security scan, it shows an alert:
This component was not approved for the following reasons:
- TLS 1.2 not implemented yet, maybe in 0.8 per roadmap, but that release may only be prep-work for future implementation:
- https://github.com/digitalbazaar/forge/issues/203
- 
- TLS does not check for acceptable cipher suite configurations. From "tls.js":
- // FIXME: should be checking configured acceptable cipher suites
- 
- TLS client connections may only support TLS_RSA_WITH_AES_128_CBC_SHA & TLS_RSA_WITH_AES_256_CBC_SHA
- https://github.com/digitalbazaar/forge/issues/600

Could we upgrade the node-forge version?

**Comment by evilebottnawi** [comment]
We don't use `node-forge` directly we need update https://github.com/webpack/webpack-dev-server/blob/master/package-lock.json#L10153

**Comment by evilebottnawi** [comment]
Feel free to send a PR with update

**Comment by evilebottnawi** [comment]
Fixed in master

**Comment by zadixon** [comment]
I don't think this is actually fixed in master. [It's still 0.7.5 there](https://github.com/webpack/webpack-dev-server/blob/99b78dc3ddeb94af33fe71942ec0312a9be3e2c2/package-lock.json#L8100).

**Comment by evilebottnawi** [comment]
Yep, but we need update this in `selfsigned`

**Comment by evilebottnawi** [comment]
Unfortunately, we can't do something on our side :disappointed: Close in favor https://github.com/jfromaniello/selfsigned/pull/29 

Workaround - update your deps and lock file
