### ISSUE TITLE
Using API doesn't add HMR plugin entry

### ISSUE THREAD

**Issue by rlamana** [webpack/webpack-dev-server#1703]
Hot Module Replacement plugin entry doesn't seem to be added when using the API. The new tests on the PR #1664 use the dev server API via the `test/helper.js` and `addEntries` function in `lib/utils/addEntries.js` had to be manually called to make it work.

webpack Version: 4.29.0
webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### How can we reproduce the behavior?

Remove `addEntries` call in [test/Client.test.js](https://github.com/webpack/webpack-dev-server/pull/1664/files#diff-b2d4a9632f66a16163b3edfdf960185eR36) and the e2e test will fail because HMR is not loaded.

### Expected behavior

When using the API and `hot` is enabled, HMR plugin entry should be also added.

**Comment by Loonride** [comment]
@evilebottnawi I messed with this issue briefly here: https://github.com/Loonride/webpack-dev-server/blob/hmr-entry-fix/lib/Server.js#L131. It would be nice if we had the ability to create the webpack compiler within Server.js. The problem I ran into was that users can use the compiler after they pass it in, so redefining it in Server.js does not work: https://github.com/webpack/webpack-dev-server/blob/master/test/Server.test.js#L25

**Comment by evilebottnawi** [comment]
@Loonride yep, we should think how better solve this without break other code, feel free to experiment and send a PR
