### ISSUE TITLE
[feature request] --stdin as option in config

### ISSUE THREAD

**Issue by njwest** [webpack/webpack-dev-server#1712]
System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

Would be really useful to be able to do:
```
module.exports = {
  //...
  devServer: {
    stdin: true
  }
};
```

instead of having to run webpack-dev-server with --stdin on CLI only [as specified in the docs](https://webpack.js.org/configuration/dev-server/#devserverstdin---cli-only)

### For Features; What is the motivation and/or use-case for the feature?

Some popular dev tools (like vue-cli) have opinionated wrappers around webpack-dev-server that make it only possible to configure webpack via their own config files (where they pass along options to webpack-dev-server's `devServer` configuration object).

Unfortunately, this obscures really useful flags like stdin

Thank you for the amazing software!

**Comment by evilebottnawi** [comment]
@njwest i think we should open this issue in `webpack-cli`, for `v4` we drop our `bin` in favor `webpack-cli` command, so i think we should discussion about this in `webpack-cli`
