### ISSUE TITLE
devServer ignore port param when load chunks

### ISSUE THREAD

**Issue by esomkin** [webpack/webpack-dev-server#1717]
- Operating System: MacOS
- Node Version: 11.9
- NPM Version: 6.9
- webpack Version: 4.29.0
- webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

```js
...
entry: {
	'test/index': [ './resources/assets/modules/test/index', ],
},
output: {
	path: path.resolve(__dirname, './public/build/'),
	publicPath: '/build/',
	filename: '[name].js',
	chunkFilename: '[name].js',
},
...
devServer: {
	host: 'domain',
	port: 8080,
},
```

```js
import React, { Component, Suspense, lazy, } from 'react';

const BlazyComponent = lazy(() => {
	return import('./blazy');
});

class Main extends Component {
	render () {
		return (<Suspense fallback={<div>Loading...</div>}>
			<BlazyComponent/>
		</Suspense>);
	}
}

export default Main;
```

### Expected Behavior
Load chunk from http://domain:8080/build/0.js

### Actual Behavior
Try load chunk from http://domain/build/0.js

### For Bugs; How can we reproduce the behavior?
Simply create react environment with dynamic import support

### For Features; What is the motivation and/or use-case for the feature?

**Comment by evilebottnawi** [comment]
@esomkin please create minimum reproducible test repo, works fine for me

**Comment by esomkin** [comment]
@evilebottnawi Here is reproducible demo https://github.com/esomkin/repo.

**Comment by jeffreymb** [comment]
This issue is majorly affecting our productivity as HMR is completely non-functional. Any ETA on this bug?

**Comment by evilebottnawi** [comment]
@jeffreymb we have many issues, if you want fix it asap - PR welcome

**Comment by Loonride** [comment]
@evilebottnawi could you reproduce this? The problem as I understand it is that if you go to `http://repo:8080/public/` it should try to load `http://repo/build/0.js`. Mine seemed to work fine and loaded `http://repo:8080/build/0.js`.

**Comment by evilebottnawi** [comment]
@Loonride i don't look this issue (many work right now), feel free to investigate and send a PR with fix

**Comment by evilebottnawi** [comment]
@esomkin @jeffreymb I can't reproduce problem

**Comment by seancrater** [comment]
@evilebottnawi This is definitely a real bug, I've been struggling with it for the past 2 hours. I have a defined host of `0.0.0.0`, `devServer` has a port of 3000 (builds are being consumed from port 8000. My entry and vendor chunk are loading fine but dynamic imports generated by them are failing because `webpack-dev-server` is trying to fetch from port 8000. This is not the behavior I would expect. I want `webpack-dev-server` to fetch all assets from the port specified in config.

**Comment by seancrater** [comment]
Also, for debugging purposes, my Webpack config looks like this:
```
        output: {
            filename: '[name].js',
            path: path.resolve(__dirname, './static/js/dist'),
            publicPath: '/static/js/dist/'
        },
        devServer: {
            // contentBase: path.join(__dirname, 'static/js/dist'),
            headers: { 'Access-Control-Allow-Origin': '*' },
            port: 3000
        },
```

**Comment by Loonride** [comment]
@seancrater Does specifying an exact output `publicPath` fix your problem? Like `publicPath: 'http://localhost:3000/static/js/dist/` for the config above?

See https://github.com/webpack/webpack-dev-server/issues/1385#issuecomment-502758062

**Comment by seancrater** [comment]
@Loonride worked great! Thank you very much! Kinda sucks but it seems like your PR in there should fix this anyway! 😄
