### ISSUE TITLE
Reload occurs on every entry even only one entry changed.

### ISSUE THREAD

**Issue by orange4glace** [webpack/webpack-dev-server#1719]
- Operating System:
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.2.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
module.exports = [{
    entry: {
      a: './a.js'
    },
    target: 'web',
    resolve: {
      modules: ['node_modules', 'app'],
      extensions: ['.js', '.jsx']
    },
    output: {
      path: __dirname + '/dist',
      publicPath: '/',
      filename: '[name].js'
    }
  },{
    entry: {
      a: './b.js'
    },
    target: 'web',
    resolve: {
      modules: ['node_modules', 'app'],
      extensions: ['.js', '.jsx']
    },
    output: {
      path: __dirname + '/dist',
      publicPath: '/',
      filename: '[name].js'
    }
  },

]
```

**a.js**
```js
console.log('a.js')
```
**a.html**
```js
<html>
  <body>
    <script src='./a.js'></script>
  </body>
</html>
```

**b.js**
```js
console.log('b.js')
```
**b.html**
```js
<html>
  <body>
    <script src='./b.js'></script>
  </body>
</html>
```

### Expected Behavior

When either `a.js` or `b.js` is changed, like, let's say if `a.js` is changed. Then only `a.html` should be reloaded since `b.html` does not make use of `a.js`.

### Actual Behavior

`a.html` and `b.html` are reloaded together..

### For Features; What is the motivation and/or use-case for the feature?

I'm making a web app and there's a separation between data layer and presentation layer. data layer is executed on main page and presentation layer is executed on its pop-up page. When only presentation layer script is changed, only presentation pop-up page is reloaded so the underlying data can be preserved.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/1503, thanks for issue, feel free to send a PR with fix

**Comment by orange4glace** [comment]
@evilebottnawi Thanks for the comment. It seems time to code XD

**Comment by evilebottnawi** [comment]
@orange4glace we are happy when you send PRs

**Comment by orange4glace** [comment]
@evilebottnawi I'm just trying to find where the compilation start point is, but I can't find it. The only code line I found `compiler.run()` is [here](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/context.js#L81) and it seems no actual effect since after delete that function, WDS still works. Could you tell me where the actual webpack compile starts?

**Comment by evilebottnawi** [comment]
You are right, compiler.run is function here starts webpack, need investigate inside webpack why it is happens, also we can test this in watch mode

**Comment by orange4glace** [comment]
@evilebottnawi I mean, I'm finding the **start point** of  the compilation (or at least which code line of WDS or WDM fires webpack to start compile). The only code line I found which runs `compiler.run()` is [this](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/context.js#L81) one. But when I have tested WDS without that code line (by clearing body of `rebuild()`), WDS still works normally so it looks `rebuild()` function is not the starting point of it.


```javascript
  function rebuild() {
    // if (context.state) {
    //   context.state = false;
    //   context.compiler.run((err) => {
    //     if (err) {
    //       log.error(err.stack || err);
    //       if (err.details) {
    //         log.error(err.details);
    //       }
    //     }
    //   });
    // } else {
    //   context.forceRebuild = true;
    // }
  }
```

```shell
$ npm start

> webpack-dev-server-test@1.0.0 start D:\source\webpack-dev-server-test
> webpack-dev-server --config ./webpack.config.js --mode development --content-base ./dist

i ｢wds｣: Project is running at http://localhost:8081/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\source\webpack-dev-server-test\dist
i ｢wdm｣: Hash: bc0f3ec509df1dd83567
Version: webpack 4.29.6
Time: 337ms
Built at: 2019-03-16 20:48:54
Asset     Size  Chunks             Chunk Names
 a.js  347 KiB       a  [emitted]  a
Entrypoint a = a.js
[0] multi (webpack)-dev-server/client?http://localhost:8081 ./a.js 40 bytes {a} [built]
[./a.js] 21 bytes {a} [built]

.....

i ｢wdm｣: Compiled successfully.

// Still works!
```

**Comment by evilebottnawi** [comment]
Here other run https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L130
