### ISSUE TITLE
Page not reloading in iframe mode (inline: false)

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#1720]
- Operating System: Windows 7
- Node Version: 8.10.0
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.2.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Page should reload in iframe mode on changes.

### Actual Behavior
Page does not reload on changes (console output does not update). 

### For Bugs; How can we reproduce the behavior?
reproducible test repo: https://github.com/Loonride/webpack-dev-server-iframe
Do npm start, go to http://localhost:8080/webpack-dev-server/main.
Change something in src/index.js, the console output will not change and the message "App hot update." does not go away. Upon manual page refresh, the changes appear.

**Comment by evilebottnawi** [comment]
@Loonride I think we should remove `inline` for next major release and remove `inline` client

**Comment by Loonride** [comment]
> @Loonride I think we should remove `inline` for next major release and remove `inline` client

Yes I agree

**Comment by evilebottnawi** [comment]
So i think we can close the issue, it was always buggy and looks nobody uses it
