### ISSUE TITLE
What about separating the proxy into a middleware?

### ISSUE THREAD

**Issue by xianshannan** [webpack/webpack-dev-server#1723]
I writed  [restful-mock-middleware](https://github.com/dog-days/webpack-launcher/tree/master/packages/restful-mock-middleware) and used it in the **webpack-dev-server before function**, but the mock middleware will parse the http body, which will cause the body to be blocked when the proxy is used. So we need to use the `restful-mock-middleware` before the proxy. 

I extracted the proxy from `webpack-dev-server` and created a middleware  [webpack-dev-server-proxy-middlware](https://github.com/dog-days/webpack-launcher/tree/master/packages/webpack-dev-server-proxy-middlware) to use before mock middleware.

I can also use the proxy middleware in the custom static server.

(My English is bad，never mind.)

**Comment by evilebottnawi** [comment]
@xianshannan i think it is out of scope projects, it is already `middleware`, we just easy way to configure, you can disable built-in feature and use own middleware. What is problem? Maybe we can provide more option

**Comment by xianshannan** [comment]
@evilebottnawi `middleware` use inside `middleware` is not standard? I create a `expressMiddlewareCompose` function to use multiple middlewares. Such as the following
```js
composeMiddlewares([
  bodyParser.json(),
  bodyParser.raw(),
  bodyParser.text(),
  bodyParser.urlencoded({ extended: true }),
  uploadBodyParser.any(),
  // mock should be used before body parsing
  mockMiddleware,
])(req, res, next);
```

**Comment by xianshannan** [comment]
Here is what i did with webpack dev server config:
```js
// 大部分采用 create-react-app 配置
'use strict';

const createMockMiddleware = require('restful-mock-middleware');
const createProxyMiddleware = require('webpack-dev-server-proxy-middlware');

const webpackConfig = require('./webpack.config');
const webpackLauncherConfig = require('../config/webpackLauncher.config');
const { host, https, appPublic, buildGzip } = webpackLauncherConfig;

module.exports = {
  // 当使用 HTML5 History API 时，任意的 404 响应都可能需要被替代为 index.html。通过传入以下启用：
  historyApiFallback: Object.assign({
    // 当路径中使用点(dot)，你可能需要使用 disableDotRule
    // 如 http://localhost/babel.config，就包含 (.)
    disableDotRule: true,
  }),
  // 设置为 true 时，此选项绕过主机检查。
  // 不检查主机的应用程序时，容易受到 DNS 重新连接攻击。
  // 默认开启
  disableHostCheck: true,
  // 开启gzip功能
  compress: true,
  // 关闭WebpackDevServer繁琐的输出信息
  // 但警告和错误信息不会被关闭
  clientLogLevel: 'none',
  // 告诉服务器从哪个目录中提供内容。只有在你想要提供静态文件时才需要。
  // devServer.publicPath 将用于确定应该从哪里提供 bundle，并且此选项优先。
  contentBase: appPublic,
  // 告知服务器，观察 devServer.contentBase 下的文件。文件修改后，会触发一次完整的页面重载。
  watchContentBase: true,
  // 当出现编译器错误或警告时，在浏览器中显示全屏覆盖层。
  // 使用 create-react-app wwebpackHotDevClient 时，
  // 这个覆盖成会被替换成 create-react-app 自定义的
  overlay: true,
  //开启热替换功能
  hot: true,
  //跟 webpack.config 中 publicPath 相等，bundle.js 等内存文件输出目录
  publicPath: webpackConfig.output.publicPath,
  // 会关闭WebpackDevServer编译后所有的信息（包括错误警告信息）
  // 后续通过 compiler.plugin('done',null) 自定义信息
  quiet: true,
  // watch设置
  watchOptions: {
    ignored: [/node_modules/],
  },
  // 默认情况下，dev-server 通过 HTTP 提供服务。也可以选择带有 HTTPS 的 HTTP/2 提供服务：
  https,
  host: host || 'localhost',
  // 禁止使用 webpack-dev-server
  // 使用独立的 proxy（从 webpack-dev-server 中抽离的）
  // 用法不变
  proxy: undefined,
  /**
   * 在服务内部的所有其他中间件之前， 提供执行自定义中间件的功能。
   */
  before(app, server) {
    if (buildGzip) {
      app.use(function(req, res, next) {
        if (/\.(js|css)$/.test(req.url) && !!~req.url.indexOf('dll/dll.')) {
          // buildGzip 对 dll 也有效
          res.header('Content-Encoding', 'gzip');
        }
        next();
      });
    }

    // 由于 body-parser 会截取 body 内容，所以 http-proxy-middleware 必须在 body-parser（ restful-mock-middleware 用到） 之前
    // 可以看这个 issue https://github.com/chimurai/http-proxy-middleware/issues/40
    app.use(function(...args) {
      // 可动态修改 proxy 配置
      delete require.cache[require.resolve('webpack-launcher-utils/webpackLauncherConfig')];
      const { proxy, useMockServer } = require('webpack-launcher-utils/webpackLauncherConfig');

      createProxyMiddleware(proxy, server)(...args);

      if (useMockServer) {
        app.use(createMockMiddleware());
      }
    });
  },
};
```

**Comment by xianshannan** [comment]
@evilebottnawi it's not standard to use `middleware` inside a `middleware`?
But the separation logic is better managed and more convenient.

**Comment by evilebottnawi** [comment]
@xianshannan 

> it's not standard to use middleware inside a middleware?

No

You can use `express` inside `express`

What is not enough in `proxy` configuration?

**Comment by xianshannan** [comment]
I want to use the `webpack-dev-server` proxy as a mddleware to other project. That will be more convenience. So I recommend extracting the usage of the `webpack-dev-server proxy as a middleware. This is just a suggestion.
@evilebottnawi

**Comment by evilebottnawi** [comment]
@xianshannan sorry, but it is out of scope `webpack-dev-server`, you should use `http-proxy-middleware` package for this purpose.
