### ISSUE TITLE
Inappropriate message on the front page.

### ISSUE THREAD

**Issue by abhinavsagar** [webpack/webpack-dev-server#1727]
- Operating System: 10 64
- Node Version:10.10.0
- NPM Version:6.4.1
-webpack Version: 4.28.4
-webpack-dev-server Version: 3.1.14

- [x] This is a **bug**

### Expected Behavior
Appropriate message illustrating what devserver is should be displayed.

### Actual Behavior
It shows 'error loading content' message

### For Bugs; How can we reproduce the behavior?
Just visit the home page of dev server

**Comment by evilebottnawi** [comment]
Sorry you don't provide enough information to help you, please fill issue and create minimum reproducible test repo
