### ISSUE TITLE
Inappropriate conditional checking

### ISSUE THREAD

**Issue by abhinavsagar** [webpack/webpack-dev-server#1728]
- Operating System:
- Node Version:8.14.0
- NPM Version:6.7.0
- webpack Version:4.28.4
- webpack-dev-server Version:3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
When requested for the script by the user which is not present empty script should be returned in `getCurrentScriptSourceSimilar` function. Similar problem with `overlay` function and `error` function.

### Actual Behavior
When user requests for a script which is not present then nothing happens.

### For Bugs; How can we reproduce the behavior?
In the server try getting the script or do something which produces error.

**Comment by evilebottnawi** [comment]
Can't reproduce, closing, feel free to feedback
