### ISSUE TITLE
Imported object is not defined

### ISSUE THREAD

**Issue by QuantumInformation** [webpack/webpack-dev-server#173]
Dear all, i wonder if someone could take a quick look at my repo to see if I've done someing silly

https://github.com/QuantumInformation/es6-boilerplate

For some reason in this code I am getting the error Uncaught ReferenceError: ShoppingCart is not defined(anonymous function) etc I am bundling this code with web pack and running with webpack-dev-server in hot mode. (live reload)

```js
import ShoppingCart from './shoppingCart'

document.addEventListener("DOMContentLoaded", function (event) {
  var cart = new ShoppingCart(['foo'],document.querySelector('#app'))
});
```
This is the class I am importing: shoppingcart.js:
```js
class ShoppingCart {
  constructor(defaults, element) {
    this.items = defaults;
    this.element = element;
    init();
  }

  init() {
  this.element.querySelector('button')
  }



  render() {

  }
}
export { ShoppingCart }```

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.
