### ISSUE TITLE
Routes Test relies on compilation to finish, but doesn't wait for it

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#1734]
- Operating System: Windows 7
- Node Version: 8.10.0
- NPM Version: 6.4.1
- webpack Version: 4.29.0
- webpack-dev-server Version: 3.2.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

The request made to /webpack-dev-server by Routes.test.js relies on the webpack compilation to complete: https://github.com/webpack/webpack-dev-server/blob/master/test/Routes.test.js#L58

### Expected Behavior

Compilation should finish before the test starts. As stated here: https://github.com/webpack/webpack-dev-server/issues/847 the server callback can be called before compilation is done.

### Actual Behavior

If the compilation takes a long time, this test fails, since it does not wait for compilation to finish before testing.

### For Bugs; How can we reproduce the behavior?

Bring the test here: https://github.com/webpack/webpack-dev-server/blob/master/test/Routes.test.js#L58 to the top, and the test will probably run before compilation is done. The only reason it has been succeeding is because there are many tests before it, and compilation has time to finish. 

### Additional

I ran into this while working on a different fix which extended the compilation time. I will make a PR with the fix for this test. I think this is the only test where this mistake is made, but I'm not 100% sure.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/1735
