### ISSUE TITLE
How dev server proxy chunked response

### ISSUE THREAD

**Issue by lijianxin1202** [webpack/webpack-dev-server#1742]
- Operating System:
- Node Version: 6.4.1
- NPM Version: 11.8.0
- webpack Version: 4.28.3
- webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
    proxy: {
      '/api': 'http://localhost:8778'
    }
```

```js
// additional code, remove if not needed.
  return new Promise((resolve, reject) => {
    let request = new XMLHttpRequest();
    const method = 'get';
    request.open(method.toUpperCase(), '/api/v1/chunked', true);
    request.timeout = 30 * 60 * 1000;
    request.onreadystatechange = function() {
      if (request.readyState === 4) {
        resolve(request.responseText);
        request = null;
      } else if (request.readyState === 3) {
        console.log(request.responseText);
      }
    };
    request.onerror = function() {
      reject('Network Error');
      request = null;
    };
    request.send();
  });
```

### Expected Behavior
Whenever the response returns, log the current part of responseText.
### Actual Behavior
Only the request full completed then log the whole responseText.
### For Bugs; How can we reproduce the behavior?
In the server try return a chunked response and in the browser use readyState === 3 receive it.

**Comment by evilebottnawi** [comment]
@lijianxin1202 please provide minimum reproducible test repo, looks problem in you setup, why you use `XMLHttpRequest` in server side?

**Comment by lijianxin1202** [comment]
https://github.com/lijianxin1202/webpack-proxy-chunk-demo
The chunked data request server directly and will display message every 5s, the proxy data use proxy and will display all data at once.
In demo I found that if server response does not include Content-Type header,  it will proxy chunked request correctly, otherwise it will cannot work correctly.

**Comment by evilebottnawi** [comment]
It is expected please read documentation about http proxy

**Comment by evilebottnawi** [comment]
Closing, feel free to feedback

**Comment by lijianxin1202** [comment]
Finally I use this config resolve my issue, thank you!
```js
proxy: {
  '/proxy': {
    target: 'http://localhost:7000',
    selfHandleResponse: true,
      onProxyRes: function onProxyRes(proxyRes, req, res) {
        proxyRes.on('data', function (data) {
          res.write(data);
        });
      proxyRes.on('end', function () {
        res.end();
      });
    }
  },
},
```
