### ISSUE TITLE
when i run webpack-dev-server i got this error 

### ISSUE THREAD

**Issue by Mohamed-Nassr** [webpack/webpack-dev-server#1748]
WARNING in ./node_modules/terser-webpack-plugin/dist/worker.js 12:130-137
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
 @ ./node_modules/terser-webpack-plugin/dist/index.js
 @ ./node_modules/terser-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/loader-runner/lib/loadLoader.js 5:2-28
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/loader-runner/lib/LoaderRunner.js
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/AutomaticPrefetchPlugin.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/worker-farm/lib/child/index.js 49:33-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/worker-farm/lib/fork.js
 @ ./node_modules/worker-farm/lib/farm.js
 @ ./node_modules/worker-farm/lib/index.js
 @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
 @ ./node_modules/terser-webpack-plugin/dist/index.js
 @ ./node_modules/terser-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fsevents' in 'D:\majal\server\node_modules\chokidar\lib'
 @ ./node_modules/chokidar/lib/fsevents-handler.js
 @ ./node_modules/chokidar/index.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/default-gateway/README.md 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> # default-gateway
| [![](https://img.shields.io/npm/v/default-gateway.svg?style=flat)](https://www.npmjs.org/package/default-gateway) [![](https://img.shields.io/npm/dm/default-gateway.svg)](https://www.npmjs.org/package/default-gateway) [![](https://api.travis-ci.org/silverwind/default-gateway.svg?style=flat)](https://travis-ci.org/silverwind/default-gateway)
| 
 @ ./node_modules/default-gateway sync ^\.\/.*$ ./README.md
 @ ./node_modules/default-gateway/index.js
 @ ./node_modules/internal-ip/index.js
 @ (webpack)-dev-server/lib/utils/createDomain.js
 @ (webpack)-dev-server/lib/utils/addEntries.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/default-gateway/LICENSE 1:14
Module parse failed: Unexpected token (1:14)
You may need an appropriate loader to handle this file type.
> Copyright (c) silverwind
| All rights reserved.
| 
 @ ./node_modules/default-gateway sync ^\.\/.*$ ./LICENSE
 @ ./node_modules/default-gateway/index.js
 @ ./node_modules/internal-ip/index.js
 @ (webpack)-dev-server/lib/utils/createDomain.js
 @ (webpack)-dev-server/lib/utils/addEntries.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/loader-runner/lib/loadLoader.js 5:2-28
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./node_modules/loader-runner/lib/LoaderRunner.js 7:17-40
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/AutomaticPrefetchPlugin.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js
PS D:\majal\server> npm run start

> server@1.0.0 start D:\majal\server
> webpack webpack-dev-server

Hash: 31aa1a3a670384d57598
Version: webpack 4.29.6
Time: 7071ms
Built at: 2019-03-30 18:02:14
    Asset      Size  Chunks             Chunk Names
bundle.js  9.55 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./node_modules/webpack-dev-middleware/index.js] (webpack)-dev-middleware/index.js 2.32 KiB {main} [built]
[./node_modules/webpack-dev-middleware/lib/context.js] (webpack)-dev-middleware/lib/context.js 2.24 KiB {main} [built]
[./node_modules/webpack-dev-middleware/lib/fs.js] (webpack)-dev-middleware/lib/fs.js 3.07 KiB {main} [built]
[./node_modules/webpack-dev-server/lib/Server.js] (webpack)-dev-server/lib/Server.js 27.3 KiB {main} [built]
[./node_modules/webpack-dev-server/lib/options.json] (webpack)-dev-server/lib/options.json 10.5 KiB {main} [built]
[./node_modules/webpack-dev-server/lib/utils/addEntries.js] (webpack)-dev-server/lib/utils/addEntries.js 1.8 KiB {main} [built]
[./node_modules/webpack-dev-server/lib/utils/createCertificate.js] (webpack)-dev-server/lib/utils/createCertificate.js 1.17 KiB {main} [built]
[./node_modules/webpack-dev-server/lib/utils/createLogger.js] (webpack)-dev-server/lib/utils/createLogger.js 360 bytes {main} [built]
[./node_modules/webpack/lib/webpack.js] (webpack)/lib/webpack.js 7.71 KiB {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[http] external "http" 42 bytes {main} [built]
[https] external "https" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[tls] external "tls" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
    + 1434 hidden modules

WARNING in ./node_modules/terser-webpack-plugin/dist/worker.js 12:130-137
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
 @ ./node_modules/terser-webpack-plugin/dist/index.js
 @ ./node_modules/terser-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js
 @ ./node_modules/express/lib/express.js
 @ ./node_modules/express/index.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/loader-runner/lib/loadLoader.js 5:2-28
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/loader-runner/lib/LoaderRunner.js
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/AutomaticPrefetchPlugin.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/worker-farm/lib/child/index.js 49:33-53
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/worker-farm/lib/fork.js
 @ ./node_modules/worker-farm/lib/farm.js
 @ ./node_modules/worker-farm/lib/index.js
 @ ./node_modules/terser-webpack-plugin/dist/TaskRunner.js
 @ ./node_modules/terser-webpack-plugin/dist/index.js
 @ ./node_modules/terser-webpack-plugin/dist/cjs.js
 @ (webpack)/lib/WebpackOptionsDefaulter.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fsevents' in 'D:\majal\server\node_modules\chokidar\lib'
 @ ./node_modules/chokidar/lib/fsevents-handler.js
 @ ./node_modules/chokidar/index.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/default-gateway/README.md 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> # default-gateway
| [![](https://img.shields.io/npm/v/default-gateway.svg?style=flat)](https://www.npmjs.org/package/default-gateway) [![](https://img.shields.io/npm/dm/default-gateway.svg)](https://www.npmjs.org/package/default-gateway) [![](https://api.travis-ci.org/silverwind/default-gateway.svg?style=flat)](https://travis-ci.org/silverwind/default-gateway)
| 
 @ ./node_modules/default-gateway sync ^\.\/.*$ ./README.md
 @ ./node_modules/default-gateway/index.js
 @ ./node_modules/internal-ip/index.js
 @ (webpack)-dev-server/lib/utils/createDomain.js
 @ (webpack)-dev-server/lib/utils/addEntries.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/default-gateway/LICENSE 1:14
Module parse failed: Unexpected token (1:14)
You may need an appropriate loader to handle this file type.
> Copyright (c) silverwind
| All rights reserved.
| 
 @ ./node_modules/default-gateway sync ^\.\/.*$ ./LICENSE
 @ ./node_modules/default-gateway/index.js
 @ ./node_modules/internal-ip/index.js
 @ (webpack)-dev-server/lib/utils/createDomain.js
 @ (webpack)-dev-server/lib/utils/addEntries.js
 @ (webpack)-dev-server/lib/Server.js

WARNING in ./node_modules/loader-runner/lib/loadLoader.js 5:2-28
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./node_modules/loader-runner/lib/LoaderRunner.js 7:17-40
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/AutomaticPrefetchPlugin.js
 @ (webpack)/lib/webpack.js
 @ (webpack)-dev-server/lib/Server.js

my webpack config 
[config.txt](https://github.com/webpack/webpack-dev-server/files/3025664/config.txt)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Don't import `webpack-dev-server` in your bundle because it is unsafe and no need do this
