### ISSUE TITLE
Very slow emitting and after emitting step after upgrading from node v9 to node v10 with many entry points

### ISSUE THREAD

**Issue by edwardchen** [webpack/webpack-dev-server#1762]
- Operating System: macOS Mojave Version 10.14.3
- Node Version: v9.2.1 and v10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.2.1

- [ x ] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
With node v9.2.1 and > 100 entry points, our emitting and after emitting step have gone are  <1000ms
### Actual Behavior
With same setup and node v10.15.3 they take around ~30000ms each. 

### For Bugs; How can we reproduce the behavior?
Has anybody experienced this and know what's causing the slowdown?

**Comment by evilebottnawi** [comment]
@edwardchen Please:
1. Use issue template otherwise it was closed.
2. Try to create minimum reproducible test repo. Maybe deopt in v8,  we need report about this

**Comment by edwardchen** [comment]
I found the problem. We are using rails/webpacker which is using webdeveric/webpack-assets-manifest, in which the current version does not do any stats.toJson filtering.

From: https://webpack.js.org/guides/build-performance/

> stats.toJson speed
> webpack 4 outputs a large amount of data with its stats.toJson() by default. Avoid retrieving portions of the stats object unless necessary in the incremental step. webpack-dev-server after v3.1.3 contained a substantial performance fix to minimize the amount of data retrieved from the stats object per incremental build step.

**Comment by evilebottnawi** [comment]
@edwardchen can you test master version? Also can you provide configuration of stats? We need find what we should exclude to improve build time webpack-dev-server, thanks!

**Comment by edwardchen** [comment]
I think the issue has been fixed in webpack-dev-server a while ago in this commit.

https://github.com/webpack/webpack-dev-server/commit/da33d2b2fc39c022c8326af6c5cdd408132ba7c9#diff-15fb51940da53816af13330d8ce69b4e

We are using a rails gem (webpacker) which uses webpack-dev-server but then patches in a different library to generate the asset manifest, and that's where the problem..

**Comment by evilebottnawi** [comment]
@edwardchen Maybe better open issue in `webpacker`? We don't use somethings strange here

**Comment by edwardchen** [comment]
Yeah, I'm saying that this issue can be closed because I figured out it's an issue with a different package.
