### ISSUE TITLE
[Modification] Allow passing args to `devServer.open`

### ISSUE THREAD

**Issue by dangreenisrael** [webpack/webpack-dev-server#1769]
- Operating System: Mac OS
- Node Version: 8.15.0
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.3.0

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
devServer: {
  open: ['google chrome', '--incognito']
}

```

### Expected Behavior
`devServer.open` accepts an array of strings as per the as per the `open` documentation 
https://www.npmjs.com/package/open (formerly https://www.npmjs.com/package/opn)

In this case, open chrome in an incognito tab, 

### Actual Behavior

Anything other than a string is dropped
https://github.com/webpack/webpack-dev-server/blob/21687c3bfc95752957d16470b97d281001dc6a07/lib/utils/status.js#L45-L59

### For Features; What is the motivation and/or use-case for the feature?

We would like to automatically open incognito tabs for our devs, as part of our setup and teardown for `webpack-dev-server` is updating the hosts file, and chrome caches DNS.

If this is something that would be accepted I could open a PR.

**Comment by evilebottnawi** [comment]
Yep, PR welcome :+1:

**Comment by thesaltygerman** [comment]
This option support on alternative https://www.npmjs.com/package/webpack-plugin-serve#open. It is different but if needed support, good alternitive.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by evilebottnawi** [comment]
Done in master, release will be soon
