### ISSUE TITLE
v3.3.0 freezes at 70% - halts building/running

### ISSUE THREAD

**Issue by tbehunin** [webpack/webpack-dev-server#1771]
- Operating System: MacOS 10.13.6
- Node Version: 10.15.2
- NPM Version: 6.9.0
- webpack Version: 4.15.0
- webpack-dev-server Version: 3.3.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

We have the following dependency in my `package.json`:
```
"webpack-dev-server": "^3.1.0",
```
As of today, an npm install will download the latest version: **3.3.0**. When we run our `npm start` command (which runs `"babel-node ./node_modules/webpack-dev-server/bin/webpack-dev-server --config build/webpack.dev.js --max-old-space-size=4096 --compress true --progress --colors"`), _it builds up to 70% and then **freezes**_.

When we downgrade `webpack-dev-server` to **3.2.1** in our package like so:
```
"webpack-dev-server": "3.2.1",
```
it builds and runs just fine. A co-worker of mine can also reproduce this as well. We've tried everything from removing all the `node_modules` and reinstalling, clearing the npm cache, doing a `git clean -fx` and reinstalling/rerunning, rebooting computers, etc. There's some issue with 3.3.0. If you would like more info, I can provide it to you - I just don't know what you would need to diagnose the issue.

### Expected Behavior
Version 3.3.0 should build and run as expected.

### Actual Behavior
Version 3.3.0 builds up to 70% and then freezes.

### For Bugs; How can we reproduce the behavior?
I'd assume follow the steps outlined above.

### For Features; What is the motivation and/or use-case for the feature?
n/a

**Comment by thijstriemstra** [comment]
here it doesn't freeze but throws this error (ubuntu 16.04):

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: watch /foo/bar/node_modules/es-abstract ENOSPC
    at FSWatcher.start (fs.js:1402:19)
    at Object.fs.watch (fs.js:1428:11)
```

**Comment by hiroppy** [comment]
Please submit a reproducible repository.

**Comment by thijstriemstra** [comment]
https://github.com/collab-project/videojs-wavesurfer (upgrade to v3.3.0 and it'll break `npm run start`)

**Comment by hiroppy** [comment]
This sample does not occur errors in my PC(MacOS).

**Comment by thijstriemstra** [comment]
Hmm, with 3.2.1 it works, upgrading to 3.3.0 causes issues.

**Comment by hiroppy** [comment]
@tbehunin Please submit a reproducible repository.

**Comment by hiroppy** [comment]
@thijstriemstra Could you submit an npm error log?

**Comment by thijstriemstra** [comment]
from `.npm/_logs/2019-04-08T21_20_37_680Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.9.0
3 info using node@v9.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle videojs-wavesurfer@2.8.0~prestart: videojs-wavesurfer@2.8.0
6 info lifecycle videojs-wavesurfer@2.8.0~start: videojs-wavesurfer@2.8.0
7 verbose lifecycle videojs-wavesurfer@2.8.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle videojs-wavesurfer@2.8.0~start: PATH: [HIDING THIS]
9 verbose lifecycle videojs-wavesurfer@2.8.0~start: CWD: /home/thijs/projects/videojs-wavesurfer
10 silly lifecycle videojs-wavesurfer@2.8.0~start: Args: [ '-c',
10 silly lifecycle   'npm run build && webpack-dev-server --config ./build-config/webpack.dev.main.js' ]
11 silly lifecycle videojs-wavesurfer@2.8.0~start: Returned: code: 1  signal: null
12 info lifecycle videojs-wavesurfer@2.8.0~start: Failed to exec start script
13 verbose stack Error: videojs-wavesurfer@2.8.0 start: `npm run build && webpack-dev-server --config ./build-config/webpack.dev.main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid videojs-wavesurfer@2.8.0
15 verbose cwd /home/thijs/projects/videojs-wavesurfer
16 verbose Linux 4.4.0-145-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v9.11.2
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error videojs-wavesurfer@2.8.0 start: `npm run build && webpack-dev-server --config ./build-config/webpack.dev.main.js`
22 error Exit status 1
23 error Failed at the videojs-wavesurfer@2.8.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by thijstriemstra** [comment]
the console output is more verbose:

```
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from localhost:8080/dist/
ℹ ｢wds｣: Content not from webpack is served from /home/thijs/projects/videojs-wavesurfer
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/thijs/projects/videojs-wavesurfer/node_modules/get-stdin ENOSPC
    at FSWatcher.start (fs.js:1402:19)
    at Object.fs.watch (fs.js:1428:11)
    at createFsWatchInstance (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:171:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/thijs/projects/videojs-wavesurfer/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:171:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! videojs-wavesurfer@2.8.0 start: `npm run build && webpack-dev-server --config ./build-config/webpack.dev.main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the videojs-wavesurfer@2.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thijs/.npm/_logs/2019-04-08T21_20_37_680Z-debug.log
```

**Comment by thijstriemstra** [comment]
And no, my disk is not full and has 560GB free (`ENOSPC`?)

**Comment by hiroppy** [comment]
Please run this command. 

```sh
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**Comment by thijstriemstra** [comment]
that fixed it (final step in process took a good 15 seconds though). Note i didn't need this workaround with 3.2.1 but if it works, it works. Thanks.

**Comment by tbehunin** [comment]
Thanks @thijstriemstra for your help in recreating this.

@hiroppy I don't have the ability to expose the repo I'm working in since it's behind my company's firewall. Having dev's enter an additional configuration script to modify the kernel on their machines doesn't feel like a good fix.

If there's a way for me to output more verbose logging during the build process, let me know what command I should enter to achieve that in helping debug the issue.

**Comment by hiroppy** [comment]
Sorry but I think it is difficult to resolve using just this log.

**Comment by evilebottnawi** [comment]
@thijstriemstra please open new issue with reproducible test repo and steps

> Hmm, with 3.2.1 it works, upgrading to 3.3.0 causes issues.

In `3.3.0` version `contentBase` now watching recursive (before it was only one depth), so you need more fs watchers now.

**Comment by evilebottnawi** [comment]
@tbehunin without reproducible test repo we never fix problem, sorry we can't fix something in anything

**Comment by evilebottnawi** [comment]
Friendly ping

**Comment by tbehunin** [comment]
@evilebottnawi I'm having difficulty reproducing it with a new app. I'll keep playing with it to see if I can hone down the issue.

**Comment by evilebottnawi** [comment]
Should be fixed, if you faced with this issue, please open new issue and create minimal reproducible test repo, thanks!
