### ISSUE TITLE
v3.3.0 webpack-dev-server --color no longer works when using preset stats

### ISSUE THREAD

**Issue by dvriezen** [webpack/webpack-dev-server#1772]
- Operating System: MacOS Mojave 10.14.3
- Node Version: 8.12.0
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.3.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

This code worked in 3.2.0 but not in 3.3.0
`webpack-dev-server --color --progress --config config/webpack.dev.coffee --mode development`

Potentially relevant information
```js
// webpack.config.js
`stats: 'detailed'
```

### Expected Behavior
Since color is not defined in the pre-defined detailed stats I don't expect it to not be applied.

### For Bugs; How can we reproduce the behavior?
Update to 3.3.0. Colors still work if I downgrade to previous version.

**Comment by hiroppy** [comment]
Yes, it has already been fixed.

**Comment by hiroppy** [comment]
Sorry, no, it was not reflected if passed directly from CLI.

**Comment by hiroppy** [comment]
@evilebottnawi We have already tested the color test.
https://github.com/webpack/webpack-dev-server/blob/028ceee1693c7566ea7ea54048ced23db5409c32/test/CreateConfig.test.js#L489-L499

**Comment by evilebottnawi** [comment]
Maybe it is regression for `stats` and `3.3.0`

**Comment by dvriezen** [comment]
I did a bit more testing and it works if stats isn't defined but breaks whenever it is. Not sure if that helps or not.

**Comment by hiroppy** [comment]
I added `--color` test
