### ISSUE TITLE
Error after upgrade to 3.3.0 - Uncaught SyntaxError: The URL '...' is invalid

### ISSUE THREAD

**Issue by vitexikora** [webpack/webpack-dev-server#1778]
After running the project (start devServer via server.js - below) I always get this message, no matter the port and configuration setup:
```
Uncaught SyntaxError: The URL 'http:/[http//localhost:3000]' is invalid
    at new SockJS (webpack:///./node_modules/sockjs-client/dist/sockjs.js?:678)
    at initSocket (webpack:///(:3000/role/webpack)-dev-server/client/socket.js?:9:10)
```
You can see that the URL is kind of doubled.
After some headache, I localized this problem in webpack-dev-server v3.3.0.
While doing a routine deps upgrade, it got updated from 3.2.1 to 3.3.0 and that introduced this problem. 

- Operating System: Microsoft Windows [Version 10.0.17134.648]
- Node Version: v10.13.0
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: **3.3.0** (NOT in 3.2.1)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
{entry: [
    '@babel/polyfill',
    'webpack-dev-server/client?http://localhost:' + LISTEN_PORT + '/',
    'webpack/hot/dev-server',
    path.join(__dirname, 'src', 'index')
  ]}
```

```js
// server.js
new webpackDevServer(webpack(config), {
  host: 'http://localhost:' + LISTEN_PORT,
  publicPath: config.output.publicPath,
  hot: true,
  inline: true,
  watchOptions: {
    aggregateTimeout: 300,
    ignored: /node_modules/
  },
  historyApiFallback: {
    index: 'index.html'
  },
  headers: {
    'Access-Control-Allow-Origin': '*'
  }
}).listen(LISTEN_PORT, 'localhost', someFunction)
```

### Expected Behavior
No error
### Actual Behavior
Error
### For Bugs; How can we reproduce the behavior?
I do not have the time to prepare a minimum setup, I already lost plenty, but the server.js+webpack.config.js setup could be a good start.

**Comment by evilebottnawi** [comment]
> I do not have the time to prepare a minimum setup, I already lost plenty, but the server.js+webpack.config.js setup could be a good start.

Sorry we can't fix something in anything

**Comment by evilebottnawi** [comment]
Also host should be without `protocols`

**Comment by evilebottnawi** [comment]
https://stackoverflow.com/questions/6725890/location-host-vs-location-hostname-and-cross-browser-compatibility
