### ISSUE TITLE
CORS request issue with hot-reload-endpoint on 3.3.0 and later

### ISSUE THREAD

**Issue by capaj** [webpack/webpack-dev-server#1787]
- Operating System: UBUNTU 18.04
- Node Version: 10
- NPM Version: 6
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.3.1 and 3.3.0

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js

```

### Expected Behavior
there is no CORS issue as with webpack-dev-server : 3.2.1

### Actual Behavior
there is a CORS issue when accessing `http://localhost:3000/sockjs-node/info?t=1554881051089`

```
Access to XMLHttpRequest at 'http://localhost:3000/sockjs-node/info?t=1554881054153' from origin 'http://looopco.loc.cz:3000' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
``` 

### For Bugs; How can we reproduce the behavior?
I am not sure. You probably need to run the actual server on a different domain than just `localhost`.
This bug popped up on our very complex webpack config, with custom subdomains, so I cannot give you a simple repro. Sorry. It surely is a webpack-dev-server bug because there was not other change beside the upgrade of webpack-dev-server.
I will keep testing every new version that comes out(as this product is my job I work on every day) and if It is ever fixed I will come back to this and close it myself.

**Comment by evilebottnawi** [comment]
Second answer https://stackoverflow.com/questions/31602697/webpack-dev-server-cors-issue

**Comment by evilebottnawi** [comment]
If it is nos solve your problem, please create minimum reproducible test repo

**Comment by capaj** [comment]
@evilebottnawi yes this is still an issue with version 3.5.1 that I've tested just now.
I will try to, although it might be quite tricky. Could I optionally just add you to the private repo where the error occurs? It would be trivial for you to see the error there. Just `npm i && npm run fe`

**Comment by karolyi** [comment]
+1 with 3.9.0 here
