### ISSUE TITLE
[3.3.x] window does not exist in service worker context

### ISSUE THREAD

**Issue by frlinw** [webpack/webpack-dev-server#1788]
- Operating System: Windows 10
- Node Version: 10.15.x
- NPM Version: 6.4.x
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.3.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

![image](https://user-images.githubusercontent.com/11896237/55876732-97b6b180-5b98-11e9-8d46-aa70a4e30e88.png)

### Expected Behavior
webpack-dev-server should not use `window` in its generated code

### Actual Behavior
webpack-dev-server use `window`

### For Bugs; How can we reproduce the behavior?
`window` does not exists in every context.
Define an entry point and import it with `importScripts()` in a service worker to experience the issue.

**Comment by hiroppy** [comment]
Please submit a reproducible repo.

**Comment by evilebottnawi** [comment]
Problem in not `webpack-dev-server`, it is part of `bootstrap` code of `webpack` for `browser`, you can use other `target` (`target: node`) https://webpack.js.org/concepts/targets/

**Comment by frlinw** [comment]
`node` or `webworker` don't work either.
`target` is global and can't be configured per entry point.
The build of the service worker script is tightly related to the build of the app (because its main purpose is to cache generated app files) so I can have one webpack config per entry point.
I'll stick on 3.2.1 for a while I guess

**Comment by evilebottnawi** [comment]
@frlinw we doesn't change anything related to `hmr` and your example above, stick `3.2.1` contain bugs and can break your app in future when you will update webpack, please create minimum reproducible test repo

**Comment by frlinw** [comment]
fixed using `globalObject: 'this'`
