### ISSUE TITLE
v3.3.0 - HMR stopped working - React Hot Loader

### ISSUE THREAD

**Issue by shahzaibkhalid** [webpack/webpack-dev-server#1791]
- Operating System: macOS Mojave 10.14.3
- Node Version: 10.14.2
- NPM Version: 6.4.1
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.3.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

Hot Module Replacement using `react-hot-loader` must work.

### Actual Behavior

Hot Module Replacement using `react-hot-loader` broke with `webpack-dev-server` `v3.3.0` but it works if I go back to `v3.2.1`

### For Bugs; How can we reproduce the behavior?

- Clone the repo: https://github.com/shahzaibkhalid/webpack-dev-broken-hmr-example
- Run `yarn` to install dependencies
- Start the development server by running `yarn start`
- Check the version of `webpack-dev-server` and downgrade it to v3.2.1, HMR must work now.

**Comment by evilebottnawi** [comment]
We don't touch something in hmr, not sure problem related to `webpack-dev-server`

**Comment by shahzaibkhalid** [comment]
It's reproducible in the mentioned repo, if I go back to webpack-dev-server `v3.2.1` HMR works like a charm. I connected the dots by comparing lock files of a similar project where HMR is working.

**Comment by evilebottnawi** [comment]
@shahzaibkhalid what i should run to reproducible problem? Please simplify you example with steps

**Comment by evilebottnawi** [comment]
I run `yarn build && yarn serve` and all works good

**Comment by shahzaibkhalid** [comment]
Please run `yarn start` for development server.

**Comment by evilebottnawi** [comment]
What is error you got?

**Comment by shahzaibkhalid** [comment]
There are no errors, but whole page is getting refreshed as soon as I change some code. But if I go back to the previous version (as mentioned in issue), HMR works.

Also updated issue with detailed reproducible steps.

**Comment by evilebottnawi** [comment]
@shahzaibkhalid Why you think it is problem with `react-hot-loader`? You `contentBase` is `process.cwd()` so you watch all changes in `process.cwd()` (include `node_modules`), looks somebody write new files in `node_modules` and you get refresh

**Comment by evilebottnawi** [comment]
You use ` watchContentBase: true,`, but doesn't setup `contentBase`, it is weird

**Comment by shahzaibkhalid** [comment]
Setting `contentBase` as `path.resolve(process.cwd(), 'src')` does not solve the issue. Did you tried downgrading to the mentioned version?

**Comment by evilebottnawi** [comment]
I can't run you reproducible test repo due:
```
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/evilebottnawi/IdeaProjects/webpack-dev-broken-hmr-example/node_modules/@babel/plugin-proposal-class-properties/README.md'
```

Files always random, somebody try to watch `node_modules`

**Comment by evilebottnawi** [comment]
Confirm what problem in `contentBase` because you can open in deps https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1014 and comment

```
/*const watcher = chokidar.watch(watchPath, options);

    watcher.on('change', () => {
      this.sockWrite(this.sockets, 'content-changed');
    });

    this.contentBaseWatchers.push(watcher);*/
```

then run

**Comment by evilebottnawi** [comment]
`watchPath` = `/home/evilebottnawi/IdeaProjects/webpack-dev-broken-hmr-example` (wrong) you need setup `src` as you written above

**Comment by evilebottnawi** [comment]
Example:
```
const serverConfig = {
  open: true,
  contentBase: path.resolve(__dirname, 'src'),
  watchContentBase: true,
  clientLogLevel: 'none',
  hot: true,
  publicPath: '/',
  compress: true,
  overlay: shouldShowOverlay ? overlayConfig : false,
  host,
  port: defaultPort === freePort ? defaultPort: freePort,
  https: isHttps,
  historyApiFallback: {
    disableDotRule: true,
  },
  stats: 'minimal'
};
```

Solve your problem?

**Comment by evilebottnawi** [comment]
Using `path.resolve(process.cwd(), 'src')` is wrong, you need `static` directory, not `src`, in src you store your source code, in `static` you store static files (usually they copied to dist/build directory)

**Comment by evilebottnawi** [comment]
Example `CFA` use `public` directory for this https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/template

**Comment by shahzaibkhalid** [comment]
I got you. My bad. I turned off `watchContentBase` and HMR is working now.

Thanks so much for detailed example. 🙏Closing.
