### ISSUE TITLE
static .swf file type is error in ie10 browser

### ISSUE THREAD

**Issue by zxyRealm** [webpack/webpack-dev-server#1793]
- Operating System: windows 7
- Node Version: 8.11.2
- NPM Version: 5.6.0
- webpack Version: 4.28.4
- webpack-dev-server Version: 3.3.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js

// this is vue-cli3.0 vue.config.js 
module.exports = {
  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  productionSourceMap: false,
  devServer: {
    contentBase: [path.resolve(__dirname, './static')],
    port: '3002',
    proxy: {
      '/api': {
        target: 'http://192.168.11.120',
        changeOrigin: true,
        pathRewrite: {}
      }
    }
  }
}

```

### Expected Behavior

![image](https://user-images.githubusercontent.com/29787620/55945558-9dd28e00-5c7d-11e9-8124-9c05e6f91a80.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/29787620/55945484-77acee00-5c7d-11e9-8148-96d314671a8f.png)

### For Bugs; How can we reproduce the behavior?
ie10 or lower  .swf  file con`t load, static file type is error. It`s normal if in express server

**Comment by evilebottnawi** [comment]
Looks problem in mime package, can you create minimum reproducible test repo?

**Comment by zxyRealm** [comment]
this problem is `contentBase ` info is errror

**Comment by evilebottnawi** [comment]
Can you describe?
