### ISSUE TITLE
"[WDS] Disconnected" loop

### ISSUE THREAD

**Issue by dennispg** [webpack/webpack-dev-server#1796]
- Operating System: Windows 10 - 1809
- Node Version: v8.14.0
- NPM Version: 6.9.0
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.3.1
- Browser version: Chrome 73.0.3683.103 (64-bit)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Should not repeatedly reload the page after displaying [WDS] Disconnected.

### Actual Behavior
Does not strictly happen every single time, sometimes it works. But more often than not, after making a change the hot reload will go into a loop reloading the page and displaying [WDS] Disconnected over and over.

It seems like two "o" sockjs msgs can be received during the same session, possibly when changes are recompiled in succession fast enough? This causes two socket opens, and when the second open request checks the readystate it is already open from the first request and so triggers a [WDS] Disconnect.

### How can we reproduce the behavior?
A reproducible repo is available here:
https://github.com/dennispg/webpack-wds-disconnected-bug

1. run `npm start`, open `https://localhost:9000/` in Chrome
2. find `sockjs.js` in the sources panel
3. add a breakpoint on line 933 which should look like: `this._close(1006, 'Server lost session');`
4. add some random semicolons in `src/index.js` over and over till the breakpoint hits. Try modify/save/modify/save in rapid succession for best results.

**Comment by evilebottnawi** [comment]
Feel free to send a PR with fix

**Comment by dennispg** [comment]
I would love do to exactly that, however I have been unable to track down a proper fix on my own. I have tried, and this was the most I was able to find out. I will continue to research, but I worry that I need assistance to go any further.

I had hoped it would be helpful to provide a reproducible test repo in order to get some assistance at least in finding a solution. If creating a reproducible test repo is a waste of time though, please do let me know.

**Comment by evilebottnawi** [comment]
I had hoped it would be helpful to provide a reproducible test repo in order to get some assistance at least in finding a solution. If creating a reproducible test repo is a waste of time though, please do let me know.

No, reproducible test repo allow to us fix problem very fast, i written `Feel free to send a PR with fix` because now it is weekends and you you want fix this asap you can send a PR. We will fix this anyway.

**Comment by dennispg** [comment]
I completely understand, there is no rush for a fix. I just want to help find the solution, so I shared here. I will continue to research also.

**Comment by funwithtriangles** [comment]
I rolled back to `webpack-dev-server` 3.0.0 and `webpack` 4.20.2 and still experiencing this issue. I'm on Windows 10 (1803).

I'm wondering if it has something to do with having `https` enabled. I don't seem to be experiencing it once I set this option to `false` but this might also be due to the fact my page doesn't get as far without it.

Seems related: https://github.com/webpack/webpack-dev-server/issues/851

**Comment by evilebottnawi** [comment]
@funwithtriangles can you create minimum reproducible test repo, maybe you have other problem, thanks

**Comment by blackswanny** [comment]
have the same issue since updated from 2.x to 3.2 version with the update of webpack to 4.28.4

previously worked config for `devServer`:
```
{
      https: true,
      cert: options.https.cert,
      key: options.https.key
}
```
since in here https://webpack.js.org/configuration/dev-server/
I see the change to nest `cert` and `key` inside of `https` object the next config doesn't work:
```
{
      https: {
        cert: options.https.cert,
        key: options.https.key
      }
 }
```
this hammer also doesn't work:
```
     {
      headers:          { 'Access-Control-Allow-Origin': '*' },
      disableHostCheck: true,
      https: false
    }
```

here there is `ca` prop for `https`, what is this one? Do I need it also?
https://webpack.js.org/configuration/dev-server/

**Comment by evilebottnawi** [comment]
```
 https: {
   ca: 'something',
   cert: options.https.cert,
   key: options.https.key
}
```

https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/createConfig.js#L155

**Comment by blackswanny** [comment]
ok, thanks. I can find in code, just didn't get what it means. Seems it stands for specific `cacert` certificates. However it makes no difference. I rolled back to ` webpack-dev-server@2.11.5 `, `sockjs@0.3.19` and the issue is still there. My chrome is `73.0.3683.103` and Firefox `66.0.3 `. Chrome is still complaining and I have infinite loop of requests, which makes impossible to use dev tools as it is stuck processing those requests. However, Firefox stopped issue with old 2.11.5 version of `webpack-dev-server`. So it might be a mix of newly released Chrome and new version of `sockjs` or `webpack-dev-server@3.x`. Any ideas?

**Comment by evilebottnawi** [comment]
@blackswanny can you create minimum reproducible test repo with 3 version, `webpack-dev-server@2` is deprecated and can doesn't work

**Comment by elesueur** [comment]
I have this issue too, seems to have come along with Chrome 74. I don't think anything else in my environment changed. I see a failure in the first websocket connection (only for certain routes within my app! and the app reloads continuously). The websocket fails to connect with a timeout (error code 1006).

I applied the fix suggested in https://github.com/webpack/webpack-dev-server/issues/851#issuecomment-332345350 to webpack-dev-server, and everything works fine.

I can send a merge request if desired.

**Comment by ZebraFlesh** [comment]
I'm seeing this consistently on both Mac and Windows 10 using Chrome 74, Safari 12.1.1, and Firefox 67. I was able to narrow things down a little: I was upgrading some stale dependencies and saw this error occur, so I restarted the dependency upgrades and was very methodical. This occurred when I jumped from webpack-dev-server 3.2.1 to 3.3.0 (with the corresponding required upgrade of webpack-cli from 3.2.3 to 3.3.2). I'm also extremely far from a minimum reproduction scenario.

My solution for now is to stick with webpack-dev-server 3.2.1 / webpack-cli 3.2.3.

**Comment by evilebottnawi** [comment]
Don't stick version, it can be broken in future, please create minimum reproducible test repo

**Comment by jsg2021** [comment]
If your dev server is behind a proxy, it might be sending requests to the wrong place. I was having a similar issue and solved it with defining [`public`](https://webpack.js.org/configuration/dev-server/#devserverpublic) to be localhost:devserverport

**Comment by blackswanny** [comment]
fyi, I have it with Chrome( latest 74.x version), but I don't have it with Chrome Canary ( 76.x version). So may be something is with my code, but it is fixed in 76.x version of Chrome. Also Firefox and Safari seems to not reproduce it

**Comment by ZebraFlesh** [comment]
I see this consistently with both the release and canary channels of Chrome on Windows 10.

**Comment by evilebottnawi** [comment]
@ZebraFlesh what do you mean?

**Comment by ZebraFlesh** [comment]
I'm saying it's not resolved by Chrome 76 as @blackswanny suggests

**Comment by ZebraFlesh** [comment]
Not easily, no. I've got a privately forked version of this repo: https://github.com/arabold/serverless-react-boilerplate/. It's using [serverless framework with the serverless-offline plugin to exec a webpack-dev-server process](https://github.com/arabold/serverless-react-boilerplate/blob/master/package.json#L6). I'm not even sure where to begin on unraveling all that into something minimal. My suspicion is that offline environment is doing something that is unexpected by WDS.

**Comment by evilebottnawi** [comment]
@ZebraFlesh bad, with reproducible test repo we will fix it very fast

**Comment by dennispg** [comment]
Just in case it was missed.. there has been a minimum reproducible repo available in the OP all this time.

**Comment by ZebraFlesh** [comment]
> @ZebraFlesh bad, with reproducible test repo we will fix it very fast

I understand that. If I thought I could provide a minimal repo I would have already done so. But like I said, my failure case is quite far from minimal. If you think it would help, I’m happy to try and work it up.

**Comment by evilebottnawi** [comment]
@ZebraFlesh can you send not minimal version? Sometimes impossible create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
@ZebraFlesh thanks

**Comment by dennispg** [comment]
@ZebraFlesh out of curiosity, does the repo in the OP also have the same problem in your environment?
https://github.com/dennispg/webpack-wds-disconnected-bug

**Comment by ZebraFlesh** [comment]
@dennispg No, I couldn't make it break using the repo in the OP. I tried on macOS 10.14.5 with node 10.15.3 and Chrome 74.

**Comment by funwithtriangles** [comment]
Just for extra information, I stopped getting this issue but now I'm testing on iOS Safari and it is happening every time.

**Comment by evilebottnawi** [comment]
Only on Safari?

**Comment by funwithtriangles** [comment]
Just tested in Chrome on iOS, same thing happening there

**Comment by evilebottnawi** [comment]
Only iOS? Sorry for many questions

**Comment by funwithtriangles** [comment]
Chrome on Android: ✔️ 
Chrome on iOS: ❌ 
Safari on iOS: ❌

**Comment by funwithtriangles** [comment]
So I have some sort of solution to this problem, which actually seems to be two problems for iOS. Firstly, there was an issue of the page refreshing _really fast_ (https://github.com/webpack/webpack-dev-server/issues/1370). This doesn't seem to be related to WDS but I managed to get past this issue following this advice: https://github.com/webpack/webpack-dev-server/issues/1370#issuecomment-423867493

However this lead me back to the WDS loop issue, which I seem to have solved by setting `inline: false`.

**Comment by blackswanny** [comment]
seems to be related
https://github.com/webpack/webpack-dev-server/issues/1616

**Comment by puru991** [comment]
If on a vps, Just do a `yarn serve --public [your-public-ip-address]`, for eg. `yarn serve --public 83.12.33.24`
If on local, try setting public to either localhost or 127.0.0.1 (Although did not try on local)

**Comment by sajidmansoori12** [comment]
Don't know how...but when I add the property injectClient:false to the devServer. The WDS disconnected stops showing up.

**Comment by nefarioustim** [comment]
This can generally be fixed by defining `public`. For some reason, WDS can't find the right address without it:

```
devServer: {
    https: true,
    port: 8080,
    public: "0.0.0.0:8080"
}
```

**Comment by StevenBarquet** [comment]
> This can generally be fixed by defining `public`. For some reason, WDS can't find the right address without it:
> 
> ```
> devServer: {
>     https: true,
>     port: 8080,
>     public: "0.0.0.0:8080"
> }
> ```

Thanks I modified my config to this and it works:

`devServer: {
    hot: true,
    port: 3000,
    public: 'localhost:3000',
    open: true,
    historyApiFallback: true, // fix cannot get on refresh
    contentBase: path.resolve(__dirname, 'src'),
    disableHostCheck: true // That solved it
  }`

**Comment by alexander-akait** [comment]
We refactor our code and in the next version you will have `client.webSocketURL` so you can setup right hostname/port/etc for proxyed dev server, also `[WDS] Disconnected` very often means you have invalid `publicPath` in webpack v5 we use `auto` (all assets are relative) by default, so it should happens very rare

**Comment by erikmartinessanches** [comment]
I'm getting this error in Chrome version 92.0.4515.107 and webpack-dev-server 3.11.1 created by `npx create-react-app`.
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/4912935/126813009-eb2d5324-807a-4608-8bcd-cbb4f06ad09f.png">

**Comment by alexander-akait** [comment]
it means you have invalid URL for sockjs, what is in your address bar in browser

**Comment by erikmartinessanches** [comment]
> it means you have invalid URL for sockjs, what is in your address bar in browser

http://localhost:3000/

**Comment by alexander-akait** [comment]
But for web socket connection your are use `9090`, so you got this problem, why do you use `3000` port?

**Comment by erikmartinessanches** [comment]
> But for web socket connection your are use `9090`, so you got this problem, why do you use `3000` port? Your URL in address bar should be `http://localhost:9090`

Thanks but I use port 3000 because of this:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/4912935/126815534-5265ac4b-d1a4-40b1-b1c8-922ac805831f.png">

If I use port 9090 I get "Unable to reach page" and only a `crbug/1173575, non-JS module files deprecated.`in the console.

**Comment by alexander-akait** [comment]
Something buggy in CRA... Sorry, I am afraid we can't fix it here, web socket address should be same as in address bar in browser, if you need proxy, you need more options for dev server, also please try `PORT=9090 react-scripts start`

**Comment by erikmartinessanches** [comment]
> Something buggy in CRA... Sorry, I am afraid we can't fix it here, web socket address should be same as in address bar in browser, if you need proxy, you need more options for dev server, also please try `PORT=9090 react-scripts start`

Thanks, I'll open an issue with CRA. `PORT=9090 react-scripts start didn't work for me, at least in the root directory of the app. `PORT=9090 yarn start` did start serving on http://localhost:9090, but with the same error.

**Comment by alexander-akait** [comment]
weird, your repo works fine for me, check your env variables, run `printenv` if you on linux and check you don't have `port` variable or try to `PORT=3000 react-scripts start`

**Comment by erikmartinessanches** [comment]
No `port` variable visible when `printenv`.  `PORT=3000 yarn start` also runs `react-scripts`as I understand it. Still getting the error though. I opened an issue on CRA.
