### ISSUE TITLE
Hot module reloading not working in Firefox but works in Chrome

### ISSUE THREAD

**Issue by daliusd** [webpack/webpack-dev-server#1799]
Because of some changes in Firefox (https://bugzilla.mozilla.org/show_bug.cgi?id=1536843) and change in some product (maybe this) hot reload has stopped working in apps created with create-react-app (https://github.com/facebook/create-react-app/issues/6720) with Firefox. One suspect is this product:

> In the end, I was able to reproduce it and mozregression pointed to a bug 1417463. That bug changed default accept header and further testing showed that it's server side issue. For some reason, server goes mad when "text/html" is missing in the accept header and after few frames it sends some unexpected HTTP response over the websocket connection.

Could somebody looks into this and at least eliminate that problem is in this product?

**Comment by evilebottnawi** [comment]
Here problem https://github.com/sockjs/sockjs-client/issues/474
