### ISSUE TITLE
I run this commond " npm run dev-server" server successfully started and compiled, but when I update the data in console the data doesn't update even i refresh the browser as well..? how to solve this issue?

### ISSUE THREAD

**Issue by ZaffarJamali** [webpack/webpack-dev-server#1813]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions, thanks

**Comment by evilebottnawi** [comment]
Please provide for other people you configuration
