### ISSUE TITLE
Application not found (127.0.0.1:8080)

### ISSUE THREAD

**Issue by jonathanlinat** [webpack/webpack-dev-server#1814]
- Operating System: Microsoft Windows 10
- Node Version: v11.14.0
- NPM Version: 6.7.0
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.3.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require('path')
const TerserPlugin = require('terser-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin')
const HtmlWebPackPlugin = require('html-webpack-plugin')
const CleanWebpackPlugin = require('clean-webpack-plugin')
const webpack = require('webpack')

module.exports = (env, options) => {
  const isProductionMode = (options.mode === 'production')

  const src = path.resolve(__dirname, 'src')
  const dist = path.resolve(__dirname, 'dist')

  let webpackConfig = {
    entry: {
      app: [
        path.resolve(__dirname, `${src}/simulation.js`),
        path.resolve(__dirname, `${src}/simulation.css`),
        path.resolve(__dirname, `${src}/simulation.html`)
      ]
    },
    output: {
      path: path.resolve(__dirname, dist)
    },
    resolve: {
      alias: {
        Modules: path.resolve(__dirname, `${src}/modules`)
      }
    },
    devServer: {
      host: '127.0.0.1',
      open: true,
      hot: true
    },
    plugins: [
      new CleanWebpackPlugin(),
      new MiniCssExtractPlugin(),
      new HtmlWebPackPlugin({ template: `${src}/simulation.html` }),
      new webpack.NamedModulesPlugin(),
      new webpack.HotModuleReplacementPlugin()
    ],
    module: {
      rules: [
        { enforce: 'pre', test: /\.js$/, exclude: /node_modules/, loader: 'eslint-loader' },
        { test: /\.js$/, exclude: /node_modules/, use: { loader: 'babel-loader', options: { babelrc: false } } },
        { test: /\.css$/, use: [ isProductionMode ? MiniCssExtractPlugin.loader : 'style-loader', 'css-loader' ] },
        { test: /\.html$/, use: 'html-loader' }
      ]
    }
  }

  return webpackConfig
}
```

### Expected Behavior

Open a new tab in my default Internet browser without any error.

### Actual Behavior

Webpack doesn't open a new tab on compiling and a window popup appears telling me that the application hasn't been found.

It is still possible to access the localhost manually.

### For Bugs; How can we reproduce the behavior?

Windows 10 + Brave Browser + Open option in true.
This is the repository: https://github.com/jonathanlinat/es6-retrogaming-series-pong

![Capture](https://user-images.githubusercontent.com/14064112/56596295-4f4abb00-65be-11e9-8f6a-3a3cabe72a04.PNG)

**Comment by evilebottnawi** [comment]
You should setup open browser, your os can't have browser

**Comment by evilebottnawi** [comment]
Also you don't need `new webpack.HotModuleReplacementPlugin()` anymore

**Comment by jonathanlinat** [comment]
Well... I reinstalled Brave browser, reassigned it as my default known browser and deleted `new webpack.HotModuleReplacementPlugin()`. That's it. Thanks @evilebottnawi
