### ISSUE TITLE
fs option not supported

### ISSUE THREAD

**Issue by heygrady** [webpack/webpack-dev-server#1818]
https://github.com/webpack/webpack-dev-middleware#fs
https://github.com/webpack/webpack-dev-middleware/releases/tag/v3.6.0
https://github.com/webpack/webpack-dev-server/blob/master/package.json#L56

webpack-dev-middleware added an `fs` option in version 3.6.0. When I try to set that option it fails. I am using webpack-dev-server version 3.3.1 which depends on webpack-dev-middleware version 3.6.2.

```
webpack Dev Server Invalid Options

options should NOT have additional properties
```

Seems like the option would need added here: https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json

**Comment by hiroppy** [comment]
closed via #1819
