### ISSUE TITLE
Variables defined at window object are undefined.

### ISSUE THREAD

**Issue by machacekjan** [webpack/webpack-dev-server#182]
Hi,
I have a problem with `web-dev-server` command and variables at the window object.
I tried define window.mySampleGlobalVariable and then access it from developer tools and it is undefined.

My sample app looks like this:

**app.js**

    window.mySampleGlobalVariable = 'TEST';
    console.log('App is ready');

**index.html**

    <!DOCTYPE HTML>
    <html>

    	<head>
    		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    		<title>Webpack test</title>
    	</head>

    	<body>
    		Webpack test
    		<script src="bundle.js"></script>
    	</body>

    </html>

**webpack.config.js**

    var path = require('path');
    
    module.exports = {
        entry: './app.js',
        output: {
            filename: './bundle.js'
    	},
    	resolve: {
	    	extensions: ['', '.js']
	    }
    };

When I use only `webpack` command everything is working fine. I'm testing it by typing `window.mySampleGlobalVariable` in chrome developer tools and it prints TEST as I expected

**BUT** when I run `webpack-dev-server` command then my window variable is undefined.

**Comment by mcolburn** [comment]
I also have this issue.  Would someone please provide a response.  Thank you!

**Comment by carlsgit** [comment]
same thing. is preventing react dev tools showing & window.innerHeight is incorrect
neither are problems with just webpack

**Comment by 121onto** [comment]
+1

**Comment by jvalen** [comment]
Hi,

I came across with this problem too. I've found two ways to handle it so far.

1. `webpack-dev-server` loads your app in an iframe, by default the console of the developer tools have access to the main context but not the variables inside the iframe (unless you expose them somehow with `webpack`). You can change the context to point to the iframe and access to that data. I tried with [Chrome](http://stackoverflow.com/questions/3275816/debugging-iframes-with-chrome-developer-tools) and [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Working_with_iframes) and works perfectly.

2. The other way is just using `webpack-dev-server` [inline mode](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode). We could run the following command `webpack-dev-server --inline` and check the result at `http://<host>:<port>/<path>` avoiding the iframe issue.

**Comment by SpaceK33z** [comment]
It is not possible for an iframe to pass through these `window` variables, so we can't fix this. @jvalen provided excellent workarounds.
