### ISSUE TITLE
Inline and hot mode via Node JS

### ISSUE THREAD

**Issue by padevone** [webpack/webpack-dev-server#1829]
- Operating System: Ubuntu 16/18
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.28.3
- webpack-dev-server Version: 3.1.14

- [x] This is a **bug**
- [ ] This is a **modification** request

### Demo repo
https://github.com/padevone/webpack-node-cli

### Expected Behavior
Inline and hot mode via Node JS for less and js work

### Actual Behavior
Inline and hot mode via Node JS doesn't work

_use HRM and set it for MiniCssExtractPlugin_

**Comment by evilebottnawi** [comment]
It is not working only for less?

**Comment by padevone** [comment]
@evilebottnawi less and js. Tested every all one by one.

**Comment by evilebottnawi** [comment]
Because you need `webpack-dev-server`, don't add `HotModuleReplacementPlugin`, webpack-dev-server already do this. Don't use `reloadAll` for `MiniCssExtractPlugin` (it is not you case). Don't add this https://github.com/padevone/webpack-node-cli/blob/master/bin/commands/dev.js#L12, because webpack-dev-server do this for you also

**Comment by padevone** [comment]
@evilebottnawi but this doesn't work. 
* In DevTools i don't see sources from webpack
* Use only builded js and css, because after rebuilding changes nothing. I see changes on n proxy http://localhost:8100/webpack-dev-server

Now i see that i saw with version from my repo

**Comment by PerfectionCSGO** [comment]
I may be running into the same issue. 

Operating System: Windows 10

Node Version: v10.15.3

Yarn Version: 1.15.2

webpack Version: 4.30.0

webpack-dev-server Version: 3.3.1

electron: 5.0.0

react-hot-loader: 4.8.4

```
[WDS] 92% - additional asset processing.
client:146 [WDS] 92% - chunk asset optimization.
client:146 [WDS] 93% - after chunk asset optimization.
client:146 [WDS] 93% - asset optimization.
client:146 [WDS] 94% - after asset optimization.
client:146 [WDS] 94% - after seal.
client:146 [WDS] 95% - emitting.
client:146 [WDS] 95% - emitting (HtmlWebpackPlugin).
client:146 [WDS] 98% - after emitting.
client:146 [WDS] 100% - Compilation completed.
client:265 [WDS] App hot update...
```
In my electron console but no new payload is actually served to my electron application.
My commands look like this.

```
    "build:renderer:hot": "webpack-dev-server --progress --hot --config webpack.config.renderer.development",
    "build:main:hot": "webpack --progress --hot --config webpack.config.main.development",
    "serve": "electron .",
    "start": "yarn build:main:hot && npm-run-all --parallel build:renderer:hot serve",
```

and electron entry point looks like this

```
  if (process.env.NODE_ENV !== 'production') {
    window.loadURL(`http://localhost:8080`);
  } else {
    ...
  }
```

It does look like it worked in webpack-dev-server 3.2.1. I'll go and see if I can confirm that it works with an older version.

**Comment by evilebottnawi** [comment]
Why you use inline? It was deprecated and will be removed future version

**Comment by padevone** [comment]
@evilebottnawi

It need for HMR. How i understand it need for travel sources of webpack (build) to runned server. This wrote in [documentation](https://webpack.js.org/configuration/dev-server/#devserverinline).

I saw nothing about deprecated.

**Comment by evilebottnawi** [comment]
@padevone inline not for hmr, and basically doesn't support hmr

**Comment by padevone** [comment]
@evilebottnawi where info about deprecated for inline mode?

**Comment by evilebottnawi** [comment]
@padevone no deprecation right not, but it can be removed in major release https://github.com/webpack/webpack-dev-server/projects/1

**Comment by padevone** [comment]
Okey. Thanks for info.
But do you have any idea how i can fix my issue?
Maybe you can advice existed cli with WDS? Becasuse i don't know some way. I can use express, if it need.

**Comment by evilebottnawi** [comment]
I look this issue tomorrow and give advice(s)

**Comment by evilebottnawi** [comment]
Find problems. Solution:
1. Update deps to latest `mini-css-extract-plugin` and `webpack-dev-server`

2. Remove
```
 plugins: [new webpack.HotModuleReplacementPlugin({
    multiStep: true,
  })],
```

webpack-dev-server automatically mount this plugin when you setup hot

3. Set `publicPath: '/'` (or other value what you want in `webpack.common.js`), don't use empty

4. Fix path to assets (based on above value) in index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="./styles.css">
</head>
<body>
  <h1>Test</h1>

  <script src="./scripts.js"></script>
</body>
</html>
```

5. New dev command.
```
const path = require('path');
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');

var config = require("../configs/webpack.dev.js");

const serve = (srcPath) => {
  config.entry['styles'] = path.resolve(srcPath, './src/styles/index.less');
  config.entry['scripts'] = path.resolve(srcPath, './src/js/index.js');

  var compiler = webpack(config);
  var server = new WebpackDevServer(compiler, {
    contentBase: path.resolve(srcPath, './public'),
    historyApiFallback: true,
    hot: true,
    host: 'localhost',
    port: 8100,
    // You should setup here as above pr don't use this option
    publicPath: '/',
    proxy: {
      '*': {
        target: 'http://localhost:8090/',
        secure: false
      }
    }
  },);
  server.listen(8100);
}

module.exports = serve;
```

You can't use `inline` option (it will be always true in next major). 

I found:

```
config.entry[path.resolve(srcPath, './public/dist/styles/index')] = path.resolve(srcPath, './src/styles/index.less');
  config.entry[path.resolve(srcPath, './public/dist/js/index')] = path.resolve(srcPath, './src/js/index.js');
```

It is invalid. **Please use `publicPath` option instead this.**

6. Change something in `src/js/index.js` and you can see what page was refreshed.

I don't know why you use this difficult setup for all this thing. Also i strongly recommended don't use own boilerplate because it is require deeply knowledge.

Feel free to feedback

**Comment by padevone** [comment]
@evilebottnawi thanks!

It's worked for me. Page doesn't refresh after change, but it's not important.
