### ISSUE TITLE
Remove Sock injection when options.hot is false?

### ISSUE THREAD

**Issue by plauclair** [webpack/webpack-dev-server#1831]
- Operating System: macOS 10.14.4
- Node Version: 10.15.0
- NPM Version: 6.9.0
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.3.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
const serverOptions = { hot: false };
```

### Expected Behavior

When setting hot to false, socket is still added as a dependency. Maybe I understand wrong, but shouldn't dev server _only_ serve when `options.hot` is false?

### Actual Behavior

Current code always injects Socket dependency even if hot is disabled. Currently this can be achieved through `options.inline = false` but that seems to be something completely different.

https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L21

### For Features; What is the motivation and/or use-case for the feature?

We use dev server to serve files in an environment that does not support web sockets. Having the socks module crashes the process even when hot is false.

**Comment by evilebottnawi** [comment]
hot !== sockjs, we use sockjs for getting new assets, maybe we can add option `sockjs: true | false`, PR welcome

**Comment by plauclair** [comment]
@evilebottnawi would gladly submit a PR. Anything special that comes to mind that would need to be taken into account?

**Comment by evilebottnawi** [comment]
I think no

**Comment by yordis** [comment]
> hot !== sockjs, we use sockjs for getting new assets,

@evilebottnawi would you mind to mind to explain what do you mean?

Also, the issue I am facing is that I am the socket client is using `window.location.{hostname, port}` I believe and I am including my JavaScript in a second server.

Rails Server: `http://localhost:3000`
Webpack Dev Server: `http://localhost:5000`

Because of this, I keep getting errors

```
sockjs.js:1793 GET http://192.168.141.56:3000/sockjs-node/info?t=1556570647605 net::ERR_CONNECTION_REFUSED
```

Because my dev-server is not running in `3000`.

I think we should take some extra configs to be able to change the `hostname` and the `port`.

**Comment by evilebottnawi** [comment]
We should not add client when hot is false, because it is doesn't have sense

**Comment by evilebottnawi** [comment]
@plauclair i was wrong, we should not include client when `hot` and `liveReload` is false

**Comment by plauclair** [comment]
Makes sense, we have an issue open here, I'll try to squeeze in something this week. This makes it much easier to go about it.

**Comment by Simon-Tang** [comment]
Thanks for the updated PR (#2601). I think my use case would depend on this change going into the next release.

I'm splitting a part of my code into a bundle that is loaded client-side using [`CSS.paintWorklet.addModule('./paintlet.bundle.js')`](https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet#Load_a_PaintWorklet). Both the SockJS and WebSocket transport modes expect to have a global window object, however a [PaintWorklet](https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet) cannot access any.

Current workaround is to not use webpack-dev-server, although I would still need to serve my local assets under localhost in a separate process to prevent CORS issues with `CSS.paintWorklet.addModule`.

**Comment by evilebottnawi** [comment]
Fixed for v4
