### ISSUE TITLE
npm install fails when webpack-dev-server is added

### ISSUE THREAD

**Issue by teetotum** [webpack/webpack-dev-server#1832]
- Operating System: Windows 10
- Node Version: v10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.3.1

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// excerpt from package.json
"devDependencies": {
        "webpack": "4",
        "webpack-cli": "*",
        "clean-webpack-plugin": "*",
        "copy-webpack-plugin": "*",
        "babel-loader": "*",
        "@babel/core": "*",
        "@babel/preset-env": "*",
        "mini-css-extract-plugin": "*",
        "node-sass": "*",
        "sass-loader": "*",
        "css-loader": "*",
        "handlebars": "*",
        "handlebars-loader": "*",
        "html-webpack-plugin": "*",
        "file-loader": "*",
        "zip-webpack-plugin": "*",
        "webpack-dev-server": "*"
    },
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
I expect npm install to run to completion without errors.

### Actual Behavior
When I add webpack-dev-server (the last entry in my devDependencies) the npm install will run into an error:
npm ERR! Unexpected end of JSON input while parsing near '...:"^6.0.8","tape":"^4.'
### For Bugs; How can we reproduce the behavior?
The bug should be reproducible with an empty folder, drop a package.json into it, add the devDependencies from above and run npm install

**Comment by evilebottnawi** [comment]
You have broken package.json, bot related to project

**Comment by teetotum** [comment]
nope, the package.json is fine

**Comment by evilebottnawi** [comment]
All problem related to npm please open in npm repository/bug tracker, thanks

**Comment by teetotum** [comment]
Seems like it was corrupted files in the npm cache.
npm cache clean --force
solved it for me.
Found at [npm/npm#19072](https://github.com/npm/npm/issues/19072#issuecomment-345555468)
