### ISSUE TITLE
Fail on start up if devServer.port is set and port is in use

### ISSUE THREAD

**Issue by Blanen** [webpack/webpack-dev-server#1836]
- Operating System: Windows 10 latest
- Node Version: 10.13.0
- NPM Version: 6.6.0
- webpack Version: >=4 < 4.29, I don't know the actual version. It's run via vue-cli
- webpack-dev-server Version: I don't know the actual version. It's run via vue-cli

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

I would like running the devServer to fail with a port-in-use error when the set devServer.port is in use. 

### Actual Behavior

If the port is in use, webpack-devserver increments it by 1 and tries that.

### For Features; What is the motivation and/or use-case for the feature?
1. It's just plainly weird behavior.

2.  Many dev envs use CORS. If webpack-devserver chooses another port then it can just break all communication to an API.

3. If you are unfamiliar with this behavior it can lead to a bit of wasted time.

**Comment by evilebottnawi** [comment]
Use `DEFAULT_PORT_RETRY=0` https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L119, it is not weird, it is DX
