### ISSUE TITLE
Let "open" and "openPage" open a different url then bound one

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack-dev-server#1843]
This is a **modification** request.

Scenario: you are developing a webapp on your desktop but you need to access it from from your smartphone.

This imply having the webpack-dev-server to bind to 0.0.0.0 (otherwise dev-server will not serve dev.mydomain.com resolved to desktop from the smartphone with custom DNS).

When firing dev-server with open=true, the url opened is "https://0.0.0.0" which ends up in a "certificate invalid page".

I currently see no option to open a custom url (i.e: https://dev.mydomain.com) which results in the correct opened page.

Suggestion: maybe `openPage` could stop prefixing `host` if given url is an absolute one.

i.e: 
```
openPage: 'https://dev.mydomain.com', => opens https://dev.mydomain.com
openPage: '/home', => opens HOST + /home
```

**Comment by evilebottnawi** [comment]
hm, can you provide minimum reproducible test repo with problem?

**Comment by msegers** [comment]
I was actually also hoping for some more options with the openPage prop.

We serve our build through a separate proxy (outside webpack). say dev server servers on port 8080, but we actually browse our application on 8081. with openPage I cannot specify: `https:/localhost:8081/mypage` as it will open `https://localhost:8080/httpss:/localhost:8081/mypage`

**Comment by evilebottnawi** [comment]
@msegers Can you create minimum reproducible test repo with? Looks like it is bug
