### ISSUE TITLE
dev server permanently reloads d.ts files from modules folder causing 60% CPU and more on a project with large libs

### ISSUE THREAD

**Issue by harrybin** [webpack/webpack-dev-server#1846]
[webpack-dev-server-test.zip](https://github.com/webpack/webpack-dev-server/files/3148564/webpack-dev-server-test.zip)

- Operating System: Win10
- Node Version: 12.1 (also tried 10.15.3)
- NPM Version: 6.9.0
- webpack Version: 4.29.6
- webpack-dev-server Version: 3.2.1

- [x] This is a **bug**
- [ ] ~~This is a **modification** request~~

```js
// webpackDevServer.config.js
...
 watchOptions: {
      ignored: ignoredFiles(paths.appSrc), // also tried /node_modules/
    },
...
```

```json
// tsconfig.json
{
  "compilerOptions": {
    ...
    "skipLibCheck": true
  },
  "exclude": ["node_modules", "build", "scripts", "acceptance-tests", "webpack", "jest", "config", "scripts", "src/setupTests.ts"],
  "types": ["typePatches"]
}
```

### Actual Behavior
the dev server always reads all *.d.ts files in node_modules folder:
![image](https://user-images.githubusercontent.com/15869006/57233920-e59bc980-701f-11e9-9acf-494f7b05e390.png)

if you have a project with with many and/or large modules (e.g. add @material-ui/core and @material-ui/icons) this causes more than 60% CPU on a quad core i5 processor all over all four CPUs.

### Expected Behavior
when the node_modules is set to be ignored, it should be ignored.

### For Bugs; How can we reproduce the behavior?
create an hello world project with typescript support using `create-react-app my-app --typescript` and add a proper tsconfig.json or use the project attached:
npm i
npm start

use a tool like "procmon" to show filesystem access for the node process.

see also: https://github.com/webpack/webpack/issues/9085

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by harrybin** [comment]
the attached project is a hello work project create with `create-react-app my-app --typescript`and added a tsconfig.json

**Comment by evilebottnawi** [comment]
I don't see attached project

**Comment by harrybin** [comment]
sorry, it was 7zip instead of zip--> readded

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by evilebottnawi** [comment]
Please open issue in CRA, problem not related to `webpack-dev-server`, we don't read `ts` files. Only place where we can watch files (include `ts`) is `contentBase`. But in your configuration `contentBase: paths.appPublic` so we don't watch `node_modules`. I think one of plugins/loaders do this.
