### ISSUE TITLE
v3.3.0 is breaking create-react-app's custom webpackHotDevClient

### ISSUE THREAD

**Issue by cvle** [webpack/webpack-dev-server#1851]
`create-react-app` and ejected projects use a custom `webpackHotDevClient`. This PR https://github.com/webpack/webpack-dev-server/pull/1738 prevent those users from being able to upgrade to `3.3.0` because the default client is always injected.

Another related issue is that I am also using the `Node API` to have better control where to add the _inline entries_ and where not to. For example I only have _HMR_ enabled inside an iframe and it works great, but `3.3.0` is breaking my _HMR_ setup.

Can we maybe hide the automatic injection of the inline entires behind a flag or the other way around, prevent the automatic injection using a flag?

**Comment by evilebottnawi** [comment]
Why issue template was ignored, it is really difficult to do this?

**Comment by cvle** [comment]
Apologies, will follow the template!

**Comment by evilebottnawi** [comment]
@cvle feel free to open new issue with reproducible test repo, thanks
