### ISSUE TITLE
writeToDisk: true

### ISSUE THREAD

**Issue by davidgithub1980** [webpack/webpack-dev-server#1852]
Hi. There is a new option:

`writeToDisk: true`

... but I wonder where exactly on the disk are the bundles saved? There is only the _true_ option without specifying the destination of the bundle on the disk.

Thx in advance for clearance.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions.

Your `output.path` is place where saved
