### ISSUE TITLE
live reloading is not working for me

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack-dev-server#186]
I'm using webpack `1.9.9` and webpack-dev-server `1.9.0` and the live reloading is not working.  I've been working on the backend for some months and last I had it working was quite a while ago back when it was using socket.io < 1.0 .  It just doesn't seem to be live reloading.  I can access the javascript at `http://localhost:8091/webpack-dev-server.js`.

**Comment by SpaceK33z** [comment]
Do you still have this issue? We've switched from socket.io to sock.js since.

**Comment by dschissler** [comment]
I haven't had it working for a very long time but I recently did a lot of work to it and I still don't have it working because I am now running the dev server on a VM with a fake domain name.  I think that this might be a known issue with proxies but I haven't looked into it much.  Should this be closed?

**Comment by SpaceK33z** [comment]
When using a VM, you'll probably need to use `--watch-poll` to let it pick up changes. Closing for now, if you have a specific issue let me know.
