### ISSUE TITLE
Since 3.3.0 sockjs is injected unconditionally

### ISSUE THREAD

**Issue by klimashkin** [webpack/webpack-dev-server#1867]
- Operating System: MacOS
- Node Version: 12.2.0
- NPM Version: 6.9.0
- webpack Version: 4.31.0
- webpack-dev-server Version: 3.3.1

- [X] This is a **bug**
- [ ] This is a **modification** request

Since 3.3.1 I've started suddenly see a waterfall of failed `https://localhost:8443/sockjs-node/info?t=X` requests (even with turned off hmr)
Seems like wds has started using them for something (I could not find for what).

But in my case they all fail because I have several webpack instances on different ports behind the proxy for serving different applications (different babel compilation targets, etc).
I can do hmr in that case by adding custom client location:
`webpack-dev-server/client?${protocol}://0.0.0.0:3000/sockjs-node-${port}`
And then, based on path `sockjs-node-${port}`, and using `http-proxy-middleware` I would navigate a request to the right webpack instance:
```javascript
app.use(proxyMiddleware(`/sockjs-node-${port}`, {
  target,
  ws: true,
  pathRewrite: path => path.replace(`/sockjs-node-${port}`, '/sockjs-node'),
  ...proxyWebpackOptions,
}));
```

But the new sockjs connection (3.3.0+), that is not used for `hmr`, doesn't know about that, and fails with 404 status, infinitely trying to connect, clogging up the devtool's network and console panels.
I could not find any information about those new connections, neither the way to configure them behind the proxy.

**Comment by evilebottnawi** [comment]
Already fixed in master, also we added `sockHost`, `sockPort` and `sockPath` for complex use cases, release will be in near time
