### ISSUE TITLE
Serving large assets is slow

### ISSUE THREAD

**Issue by npirotte** [webpack/webpack-dev-server#1878]
- Operating System: OS X
- Node Version: 10.8.0
- NPM Version: 6.8.0
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.10.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Working on a pretty large codebase, with wds 3.1.10 loading of the large assets was fine (few seconds)

### Actual Behavior
After upgrading to 3.10.1 loading of large assets can take more than a minute

**Comment by evilebottnawi** [comment]
Sorry, but we can't help you without minimum reproducible test repo, please provide example and we reopen issue. There are a lot of places where you can to lose time starting with network/environment and ending your setup.

**Comment by evilebottnawi** [comment]
Just note, we recently had a similar problem and problem was in browser extension

**Comment by npirotte** [comment]
Our repo is hosted on a private bitbucket instance, so it's hard for me to reproduce.

I set compress to false and it seems to be way better now, not maybe not an issue in webpack dev server config itself.

Thanks for responding quickly anyway 👍

**Comment by evilebottnawi** [comment]
@npirotte In any case, I would advise you do profiling and search what is wrong, maybe something wrong in deps/setup and in future it can break other place
