### ISSUE TITLE
Parenthesis in root or any parent directory name breaks live reload.

### ISSUE THREAD

**Issue by spoeken** [webpack/webpack-dev-server#188]
Parenthesis in root or any parent directory name breaks live reloading. No errors in either consoles.

**Comment by spoeken** [comment]
Can anyone reproduce this to make sure its not just me. Simply rename the root folder of your project to something with parenthesis i.e. "myProject (test)".

**Comment by Savageman** [comment]
Can confirm, had the same problem. Spaces in path are fine. Parenthesis are not.

**Comment by spoeken** [comment]
I tried to simply escape options.contentBase in Server.js, no luck.

    options.contentBase = options.contentBase.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");

**Comment by SpaceK33z** [comment]
Just verified, it still happens. I also tested if running `webpack` works, but that doesn't work either. This means that it is a problem in `webpack`, not `webpack-dev-server`. Could you make a ticket over there (if there isn't one already)?

**Comment by SpaceK33z** [comment]
For future reference, this is probably getting fixed with https://github.com/paulmillr/chokidar/pull/535.
