### ISSUE TITLE
wds cannot hot reload after upgrading from 3.2.1 to 3.4.0

### ISSUE THREAD

**Issue by endiliey** [webpack/webpack-dev-server#1897]
- Operating System: WSL
- Node Version: 12.2.0
- NPM Version: 6.9.0
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.4.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Description

After upgrading my webpack-dev-server dependency to 3.4.0 from 3.2.1, the hot reload stopped working although there is no change in code. See gif below and steps to reproduce

### Expected Behavior

Hot reload was working in 3.2.1
![3 2 1](https://user-images.githubusercontent.com/17883920/57935410-52527600-78f4-11e9-9342-8341b5e195a2.gif)

### Actual Behavior

![hmr not working](https://user-images.githubusercontent.com/17883920/57935765-25529300-78f5-11e9-8af8-70b5827e02a6.gif)

### For Bugs; How can we reproduce the behavior?

My webpack.config.js is constructed dynamically and we run webpack through NodeJS API.
You can try the repo here:

https://github.com/facebook/Docusaurus/

Run install (we use yarn workspaces and monorepo)
```bash
yarn // install at root
```

Run the website
```bash
cd website
yarn start
```

Go to http://localhost:3000/docs/introduction
Edit file in `website/docs/introduction.md` and make changes. It should hot reload

Upgrade `webpack-dev-server` to `3.4.0` for `packages/docusaurus/package.json` and yarn again at project root.

Run the website again
```bash
cd website
yarn start
```

Notice that it is not able to hot reload now. It's always live reload

**Comment by evilebottnawi** [comment]
Thanks for issue, regression

**Comment by endiliey** [comment]
@evilebottnawi Thanks for the fast reply. It seems that it's happening for wds v3.3.1 too.

I suspect 3.30 or 3.3.1 caused the regression. Hope it helps. Let me know if you need more info ❤️

**Comment by hiroppy** [comment]
maybe related https://github.com/webpack/webpack-dev-server/pull/1889

**Comment by evilebottnawi** [comment]
Yes related, we need search way how testing client

**Comment by hiroppy** [comment]
@endiliey hmm... I couldn't meet this bug in facebook/Docusaurus...

**Comment by endiliey** [comment]
@hiroppy facebook/Docusaurus was fine. Did you upgrade to 3.4.0 and then try it ? After the upgrade it broke

**Comment by hiroppy** [comment]
yeah, I updated webpack-dev-server@3.4.0...

**Comment by endiliey** [comment]
Ok that's super weird. 

@hiroppy can you try this branch ? https://github.com/facebook/Docusaurus/tree/wds-3.4.0
Don't forget to run install again at root folder with `yarn`

Could it be WSL issue (?) It was working fine in 3.2.1 though >.<
![3 4 0](https://user-images.githubusercontent.com/17883920/57941226-f80be200-7900-11e9-86e7-d03c472f532b.gif)

**Comment by evilebottnawi** [comment]
@endiliey hm, let's try fix:
- go to `node_modules/webpack-dev-server/client/index.js`
- Find `reloadApp` function
- Change
```
if (_hot) {
    log.info('[WDS] App hot update...'); // eslint-disable-next-line global-require

    var hotEmitter = require('webpack/hot/emitter');

    hotEmitter.emit('webpackHotUpdate', currentHash);

    if (typeof self !== 'undefined' && self.window) {
      // broadcast update to window
      self.postMessage("webpackHotUpdate".concat(currentHash), '*');
    }
  } // allow refreshing the page only if liveReload isn't disabled


  if (_liveReload) {
    var rootWindow = self; // use parent window for reload (in case we're in an iframe with no valid src)

    var intervalId = self.setInterval(function () {
      if (rootWindow.location.protocol !== 'about:') {
        // reload immediately if protocol is valid
        applyReload(rootWindow, intervalId);
      } else {
        rootWindow = rootWindow.parent;

        if (rootWindow.parent === rootWindow) {
          // if parent equals current window we've reached the root which would continue forever, so trigger a reload anyways
          applyReload(rootWindow, intervalId);
        }
      }
    });
  }
```

to 
```
if (_hot) {
    log.info('[WDS] App hot update...'); // eslint-disable-next-line global-require

    var hotEmitter = require('webpack/hot/emitter');

    hotEmitter.emit('webpackHotUpdate', currentHash);

    if (typeof self !== 'undefined' && self.window) {
      // broadcast update to window
      self.postMessage("webpackHotUpdate".concat(currentHash), '*');
    }
  } else if (_liveReload) {
    var rootWindow = self; // use parent window for reload (in case we're in an iframe with no valid src)

    var intervalId = self.setInterval(function () {
      if (rootWindow.location.protocol !== 'about:') {
        // reload immediately if protocol is valid
        applyReload(rootWindow, intervalId);
      } else {
        rootWindow = rootWindow.parent;

        if (rootWindow.parent === rootWindow) {
          // if parent equals current window we've reached the root which would continue forever, so trigger a reload anyways
          applyReload(rootWindow, intervalId);
        }
      }
    });
  }
```

**Comment by hiroppy** [comment]
@endiliey Thank you. I met this issue.😇

**Comment by endiliey** [comment]
It worked after I applied your patch @evilebottnawi 😄 seems that the liveReload overwrite the hot :|

![worked like a charm](https://user-images.githubusercontent.com/17883920/57941640-10303100-7902-11e9-85c4-b09e101aeab3.gif)

**Comment by hiroppy** [comment]
@endiliey Thank you for confirming. We'll fix and release a patch version as soon as possible.

**Comment by endiliey** [comment]
Sure thing. Thanks a lot for the fast response. Awesome 🎉  

By the way I've also verified that it still fall backs to livereload if hot reload is not working.

Did it by removing "accept the updated module" function like
```js
if (module.hot) {
    module.hot.accept(.....) {
   // some code
}
```

**Comment by evilebottnawi** [comment]
@endiliey hm, fix above solve problem?

**Comment by endiliey** [comment]
@evilebottnawi yes it worked. See the gif above. It works now

**Comment by iMoses** [comment]
I just updated from 3.3.0 to 3.4.1 and hot reload stopped working completely. Seems that the websockets aren't even trying to establish a connection. Could it be related or is it a different issue?

**Comment by endiliey** [comment]
I think it might be different issue. This issue was about livereload taking precedence against hot reload
