### ISSUE TITLE
npm run test failing

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#1905]
- Operating System: Windows 7
- Node Version: 8.9.4
- NPM Version: 6.4.1
- webpack Version: 4.31.0
- webpack-dev-server Version: 3.4.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

do `npm run test`

### Expected Behavior

Tests should run

### Actual Behavior

The following relevant output:

```
> npm-run-all -l -p 'lint:**'

ERROR: Task not found: "'lint:**'"
```

### For Bugs; How can we reproduce the behavior?

Explained above

**Comment by hiroppy** [comment]
It does not occur. Check local node_modules and your git.

```
> webpack-dev-server@3.4.1 lint /Users/webpack/webpack-dev-server
> npm-run-all -l -p 'lint:**'

[lint:prettier] 
[lint:prettier] > webpack-dev-server@3.4.1 lint:prettier /Users/webpack/webpack-dev-server
[lint:prettier] > prettier '{**/*,*}.{js,json,md,yml,css}' --list-different
[lint:prettier] 
[lint:js      ] 
[lint:js      ] > webpack-dev-server@3.4.1 lint:js /Users/webpack/webpack-dev-server
[lint:js      ] > eslint . --cache
[lint:js      ] 
[lint:js      ] (node:67025) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "webpack")
```

**Comment by hiroppy** [comment]
Or you can change `lint:**` or `"lint:**"` if windows occurs this issue.

**Comment by Loonride** [comment]
Yes that seems to be the problem because of Windows. Still getting errors after I change that in the few `package.json` instances, likely also caused by Windows

**Comment by hiroppy** [comment]
Did you try the following?

```
"lint": "npm-run-all -l -p lint:**",
"lint": "npm-run-all -l -p \"lint:**\"",
```

**Comment by Loonride** [comment]
`npm-run-all` works after making that change. I made a similar change here:

`
"lint:prettier": "prettier {**/*,*}.{js,json,md,yml,css} --list-different"
` 

I got this (possibly a problem with `prettier`):

```
[lint:prettier] test\Validation.test.js
[lint:prettier] npm ERR! code ELIFECYCLE
[lint:prettier] npm ERR! errno 1
[lint:prettier] npm ERR! webpack-dev-server@3.4.1 lint:prettier: `prettier {**/*,*}.{js,json,md,yml,css} --list-different`
[lint:prettier] npm ERR! Exit status 1
[lint:prettier] npm ERR!
[lint:prettier] npm ERR! Failed at the webpack-dev-server@3.4.1 lint:prettier script.
[lint:prettier] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[lint:prettier]
[lint:prettier] npm ERR! A complete log of this run can be found in:
[lint:prettier] npm ERR!     C:\Users\student\AppData\Roaming\npm-cache\_logs\2019-05-17T21_29_19_918Z-debug.log
ERROR: "lint:prettier" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-dev-server@3.4.1 lint: `npm-run-all -l -p lint:**`
```

**Comment by hiroppy** [comment]
I think you should rewrite it as follows.

```
 "lint:prettier": "prettier \"{**/*,*}.{js,json,md,yml,css}\" --list-different",
```

**Comment by Loonride** [comment]
Yes I tried that too, no luck. I will take a closer look later and let you know what I find.

**Comment by Loonride** [comment]
@hiroppy `--list-different` is causing Exit status 1 from `lint:prettier` (which is expected behavior: https://prettier.io/docs/en/cli.html#list-different). Is this behavior we want? If not, the simple solution is to have:
```
"lint:prettier": "prettier \"{**/*,*}.{js,json,md,yml,css}\" --list-different || exit 0"
```

Either way, I think quotes should be switched to the `\"` style.

**Comment by hiroppy** [comment]
The current behavior of master in my local is below.

```
> prettier '{**/*,*}.{js,json,md,yml,css}' --list-different

npm run lint:prettier  7.52s user 1.55s system 104% cpu 8.666 total
```

Exit status is 0.


> Either way, I think quotes should be switched to the \" style.

I agree with you.

**Comment by evilebottnawi** [comment]
Peoblem still exists? I can't reproduce

**Comment by Loonride** [comment]
The problem was with my CRLF line endings on Windows. I'll make a PR for the `package.json` quote fix but otherwise it's my local problem.
