### ISSUE TITLE
the lateset version looks like has an error

### ISSUE THREAD

**Issue by zhangyuang** [webpack/webpack-dev-server#1910]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version: 3.4.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```
webpack-dev-server --port 8000 --hot --config ./build/webpack.config.client.js

### Expected Behavior

use hmr, and when i change the code ,the browser need not reload

### Actual Behavior

the console prompt Live Reloading enabled.and the browser reload when i change the code, if i use old version, it can work correctly
![image](https://user-images.githubusercontent.com/17424434/58066696-038b3180-7bbd-11e9-8707-d28325f2f9e7.png)

**Comment by evilebottnawi** [comment]
Please update webpack-dev-server to latest version, you still use old version(3.4.0), maybe you have lock file, you need update this file too

**Comment by evilebottnawi** [comment]
If it is not help, please create minimum reproducible test repo
