### ISSUE TITLE
protocoll-agnostic "public" option no longer possible

### ISSUE THREAD

**Issue by Connum** [webpack/webpack-dev-server#1919]
- Operating System: Windows 10
- Node Version: 8.11.1
- NPM Version: 6.4.1
- webpack Version: 4.32.2
- webpack-dev-server Version: 3.4.1

- [X] This is a **bug**
- [ ] This is a **modification** request
---
**I ran into a problem when updating from `3.2.1` to `3.4.1`, receiving the error mentioned below, without making any change to the webpack config. I believe this could be related to #1743 and the fix that was made in #1750.**

### Code

```js
// webpack.config.js
[...]
    devServer: {
      host: '0.0.0.0',
      https: true,
      port: 8088,
      contentBase: false,
      hot: true,
      headers: {
        'Access-Control-Allow-Origin': '*'
      },
      public: '//devs-server:8048/sockjs-node' // <= this was working in 3.2.1
    }
[...]
```
It's working when changing the `public` option to
```js
      public: 'https://devs-server:8088/sockjs-node'
```

### Expected Behavior
Protocoll-agnostic notation for the `public` option should work, like it did in 3.2.1.
(Before anyone asks: I need to specificly set that option in order for HMR to work in my setup, but I would like to have it work for http and https connections, without causing a self-signed certificate error when requested via http)

### Actual Behavior
Without a protocoll, I can see the following error in the browser console (though there are no errors in the terminal where webpack is running):
```
The URL 'http:/sockjs-node' is invalid
```

### For Bugs; How can we reproduce the behavior?
Explicitly set the `public` option, but without a protocol in the URL.

**Comment by evilebottnawi** [comment]
Please use `sockPath`, `sockPort` or `sockHost` to this, it was internal bug and it is invalid behaviour

**Comment by Connum** [comment]
Thanks for the super-fast reply!
For anyone encountering this issue, this is how my `devServer` looks like in the `webpack.config.js` now:

```
[...]
    devServer: {
      host: '0.0.0.0',
      https: true,
      port: 8088,
      contentBase: false,
      hot: true,
      headers: {
        'Access-Control-Allow-Origin': '*'
      },
      sockHost: 'devs-server',
      sockPort: 8048
    }
[...]
```

Works like a charm!

**Comment by evilebottnawi** [comment]
Yes, right solution, it was buggy on our side so you code works in previous versions, but after fix it you can face with problem, we can't solve other main problems without break this invalid case
