### ISSUE TITLE
Mixed content warnings over https

### ISSUE THREAD

**Issue by necolas** [webpack/webpack-dev-server#192]
I've set `https` to `true` in the dev server options, but I get mixed content warnings for the socket.io polling script.

```
Mixed Content: The page at 'https://localhost:4445/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4445/socket.io/?EIO=3&transport=polling&t=1433463024226-0'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by necolas** [comment]
Sorry this was my fault – didn't change the protocol for the client script.

**Comment by khowling** [comment]
Really happy to see https support, but I have same issue

**Comment by iansinnott** [comment]
If anyone else runs into this issue, you may want to check your `webpack.config.js` file and make sure you're not using HTTP (without the S) anywhere in your config. This was a problem I ran into where I had set `https: true` in the webpack dev server config, but my actual webpack config file was still passing a plain `http` URL. This caused the dev-server to work but hot reloads were failing.

When in doubt `grep` your whole project for "http" and you might find that you have a non-SSL address hardcoded somewhere you wouldn't expect.

**Comment by cmfoula** [comment]
can it have effect on app performance?
