### ISSUE TITLE
Support `inline` option via Node.js API

### ISSUE THREAD

**Issue by necolas** [webpack/webpack-dev-server#193]
It is currently supported in the CLI but not the Node API

**Comment by leecade** [comment]
+1 very confused for me

**Comment by crenwick** [comment]
Is there a good workaround for this? I have been trying to get webpack-dev-server to run through a proxy to a node server like so:

```javascript
  // 'ip' and 'port' are defined above
  var devClient = [require.resolve('./node_modules/webpack-dev-server/client/') + '?http://' + ip.address() + ':8080'];
  devClient.push('webpack/hot/dev-server');
  config.entry = devClient.concat(config.entry);

  new WebpackDevServer(webpack(config), {
    devtool: 'eval-source',
    stats: { colors: true },
    progress: true,
    hot: true,
    inline: true,
    historyApiFallback: true,
    proxy: {
      '*': 'http://' + ip.address() + ':' + port,
      'host': 'http://' + ip.address() + ':' + port,
    },
  }).listen(8080, ip.address(), function(err) {
    if(err) throw err;
    console.log('http://' + ip.address() + ':8080' + '/webpack-dev-server/');
    console.log('webpack result is served from ');
  });
```

And I keep getting weird errors that are not mapped correctly. Also, very related to https://github.com/webpack/webpack-dev-server/issues/256

**Comment by vegetableman** [comment]
This was brain damage, since, the api for the cli vs node is different.

**Comment by SpaceK33z** [comment]
Closing, since this is [documented properly](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode-with-node-js-api) and the idea of dev-server is that it does not modify the webpack config.
