### ISSUE TITLE
Using with HtmlWebpackPlugin and devServer.lazy

### ISSUE THREAD

**Issue by notiv-nt** [webpack/webpack-dev-server#1936]
Operating System: MacOS 10.14.5 (18F203)
Node Version: v10.15.3
NPM Version: 6.4.1
webpack Version: 4.32.2
webpack-dev-server Version: 3.4.1

- [x] This is a **bug** ?
- [ ] This is a **modification** request

### Code

Repo: https://github.com/notiv-nt/webpack-html-lazy

### Expected Behavior

On start, or on first request, dev-server should run HtmlWebpackPlugin/... plugin(s)

### Actual Behavior

Nothing

### How can we reproduce the behavior?

```
yarn start
open http://localhost:8080
```

### Solution (temporary)

https://github.com/notiv-nt/webpack-html-lazy/blob/8b8fcc276e8a095bafd2c9b56d8b922d7c81de8c/webpack.config.js#L27-L37

```js
devServer: {
  before(app) {
    let invoked = false;

    app.use('/', (req, res, next) => {
      if (!invoked) {
        invoked = true;
        return res.send(`
          <script src="/bundle.js" async></script>
          <meta http-equiv="refresh" content="1" />
        `);
      }
      return next();
    });
  },
}
```

**Comment by evilebottnawi** [comment]
Why you use laze?

**Comment by notiv-nt** [comment]
https://github.com/webpack/webpack-dev-middleware/issues/409#issuecomment-496618709

**Comment by evilebottnawi** [comment]
Lazy was removed due incompatibility with webpack, this option will be removed in next release
