### ISSUE TITLE
Webpack HMR does NOT work when target is not "web".

### ISSUE THREAD

**Issue by erwin-k** [webpack/webpack-dev-server#1938]
- Operating System: Window 10
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.32.2
- webpack-dev-server Version: 3.4.1

- [x] This is a **bug**
- [ ] This is a **modification** request

## From the documentation itself
![image](https://user-images.githubusercontent.com/41877426/58608710-2ac0bd80-82a5-11e9-907a-4dc1bce770aa.png)

When the target is anything other than "web" the webpack-dev-server entry does not get added, adding the entry manually "fixes" it.
The dev server entry shown in that screenshot from the docs isn't even the one I needed, the only thing that fixed this for me was adding "webpack-dev-server/client"

### Expected Behavior
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
[WDS] Live Reloading enabled.

### Actual Behavior
[HMR] Waiting for update signal from WDS...

### For Bugs; How can we reproduce the behavior?
Set  webpack config target to anything other than "web", even a custom target function which copies what target "web" does doesn't work.

**Comment by evilebottnawi** [comment]
HMR !== client, but without client hmr not work

We add client entry for https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L72 targets

I can't understand your problem

If you have other target(s), please provide minimum reproducible test repo. We can't add client entry for all targets because it is invalid.

**Comment by erwin-k** [comment]
You can't understand my problem? It's not fucking documented and you added "electron-renderer" 20 hours ago are you serious. I spend too much time trying to figure out why HMR did not work, please document it.....

**Comment by evilebottnawi** [comment]
@erwin-k first and last warning about using `f*cking` words, as i said above HMR !== client, if you use other target in your configuration please provide reproducible test repo and we fix it
