### ISSUE TITLE
GSoC Refactor: CLI Refactor (CLI/API Uniformity Improvements, webpack-cli serve)

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#1960]
I decided to separate this from the `clientMode/serverMode` refactor effort. Here are my plans:

- [ ] make any "CLI Only" options available to API as well (e.g. [`devServer.progress`](https://webpack.js.org/configuration/dev-server/#devserverprogress))
- [ ] bring options handling in [`bin/webpack-dev-server`](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js) to a bare minimum
- [ ] minimize [`createConfig`](https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/createConfig.js) such that it only normalizes CLI arguments to API options, but does not handle defaults. Instead, the API should handle setting defaults.
- [ ] move the logic of [`bin/webpack-dev-server`](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js) into `webpack-cli serve`, such that `webpack-cli serve` calls the Dev Server API.

Issue created at `webpack-cli`: https://github.com/webpack/webpack-cli/issues/900

EDIT:

- [ ] make the CLI throw an error (or possibly just a warning for backwards compatability?) if an argument is provided that does not exist

**Comment by Parikshit-Hooda** [comment]
@hiroppy we can close this issue now.

**Comment by evilebottnawi** [comment]
Still no

**Comment by evilebottnawi** [comment]
Let's close, it is done, but with some bugs, but, we will fix them
