### ISSUE TITLE
historyApiFallback fails for HMR requests

### ISSUE THREAD

**Issue by SpainTrain** [webpack/webpack-dev-server#197]
I noticed that HMR was not working in my project that uses the HTML5 History API (via `react-router`).  Upon investigation I found this was because:

* webpack HMR uses relative path to download manifest[[1](https://github.com/webpack/webpack/blob/v1.9.11/lib/JsonpMainTemplate.runtime.js#L26)] and updates[[2](https://github.com/webpack/webpack/blob/v1.9.11/lib/JsonpMainTemplate.runtime.js#L17)]
* webpack-dev-server `historyApiFallback` option only falls back for index [[3](https://github.com/webpack/webpack-dev-server/blob/v1.9.0/lib/Server.js#L140)]

A solution, if you are using default options for `output.hotUpdateChunkFilename` and `output.hotUpdateMainFilename` is to use the undocumented[[4](http://webpack.github.io/docs/webpack-dev-server.html)] feature of setting `historyApiFallback` to the following `connect-history-api-fallback` config object, rather than `true`:

```js
var myServer = new WebpackDevServer(webpack(/* webpack config */), {
    historyApiFallback: {
        rewrites: [{
            from: /\.hot-update\.json$/,
            to: function(context) {
                return '/' + path.basename(context.parsedUrl.pathname);
            }
        }, {
            from: /\.hot-update\.js$/,
            to: function(context) {
                return '/' + path.basename(context.parsedUrl.pathname);
            }
        }]
    }
});
```

There is a valid argument that `webpack-dev-server` should not automatically fallback for these cases, so I am happy to do one of two things based on feedback from maintainer @sokra :

* Generalize this solution by converting `output.hotUpdateChunkFilename` and `output.hotUpdateMainFilename` to regexes and open PR to fix this 
* Update https://github.com/webpack/docs/wiki/webpack-dev-server to document this feature and provide this example config for `historyApiFallback`

**Comment by ryancole** [comment]
:+1:

**Comment by SpaceK33z** [comment]
@SpainTrain, this is over a year old, but are you still willing to do a PR for this? The first option would be best I think.

**Comment by SpaceK33z** [comment]
I've tested this, and this is no longer an issue. Tested with `examples/hmr`, and added `--history-api-fallback` to the command. Browsed to `http://localhost:8080/foo`, and made a changing `example.js`.

**Comment by SpainTrain** [comment]
Sorry for not responding.  Thanks for testing this.  Glad it has gone away, I will have to try it out!
