### ISSUE TITLE
[refactor] tests

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack-dev-server#1983]
No issue template. Ref: https://github.com/webpack/webpack-dev-server/pull/1982#issuecomment-499510055

Test structure (approximately):
```
- test
  - e2e
  - cli
  - client
    - clients
      - SockJSClient.test.js 
    - utils
      - sendMessage.test.js
    - overlay.test.js 
  - server
    - servers
      - SockJSServer.test.js
    - utils
      - tryParseInt.test.js
```

Test naming:
1. class tests have same name as class -> `MyClass.js` -> `MyClass.test.js`
2. pure file like `defaultPort.js` -> `defaultPort.test.js`
3. options for server should be placed in `server` directory and have name `compress-option.test.js`
4. options for client should be placed in `client` directory and have name `sockPath-options.test.js`

Next we should improve test performance, many tests are very long and written in effective way.

Some of tests files should be merge in other, some of separated based on above structure.

I am WIP on this after merge this PR

-----

Ideally each option **should have**:
1. Unit test (own)
2. Integration test (Server.test.js)
3. E2E test (can be avoided for non client options)
4. CLI test (can be avoided right now)

We should concentrate on `1` and `2` points right now.

Other changes what we should do:
- avoid using `--runInBand` it is decrease time on tests
- union option.test.js and validation.test.js (they do same)
- rewrite some test in more effective way
- better naming of tests

**Comment by hiroppy** [comment]
Yes, I definitely agree with this plan.
I added below to this issue.

```
    - utils
      - sendMessage.test.js
```

**Comment by evilebottnawi** [comment]
Structure is done. Unfreeze merge for any branches.

/cc @hiroppy need rebase next

**Comment by hiroppy** [comment]
We don't rebase because a base branch will be broken if we force push. So I've always use cherry-pick. What do you think? (also, It depends on the committer to merge, but if the committer is not myself, then the commit revision is changed.)

**Comment by evilebottnawi** [comment]
Yes, we need rebase :+1:

**Comment by hiroppy** [comment]
ok, so maybe pr is broken

**Comment by hiroppy** [comment]
And I deleted branch rules because if we set branch rules, we can not force push.

**Comment by evilebottnawi** [comment]
> And I deleted branch rules because if we set branch rules, we can not force push.

:+1:

**Comment by hiroppy** [comment]
We completed migrating to the new directory structure. I'll close.
