### ISSUE TITLE
devServer.progress is only available trough cmd and not trough webpack.config

### ISSUE THREAD

**Issue by LeonFedotov** [webpack/webpack-dev-server#201]
Hi, for example activation of progress flag happens in [webpack/bin/convert-argv.js#L333](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L333) and it is called in 
[webpack-dev-server/bin/webpack-dev-server.js#L46](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L46) before options is merged into argv so 
` devServer: { progress: false } ` isn't working.

**Comment by iMoses** [comment]
+1
I used `devServer: {hot: true}` in the webpack.config file and `module.hot` in `webpack/hot/dev-server` equals false which throws an error (`[HMR] Hot Module Replacement is disabled.`). Tried the CLI option `webpack-dev-server --hot` and it suddenly works great.
Would really appreciate a fix. Thanks.

**Comment by alexilyaev** [comment]
I'm having the same issues as mentioned above.

Simple config to test the `progress` flag:
```js
var webpack = require('webpack');
var appRoot = __dirname + '/client';

module.exports = {
    context: appRoot,
    entry: './index.js',
    output: {
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loaders: ['babel']
            }
        ]
    },
    devServer: {
        contentBase: appRoot,
        colors: true,
        progress: true,
        inline: true
    }
};
```

Running `webpack-dev-server` doesn't show the progress.
Only when adding `--progress` it shows the progress.

**Comment by chemoish** [comment]
:+1:

**Comment by mathieumg** [comment]
+1 :+1:

**Comment by wendellm** [comment]
+1 :+1:

**Comment by mathieumg** [comment]
I think for `hot` you can get away with:

```js
devServer: {
  hot: true,
  inline: true,
}
```

but there is no config equivalent for `progress`.

**Comment by satazor** [comment]
+1

**Comment by iyel** [comment]
Any update on this?

**Comment by martin-svk** [comment]
+1

**Comment by chunkai1312** [comment]
+1

**Comment by leebenson** [comment]
+1

**Comment by mikeys** [comment]
+1

**Comment by oliverwehn** [comment]
+1

**Comment by LeonFedotov** [comment]
@sokra yo yo yo yo :)

**Comment by bensleveritt** [comment]
+1

**Comment by skleinei** [comment]
+1

**Comment by mori-dev** [comment]
+2

**Comment by betolink** [comment]
We can manually use the ProgressBarPlugin in the webpack config file and that should do it. 

`npm install --save-dev progress-bar-webpack-plugin`

The in our development webpack config:

```js
const ProgressBarPlugin = require('progress-bar-webpack-plugin');

...

plugins: plugins.concat([
  new webpack.HotModuleReplacementPlugin(),
  new ProgressBarPlugin({ clear: false })
])
```

**Comment by feel** [comment]
+1

**Comment by SpaceK33z** [comment]
This is not something that can be fixed in webpack-dev-server. The dev-server only passes the `progress` flag through to the webpack CLI options, as you can [see here](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L265). If you want this to be fixed, you should create an issue in the webpack repo. It will automatically also work in dev-server if it's fixed over there (since dev-server has nothing to do with compiling to a bundle).

There are a couple of workaround for this though. The answer from @betolink is an option, or you can use `webpack.ProgressPlugin`. Example: `new ProgressPlugin(percentage => progressBar.update(percentage))`. `progressBar` comes from the [`progress`](https://www.npmjs.com/package/progress) package.

**Comment by elmorec** [comment]
Simply you can use the webpack ProgressPlugin instead of any other third party plugin.

```javascript
const ProgressPlugin = require("webpack/lib/ProgressPlugin");

...

config.plugins.push(new ProgressPlugin({ profile: false, colors: true }));

```

Cheers!😜

**Comment by alexilyaev** [comment]
@elmorec That worked, thanks.

Note `colors` doesn't do anything, it's not in the plugin's code as well.

**Comment by elmorec** [comment]
@alexilyaev Yeah, you are right, thx.

**Comment by PeterShershov** [comment]
Yo, any update on this?
