### ISSUE TITLE
Hot reload does not work in multi html & multi entry setup

### ISSUE THREAD

**Issue by thezjy** [webpack/webpack-dev-server#2024]
- Operating System: macOS 10.14.5
- Node Version: v10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.28.3
- webpack-dev-server Version: 3.1.14

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

webpack.config.js
```js
 entry: {
      index: [
        isEnvDevelopment &&
        require.resolve('react-dev-utils/webpackHotDevClient'),
        paths.appIndexJs,
      ].filter(Boolean),
      published: [
        isEnvDevelopment &&
        require.resolve('react-dev-utils/webpackHotDevClient'),
        paths.appPublishedIndexJs,
      ].filter(Boolean),
    },
}

 plugins: [
      // Generates an `index.html` file with the <script> injected.
      new HtmlWebpackPlugin(
        Object.assign(
          {},
          {
            inject: true,
            chunks: ["index"],
            template: paths.appHtml,
          },
          isEnvProduction
            ? {
                minify: {
                  removeComments: true,
                  collapseWhitespace: true,
                  removeRedundantAttributes: true,
                  useShortDoctype: true,
                  removeEmptyAttributes: true,
                  removeStyleLinkTypeAttributes: true,
                  keepClosingSlash: true,
                  minifyJS: true,
                  minifyCSS: true,
                  minifyURLs: true,
                },
              }
            : undefined
        )
      ),
      new HtmlWebpackPlugin(
        Object.assign(
          {},
          {
            inject: true,
            chunks: ["published"],
            template: paths.appHtml,
            filename: 'published.html',
          },
          isEnvProduction
            ? {
              minify: {
                removeComments: true,
                collapseWhitespace: true,
                removeRedundantAttributes: true,
                useShortDoctype: true,
                removeEmptyAttributes: true,
                removeStyleLinkTypeAttributes: true,
                keepClosingSlash: true,
                minifyJS: true,
                minifyCSS: true,
                minifyURLs: true,
              },
            }
            : undefined
        )
      ),
)
```

webpackDevserver.config.js
```js
contentBase: paths.appPublic,
historyApiFallback: {
      // Paths with dots should still use the history fallback.
      // See https://github.com/facebook/create-react-app/issues/387.
      disableDotRule: true,
      rewrites: [
        { from: /^\/f\/\S*$/, to: '/published.html' },
        { from: /^\/pf\/\S*$/, to: '/published.html' },
      ]
    },
```

### Behavior

In our ejected create-react-app, we generate two entries (basically two SPAs) to use in two separate server-rendered pages. In our webpack.config.js, we set up two entries and two HtmlWebpackPlugins, one for each. In webpackDevServer.config.js, the contentBase still points to the public folder. And we use historyApiFallback to rewrites certain routes to each HTML, simulating the production routing. Everything works fine, except hot reloading (both for js and css) not working in the second non-index entry. In Chrome console we saw the hot reload xhr request, but the response indicates false, which means no change I guess.

**Comment by evilebottnawi** [comment]
Please update `webpack-dev-server` to latest version. If it is not solve your problem please create reproducible test repo

**Comment by thezjy** [comment]
Hi, @evilebottnawi, I eject from a new create-react-app project and upgrade both webpack and webpack-dev-server to the latest versions. The reproduction [repo is here](https://github.com/thezjy/hot-reload-issue-reproduction).

In our production project, hot reload does work in second html & entry but the page works fine. Somehow in this reproduction the second html & entry loads correctly but the js never run. The configs are exactly the same.

**Comment by mingenesis** [comment]
I have the same issue!! @thezjy did you resolved?

**Comment by thezjy** [comment]
@mingenesis no, sadly

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by mingenesis** [comment]
@thezjy I resolved.
change
`
output: {
      ...
      filename: isEnvProduction ? 'static/js/[name].[contenthash:8].js' : 
                       isEnvDevelopment && 'static/js/bundle.js',
      ...
}
`
to
`
output: {
      ...
      filename: isEnvProduction ? 'static/js/[name].[contenthash:8].js' : 
                       isEnvDevelopment && 'static/js/[name].js',
      ...
}
`
work for me.

**Comment by nickmcmillan** [comment]
Still facing the same problem here too. 

As soon as there's a second entry specified in the config file, the hot update no longer works.

As @thezjy mentions in the original post, the Network tab shows activity when a hot update should occur, but its response is false, indicating nothing to update.

**Comment by mcuking** [comment]
I solved the problem by the article below. Hope it's helpful

https://sapandiwakar.in/multiple-html-pages-with-create-react-app-app/
