### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by jamiek-acl** [webpack/webpack-dev-server#2029]
- Operating System: Mac OS
- Node Version: 10.15.1
- NPM Version: 6.4.1
- webpack Version: 4.34.0
- webpack-dev-server Version: 3.2.1

- [x] This is a **bug**...?
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');
const config = require('./webpack.dev.config');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const newConfig = Object.assign({}, config);

newConfig.entry = ['@babel/polyfill', './app/features/Certifications/index', 'webpack/hot/only-dev-server'];

newConfig.output = {
  filename: 'webpack-certifications-bundle.js',
  path: path.resolve('../app/assets/webpack'),
  publicPath: '/',
};

newConfig.devServer = {
  historyApiFallback: true,
  hot: true,
  open: true,
  openPage: 'dashboard',
  port: 9000,
  proxy: {
    '/api': {
      target: 'http://localhost:9010',
      secure: false,
    },
  },
  publicPath: '/',
};

newConfig.plugins.push(new HtmlWebpackPlugin());

module.exports = newConfig;
module.exports.devtool = 'cheap-module-eval-source-map';

```

```js
// package.json
scripts: {
  "dev:cert:webpack": "NODE_ENV=development webpack-dev-server --config webpack.dev.certifications.config.js"
}
```

### Expected Behavior

Running `npm run dev:cert:webpack` starts webpack dev server.

### Actual Behavior
```
~/src/projects/client$ npm run dev:cert:webpack

> acl-project-manager@0.0.1 dev:cert:webpack /Users/jamie/src/projects/client
> NODE_ENV=development webpack-dev-server --config webpack.config.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jamie/src/projects/client/node_modules/webpack-dev-server/bin/webpack-dev-server.js:77:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! acl-project-manager@0.0.1 dev:cert:webpack: `NODE_ENV=development webpack-dev-server --config webpack.dev.certifications.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the acl-project-manager@0.0.1 dev:cert:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jamie/.npm/_logs/2019-06-14T23_23_20_044Z-debug.log
```

If I downgrade to webpack-dev-server 3.2.1, this error does not occur.

Thank you for your help.

**Comment by hiroppy** [comment]
hmm. webpack-cli changed a directory structure...
related: https://github.com/webpack/webpack-cli/pull/781

**Comment by hiroppy** [comment]
I cannot reproduce this issue.

<details>

```sh
ᐅ npm i webpack-dev-server

+ webpack-dev-server@3.7.1
added 441 packages from 281 contributors and audited 3458 packages in 18.504s
found 0 vulnerabilities

ᐅ npx webpack-dev-server
Cannot find module 'webpack'
Require stack:
- /Users/Desktop/test2/node_modules/webpack-dev-server/bin/webpack-dev-server.js

ᐅ npm i webpack
npm WARN saveError ENOENT: no such file or directory
npm WARN enoent ENOENT: no such file or directory
npm WARN test2 No description
npm WARN test2 No repository field.
npm WARN test2 No README data
npm WARN test2 No license field.

+ webpack@4.34.0
added 148 packages from 130 contributors and audited 15992 packages in 10.067s
found 0 vulnerabilities

ᐅ npx webpack-dev-server
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/Desktop/test2/node_modules/webpack-dev-server/bin/webpack-dev-server.js

ᐅ npm i webpack-cli

> webpack-cli@3.3.4 postinstall
> node ./bin/opencollective.js



                            Thanks for using webpack!
                 Please consider donating to our Open Collective
                        to help us maintain this package.



              👉  Donate: https://opencollective.com/webpack/donate


npm WARN saveError ENOENT: no such file or directory
npm WARN enoent ENOENT: no such file or directory
npm WARN test2 No description
npm WARN test2 No repository field.
npm WARN test2 No README data
npm WARN test2 No license field.

+ webpack-cli@3.3.4
added 21 packages from 21 contributors and audited 22506 packages in 5.154s
found 0 vulnerabilities

ᐅ npx webpack-dev-server
...  
```

</details>

**Comment by evilebottnawi** [comment]
You use old webpack-cli version, please update webpack-cli

**Comment by jamiek-acl** [comment]
@evilebottnawi 
```
    "webpack-cli": "^3.3.4",
```

**Comment by hiroppy** [comment]
We cannot reproduce your issue. if we need to investigate this issue, please submit the reproducible repo.

**Comment by jamiek-acl** [comment]
It looks like you used `webpack-dev-server@3.7.1`, but I had the problem with version 3.2.1 (I am not able to upgrade).

**Comment by snaill** [comment]
webpack-dev-server@3.7.1 is OK.

**Comment by snaill** [comment]
webpack-dev-server@3.7.2 error: Cannot find module 'yargs'

**Comment by dhantke** [comment]
Same problem here.

- webpack-dev-server@3.7.2: does not work
- webpack-dev-server@3.7.1: works

@snaill thx for investigation!

**Comment by Dheeraj-GL** [comment]
same issue on 3.8.2

**Comment by sneeze-attack** [comment]
I ran into this issue after updating webpack-cli from:

`webpack-cli  ^3.2.1  →  ^3.3.9`


I fixed it by changing:

node_modules\webpack-dev-server\bin\webpack-dev-server.js

Line 84:
`require('webpack-cli/bin/config-yargs')(yargs);`
To:
`require('webpack-cli/bin/config/config-yargs')(yargs);`

Line 92:
`const config = require('webpack-cli/bin/convert-argv')(yargs, argv, {`
To:
`const config = require('webpack-cli/bin/utils/convert-argv')(yargs, argv, {`

**Comment by cjlarose** [comment]
Fixed in #1754

**Comment by jods4** [comment]
This is broken again when using `webpack-cli` 4.0.0 (in beta). There's only `cli.js` left inside `webpack-cli/bin`.

**Comment by evilebottnawi** [comment]
Please use `webpack serve` for run webpack-dev-server

**Comment by jods4** [comment]
@evilebottnawi thanks for the tip. Is there any doc? Is that equivalent to `webpack-dev-server` (hmr, etc.) moving forward with webpack 5?

**Comment by evilebottnawi** [comment]
No docs right now, webpack-cli is still in beta, docs will be improved before stable release

**Comment by jods4** [comment]
No problem, I'll figure it out. But it's the new way to run dev-server, with support for HMR?

**Comment by evilebottnawi** [comment]
@jods4 flags are unstable right now, please use the configuration file

**Comment by Loligplayer33** [comment]
I have the same issue with the webpack-cli 4.0.0 version. Is there some way to downgrade to an older version that works or how can i solve the problem?

**Comment by evilebottnawi** [comment]
Do **not use** `webpack-cli@4`, it is still in beta

**Comment by Loligplayer33** [comment]
Ok but how can I downgrade?

**Comment by evilebottnawi** [comment]
What is downgrade? We don't use `webpack-cli@4`, please look in own `package.json`

**Comment by Loligplayer33** [comment]
I got this, my question is how do i install an older (and working) version of webpack-cli? 
This is probably quite obvious but I'm new to all this stuff ;)

**Comment by evilebottnawi** [comment]
`npm i  webpack-cli`

**Comment by Loligplayer33** [comment]
Already tried this. It is adding `+ webpack-cli@4.0.0-beta.3` as the version...

**Comment by evilebottnawi** [comment]
Something wrong with package manager because latest is `3.3.11` https://www.npmjs.com/package/webpack-cli

**Comment by Loligplayer33** [comment]
Thank you a lot! Unfortunately I have no idea what to look for or where the bug could be. Do you have any suggestions what to look out for? Or, if it is not to time consuming, here is a repo with the files. You would literually make my day. I try to set this thing up for hours now....
https://github.com/Loligplayer33/Portfolio-Website-2.0

**Comment by evilebottnawi** [comment]
Just change https://github.com/Loligplayer33/Portfolio-Website-2.0/blob/master/package.json#L29 to `3.3.11`, remove `package-lock.json` and run `npm i` again

**Comment by Loligplayer33** [comment]
can't thank you enough for your time ;)

**Comment by bigbizze** [comment]
I wrote a python script to fix the problem until it's patched.

You can just add the command to your package.json script after adding the file to your project (assuming you have python installed).

https://github.com/bigbizze/FixWebPackError-Cannot-find-module-webpack-cli-bin-config-yargs

**Comment by funkjunky** [comment]
Installing the latest webpack-dev-server and webpack and i get this same issue. Is this a regression?

**Comment by clio19** [comment]
Remove node_modules folder   and if you are using yarn change to npm and run npm install otherwise remove  yarn.lock

**Comment by Linbubin** [comment]
`webpack-cli@4` this problem still exists
run `npm  install -D webpack-cli@3` to solve it

**Comment by unp** [comment]
I was trying to run `yarn webpack-dev-server` on an app running `react-scripts`. I forgot I had used `create-react-app` to bootstrap my app.

Running `yarn start` fixed the issue.

**Comment by xdvarpunen** [comment]
I had windows update today that prevented recognizing `webpack` and `webpack-cli`. After finishing the update and restarting PC the project recognized `webpack` and `webpack-cli` again.

**Comment by harsh1612-dec** [comment]
> I had windows update today that prevented recognizing `webpack` and `webpack-cli`. After finishing the update and restarting PC the project recognized `webpack` and `webpack-cli` again.


> webpack-dev-server --hot

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'webpack/bin/config-yargs'
Require stack:
- C:\Users\Harsh Agarwal\Desktop\reactapp\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Harsh Agarwal\Desktop\reactapp\node_modules\webpack-dev-server\bin\webpack-dev-server.js:54:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Harsh Agarwal\\Desktop\\reactapp\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactapp@1.0.0 start: `webpack-dev-server --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Harsh Agarwal\AppData\Roaming\npm-cache\_logs\2020-09-19T03_56_55_540Z-debug.log

Kindly help me with this i cant find solution from past 3 days

**Comment by matrunchyk** [comment]
Same to me:
```
"webpack": "^5.0.0-rc.3",
"webpack-cli": "^4.0.0-rc.0",
"webpack-dev-server": "^3.11.0"
```

**Comment by matrunchyk** [comment]
@evilebottnawi wanna reopen or should I create a new issue?

**Comment by GurvirSingh** [comment]
use the command `npm i webpack-cli@3.3.12` and it should work!

**Comment by dmitriid** [comment]
Just reporting that this is still broken.

```
   "webpack": "~4.44.2",
    "webpack-cli": "~4.0.0",
    "webpack-dev-middleware": "~3.7.2",
    "webpack-dev-server": "~3.11.0"
```

Do not upgrade to `"webpack": "~4.44.2"` yet, stay on `"webpack-cli": "~3.3.12"`

**Comment by evilebottnawi** [comment]
Need update `webpack-cli` to v4 (**stable**) and change `webpack-dev-server` bin in package.json on `webpack serve`, please read my answer careful

**Comment by dmitriid** [comment]
@evilebottnawi Your answer is somewhere in the middle of 20-30 replies to this issues. It's nowhere in the README. The version didn't change, but somehow the behaviour broke due to a release of an external lib?

Dependabot has bumped cli version for quite a number of projects, so expect a lot of people flocking to this issue and potentially missing a response.

The best way to solve this is just to add a line to the README:

```diff
NPM package.json scripts are a convenient and useful means to run locally installed binaries without having to be concerned about their full paths. Simply define a script as such:

+ For webpack-cli 3.x:
+
"scripts": {
  "start:dev": "webpack-dev-server"
}

+ For webpack-cli 4.x:
+
+ "scripts": {
+  "start:dev": "webpack serve"
+}

And run the following in your terminal/console:
```

**Comment by evilebottnawi** [comment]
Yes, we are working on bugs in webpack-cli, it will be improved after this

**Comment by devenderbe** [comment]
> @evilebottnawi Your answer is somewhere in the middle of 20-30 replies to this issues. It's nowhere in the README. The version didn't change, but somehow the behaviour broke due to a release of an external lib?
> 
> Dependabot has bumped cli version for quite a number of projects, so expect a lot of people flocking to this issue and potentially missing a response.
> 
> The best way to solve this is just to add a line to the README:
> 
> ```diff
> NPM package.json scripts are a convenient and useful means to run locally installed binaries without having to be concerned about their full paths. Simply define a script as such:
> 
> + For webpack-cli 3.x:
> +
> "scripts": {
>   "start:dev": "webpack-dev-server"
> }
> 
> + For webpack-cli 4.x:
> +
> + "scripts": {
> +  "start:dev": "webpack serve"
> +}
> 
> And run the following in your terminal/console:
> ```

`"start": "webpack serve --mode development --open"` it's working fine but without using --open. But giving error on adding --open.

**Comment by ekb72-B** [comment]
Hi All, having trouble with this as well. 
```> reactapp@1.0.0 start /Users/kimberlybomani/Desktop/reactApp
> webpack-dev-server --mode development --open --hot

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactapp@1.0.0 start: `webpack-dev-server --mode development --open --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
``` 

I changed the versions to recommended ones here, but the issue persists.

**Comment by renic** [comment]
running 3.3.12 resolved this for me.`npm i webpack-cli@3.3.12`

**Comment by BelisonRazer** [comment]
> running 3.3.12 resolved this for me.`npm i webpack-cli@3.3.12`

 downgraded 4.x => 3.3.12, it's work
