### ISSUE TITLE
CI failing due to outdated chokidar dependency

### ISSUE THREAD

**Issue by ryanelian** [webpack/webpack-dev-server#2059]
- Operating System: Windows 10
- Node Version: v12.4.0
- NPM Version: 6.9.0 and yarn 1.16.0
- webpack Version: 4.35.0
- webpack-dev-server Version: 3.7.2

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```
warning webpack-dev-server > chokidar > braces > snapdragon > base > mixin-deep@1.3.1: Critical bug fixed in v2.0.1, please upgrade to the latest version.
warning webpack-dev-server > chokidar > braces > snapdragon > base > cache-base > set-value@2.0.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning webpack-dev-server > chokidar > braces > snapdragon > base > cache-base > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
```

Please update chokidar to 3.0.1 to remove this warning.

### Expected Behavior

No warnings.

### Actual Behavior

Warnings due to to outdated chokidar which depended on braces@2.3.2 which depended on snapdragon package.

The newer chokidar depends on braces@3.0.2 which no longer depends on snapdragon package.

### For Bugs; How can we reproduce the behavior?

```
yarn add webpack-dev-server
```

**Comment by evilebottnawi** [comment]
It is breaking change and we can't do this in master, will be solved in next major release

**Comment by ryanelian** [comment]
Shouldn't this issue remain open until next major release, then?

**Comment by evilebottnawi** [comment]
@ryanelian we have roadmap for this https://github.com/webpack/webpack-dev-server/projects/1#card-12639653, we use card this next releases
