### ISSUE TITLE
Browser not refreshing

### ISSUE THREAD

**Issue by aoshi321** [webpack/webpack-dev-server#206]
Hi

The browser does not refresh automatically even though the file has updated. I have to manually refresh the browser.

This is the console output from the browser

[HMR] Waiting for update signal from WDS...
webpack-dev-server.js:1 [WDS] Hot Module Replacement enabled.
2webpack-dev-server.js:1 [WDS] App updated. Recompiling...
webpack-dev-server.js:1 [WDS] App hot update...
dev-server.js:52 [HMR] Checking for updates on the server...
log-apply-result.js:20 [HMR] Updated modules:
log-apply-result.js:22 [HMR]  - 3
log-apply-result.js:22 [HMR]  - 0
dev-server.js:38 [HMR] App is up to date.

This is my config

var path = require('path');
module.exports = {
  entry: [
	'webpack/hot/dev-server',
  	path.resolve(__dirname, 'app/test/main.js'),
  ],
  output: {
    path: path.resolve(__dirname, 'public'),
    filename: 'bundle.js',
  }
};

Im calling it via this command from the package.json

"start": "webpack-dev-server --config webpack.development.js --devtool eval --progress --colors --hot --content-base public"

thanks

**Comment by mistadikay** [comment]
+1 same here

**Comment by hendrikswan** [comment]
It seems like almost everyone is plagued with this. I've spent 2 hours trying to get this working, and haven't managed to find one full single working example, only snippets, and when you pull them together, it's not watching and packaging the files.

**Comment by daniel-erickson** [comment]
This was driving me insane, I have got it working by removing --hot and including 
plugins: [
    new webpack.HotModuleReplacementPlugin()
]

in the webpack.config file.

**Comment by jugend** [comment]
+1 same here, @daniel-erickson the fix works for me too, thanks!

**Comment by jonmanzo** [comment]
Updating WP to 1.10.1 fixed my issues.

**Comment by daniel-erickson** [comment]
Yeah, can confirm that 1.10.1 fixed it. Thanks!

**Comment by smaye81** [comment]
I am seeing this issue with 1.11.0 and dev-server 1.10.1.  Had to replace `hot: true` with:

```
plugins: [
new webpack.HotModuleReplacementPlugin()
]
```
to get it working

**Comment by chrisiDC** [comment]
this is sooo bad documented

**Comment by blade254353074** [comment]
@smaye81 
Fixed in same way!

**Comment by liminalisht** [comment]
Thank you

**Comment by elvengard** [comment]
This is the console output from the browser
I use command  webpack-dev-server --hot --inline and change the file.but browser can not reload.
And the console show like this .I don't know why.
![image](https://cloud.githubusercontent.com/assets/22080085/19506311/0ffc04f6-95fd-11e6-944f-079894fe4c68.png)
[WDS] Hot Module Replacement enabled.
[WDS] App updated. Recompiling...
[WDS] App hot update...
[WDS] App updated. Recompiling...
Nothing changed.
[WDS] App updated. Recompiling...
App hot update...

**Comment by diegolaciar** [comment]
@smaye81 In my case , doing your solution reload the full page, not HMR.

**Comment by dfang** [comment]
@smaye81   Thank you, same as webpack-dev-server@^1.16.2

**Comment by goartur** [comment]
I had the same problem. I know it's a old topic but I have my webpack on port 9000 and application on port 3000 so in devServer I added:
```
headers: {
			'Access-Control-Allow-Origin': '*'
		}
```

Hope it helps.

**Comment by Kitanga** [comment]
can confirm @daniel-erickson and @smaye81 's solution works in webpack 3.4.1 and webpack-dev-server 2.6.1

> I am seeing this issue with 1.11.0 and dev-server 1.10.1. Had to replace hot: true with:
plugins: [
new webpack.HotModuleReplacementPlugin()
]
to get it working
