### ISSUE TITLE
Is there any way to use index.html render from backend?

### ISSUE THREAD

**Issue by kubeadm** [webpack/webpack-dev-server#2066]
- Operating System: win7
- Node Version: ^11
- NPM Version:6.9
- webpack Version:4.35.0
- webpack-dev-server Version:3.7.2

- [ ] This is a **bug**
- [x] This is a **modification** request
- This is a question

### Code

```js
// additional code, remove if not needed.
var proxy = require('proxy-middleware');
router.use('/', proxy(getOptions(baseURL)));
router.use('/json', proxy(getOptions(`${baseURL}json`)));
app.use(`/${ctxRoot}/`, router);
app.get('/', (req, res) => {
  res.redirect(`http://localhost:8088/${ctxRoot}`);
});
```

### For Features; What is the motivation and/or use-case for the feature?
I want to upgrade our project with latest webpack,  previously we are using  a server file using express .

it behaved like this:
"/" : redirected to  back-end server with cookie keep  ,which then return a html page with some  javascript  global data.

"/json": normal api request.

I cannot modify the index.html render process cause it's in our java library, so I can't use publicPath option, 
I cannot figure out how to configure webpack dev server proxy to implement the same function as before.

**Comment by evilebottnawi** [comment]
I can't understand problem, please provide more information. You can use `bypass` option https://webpack.js.org/configuration/dev-server/#devserverproxy
