### ISSUE TITLE
How can I integrate socket.io with the server?

### ISSUE THREAD

**Issue by chillyond** [webpack/webpack-dev-server#2073]
- Operating System: macOS 10.14.5
- Node Version: v10.13.0
- NPM Version: 6.4.1
- webpack Version: 4.35.0
- webpack-dev-server Version: 3.7.2

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const io = require('socket.io')(server) // how can I get this server?

io.of('/test').on('connection', function(socket){
  console.log('test connected')
});
```

### Expected Behavior
I want run some testing that expect for devServer supports socket.io apis, just like do this:
``` javascript
devServer: {
  before: function(app, server) {
    app.get('/some/path', function(req, res) {
      res.json({ custom: 'response' });
    });
  }
}
```

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions, thanks

Simple example:
```
devServer: {
  before: function(app, server) {
    const io = require('socket.io')(server)

    io.of('/test').on('connection', function(socket){
      console.log('test connected')
    });

    app.get('/some/path', function(req, res) {
      res.json({ custom: 'response' });
    });
  }
}
```

**Comment by chillyond** [comment]
> Please use stackoverflow or gitter for questions, thanks
> 
> Simple example:
> 
> ```
> devServer: {
>   before: function(app, server) {
>     const io = require('socket.io')(server)
> 
>     io.of('/test').on('connection', function(socket){
>       console.log('test connected')
>     });
> 
>     app.get('/some/path', function(req, res) {
>       res.json({ custom: 'response' });
>     });
>   }
> }
> ```

Thank you for the reply, but I have tried this, and it doesn't work, because `socket.io` need a `http.Server` instance, the `server` passed in `before` and `after` was a wrapped object, theses hooks are invoked before the `listeningApp` is assigned, so I can't handle this for now.

**Comment by chillyond** [comment]
@evilebottnawi Is there any solution?

**Comment by TimonLukas** [comment]
I've managed to do it in a project by using `Object.defineProperty` on the `server` inside the `after` to create a custom getter and setter for the `listeningApp` property. You can use the setter as a kind of event listener.

```javascript
devServer: {
    after (app, server) {
        Object.defineProperty(server, 'listeningApp', {
            set (value) {
                server._listeningApp = value
                executeCustomFunction(value) // here you can set up your socket.io server
            },
            get () {
                return server._listeningApp
            }
        })
    }
}
```

But this is obviously very hacky. An official hook for when the HTTP server instance is created would be very nice.
