### ISSUE TITLE
Set WDS for PHP app

### ISSUE THREAD

**Issue by padevone** [webpack/webpack-dev-server#2074]
- Operating System: Ubuntu 16
- Node Version: 8.12.0
- NPM Version: 6.4.1
- webpack Version: 4.30.0
- webpack-dev-server Version: 3.3.1

- [ ] This is a **bug**
- [ ] This is a **modification** request
- [x] This is a **question** request

### Code

```js
// webpack.config.js
{
    host: 'localhost',
    port: 8100,
    disableHostCheck: true,
    hot: true,
    proxy: {
      '/': {
        changeOrigin: true,
        secure: false,
        target: {
          host: PROXY_HOST,
          protocol: PROXY_PROTOCOL,
          port: PROXY_PORT,
        },
      }
    }
  }
```

### Question

Hello. I have runned project on PHP server. I need to use WDS for work with scripts and styles in dev mode without generating files.
How do i can set WDS for this goal? Now my project runned on proxy host, but files didn't actual (getting earlier generated). I need some options for WDS or exmaples with same goal.
I use WDS via Node JS.

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions. There a lot of possible solutions. Sorry we don't have time to setup your project.

**Comment by evilebottnawi** [comment]
Also don't use old version of webpack-dev-server

**Comment by evilebottnawi** [comment]
For example you can use https://github.com/JeffreyWay/laravel-mix (laravel), you can find repositories for webpack/drupal/pure php solution in github.
