### ISSUE TITLE
Client reloads app even when there is an error and the screen is just shown for a very short time.

### ISSUE THREAD

**Issue by jespermjonsson** [webpack/webpack-dev-server#209]
When loading the application with the live client e.g. http://localhost:3000/webpack-dev-server/index.html the browser is reloaded on script/style changes. But when there is an syntax error (and using the NoErrorsPlugin) the browser is reloaded with the message: **Errors while compiling. App ready.** And an error screen is displayed just before the browser is reloaded. But if the browser is reloaded manually after this syntax error has occured (so it is the initial load) the error screen is displayed nicely with the title: **Errors while compiling. App updated with errors. No reload!**.

Is there a reason why the client reloads the browser on errors? Thinking of these lines in the client: https://github.com/webpack/webpack-dev-server/blob/8fddb2adbf71582d4728d85021a32bd3175571c4/client/index.js#L47-L48

Or are you open to change this somehow so the error message is shown until the syntax error is fixed and a new bundle is generated even when the error occurs during a regular reload (not just the initial load)?

**Comment by SpaceK33z** [comment]
More then one year later, I fixed this in the `prevent-reload-on-errors` branch ⏳ .

I simply removed the code that did a reload when there were warnings or errors. I still want to look at it if there are valid use cases for this. At the moment I can't think of any.

**Comment by SpaceK33z** [comment]
Looks like this code was introduced in the first version of the "inline" modus (2329516ac2f73760a973d788e5bb3e25f98dda40). After some tests it seems safe to remove.

**Comment by kozakluke** [comment]
Hello, I use react + typescript and when I for example load module without dt.ts definition file I see error in console and reload is prevented...
So reloading app when compiler see errors should be optional because IT'S errors usually are not dangerous, but stopping hot reload is really uncomfortable...
