### ISSUE TITLE
Fails to find `/` if index is generated dynamically on Windows

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-dev-server#210]
I set up a small [demo project](https://github.com/bebraw/webpack-dev-server-bug). Instructions:

1. `npm i`
2. `npm start`
3. Surf to `http://localhost:8080` - It **should** show a small app and it does do this on OS X. On Windows it shows a directory listing.

It looks like it works on Windows if you navigate to `/index.html` directly. For some reason just having `/` won't work.

**Comment by publicJorn** [comment]
I can second this. It's not a big issue, but slightly annoying

**Comment by mushishi78** [comment]
+1

**Comment by bebraw** [comment]
Apparently enabling history api fallback fixes this. A user reported `webpack-dev-server -d --inline --history-api-fallback --output-public-path /` works.

Perhaps it should be enabled by default?

**Comment by d3lm** [comment]
+1

**Comment by mushishi78** [comment]
I think history api fallback just serves the index.html at root no matter what path you put in. So a path like `http://localhost:8080/apples/` will serve `http://localhost:8080/index.html`,  not `http://localhost:8080/apples/index.html`.

**Comment by bebraw** [comment]
@mushishi78 Yeah, that's a valid point. It's not a real solution in that sense. It just covers the common case, not all of it.

**Comment by chrisbateman** [comment]
It seems like this is fixed as of webpack-dev-middleware@1.5.0

https://github.com/webpack/webpack-dev-middleware/issues/54
