### ISSUE TITLE
Allow passing data to Webpack configuration?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-dev-server#211]
I'm currently using this kind of pattern with `webpack-dev-server`:

**package.json**

```json
"scripts": {
  "start": "TARGET=dev webpack-dev-server ...",
  ...
}
```

My `webpack.config.js` will then pick the configuration fragment based on `TARGET`. This allows me to keep all configuration within one file while keeping it all maintainable. Earlier I used multiple separate files but that just got messy.

The problem with this approach is that it won't work on Windows and there's no cross-platform way to deal with environment variables. Under Windows you'll need a slightly different command to set the env. That's a problem.

Would it be possible to come up with a cross-platform mechanism that would make it possible to pass custom data to Webpack configuration? I expect it would work if there was a way to pass this data to `webpack-dev-server` through a parameter. Maybe it would just set the env internally based on given parameters? Ideally this same mechanism would be used for `webpack` command as well given it's the same problem there.

**Comment by sokra** [comment]
There is a new way in the webpack-2 branch.

`--env.dev`

I write some documentation about that soon.

**Comment by bebraw** [comment]
Cool. Sounds great!
