### ISSUE TITLE
[Discussion]: Refactoring using - functional maybe - programming

### ISSUE THREAD

**Issue by anikethsaha** [webpack/webpack-dev-server#2111]
- Operating System:
- Node Version: 8
- NPM Version: 5
- webpack Version: 4.35
- webpack-dev-server Version:3.7
- Browser: Chrome 

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code
[`implementaion`](https://github.com/anikethsaha/webpack-dev-server/blob/refactor/remove-hardcoded-createConfig/lib/utils/createConfig.js)

```js
// webpack.config.js
// Will be same
```

### Expected Behavior
To remain the same

### Actual Behavior
Current behavior

### For Features; What is the motivation and/or use-case for the feature?
As in the `lib/utils/createConfig.js`, there are quite a few numbers of the same code ( like - if statements to check whether the property exists or not) are present. There is absolutly no perf diff in refactoring them but we can make the number of line of code to quite a few using functional programming like looping through the args and just adding it to `this.options` , it willl automatically add those only which exist there. no need for these many lines of code
This is just overviewing if we are open with this kind of refactoring 
ALSO
I think refactoring to these kinds of code should not increase any kind of perf load but still, I am **not** 100% on that

Need @evilebottnawi @hiroppy 's thoughts on this whether it would be a good idea or not?

PS: in the implementation, there are few missed case I think cause few of the tests are failing but it can resolve it seems

**Comment by evilebottnawi** [comment]
I think we don't need `functional` programming here, just move duplicate code in other util

**Comment by anikethsaha** [comment]
Okay !
