### ISSUE TITLE
Vulnerability 1012

### ISSUE THREAD

**Issue by dalefrancis88** [webpack/webpack-dev-server#2118]
Team,

https://www.npmjs.com/advisories/1012 was just raised today. It looks like it's based in `http-proxy-middleware` do you guys have an estimate on how long you think it'll take to get a release out that'll resolve this?

it looks like `cache-base` may be the bottleneck here

**Comment by evilebottnawi** [comment]
It is development server, so this security problem is not high priority here, also we don't use `set-value` directly so we can't do something on our side, please open issue in `cache-base`, sorry

**Comment by dalefrancis88** [comment]
I did, i actually created a PR but i was curious if you guys were actively engaging is all

**Comment by evilebottnawi** [comment]
Let's keep open for tracking

**Comment by mixtur** [comment]
For me it looks like I suddenly went from 0 vulnerabilities to uh... 765? I gues there is сombinatorial explosion here because dependencies are all messed up.
Ok, maybe there is no real vulnerability here. But If there was now, I would have definitely missed it behind these 765.

**Comment by evilebottnawi** [comment]
Problem was on npm side, now we doesn't have any vulnerability, thanks for issue
