### ISSUE TITLE
proxy server does not work

### ISSUE THREAD

**Issue by SephVelut** [webpack/webpack-dev-server#2126]
- Operating System: OSX
- Node Version: v12.6.0
- NPM Version: 6.9.0
- webpack Version: 4.28.4
- webpack-dev-server Version: 3.7.2
- Browser: chrome Version 75.0.3770.100

- [x] This is a **bug**
- [ ] This is a **modification** request

Given 
```
module.exports = {
  devServer: {
    proxy: {
      '/login': {
        target: 'http://localhost:8000',
        changeOrigin: true,
        logLevel: 'debug'
      }
    }
  }
}
```

The dev server successfully proxies the request to localhost:8000 backend server. I see the request reaches the backend server and the backend server responds with
```
HTTP/1.1 202 Accepted
Content-Length: 0
Date: Tue, 16 Jul 2019 02:55:17 GMT
Server: MyServer
```

Despite that, the webpack dev server errors out with `Proxy error: Could not proxy request /login from localhost:8080 to http://localhost:8000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).` 

The Ajax request on the javascript side receives a 500 http error.

**Comment by evilebottnawi** [comment]
You don't provide minimum reproducible test repo as described in issue template so we can't help, you can see `ECONNRESET` error - what mean you server reset connection, or something other on this host:port reset connection. Without reproducible test repo we can't help

**Comment by SephVelut** [comment]
Here is a [minimal reproducible test repo ](https://github.com/SephVelut/webpack-proxy-issue)
Here us a [webm](https://streamable.com/ixlqn) of the issue as I'm executing it

**Comment by SephVelut** [comment]
So it appears that the proxy dev server expects the tcp connection to remain connected after the backend server sends its response. Am I supposed to just hold the connection resource open, for every single new connection from the proxy server, permanently on my server? I would not like to do this. Is this expected? Is this configurable?

**Comment by hiroppy** [comment]
@SephVelut Can you explain how to occur this problem using your repository? I would like to know the procedure because your minimal test repository doesn't have README.

**Comment by SephVelut** [comment]
@hiroppy I agree, the repo should include an example server that the proxy uses to talk to as it's an important piece. Right now I don't have time so I'm going to close this issue, until I can address it again in the future.
