### ISSUE TITLE
Specify proxy through cli

### ISSUE THREAD

**Issue by MikaAK** [webpack/webpack-dev-server#213]
I'm having an issue where my webpack-dev-server won't use my proxy options from my `webpack.config.js` and I was wondering if there's a way instead to specify it through the cli. 

In my config from the file I set the proxy like this and use the following cli call from node. These options don't work for some reason so I figured creating the proxy via the cli call would be the best option
```javasript
childProcess.spawn('webpack-dev-server', [
   '--content-base', buildDir,
   '--port', PORT,
   '--config', configFile,
   '--colors',
   '--inline',
   '--hot',
   '--history-api-fallback'
], {cwd: clientPath, stdio: 'inherit'})
```
```javascript
devServer: {
  proxy: {
    '/api/*': 'http://localhost:4000'
  }
}
```

**Comment by ianor** [comment]
Seeing same issue here. Were you able to figure out any kind of work-around?

**Comment by MikaAK** [comment]
@ianor No solution here, it just started working. Though the display from the cli doesn't display that it is working. In my previous tests I would see `Forwarding /api/* to localhost:4000` or something simliar, now I've got it working but it doesn't display anything.

**Comment by ianor** [comment]
Cool.  I ended up going the other direction and having my express server forward requests to webpack-dev-server. There's a little more set up but it's working well now.  Followed the outline [HERE](http://www.christianalfoni.com/articles/2015_04_19_The-ultimate-webpack-setup). Good luck and happy coding!

**Comment by stevehu** [comment]
@MikaAK I have tried the same setup but it never worked for me. Have you update any npm modules to make it work? Calling http proxy is very simple but the developer just over engineered it to make the configuration so complicated without providing samples and document. My workaround is to bypass the config and update the server to call my proxy if uri starts with /api

**Comment by watsoncj** [comment]
It appears that the webpack-dev-server proxy can't be defined in `webpack.config.js`. It is ignored since webpack isn't aware of a proxy feature.

The proxy option needs to be passed directly to a `WebpackDevServer` via something like [grunt-webpack](https://github.com/webpack/grunt-webpack).

[See example in API documentation](https://webpack.github.io/docs/webpack-dev-server.html#api)

**Comment by MikaAK** [comment]
@watsoncj it actually can. This is from our `webpack.config.js`

```
var config = {
  ...
  devServer: {
    proxy: [{
      path: '/api/*',
      target: 'http://localhost:3000'
    }],

    historyApiFallback: {
      rewrites: [{
        from: /\/auth.*/,
        to: '/auth.html'
      }, {
        from: /\/external.*/,
        to: '/external.html'
      }, {
        from: /(\/school)?.*/,
        to: '/school.html'
      }]
    }
  }
}
```
