### ISSUE TITLE
can webpack-dev-server work with nginx?

### ISSUE THREAD

**Issue by LIUeng** [webpack/webpack-dev-server#2132]
- Operating System: macOS
- Node Version: v10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.28.3
- webpack-dev-server Version: ^3.7.2
- Browser: chrome 75.0.3770.100

- [ ] This is a **bug**
- [ ] This is a **modification** request
- [x] This is a problem about can webpack-dev-server work with nginx?

### Code

```md
listen          80;
server_name     hello.world.cn;
...
location / {
        proxy_pass  http://127.0.0.1:3001;
    }

location /sockjs-node/ {
        proxy_pass http://127.0.0.1:3001/sockjs-node/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";	
    }
```
### Expected Behavior

when I visit the "hello.world.cn" on the chrome browser, not have the sockPort, if visit "hello.world.cn:3001", it is ok!  The sockjs-client can work, the HMR also works ok, but "http://ipaddress/sockjs-node/info?t=xxxx" is polling all the time 404(Not Found)

### Actual Behavior

The "http://ipaddress/sockjs-node/info" can work with no 404, how can I config? Can webpack-dev-server work with nginx? Thank you help!

### For Bugs; How can we reproduce the behavior?

NO

### For Features; What is the motivation and/or use-case for the feature?

webpack-dev-server with nginx solve the proxy problem

**Comment by evilebottnawi** [comment]
Yes, proxy works with any webserver, you need setup nginx to accept websocket connects

**Comment by simkessy** [comment]
Any examples? I'm having issues where the client app is running on port 8080 but updates served by devServer are on port 10005 and I keep getting 404s and can't find documentation on how to address this

**Comment by corytheboyd** [comment]
Hey @simkessy I figured out the proper nginx configuration for websocket connection upgrade. I haven't tested this in isolation (just pulling it from a codebase I was recently working on) but maybe it will help:

```
ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers         HIGH:!aNULL:!MD5;

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    location /wss/ {
        proxy_pass http://wss;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```

I stripped out all other non-wss parts of the configuration, but it just looks like you're missing the `map` declaration.

**Comment by Bkucera** [comment]
`webpack-dev-server` needs to be told the sockjs port will match the pages `window.location` port, which is done by specifying `devServer.sockPort: 'location'`

webpack.config.js:
```js
devServer {
  sockPort: 'location'
  // ...
}

```

Here's a complete `nginx.conf` that will allow you to proxy webpack-dev-server without requiring any changes other than `sockPort`

nginx.conf:
```
events {}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 4443 ssl;

    ssl_certificate cert.pem;
    ssl_certificate_key privkey.pem;


    location / {
        # webpack-dev-server port
        proxy_pass http://localhost:3000;

        proxy_http_version 1.1;
        proxy_set_header Host localhost;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
  }
}


```

If you're using docker, make sure to specify `network_mode: 'host'` so your container has access to loopback on the host machine.


docker-compose.yml:

```yaml
services:
  webpack-ssl-proxy:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/private/cert.pem:/cert.pem
      - /etc/ssl/private/provkey.pem:/privkey.pem

```

**Comment by jose-sampedro** [comment]
Hi @Bkucera 

you can put a total example or an example repository?

thanx!

**Comment by yaroslav-perec** [comment]
For v5, adding the following settings to webpack.config.js worked for me

```
    devServer: {
      client: {
        webSocketURL: 'auto://0.0.0.0:0/ws',
      }
    }
```
