### ISSUE TITLE
sockHost not being used with HMR requests

### ISSUE THREAD

**Issue by petercpwong** [webpack/webpack-dev-server#2138]
- Operating System: Ubuntu 18.04
- Node Version: 12.4
- NPM Version: 6.9
- webpack Version: 4.36.1
- webpack-dev-server Version: 3.7.2
- Browser: Chrome 75.0.3770.100

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
{
  ...baseConfig,
  devServer: {
    disableHostCheck: true,
    historyApiFallback: true,
    hot: true,
    public: 'myhost.local',
    host: 'localhost',
    port: 3000,
    sockHost: 'myhost.local',
    sockPort: 443
  }
}
```

### Expected Behavior
Bundle served by WDS should be polling HMR updates with host name using `sockHost` (eg. `myhost.local/sockjs-node/info?t=<TIMESTAMP>`)

### Actual Behavior
Some requests are sent using the correct host name (eg. `myhost.local`) but other requests are still using 'localhost' (eg. `localhost/sockjs-node/info?t=<TIMESTAMP>`). This causes WDS to get disconnected and HMR to break.

### For Bugs; How can we reproduce the behavior?
Run a reverse proxy in front of your webpack dev server with host/port settings outlined above.

**This bug only appears after webpack dev server 3.2.1. Everything works as intended in 3.2.1 with only the `public` field set and `sockHost/sockPort` left empty**

**Comment by evilebottnawi** [comment]
> Run a reverse proxy in front of your webpack dev server with host/port settings outlined above.

Please clarify - provide minimum reproducible test repo with README how we can reproduce this

**Comment by petercpwong** [comment]
I was incorrectly passing in the dev server config. Closing this.

**Comment by petercpwong** [comment]
@chaddjohnson There was originally a bug elsewhere in my code, not the config itself. What are you having trouble with specifically?

**Comment by chaddjohnson** [comment]
> @chaddjohnson There was originally a bug elsewhere in my code, not the config itself. What are you having trouble with specifically?

Thanks Peter. I figured it out by adding this the the `devServer` settings:

```
headers: {
  'Access-Control-Allow-Origin': '*'
},
sockHost: url.parse(process.env.APP_URL).host
```

What I am doing is rendering the app on a different domain (dev.mydomain.com) while tunneling to my local machine. When rendering on dev.mydomain.com, it's trying to use dev.mydomain.com/sockjs-node/info for the Hot Reload websocket, which doesn't exist, and I need to use myapp.ngrok.io/sockjs-node/info instead (I'm using a local tunnel). APP_URL is set to myapp.ngrok.io.

The settings above let me accomplish this.
