### ISSUE TITLE
Higher CPU usage with node

### ISSUE THREAD

**Issue by nodece** [webpack/webpack-dev-server#2140]
- Operating System: MacOS 10.14.1 
- Node Version: v10.16.0
- NPM Version: yarn - 1.17.3
- webpack Version: 3.8.1
- webpack-dev-server Version: 2.9.4
- Browser: Chrome

After running `webpack-dev-server`, the CPU occupancy is between 100% and 200%.

Do you have such an issue?

**Comment by rishabh3112** [comment]
@nodece please share a minimal reproducible repo and steps to reproduce.
Also, the issue is the same as #1881

**Comment by nodece** [comment]
@rishabh3112 can I send the reproducible repo to your email?

**Comment by rishabh3112** [comment]
Sharing publically would be great, that way we all can investigate for the issue. :)

**Comment by nodece** [comment]
Maybe it's caused by `mds_stores` process in MacOS.
I hope I can collect some answers here. :)

**Comment by cismous** [comment]
I have same issue
- Operating System: MacOS 10.14.5
-Node Version: v12.6.0
-Yarn Version: 1.17.3
-webpack Version: 4.29.6
-webpack-dev-server Version: 3.7.2
-cpu: i7 6700K

After running webpack-dev-server, the CPU occupancy is between 20% and 30%.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo otherwise issue was closed, thanks

**Comment by danvk** [comment]
I was able to fix this by following the advice of #1180 and installing `fsevents`:

    npm install -D fsevents

It was previously installed as a transitive dependency, but installing it explicitly made all the difference.

**Comment by briandhill** [comment]
I concur with @danvk on his remedy. Just to note, I'm running on macOS Mojave 10.14.6.

**Comment by LvChengbin** [comment]
@danvk it's not working for me, the CPU occupancy is always more than 160%

**Comment by binaryj** [comment]
Using the approach that @danvk suggested worked for me. You have to install fsevents as a dev dependency of the project you are running the webpack dev server for. My CPU usage was up around 160% prior to the install and is now around 15% post install.

**Comment by LvChengbin** [comment]
@binaryj I added more directories into the ignored list in `watchOptions`, and it's much better than before.

**Comment by binaryj** [comment]
UPDATE: I used the "fsevents" approach suggested by @danvk and it seemed to work for a few minutes, but then my CPU shot back up to 130% - 160% consistently for the node process. I then uninstalled the "fsevents" package from the project and tried @LvChengbin approach of updating my webpack config to set "watchOptions" to ignore nodeModules. I also set it to "poll" every second:

```
watchOptions: {
     poll: 1000,
     ignored: ["node_modules"]
}
```

Doing this has dropped my CPU usage for the node process to around 15% consistently now and has resolved my issue. I then reduced the "poll" frequency to 5 seconds(5000ms) instead of 1(1000ms) second and my CPU is consistently around 4% for the node process.

The approach originally suggested by @LvChengbin should be the correct answer to this issue and doesn't involve adding any new packages to your project.

**Comment by ulitiy** [comment]
If you're using `ts-loader` it's better to use `TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling webpack-dev-server` command so it forces `ts-loader` to use fsevents too.

15% consistently with no polling.

**Comment by oivinds** [comment]
I switched  from `node v10.14.0 (npm v6.4.1)` to `node v11.3.0`
My cpu is now 0,0 % when idle.

**Comment by Oshri-Garama** [comment]
Had the same problem, I had warning about gyp: No Xcode or CLT version when installed npm.
The solution is in here:
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
reinstall Xcode.

**Comment by sreuter** [comment]
This really needs to be addressed in webpack itself, by updating the `chokidar` dependency to 3.x.

**Comment by hiroppy** [comment]
We can't update chokidar to the major version because it's breaking changes, but we'll upgrade it when we release the major version of webpack-dev-server. Please wait.

**Comment by joelrbrandt** [comment]
> Had the same problem, I had warning about gyp: No Xcode or CLT version when installed npm.
> The solution is in here:
> https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
> reinstall Xcode.

For me, on Catalina, simply running `sudo xcode-select --reset` resolved the gyp problems for building fsevents.

**Comment by cubbK** [comment]
I had this problem because I also had watchmen installed. Running `brew uninstall watchman` helped for me 🤔

**Comment by jeffreyvanhees** [comment]
I cleard the Notification Center cache and the problem disappeared immediately.

```cd $TMPDIR
cd ..
cd 0
sudo rm -rf ./com.apple.notificationcenter
killall NotificationCenter; killall usernoted```

**Comment by wayneforrest** [comment]
I did the following to reduce my node CPU usage on MacOS Big Sur; it went from 40% down to 0% when idle.

` npm install fsevents@2.3.2`

```
-    "fsevents": "^1.2.12",
+    "fsevents": "^2.3.2",

```

**Comment by chrisfcarroll** [comment]
( I wonder if there are multiple issues involved. It seems to me that `npm install` triggers heavy CPU usage by `mds_stores` )

**Comment by eliozashvili** [comment]
> UPDATE: I used the "fsevents" approach suggested by @danvk and it seemed to work for a few minutes, but then my CPU shot back up to 130% - 160% consistently for the node process. I then uninstalled the "fsevents" package from the project and tried @LvChengbin approach of updating my webpack config to set "watchOptions" to ignore nodeModules. I also set it to "poll" every second:
> 
> ```
> watchOptions: {
>      poll: 1000,
>      ignored: ["node_modules"]
> }
> ```
> 
> Doing this has dropped my CPU usage for the node process to around 15% consistently now and has resolved my issue. I then reduced the "poll" frequency to 5 seconds(5000ms) instead of 1(1000ms) second and my CPU is consistently around 4% for the node process.
> 
> The approach originally suggested by @LvChengbin should be the correct answer to this issue and doesn't involve adding any new packages to your project.

how can I install that watchOptions? or where should I write that code? :(

**Comment by xeroxstar** [comment]
I know it sounds silly but after I changed the "mode" to "development" from "production" the webpack speed increased by 70%. Running in production mode can add some build time cost because doing this minification, dead code elimination, etc.

**Comment by cklee75** [comment]
> > UPDATE: I used the "fsevents" approach suggested by @danvk and it seemed to work for a few minutes, but then my CPU shot back up to 130% - 160% consistently for the node process. I then uninstalled the "fsevents" package from the project and tried @LvChengbin approach of updating my webpack config to set "watchOptions" to ignore nodeModules. I also set it to "poll" every second:
> > ```
> > watchOptions: {
> >      poll: 1000,
> >      ignored: ["node_modules"]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Doing this has dropped my CPU usage for the node process to around 15% consistently now and has resolved my issue. I then reduced the "poll" frequency to 5 seconds(5000ms) instead of 1(1000ms) second and my CPU is consistently around 4% for the node process.
> > The approach originally suggested by @LvChengbin should be the correct answer to this issue and doesn't involve adding any new packages to your project.
> 
> how can I install that watchOptions? or where should I write that code? :(

@eliozashvili,
Normally is under `webpack.dev.js`.

**Comment by jakubferenc** [comment]
> > UPDATE: I used the "fsevents" approach suggested by @danvk and it seemed to work for a few minutes, but then my CPU shot back up to 130% - 160% consistently for the node process. I then uninstalled the "fsevents" package from the project and tried @LvChengbin approach of updating my webpack config to set "watchOptions" to ignore nodeModules. I also set it to "poll" every second:
> > ```
> > watchOptions: {
> >      poll: 1000,
> >      ignored: ["node_modules"]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Doing this has dropped my CPU usage for the node process to around 15% consistently now and has resolved my issue. I then reduced the "poll" frequency to 5 seconds(5000ms) instead of 1(1000ms) second and my CPU is consistently around 4% for the node process.
> > The approach originally suggested by @LvChengbin should be the correct answer to this issue and doesn't involve adding any new packages to your project.
> 
> how can I install that watchOptions? or where should I write that code? :(

If you're using Vue CLI with Vue 2, you will add the `watchOptions` property to `configureWebpack` property. So it can look like this:
```
module.exports = {
  configureWebpack: {
    watchOptions: {
      poll: 1000,
      ignored: /node_modules/,
    },
    resolve: {
      extensions: ['.ts', '.js', '.vue'],
    },
  },
};
```
