### ISSUE TITLE
Response is always compressed with gzip

### ISSUE THREAD

**Issue by josias-r** [webpack/webpack-dev-server#2141]
- Operating System: Windows 10
- Node Version: 10.16.9
- NPM Version: 6.10.1
- webpack Version: ^4.35.3
- webpack-dev-server Version: ^3.7.2
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
devServer: {
    publicPath: `${options.publicPath}/assets/`,
    clientLogLevel: "silent",
    hot: true,
    inline: true,
    // compress: true,
    proxy: {
      "**": {
        selfHandleResponse: true,
        target: "http://localhost:8000",
        changeOrigin: true,
        onProxyRes: proxyRes
      }
    }
  },
```

```js
const proxyRes = (proxyRes, req, res) => {
  let body = new Buffer.from("");
  proxyRes.on("data", data => {
    body = Buffer.concat([body, data]);
  });
  proxyRes.on("end", () => {
    res.writeHead(200, {
      "Content-Type": "text/html" //,
      // "Content-Encoding": "gzip"
    });
    res.end(body);
  });
};
```

### Expected Behavior
The above config should display the page properly .

### Actual Behavior
Without the `Content-Encoding: gzip`header, the response body is just random characters, therefore the response seems to be gzipped even without the `compress: true` flag.

### For Bugs; How can we reproduce the behavior?
With the above config.

**Comment by josias-r** [comment]
Is it possible that I always get a gzipped response, because the URL I'm proxying is gzipped? 🤔

**Comment by evilebottnawi** [comment]
Yes, because, it is problem not related to webpack-dev-server, you proxy server gzipped response so you got gziped response, we can't do something on our side
