### ISSUE TITLE
Feature request: Add option to suppress the status display

### ISSUE THREAD

**Issue by muffinresearch** [webpack/webpack-dev-server#218]
We're currently using webpack hot module reloading in some modal dialogues. It would be handy to have the option to suppress the status of module loading to avoid the ui being pushed down by the iframe parent. We could rely on console logging to know what's going on.

**Comment by SpaceK33z** [comment]
If you want to rely only on the console, you should not use `http://localhost:<port>/webpack-dev-server/`, but just `http://localhost:8080/`.
