### ISSUE TITLE
我搭建的webpack-dev-server运行一定时间后就会卡死

### ISSUE THREAD

**Issue by mangoZT** [webpack/webpack-dev-server#2184]
- Operating System:win10
- Node Version:v10.16.0
- NPM Version:6.9.0
- webpack Version:4.29.6
- webpack-dev-server Version:3.7.2
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
 devServer: {
        publicPath: '/', // 存放的路径
        host: '0.0.0.0',
        port: '8000',
        compress: true,
        useLocalIp: true,
        hot: true,
        historyApiFallback: true, // 解决启动后刷新404
        proxy
    },
```js
// additional code, remove if not needed.
```

**Comment by mangoZT** [comment]
![image](https://user-images.githubusercontent.com/26948222/62761216-a36ba380-bab8-11e9-855e-de32104b4287.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Please use English language

**Comment by pengliheng** [comment]
same problem with me.

**Comment by mangoZT** [comment]
> same problem with me.

colse eslint cache
