### ISSUE TITLE
My webpack-dev-server was running for a while, but it jammed and occupied the port and needed to kill the process

### ISSUE THREAD

**Issue by mangoZT** [webpack/webpack-dev-server#2187]
Operating System:win10
Node Version:v10.16.0
NPM Version:6.9.0
webpack Version:4.29.6
webpack-dev-server Version:3.7.2
Browser:chrom

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
devServer: {
publicPath: '/', // 存放的路径
host: '0.0.0.0',
port: '8000',
compress: true,
useLocalIp: true,
hot: true,
historyApiFallback: true, // 解决启动后刷新404
proxy
},
```js
// additional code, remove if not needed.
```

**Comment by mangoZT** [comment]
![image](https://user-images.githubusercontent.com/26948222/62819301-de87d880-bb85-11e9-8e03-7589793b6e9a.png)
The node process must be killed before it can be restarted

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

If you again create issue with incomplete issue template we will ban you, PLEASE full issue template
