### ISSUE TITLE
"Error: Watching remote files is not supported" on windows with latest

### ISSUE THREAD

**Issue by docteurzoidberg** [webpack/webpack-dev-server#2190]
- Operating System: Windows 10
- Node Version: 10.16.1
- NPM Version: 6.10.3
- webpack Version: 4+
- webpack-dev-server Version: 3.8.0
- Browser: none

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

'npm run serve' should work like always

### Actual Behavior

'npm run serve' give me an "Error: Watching remote files is not supported.". 
-> I cannot build / run anything with the dev-server

### For Bugs; How can we reproduce the behavior?

Running 'npm run serve' on any vue-cli boilerplate webapp

**Comment by evilebottnawi** [comment]
Looks you try to watch remove files

> Running 'npm run serve' on any vue-cli boilerplate webapp

Sorry, i can't reproduce nothing, please create **minimum** reproducible test repo or provide your configuration

**Comment by docteurzoidberg** [comment]
https://github.com/vuejs/vue-cli/issues/4424

**Comment by evilebottnawi** [comment]
@docteurzoidberg still no configuration

**Comment by docteurzoidberg** [comment]
@evilebottnawi i haven't any, it's the default vue-cli project !

**Comment by docteurzoidberg** [comment]
@evilebottnawi > I found the bug; it's because of the pwd of my project: "c:\dev\test-broken" 
It doesn't work on windows when parent dir is named DEV xD
I moved it elsewhere and now it works flawlessly, in another folder....

**Comment by evilebottnawi** [comment]
need investigate, maybe wrong regexp

**Comment by evilebottnawi** [comment]
Thanks for more infromation which can help us

**Comment by docteurzoidberg** [comment]
https://i.imgur.com/etToqUI.png not working in c:\dev\test-broken
https://i.imgur.com/w4sHePq.png working in c:\users\drzoid\test-broken

Same project, working in any other folder with no "dev" parent folder

**Comment by evilebottnawi** [comment]
@docteurzoidberg can you provide you project, or minimum reproducible test repo, it can help fix problem fastly, thanks

**Comment by docteurzoidberg** [comment]
sorry, i don't have git to publish on windows setting, i'm at camping right now. i can do it next week.

The project is done with vue-cli ("npm install vue-cli -g"), then "vue init test-broken"

**Comment by evilebottnawi** [comment]
@docteurzoidberg no additional configurations?

**Comment by docteurzoidberg** [comment]
> 
> 
> @docteurzoidberg no additional configurations?

absolutly not, i was testing, all default settings from sample project

**Comment by evilebottnawi** [comment]
Thanks, we will look on this in near future

**Comment by docteurzoidberg** [comment]
seems to depend entierly on path
some fails, some others don"t....
https://i.imgur.com/oQpvSuK.png

**Comment by docteurzoidberg** [comment]
Seems that it's the "is-absolute-url" module (used in server.setupWatchStaticFeature) wich returns true for some windows path and cause the bug:

https://i.imgur.com/vlb0L1E.png

**Comment by n0code** [comment]
I think this issue about webpack-dev-server

https://stackoverflow.com/questions/57449355/how-to-fix-error-watching-remote-files-is-not-supported-problem-in-visual-stu

**Comment by hiroppy** [comment]
I cannot reproduce this issue using MacOS. maybe only Windows.
I think a related pr is https://github.com/webpack/webpack-dev-server/pull/1980.
vue-cli is [here](https://github.com/vuejs/vue-cli/blob/c76d2e691d8ea58b219394ca7799f50d873b8588/packages/%40vue/cli-service/lib/commands/serve.js#L169).

In addition, We checked an URL strictly from this pr.

**Comment by wjw99830** [comment]
webpack-dev-server/lib/Server.js:
```javascript
if (isAbsoluteUrl(String(contentBase)) || typeof contentBase === 'number') {
  throw new Error('Watching remote files is not supported.');
}
```
Here the contentBase is default value(`process.cwd()`) which is absolute url, so you should specified a relative path in vue.config.js or webpack.config.js:
```javascript
devServer: {
    contentBase: './public'
}
```

**Comment by evilebottnawi** [comment]
I think it is regression, we need fix it, PR, welcome, it is easy

**Comment by sodatea** [comment]
My reply in the Vue CLI issue thread:
> False-positive in https://github.com/sindresorhus/is-absolute-url (webpack-dev-server changed from testing `/https?:/` to using this library in the 3.8 release)
>
> Please report to that repository.
>
> I believe it's because of the lower case `c`. But how come the lower case volume label? I thought it would always be UPPER CASE.

**Comment by evilebottnawi** [comment]
@sodatea thanks for investigate,  what is the `contentBase` value you have? Just for infromation

**Comment by sodatea** [comment]
@evilebottnawi In Vue CLI it's set to the user's public folder path, and it's an absolute path.

**Comment by evilebottnawi** [comment]
@sodatea i know, just want to see you `contentBase`

**Comment by sodatea** [comment]
@evilebottnawi 😂I've never encountered such issues. I was just investigating based on the information @docteurzoidberg provided.

**Comment by mnlj** [comment]
Came across the same issue, when running fresh new project from `c:\work\project` it fails, when it's from `C:\work\project` it works. I believe webpack-dev-server already had similar Windows path case-sensitivity issue last year.

**Comment by evilebottnawi** [comment]
@mnlj Yes, we had such a problem for a long time, before we check on absolute url only when you use contentBase as string, in webpack-dev-server@3.8.0 we start to check when you use array, so problem appears

**Comment by docteurzoidberg** [comment]
> 
> 
> Came across the same issue, when running fresh new project from `c:\work\project` it fails, when it's from `C:\work\project` it works. I believe webpack-dev-server already had similar Windows path case-sensitivity issue last year.

it definitely has since i got similar result to my error message on stackoverflow and i saw people having problem on older versions in webpack 3

**Comment by evilebottnawi** [comment]
Anyway PR welcome :+1:

**Comment by viruscamp** [comment]
To reproduce the issue, create the file below, and run it with node.
node start-test.js
```javascript
require('child_process').execSync('npm run serve', {
  cwd: 'c:\\work\\project\\',
  stdio: ['inherit', 'inherit', 'inherit']
})
```

**Comment by evilebottnawi** [comment]
Should be solved, just update deps
