### ISSUE TITLE
Accessing localhost via devserver stopped working: ERR_UNSAFE_REDIRECT

### ISSUE THREAD

**Issue by kmaraz** [webpack/webpack-dev-server#2192]
- Operating System:
Windows 10 64bit
- Node Version:
v12.1.0
- NPM Version:
6.9.0
- webpack Version:
4.39.1
- webpack-dev-server Version:
3.8.0
- Browser:
Chrome Version 76.0.3809.100 (Official Build) (64-bit)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  
module.exports = (env, argv) => {

  const config = {

    devServer: {
      allowedHosts: ['localhost', 'local.sli.do', 'admin.local.sli.do'],
      historyApiFallback: true,
      hot: true,
      https: true,
      port: 443,
      public: 'localhost:443'
    },
  };

  return config;
}

```

### Expected Behavior
When I use URL https://localhost/#/something it serves redirects me to https://localhost/something and it works fine. When I want to open https://localhost/something directly, it should serve the content.

### Actual Behavior
When I go directly to https://localhost/something I see an error ERR_UNSAFE_REDIRECT and no content is served.

### How can we reproduce the behavior?
Just run: node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --mode=development --config=webpack.config.dev.js

**Comment by kmaraz** [comment]
Version 3.7.2 works without any problem with the same configuration.

**Comment by evilebottnawi** [comment]
Try to disable `historyApiFallback`

**Comment by kmaraz** [comment]
@evilebottnawi nothing changed as far as I can tell.

**Comment by evilebottnawi** [comment]
It is full webpack-dev-server configuration?

**Comment by kmaraz** [comment]
@evilebottnawi no, but I was able to simulate it with this minimal config as well, so I have pasted only this configuration.

**Comment by evilebottnawi** [comment]
@kmaraz please provide full configuration for webpack-dev-server you have deprecated message, but i can't see any option related to this

**Comment by kmaraz** [comment]
@evilebottnawi I is not much different.
```
const path = require('path');

module.exports = (env, argv) => {

  const context = path.resolve(__dirname, './app');

   const config = {
    context: context,

    entry: {
      app: path.resolve(context, './index'),
    },

    resolve: {
      alias: {},
      modules: ['app', 'node_modules'],
      extensions: ['.js']
    },

    devServer: {
      allowedHosts: ['localhost', 'local.sli.do', 'admin.local.sli.do'],
      historyApiFallback: true,
      hot: true,
      https: true,
      port: 443,
      public: 'localhost:443'
    },

    devtool: 'nosources-source-map',
    target: 'web'
  };

  return config;
}
```
```
SET NODE_ENV=development
node --max_old_space_size=10092 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --mode=development --config=webpack.config.dev.js
```
![image](https://user-images.githubusercontent.com/6079654/62949923-61f43480-bde7-11e9-9c1f-0d6f61bfd69f.png)

**Comment by evilebottnawi** [comment]
Thanks

**Comment by IdeaHunter** [comment]
Hit possibly same problem, downgrading to 3.7.2 made my code works without any changes, problem appeared after upgrade 3.1.10 -> 3.8.0

**Comment by evilebottnawi** [comment]
Pr welcome if you want so solve this asap

**Comment by IdeaHunter** [comment]
@evilebottnawi not urgent - i was trying to see if problem with websocket connection reset that was causing to proxy stop working is fixed in new version(it wasnt). Im now working with downgraded version of dev server.

**Comment by AlanZou007** [comment]
`host: process.env.HOST || '0.0.0.0'`

**Comment by alecgibson** [comment]
I specifically only get this issue when I attempt to access my app through Chrome's "remote devices" tab with ports forwarded. Weirdly, accessing it on a remote device also suddenly makes the host computer stop working too (whereas without a remote device, the host works fine).

**Comment by alexander-akait** [comment]
Fixed in master
