### ISSUE TITLE
Add ability to configure the socket.io path

### ISSUE THREAD

**Issue by mingfang** [webpack/webpack-dev-server#220]
I'm running the webpack-dev-server behind a proxy server and need to change the default socket.io path from 
```/socket.io``` to ```/<myapp>/socket.io```.

Is this possible?

**Comment by vectart** [comment]
+1

**Comment by michaelzoidl** [comment]
+1

**Comment by syranide** [comment]
+1, somewhat related #46

**Comment by syranide** [comment]
I've put up a PR #240 for this.

**Comment by frontengineer** [comment]
+1

**Comment by syranide** [comment]
#240 merged

**Comment by mingfang** [comment]
#240 is a huge setup forward but it's not enough.
Setting host to window.location.host works.
But we also need to set port to window.location.port.
```
port: urlParts.port ? urlParts.port : window.location.port
```

**Comment by SpaceK33z** [comment]
Setting the port was fixed in #430, which will be part of a 1.x release.
