### ISSUE TITLE
webpack-dev-server uses vulnerable versions (via dependencies) of lodash, set-value and mixin-deep

### ISSUE THREAD

**Issue by michdsouza** [webpack/webpack-dev-server#2211]
- Operating System: Mac OS 10.14.5
- Node Version: 11.12.0
- NPM Version: 6.7.0
- webpack Version: 4.0.4
- webpack-dev-server Version: 3.1.11
- Browser: All

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

N/A

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

webpack-dev-server should use updated versions of its dependencies that have the patched versions of lodash (>=4.17.12), set-value (>=3.0.1), and mixin-deep (>=2.0.1)

### Actual Behavior

webpack-dev-server uses vulnerable versions (via dependencies) of lodash, set-value and mixin-deep. 

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | lodash                                                                    |
| Patched in    | >=4.17.12                                                                 |
| Dependency of | webpack-dev-server                                                        |
| Path          | webpack-dev-server > http-proxy-middleware > lodash                       |
| More info     | https://www.npmjs.com/advisories/1065                                     |

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | set-value                                                                 |
| Patched in    | >=2.0.1 <3.0.0 || >=3.0.1                                                 |    
| Dependency of | webpack-dev-server                                                        |
| Path          | webpack-dev-server > chokidar > anymatch > micromatch >                   │
│               │ braces > snapdragon > base > cache-base > set-value                       |
| More info     | https://www.npmjs.com/advisories/1012                                     |

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | mixin-deep                                                                |
| Patched in    | >=1.3.2 <2.0.0 || >=2.0.1                                                 |    
| Dependency of | webpack-dev-server                                                        |
| Path          | webpack-dev-server > chokidar > anymatch > micromatch >                   |
│               │ braces > snapdragon > base > mixin-deep                                   |
| More info     | https://www.npmjs.com/advisories/1013                                     |

### For Bugs; How can we reproduce the behavior?
Running a `yarn audit` provides this information

**Comment by evilebottnawi** [comment]
Update your deps

**Comment by evilebottnawi** [comment]
`Running `npm audit` on latest deps output:
```
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
```
