### ISSUE TITLE
Config host and open

### ISSUE THREAD

**Issue by PierBJX** [webpack/webpack-dev-server#2226]
- Operating System: Windows 10 Pro
- Node Version: 10.15.3
- NPM Version: 6.10.1
- webpack Version: 4.34.0
- webpack-dev-server Version: 3.7.1
- Browser: Opera

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
devServer: {
    host: '0.0.0.0',
    port: 4002,
    overlay: true,
    open: true
}
```

### Expected Behavior
I add the `host: '0.0.0.0'` in order to access the server via my IP address.
I add `open: true` in order to open the page in my browser automatically.
`webpack-dev-server` should open a tab with a proper url.

### Actual Behavior
It opens the page in the browser with this url: `0.0.0.0:4002`.
If I remove `host: '0.0.0.0'` from the config, I can not open the page with my url address anymore but only with localhost.

**Comment by Loonride** [comment]
@PierBJX Try using the `openPage` option to specify the URL you want to open (https://webpack.js.org/configuration/dev-server/#devserveropenpage). The `open` option just tries to infer the URL you want using the `host` option.

**Comment by PierBJX** [comment]
Thanks @Loonride it works now 🥇 

```
  devServer: {
    host: '0.0.0.0',
    port: 4002,
    overlay: true,
    open: true,
    openPage: 'http://localhost:4002'
  }
```

**Comment by evilebottnawi** [comment]
@Loonride maybe we should handle this case, what are you thinking?

**Comment by Loonride** [comment]
> @Loonride maybe we should handle this case, what are you thinking?

Yes, should it just be this particular case where `0.0.0.0` becomes `localhost`? Because if `0.0.0.0` is the host option, we don't have any better guess as to what the user wants.
