### ISSUE TITLE
TypeError: Cannot read property 'headers' of null at Server.socket.on (***/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:68:32)

### ISSUE THREAD

**Issue by qyjs** [webpack/webpack-dev-server#2242]
TypeError: Cannot read property 'headers' of null at Server.socket.on (***/node_modules/webpack-dev-server/lib/servers/SockJSServer.js:68:32)

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-dev-server/commit/79649971c299f648fdd0ba3d4513a8cf7fc881d2, in near future we will be doing patch release

**Comment by davidm1766** [comment]
When will be patch release?

**Comment by tapaswi** [comment]
> Fixed [7964997](https://github.com/webpack/webpack-dev-server/commit/79649971c299f648fdd0ba3d4513a8cf7fc881d2), in near future we will be doing patch release

Even I am facing the same issue!
Is patch release done?

**Comment by evilebottnawi** [comment]
Update deps please

**Comment by k3RetailDaveIzon** [comment]
I too am getting this issue when running ng serve. Its ok for awhile then crashes out with:

TypeError: Cannot read property 'headers' of null
\node_modules\webpack-dev-server\lib\servers\SockJSServer.js:67
      f(connection, connection.headers);

**Comment by tapaswi** [comment]
> Update deps please

I am facing this issue since i upgraded angular 6 app to angular 8 and I had used angular cli to create an application. 
Now which dependency should I update? 
As I don't use webpack directly, Is it that I should go for updating @angular-devkit/build-angular?

**Comment by k3RetailDaveIzon** [comment]
If you follow the link above by tapaswi, this will fix your issue.
