### ISSUE TITLE
Exit code 255 with --help flag?

### ISSUE THREAD

**Issue by lauritzsh** [webpack/webpack-dev-server#225]
I was trying to `grep` to find the option flag for `--history-api-fallback`:  
`webpack-dev-server --help | grep api`  
but I would just get the complete list of options instead.

Using `$?` I see it exits with code 255 so `grep` doesn't pick it up. Instead I have to:  
`webpack-dev-server --help 2>&1 | grep api`

Is this by design? What's the reason for using 255?

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L14

send a PR.

**Comment by SpaceK33z** [comment]
Tested this, it is happening in 1.x, but is fixed in 2.x because of the switch to `yargs`.
