### ISSUE TITLE
sockjs-node/info failed when have subdirectory

### ISSUE THREAD

**Issue by melodyfang** [webpack/webpack-dev-server#2251]
- Operating System:
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.39.2
- webpack-dev-server Version: 3.8.0
- Browser: Chrome

- [x] This is a **bug** 
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
devServer: {
    contentBase: path.resolve(__dirname, '../dist/'),
    compress: true,
    watchContentBase: true,
    public: '0.0.0.0/service',
    historyApiFallback: {
      rewrites: [
        { from: /./, to: '/index.html' }
      ]
    },
    disableHostCheck: true,
    host: '0.0.0.0',
    port: 8082,
    hot: true,
    hotOnly: true,
    quiet: true,
    inline: true
  },
```

My project has subdirectory, for example my.domain.com/service, 
hot module replacement is working when access through localhost:8082/service,
but it is not working when access through my.domain.com/service,
Who can help me？

### Expected Behavior
hot module replacement can work when access through my.domain.com/service
### Actual Behavior
hot module replacement not work, sockjs-node/info failed
### For Bugs; How can we reproduce the behavior?
just domain has subdirectory, can  reproduce

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
You need use `host`: 'my.domain.com' and add this in hosts file
