### ISSUE TITLE
development server renders blank view when index.html has last modified date set in the future

### ISSUE THREAD

**Issue by kyeotic** [webpack/webpack-dev-server#2253]
- Operating System: MacOS 10.14.6
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.39.1
- webpack-dev-server Version: 3.2.1
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I am crossposting [this issue](https://github.com/facebook/create-react-app/issues/7212) from Create-React-App

### Steps to Reproduce
1. `npm install -g create-react-app`
2. `create-react-app 190611-cra && cd create-react-app 190611-cra`
3. `touch -t 299901011200 public/index.html`
4. `npm start`

### Expected Behavior
The devserver will render the default app

### Actual Behavior
A blank screen is rendered without errors in the console:

![Screen Shot 2019-06-13 at 12 41 10 PM](https://user-images.githubusercontent.com/331833/59462677-1dddb700-8dd9-11e9-9262-39a3eacff99e.png)

If you then refresh the page, it will start rendering, but this is not intended.

If you `touch public/index.html`, it will also render, but this should not be necessary.

![Screen Shot 2019-06-13 at 12 41 31 PM](https://user-images.githubusercontent.com/331833/59462837-66957000-8dd9-11e9-82d0-2a6984ed4ec0.png)

### Reproducible Demo
The steps to reproduce are already comprehensive

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by rishabh3112** [comment]
@evilebottnawi I would like to work on it, where should I start ?

**Comment by evilebottnawi** [comment]
@rishabh3112 need investigate why it is happens :smile:
