### ISSUE TITLE
webpack outside folder index.html 

### ISSUE THREAD

**Issue by VCodepp** [webpack/webpack-dev-server#2255]
Hi everyone,

Apart from the dist folder, I have another folder called demo. and this demo folder contains the index.html file.

When I run demo / index.html with dev server, I can't find the files in the dist folder.

folder structure;

```
/ demo
  - index.html
/ dist
 - bundle.js
/ src 
 - index.js
```

webpack.dev.js :

```
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, './dist'),
    publicPath: '/',
  },
  mode: 'development',
  devServer: {
    open: true,
    hot: true,
    contentBase: path.resolve(__dirname, './demo'),
    port: 9000,
  },
 ...
```

I want to refresh the browser every time I make a change in the src folder.

**Comment by Loonride** [comment]
@VCodepp try `writeToDisk: true` in your `devServer` config to get the bundle in your `dist` folder (https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-). Is that what you are going for?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Answer above.
