### ISSUE TITLE
Document the output directory for devServer.writeToDisk option

### ISSUE THREAD

**Issue by bseib** [webpack/webpack-dev-server#2264]
### Note: This is a documentation-only related request -- i.e. no code

- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version:
- webpack-dev-server Version: 3.1.0+
- Browser: any

- [ ] This is a **bug**
- [x] This is a **modification** request

### Current documentation:

https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-

![image](https://user-images.githubusercontent.com/1313561/65883875-e1bd6a80-e365-11e9-8d48-755b0e6496b1.png)

### Expected Behavior

The docs should tell us where to find the files that get written to disk.

### Actual Behavior

It is not clear where to find the files that were generated by webpack-dev-server, and the `writeToDisk` docs are the perfect place to spell it out.

### For Features; What is the motivation and/or use-case for the feature?

Webpack is a lot to take in, especially to the newcomer. So every bit of detail on how a thing works makes a big difference. 😄

**Comment by evilebottnawi** [comment]
Please open issue in webpack docs repo, anyway you can find files in you `output`directory as you do for build without dev server
