### ISSUE TITLE
Open multiple windows

### ISSUE THREAD

**Issue by digitaljohn** [webpack/webpack-dev-server#2265]
- Operating System:
- Node Version: v10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.0
- webpack-dev-server Version: 3.8.1
- Browser: Chrome 77.0.3865.90

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

It would be really helpful to launch multiple windows using the `openPage` option rather than only a single one.

E.g.

```js
// webpack.config.js

  devServer: {
    open: true,
    openPage: ["/pageone", "/pagetwo"]
  },
```

### For Features; What is the motivation and/or use-case for the feature?

We are working on an application which in its nature requires multiple web-browser windows to be open.

**Comment by evilebottnawi** [comment]
It is expected and can't be fixed because we don't have api for allowing browser to open page in same tab, also we use `open` library https://github.com/sindresorhus/open, open issue in this repo

**Comment by evilebottnawi** [comment]
What is use case?

**Comment by digitaljohn** [comment]
In my particular case, I am working on a presentation system where there are three browser windows open (one on each of the three monitors connected). The browsers are synchronised using `BroadcastChannel`.

When starting a development session it's a chore to have to manually open three windows and change the urls to include `?window=1` etc.

Example visual below:
![image](https://user-images.githubusercontent.com/1425921/65917127-98553580-e3ce-11e9-8c55-6183e512b0b8.png)

I do believe this may be an edge case and rare but I feel its something I may use over and over while developing multi user games/chat apps etc.

I am willing to perform the leg work and get a PR up and running if you think its a worthy feature.

**Comment by evilebottnawi** [comment]
Yes, PR welcome :+1:

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack/webpack-dev-server/pull/2266
