### ISSUE TITLE
Webpack fails to bundle node_redis

### ISSUE THREAD

**Issue by Dindaleon** [webpack/webpack-dev-server#227]
Whenever I require redis inside a file other than the one where I start the server, I get the following error while webpack is bundling:

    ERROR in ./~/redis/index.js
    Module not found: Error: Cannot resolve module 'net' in     C:\NodeServer\AppInTheWild\node_modules\redis
     @ ./~/redis/index.js 3:10-24

    ERROR in ./~/redis/lib/parser/hiredis.js
    Module not found: Error: Cannot resolve module 'hiredis' in C:\NodeServer\AppInTheWild\node_modules\redis\lib\parser
     @ ./~/redis/lib/parser/hiredis.js 3:14-32

**Comment by nkbt** [comment]
You can't bundle node-only libs (that do not provide browser shims). It is
impossible to run node-redis in the browser.

**Comment by Dindaleon** [comment]
oh! What do you suggest me do then?

**Comment by nkbt** [comment]
You simply cannot use node redis in your frontend build :).

**Comment by Dindaleon** [comment]
Well sorry then, I am still learning. However, I know this is off topic, but I am able to import redis in my server.js file without any problems, but I cannot import it into any other files as it outputs the error I just mentioned.

I have looked on google about this but havent been able to find a tutorial or example that talks about this, that could explain what I am doing wrong and what the correct way is.

The few tutorials and examples I did find, they import redis into any of their files and it just works. That is why I thought it might be webpack causing this issue.

If I install net and hiredis, the errors go away but it outputs a warning that says it could not find the bindings file. I want to avoid having to install these dependencies as I have seen projects not using them while using redis.

**Comment by Dindaleon** [comment]
Well, it seems that we have to specify redis as an external dependency. The following code in webpack's config file seems to have fixed my issue:

     externals: [
       {
         'redis': true        
       }
     ]

Please correct me if I am wrong or if there is a better way.

**Comment by nkbt** [comment]
@Dindaleon using externals is the way to tell webpack not to include those deps into a build. But I still have a question, why you are using node-redis in your frontend code? If you are using it only for your server code, then why do you need webpack build there in the first place? Webpack is not supposed to bundle server-side code (well, it potentially could of course, but why?)

**Comment by shama** [comment]
Some modules on npm cannot run in a web browser and some modules cannot run without a web browser. Generally if a module read/writes to a file system (as databases tend to do) or uses APIs native to OSs (such as `require('net')` or native addons) it will likely not run in a web browser. There is simply no compatible API in the web browser unless the module author has gone out of their way to provide one.

Think of it like asking, "Why can't I play Xbox games on my Nintendo?" Some games are designed to work on both systems, some only Xbox and some only Nintendo.

Same goes for node modules. Some only work with Node.js v0.12, some only io.js, some only on Chrome, some only on Firefox. Some work everywhere. Most of the time you just need to try it and find out.

**Comment by Dindaleon** [comment]
yes, I had no clue. I was still learning about it. Thanks for your help and time.

**Comment by bryanliu-gpsw** [comment]
I have the same issue as i am gettin gthis error:
`Module not found: Error: Cannot resolve module 'hiredis' in /code/node_modules/redis/lib/parsers`
 
For me the weird thing is that I dont get this error on my local machine but when i pushed this to github and ran on CircleCI, then im getting this error.  

I'm pretty sure Redis is only on server side code, so im not sure why webpack is running into this issue. Anyone got solution to this?

**Comment by claudiordgz** [comment]
Hey @bryanliu-gpsw, @Dindaleon. I know it has been a while but have a look here http://jlongster.com/Backend-Apps-with-Webpack--Part-I

I too use Webpack on the backend for several reasons, by using that configuration I was able to get the best of both worlds.

**Comment by richburdon** [comment]
@claudiordgz I've used the following to build node modules with webpack

const nodeExternals = require('webpack-node-externals');

But with this and the articles you mention, I'm also getting this error; but only with redis. Did you specifically get this working?

**Comment by claudiordgz** [comment]
@richburdon I haven't touch this in a while, bear with me, [I did it here](https://github.com/claudiordgz/blog-twitter-integration/blob/master/webpack.config.js). I remember we had to do a map of the dependencies manually and pass them to the webpack config. Maybe it stopped working? I'll check it out tomorrow morning.

**Comment by richburdon** [comment]
@shama sorry to revive an old thread, but why not use webpack to bundle/compress server side code (e.g., to build Docker containers). Are there better tools for that or do you not see the need.

E.g., I have a monorepo with a dozen sub modules linked via lerna. It's a PITA to bundle all of these and export lerna into my Docker build. It's really handle to bundle my server code into a single JS. And for the most part I can do this, but redis (hiredis.js) is the only module (out of 1000s) that gives the error above.

**Comment by josecolella** [comment]
Is it possible to use webpack with node_redis? I am also interested in bundling server-side code with webpack and I'm using node_redis
