### ISSUE TITLE
Self-signed SSL certs not valid on MacOS 10.15 (Catalina)

### ISSUE THREAD

**Issue by tarrall** [webpack/webpack-dev-server#2273]
(PR inbound)

- Operating System:  MacOS 10.15
- Node Version: 12.9.0
- NPM Version: 6.10.3
- webpack Version: 4.39.3
- webpack-dev-server Version: 3.8.2
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

(Usual webpack setup; no specific code needed to repro)

### Expected Behavior
Autogenerated SSL certificate should be accepted by common browsers.

### Actual Behavior
As of MacOS 10.15, the SSL certificate validation logic is more strict and requires some additional certificate extensions.  Ref: https://support.apple.com/en-us/HT210176

### For Bugs; How can we reproduce the behavior?
Start up webpack-dev-server with SSL enabled on a MacOS 10.15 system; attempt to hit the server in Chrome (probably Safari as well).

**Comment by stefanovualto** [comment]
@evilebottnawi , I am still having a `NET::ERR_CERT_INVALID` with version `3.8.2` which should  includes #2274

**Comment by evilebottnawi** [comment]
Release will be today

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack/webpack-dev-server/pull/2274

**Comment by evilebottnawi** [comment]
Release https://github.com/webpack/webpack-dev-server/releases/tag/v3.9.0
