### ISSUE TITLE
Opens port on IPv4 that's also used by a process on IPv6 causing mixed results

### ISSUE THREAD

**Issue by ominestre** [webpack/webpack-dev-server#2277]
- Operating System: macOS Mojave version 10.14.3
- Node Version: 10.12.0
- NPM Version: 6.4.1
- webpack Version: ^4.41.1
- webpack-dev-server Version: ^3.8.2
- Browser: Firefox 67.0.4

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

[GitHub Demo with documentation on the issue](https://github.com/ominestre/DEMO-webpack-port-issue)

### Expected Behavior

When Dev Server is configured to use a port that is already in use, either IPv4 or IPv6, it should bubble up the Address In Use error, or at least a warning of the discrepancy.

### Actual Behavior

When another process opens a server on [::!]:9876 for IPv6, and Dev Server is configured to also use port 9876, the browser opened by the `--open` flag will go to `localhost:9876` which defaults to the IPv6 address.

### For Bugs; How can we reproduce the behavior?

I provided a [bare bones demo repository](https://github.com/ominestre/DEMO-webpack-port-issue) with documentation on how to run it. If you would like to do this on your own bind a http server to a port using only IPv6, then configure Webpack Dev Server to use that same port and fire it up.

We ran into this because I configured Webpack Dev Server to run on port 9000 and there was a VS Code plugin some of my team had that hosted some Swagger-UI server on port 9000 as well but only IPv6.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Fixed in v4
