### ISSUE TITLE
Bundle errors freeze and lock up Chrome

### ISSUE THREAD

**Issue by Boycce** [webpack/webpack-dev-server#2286]
- Operating System: Ubuntu 18.04.1 LTS
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.40.2
- webpack-dev-server Version: 3.8.1
- Browser: Chrome Version 77.0.3865.75

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/Boycce/webpack-dev-server-chrome-issue

### Expected Behavior

Chrome should continue to run smoothly.

### Actual Behavior

When saving `index.js` with an error, Chrome locks / freezes for 5-10 seconds where you are unable to refresh or close the tab. The lock duration increases with the bundle size, and only happens when Chrome DevTools is open, the project is linked to a DevTools Workspace, and `devServer.writeToDisk` is enabled.

### For Bugs; How can we reproduce the behavior?

1. add the project folder as a chrome workspace
2. `npm install`
3. `npm run dev`
4. open http://localhost:8080 and DevTools
5. re-run `npm run dev`

**Comment by evilebottnawi** [comment]
Can't reproduce, maybe problem with chrome, we do not use anything special

**Comment by evilebottnawi** [comment]
Reproduce, investigate

**Comment by evilebottnawi** [comment]
Yes, bug in chrome https://stackoverflow.com/questions/36411530/big-source-minified-files-make-chrome-developer-tools-freeze/36411531
 
Please report this problem to google chrome bug tracker, we can't fix problem on our side, sorry

**Comment by Boycce** [comment]
Hello @evilebottnawi, sometimes you need to rerun ‘npm run dev’ a few times for the block to occur. It’s really a difficult issue to reproduce but hinders development greatly.

This issue also seems different to the issue you referenced and others I have a seen that are similar. If you see the CPU usage within chrome you will notice it is very high, as if the wepack-dev-server browser refresh is caught in a loop or something.

Can you please share your environment which you used to test this with.
