### ISSUE TITLE
dev server generates different digests than webpack:compile

### ISSUE THREAD

**Issue by Jonnymcc** [webpack/webpack-dev-server#2287]
- Operating System: 4.9.184-linuxkit
- Node Version: v10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.38.0
- webpack-dev-server Version: 3.8.0
- Browser: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

No specific code to reference.

I noticed this hash is printed when the webpack-dev-server starts. When I run `bundle exec rake assets:precompile` `webpacker:compile` also prints this line, but the hash is different. Why? And where does this hash come from? I searched for it in both https://github.com/webpack/webpack-dev-server and https://github.com/rails/webpacker and could not find it.

```
19:30:45 webpack_dev_server.1 | ℹ ｢wdm｣: Hash: ec813212c73ed1f1f6bb
19:30:45 webpack_dev_server.1 | Version: webpack 4.38.0
```

### Expected Behavior
When webpack-dev-server runs it creates a public/assets/packs/manifest.json that has different digests for assets than those created using `bundle exec rake assets:precompile`.

### Actual Behavior
The output of webpack-dev-server should be consistent with `bundle exec rake assets:precompile`.

**Comment by evilebottnawi** [comment]
Because you change files so compilation hash is changed too. Also please full **all** questions in issue template in future.
