### ISSUE TITLE
devServer.https options - include passphrase for local cert key

### ISSUE THREAD

**Issue by carlgunderson** [webpack/webpack-dev-server#2293]
- Operating System: MacOS
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: 3.3.9
- webpack-dev-server Version: 3.9.0
- Browser: N/A

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

Per the documentation on HTTPS settings:
https://webpack.js.org/configuration/dev-server/#devserverhttps

Is there a way to specify that a passphrase is required for the `.key` file? If not, are you aware of any possible workarounds that I could look into that would circumvent the webpack config?

My other question would be is this possible via `webpack-cli`? It seems like the options are the same between `webpack-dev-server` and `webpack-cli`, but not sure if more actions could be possible via `webpack-cli`.

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter for questions. 

We use https://github.com/jfromaniello/selfsigned package for generation certificates. Here issue https://github.com/jfromaniello/selfsigned/issues/23. No workarounds, you can send a PR to the original repo and we update the package after merge.
