### ISSUE TITLE
How to listen static folder to refresh the page

### ISSUE THREAD

**Issue by pangjunpeng** [webpack/webpack-dev-server#2294]
- Operating System: Max OS 10.14.6
- Node Version: v10.16.3
- NPM Version: 6.11.3
- webpack Version: v3.6.0
- webpack-dev-server Version: v2.9.1
- Browser: Chrome 77

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

this is folder tree
```
├─ build
    ├─ webpack.dev.config.js
├─ static
    ├─ some.css
```

I try to set `contentBase: '/static'` and `watchContentBase: true`, but no effect
```js
// webpack.dev.config.js
devServer: {
    hot: true,
    contentBase: path.resolve(__dirname, '../static'),
    watchContentBase: true
    // ...
}
```

### Expected Behavior
I expect to that when `static` changed,   the page in chrome will be refreshed

### Actual Behavior
No Response

头大, thanks

**Comment by evilebottnawi** [comment]
Something wrong in your configuration, please provide minimum reproducible test repo

**Comment by pangjunpeng** [comment]
thx，I've found a solution :)
Sorry for troubling you
