### ISSUE TITLE
Webpack Dev Server does not work on Port 8080

### ISSUE THREAD

**Issue by arnavb** [webpack/webpack-dev-server#2295]
- Operating System: Mac OSX Catalina 10.15
- Node Version: 12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: `Google Chrome | 77.0.3865.120 (Official Build) (64-bit)`

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

For reference, here is the repository with [a minimal example](https://github.com/arnavb/wds-issue).

I've been learning how to use webpack dev server, and I'm getting a weird issue where the server is unable to be opened on port 8080. All other ports seem to work (at least the ones I've tested), but 8080 doesn't. Here is my `webpack.config.js`:

```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  devServer: {
      contentBase: './dist',
      port: 8080
  },
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
};
```

My folder structure consists of:
- A `dist` folder, with a simple `index.html` referencing `main.js`.
- A `src` folder, with a `index.js` containing a single `console.log` statement.

I run webpack dev server using `webpack-dev-server --open` (through `npm start` in the repository).'

### Expected Behavior

The server should open the webpage in my browser, and I should see the `console.log` statement in the browser console.

### Actual Behavior

I see this:

![image](https://user-images.githubusercontent.com/30810402/67431118-a05d5b00-f5b1-11e9-9cff-36cf077219dd.png)

In the repository, when I change the port to another value (like 3000), everything works as expected.

### Trying to solve the problem

In an attempt to determine what was going on, I used the command `lsof -i :PORT` (where `PORT` is the respective port I'm using). Here are some outputs from the command:

##### Before starting the dev server:

No output

##### After starting the dev server:

```
COMMAND   PID          USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
node    63303 arnavborborah   28u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:http-alt (LISTEN)
```

##### Before starting the dev server:

No output

##### After starting the dev server:

```
COMMAND     PID          USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
Google    24654 arnavborborah   52u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:59090->localhost:hbci (ESTABLISHED)
Google    24654 arnavborborah   59u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:59091->localhost:hbci (ESTABLISHED)
Google    24654 arnavborborah   62u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:59093->localhost:hbci (ESTABLISHED)
node      63334 arnavborborah   28u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:hbci (LISTEN)
node      63334 arnavborborah   33u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:hbci->localhost:59090 (ESTABLISHED)
node      63334 arnavborborah   35u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:hbci->localhost:59091 (ESTABLISHED)
node      63334 arnavborborah  227u  IPv4 XXXXXXXXXXXXXXXXX      0t0  TCP localhost:hbci->localhost:59093 (ESTABLISHED)
```

Noticeably, when `lsof`'d port 8080, there is only one line of output, whereas for 3000, there are many more. This tells me webpack-dev-server isn't properly setting up port 8080, perhaps?

Just to make sure this is webpack specific, I ran a node.js file with the following contents:

```js
var http = require('http');

http.createServer(function (req, res) {
  res.write('Hello World!');
  res.end();
}).listen(8080);
```

With this code, however, I see the expected `Hello World!` on `http://localhost:8080`.

**Comment by evilebottnawi** [comment]
Looks like problem with firewall/ports/network, can't reproduce (try to other computer), try to disable antivirus/firewall/reconfigure network/etc, feel free to feedback

**Comment by arnavb** [comment]
@evilebottnawi I've tried disabling the firewall and adding Chrome to the list of applications allowed to accept incoming connections, nothing works there. Next, I tried running an HTTP server on port 8080 created from `npm i -g http-server && http-server`, which works well.

I just don't understand, I can create an HTTP server on 8080 for everything _but_ webpack dev server.

**Comment by evilebottnawi** [comment]
@arnavb I don't know what is wrong with your environment, try to use other compute or you can use docker for testing, all work fine

**Comment by d3chapma** [comment]
@arnavb Any chance you figured this out. I just started experiencing the same thing today. Everything was working fine, then all of a sudden I cannot access anything webpack-dev-server was serving via port 8080. If I switch to another port it works fine and if I `lsof -i :8080` I have one result if webpack-dev-server is running, otherwise nothing.

Really confused about this, especially because it started happening in the middle of my work today.

**Comment by arnavb** [comment]
@d3chapma Nope! I still have this issue today. There is nothing running on 8080 except webpack-dev-server (based on terminal output). I've just learned to live with it :)

**Comment by d3chapma** [comment]
@arnavb In case it helps I found out that my issue was that I had "Content & Privacy Restrictions" turned on in the "Screen Time" mac app. That was using port 8080, but for some reason wasn't showing up in a `lsof -i :8080`.

![image](https://user-images.githubusercontent.com/286092/99977841-2b8bc000-2d73-11eb-8f7c-ac20db85a21b.png)

Turning it off fixed the issue for me.
