### ISSUE TITLE
[Q] How you detect fake changes? e.g hitting ctrl+s without actual change.

### ISSUE THREAD

**Issue by dehghani-mehdi** [webpack/webpack-dev-server#2301]
Hi,

I apologies for breaking repo's issue report rules.

I'm wondering how webpack detect actual file changes. I mean if I hit `ctrl+s` without actual change to the file, webpack send signal to the browser, but not reload signal. how do you do that? I could not find any clue on this. would you please explain or show me the right place to see the related code.

__Update__: this is not an issue, I just want to know how you implemented this, I don't want to disable or change this behavior.

Thank you.

**Comment by derekdon** [comment]
It's likely the watcher is watching an ide directory too, which changes on hitting ctrl + s. For example, Intellij IDEA / WebStorm, will write to a .idea directory on the project root every time, so you might want to exclude it.

`
watchOptions: {
    aggregateTimeout: 1000,
    ignored: [
        /\.idea/,
`

**Comment by evilebottnawi** [comment]
https://github.com/paulmillr/chokidar watch for filesystem event and send a signal to browser using websocket, better use stackoverflow for this questions, there are a lot of smart development who can explain every line of code and why it is needed
