### ISSUE TITLE
transportMode: 'ws' interferes with proxy { ws: true }

### ISSUE THREAD

**Issue by joonas-lahtinen** [webpack/webpack-dev-server#2310]
- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version: any
- webpack-dev-server Version: any
- Browser: any

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
...
devServer: {
  transportMode: 'ws',
  proxy: {
    '/api': {
      target: 'http://localhost:8888',
      ws: true,
    },
  },
},
...
```

### Expected Behavior

Proxying Websockets works similar to `transportMode: 'sockjs'`

### Actual Behavior

Websocket connections get closed with `400 Bad Request` error.

### For Bugs; How can we reproduce the behavior?

Simultaneously enable `transportMode: 'ws'` and `proxy: { ws: true }`

**Comment by hiroppy** [comment]
fixed by #2311, thank!
