### ISSUE TITLE
WebpackDevServer will add 'webpack-dev-server/client' by default

### ISSUE THREAD

**Issue by githoniel** [webpack/webpack-dev-server#2315]
- Operating System: Win10
- Node Version: 12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.35.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome

- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
default webpack config
```

```js
   const devClients = [
      // dev server client
      require.resolve('webpack-dev-server/client') + sockjsUrl,
      // hmr client
      require.resolve(projectDevServerOptions.hotOnly
        ? 'webpack/hot/only-dev-server'
        : 'webpack/hot/dev-server')
      ]
    // inject dev/hot client
    addDevClientToEntry(webpackConfig, devClients)

    const compiler = webpack(webpackConfig)
    const server = new WebpackDevServer(compiler)
```

### Expected Behavior

WebpackDevServer do not add entry by default

### Actual Behavior

WebpackDevServer will add entry by default

after debug, if found `options.inline === false` will disable addEntries.

**Comment by evilebottnawi** [comment]
Because without client hot will not be work, do not use `inline` it is deprecated and will be removed in next release
