### ISSUE TITLE
config.open doesn't work

### ISSUE THREAD

**Issue by yf287** [webpack/webpack-dev-server#2321]
- Operating System: mac osx
- Node Version:8.12.0
- NPM Version: 6.9.0
- webpack Version: 3.7.0
- webpack-dev-server Version: 2.9.1
- Browser: chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
devServer: {
    open: false
}
```js
// additional code, remove if not needed.
```
reproducible repo:

I m using bisheng@0.28.0(https://github.com/benjycui/bisheng) which is dependeced on webpack-dev-server@2.9.1,
I ve configed devServer param for bisheng, and console.log the result in the npm when I start the server,but config.open doesn't work

### Expected Behavior
when server start, it wont open the browser and a new page
### Actual Behavior
it opens the browser and a new page
### For Bugs; How can we reproduce the behavior?
normal config，with config.open = false
### For Features; What is the motivation and/or use-case for the feature?
going to run a devServer on testing env, but our servers dont allow us to open the browser

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by yf287** [comment]
> Please create reproducible test repo

update my question just now, is it available for you? Need I show the log?

**Comment by evilebottnawi** [comment]
Yes, open was broken in `2` version, we can't solve this because 2 branch is deprecated and do not supported, please update `webpack-dev-server` to `3` version

**Comment by yf287** [comment]
> Yes, open was broken in `2` version, we can't solve this because 2 branch is deprecated and not supported, please update `webpack-dev-server` to `3` version

thanks a lot
