### ISSUE TITLE
Module not found error after upgrading from Webpack 3.x to 4.x

### ISSUE THREAD

**Issue by tomraut** [webpack/webpack-dev-server#2322]
- Operating System: OS X
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
'use strict';

var webpack = require('webpack');
var path = require('path');


module.exports = {
    output: {
        publicPath: '/dist-dev/',
        path: path.resolve(__dirname),
        filename: '[name].bundle.js'
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
    ],
    module: {
      rules: [
        {
          test: /\.(svg|png|gif|jpg)$/,
          use: ['url-loader?limit=10000']
        },
        {
          test: /\.(otf|ttf|eot|woff(2)?)(\?[a-z0-9]+)?$/,
          use: ['file-loader']
        },
        {
          test: /\.json$/,
          use: ['json-loader']
        },
        {
          // http://survivejs.com/webpack/advanced-techniques/configuring-react/
          // TODO use react-lite for smaller filesize?
          test: /\.(js|jsx)$/,
          include: /app/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                cacheDirectory: '/tmp'
              }
            }
          ]
        }
      ]
    },
    resolve: {
        modules: [
          __dirname,
          'node_modules'
        ],
        extensions: ['.js', '.json', '.jsx', '.scss', '.css']
    },
    resolveLoader: {
        modules: [
          path.join(__dirname, 'node_modules'),
          __dirname,
          path.resolve('node_modules')
        ]
    }

};
```

```js
// dev-entry.js
'use strict';
//exposes global player app during dev
require("expose-loader?player!app/init");

//enables hot loading of styles during dev
require("./app/styles/main");
```

```js
// gulp task
gulp.task('webpack:dev-server', gulp.series('version', function(done) {
  try {
    var config = Object.create(webpackConfig),
      port = devConfig.devServerPort || 8080
    config.devtool = 'source-map'
    config.resolve.alias = devConfig.aliases || {}
    config.module.rules.push(
      {
        test: /\.scss$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: function () {
                return [ autoprefixer() ]
              }
            }
          },
          'sass-loader?' + getIncludePaths()]
      }
    )
    config.entry = polyfillEntries.concat(['./dev-entry.js', 'webpack-dev-server/client?http://localhost:' + port, 'webpack/hot/dev-server'])

    config.plugins = config.plugins.concat(
      new webpack.LoaderOptionsPlugin({
        context: config.context,  // config is your webpack config object
        output: config.output,
        debug: true
      }),
      new webpack.DefinePlugin({
        __DEV__: true,
        __VERSION__: version,
        __GIT_INFO__: JSON.stringify(getGitInfo()),
        __DASHJS_VERSION__: JSON.stringify(dashJsVersion)
      })
    )

    new WebpackDevServer(webpack(config), {
      hot: true,
      publicPath: config.output.publicPath,
      disableHostCheck: true,
      stats: {
        colors: true
      },
      proxy: proxies
    }).listen(port, '0.0.0.0', function(err) {

      if(err) {
        throw new gutil.PluginError('webpack-dev-server', err)
      }
      gutil.log('[webpack-dev-server]', 'http://0.0.0.0:' + port + '/webpack-dev-server/index.html')
    })
  } catch(e) {
    console.error(e)
    e.message && console.error(e.message)
  }
  done()
}))
```

### Expected Behavior
Server should start without issues.

### Actual Behavior
It says "failed to compile" and prints out following errors:

ERROR in ./dev-entry.js
Module not found: Error: Can't resolve './app/styles/main' in '/work/player'
 @ ./dev-entry.js 7:0-28
 @ multi whatwg-fetch ./dev-entry.js webpack-dev-server/client?http://localhost:9001 webpack/hot/dev-server

ERROR in ./dev-entry.js
Module not found: Error: Can't resolve 'app/init' in '/work/player'
 @ ./dev-entry.js 3:0-50
 @ multi whatwg-fetch ./dev-entry.js webpack-dev-server/client?http://localhost:9001 webpack/hot/dev-server
ℹ ｢wdm｣: Failed to compile.

### For Bugs; How can we reproduce the behavior?
This happens only with Webpack 4.x versions. I've been using previously Webpack 3.11.0 and same configuration worked without any issues.

**Comment by evilebottnawi** [comment]
Sorry issue not related to webpack-dev-server, problems with configuration, some improvement:
- You don't need `webpack.HotModuleReplacementPlugin`
- You don't need 'webpack-dev-server/client?http://localhost:' + port, 'webpack/hot/dev-server'
- You don't need webpack.LoaderOptionsPlugin

I can't help without reproducible test repo, error means you don't have `./dev-entry.js` file

**Comment by tomraut** [comment]
@evilebottnawi I've removed things you mentioned but it still gives me same error. Regarding your last comment, I have to disagree with you. I do have `./dev-entry.js` in place, error even points to some lines of that file:

ERROR in ./dev-entry.js
Module not found: Error: Can't resolve './app/styles/main' in '/app/player'
 @ ./dev-entry.js 7:0-28

Any idea what's in my configuration is causing this?

**Comment by evilebottnawi** [comment]
What is `/app/styles/main`? JS or CSS or TS?

**Comment by evilebottnawi** [comment]
If you create reproducible test repo i will help you very fast

**Comment by tomraut** [comment]
> What is `./app/styles/main`? JS or CSS or TS?

It is a `.scss` file.

**Comment by evilebottnawi** [comment]
Sorry can't help without reproducible test repo, problem in configuration, you can try to remove `resolve` option

**Comment by tomraut** [comment]
> Sorry can't help without reproducible test repo, problem in configuration, you can try to remove `resolve` option

That didn't help either. Actually it doesn't even use config from webpack.config.js file because when I'm logging what kind of config is actually used at this stage:

```
console.log(config)
    new WebpackDevServer(webpack(config), {
      hot: true,
      publicPath: config.output.publicPath,
      disableHostCheck: true,
      stats: {
        colors: true
      },
      proxy: proxies
    }).listen(port, '0.0.0.0', function(err) {

      if(err) {
        throw new gutil.PluginError('webpack-dev-server', err)
      }
      gutil.log('[webpack-dev-server]', 'http://0.0.0.0:' + port + '/webpack-dev-server/index.html')
    })
  } catch(e) {
    console.error(e)
    e.message && console.error(e.message)
  }
```
..I'm getting only this:
```
{ devtool: 'source-map',
  entry: [ 'whatwg-fetch', './dev-entry.js' ],
  plugins: [ DefinePlugin { definitions: [Object] } ] }
```

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, without source code i can't help

**Comment by tomraut** [comment]
I got bit further now and I'm getting new errors now:
```
ERROR in ./app/appModules/error-ui.js
Module not found: Error: Can't resolve '../components/ErrorUI' in '/work/app/appModules'
 @ ./app/appModules/error-ui.js 13:12-44
 @ ./app/modules.js
 @ ./app/init.js
 @ ./node_modules/expose-loader?player!./app/init.js-exposed
 @ ./dev-entry.js
 @ multi whatwg-fetch ./dev-entry.js

ERROR in ./app/styles/main.scss 5:0
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| 
> @import "variables";
| @import "mixins";
| 
 @ ./dev-entry.js 7:0-33
 @ multi whatwg-fetch ./dev-entry.js
```

First error must be somehow related to path configuration but I'm not sure what might've been changed in Webpack 4.x vs 3.x regarding this?

Second error relates to loaders. Apparently Webpack 4.x doesn't understand SCSS syntax anymore.

Unfortunately I cannot create reproducable repo as my project contains some references to private repos.

**Comment by evilebottnawi** [comment]
@tomraut remove private code, and create simple example with configuration(s) and couple lines of code, all errors related to configuration, not webpack-dev-server, I would recommend using stackoverflow or gutter for that, sorry without reproducible test repo issue will be closed, i can't help without examples/code

**Comment by endiliey** [comment]
Creating a minimal repro removes most extraneous moving pieces, improving the signal to noise ratio, enabling the real problem to be seen. I think this issue should be closed 😉

**Comment by tomraut** [comment]
@evilebottnawi I've got light test repo ready now, can you please check what might be wrong with my configs: https://github.com/tomraut/webpacktest

**Comment by tomraut** [comment]
I've ended up creating new one: https://github.com/webpack/webpack-dev-server/issues/2339
