### ISSUE TITLE
History-api-fallback not work when path is special case

### ISSUE THREAD

**Issue by hackwaly** [webpack/webpack-dev-server#2343]
- Operating System: macOS 10.14.6 (18G1012)
- Node Version: v10.16.2
- NPM Version: 6.13.2
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: Chrome 79.0.3945.79

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```sh
webpack-dev-server --history-api-fallback
```

```text/plain
 ℹ ｢wds｣: Project is running at http://localhost:8080/
 ℹ ｢wds｣: webpack output is served from /
 ℹ ｢wds｣: Content not from webpack is served from /path/to/my/project
 ℹ ｢wds｣: 404s will fallback to /index.html
```

### Expected Behavior

Url http://localhost:8080/http://www.example.com fallback to /index.html

### Actual Behavior

```
Cannot GET /http://www.example.com
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please full issue template
