### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by rajasekhar2** [webpack/webpack-dev-server#2348]
- Operating System: windows 10
- Node Version:1.19.1
- NPM Version:
- webpack Version: 4.29.6
- webpack-dev-server Version:3.1.14
- Browser: chrome

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code
<--- Last few GCs --->
 
[17208:0000020B4EB70F20]  1184996 ms: Scavenge 3365.3 (4162.0) -> 3364.3 (4162.5) MB, 10.8 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
[17208:0000020B4EB70F20]  1185019 ms: Scavenge 3366.8 (4163.0) -> 3366.0 (4163.5) MB, 10.5 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
[17208:0000020B4EB70F20]  1185036 ms: Scavenge 3367.7 (4163.5) -> 3366.9 (4164.0) MB, 9.7 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
 
 
<--- JS stacktrace --->
 
==== JS stack trace =========================================
 
    0: ExitFrame [pc: 0000016F06950481]
Security context: 0x023dcff9d9d1 <JSObject>
    1: set [0000023DCFF90E29](this=0x022843ae3df1 <Map map = 000000A62F483EC1>,0x00fc22082d79 <DependenciesBlock map = 000001714723CBD1>,4096)
    2: processDependenciesBlocksForChunkGroups [000003C1DC7AD841] [D:\TCS\Projects\AzureCXP\Git\AzureCXP-Eng-UX\src\node_modules\webpack\lib\Compilation.js:~1514] [pc=0000016F07884402](this=0x024f2d6ba8f9 <Tapable m...
 
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 00007FF7B12BD7AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
2: 00007FF7B126B736 uv_loop_fork+86646
3: 00007FF7B126C1FD uv_loop_fork+89405
4: 00007FF7B169454E v8::internal::FatalProcessOutOfMemory+798
5: 00007FF7B1694487 v8::internal::FatalProcessOutOfMemory+599
6: 00007FF7B1747F64 v8::internal::Heap::RootIsImmortalImmovable+14068
7: 00007FF7B173DD72 v8::internal::Heap::CollectGarbage+7234
8: 00007FF7B173C588 v8::internal::Heap::CollectGarbage+1112
9: 00007FF7B1745EB7 v8::internal::Heap::RootIsImmortalImmovable+5703
10: 00007FF7B1745F36 v8::internal::Heap::RootIsImmortalImmovable+5830
11: 00007FF7B187DC6D v8::internal::Factory::AllocateRawArray+61
12: 00007FF7B187E602 v8::internal::Factory::NewFixedArrayWithFiller+66
13: 00007FF7B18C52DE v8::internal::wasm::AsmType::Void+86510
14: 00007FF7B18C599D v8::internal::wasm::AsmType::Void+88237
15: 00007FF7B194F6B4 v8::internal::StoreBuffer::StoreBufferOverflow+123924
16: 0000016F06950481
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```js
// webpack.config.js
```
{
  "name": "cxp-web-service",
  "version": "1.0.0",
  "description": "Azure CXP Engineerings Web Platform Service",
  "license": "UNLICENSED",
  "main": "index.js",
  "scripts": {
    "auth": "yarn global add vsts-npm-auth --registry https://msazure.pkgs.visualstudio.com/_packaging/AzureCXP/npm/registry --always-auth false && vsts-npm-auth -config .npmrc",
    "start": "concurrently --names \"FrontEnd,MockServer\" \"yarn run start:frontendmock\" \"yarn run backend\"",
    "integration": "yarn run start:frontend",
    "backend": "yarn ts-node-dev -P .\\Tools\\ExpressServer\\tsconfig.json .\\Tools\\ExpressServer\\ConfigureExpressServer.ts",
    "start:frontendmock": "node --max-old-space-size=4096 tools/Server.js auth mock",
    "start:frontend": "node --max-old-space-size=4096 tools/Server.js auth",
    "start:dev": "node tools/ExpressServer/.out/StartDevServer.js",
    "start:old": "node --max-old-space-size=4096 tools/Server.js auth",
    "unauthStart": "node --max-old-space-size=4096 tools/Server.js unauth",
    "prebuild": "node tools/BuildClean.js",
    "build": "yarn run build:release",
    "postbuild": "node tools/ProdServer.js",
    "build:release": "node --max-old-space-size=4096 tools/Build.js auth",
    "prebuildazurepulse": "yarn run prebuild azurepulse",
    "buildazurepulse": "yarn run build:release azurepulse",
    "prebuildkb": "yarn run prebuild azurekb",
    "buildkb": "yarn run build:release azurekb",
    "prebuildceres": "yarn run prebuild ceres",
    "buildceres": "yarn run build:release ceres",
    "prebuildoslo": "yarn run prebuild health",
    "buildoslo": "yarn run build:release health",
    "prebuildauris": "yarn run prebuild feedback",
    "buildauris": "yarn run build:release feedback",
    "prebuildace": "yarn run prebuild ace",
    "buildace": "yarn run build:release ace",
    "prebuildadmin": "yarn run prebuild admin",
    "buildadmin": "yarn run build:release admin",
    "prebuildhipri": "yarn run prebuild hipri",
    "buildhipri": "yarn run build:release hipri",
    "prebuildcore": "yarn run prebuild coreapp",
    "buildcore": "yarn run build:release coreapp",
    "prebuildcorti": "yarn run prebuild corti",
    "buildcorti": "yarn run build:release corti",
    "prebuildUnauth": "yarn run prebuild externalfeedback",
    "buildUnauth": "node --max-old-space-size=4096 tools/Build.js unauth",
    "prebuildAmp": "yarn run prebuild addnomination",
    "buildAmp": "yarn run build:release addnomination",
    "prebuildnomportal": "yarn run prebuild nominationportal",
    "buildnomportal": "yarn run build:release nominationportal",
    "tslint-check": "tslint-config-prettier-check ./tslint.json",
    "build:expressserver": "tsc -p Tools/ExpressServer/",
    "build:frontendfortest": "node --max-old-space-size=4096 tools/BuildTest.js auth mock",
    "build:testall": "concurrently \"yarn build:expressserver\" \"yarn build:frontendfortest\"",
    "cypress:runtestserver": "concurrently --names \"FrontEnd,MockServer\" \"node tools/StartFrontEndBuild.js ../../testOut\" \"yarn run backend\"",
    "cypress:test": "yarn run cypress open",
    "cypress:build": "yarn run cypress run --spec 'cypress/integration/Mocked/**/*' --browser chrome",
    "cypress:frontendcli": "concurrently --kill-others --success \"first\" \"wait-on http-get://localhost:15063 && yarn cypress:build\" \"yarn cypress:runtestserver\""
  },
  "author": "Microsoft",
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^4.0.3",
    "@microsoft/sp-office-ui-fabric-core": "^1.8.0",
    "@types/applicationinsights-js": "^1.0.9",
    "@types/chart.js": "^2.7.37",
    "@types/classnames": "2.2.7",
    "@types/cors": "^2.8.4",
    "@types/express": "^4.16.1",
    "@types/file-saver": "^2.0.0",
    "@types/jquery": "^3.3.11",
    "@types/lodash": "^4.14.116",
    "@types/moment-timezone": "^0.5.9",
    "@types/pluralize": "^0.0.29",
    "@types/prop-types": "^15.5.6",
    "@types/query-string": "^6.3.0",
    "@types/react": "^16.8.4",
    "@types/react-adal": "^0.4.1",
    "@types/react-big-calendar": "^0.20.19",
    "@types/react-bootstrap": "^0.32.14",
    "@types/react-dom": "^16.0.8",
    "@types/react-infinite-scroller": "^1.2.1",
    "@types/react-redux": "^7.1.2",
    "@types/react-router-dom": "^4.3.1",
    "@types/react-scroll": "^1.5.4",
    "@types/react-select": "^2.0.15",
    "@types/react-simple-maps": "^0.12.2",
    "@types/react-table": "^6.8.0",
    "@types/redux-form": "^8.1.0",
    "@types/redux-immutable-state-invariant": "^2.0.4",
    "@types/sanitize-html": "1.18.3",
    "@types/spdy": "^3.4.4",
    "@types/toastr": "^2.1.35",
    "@types/webpack-dev-server": "^3.1.1",
    "cache-loader": "^4.0.0",
    "chalk": "^2.4.2",
    "cheerio": "^1.0.0-rc.2",
    "colors": "^1.3.3",
    "concurrently": "^4.1.0",
    "copy-webpack-plugin": "^5.0.3",
    "cors": "^2.8.5",
    "css-loader": "^2.1.1",
    "express": "^4.16.3",
    "file-loader": "^3.0.1",
    "fork-ts-checker-webpack-plugin": "^1.0.0",
    "happypack": "^5.0.0",
    "html-webpack-plugin": "^4.0.0-beta.5",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "npm": "^6.4.1",
    "npm-run-all": "^4.1.3",
    "open": "^6.1.0",
    "optimize-css-assets-webpack-plugin": "^5.0.1",
    "prettier": "1.16.4",
    "react-hot-loader": "^4.3.11",
    "resolve-url-loader": "^3.0.1",
    "rimraf": "^2.6.3",
    "sass-loader": "^7.1.0",
    "source-map-loader": "^0.2.4",
    "style-loader": "^0.23.1",
    "thread-loader": "^2.1.2",
    "ts-loader": "^5.2.1",
    "ts-node-dev": "^1.0.0-pre.40",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.17.0",
    "tslint-loader": "^3.6.0",
    "tslint-microsoft-contrib": "^6.1.0",
    "tslint-react-hooks": "^2.1.0",
    "typescript": "^3.3.4",
    "wait-on": "^3.3.0",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.3.0",
    "webpack-dev-middleware": "^3.4.0",
    "webpack-dev-server": "^3.1.14",
    "webpack-hot-middleware": "^2.24.2",
    "webpack-merge": "^4.1.4"
  },
  "dependencies": {
    "@azure/storage-blob": "^10.3.0",
    "@msfast/lpc-bootstrapper": "^20190621.7.0",
    "applicationinsights-js": "^1.0.20",
    "axios": "^0.18.0",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.8.0",
    "chartjs-plugin-annotation": "^0.5.7",
    "classnames": "2.2.6",
    "cypress": "^3.4.1",
    "es6-promise": "^4.2.5",
    "file-saver": "^2.0.1",
    "font-awesome": "^4.7.0",
    "guid-typescript": "^1.0.7",
    "jquery": "^3.3.1",
    "js-sha256": "^0.9.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.16",
    **"msal": "^1.1.3",**
    "office-ui-fabric-core": "^9.6.1",
    "office-ui-fabric-react": "^6.157.3",
    "pluralize": "^7.0.0",
    "popper.js": "^1.14.4",
    "query-string": "^6.5.0",
    "react": "^16.8.4",
    "react-adal": "^0.4.17",
    "react-big-calendar": "^0.21.0",
    "react-bootstrap": "^1.0.0-beta.5",
    "react-chartjs-2": "^2.7.4",
    "react-dom": "^16.5.2",
    "react-infinite-scroller": "^1.2.4",
    "react-localization": "^1.0.15",
    "react-moment": "^0.8.4",
    "react-redux": "^7.1.0",
    "react-responsive-carousel": "^3.1.49",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scroll": "^1.7.11",
    "react-select": "^2.4.2",
    "react-simple-maps": "^0.12.1",
    "react-table": "^6.8.6",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-form": "^8.1.0",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "roosterjs-react": "^0.0.68",
    "roosterjs-react-ribbon": "^0.0.68",
    "sanitize-html": "^1.20.1",
    "status": "^0.0.13",
    "toastr": "^2.1.4",
    "world-atlas": "^1.1.4"
  }
}

```js
// additional code, remove if not needed.
```

### For Bugs; How can we reproduce the behavior?
Once I include some library this issue is surfacing

**Comment by rishabh3112** [comment]
@rajasekhar2 send up a minimum reproducible repository so that we can dig up the issue.

**Comment by rajasekhar2** [comment]
I cannot provide a minimum repository as this occurs on inclusion of large number of modules and large no of files in repo. When I increase the space to 10240 build goes fine i.e. node --max-old-space-size=10240 tools/Server.js auth . This seems to be the worst part of it, I have only 8GB RAM and how 10GB is fixing this ? Looks like somewhere its bluffing itself.

**Comment by evilebottnawi** [comment]
Something wrong in your deps (looks you use wasm somewhere), we don't use wasm on our side, so we can't help you here, also without reproducible test repo impossible detect what is problem

**Comment by rajasekhar2** [comment]
Interesting!!!!
What do you mean by wasm? where we are using it. So closing this issue is the only solution you have?

**Comment by victorykong** [comment]
> 我无法提供最小存储库，因为在 repo 中包含大量模块和大量文件时会发生这种情况。当我将空间增加到 10240 时，构建运行正常，但在保存更改的文件时触发的后续构建将变为几分钟而不是分钟。更改我做了 "node --max-old-space-size=10240 tools/Server.js auth" 。这似乎是最糟糕的部分，我只有 8GB RAM，而 10GB 是如何解决这个问题的？看起来它在某处虚张声势。
> 附件是webpack生成的报告文件。我希望这对你有帮助。
> 
> [报告.20191213.164836.16708.0.001.zip](https://github.com/webpack/webpack-dev-server/files/3964198/report.20191213.164836.16708.0.001.zip)

I want to ask you how this json file was generated. But it seems that the file does not clearly locate which object caused the memory leak. Even increasing the memory will not solve the fundamental problem. I'm looking for a good monitoring scheme to know which hateful object is occupying my heap memory.
