### ISSUE TITLE
Pass request object along to proxyConfig callback function for conditional proxyConfigs

### ISSUE THREAD

**Issue by RavenHursT** [webpack/webpack-dev-server#2360]
- Operating System: OSX
- Node Version: 10.15.3
- NPM Version: 6.13.1
- webpack Version: 4.41.2
- webpack-dev-server Version: 4.41.2
- Browser: Chrome (latest)

- [ ] This is a **bug**
- [x ] This is a **modification** request

### Code

```js
// webpack.config.js
devServer: {
  .
  .
  .
  proxy: (req) =>
    req.headers.accept.includes('html') ? // req is currently undefined here
      {} : 
      {
        '/': {
          target: 'http://my.backend.api',
          logLevel: 'debug',
          secure: false
        }
     }
}
```

### Expected Behavior
Be able to modify `proxyConfig` based on incoming requests.
### Actual Behavior
Right now `req` and `res` are not passed into a given `proxyConfig`-generating function, so there's no way to  alter the proxy config based on introspection of a given incoming request.
See: https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L290-L292
### For Features; What is the motivation and/or use-case for the feature?
I'm trying to proxy requests on `/`, but only for _specific_ content types.  If the request object were passed along to the provided `proxyConfig` callback function, then hypothetically the returned `proxyConfig` could then be altered to either proxy requests w/ `path: '/'`, or not, based on introspection of the request's `Content-Type` header (or any other condition the developer should choose).

For my specific use case, I've attempted to use the `bypass` option, but I'm not seeing how to accomplish my goals with that option.  The details of which can be found in this SO question: https://stackoverflow.com/questions/59400158/how-do-i-proxy-some-requests-to-using-http-proxy-middleware-for-webpack

Furthermore, I don't see anywhere in documentation that suggests a `function` can be provided for the `proxyConfig`.  I only see a plain object, or an array of objects as acceptable values for the `proxy` option for the `devServer` config: https://webpack.js.org/configuration/dev-server/#devserverproxy

I only discovered this option by diving into the source code here.  It may be worthwhile to update the documentation w/ the option to provide a callback function that returns a `proxyConfig` for the value provided to the `proxy` option.

**Comment by evilebottnawi** [comment]
I can't understand problem, do you solve this? problem in documentation?

**Comment by RavenHursT** [comment]
I solved the problem I was trying to solve in the SO question, ultimately.  But I do think this is still a needed change.  What's the point of calling a callback for `proxyConfig` if you're not passing along any context to it?

**Comment by evilebottnawi** [comment]
Feel free to improve this

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/2714
