### ISSUE TITLE
The [before] and [after] option hook not allow http POST request?

### ISSUE THREAD

**Issue by DemonCloud** [webpack/webpack-dev-server#2370]
Operating System: Mac OS 10.15.2
Node Version: 13.5.0
NPM Version: 6.13.4
webpack Version: 4.41.4
webpack-dev-server Version: 3.10.1
Browser: Chrome

! This is a bug

I was writing an express middleware, try to send request dev server, but it not allowed!
** But webpack-dev-server 3.9.0 work fine!!!**

<img width="526" alt="Screen Shot 2019-12-25 at 11 22 09 AM" src="https://user-images.githubusercontent.com/7436361/71430929-9f5bbd80-2709-11ea-8394-d652cbea4a24.png">

**Comment by evilebottnawi** [comment]
Please create reproducible test repo
