### ISSUE TITLE
Update chokidar to v3

### ISSUE THREAD

**Issue by paulmillr** [webpack/webpack-dev-server#2376]
So the decision to keep chokidar v2 around for another year causes more and more users to have issues. https://github.com/fsevents/fsevents/issues/301 It will keep getting worse.

Chokidar v2 uses fsevents v1, which needs node-gyp, may download shady binaries (I say shady even though i'm the maintainer of fsevents) from AWS, causes people to get crazy because of node-gyp's Python v2 dependency (which would become unsupported for security updates in 3 days); breaks the build from time to time.

I **strongly** suggest updating to chokidar v3! nodejs v8 will be officially unsupported in a couple days. For those who want to stick around with v8, there's always an option to use older webpack-dev-server. 

Benefits of upgrading to chokidar v3 are described in [a blog post](https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/):

- 4.9x faster installtion time
- 9x less traffic to download the pkg
- 13x less dependencies (15 vs 201)
- 16x smaller node_modules size
- Not needing to build a binary on macos! node's nan api is great and works perfectly here.

The downside is just the fact that it requires node 8.10 or higher — not even v10.x.

**Comment by evilebottnawi** [comment]
Will be done in next, we can't do it right now, because we still support node@6, release next version will be in next year

**Comment by silverwind** [comment]
Any news? I'm personally getting tired of dealing with [`node-gyp` errors](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md).

**Comment by HawkeyePierce89** [comment]
> because we still support node@6

what about people with Node@13 ?

**Comment by HawkeyePierce89** [comment]
@silverwind you can instal your dependencies like a option `yarn install --ignore-optional` or `npm install --no-optional`

**Comment by HawkeyePierce89** [comment]
@silverwind ok, I found how fix this shit (next commands for yarn)

* `rm -rf node_modules`
* `yarn cache clean`
* delete yarn.lock OR partially change [fsevents section in yarn.lock](https://github.com/HawkeyePierce89/react-react-and-to-production/commit/a8fb52531ba27189c21ae393430f326e7e00fdf1#diff-8ee2343978836a779dc9f8d6b794c3b2R3603) 
* `yarn install --ignore-optional`

**Comment by silverwind** [comment]
I'd rather wait for the dependency update then try such dangerous workarounds 😉
