### ISSUE TITLE
WDS won't connect using HTTPS

### ISSUE THREAD

**Issue by simkessy** [webpack/webpack-dev-server#2377]
- Operating System:
- Node Version: 12
- NPM Version: 6
- webpack Version: latest
- webpack-dev-server Version: latest
- Browser: Chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
module.exports = Object.assign(baseConfig, {
  output: {
    path: path.resolve(ROOT_PATH, 'dist'),
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].bundle.js',
    hotUpdateMainFilename: 'hot-update.json',
    hotUpdateChunkFilename: 'hot-update.js'
  },
  mode: 'development',
  devtool: 'cheap-module-eval-source-map',
  devServer: {
    allowedHosts: ['.ec2.pin220.com', '.pinterdev.com'],
    // 0.0.0.0 binds to all interfaces. The public port is 8080 which is served
    // by nginx and proxied to the internal webpack port of 10005.
    host: '0.0.0.0',
    port: 10005,
    hotOnly: true,
    publicPath: '/',
    // headers: { 'Access-Control-Allow-Origin': '*' },
    https: false,
    // hot: true,
    headers: {
      'Access-Control-Allow-Origin': '*'
    },
    disableHostCheck: true
  }
```

### Actual Behavior
When I run WDS and access my site through HTTPS I get "WDS Disconnected!"
When I access through HTTP, WDS works. However HMR looks for the hot-update.js file under the HTTPS path. So 404 not found for the the update 

### Expected Behavior
How do I get WDS to work under HTTPS?

**Comment by simkessy** [comment]
I was able to fix this by setting `  sockPort: 8080,` to match the port nginx is using to serve the app. So now I have it connecting under HTTPS but it just says

`[HMR] Checking for updates on the server...`

**Comment by evilebottnawi** [comment]
Closing in favor https://github.com/webpack/webpack-dev-server/issues/2378
