### ISSUE TITLE
Stuck on [HMR] Checking for updates on the server...

### ISSUE THREAD

**Issue by simkessy** [webpack/webpack-dev-server#2378]
- Operating System: Linux
- Node Version: 12
- NPM Version: 6
- webpack Version: 4
- webpack-dev-server Version: 3
- Browser: Chrome

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
  output: {
    path: path.resolve(ROOT_PATH, 'dist'),
    publicPath: '0.0.0.0:10005/',
    filename: '[name].bundle.js',
    chunkFilename: '[id].bundle.js'
  },
  devServer: {
    allowedHosts: ['.ec2.pin220.com', '.pinterdev.com'],
    // 0.0.0.0 binds to all interfaces. The public port is 8080 which is served
    // by nginx and proxied to the internal webpack port of 10005.
    host: '0.0.0.0',
    port: 10005,
    hotOnly: true,
    publicPath: '0.0.0.0:10005/'
  }
```

```js
if (module.hot) module.hot.accept();

const root = document.getElementById('root');

if (root !== null) {
  ReactDOM.render(<App />, root);
}

```

### Expected Behavior
Work
### Actual Behavior
Doesn't work, just says 
```
[WDS] App hot update...
log.js?1afd:24 [HMR] Checking for updates on the server...
```

**Comment by evilebottnawi** [comment]
Please create full reproducible test repo

**Comment by evilebottnawi** [comment]
Try to use `publicPath: '/'`

**Comment by simkessy** [comment]
It didn't help. Im looking at the nginx settings:

```
upstream app_webpack_upstream {
  server localhost:10005;
}
server {
  listen 8080;
  server_name ~^(?!api).*.mysite.com;
  access_log /var/log/nginx/mysite.com/app_access.log;
  error_log /var/log/nginx/mysite.com/app_error.log;
  ssl on;
  ssl_certificate /etc/ssl/certs/star.mysite.com.crt;
  ssl_certificate_key /etc/ssl/private/star.mysite.com.key;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  location / {
    proxy_pass http://app_webpack_upstream;
    proxy_set_header X-Forwarded-Protocol ssl;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    include /etc/nginx/conf.d/proxy.conf;
    set $upstream_name app_webpack_upstream;
  }
}
```

Other settings too: 

I've been trying to figure out how to get Webpack dev server working with Flask, Docker and nginx. 

I'm not familiar in these technologies so i'm a bit stuck. 

I have a Makefile that contains: 

    server-watch: server-install
    	uwsgi --http-socket 0.0.0.0:10001 --module my:app --master --processes 4 --enable-threads --honour-stdin

my docker file: 

      client-dev:
        image: node:12.13.1-slim
        working_dir: /code
        networks:
          - dev_net
        ports:
          - 10005:10005
        volumes:
          - './client:/code'
        environment:
          NODE_ENV: "development"
        command: yarn dev

webpack dev settings: 

 

     devServer: {
        allowedHosts: ['.ec2.100.com', '.site.com'],
        // 0.0.0.0 binds to all interfaces. The public port is 8080 which is served
        // by nginx and proxied to the internal webpack port of 10005.
        host: '0.0.0.0',
        port: 10005,
        hot: true,
        sockPort: 8080,
        hotOnly: true,
        compress: true, watchOptions: {
          poll: true
        },
        headers: {
          'Access-Control-Allow-Origin': '*'
        }
      }

yarn dev runs:
> webpack-dev-server --progress --colors --hot --inline --config ./webpack.dev.config.js

**Comment by evilebottnawi** [comment]
Why you use nginx for dev server? I can't reproduce problem, please create reproducible test repo with instruction, it is hard to read configuration from issue, also it is not fully instructions and i don't know you project

**Comment by simkessy** [comment]
I think my problem relates to this: https://github.com/webpack/webpack-dev-server/pull/1664

We just NGINX as a proxy server in front of docker.  I don't personally know why but that's the setup we have.

**Comment by evilebottnawi** [comment]
@simkessy you can setup `socket` host https://webpack.js.org/configuration/dev-server/#devserversockhost

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback

**Comment by takhello** [comment]
Same question：

[HMR] Checking for updates on the server...
--------------------------------------------
No follow-up updates

**Comment by alexander-akait** [comment]
@takhello without reproducible example I can't help
