### ISSUE TITLE
Improve server URL deduction

### ISSUE THREAD

**Issue by jeremejevs** [webpack/webpack-dev-server#239]
Right now, to get the server URL, the [client code](https://github.com/webpack/webpack-dev-server/blob/master/client/index.js#L6) just takes a random `script` element and removes everything from its source URL after the last slash, including the slash itself.

1. If there's no slash in that URL - it takes the script's name = `http://bundle.js/`.
2. If there's a dot and a slash - it takes just the dot = `http://./`.

My HTML file is auto-generated, so I have to use `webpack-dev-server/client?/` as my entry.

Consider utilizing `window.location` instead? Or improving the heuristics?

**Comment by timkrins** [comment]
For my own development workflow, as I am only ever going to be serving on the root of a local network IP or localhost, I changed my index.js to say
`io = io.connect(window.location.host);`
Works for me, but obviously not elegant

**Comment by SpaceK33z** [comment]
The heuristics have improved a lot lately. Does it work for you now, with `1.15.0`?

**Comment by jeremejevs** [comment]
I don't remember what it was supposed to be, never committed it, sorry. Just removed `?/` and it seems to be still working, so there's that.

**Comment by SpaceK33z** [comment]
Okay cool, so closing this because the heuristics are good enough now. There's still room for improvement, but that should be done with specific issues.
