### ISSUE TITLE
Webpack build output differs from what is served via the server

### ISSUE THREAD

**Issue by Legends** [webpack/webpack-dev-server#2391]
- Operating System: Win10
- Node Version: 12.13
- NPM Version: 5.8.0
   "@babel/cli": "^7.7.7",
    "@babel/core": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "ejs-loader": "^0.3.5",
    "html-webpack-plugin": "^4.0.0-beta.11",
    "jest": "^24.9.0",
    "jest-junit": "^10.0.0",
    "nodemon": "1.18.4",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.10.1"
- Browser:chrome

- [?] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const path = require("path");

module.exports = {
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000
  },
  // mode: "development",
  // devtool: 'source-map', 
  optimization: {
    // usedExports: true,
    splitChunks: {
      chunks: 'all',
    },
  },
  resolve: {
    extensions: ['.js', '.json']
  },
  output: {
    /**
     * With zero configuration,
     *   clean-webpack-plugin will remove files inside the directory below
     */
    path: path.resolve(process.cwd(), 'dist'),
  },
  entry: {
    home: path.resolve('./src/pages/home/entry.js'),
    about: path.resolve('./src/pages/about/entry.js')
  },
  module: {
    rules: [
      { test: /\.ejs$/, loader: 'ejs-loader' },
      {
        test: /\.m?js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          }
        }
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin({ verbose: true }),
    new HtmlWebpackPlugin({
      template: "src/layout.js",
      page: 'home/home',
      level1: 'Home',
      level2: 'Private',
      level3: 'Sports',
      dummy: "some string",
      filename: 'index.html',
      title: 'Home',
      chunks: ['home'],
      filename: 'index.html'
    }),
    new HtmlWebpackPlugin({
      template: "src/layout.js",
      page: 'about/about',
      level1: 'Home',
      level2: 'Business',
      level3: 'Coding',
      dummy: "some string",
      filename: 'about.html',
      title: 'About',
      chunks: ['about'],
      filename: 'about.html'
    }),
  ]
};

```

**package.json:**

```
 "scripts": {
    "start": "webpack-dev-server",
    "dev": "webpack  --verbose --display-error-details --colors --mode development",
    "prod": "webpack  --verbose --display-error-details --colors --mode production"
  },
```

**When I run:**

`yarn dev`

**output is:**
![image](https://user-images.githubusercontent.com/966368/72299363-e251e680-3660-11ea-98cf-9bd6712354d7.png)

**When I run:** `yarn start` **in the browser I get:**

![image](https://user-images.githubusercontent.com/966368/72299492-4ecce580-3661-11ea-9952-7be15e0aa5e2.png)

**Question:**
Where does the vendors file come from?

I would expect the files in `dist` folder to be served as is.

**Comment by evilebottnawi** [comment]
webpack-dev-server uses memory-fs so we don't write files in filesystem, you have old output when you run `dev` or `prod`, you can use the https://github.com/webpack/webpack-dev-server/blob/master/lib/options.json#L406 option to always write files in filesystem

**Comment by Legends** [comment]
@evilebottnawi 

But why do i have a vendors file when running `webpack-dev-server` ?
Btw. I am using the CleanWebpackPlugin to clean the dist folder before the compilation emits.

**When doing a webpack build using mode** `production|development`
 
![image](https://user-images.githubusercontent.com/966368/72346002-529a4f80-36d5-11ea-95fd-f7f40994a675.png)

**webpack-dev-server outputs:**

 
![image](https://user-images.githubusercontent.com/966368/72346068-7eb5d080-36d5-11ea-8fe0-cae9dd1d5e8d.png)

**Comment by evilebottnawi** [comment]
Please provide full reproducible test repo, we don't modify your configuration, and do not enable code splitting or other optimizations, so problems in configuration(s)

**Comment by Legends** [comment]
[Here it is](https://github.com/Legends/html-webpack-plugin-layout-2)

**Comment by Legends** [comment]
I made a change before and updated the code to the previous state which reproduces the issue, just in case you have git cloned it already!

**Comment by evilebottnawi** [comment]
It is expected due https://github.com/Legends/html-webpack-plugin-layout-2/blob/master/webpack.config.js#L16.

When you use webpack-dev-server, we add more entries:
- https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L39
- https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L46

It is require for hot reloading/overlay/reloading/etc, but it is increase size of generated bundle file, webpack has default options when code splitting starts to work https://github.com/webpack/webpack/blob/v4.41.5/lib/WebpackOptionsDefaulter.js#L226 so you got this file.

My recommendation is disable any `optimization` in development mode.

**Comment by evilebottnawi** [comment]
Feel free to feedback if you have more questions

**Comment by Legends** [comment]
Ah ok, I thought it serves just the plain build output , didn't know that it bundles the the other stuff too.
Thanks for clarification!
