### ISSUE TITLE
devserver app request post  url get 405

### ISSUE THREAD

**Issue by henryzp** [webpack/webpack-dev-server#2392]
- Operating System: mac
- Node Version: v10.17.0
- NPM Version: 6.11.3
- webpack Version: ^4.40.2
- webpack-dev-server Version: 3.10.2
- Browser: chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I implemented a server function myself, go to compile webpack。

The following code is to proxy local mock requests

```js
// app => devServer.app
app.use(`${prefix}/*`, localMockHandler(prefix, true)); 

function localMockHandler() {
    // return a middleware
    return () => {

    }
}
```

The get request is normal, but the post request will report 405。

but I use `webpack-dev-server@3.8.1`，It is good and normal。

### Expected Behavior

post request can normal。

### Actual Behavior

post request break，it tell me 405，post method not allowed。

**Comment by evilebottnawi** [comment]
Already fixed https://github.com/webpack/webpack-dev-server/pull/2374, just not released yet
