### ISSUE TITLE
WebSocket transportMode is missing heartbeat

### ISSUE THREAD

**Issue by ianschmitz** [webpack/webpack-dev-server#2403]
- Operating System:
- Node Version: 10.18.1
- NPM Version: 	6.13.4
- webpack Version: 4.41.5
- webpack-dev-server Version: 3.9.0
- Browser: Chrome 79

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
webpack-dev-server sends keep alive heartbeat when using `transportMode: 'ws'`, [consistent with sockjs-node](https://github.com/sockjs/sockjs-node/blob/4c9f3009be13962b0785138ccdf527c5abe925f6/lib/transport/websocket.js#L74-L82) to keep the connection open while developing.

### Actual Behavior
WebSocket connection times out after a period of inactivity. A page refresh is needed to reconnect.

Create React App related issue: https://github.com/facebook/create-react-app/issues/8091

### For Bugs; How can we reproduce the behavior?
Use `transportMode: 'ws'`, connect to running webpack-dev-server instance, and wait for socket to timeout.

Here's the RFC for ping/pong in the WebSocket spec: https://tools.ietf.org/html/rfc6455#section-5.5.2

**Comment by evilebottnawi** [comment]
Easy to implement - https://github.com/websockets/ws#how-to-detect-and-close-broken-connections, somebody want to be a champion?

**Comment by Loonride** [comment]
> Easy to implement - https://github.com/websockets/ws#how-to-detect-and-close-broken-connections, somebody want to be a champion?

I can do this

**Comment by evilebottnawi** [comment]
Client doesn't require additional code (browser automatically sends ping)
