### ISSUE TITLE
the vscode snippets can't show when I install webpack-dev-server in my react-app devDependencies

### ISSUE THREAD

**Issue by zhangjm2518** [webpack/webpack-dev-server#2405]
- Operating System: windows 10
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.41.5
- webpack-dev-server Version: 3.10.1
- Browser: 

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please report issue in `vscode`
