### ISSUE TITLE
serve pretty links for HTML i.e. default .html extension

### ISSUE THREAD

**Issue by xLegoz** [webpack/webpack-dev-server#241]
An issue that is run into while working on a project is that many of the static links on pages are provided as pretty links provided by Jekyll. it would be awesome if links without extensions could have a default extension tried. e.g. you hit `localhost:8080/info` the dev server would attempt to serve `info` from static files, and if not found then attempt `info.html`.

I dug around a bit to have Express do this, as it's a setting, but didn't succeed.
The setting to do this for Express is [static] (http://expressjs.com/api.html#express.static) `extensions` property.

The line of interest, or at least where I thought was appropriate was https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L185

**Comment by sokra** [comment]
You can send a PR.

**Comment by SpaceK33z** [comment]
This is possible with the `bypass` method in `proxy` now. [See docs](https://webpack.github.io/docs/webpack-dev-server.html#bypass-the-proxy).
