### ISSUE TITLE
Error installing on iojs 3.0.0

### ISSUE THREAD

**Issue by eugene1g** [webpack/webpack-dev-server#242]
Socket.io fails to build on the recently release iojs 3 (as per https://github.com/socketio/socket.io/issues/2213) which means webpack-dev-server fails to build as well. Leaving the issue here as a reference note, but nothing can be done about this until the upstream problem is resolved.

P.S. socket.io fails because of the ws dependency issue as tracked at https://github.com/websockets/ws/issues/549 which has been fixed with updated dependencies as per https://github.com/websockets/ws/commit/ee660710e151779a258f29f33040234c3133a63a and awaits publishing to npm. Once ws publishes, socket.io will bump it's dependency version, then webpack-dev-server should work on iojs 3

**Comment by framerate** [comment]
Confirming I see this exact behavior!

**Comment by dlong500** [comment]
Is this fixed now that Nodejs 4.0 (based on iojs) is released?

**Comment by eugene1g** [comment]
webpack-dev-server relies on socket.io, and socket.io currently cannot be compiled on Nodejs4. However, the patch has been applied to socket.io (https://github.com/socketio/socket.io/commit/210e6887327e6afed4761940fae405b8e784e8e1) and now webpack awaits for them to cut a new release. A lot of other projects are in the same boat, so it's likely to happen very soon.

**Comment by lucasterra** [comment]
@dlong500 no.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by eugene1g** [comment]
A temporary hack on how to get webpack-dev-server working on iojs3 is posted at https://github.com/webpack/webpack-dev-server/issues/260#issuecomment-139842716

**Comment by SpaceK33z** [comment]
A new version of socket.io including the patch is now released, so after re-adding the `webpack-dev-server` package this issue should be fixed. Please test this.

**Comment by jdhiro** [comment]
@SpaceK33z I've confirmed that it works now.
