### ISSUE TITLE
ngrok is not working with web-pack 

### ISSUE THREAD

**Issue by divya-kanak** [webpack/webpack-dev-server#2423]
- Operating System: window 10
- Node Version: v8.5.0
- NPM Version: 5.3.0
- webpack Version: 2.2.0
- webpack-dev-server Version: 2.2.0
- Browser: Chrome

I have tried to serve the app from using webpackserver 

`webpack output is served from http://localhost:8080/
`
Then, I have start tunnel from ngrok

`ngrok http 8080`

Output is http://prntscr.com/qwojpl

Issue: this is working fine with my pc only, but when I fire this from other's pc, this is not working. The app is going with infinite loading.

Anyone can help me? where I am going to wrong.

**Comment by evilebottnawi** [comment]
Please fill all questions in the issue template and use stackoverflow for questions, `ngrok` is vendor software, so we can't say about compatibility, better open issue in `ngrok` repo, thanks
