### ISSUE TITLE
Ignore node_modules by default

### ISSUE THREAD

**Issue by j18s** [webpack/webpack-dev-server#2430]
- Operating System: Mac OS X ProductVersion:	10.15.3
- Node Version: v10.10.0
- NPM Version: 6.11.2
- webpack Version: 4.27.1
- webpack-dev-server Version: 3.1.10
- Browser: Firefox Developer Edition 73.0b12

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

In my project after running ```webpack-dev-server``` node process was taking 180% CPU usage. Then I did some research and added the following option in webpack.config.js:

```
   watchOptions: {
      ignored: /node_modules/,
    },
```

I suggest can we make this as default option that webpack will ignore node_modules.

Thanks

**Comment by evilebottnawi** [comment]
Wrong repo, `watchOptions` is part of webpack configuration, not webpack-dev-server, many developers change the code in node_modules when developing, I don’t think it would be a good decision to ignore it by default, anyway you can open an issue in webpack repo and we consider that, thanks for issue
