### ISSUE TITLE
websocket proxying is broken

### ISSUE THREAD

**Issue by dtanabe** [webpack/webpack-dev-server#2432]
The websockets server library used internally by `webpack-dev-server` appears to explicitly forbid multiple listeners on an http.Server's `'upgrade'` event (see this commit https://github.com/websockets/ws/commit/364126620bf3fe4e6e0042d3b74ec53b5ccbbb08), which prevents any other websocket traffic on the same Server.

I found this because I was trying to use [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) as [react-scripts](https://www.npmjs.com/package/react-scripts) recommends:

```js
const proxy = require("http-proxy-middleware");
module.exports = app => {
    // this http-proxy-middleware call's attempt to write to a websocket will fail
    // because lib/servers/WebsocketServer hijacks all upgrades and sends a 400
    // to the client
    app.use(proxy("/ws", {target: "http://localhost:8080", ws: true}));

    // this call is of course fine
    app.use(proxy("/api", {target: "http://localhost:8080"}));
}
```

This leads to a `400 Bad Request`, which is ultimately caused because `websockets/ws` sends this response for all connections it does not recognize (see https://github.com/websockets/ws/blob/9535702e50525621313941f0e1a972fdca403045/lib/websocket-server.js#L208).

I created a similar issue (https://github.com/websockets/ws/issues/1692) for a feature request that would make this issue easier to solve on this end.

**Comment by evilebottnawi** [comment]
Please use the issue template, yes, I closed the issue before you fix it, I get a few dozens messages for helping/fixing/improvements every day and try to help everyone, but every time I have to remind about this, It is inconvenient for me and other developers, I don't know use case, I don't know you configuration, I don't know you environments. All I know is a piece of code. Please respect the work and time of other people, thanks
