### ISSUE TITLE
Updating to the latest 3.10.3 break the live reload

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack/webpack-dev-server#2433]
- Operating System: **Windows 7 x64**
- Node **12.11.1**
- NPM **6.13.4**
- webpack **4.41.6**
- webpack-dev-server **3.10.3**
- Browser: **Google Chrome 80.0.3987.116 x64**

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './index.js',
  output: {
    filename: 'bundle.js',
    path: __dirname
  },
  devServer: {
    contentBase: [
      path.join(__dirname, '/'),
      path.join(__dirname, '/product')
    ],
    watchContentBase: true,
    compress: true
  }
};
```

> `index.js` only contain a `console.log('hello')` call
> contentBase folders just contain `.html` files

### Expected Behavior
WDS should properly reload content inside the `/` and `/product` folders.

### Actual Behavior
WDS doesn't reload/build anything.

### For Bugs; How can we reproduce the behavior?
Just upgrade from `webpack-dev-server@3.10.2` to `webpack-dev-server@3.10.3` break the live reload.

Thanks for the feedback :wink:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, no changes with live reload logic between `3.10.3` and `3.10.4`

**Comment by xavierfoucrier** [comment]
Hi @evilebottnawi,

I am very confused about the `3.10.4`... I made a mistake when writing the issue :roll_eyes:
Probably because I forget to take my coffee this morning haha :sweat_smile: :coffee: ...

Finally, I took time to realize that I wasn't calling the `bundle.js` script in my `.html` file, causing WDS to not reload the page when updating the HTML... everything is now working as expected.

Sorry for the confusion!
