### ISSUE TITLE
If the `devServer` is not set in the `webpack.config.js` file, devServer configuration information is not available in the Webpack Plugin

### ISSUE THREAD

**Issue by nanyuantingfeng** [webpack/webpack-dev-server#2442]
I'm writing a webpack plugin and need to get the devserver configuration information,
I found a problem:
     if the node has be created, even if the registered value of the node
     is an empty object, it will be filled with the correct value during the runtime

```js
// webpack.config.js
module.exports = {
  // ....
}

// Plugin.js
class Plugin {
  apply(compiler){
    compiler.options.devServer 
   // is undefined
  }
}
```

```js
// webpack.config.js
module.exports = {
  // ....    ,

  devServer : {}
}

// Plugin.js
class Plugin {
  apply(compiler){
    compiler.options.devServer 
 // There is correct information available, even if it is set in the cli
  }
}

```

**Comment by evilebottnawi** [comment]
Yes it is expected, just add check `if (compiler.options.devServer) {}`, some values can be calculated only in runtime

**Comment by nanyuantingfeng** [comment]
How do I get cli options and calculated value in runtime ?

**Comment by evilebottnawi** [comment]
You can get them from `process.argv`, what an option do you need?

**Comment by nanyuantingfeng** [comment]
Is it possible to update webpack config options to empty object before running ?  I have checked that , it can get all calculated values in `compiler.options.devServer`

**Comment by nanyuantingfeng** [comment]
Now the situation is that if the user's configuration items are all on the cli, I also need the user to set 'devServer' an empty object in `webpack.config.js` . This is too embarrassing.

**Comment by evilebottnawi** [comment]
You can write:
```js
if (!compiler.options.devServer) {
  compiler.options.devServer = {}
}
```

**Comment by nanyuantingfeng** [comment]
if write like that, i can't get the information I need,   `devServer : {}` must be in the `webpack.config.js`,
at run time, it will be filled it used all the correct values, including `host,port, publicPath...` . 

in script :  `webpack-dev-server --progress --color --port 3000`  
in webpack.config.js : ` module.exports = {  devServer : {} }`

it work .     `compiler.options.devServer`  has value  `host: localhost, port : 3000,  ....`

if in webpack.config.js does not set `devServer : {}`,  
`compiler.options.devServer` is undefined... 

i think set `devServer : {}` is meaningless , because it is an empty obejct, there is no valid information,
but i can't get the value without setting it.

**Comment by nanyuantingfeng** [comment]
https://github.com/webpack/webpack-dev-server/blob/e953d01ca93764dabe38cedad8e7b9ef4e7f04bc/lib/utils/processOptions.js#L8

add :  `config.devServer = config.devServer || {}` ,
it work ..
