### ISSUE TITLE
chore: ignore yarn.lock

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-dev-server#2444]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

as the project is using npm (package-lock.json) , we should ignore the `yarn.lock` , file as it will create unnecessary changes (yarn.lock)  will be committed by a first time contibutor unknowingly if he used yarn to install the dependencies.

**Comment by evilebottnawi** [comment]
Feel free to send a PR
