### ISSUE TITLE
Separate templates for bug_report and feature requests

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-dev-server#2446]
- Operating System: Kali Linux
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

We should have two different templates for bug report and feature request , so a user will be asked to chhose one while creating a new issue. This will increase user experience. 

![Screenshot from 2020-03-06 18-27-33](https://user-images.githubusercontent.com/46647141/76085538-3e3d4980-5fd8-11ea-92ba-2e0d28fbe087.png)

### Actual Behavior
Single issue template.

**Comment by evilebottnawi** [comment]
Thanks for the issue, we don't want to do it, many bugs sounds like features and versa vice
