### ISSUE TITLE
docs: link of deps badge is broken in readme

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-dev-server#2447]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

N/A

- [ ] This is a **bug**
- [ ] This is a **modification** request

N/A
### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
deps badge should be there on readme

### Actual Behavior
broken link of deps badge

![Screenshot (52)](https://user-images.githubusercontent.com/43860289/76159964-dad42880-614b-11ea-90b9-efab4c5cbb89.png)
### For Bugs; How can we reproduce the behavior?
N/A
### For Features; What is the motivation and/or use-case for the feature?
N/A

**Addition Information**
I will work on this issue

**Comment by evilebottnawi** [comment]
Make sure that the provider gives you access to the web resource, everything works well
