### ISSUE TITLE
chore: issue template contains unnecessary spaces

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-dev-server#2448]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:
N/A

- [ ] This is a **bug**
- [ ] This is a **modification** request
N/A

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
Spacing between words should be correct
### Actual Behavior
Wrong Spacing between words.
### For Bugs; How can we reproduce the behavior?
N/A
### For Features; What is the motivation and/or use-case for the feature?
N/A
**Additional Information**
I will work on this issue

**Comment by evilebottnawi** [comment]
It is expected, we don't want to change it
