### ISSUE TITLE
devServer break optimization.moduleIds expected behavior

### ISSUE THREAD

**Issue by EugeneJao** [webpack/webpack-dev-server#2469]
- Operating System: macOS 10.14.6
- Node Version: v13.7.0
- NPM Version: 6.13.6
- webpack Version:4.42.0
- webpack-dev-server Version:3.10.3
- Browser: not browser's business

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: '[name].runtime.js',
    path: path.resolve('./dist'),
    publicPath: '',
  },
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000,
    writeToDisk: true,
  },
  optimization: {
    moduleIds: 'hashed',
    runtimeChunk: {
      name: entrypoint => `runtime~${entrypoint.name}`
    }
  },
};
```

### Expected Behavior
all compiled moudules have a hashed moduleid
### Actual Behavior
the moduleid of entry module is a zero, not a hashed string.
### For Bugs; How can we reproduce the behavior?
just create a index.js under the src dir, and compile this file with webpack.

**Comment by evilebottnawi** [comment]
Can't reproduce all works fine

**Comment by EugeneJao** [comment]
u mean that entry's moduleid on the file named 'main.runtime.js' which outputed by webpack-dev-sever is a hashed code, not a natrual number? attach my compiled code
[main.runtime.txt](https://github.com/webpack/webpack-dev-server/files/4357535/main.runtime.txt)
:

**Comment by evilebottnawi** [comment]
You can find in your code `+gfj`, it is hashed module
