### ISSUE TITLE
Watcher API

### ISSUE THREAD

**Issue by ivan-kleshnin** [webpack/webpack-dev-server#247]
http://webpack.github.io/docs/node.js-api.html documents an access to watcher API.
So I can hook on rebuilds by providing a handler to `compiler.watch` function.

```js
let watcher = compiler.watch(watchOptions, handler); // handler is called on every build!
```

Does Webpack-Dev-Server API expose an access to a watcher?
http://webpack.github.io/docs/webpack-dev-server.html#api contains not clues unfortunately.
How to hook on rebuilds in the case Webpack-Dev-Server API is used?

**Comment by sokra** [comment]
add a plugin on `"done"`

**Comment by ivan-kleshnin** [comment]
Can you provide some links to consider?

**Comment by SpaceK33z** [comment]
See https://github.com/webpack/docs/wiki/plugins. Closing because of staleness, but feel free to comment and I'll reopen.

**Comment by sbergotts** [comment]
I think it would be a good thing to have because it would allow tool makers to plug a custom logger on emitted stats. Right now that is not possible.
