### ISSUE TITLE
please update npm repository

### ISSUE THREAD

**Issue by vedmalex** [webpack/webpack-dev-server#248]
version in repository doesn't compiles with iojs 3.x because of old dependency socket.io 1.3.3

**Comment by mathieumg** [comment]
+1 :+1: It was fixed about 2 months ago and still not tagged. :(

**Comment by eranimo** [comment]
:+1:

**Comment by sokra** [comment]
The current socket.io neither works, see https://github.com/webpack/webpack-dev-server/issues/260#issuecomment-139842716

**Comment by SpaceK33z** [comment]
This should be fixed now with the new socket.io version being released.
