### ISSUE TITLE
TypeError: Cannot set property 'ckeFiller' of undefined

### ISSUE THREAD

**Issue by UzairAshraf1314141** [webpack/webpack-dev-server#2480]
Hello,
I'm facing following error while creating build of angular 7 with SSR(Express-Enginee).

> Fourlead@4.3.0 serve:ssr D:\Repos\FourleadWeb
> node dist/server

D:\Repos\FourleadWeb\dist\server.js:354026
!function(t){t.en=Object.assign(t.en||{},{a:"Cannot upload file:",b:"Image toolbar",c:"Table toolbar",d:"Bold",e:"Insert image or file",f:"Choose heading",g:"Heading",h:"Full size image",i:"Side image",j:"Left aligned image",k:"Centered image",l:"Right aligned image",m:"image widget",n:"Block quote",o:"Numbered List",p:"Bulleted List",q:"Increase indent",r:"Decrease indent",s:"Insert image",t:"Insert table",u:"Header column",v:"Insert column left",w:"Insert column right",x:"Delete column",y:"Column",z:"Header row",aa:"Insert row below",ab:"Insert row above",ac:"Delete row",ad:"Row",ae:"Merge cell up",af:"Merge cell right",ag:"Merge cell down",ah:"Merge cell left",ai:"Split cell vertically",aj:"Split cell horizontally",ak:"Merge cells",al:"Italic",am:"Insert media",an:"The URL must not be empty.",ao:"This media URL is not supported.",ap:"media widget",aq:"Upload failed",ar:"Enter image caption",as:"Link",at:"Could not obtain resized image URL.",au:"Selecting resized

TypeError: Cannot set property 'ckeFiller' of undefined
    at jo (D:\Repos\FourleadWeb\dist\server.js:354026:150866)
    at Module.<anonymous> (D:\Repos\FourleadWeb\dist\server.js:354026:161631)
    at n (D:\Repos\FourleadWeb\dist\server.js:354026:1970)
    at D:\Repos\FourleadWeb\dist\server.js:354026:2769
    at D:\Repos\FourleadWeb\dist\server.js:354026:2779
    at D:\Repos\FourleadWeb\dist\server.js:354026:1822
    at Object.<anonymous> (D:\Repos\FourleadWeb\dist\server.js:354026:1836)
    at __webpack_require__ (D:\Repos\FourleadWeb\dist\server.js:20:30)
    at Object.@ckeditor/ckeditor5-build-classic (D:\Repos\FourleadWeb\dist\server.js:183305:18)
    at __webpack_require__ (D:\Repos\FourleadWeb\dist\server.js:128986:30)

![image](https://user-images.githubusercontent.com/61478358/77365516-168c0680-6d78-11ea-974c-ef31099537bd.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It is problem with your code in `dist/server.js`

**Comment by millemax** [comment]
ayudaaaaaa tengo el mismo problema
