### ISSUE TITLE
v3.10.3 Can't resovle 'loglevel'

### ISSUE THREAD

**Issue by Aidan-OS** [webpack/webpack-dev-server#2483]
- Operating System: MacOS 10.15.3
- Node Version: 12.16.1
- NPM Version: 6.13.4
- Yarn Version: 1.22.4
- webpack Version: 4.42.0
- webpack-dev-server Version: Tested on versions 3.5.0 - 3.10.3
- Browser: Chrome, Electron

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const webpack = require('webpack');
let path = require('path');
let CopyWebpackPlugin = require('copy-webpack-plugin');


module.exports = [{
		context: path.join(__dirname, '../app'),
		devtool: 'inline-source-map',
		entry: {
			'app': [
				'@babel/polyfill',
				'react-hot-loader/patch',
				'webpack-dev-server/client?http://localhost:8080',
				'webpack/hot/only-dev-server',
				'./src/main/js/index.js',
			],
		},
		output: {
			path: path.resolve(__dirname, './app/build'),
			filename: 'app.bundle.js',
			publicPath: 'http://localhost:8080/',
		},
		devServer: {
			hot: true,
			publicPath: 'http://localhost:8080/',
			historyApiFallback: true,
		},
		// MANUALLY SPECIFY TARGET - THIS IS REQUIRED TO RESOLVE A DEPENDENCY WITHIN THE RPC CLIENT MODULE AND WEBPACK
		target: "electron-main",
		module: {
			rules: [
				{
					exclude: /node_modules/,
					test: /\.js$/,
					loader: 'babel-loader',
					query: {
						presets: ['@babel/preset-react'],
						plugins: ["@babel/plugin-transform-destructuring", "@babel/plugin-proposal-object-rest-spread"]
					},
				},
				{
					test: /\.css/,
					use: ['style-loader', 'css-loader']
				}
			],
		},
		resolve: {
			mainFields: ['module', 'browser', 'main']
		},
		plugins: [
			new webpack.HotModuleReplacementPlugin(),
			new webpack.NamedModulesPlugin(),
			new CopyWebpackPlugin([
				{ from: './src/main/app.js' },
				{ from: './src/main/index.html', to: 'index.html' },
				{ from: './src/main/res', to: 'res' },
			]),
		],
	},
	////////////////
	{
		context: path.join(__dirname, '../app'),
		devtool: 'source-map',
		entry: {
			'app': [
				'react-hot-loader/patch',
				'./src/main/index.html',
				'webpack-dev-server/client?http://localhost:8080',
				'webpack/hot/only-dev-server',
			],
		},
		output: {
			path: path.resolve(__dirname, '../app/build/'),
			filename: 'app.bundle.js',
			publicPath: '/',
		},
		target: "electron-renderer",
		module: {
			rules: [
				{
					exclude: /node_modules/,
					test: /\.html$/,
					loader: 'html-loader',
				},
				{
					test: /\.css/,
					use: ['style-loader', 'css-loader']
				}],
		},
		resolve: {
			mainFields: ['browser', 'module']
		},
		plugins: [
			new webpack.HotModuleReplacementPlugin(),
			new CopyWebpackPlugin([
				{
					from: './src/main/index.html',
					to: path.join(__dirname, '../app/build/')
				},
			]),
			new webpack.NamedModulesPlugin(),
		],
	}
];
```
### Expected Behavior
running "webpack-dev-server --color --config ./configs/webpack.dev.config.js" should compile and run without error

### Actual Behavior
Webpack fails to pack, with this being the error
```
    ERROR in ../node_modules/webpack-dev-server/client/utils/log.js
    Module not found: Error: Can't resolve 'loglevel' in '/Users/user/app-name/node_modules/webpack-dev-server/client/utils'
     @ ../node_modules/webpack-dev-server/client/utils/log.js 3:10-29
     @ ../node_modules/webpack-dev-server/client?http://localhost:8080
     @ multi ../node_modules/webpack-dev-server/client?http://localhost:8080 ../node_modules/webpack/hot/dev-server.js react-hot-loader/patch ./src/main/index.html webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server
```
This is error is the same as in https://github.com/webpack/webpack-dev-server/issues/1000, and does not appear to be fixed.

### For Bugs; How can we reproduce the behavior?
Create a basic Electron 8 Application and attempt to package it with webpack

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, I can't reproduce locally

**Comment by Aidan-OS** [comment]
I have a test repo made: https://github.com/Aidan-OS/min-repo-webpack-dev-server
Run the "hot" script in package.json

**Comment by Aidan-OS** [comment]
Hi! It's been a couple weeks now, any progress?

**Comment by evilebottnawi** [comment]
Problem in `mainFields`, why do you change it?

**Comment by Aidan-OS** [comment]
`mainFields` in both my original example and test repo are the same, so I assume you are talking about the default. Looking through the commits on our main repo, it seems that this was done due to a Firebase issue, removing both `resolve` sections results in this error:
![image](https://user-images.githubusercontent.com/1919827/78701235-ae3f3800-78d4-11ea-97a8-4687972ec0e4.png)

**Comment by evilebottnawi** [comment]
```diff
'app': [
				'@babel/polyfill',
				'react-hot-loader/patch',
-				'webpack-dev-server/client?http://localhost:8080',
-				'webpack/hot/only-dev-server',
				'./src/main/js/index.js',
			],
```

```diff
entry: {
			'app': [
				'react-hot-loader/patch',
				'./src/main/index.html',
-				'webpack-dev-server/client?http://localhost:8080',
-				'webpack/hot/only-dev-server',
			],
		},
```

```diff
plugins: [
-			new webpack.HotModuleReplacementPlugin(),
			new CopyWebpackPlugin([
				{
					from: './src/main/index.html',
					to: path.join(__dirname, '../app/build/')
				},
			]),
			new webpack.NamedModulesPlugin(),
		],
```

Why do you add that? Where docs say about it? Please do not touch `mainFields` if you don't known what you do.

**Comment by evilebottnawi** [comment]
What a command from package.json I should use to debug your repo?

**Comment by Aidan-OS** [comment]
I am a student that had been tasked with upgrading from electron 4 to electron 8. I have no actual experience in JavaScript or Electron. The reason parts of this code is wrong is most likely due to its age. I have removed the lines you have suggested and the issue remains the same. 

I am currently updating the test repo to make it suitable to test for this new error, as it was more stripped down than this new error requires.

**Comment by evilebottnawi** [comment]
@Aidan-OS feel free to ping me when it will be ready

**Comment by Aidan-OS** [comment]
Alright @evilebottnawi I have updated the repo to the point of being able to test for this new error. To run the repo, simply install with npm or yarn then run the `hot` script in one terminal window and the `dev` script afterwards (while hot is still runnning) in another.

**Comment by evilebottnawi** [comment]
There are a lot of invalid options and configurations, I understand that you are a new developer, but unfortunately I can not help all new developers, my recommendation is to use a working solution - https://github.com/electron-userland/electron-webpack, there are a lot of guides and examples. You can us stackoverflow or gitter for questions. It’s best to start with something working and see how it works.

Problem does not apply to webpack-dev-server, it is more related to electron, so better use their repo for asking questions. Sorry again.
