### ISSUE TITLE
Add API to close dev server

### ISSUE THREAD

**Issue by tricoder42** [webpack/webpack-dev-server#249]
I'm trying to close webpack dev server programatically, so I can run it it task with webdriverio.

The webpack API already provides *listen* method which delegates listen call and inits socket.io. I tried to add close method with similar functionality, but couldn't get it work (the process still hangs). 

```javascript
Server.prototype.close = function(callback) {
	this.io.close();
	this.io = null;

	this.listeningApp.close(callback);
	this.listeningApp = null;
}
```

Any ideas?

**Comment by TheLarkInn** [comment]
Fixed

**Comment by cbelhaffef** [comment]
Hi,
How i can stop webpack-dev-server programaticaly ? like webpack-dev-server close() for example ...

**Comment by SpaceK33z** [comment]
Like you said, with `close()`?

**Comment by cbelhaffef** [comment]
i used but nothing happen.. :(

**Comment by SpaceK33z** [comment]
Which version of dev-server are you using? Can you share the relevant part of your code?

**Comment by cbelhaffef** [comment]
version : 1.14.1

var WebpackDevServer = require("webpack-dev-server");
var webpack = require("webpack");

`var compiler = webpack({
......
.....
});
var server = new WebpackDevServer(compiler, {  
});
server.listen(3000, "localhost", function() {});

server.close();
`

the server started but not closed.

**Comment by SpaceK33z** [comment]
Can you try changing `localhost` to `127.0.0.1`? This causes a lot of weird errors (see #183).

**Comment by cbelhaffef** [comment]
Hi, 
nothing changed.

**Comment by pavel06081991** [comment]
@SpaceK33z, have the same issue, "webpack-dev-server": "^2.4.2", the server is alive even after calling stop() method. Do you have any idea why it happens?

**Comment by pkearney13** [comment]
Same here..

**Comment by AlexLeung** [comment]
After I call the close it still seems to be alive.
