### ISSUE TITLE
webpack-dev-server doesn't support --display-modules

### ISSUE THREAD

**Issue by mgummelt** [webpack/webpack-dev-server#2504]
- Operating System: Ubuntu 18.04
- Node Version: 12.16.1
- NPM Version: 6.14.4
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: chrome

- [X ] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

`webpack-dev-server --display-modules` should show all modules built by webpack.

### Actual Behavior

`webpack-dev-server --display-modules` still shows ` + 976 hidden modules`.  `--display-modules` has no effect.

**Comment by evilebottnawi** [comment]
We never support `--display-modules`, we refactor our CLI for next major release, you can use the `stats` option to setup it
