### ISSUE TITLE
Insecure dependency in tree from chokidar

### ISSUE THREAD

**Issue by seancrater** [webpack/webpack-dev-server#2505]
- webpack-dev-server Version: 3.10.3

- [ x ] This is a **bug**
- [ ] This is a **modification** request

### Code
```js
└─┬ webpack-dev-server@3.10.3
  └─┬ chokidar@2.1.8
    └─┬ fsevents@1.2.9
      └─┬ node-pre-gyp@0.12.0
        ├─┬ mkdirp@0.5.1
        │ └── minimist@0.0.8 
        └─┬ rc@1.2.8
          └── minimist@1.2.0 
```

### For Bugs; How can we reproduce the behavior?
This is a high severity security issue, can be resolved by updating chokidar in this repo.

**Comment by evilebottnawi** [comment]
Fixed, please update your lock file, problem already fixed
