### ISSUE TITLE
WDS log lines grab too much attention

### ISSUE THREAD

**Issue by itayganor** [webpack/webpack-dev-server#2509]
- Operating System: Windows 10 64bit
- Node Version: v11.1.0
- NPM Version: 6.4.1
- webpack Version: 4.42.1
- webpack-dev-server Version: 3.10.3
- Browser: Chrome 80.0.3987.163

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior
![image](https://user-images.githubusercontent.com/6430313/78888868-335c5580-7a6b-11ea-982f-ed3323e66faa.png)
Although they all start with `[WDS]`, WDS logs mingle with the app's code logs.

### Actual Behavior
WDS log lines should be less opaque to not mix with the logic's log lines.

### For Features; What is the motivation and/or use-case for the feature?

This is actually super easy to achieve:
![image](https://user-images.githubusercontent.com/6430313/78888971-6d2d5c00-7a6b-11ea-900a-240eacbf83e5.png)

Every project uses `console.log` to track events or for debugging. Sometimes, there are quite a lot of them, especially when hot-reloading the app. In this case, there are multiple WDS log lines with every hot-reload state, like *Compiling*, *Disconnected*, etc.\
While those logs are totally important and shouldn't be dropped by any means, I do think they should be a little bit more subtle.\
Making those log lines gray, for example, will help your eye separate development-related logs and logic-related logs.

If not as the default, I think that adding a formatter option to webpack-dev-server configuration can make development adaptive and fit to everyone :)

**Comment by evilebottnawi** [comment]
> WDS log lines should be less opaque to not mix with the logic's log lines.

Sorry, it can be fixed, you can disable logs if you want

**Comment by itayganor** [comment]
> > Although they all start with [WDS], WDS logs mingle with the app's code logs.
> 
> Sorry, it can be fixed, you can disable logs if you want

Disabling logs is not a solution; they are helpful and important. I do think adding a simple formatter option could be awesome.

Actually it can be done really simply, since webpack-dev-server uses `loglevel` for logs, and they support custom plugins. If only we could insert a `loglevel` plugin in webpack config.. Don't you think? 😊

**Comment by evilebottnawi** [comment]
> Actually it can be done really simply, since webpack-dev-server uses loglevel for logs, and they support custom plugins. If only we could insert a loglevel plugin in webpack config.. Don't you think? blush

Next version uses webpack built-in logger and we can't implement it, you can create a plugin for it in future, current version only for bug fixes and very important features
