### ISSUE TITLE
jquery 3.4.1 has known vulnerabilities: severity: medium

### ISSUE THREAD

**Issue by rajkeshwar** [webpack/webpack-dev-server#2515]
- Operating System: macOS 10.15.3 (19D76)
- Node Version: v10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.41.6
- webpack-dev-server Version: 3.10.3
- Browser: Google Chrome 80.0.3987.163

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
Should not have any vulnerabilities issue.

### Actual Behavior
jquery 3.4.1 has known vulnerabilities: severity: medium; summary: Regex in its jQuery.htmlPrefilter  sometimes may introduce XSS; https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

### For Bugs; How can we reproduce the behavior?
```sh
retire --jspath node_modules/
```

**Comment by evilebottnawi** [comment]
Fixed, release will be soon (today)

**Comment by JulianMeinhardt** [comment]
Is there any info when this fix will be released?

**Comment by evilebottnawi** [comment]
In near future
