### ISSUE TITLE
Redirect http traffic to https when listening on https protocol

### ISSUE THREAD

**Issue by axos88** [webpack/webpack-dev-server#2517]
- Operating System: n/a
- Node Version: 10.20.1
- NPM Version: 6.14.4
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.9.0
- Browser: chrome, but not really important.

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

When listening on https protocol, any received http traffic should be (optionally) redirected to https, or handled without initiating an ssl context.

### Actual Behavior

Connection is closed prematurely. One needs to type in https://localhost:4200 manually instead, which is not automatically saved into the quicksearch bar of chrome.

### For Features; What is the motivation and/or use-case for the feature?

When developing an application locally, typing in say `localhost:4200` into the address bar opens a connection using http protocol by default, and chrome returns an `ERR_EMPTY_RESPONSE` error, wihtout trying to connect using https.

A 302 response to the same endpoint with https protocol would take care of this issue.

A most simple implementation would take a look at the first few bytes of the incoming stream *before* initiating the ssl context and if it equals `GET`, it would handle the connection in a special manner, returning a 302.

**Comment by evilebottnawi** [comment]
Sounds good, but we need additional server on `http` for that, related https://github.com/webpack/webpack-dev-server/issues/126

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack/webpack-dev-server/issues/126
