### ISSUE TITLE
security vulnerability of webpack-dev-server dependency set-value via http-proxy-middleware@0.19.1

### ISSUE THREAD

**Issue by SteveBadera** [webpack/webpack-dev-server#2519]
- Operating System: Linux bc57d375619e 4.19.76-linuxkit
- Node Version: v8.16.2
- NPM Version: 6.4.1
- webpack Version: 4.0.7
- webpack-dev-server Version: 3.10.3
- Browser:

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
=> Found "cache-base#set-value@2.0.1"
info This module exists because "micromatch#snapdragon#base#cache-base" depends on it.
=> Found "union-value#set-value@2.0.1"
info This module exists because "micromatch#snapdragon#base#cache-base#union-value" depends on it.
```

### Expected Behavior
webpack-dev-server no longer relies on http-proxy-middleware@0.19.1

### Actual Behavior
webpack-dev-server relies on http-proxy-middleware@0.19.1 which creates vulnerable nested dependencies for set-value@2.0.1

### For Bugs; How can we reproduce the behavior?
$ yarn why set-value

### For Features; What is the motivation and/or use-case for the feature?
fix security vulnerability

**Comment by evilebottnawi** [comment]
Please provide scripts for getting vulnerability

**Comment by SteveBadera** [comment]
Apologies, set-value 2.0.1 is not impacted by the vulnerability. I thought it was everything <3.0.1;

<2.0.1,>=3.0.0 <3.0.1
https://snyk.io/vuln/npm:set-value
