### ISSUE TITLE
Add possibility to hide even startup information when quiet === true

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack-dev-server#2525]
- Operating System: OSX
- Node Version: v13.13.0
- NPM Version: 6.14.4
- webpack Version: 4.42.1
- webpack-dev-server Version: 3.10.3
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### [REPRODUCIBLE REPO](https://github.com/marcofugaro/repro-webpack-dev-server)

```js
// webpack.config.js
module.exports = {
  devServer: {
    clientLogLevel: 'silent',
    quiet: true,
  }
}
```

From the [documentation](https://webpack.js.org/configuration/dev-server/#devserverquiet-)

> With `devServer.quiet` enabled, nothing except the initial startup information will be written to the console.

However I want to hide also the startup information. 

This happened since https://github.com/webpack/webpack-dev-server/pull/2235, is there a plan to support hiding that information as well again?

### Expected Behavior
Nothing should be outputted to the console

### Actual Behavior
<img width="415" alt="Screenshot 2020-04-20 at 20 06 57" src="https://user-images.githubusercontent.com/7217420/79784516-a8b90780-8342-11ea-989f-9a34612c54de.png">

### For Features; What is the motivation and/or use-case for the feature?
I am using webpack-dev-server in a custom webapp builder, where I have my custom logs. Something like [create-react-app](https://github.com/facebook/create-react-app). I want to decide what is output to the console and what not.

**Comment by neberej** [comment]
There is `noInfo: true` for this scenario. 

I use the following settings and see no console output.

```
 devServer: {
      clientLogLevel: 'silent',
      noInfo: true
    },
```

**Comment by marcofugaro** [comment]
@neberej I've tried your configuration, it still shows the initial information.

I've made a [repro](https://github.com/marcofugaro/repro-webpack-dev-server) if you want to check it out.

**Comment by jquense** [comment]
This is confusing behavior. WDS is explicitly bypassing the configured logger when `quiet` is true. `quiet` should mean what is says, no logs

**Comment by evilebottnawi** [comment]
@jquense yep, for v4 we migrate on built-in webpack logger (so fixed), so you can easy disable all logs, for v3 you should use `noInfo: true` (we can't change it because it is a breaking change)

**Comment by thealjey** [comment]
@alexander-akait 
even with `stats: "errors-warnings",` (or even with `"none"`) in webpack.config
I see:
```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.91.128:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/al/Projects/designer/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
webpack compiled successfully
No issues found.
webpack compiled successfully
No issues found.
```

I would like to get rid of all the "&lt;i&gt;" lines
(and to someday figure out why it compiles twice on startup)
I have the following package versions:
webpack: 5.51.0
webpack-cli: 4.8.0
webpack-dev-server: 4.0.0

**Comment by alexander-akait** [comment]
For logger please use https://webpack.js.org/configuration/other-options/#level

**Comment by alexander-akait** [comment]
If you want to hide unnecessary things, please use `level: "warn"`

**Comment by alexander-akait** [comment]
> I would like to get rid of all the "<i>" lines

Impossible, because it means `info`, you can disable colors or your terminal can't support colors, so we use `<i>` to indicate it is `info` message

**Comment by thealjey** [comment]
@alexander-akait 
wow, thank you so much!
this was bugging me for months :)

**Comment by meduzen** [comment]
> > I would like to get rid of all the "<i>" lines
> 
> Impossible, because it means `info`, you can disable colors or your terminal can't support colors, so we use `<i>` to indicate it is `info` message

It’s the first time I see this “output design” choice, so it bugged me too. I understand the intent, but the message is pretty clear by itself. Not sure it needs an additional flag to indicate it’s informative.
