### ISSUE TITLE
iojs v3.3.0 - segmentation fault when starting up webpack-dev-server

### ISSUE THREAD

**Issue by geekyme** [webpack/webpack-dev-server#253]
see above. 

I ran my app without webpack-dev-server and there was no problem. 

iojs v3.0.0 and below are the only versions that are compatible with webpack-dev-server

**Comment by yodairish** [comment]
Have a same error, I just installed iojs v3.3.0 and now when I try to run webpack-dev-server I always have an error: Segmentation fault: 11
without webpack-dev-server no problems

**Comment by geekyme** [comment]
@sokra any thoughts? With node 4.0 around the corner i don't want webpack-dev-server to be the one holding everyone back.

**Comment by fraserxu** [comment]
+1

**Comment by gdi2290** [comment]
run `npm update` or delete your `node_modules` and install again

**Comment by fraserxu** [comment]
or `npm rebuild`?

**Comment by geekyme** [comment]
npm rebuild works for me. Thanks for the tip!! confirmed on v4.0.0

**Comment by fraserxu** [comment]
:+1:

**Comment by cleechtech** [comment]
+1 for `npm rebuild`

**Comment by FrankFan** [comment]
+1 for  **`npm rebuild`**
