### ISSUE TITLE
How to restart server from watchRun process?

### ISSUE THREAD

**Issue by neberej** [webpack/webpack-dev-server#2534]
I have an application that accepts two parameters. These parameters are passed as arguments in package.json scripts and then to environment variables using dotEnv. My package.json currently has 106 scripts to accommodate all the possible parameters.

What I would like to do is, create one script and maintain an env file. When env is changed, restart the server. 

- Operating System: Mac
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```
compiler.hooks.watchRun.tap('WatchRun', (comp) => {
  const changedTimes = watching.compiler.watchFileSystem.watcher.mtimes;
  const changedFiles = Object.keys(changedTimes)
    .map(file => `\n  ${file}`)
    .join("");
  if (changedFiles.length && path.extname(changedFiles) === '.env) {
    // I want to restart server here ??
  }
});
```

```js
// package.json
"scripts": {
 "dev": "webpack-dev-server --config webpack.config.dev.js"
```

```js
 // webpack.config.dev.js

require('dotenv').config({path: './build/local.env});
const { category, type } = process.env
```

### Expected Behavior

I want to restart server when env files are changed.

### Actual Behavior

I don't see any hooks/APIs to reload server. I am able to tap into file change event but stuck on how to reload server?

**Comment by evilebottnawi** [comment]
You don't need to restart server, just add files to file dependencies, but if you really need this you can do is manually using `listen`/`close`, sorry it is out of scope webpack-dev-server, example - https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L102, feel free to leave feedback
