### ISSUE TITLE
Explicitly setting static routes

### ISSUE THREAD

**Issue by ctindel** [webpack/webpack-dev-server#254]
I'd like to make a change where we allow the user to configure some static routes on top of the express server.  So for example, you might do a 

```
contentBase: 'src/public',
staticRoutes: [ {'route' : '/npm_scripts', 'dir' : __dirname + '/node_modules'}, 
                        {'route' : '/bower_scripts', 'dir' : __dirname + '/bower_components'} ]
```

Would you welcome a pull request for a change like this?  I don't see any other built in way of serving up npm and bower scripts without having contentBase forced to be '.'

**Comment by ctindel** [comment]
I went ahead and added the code for such a change here:

https://github.com/webpack/webpack-dev-server/pull/255/files

**Comment by maiopirata** [comment]
It seams a good idea for me..
I would also appreciate a way to set static path like in express.

**Comment by SpaceK33z** [comment]
Closing, for explanation see the PR #255. TL;DR - setup your own middleware via the Node API, this doesn't belong in webpack-dev-server.
