### ISSUE TITLE
Upgrade "del" dependency

### ISSUE THREAD

**Issue by madeken** [webpack/webpack-dev-server#2541]
https://github.com/webpack/webpack-dev-server/blob/375ab2332706ead66335e8f54391ef37f718e129/package.json#L45

Is a bit out of date, and has a bug in which it ends it ends up dragging in `@types/node@13.9.3` which can be problematic for typescript users.

**Comment by hiroppy** [comment]
This will be fixed by https://github.com/webpack/webpack-dev-server/pull/2542.

**Comment by evilebottnawi** [comment]
Done for `v4`
