### ISSUE TITLE
Self-signed SSL certs not valid on MacOS 10.15.4 if localhost is used (Catalina) 

### ISSUE THREAD

**Issue by marcusschiesser** [webpack/webpack-dev-server#2545]
- Operating System: MacOS 10.15.4 (Catalina) 
- Node Version: v10.17.0
- NPM Version: 6.11.3
- webpack Version: 4.36.1
- webpack-dev-server Version: 3.10.3 
- Browser: Safari 13.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```
...
module.exports = merge(common, {
    mode: 'development',
    devServer: {
        port: 8000,
        https: true,
        http2: false,
        hot: true,
        compress: false,
        watchContentBase: true,
        contentBase: path.join(__dirname, 'public'),
...
```

### Expected Behavior

The autogenerated SSL certificate should be accepted by Safari if URL is requested via `localhost` (https://localhost:8000)

### Actual Behavior

If requested via https://localhost:8000, the certificate is not accepted, only if requested via https://127.0.0.1:8000

### For Bugs; How can we reproduce the behavior?

Start up webpack-dev-server with SSL enabled on a MacOS 10.15.4 system; attempt to hit the server in Safari 13.1 using https://localhost:8000
Related to #2273.

**Comment by evilebottnawi** [comment]
On Safari 13 self-signed SSL certs works?

**Comment by marcusschiesser** [comment]
yes, but for me it was only working accessing https://127.0.0.1:8000 not https://localhost:8000

**Comment by evilebottnawi** [comment]
@marcusschiesser maybe you have a firewall or something same?

**Comment by marcusschiesser** [comment]
@evilebottnawi only standard firewall from macOS, this one:
![image](https://user-images.githubusercontent.com/17126/80941881-1b7fb380-8e16-11ea-9bb1-909da4f2fc6f.png) 

and lookup of localhost is working:
```
~ » nslookup localhost                               
Server:		2401:e180:8844:ce38::2a
Address:	2401:e180:8844:ce38::2a#53

Name:	localhost
Address: 127.0.0.1
```

**Comment by marcusschiesser** [comment]
Update:
With firewall turned off, the same behavior.

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-dev-server/issues/2957, maybe safari has the same `chrome://flags/#allow-insecure-localhost`, it is default behavior for browsers now :disappointed:
