### ISSUE TITLE
yargs-parser vulnerability

### ISSUE THREAD

**Issue by nessor** [webpack/webpack-dev-server#2559]
- Node Version: 12.16.1
- NPM Version: 6.13.4
- OS: Ubuntu 19.10

- [x] This is a **bug**
- [ ] This is a **modification** request

Hey guys,

npm is reporting a Prototype Pollution vulnerability on the yargs-parser dependency

 Low             Prototype Pollution                                                                                                                           
 Package         yargs-parser                                                                                                                                
 Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2                                                                                             
 Dependency of   webpack-dev-server [dev]                                                                                                                      
 Path            webpack-dev-server > yargs > yargs-parser                                                                                                     
 More info       https://npmjs.com/advisories/1500

**Comment by panuhorsmalahti** [comment]
Fix should be to update the `yargs` dependency. It might be enough to update yargs to 13.3.0 (but perhaps the latest version works without code changes to webpack-dev-server-too, haven't looked at the code).

**Comment by gbhasha** [comment]
Snyk Report: https://snyk.io/test/npm/webpack-dev-server
