### ISSUE TITLE
`hot: true` in Node.js API not working

### ISSUE THREAD

**Issue by leecade** [webpack/webpack-dev-server#256]
Follow documents, with `hot: true` not working.

```js
devServer: {
    // not working?
    hot: true,
  }
```

Only works as a plugin, did I miss anything?

```js
plugins: [
    new webpack.HotModuleReplacementPlugin()
  ]
```

**Comment by bencooling** [comment]
I had same issue; I can only get in working from cli:

package.json
```
  "scripts": {
    "dev": "webpack-dev-server --hot"
  },
```

webpack.config.js will get error: Hot Module Replacement is disabled.
```
  devServer: {
    hot: true
  },
```

**Comment by sokra** [comment]
updated documentation
