### ISSUE TITLE
Server.test.js not terminating correctly

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#2560]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

`Server.test.js` exits properly

### Actual Behavior

Always getting `Jest did not exit one second after the test run has completed` when running `Server.test.js`. I will look into this later

### For Bugs; How can we reproduce the behavior?

Run `Server.test.js` alone

**Comment by alexander-akait** [comment]
I think we can close this
