### ISSUE TITLE
Fix clientLogLevel = silent for HMR

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#2561]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

When `clientLogLevel = 'silent'`, HMR messages in the browser console should not be sent

### Actual Behavior

As shown in this test snapshot (https://github.com/webpack/webpack-dev-server/blob/v4/test/e2e/__snapshots__/ClientOptions.test.js.snap#L6) HMR messages are being shown in the console when clientLogLevel is silent

### For Bugs; How can we reproduce the behavior?

SImply set `clientLogLevel = 'silent'` and look at the console

**Comment by evilebottnawi** [comment]
Duplicate if #2166
