### ISSUE TITLE
devServer.stats object does not work with multiple configs

### ISSUE THREAD

**Issue by ryansully** [webpack/webpack-dev-server#2569]
- Operating System: mac OS
- Node Version: 14.1
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.10.3
- Browser: Chrome 81.0.4044.129

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const devServerConfig = require('./webpack.config.devserver.js');
const firstConfig = require('./webpack.config.first.js');
const secondConfig = require('./webpack.config.second.js');

module.exports = function config(env = { development: true }, argv) {
  return [
    {
      // config that exports a function
      ...firstConfig(env, argv),
      devServer: devServerConfig(env, argv),
    },

    // config that exports a function
    secondConfig(env, argv),
  ];
};
```

```js
// webpack.config.devserver.js
function devServerConfig(env, argv) {
  return {
    // rest of config omitted for brevity
    stats: {
      assets: true,
      assetsSort: 'chunks',
      cachedAssets: false,
      children: false,
      chunks: false,
      entrypoints: false,
      hash: false,
      modules: false,
      publicPath: false,
      timings: true,
      version: false,
      warnings: false,
    },
  };
}

module.exports = devServerConfig;
```

### Expected Behavior
Console output should display assets, timings, etc when webpack is finished compiling.

### Actual Behavior
Console output only shows the message, "Compiled successfully."

### For Bugs; How can we reproduce the behavior?
Given two separate configs that export functions and are combined in a [multiple configuration array](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) and a `devServer` config that also exports a function, the error is reproduced. Changing the final config to return only a single config with the `devServer` config attached to it behaves as expected.

Also of note, setting `stats` to one of the preset strings works; the bug only occurs when trying to use a `stats` object value.

I'm aware that "only the `devServer` options for the first configuration will be taken into account and used for all the configurations in the array."

**Comment by evilebottnawi** [comment]
@ryansully Yes, it is not bug, it is a limitation, can you provide full configuration, maybe we can improve it

**Comment by alexander-akait** [comment]
Anyway in near future we will support dev server as plugin so it will be allowed
