### ISSUE TITLE
how to config proxy with same context and different domain

### ISSUE THREAD

**Issue by paul-xiao** [webpack/webpack-dev-server#2575]
- Operating System: linux
- Node Version: 12.13.1
- NPM Version: 6.12.1
- webpack Version: 3.6.0
- webpack-dev-server Version: 2.11.5
- Browser:chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const targetURL1 = 'https://a.example.com/'
const targetURL2 = 'https://b.example.com/'

module.exports = {
  dev: {
    // Paths
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: [
      {
        context: ['/api/users'],
        target:   targetURL1,
        pathRewrite: {
          '^/api': ''
        },
        changeOrigin: true,
        secure: false
      },
   ...
```
### Expected Behavior 
> expect same context(/api/users) from two different target(targetURL1,targetURL2) can be both proxy correctly 

i'm running this at localhost, *targetURL1* can be proxy correctly 
expect request from *targetURL2* also can be proxy to localhost
anyone know how to config this

**Comment by evilebottnawi** [comment]
Please use gitter or stackoverflow for questions, it is bug tracker, thanks
