### ISSUE TITLE
Need a grammar check in README file

### ISSUE THREAD

**Issue by Deeksha2501** [webpack/webpack-dev-server#2596]
There are some missing commas in README file.
Can I work on this issue?

**Comment by snitin315** [comment]
No need to create issues for small docs related changes. You can send a PR directly.

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/issues/10877#issuecomment-627291816

**Comment by snitin315** [comment]
Will be great if you can solve all grammar issues for README in a single PR.
