### ISSUE TITLE
HMR does't work when code clearTimeout(true) in file

### ISSUE THREAD

**Issue by EnjoyChan** [webpack/webpack-dev-server#2610]
- Operating System: mac
- Node Version: v10.15.3
- NPM Version: @6.4.1
- webpack Version: 4.39.1
- webpack-dev-server Version: 3.7.2
- Browser:chrome

- [ x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed
```

### Expected Behavior
I use hmr pllugin and react-hot-loader/babel, whent I code setTimeout(true) , hmr doesn't work,  the console is waiting for wds; but when remove that code , it works, I just wonder why
![image](https://user-images.githubusercontent.com/6998403/82123170-7cba6600-97ca-11ea-8612-c47c6a7a4106.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

We don't modify your code.
