### ISSUE TITLE
yargs-parser in yargs is out of date and has a low vulnerability [Please add to http-proxy fix]

### ISSUE THREAD

**Issue by ahmed-gl** [webpack/webpack-dev-server#2611]
- webpack-dev-server Version: 3.11.0
Hi, Aside from the DoS issue with http-proxy one other issue, is a low priority that requires 'yargs' top be updated to the latest version. 

                       === npm audit security report ===                        

                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           

  High            Denial of Service                                             

  Package         http-proxy                                                    

  Patched in      No patch available                                            

  Dependency of   react-scripts                                                 

  Path            react-scripts > webpack-dev-server > http-proxy-middleware >  
                  http-proxy                                                    

  More info       https://nodesecurity.io/advisories/1486                       

  High            Denial of Service                                             

  Package         http-proxy                                                    

  Patched in      No patch available                                            

  Dependency of   webpack-dev-server                                            
  Path            webpack-dev-server > http-proxy-middleware > http-proxy       

  More info       https://nodesecurity.io/advisories/1486                       

  Low             Prototype Pollution                                           

  Package         yargs-parser                                                  

  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2              

  Dependency of   react-scripts                                                 

  Path            react-scripts > webpack-dev-server > yargs > yargs-parser     

  More info       https://nodesecurity.io/advisories/1500

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
