### ISSUE TITLE
yargs-parser in yargs is out of date and has a low vulnerability

### ISSUE THREAD

**Issue by ahmed-gl** [webpack/webpack-dev-server#2612]
- Operating System: Windows 10
- Node Version: v12.14.1
- NPM Version: 6.1.0
- webpack Version:
- webpack-dev-server Version: 3.11.0
- Browser:

- [ ] This is a **bug**
- [x ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
Yargs should use the latest version without the security flaw Patched in >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2

### Actual Behavior
Yargs uses version 18.1.1

### For Bugs; How can we reproduce the behavior?
npm audit

**Comment by evilebottnawi** [comment]
Looks you do not use latest version, update your version, we already fixed it https://github.com/webpack/webpack-dev-server/blob/master/package.json#L71

**Comment by ahmed-gl** [comment]
thanks!
