### ISSUE TITLE
Please upgrade your version of Chokidar

### ISSUE THREAD

**Issue by davidnewcomb** [webpack/webpack-dev-server#2621]
Please can you upgrade your `chokidar` dependency. You are currently using 2.1.8 (which is also in the lock file) but the latest version 3.4.0. Projects upstream of you are starting to get warnings.
Also the little note about Chokidar breaking soon and having 15 times less dependencies should be reason enough!

```
warning react-scripts > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning react-scripts > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-scripts > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

**Comment by evilebottnawi** [comment]
Done for `v4`

**Comment by shprink** [comment]
I fixed it by downgrading Node to v12.

I don't think there is another way until webpack-dev-server upgrades Chokidar

**Comment by tatsujb** [comment]
> Done for `v4`

this is absurd.

why would you close this issue? 

3.11 is your latest release this is still very much an issue and very much unresolved.

either release 4 or fix in 3.

this makes Angular projects unbuildable for a whole slew of platforms : Mac OSX catalina, CentOS 8, Fedora 32 and to the best of my knowledge a bunch of other linux distributions in their latest offerings.

how could you leave this as-is four four months?

**Comment by capono** [comment]
As a workaround you could add to the package.json  

```
"resolutions": {
    "webpack-dev-server/chokidar": "^3"
  }
```
This lets you use custom package version in your dependencies.
