### ISSUE TITLE
webpack-dev-server, host argument and ifdef loader

### ISSUE THREAD

**Issue by TanukiSharp** [webpack/webpack-dev-server#2623]
- Operating System: Ubuntu 18.04.4 LTS (via WSL 1 on Windows 10)
- Node Version: 12.16
- NPM Version: 6.13.4
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.11.0
- Browser: Edge 81.0.416.77

- [x] This is a **bug** (I think?)
- [ ] This is a **modification** request

### Code

Here is a stripped-down, bare-bones, easy to get ready, repository to reproduce the problem, with an exhaustive README explaining all things: https://github.com/TanukiSharp/webpack-dev-server-host-ifdef-loader

### Expected Behavior

The same when `--host 0.0.0.0` is provided or not, meaning to get the `ifdef-loader` to work in both cases.

### Actual Behavior

The `ifdef-loader` works only when `--host 0.0.0.0` is not provided, otherwise it seems to be ignored.

### For Bugs; How can we reproduce the behavior?

Run once with `npm start success` to see the working case, and once with `npm start failure` to witness the problematic case.

It's all in the README anyway.

Thanks for your help.

---

Note: I followed the guidelines and posted on Stackoverflow first (https://stackoverflow.com/questions/61832809/how-to-get-webpack-dev-server-working-with-host-argument-and-ifdef-loader) then I asked on Gitter (https://gitter.im/webpack/webpack on May 19th at 17:07 JST) and so far no sign of activity, therefore me posting here now.

**Comment by evilebottnawi** [comment]
Problem on `ifdef-loader` side, not related to webpack-dev-server, using regexp is not safe for parsing https://github.com/nippur72/ifdef-loader/blob/master/preprocessor.ts#L115

**Comment by TanukiSharp** [comment]
Thanks for the pointer :) and sorry for the noise.

**Comment by TanukiSharp** [comment]
I have a few questions:

1. Running `npm test` produces strange output. In the `test` script of `package.json`, did you mean `&&` instead a single `&` to chain commands ?

2. The regular expression to match `#if` and `#elif` has `[\s\S]+`, which means "match any whitespace character or non-whitespace character at least once". Is that what you meant ? Currently the expression matches something like `/// #iflol`. By `\S` did you intent to match Unicode whitespace characters ?

Thanks.

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions

**Comment by TanukiSharp** [comment]
Sorry, wrong repo...
