### ISSUE TITLE
Server Errors are Swallowed Causing Process to Hang When Server Did Not Start

### ISSUE THREAD

**Issue by emilyrohrbough** [webpack/webpack-dev-server#2624]
- Operating System:
- Node Version: `v10.18.0`
- NPM Version: `v6.13.4`
- webpack Version: `webpack@4.43.0`
- webpack-dev-server Version: `webpack-dev-server@3.11.0`
- Browser: n/a

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
When specifying the serve port and the port is busy, throw an error to kill the server.

### Actual Behavior
When specifying the serve port and the port is busy, [the error is logged and being swallowed here](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L691-L693). What happens is webpack continues to compile and the process end hangs since server did not start.

```bash
➜  node node_modules/.bin/webpack-dev-server --port 8080

✖ ｢wds｣:  { Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }
ℹ ｢wdm｣: Hash: 2d6b4cca7cb2ac0c26d9
Version: webpack 4.43.0
Time: 1127ms
Built at: 05/21/2020 10:46:25 AM
....
ℹ ｢wdm｣: Compiled successfully.
^[[A^C^C%   q qq
```

### For Bugs; How can we reproduce the behavior?
Steps to reproduce:
1. start server on port 8080 
```sh
> node node_modules/.bin/webpack-dev-server --port 8080
```
2. start  another server on port 8080 defining the port with the `--port` flag
```sh
> node node_modules/.bin/webpack-dev-server --port 8080
```

What happens when running in both the standalone and via the CLI.

### Proposed Solution
Update the server to throw the error when an error occurs instead of just logging it:

```diff
    this.listeningApp.on('error', (err) => {
      this.log.error(err);
+     throw err
    });
```

**Comment by alexander-akait** [comment]
Fixed
