### ISSUE TITLE
writeToDisk doesn't work with multiple targets

### ISSUE THREAD

**Issue by Timmmm** [webpack/webpack-dev-server#2626]
webpack version: 4.43.0
webpack-cli version: 3.3.11
webpack-dev-server version: 3.11.0
Node.js version: 14.0.0
Operating System: MacOS 10.14.6

- [x] This is a **bug**

If you have a `webpack.config.js` that exports multiple targets, e.g:

```
module.exports = [rendererConfig, mainConfig];
```

And you set this in one of them:

```
  devServer: {
    writeToDisk: true,
  },
```

Then no files are written to disk - the behaviour is identical to not setting it. If you add that setting to *both targets* then it correctly writes everything out to disk. But I would have expected that you can set that option in different targets separately.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Timmmm** [comment]
I don't think I missed any information, but sure: #2627
