### ISSUE TITLE
No work proxy

### ISSUE THREAD

**Issue by higimo** [webpack/webpack-dev-server#2629]
- Operating System: Windows 10
- Node Version: v10.16.2
- NPM Version: 6.4.0
- webpack Version: ^4.43.0
- webpack-dev-server Version: ^3.11.0
- Browser: chrome 83

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
module.exports = {
	devServer: {
		open               : true,
		contentBase        : path.join(__dirname, '../www/'),
		compress           : true,
		port               : 8000,
		historyApiFallback : true,
		proxy: {
			'/api': {
				target: 'https://mydomain.ru:80',
				pathRewrite: {
					'^/api' : '/api'
				},
				secure: false,
				changeOrigin: true,
			},
		},
	},
}
```

```js
fetch('/api/v1/?action=do') // 500 error
```

### Actual Behavior
open `http://localhost:8000/api/v1/index.php?job/getList` in new tab:
```
Error occured while trying to proxy to: localhost:8000/api/v1/index.php?action=do
```

only fix `target: 'https://mydomain.ru:80',` to `target: 'https://mydomain.ru',` fixed this bug. Not okay.

**Comment by evilebottnawi** [comment]
You can't use `https` on `80` port, it is expected and limitation from https://github.com/chimurai/http-proxy-middleware
