### ISSUE TITLE
No way to force webpack-dev-server client to use window.location

### ISSUE THREAD

**Issue by wbobeirne** [webpack/webpack-dev-server#2632]
- Operating System: macOS 10.15.3
- Node Version: v12.16.0
- NPM Version: 6.13.4
- webpack Version: 4.41.6
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 81

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

There would be some configuration that would let me force webpack-dev-server's hot client to use `window.location`.

### Actual Behavior

No configuration will cause webpack-dev-server's hot client to not use `__resourceQuery`, which in my case is always `"?http://localhost:8080"`. As far as I can tell, I can't get this behavior with the current configuration options.

### For Features; What is the motivation and/or use-case for the feature?

I'm working on a cloud platform that provides dev environments, and it let's you proxy requests to localhost via a domain. Out of the box, webpack-dev-server doesn't work since it tries to hit `localhost:8080/sockjs-node`. We've been working around this by setting `public` to an environment variable, but the annoying thing is that everyone gets a different domain. It'd be ideal if we could just set a flag on the `devServer` config that told it to always use `window.location` so each user wouldn't have to configure an environment variable.

It's worth noting that create-react-app doesn't encounter this because of their custom hot client, which has much simpler logic: https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/webpackHotDevClient.js#L59-L69

**Comment by evilebottnawi** [comment]
@wbobeirne we have `sockPath`, `sockPort` and `sockHost` option, why do not use them?

**Comment by wbobeirne** [comment]
Yes, it's because these aren't static values. Developers can access the project from randomly generated domains, so it can't be configured in the webpack config. Somewhat similar to https://ngrok.com/.

**Comment by evilebottnawi** [comment]
@wbobeirne So that I definitely don’t lose anything when fixing, can you do minimum reproducible test repo and describe in readme what you have and what you want to change

**Comment by lperiodbose** [comment]
For folks Googling their way here looking for answers, [this hack proposed a few years ago](https://github.com/webpack/webpack-dev-server/issues/1240#issuecomment-442640889) still works (from #1240):

    devServer: {
      public: '0.0.0.0:0',
      host: '0.0.0.0',
      disableHostCheck: true
    },

...to get the client to fallback to `window.location`.

**Comment by evilebottnawi** [comment]
@lperiodbose thanks, let's close in favor https://github.com/webpack/webpack-dev-server/issues/1240, try to find time on it for v4
