### ISSUE TITLE
Async chunk loading fails when `devServer.publicPath` is not respected

### ISSUE THREAD

**Issue by vvanpo** [webpack/webpack-dev-server#2634]
- Operating System: macOS 10.15.5
- Node Version: 10.21.0
- NPM Version: 6.14.4
- webpack Version: 4.41.6
- webpack-dev-server Version: 3.10.3
- Browser: Chrome 83.0.4103.61

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
export default {
  ...
  devServer: {
    host: '0.0.0.0',
    https: true,
    port: 8080,
    public: 'https://localhost:8080',
    publicPath: 'https://localhost:8080/dist/',
  },
  ...
  output: {
    publicPath: '/dist/',
  },
  ...
}
```

### Expected Behavior

When loading chunks asynchronously, the `devServer.publicPath` configuration should override the `output.publicPath` configuration for resolving the chunk address.

### Actual Behavior

```
ChunkLoadError: Loading chunk 2 failed.
(error: https://my-app.local/dist/2.js)
    at Function.requireEnsure [as e] (https://localhost:8080/dist/runtime.js:832:26)
```

As you can see, `__webpack_require__` attempts to load the chunk via `output.publicPath`'s relative path, rather than the absolute URL provided by `devServer.publicPath`. Because the server is running at `https://localhost:8080`, and not at `https://my-app.local`, the relative path resolves to an invalid address.

### For Bugs; How can we reproduce the behavior?

Configure `webpack-dev-server` to run on `localhost` as in the configuration above.
Build an application that runs on a different port or at a different address, so that it has to include the Webpack assets via absolutes URLs, i.e. `<script src="https://localhost:8080/dist/runtime.js">....`.
Import at least one asset asynchronously.
Attempt to load the application, and notice console errors with `ChunkLoadError` and a broken page.

**Comment by vvanpo** [comment]
I can of course mitigate the issue by setting `output.publicPath` to `https://localhost:8080/dist/`. However, that would break all static builds. So I would have to generate the Webpack configuration dynamically based on whether I intend to run `webpack-dev-server` or not, which is not ideal.

**Comment by vvanpo** [comment]
Interestingly, using the command line option `--output-public-path` _does_ correctly override `output.publicPath`, so this is another workaround.

**Comment by vvanpo** [comment]
From what I can tell, the `devServer.publicPath` doesn't actually do anything. If it's not set the config object will be altered to set it equal to `output.publicPath` (https://github.com/webpack/webpack-dev-server/blob/v3.11.0/lib/utils/createConfig.js#L64), which actually conflicts with the documentation (https://v4.webpack.js.org/configuration/dev-server/#devserverpublicpath-) which claims it always defaults to `/`, but nowhere does the config's `output.publicPath` get modified before it's passed to the middleware.

**Comment by vvanpo** [comment]
Hmm I see now that the options object (which starts off as the `devServer` config) is passed to the middleware, which actually requires a `publicPath` option (hence grabbing the default from `output.publicPath`).

But the whole thing feels confused to me. Why would you want to serve your bundles from a path that your application doesn't recognize? Everywhere `publicPath` is discussed in `webpack-dev-server` and `webpack-dev-middleware` documentation is an explicit warning to always keep it equal to `output.publicPath`. Does it not make sense to then use `devServer.publicPath` to populate `output.publicPath` as passed to the compiler?

**Comment by alexander-akait** [comment]
Not related to `webpack-dev-server` or `webpack-dev-middleware`, please use `webpack@5` and `publicPath: 'auto'`

**Comment by alexander-akait** [comment]
Fixed in https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0
