### ISSUE TITLE
Get Error when dockerize React js Application

### ISSUE THREAD

**Issue by deepikavijay528** [webpack/webpack-dev-server#2638]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
