### ISSUE TITLE
No color in console when using `devServer.stats` option

### ISSUE THREAD

**Issue by SatoAV** [webpack/webpack-dev-server#2641]
- Operating System: Ubuntu (Windows Linux Subsystem)
- Node Version: 12.17.0
- NPM Version: 6.14.4
- webpack Version: 4.41.17
- webpack-dev-server Version: 3.11.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
{
  devServer: {
    stats: 'minimal',
  }
}
```

### Expected Behavior
When running `webpack-dev-server`, console messages are coloured (I assume `colors` option is now enabled by default, as I didn't state it anywhere in config or CLI options):
![image](https://user-images.githubusercontent.com/1641218/84057749-cad51a80-a9c0-11ea-901e-734db1b70bca.png)

### Actual Behavior
If I define `devServer.stats` value, my console output is no longer coloured, although the `wds` prefix still has colors:
![image](https://user-images.githubusercontent.com/1641218/84057795-dfb1ae00-a9c0-11ea-8d30-66a68b36e79d.png)

### How can we reproduce the behavior?
I'm not sure if this is system- or shell-specific issue. The screens are from VS Code bash terminal from Ubuntu running in WSL (Windows 10).
I tried launching both from VS Code (which I'm using most of the time), and from standalone terminal (Windows Terminal 1.0.1401.0)

**Comment by evilebottnawi** [comment]
Yep, but, fixed for v4

**Comment by SatoAV** [comment]
> Yep, bug, fixed for v4

Can I just install v4 webpack-server on my current setup, or is it a breaking-change upgrade?

**Comment by evilebottnawi** [comment]
It is still WIP :disappointed: and yes it is a breaking change upgrade

**Comment by SatoAV** [comment]
> It is still WIP 😞 and yes it is a breaking change upgrade

OK, will look forward for a release! :)

**Comment by alexander-akait** [comment]
Fixed for webpack-cli v4 and `webpack serve` (please migrate on it and don't use `webpack-dev-server` to run webpack-dev-server, it is deprecated)
