### ISSUE TITLE
Node.js 14 compatibility warning related to outdated chokidar and fsevents

### ISSUE THREAD

**Issue by nstuyvesant** [webpack/webpack-dev-server#2642]
- Operating System: macOS 10.15.5
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.11.0
- Browser: Safari 13.1.1

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

fast-form@1.0.0 /Users/nates/dev/fast-form
├─┬ @vue/cli-service@4.4.1
│ └─┬ webpack-dev-server@3.11.0
│   └─┬ chokidar@2.1.8
│     └── fsevents@1.2.13 

### Expected Behavior
npm install webpack-dev-server --saveDev
no warnings

### Actual Behavior
npm install webpack-dev-server --saveDev
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

### For Bugs; How can we reproduce the behavior?
npm install webpack-dev-server --saveDev

### For Features; What is the motivation and/or use-case for the feature?
Confidence using webpack-dev-server with Node.js 14.
chokidar@3.4.0 uses fsevents@2.1.3 and avoids this problem.

**Comment by evilebottnawi** [comment]
Fixed for v4, not release yet

**Comment by xiaoxiangmoe** [comment]
When will v4 release? @evilebottnawi

**Comment by frankstepanski** [comment]
Is there an update?

**Comment by KevinTCoughlin** [comment]
Is there an ETA now that Node 14 is LTS?

**Comment by AlmirKadric** [comment]
@nstuyvesant poke regarding this, what is the current ETA for version 4?
