### ISSUE TITLE
strip-ansi compatibility problem and general compatibility for old browsers

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-dev-server#2649]
- [x] This is a **bug**
- [ ] This is a **modification** request

The issue is with the latest version of `strip-ansi` (6.0.0). It uses syntax that is not compatible with the oldest browsers, like `const`, which is reflected in the user's bundle (`localhost:8080/main.js`):

![strip-ansi-problem](https://user-images.githubusercontent.com/22580625/84986438-2e1f2500-b104-11ea-9d11-b52ab15225bd.png)

Latest version of webpack-dev-server is fine, because it uses `strip-ansi@3.0.1`.

To reproduce, simply use any config like https://github.com/Loonride/babel-repro , then navigate to `localhost:8080/main.js` after starting. You will not see `const` being used in the bundle with latest released webpack-dev-server version, but you will see it if you npm link the `v4` webpack-dev-server branch.

Usage of `strip-ansi` in the client is here: https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/client-src/default/index.js#L5

This is an issue we need to prevent, correct? If so, we generally need a better strategy so that we don't have to trust dependencies like `strip-ansi` to be compatible with old browsers.

### For Bugs; How can we reproduce the behavior?

Reproducing is explained above

**Comment by alexander-akait** [comment]
Let's close, fixed, but we still uses not bundled version in some cases, but we have issue for this
