### ISSUE TITLE
Make Overlay Dismissible

### ISSUE THREAD

**Issue by dleavitt** [webpack/webpack-dev-server#2650]
- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Right now the iframe that gets popped up by overlay.js (when `devServer.overlay` is set) seems to block all interaction and lacks any sort of close button.

There are a variety of scenarios where you might want to soldier on and see the page under it (eslint errors, typescript typecheck errors, webpack warnings, etc.)

Current workarounds are:
- Set `overlay` to false so it's disabled entirely :(
- Use MutationObserver or similar to stick a close button in front of it when it pops up. Fragile + gross.

Appears easy to add - `overlay.js` already exports a `clear` function for the purpose (just can't get at it easily from client code.) Happy to submit a PR if others agree.

**Comment by evilebottnawi** [comment]
`iframe` was removed in the `v4`, so no need to fix
