### ISSUE TITLE
Forcing output.path to "/" breaks sass sourceMaps

### ISSUE THREAD

**Issue by shanear** [webpack/webpack-dev-server#266]
Is there a reason why the `output.path` option is forced to `/`?

The source maps generated by sass-loaders depend on the value of this option to generate source paths. The generation of these source paths fail due to the `output.path` being incorrect.

I've tracked back to this commit, but can't figure out why it was changed.
https://github.com/webpack/webpack-dev-server/commit/a8b62428c2ea0d98bed32e7d2a1a1ecb34fcbb4a

see this issue for more info:
https://github.com/bholloway/resolve-url-loader/issues/3

**Comment by bholloway** [comment]
+1

**Comment by SpaceK33z** [comment]
Closing this in favor of #337.
