### ISSUE TITLE
Hot Module Replacement/HMR doesn't trigger reload in wsl2

### ISSUE THREAD

**Issue by gjj** [webpack/webpack-dev-server#2661]
- Operating System: Ubuntu 18.04 LTS (WSL2) within Windows 10 version 2004 
- Node Version: v12.18.1
- NPM Version: 6.14.5
- webpack Version: 4.42.0
- webpack-dev-server Version: 3.10.3
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
I used `create-react-app` and I haven't ejected it, so all webpack settings are pre-configured by CRA.

### Expected Behavior
Hot Module Replacement should trigger a reload when editing files that are watched.

### Actual Behavior
HMR does not trigger a reload to reflect the updated changes.

### For Bugs; How can we reproduce the behavior?
1. Install wsl2
2. Launch a new app using `create-react-app` (see https://create-react-app.dev/docs/getting-started)
3. Run `npm start`
4. Go to `src/App.tsx` add some characters then save
5. Notice that in the console, the console message does not update i.e. I didn't see "Compiling..."
6. Go to Chrome, the changes are not reflected at all

I tested this on my desktop with wsl2 and laptop with wsl1. In wsl1, HMR works which was why I figured the problem might be with wsl2. I downgraded my desktop's wsl2 back to wsl1 and HMR works.

Summary:

- Ubuntu 18.04 LTS (WSL1) within Windows 10 version 2004: HMR works
- Ubuntu 18.04 LTS (WSL**2**) within Windows 10 version 2004: HMR **does not trigger a reload**
- Ubuntu 18.04 LTS (WSL1) within Windows 10 version 1909: HMR works

**Comment by gjj** [comment]
Ok after a bit of Googling, found out that it's really because of wsl2 (see https://github.com/microsoft/WSL/issues/4417) and not WDS.

So I'm not sure what to do with this issue now, I guess I could leave this here in case anyone else faces the same issue.

**Comment by evilebottnawi** [comment]
@gjj You can send a PR to docs, we don't want to keep opened specific problems when we can't fix it

**Comment by gjj** [comment]
Sure!

**Comment by philippeaellig** [comment]
https://github.com/microsoft/WSL/issues/4417#issuecomment-657799528
