### ISSUE TITLE
HMR broken w/ configured port

### ISSUE THREAD

**Issue by caseyWebb** [webpack/webpack-dev-server#2662]
- Operating System: Arch Linux
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.11.0
- Browser: Firefox 77.0b3

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/caseyWebb/webpack-dev-server-hmr-repro

### Expected Behavior

HMR should work when port is configured

### Actual Behavior

Configuring a port breaks HMR

### For Bugs; How can we reproduce the behavior?

See repo. Comment/uncomment devServer.port in webpack.config.js.

---

Pretty sure this is a duplicate; I found several 1+ year old issues that sound the same and comments asking for a minimal repo to repro. Well, here is a repo.

**Comment by alexander-akait** [comment]
Sorry for big delay, works fine on v4 and v5, your code doesn't have HMR code so webpack just reload the page, you need write HMR code if you need refresh without reloading, please read https://webpack.js.org/concepts/hot-module-replacement/, feel free to open an issue in docs repo if something misleading
