### ISSUE TITLE
Global window libraryTarget does not work with webpack 5

### ISSUE THREAD

**Issue by hmnd** [webpack/webpack-dev-server#2663]
- Operating System: Solus
- Node Version: 12.18.0
- NPM Version: 6.14.5
- webpack Version: 5.0.0-beta.18
- webpack-dev-server Version: 3.11.0
- Browser: Firefox Developer Edition 78.0b9

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
function genConfig(target, name) {
  const config = {
    mode: 'production',
    entry: combinedPaths,
    output: {
      path: buildPath,
      filename: `[name]${
        !target || target === 'window' ? '' : `.${target}`
      }.min.js`,
      libraryTarget: target,
    },
    externals: {
      _: '_',
    },
    module: {
      rules: [
        ...
      ],
    },
    plugins: [
      ...
    ],
    resolve: {
      alias: {
        vue$: 'vue/dist/vue.esm.js',
        '@': path.resolve(__dirname, 'src'),
        path: 'path-browserify',
        stream: 'stream-browserify',
      },
      extensions: ['.ts', '.js', '.vue'],
    },
    optimization: {
      ...
    },
    devServer: {
      host: 'localhost',
      port: 8080,
      https: true,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods':
          'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        'Access-Control-Allow-Headers':
          'X-Requested-With, content-type, Authorization',
      },
      disableHostCheck: true,
      compress: true,
    },
  };
  if (name) {
    config.output.library = name;
  }
  return config;
}

module.exports = [genConfig('window'), genConfig('umd', 'MyLibrary')];
```

### Expected Behavior
Functions are assigned to the `window` object when using dev-server.

### Actual Behavior
Functions are not assigned to the `window` object.

### For Bugs; How can we reproduce the behavior?
Set `libraryTarget` to `window` with no `library` name specified.

**Comment by evilebottnawi** [comment]
What is the problem? We bundle the client before include it. Yes, it is not respect `libraryTarget` and should not

**Comment by hmnd** [comment]
@evilebottnawi maybe I'm misunderstanding something, but as far as I can tell, it did work with webpack 4. I develop a library that is embedded in a third-party platform using a script tag. I provide a version of this library exported as a global to `window` to retain backwards compatibility for some of my clients, and I would like those functions to continue to work while I develop them.

**Comment by evilebottnawi** [comment]
@hmnd how it is related to webpack-dev-server? We don't modify `libraryTarget`, without webpack-dev-server all works fine?

**Comment by zhangwilling** [comment]
But actually it happened . it is very stranrgely, i found when `hot` is enabled, outout.libraryTarget would not works，an empty object will be exported no matter which libraryTarget is setted.

it may caused by webpack5 see [here ](https://github.com/webpack/changelog-v5#hot-module-replacement)

i would do some research to find the answer.

**Comment by zhangwilling** [comment]
aha, look this [issue](https://github.com/webpack/webpack-dev-server/issues/2484)

**Comment by evilebottnawi** [comment]
Yep, duplicate, let's close in favor https://github.com/webpack/webpack-dev-server/issues/2484
