### ISSUE TITLE
\my-app>npm audit                         === npm audit security report ===                                    Manual Review              Some vulnerabilities require your attention to resolve            Visit https://go.npm.me/audit-guide for additional guidance     Low             Prototype Pollution    Package         yargs-parser    Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2    Dependency of   react-scripts    Path            react-scripts > webpack-dev-server > yargs > yargs-parser    More info       https://npmjs.com/advisories/1500  found 1 low severity vulnerability in 1634 scanned packages   1 vulnerability requires manual review. See the full report for details.

### ISSUE THREAD

**Issue by nidhigupta09** [webpack/webpack-dev-server#2664]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by RejithReghunathan** [comment]
=== npm audit security report ===                        
                                                                                
                                                                                
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  Low             Prototype Pollution                                           
                                                                                
  Package         yargs-parser                                                  
                                                                                
  Patched in      >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2              
                                                                                
  Dependency of   react-scripts                                                 
                                                                                
  Path            react-scripts > webpack-dev-server > yargs > yargs-parser     
                                                                                
  More info       https://npmjs.com/advisories/1500                             
                                                                                
found 1 low severity vulnerability in 1628 scanned packages
  1 vulnerability requires manual review. See the full report for details.

How to fix this bug, Someone help
