### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by glekner** [webpack/webpack-dev-server#2668]
- Operating System: WSL Fedora 31
- Node Version: 12.16.1
- NPM Version: 6.13.4
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.11.0
- Browser: Chromium Edge 83

- [x] This is a **bug**

After changing `transportMode` to `ws` im getting the following error in the console:

`WebSocket connection to 'ws://localhost:9000/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200`

My app is using a bridge, webpack-dev-server is on port `8080` and is only meant for compiling and hot-reloading.
I'm accessing the app from port `9000`, where we have a bridge that uses the compiled assets with the help of `writeToDisk`.
Why am I getting this console error? isn't changing to `transportMode` to `ws` disable the usage of `sockjs-node`?
the app and websockets runs fine even though i'm getting it.

### Code

```js
  devServer: {
    writeToDisk: true,
    progress: true,
    hot: true,
    inline: true,
    contentBase: false,
    transportMode: 'ws',
  },
```

### Expected Behavior
No error should show.

### Actual Behavior
`WebSocket connection to 'ws://localhost:9000/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200`

### For Bugs; How can we reproduce the behavior?
PR That causes this issue: https://github.com/openshift/console/pull/5840

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, link on the issue it is not reproducible test repo, I will reopen issue when you fill out `For Bugs; How can we reproduce the behavior?`
