### ISSUE TITLE
Update chokidar to new major version (version 3)

### ISSUE THREAD

**Issue by Roseidon** [webpack/webpack-dev-server#2683]
- Operating System: Ubuntu
- Node Version: 14.5
- NPM Version: 6.14.5
- webpack Version: 4.42.0 (through @angular-devkit/build-angular@0.901.12)
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

When running npm install on a node 14.5 environment following deprecation warning appears:
```bash
npm WARN deprecated chokidar@2.0.4: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
```

### For Features; What is the motivation and/or use-case for the feature?
The motivation to upgrade this package is chokidar saying to have 15x less dependencies in version 3 compared to version 2. And also that node 14 would be supported

**Comment by evilebottnawi** [comment]
Done for v4

**Comment by hxykjc** [comment]
hello,  actually there is a bug in chokidar 2.x，exactly in fsevents
crash when watch one file several times

https://github.com/webpack/webpack/issues/10037

**Comment by jasonwilliams** [comment]
@evilebottnawi when is v4 going to be a thing?

**Comment by evilebottnawi** [comment]
@jasonwilliams hope we will end work on the next week, there are 3 PRs left
