### ISSUE TITLE
Denial Of Service (DoS): http-proxy 1.17.1 comming from http-proxy-middleware 0.19.1 

### ISSUE THREAD

**Issue by guyhanael** [webpack/webpack-dev-server#2687]
Denial Of Service (DoS): http-proxy 1.17.1 coming from http-proxy-middleware 0.19.1 
Need to update to the latest http-proxy-middleware  1.0.5 as http-proxy 1.18.1 is good.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Fixed for v4, just regenerate your lock file
