### ISSUE TITLE
HMR broken with module federation

### ISSUE THREAD

**Issue by codepunkt** [webpack/webpack-dev-server#2688]
After having a video call with @ScriptedAlchemy yesterday evening, he asked me to open an issue for HMR being broken with module federation.

- Operating System: Windows 10
- Node Version: 12.16.2
- NPM Version: 6.14.4
- webpack Version: 5.0.0-beta.22
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 84.0.4147.105, Firefox 79.0, Edge 84.0.522.48

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/codepunkt/react-microfrontend-eval

### Expected Behavior

Changes in a react component will show in the browser without a refresh.

### Actual Behavior

Changes in a react component will **not** show in the browser without a refresh.

### For Bugs; How can we reproduce the behavior?

1. clone repository
2. checkout commit `b53e2a249226d96525b96213db7f1b6e43309e8b`
2. run `yarn` on project root
3. go into `federation` directory
4. run `yarn start` in `federation` directory
5. open `localhost:3001` in the browser
6. open `federation/remote-a/src/components/Content/Content.tsx` in an editor of choice, make changes to the react component in this file and save
7. browser will not show changes and throw 2 errors like these:
    - jsonp chunk loading:86 Uncaught TypeError: Cannot read property 'push' of undefined
    at window.webpackHotUpdate_federation_remote_a (jsonp chunk loading:86)
    at main.6fa816d24a2d1d5749e3.hot-update.js:1
    - Uncaught TypeError: Cannot set property './src/components/Content/Content.tsx' of undefined
    at window.webpackHotUpdate_federation_remote_a (jsonp chunk loading:82)
    at src_bootstrap_tsx-webpack_sharing_consume_default_react_react.6fa816d24a2d1d5749e3.hot-update.js:1

### Related
Issue at `webpack`: https://github.com/webpack/webpack/issues/11240

**Comment by evilebottnawi** [comment]
Do not duplicate issues

**Comment by codepunkt** [comment]
@evilebottnawi that advice is stupid - i'm not duplicating the issue for no reason.

The problem lies in the intersection of webpack-dev-servers hot module reloading feature and webpack v5 module federation feature. It might very well lead to fixes/changes in both of them - and if it leads to changes in `webpack-dev-server`, this is the issue for it.

Is there a hidden rule that i'm not aware of? Like "create all issues that deal with the intersection of webpack and webpack-dev-server in the `webpack` project"?

**Comment by evilebottnawi** [comment]
Keep it in webpack projects, when we fix it on webpack side we will open an issue or PR here without work on webpack side we can't do something here
