### ISSUE TITLE
HRM broken with historyApiFallback and disableDotRule

### ISSUE THREAD

**Issue by pdelacroix** [webpack/webpack-dev-server#2689]
- Operating System: Arch Linux
- Node Version: 14.6.0
- NPM Version: 6.14.7
- webpack Version: 4.41.2
- webpack-dev-server Version: 3.11.0
- Browser: Firefox 78.0.2

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
    devServer: {
        contentBase: 		'./dist',
        disableHostCheck: 	true,
        host: 			'0.0.0.0',
        hot: 			true,
        liveReload: 		false,
        port: 			9000,
        publicPath: 		'/dist/',
        historyApiFallback: {
            disableDotRule: 	true
        },
        writeToDisk: 		true
    }
```

### Expected Behavior

Fetching the file `dist*.hot-update.json` gets the right JSON file. Modules are reloaded.

### Actual Behavior

WDS returns the `index.html` file instead of the correct JSON file (which exists on disk). `JSON.parse()` fails.

### For Bugs; How can we reproduce the behavior?

Configure WDS with `hot: true` and `historyApiFallback: { disableDotRule: true }`. Modify and save some source file. See the network request response.

**Comment by evilebottnawi** [comment]
You have invalid `publicPath`, without reproducible test repo I can't help, when you get `index.html`, it is mean you setup invalid `publicPath`, also I can't reproduce, please provide full reproducible test repo and I will reopen the issue
