### ISSUE TITLE
Cannot install Webpack dependency : webpack-dev-server

### ISSUE THREAD

**Issue by mshahzebraza97** [webpack/webpack-dev-server#2698]
- Operating System: Win 10 64-bit
- Node Version: v12.18
- NPM Version: v6.14.4
- webpack Version: v4.44.1
- webpack-dev-server Version:
- Browser: Google Chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code
`
`

```js
// I Use this command
npm install web-dev-server --save-dev
```

```js
// The error I get
$ npm install webpack-dev-server --save-dev
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):sevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code EINTEGRITY
npm ERR! sha512-SEYeGAIQIQX8NN6LDKprLjbrd5dARM5EXsd8GI/A5l0apYI1fGMWgPHSe4ZKL4eozlAyI+doUE9XbYS4xCkQ1w== integrity checksum failed when using sha512: wanted sha512-SEYeGAIQIQX8NN6LDKprLjbrd5dARM5EXsd8GI/A5l0apYI1fGMWgPHSe4ZKL4eozlAyI+doUE9XbYS4xCkQ1w== but got sha512-8S461SR/c4q+s1MSXpEMKKLsyotxW5HJysB6RranBYdBVKNDHi1vuOh5otKg8TjtDxIr1rXRZNwA6EQjvLJ96g==. (2017 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shahzeb Raza\AppData\Roaming\npm-cache\_logs\2020-08-09T08_42_23_136Z-debug.log

```

### Expected Behavior
Should install the webpack-dev-server as a development dependency

### Actual Behavior
producing strange errors

### Edit 1: I can now install it after cleaning cache
`npm cache clean --force`
i found above mentioned command somewhere on the internet and this solves the problem. However, i have some doubts with this. First all there is a message "I hope you know what you're doing" when i try to execute the command. Also, I had to face a similar problem of installing a web dependency earlier and i used the same hack to solve that too. So i would like to know if this is something bad and also why do i have to use this hack. My course instructor is doing fine without using anything like this.

**Comment by evilebottnawi** [comment]
Please report the issue to npm repo, we can't fix it on our side
