### ISSUE TITLE
Removing and readding entry point makes the server explode

### ISSUE THREAD

**Issue by SimenB** [webpack/webpack-dev-server#270]
At the moment, I'm moving between branches Where the entry point has moved on one machine. If I move to a branch where the files is not in the location provided to webpack-dev-server, I get `Module build failed: Error: ENOENT` which is fine. But if I move back to the original branch, it doesn't pick up on the fact that the file exists, I have to restart the dev-server.
This is a problem as I have to rebase against a changing base all the time, and it dies. I have no idea if it's actually fixable, though.

**Comment by SpaceK33z** [comment]
I doubt if this is something we can fix in webpack-dev-server. webpack takes care of building these files, not the dev-server. We might implement live-reloading for the webpack config and content base, which would (maybe?) fix this problem; #440 and #350.
