### ISSUE TITLE
devServer.proxy must be a string or an object

### ISSUE THREAD

**Issue by suhrab** [webpack/webpack-dev-server#2702]
- Operating System: Windows 10
- Node Version: v12.16.2
- NPM Version: 6.14.2
- webpack Version: 4.44.1
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome 84.0.4147.125 (Official Build) (64-bit)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports = {
    devServer: {
        host: '0.0.0.0',
        port: 8080,
        disableHostCheck: true,
        proxy: [{
	    context: ['/api', 'goto'],
            target: 'http://localhost:49409'
        }]
    },
};
```

### Expected Behavior
DevServer should start with proxy defined as array. https://webpack.js.org/configuration/dev-server/
> If you want to proxy multiple, specific paths to the same target, you can use an array of one or more objects with a context property:

### Actual Behavior
Error:
> When specified, "proxy" in package.json must be a string or an object.
> Instead, the type of "proxy" was "object".
> Either remove "proxy" from package.json, or make it an object.

### For Bugs; How can we reproduce the behavior?
We discovered this bug using vue-cli
> vue create hello-world
> add devServer with proxy vue.config.js(webpack.config.js)
> npm run serve

**Comment by evilebottnawi** [comment]
Please open an issue in `vue-cli`
