### ISSUE TITLE
bazillion requests being made

### ISSUE THREAD

**Issue by luisrudge** [webpack/webpack-dev-server#271]
after upgrading to 1.11.0, the dev server is making a huge amount of requests. If I open the network tab, chrome crahses. Look at this:

![webpack](https://cloud.githubusercontent.com/assets/941075/9973250/dcb2f5cc-5e45-11e5-8675-f6b4d399abc7.gif)

**Comment by luisrudge** [comment]
Rolling back to 1.10.1 fixed this issue for me

**Comment by luisrudge** [comment]
thoughts?

**Comment by iansinnott** [comment]
Yeah I get the same bug in `1.12.2`.

**Comment by luisrudge** [comment]
@iansinnott are you using gulp with webpack?

**Comment by iansinnott** [comment]
Yes. Is it possible that's causing the issue?

**Comment by luisrudge** [comment]
Probably, yeah. I'm using webpack in other projects without gulp with success.

**Comment by iansinnott** [comment]
Interesting. I'm not using any gulp-specific module, so it may be an issue with the javascript API. Anyway, thanks for the info @luisrudge. I'll try using it without gulp.

**Comment by SpaceK33z** [comment]
@iansinnott, this ticket is no longer relevant then, right?

**Comment by luisrudge** [comment]
I haven't tried with gulp again..

**Comment by iansinnott** [comment]
Yeah I've upgraded a a bunch of modules in my workflow and I don't see this issue anymore. Can't pinpoint what was causing it but it doesn't seem to be a problem now

**Comment by SpaceK33z** [comment]
@luisrudge, can you close the ticket then?
