### ISSUE TITLE
 Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by Darsan357** [webpack/webpack-dev-server#2712]
- Operating System: Windows 10
- Node Version: v12.18.3
- NPM Version:  6.14.6
- webpack Version: ^4.44.1
- webpack-dev-server Version:^3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// 'use strict'
const utils = require('./utils')
const webpack = require('webpack')
const config = require('../config')
const merge = require('webpack-merge')
const path = require('path')
const baseWebpackConfig = require('./webpack.base.conf')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')
const portfinder = require('portfinder')

const HOST = process.env.HOST
const PORT = process.env.PORT && Number(process.env.PORT)

const devWebpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: true })
  },
  // cheap-module-eval-source-map is faster for development
  devtool: config.dev.devtool,

  // these devServer options should be customized in /config/index.js
  devServer: {
    clientLogLevel: 'warning',
    historyApiFallback: {
      rewrites: [
        { from: /.*/, to: path.posix.join(config.dev.assetsPublicPath, 'index.html') },
      ],
    },
    hot: true,
    contentBase: false, // since we use CopyWebpackPlugin.
    compress: true,
    host: HOST || config.dev.host,
    port: PORT || config.dev.port,
    open: config.dev.autoOpenBrowser,
    overlay: config.dev.errorOverlay
      ? { warnings: false, errors: true }
      : false,
    publicPath: config.dev.assetsPublicPath,
    proxy: config.dev.proxyTable,
    quiet: true, // necessary for FriendlyErrorsPlugin
    watchOptions: {
      poll: config.dev.poll,
    }
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': require('../config/dev.env')
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(), // HMR shows correct file names in console on update.
    new webpack.NoEmitOnErrorsPlugin(),
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true
    }),
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
  ]
})

module.exports = new Promise((resolve, reject) => {
  portfinder.basePort = process.env.PORT || config.dev.port
  portfinder.getPort((err, port) => {
    if (err) {
      reject(err)
    } else {
      // publish the new Port, necessary for e2e tests
      process.env.PORT = port
      // add port to devServer config
      devWebpackConfig.devServer.port = port

      // Add FriendlyErrorsPlugin
      devWebpackConfig.plugins.push(new FriendlyErrorsPlugin({
        compilationSuccessInfo: {
          messages: [`Your application is running here: http://${devWebpackConfig.devServer.host}:${port}`],
        },
        onErrors: config.dev.notifyOnErrors
        ? utils.createNotifierCallback()
        : undefined
      }))

      resolve(devWebpackConfig)
    }
  })
})

```

```js
// additional code, remove if not needed.
```

###  shows error ```
D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:96
    throw new _ValidationError.default(errors, schema, configuration);
    ^

ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\copy-webpack-plugin\node_modules\schema-utils\dist\validate.js:96:11)
    at new CopyPlugin (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\copy-webpack-plugin\dist\index.js:24:30)
    at Object.<anonymous> (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\build\webpack.dev.conf.js:61:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at WEBPACK_OPTIONS (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (D:\DATA\Learning\Creations\WEB\website\tabs tracker\Vue-and-Express.JS\client\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  errors: [
    {
      keyword: 'required',
      dataPath: '[0]',
      schemaPath: '#/required',
      params: { missingProperty: 'patterns' },
      message: "should have required property 'patterns'",
      schema: {
        patterns: { type: 'array', minItems: 1, items: { anyOf: [Array] } },
        options: {
          type: 'object',
          additionalProperties: false,
          properties: { concurrency: [Object] }
        }
      },
      parentSchema: {
        definitions: {
          ObjectPattern: {
            type: 'object',
            additionalProperties: false,
            properties: [Object],
            required: [Array]
          },
          StringPattern: { type: 'string', minLength: 1 }
        },
        type: 'object',
        additionalProperties: false,
        properties: {
          patterns: { type: 'array', minItems: 1, items: [Object] },
          options: {
            type: 'object',
            additionalProperties: false,
            properties: [Object]
          }
        },
        required: [ 'patterns' ]
      },
      data: {
        from: 'D:\\DATA\\Learning\\Creations\\WEB\\website\\tabs tracker\\Vue-and-Express.JS\\client\\static',
        to: 'static',
        ignore: [ '.*' ]
      },
      children: [
        {
          keyword: 'additionalProperties',
          dataPath: '[0]',
          schemaPath: '#/additionalProperties',
          params: { additionalProperty: 'from' },
          message: 'should NOT have additional properties',
          schema: false,
          parentSchema: {
            definitions: [Object],
            type: 'object',
            additionalProperties: false,
            properties: [Object],
            required: [Array]
          },
          data: {
            from: 'D:\\DATA\\Learning\\Creations\\WEB\\website\\tabs tracker\\Vue-and-Express.JS\\client\\static',
            to: 'static',
            ignore: [Array]
          },
          children: undefined
        },
        {
          keyword: 'additionalProperties',
          dataPath: '[0]',
          schemaPath: '#/additionalProperties',
          params: { additionalProperty: 'to' },
          message: 'should NOT have additional properties',
          schema: false,
          parentSchema: {
            definitions: [Object],
            type: 'object',
            additionalProperties: false,
            properties: [Object],
            required: [Array]
          },
          data: {
            from: 'D:\\DATA\\Learning\\Creations\\WEB\\website\\tabs tracker\\Vue-and-Express.JS\\client\\static',
            to: 'static',
            ignore: [Array]
          },
          children: undefined
        },
        {
          keyword: 'additionalProperties',
          dataPath: '[0]',
          schemaPath: '#/additionalProperties',
          params: { additionalProperty: 'ignore' },
          message: 'should NOT have additional properties',
          schema: false,
          parentSchema: {
            definitions: [Object],
            type: 'object',
            additionalProperties: false,
            properties: [Object],
            required: [Array]
          },
          data: {
            from: 'D:\\DATA\\Learning\\Creations\\WEB\\website\\tabs tracker\\Vue-and-Express.JS\\client\\static',
            to: 'static',
            ignore: [Array]
          },
          children: undefined
        }
      ]
    }
  ],
  schema: {
    definitions: {
      ObjectPattern: {
        type: 'object',
        additionalProperties: false,
        properties: {
          from: { type: 'string', minLength: 1 },
          to: { type: 'string' },
          context: { type: 'string' },
          globOptions: { type: 'object' },
          toType: { enum: [Array] },
          force: { type: 'boolean' },
          flatten: { type: 'boolean' },
          transform: { instanceof: 'Function' },
          cacheTransform: { anyOf: [Array] },
          transformPath: { instanceof: 'Function' },
          noErrorOnMissing: { type: 'boolean' }
        },
        required: [ 'from' ]
      },
      StringPattern: { type: 'string', minLength: 1 }
    },
    type: 'object',
    additionalProperties: false,
    properties: {
      patterns: {
        type: 'array',
        minItems: 1,
        items: { anyOf: [ [Object], [Object] ] }
      },
      options: {
        type: 'object',
        additionalProperties: false,
        properties: { concurrency: { type: 'number' } }
      }
    },
    required: [ 'patterns' ]
  },
  headerName: 'Copy Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Darsan\AppData\Roaming\npm-cache\_logs\2020-08-20T02_33_23_145Z-debug.log
```

### For Bugs; How can we reproduce the behavior?

### For Features; What is the motivation and/or use-case for the feature?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

No related to `webpack-dev-server`, please read the error message, it is validation error due invalid configuration of `copy-webpack-plugin`
