### ISSUE TITLE
Create migration guide

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack-dev-server#2713]
We are going to release the next version but we have many breaking changes between v3 and v4 so we should create a migration guide for developers.

Related: https://github.com/webpack/webpack-dev-server/pull/2592

**Comment by evilebottnawi** [comment]
I think we can describe it in changelog, no need extra doc, it is already in my todo before release

**Comment by hiroppy** [comment]
ok, let me know when you create the changelog.
