### ISSUE TITLE
[HMR] Waiting for update signal from WDS...(PROBLEM)

### ISSUE THREAD

**Issue by Rohit-huta** [webpack/webpack-dev-server#2725]
- Operating System: MacOS
- Node Version: v12.18.3
- NPM Version: 6.14.6
- webpack Version: 4.42.0
- webpack-dev-server Version: 
- Browser: CHROME

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code
[HMR] Waiting for update signal from WDS...(PROBLEM)

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
it should start running my code.
### Actual Behavior
[HMR] Waiting for update signal from WDS...
<img width="1440" alt="Screenshot 2020-08-31 at 1 58 31 PM" src="https://user-images.githubusercontent.com/70508911/91736700-b70a1080-ebcb-11ea-8703-2242241c936e.png">

### For Bugs; How can we reproduce the behavior?
-
### For Features; What is the motivation and/or use-case for the feature?
-

**Comment by evilebottnawi** [comment]
Please fill out all fields, I again repeat I can't help without this information, please respect time of other developers, I will reopen when you done it

**Comment by evilebottnawi** [comment]
What you expected, it is normal have this message in console
