### ISSUE TITLE
[HMR] Waiting for update signal from WDS...(STUCK HERE, not running my code)

### ISSUE THREAD

**Issue by Rohit-huta** [webpack/webpack-dev-server#2726]
- Operating System: MacOS
- Node Version: v12.18.3
- NPM Version: 6.14.6
- webpack Version: 4.42.0
- webpack-dev-server Version: ^3.11.0
- Browser: CHROME

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code
[HMR] Waiting for update signal from WDS...(PROBLEM)

```js
// webpack.config.js
import React, {Component} from 'react';

class Application extends Component {
  constructor(props){
    super(props);

    this.state = {
      count: 0
    }
  }

  handleClick = () => {
    console.log("dfsd");
  }
  
  render(){
    let {count} = this.state;
    return (
      <div>
      <h1>You clicked the button {count} times</h1>
      <span>
        <button onClick={(e) => this.handleClick}>CLICK ME</button>
      </span>
      </div>
    );
  }
}

export default Application;
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
it should start running my code.
### Actual Behavior
[HMR] Waiting for update signal from WDS...STUCK HERE
<img width="1440" alt="Screenshot 2020-08-31 at 1 58 31 PM" src="https://user-images.githubusercontent.com/70508911/91736700-b70a1080-ebcb-11ea-8703-2242241c936e.png">

### For Bugs; How can we reproduce the behavior?
-
### For Features; What is the motivation and/or use-case for the feature?
-

**Comment by evilebottnawi** [comment]
Please stop doing it, fill out **all** fields, without configuration I can't help

**Comment by Rohit-huta** [comment]
> Please stop doing it, fill out **all** fields, without configuration I can't help

NOW??? I don't, I think I have filled all the fields. IF any left please specify, I'm a bit noob. Apologies

**Comment by evilebottnawi** [comment]
Your link `https://github.com/Rohit-huta/React_beginner.git` is not working, please fix it
