### ISSUE TITLE
Getting errors - while installing ‘WebPack’ package using ‘npm’ (node package manager) (So that this can be used in package.json)

### ISSUE THREAD

**Issue by bhagya099** [webpack/webpack-dev-server#2730]
Issue - Getting errors - while installing ‘WebPack’ package using ‘npm’ (node package manager) (So that this can be used in package.json)

Error:
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.2.13 install /Users/riddhish/Desktop/Forkify Project/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/riddhish/Desktop/Forkify Project/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.9.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN forkify@1.0.0 No repository field.

Observation during Further investigation
We have already upgraded to latest version of Chokidar but system is still showing the same error, it looks like system is not referring to the latest version of chokidar.

- Operating System:OS - Catalina 10.15.6

- Node Version: 14.9.0
- NPM Version:6.14.8
- webpack Version:  4.44.1
- webpack-dev-server Version: -
- Browser: Chrome 85.0.4183.83

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Something wrong with your computer, try to `npm i -D chokidar` and when `npm i -D webpack`
