### ISSUE TITLE
Security problem with `node-forge`

### ISSUE THREAD

**Issue by warpech** [webpack/webpack-dev-server#2739]
GitHub Security Advisory reports that `node-forge` 0.9.0, which is an indirect dependency of `webpack-dev-server` 3.11.0 has a high deverity problem: https://github.com/advisories/GHSA-92xj-mqp7-vmcj

Webpack Dev Server uses that package through a package called `selfsigned`, which tracks this problem here: https://github.com/jfromaniello/selfsigned/issues/41

**Comment by evilebottnawi** [comment]
No need to duplicate issue, it should be fixed in `selfsigned`, we can't fix it on our side

**Comment by warpech** [comment]
Sorry, but I can't see how the fix in `selfsigned` will automatically propagate to `webpack-dev-server`. Is there some automatic process for that?

**Comment by warpech** [comment]
You might consider that https://github.com/jfromaniello/selfsigned/issues/41 is quite stale. The author does not respond in the issue and did not commit to the repo https://github.com/jfromaniello/selfsigned/commit/7b3fb86eab6307c29a6b8276b4e73197768c1f28

**Comment by evilebottnawi** [comment]
@warpech How we can fix it? Be patient the developer will fix it soon

**Comment by warpech** [comment]
> @warpech How we can fix it? Be patient the developer will fix it soon

By a resolution in the project lockfile. Personally I don't care, I made a resolution in my lockfile.

**Comment by evilebottnawi** [comment]
@warpech our lock file is not related to your lock file

**Comment by warpech** [comment]
Sorry, I meant `resolution` in `package.json`, but I just realised that this is a Yarn-only solution. Let's hope https://github.com/jfromaniello/selfsigned/issues/41 gets fixed soon.

**Comment by evilebottnawi** [comment]
> Sorry, I meant resolutions in package.json

Yes, we need a fix

**Comment by jrochkind** [comment]
If selfsigned is unmaintained and does not fix it, I think webpack-dev-server needs to eliminate selfsigned as a dependency, is what makes it potentially a webpack-dev-server issue.

**Comment by evilebottnawi** [comment]
@jrochkind I suggest to wait a little longer, I tried to contact the developers

**Comment by evilebottnawi** [comment]
Fixed https://github.com/jfromaniello/selfsigned/releases/tag/v1.10.8, As you can see, this is usually not difficult. Just update lock files

**Comment by jrochkind** [comment]
Thanks! Not difficult if you are authorized to do a release of the dependency, or can get the attention of those who are! Others of us tried by filing an issue on the selfsigned project and failed, but perhaps being a maintainer of webpack-dev-server got their attention, or using a method of communication other than github issues? Anyway, thanks!

**Comment by khhhum** [comment]
any plans on releasing an updated webpack-dev-server with this dependency updated?

**Comment by jrochkind** [comment]
webpack-dev-server already allows the updated `selfsigned` and `node-forge`, a webpack-dev-server release isn't required to use those updated dependencies. 

But it can be confusing to figure out how to update 'indirect' dependencies like this, and the tooling can be surprisingly unhelpful. 

If you are using `yarn`, the best way i have found is to open up the `yarn.lock` manually, and delete the lines for `selfsigned` and `node-forge`, and then run `yarn install`. It will insert the (new) latest allowable releases of `selfsigned` and `node-forge` into your yarn.lock, and you have updated your dependencies, no need for a webpack-dev-server release.  See this [blog post](https://medium.com/@ayushya/upgrading-javascript-packages-deep-dependencies-using-yarn-8b5983d5fb6b) and this [yarn issue](https://github.com/yarnpkg/yarn/issues/4986).  I remain surprised yarn doesn't support a way of upgrading indirect dependencies less manually. 

If you are using `npm` straight without yarn or other alternatives, I'm not certain the approach, but there should be one that does not require a `webpack-dev-server` release.  If dependencies had to be re-released every time there was a new release of any of their own dependencies, that would be messy!

**Comment by ilam-natarajan** [comment]
an alternative to manually editing yarn.lock file was,
1. add below to package.json
```json
"resolutions": {
    "webpack-dev-server/**/selfsigned": "^1.10.8"
  }	  
```
2. yarn install . This modifies yarn.lock
3. git restore package.json
4. yarn install . This again modifies yarn.lock
5. commit yarn.lock change

**Comment by khhhum** [comment]
thank you, that did indeed help :)

**Comment by jrochkind** [comment]
One thing that worries me about the `resolutions` solution is that if you aren't careful you can get a version of an indirect dependency that *violates* the restrictions of the more direct dependency, and runs a greater risk of not working properly. Rather than the intent, updating to the most recent indirect dependency allowed by other dependency restrictions. 

But this is now a different conversation about that general topic. Although this particular issue here is a good demonstration of why, IMO, yarn needs a built-in method for updating indirect dependencies; I'm still kinda confused that yarn maintainers haven't seen this need.
