### ISSUE TITLE
Security Alert: please update `selfsigned` package version

### ISSUE THREAD

**Issue by Tzahile** [webpack/webpack-dev-server#2741]
- Operating System: win10
- Node Version: 14.8.0
- NPM Version: 6.14.6
- webpack Version: ^4.0.0
- webpack-dev-server Version: 3.11.0
- Browser: chrome 85.0.4183.102

- [x] This is a **bug**
- [ ] This is a **modification** request

### Actual Behavior
  Dependency alert is given for `selfsigned@1.10.7` package - because of `node-forge` issue.
  There's already an update available - `selfsigned@1.10.8` fixing it.
### For Bugs; How can we reproduce the behavior?
  check your dependabot;
  https://github.com/advisories/GHSA-92xj-mqp7-vmcj

**Comment by evilebottnawi** [comment]
Please update your lock file
