### ISSUE TITLE
webpack output is served from undefined

### ISSUE THREAD

**Issue by loadingwyn** [webpack/webpack-dev-server#2745]
**Describe the bug**

The output of webpack doesn't get served.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/17921180/94137890-c3674d80-fe99-11ea-951d-771549320035.png)

My config:

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
  entry: './index.ts',
  context: path.resolve(__dirname),
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader', 'postcss-loader'],
      },
    ],
  },
  devServer: {
    contentBase: './demo',
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },

};
```
Command: 

`webpack serve --config ./demo/webpack.config.js --mode development --open chrome`

**To Reproduce**

1. Define a devServer config in your webpack config file
2. Run webpack serve --config webpack.dev.js

**Expected behavior**

The output js file can be served by dev server

**Additional context**

![image](https://user-images.githubusercontent.com/17921180/94138153-3bce0e80-fe9a-11ea-8eae-b323ef839754.png)

**Comment by Bowser65** [comment]
I've encountered this issue on my end and after some digging, it appears specifying `publicPath` inside `devServer` options in my config solved it.

```js
{
  ...,
  devServer: {
    ...,
    publicPath: '/dist'
  }
}
```

**Comment by dwiyatci** [comment]
@Bowser65 🤦🏻‍♂️ isn't that weird? If `devServer.publicPath`, it should actually be default to `'/'`.

https://webpack.js.org/configuration/dev-server/#devserverpublicpath-

🤷🏻‍♂️
