### ISSUE TITLE
why entryOption will be executed twice

### ISSUE THREAD

**Issue by zhuping** [webpack/webpack-dev-server#2746]
When I wrote the webpack plugin in the project created by vue cli4, I found that the callback function was executed twice when the entryOption hook was registered. Not sure if it is a bug or by design

- Operating System:Mac OS
- Node Version:v12.13.0
- NPM Version:6.12.0
- webpack Version: ^4.0.0
- webpack-dev-server Version:^3.4.1
- Browser:

### Code

```js
// webpack plugin code
```
```js
class Plugin {
  apply(compiler) {
    if (compiler.hooks) {
      compiler.hooks.entryOption.tap('xxx', () => {
        console.log(111111111)
      })
    }
  }
}

module.exports = Plugin
```

```js
// vue.config.js.
```

```js
const Plugin = require('./plugin')

module.exports = {
  configureWebpack: config => {
    config.plugins.push(
      new Plugin()
    );
  },
}
```

### Expected Behavior

execute entryOption callback only once

### Actual Behavior

execute twice

**Comment by evilebottnawi** [comment]
It is hack for webpack@4, fixed in webpack@5
