### ISSUE TITLE
webpack-dev-server lists common chunk as dependency to unrelated entry point

### ISSUE THREAD

**Issue by mbehzad** [webpack/webpack-dev-server#2747]
- Operating System: Windows 10
- Node Version: v12.13.0
- NPM Version: 6.12.0
- webpack Version: 4.44.2
- webpack-dev-server Version: 3.11.0
- Browser: any

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Minimal reproducale repo:
https://github.com/mbehzad/webpack-dev-server-common-chunk-bug

```js
// webpack.config.js
const path = require("path");

module.exports = {
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000,
    hot: false,
  },
  entry: {
    a: "./src/a.js", // has dependency to utils.js
    b: "./src/b.js", // has dependency to utils.js
    c: "./src/c.js", // has no (shared) dependency
  },
  output: {
    filename: '[name].bundle.js',
    path: __dirname + '/dist'
  },
  mode: "development",

  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          name: "common",
          filename: "common.js",
          chunks: "initial",
          minChunks: 2,
          minSize: 0,
        },
      },
    },
  },

}
```

### Expected Behavior
There are 3 entry points a.js, b.js and c.js. a and b have a common dependency to utils.js. Webpack with optimization.splitChunks option will generate a common.js chunk (with utils.js content) which a.bundle.js and b.bundle.js are depending on. The c.bundle.js can be used standalone because it has no (shared) dependecy with other entries.

This is the behaviour when using the webpack cli directly:
cmd output: 
```cmd
Entrypoint a = common.js a.bundle.js
Entrypoint b = common.js b.bundle.js
Entrypoint c = c.bundle.js   //  <----------------
```

### Actual Behavior
But when generating the bundles via webpack-dev-server (instead of webpack cli), the common chunk is listed as an output and therefor required to be loaded for the entry c. even if it has no dependency in the source code to it:

cmd output:

```cmd
Entrypoint a = common.js a.bundle.js
Entrypoint b = common.js b.bundle.js
Entrypoint c = common.js c.bundle.js  //  <------- 
```

In c.bundle.js:

```js
/******/ 	// add entry module to deferred list
/******/ 	deferredModules.push([2,"common"]);
```

### For Bugs; How can we reproduce the behavior?

Check out https://github.com/mbehzad/webpack-dev-server-common-chunk-bug repo, there are two npm scripts `npm run build` which calls the webpack cli directly, and outputs will be in "dist" folder. and `npm start` which calls webpack-dev-server and the output can be opened in the browser under localhost:9000

**Comment by evilebottnawi** [comment]
Not related to webpack-dev-server, you need to use `dependOn` (only in webpack@5)
