### ISSUE TITLE
Not be able to develop Web Extensions

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack-dev-server#2748]
- Operating System: Not related
- Node Version: Not related
- NPM Version: Not related
- webpack Version: Not related
- webpack-dev-server Version: webpack-dev-server@3.11.0
- Browser: Not related

When I use webpack-dev-server with web extension, it reports "Invalid Host/Origin header"

https://github.com/webpack/webpack-dev-server/blob/89ffb86cd26425c59e3937ca06a2c804a01b8f1d/lib/Server.js#L712-L713

The code assumes connection comes from `http://` which disabled our use case.

In our use cases, the connection usually starts from a `chorme-extension://` URL or a `browser-extension://` URL. Please add an option to close the origin check!

- [x] This is a **bug**
- [x] This is a **modification** request

**Comment by evilebottnawi** [comment]
You need to set `https://webpack.js.org/configuration/dev-server/#devserverdisablehostcheck` to `true`

**Comment by Jack-Works** [comment]
Hi! Thanks for your reply! It do work but now I get another problem.

![image](https://user-images.githubusercontent.com/5390719/94441407-4ad3fa00-01d5-11eb-9105-f63fa2e2a392.png)

WDS is injecting code using a script tag, which will cause a context change (and get the wrong result) in our environment. How can I change that to let WDS call `eval` directly?

**Comment by evilebottnawi** [comment]
I need your config, webpack always inject code using `script` tag, not sure it is problem with webpack-dev-server

**Comment by Jack-Works** [comment]
Thanks, I'll investigate this by myself later

**Comment by Jack-Works** [comment]
Problem resolved. Please see https://github.com/crimx/webpack-target-webextension
