### ISSUE TITLE
Release webpack-dev-server v4 or make chokidar dependency v3 instead of v2 for webpack-dev-server v3.11.0

### ISSUE THREAD

**Issue by tatsujb** [webpack/webpack-dev-server#2754]
- Operating System: Mac OS Catalina 10.15.6
- Node Version: 12.18.1
- NPM Version: 5.1.0
- webpack Version: 4.43.0
- webpack-dev-server Version: 3.11.0 (2020-05-08)
- Browser: chrome 84.0.4147.135

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

for `npm install` with an Angular-cli project to finish with a success under mac Catalina

### Actual Behavior

`npm install` fails

### For Bugs; How can we reproduce the behavior?

clone and `npm i` an angular-cli project under mac Catalina

### For Features; What is the motivation and/or use-case for the feature?

having a functional npm stack under mac Catalina and multiple other newer entries of operating systems.

### Explanation 

fsevents v1 has been deprecated for over a year it is at long last fully incompatible with the latest iteration of MacOS (the two latest iterations if you count Big Sur) and a number of other unix-based OSes, but unfortunately fsevents v1 is what was around at the time chokidar v2 was made.

fsevents v2 has existed for a year and chokidar 3 since may 2019, however in it's latest release : 3.11.0 (2020-05-08), webpack-dev-server still points towards chokidar v2.

Apparently this is not the case in dev of  webpack-dev-server v4 but webpack-dev-server v4 is not released. 

This puts angular developers on the platforms I mentioned in difficulty.

### Current hacky workaround

Through experimentation, I stumbled upon a workaround that makes tons of gyp errors in `npm install` but finishes on an install success so it can probably help others : 

     npm i -d fsevents@2.1.3

or manually adding fsevents@2.1.3 to your dev-dependencies.

you can then run `npm i` successfully.

fsevents@2.1.3 will download but npm will attempt (and fail) to compile fsevents v1 anyways but since the fsevents dependency is met, npm is sorta satisfied.

**Comment by evilebottnawi** [comment]
ETA is `2020-10-07`

**Comment by tatsujb** [comment]
@evilebottnawi thanks that's good to hear, I saw you as a contributor for webpack, will you be able to make webpack follow suit at the same date?

And when that's the case, what happens with Angular-cli? (I saw you're not a contributor there) are they alerted to this impending change and "on-deck"?

should I create an issue at angular-cli to alert them of this impending change?

**Comment by evilebottnawi** [comment]
@tatsujb webpack@5 release is `2020-10-10` (couple days on fixing some critical issues). 

> And when that's the case, what happens with Angular-cli? (I saw you're not a contributor there) are they alerted to this impending webpack v5 and "on-deck" to release their own Angular-cli update that includes it?

I think they already work on this https://github.com/angular/angular-cli/pull/18820

Anyway better ask this in angular-cli repo

**Comment by jimsimon** [comment]
Any ETA on this fix? It's causing a lot of issues with `npm@7`.

**Comment by evilebottnawi** [comment]
Next week, hope, a lot of issue and very few time :disappointed:

**Comment by evilebottnawi** [comment]
Fixed in v4 branch (release will be soon), sorry for delay

**Comment by HansAarneLiblik** [comment]
This is not resolved yet despite even a change in year
