### ISSUE TITLE
High vulnerability found for node-forge@0.9.0 (Need to upgrade to 0.10.0)

### ISSUE THREAD

**Issue by phoebe-rival** [webpack/webpack-dev-server#2755]
- Operating System:  N/A
- Node Version:  All
- NPM Version:  All
- webpack Version:  N/A
- webpack-dev-server Version:  3.11.0
- Browser:  N/A

- [X ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
npm-audit-ci-wrapper --threshold=high 

returns:

node-forge@0.9.0 │ high     │ https://www.npmjs.com/advisories/1561
```

### Expected Behavior
Upgrade and remove this vulnerability

**Comment by piraces** [comment]
There are two PRs related to this... Hope they merge them soon.
**For reference:**
https://github.com/webpack/webpack-dev-server/pull/2752
https://github.com/webpack/webpack-dev-server/pull/2740

**Comment by evilebottnawi** [comment]
Please update your lock file, we use `^` to avoid extra releasing when something broken in transitive deps
