### ISSUE TITLE
[BUG] clientLogLevel: 'none' not working

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [webpack/webpack-dev-server#2756]
Version:
-
    "webpack": "^4.44.2",
    "webpack-dev-server": "^3.11.0",

Config:
-
webpack.config.js:

```js
module.exports = {
    devServer: {
      clientLogLevel: 'none',
      contentBase: path.resolve(__dirname, build),
      stats: 'errors-only',
      port: 3000,
      hot: true,
    },
}
```

Behavior:
-
![image](https://user-images.githubusercontent.com/69426460/95030766-8cbfdd00-06ba-11eb-9a14-e525b9e47490.png)

Expected behavior:
-

None of these lines should be in the console, neither the first nor the second:
```
[HMR] Waiting for update signal from WDS...
[HMR] Detected local css modules. Reload all css
```

**Comment by MaxmaxmaximusAWS** [comment]
temp solution for chrome:

![image](https://user-images.githubusercontent.com/69426460/95031453-c7c40f80-06be-11eb-86b0-07d1e5e4d2e2.png)

![image](https://user-images.githubusercontent.com/69426460/95031464-d3173b00-06be-11eb-952a-10194fb3dc62.png)

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0 and https://webpack.js.org/configuration/other-options/#infrastructurelogginglevel

**Comment by MaxmaxmaximusAWS** [comment]
@alexander-akait 
![image](https://user-images.githubusercontent.com/69426460/100487486-f3410480-3119-11eb-8b78-cfe60a207f97.png)

**Comment by ylemkimon** [comment]
https://webpack.js.org/configuration/other-options/#level

**Comment by chenxsan** [comment]
@alexander-akait I'll take a look at it soon.

**Comment by chenxsan** [comment]
`infrastructureLogging.level` would be too long for sidebar:

![image](https://user-images.githubusercontent.com/1091472/100530420-e3661500-322c-11eb-8fda-6c1b4c3202da.png)

Hence sometimes ago we changed the header from `infrastructureLogging.level` to `level`.
