### ISSUE TITLE
any idea to hide the status logs?

### ISSUE THREAD

**Issue by tageecc** [webpack/webpack-dev-server#2757]
Hi! I use node api to start the service, and then I don’t want to output any logs to the console. When I set quiet: true, the status information cannot be hidden。

I look at the source code here: 
[https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L766](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L766)

This seems to be mandatory, but it doesn’t feel very reasonable

**Comment by evilebottnawi** [comment]
Fixed in v4, release will be `2020-10-07`

**Comment by tageecc** [comment]
@evilebottnawi any problems?

**Comment by evilebottnawi** [comment]
Yes, more work than expected, WIP
