### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by yilmazbingo** [webpack/webpack-dev-server#2759]
- Operating System: kali-2020
- Node Version: v10.21.0
- NPM Version: 6.14.7
- webpack Version: ^5.0.0
- webpack-dev-server Version:^3.11.0"

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
webpack-dev-server should compile
### Actual Behavior
Error: Cannot find module 'webpack-cli/bin/config-yargs'

webpack-dev-server is dependent on the webpack-cli. looks like it has been updated 13 hours ago to version 4.0.0 so its folder structure has changes. here is the current folder structure:
![webpack-cli](https://user-images.githubusercontent.com/47233790/95673600-128acf00-0b78-11eb-8522-7bab12eb8815.jpg)

this is the older folder structure i just created a few days ago:
![Screen Shot 2020-10-11 at 4 15 54 AM](https://user-images.githubusercontent.com/47233790/95673657-92b13480-0b78-11eb-987b-ec75ee98cbda.png)

**Comment by martinoppitz** [comment]
Yes - webpack-dev-server does not work with webpack-cli v4

**Comment by wood1986** [comment]
Same there. But when will it get fixed?

**Comment by snitin315** [comment]
Can you try `webpack serve` ?

**Comment by wood1986** [comment]
@snitin315 What is the difference between `webpack-dev-server` and `webpack serve`? Does it mean I do not need `webpack-dev-server` when I use webpack v5?

**Comment by snitin315** [comment]
Yes webpack-cli v4 comes with out of box support of `@webpack-cli/serve` which means you can use `webpack serve` to invoke the `webpack-dev-server`.

**Comment by evilebottnawi** [comment]
We need to add try/catch to our cli when we require module from webpack-cli and output a warning to use webpack serve to run webpack dev server

**Comment by malcolm-kee** [comment]
Able to reproduce the bug in Windows.

**Comment by navirick** [comment]
Can you provide an example of how we replace the use of devServer in our webpack config file with serve?

**Comment by evilebottnawi** [comment]
Please update `webpack-cli` to v4 and use `webpack serve` to run webpack-dev-server

**Comment by mybrainishuge** [comment]
How are [environment options](https://webpack.js.org/api/cli/#environment-options) passed to `webpack serve` when [exporting a function](https://webpack.js.org/configuration/configuration-types/#exporting-a-function) in the webpack config? With `webpack-dev-server`, I passed environment variables:
```
webpack-dev-server --env.mode development
```
Passing the same argument to `webpack serve` errors:
```
[webpack-cli] Unknown argument: --env.mode
[webpack-cli] Unknown argument: development
```
I'm not seeing how to pass anything other than booleans to `webpack serve`, but I want to pass strings:
```
webpack serve --env mode
```

**Comment by navirick** [comment]
I would hope since it seems it is understood what is needed for webpack-dev-server to work with webpack 5, the authors would put a fix in ASAP to resolve this issue. I too am trying webpack serve, and am not able to get it to work. In the future, when suggesting a change like this, it would be extremely beneficial to provide a simple example of how it should work. As it is, it seems this requires knowledge or figuring out how serve works which is different than how webpack-dev-server works.

**Comment by AstroneCommons** [comment]
> Please update `webpack-cli` to v4 and use `webpack serve` to run webpack-dev-server

I also had to reinstall webpack dev server (v3.11.0) to make it work.

**Comment by wanliyunyan** [comment]
`"dev": "webpack server --mode development --env development"`

```
"webpack": "^5.0.0",
"webpack-cli": "^4.0.0",
"webpack-dev-server": "^3.11.0",
```

ERROR in main
Module not found: Error: Can't resolve 'server' in '*********'

webpack 5.0.0 compiled with 1 error in 521 ms

what should I do?

**Comment by mybrainishuge** [comment]
@wanliyunyan 
Should be `webpack serve` not `server`

```"dev": "webpack serve --mode development --env development"```

**Comment by wanliyunyan** [comment]
> @wanliyunyan Should be `webpack serve` not `server`:
> 
> ```
> "dev": "webpack serve --mode development --env development"
> ```

thank you,.............

**Comment by YahzeeSkellington** [comment]
The migration guide says we should be using webpack-dev-server instead of serve:

``
serve ↦ serve is removed in favor of DevServer
```

[https://webpack.js.org/migrate/5/]{https://webpack.js.org/migrate/5/)

Furthermore HMR no longer works when I switch to 'serve'. The browser console logo shows `[HMR] Waiting for update signal from WDS...` but nothing happens. Going back to Webpack 4

**Comment by chenxsan** [comment]
@YahzeeSkellington 

That `serve`/`devServer` mentioned in migration is a configure defined in webpack configuration, not the one used in CLI.

Regarding the HMR, you might have the similar issue as https://github.com/webpack/webpack-dev-server/issues/2758 if you have browserslist in your project.

**Comment by Yammoe** [comment]
@YahzeeSkellington  as @chenxsan  said, I removed "browsersList" from package.json and hot reload work well.

**Comment by evilebottnawi** [comment]
Please stop spam, we known about the problem and we provide solution above

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0
