### ISSUE TITLE
socket.io too verbose

### ISSUE THREAD

**Issue by jardakotesovec** [webpack/webpack-dev-server#276]
Just updated to newest webpack and webpack-dev-server. And using node v4.1
```
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.11.0"
```

And socket.io got too verbose in browser.. not sure how to suppress that so I can see important stuff:
![screenshot 2015-09-22 11 06 51](https://cloud.githubusercontent.com/assets/1590681/10014549/5179d228-611a-11e5-8b47-96bab770da06.png)

**Comment by SpaceK33z** [comment]
See my comment in [#302](https://github.com/webpack/webpack-dev-server/pull/302#issuecomment-161585998) for a fix.

This is not a bug.
