### ISSUE TITLE
CLI open option no longer opens default browser with webpack 5

### ISSUE THREAD

**Issue by paulfalgout** [webpack/webpack-dev-server#2765]
- Operating System: OSX
- Node Version: 10.22.0
- NPM Version: 6.14.6
- webpack Version: 5.1.0
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

`webpack serve --open true`

### Expected Behavior

Expect my default browser to launch after compilation

### Actual Behavior

Nothing happens.  No error.  Server does start successfully.  However naming a specific browser _does_ work.  `webpack serve --open 'Google Chrome'` or simply setting `open: true` in the webpack config works.

### For Bugs; How can we reproduce the behavior?

`webpack serve --open true`

**Comment by evilebottnawi** [comment]
This mean you don't have default browser, so nothing to open

**Comment by paulfalgout** [comment]
I really do not think it is my default.

`--open true` works with webpack 4 And `open: true` works in the webpack config.  
Only the `--open true` with webpack 5 isn't working.

**Comment by evilebottnawi** [comment]
Because `--open true` is `true` browers, boolean flags work `--open` or `--no-open`

**Comment by paulfalgout** [comment]
```
> webpack serve --open

error: option '--open <value>' argument missing
```

**Comment by paulfalgout** [comment]
FWIW I was using `webpack-dev-server --open` previously with webpack 4.

**Comment by evilebottnawi** [comment]
@paulfalgout bug, thanks

**Comment by milahu** [comment]
```
npx webpack-dev-server --open xdg-open # linux
npx webpack-dev-server --open open # mac?
npx webpack-dev-server --open explorer # win?
```

cross platform: https://github.com/sindresorhus/open

but open.js does not work with the `--open cmd` option, cos its not a CLI app

**Comment by alexander-akait** [comment]
Fixed, release will be in near future
