### ISSUE TITLE
Is there any plan to upgrade sockjs version to 0.3.21?

### ISSUE THREAD

**Issue by anandshanbhag** [webpack/webpack-dev-server#2767]
- Operating System: Windows 10 & Mac
- Node Version: 10.22.1
- NPM Version: 6.14.6
- webpack Version: 4.44.1
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?
webpack-dev-server is having a dependency on sockjs and the current version that it is using is 0.3.20.

Sockjs version 0.3.20 in turn uses faye-websocket version "^0.10.0". faye-websocket 0.10.* has some security issue and is causing issues in our security scans.
Is there any plan to upgrade sockjs version to 0.3.21 which uses faye-websocket version ^0.11.3?

Some details on my application;
I am using Angular 10 in my application and presently @angular-devkit/build-angular is refering to the latest version(3.11.0) of webpack-dev-server.

**Comment by evilebottnawi** [comment]
Update your lock file

**Comment by anandshanbhag** [comment]
I didn't raise this as a bug and the fix that you provided assumes that we maintain package-lock.json file in the repository along with the codebase. If you have any plans then please let me know or else close the issue by saying not planned.

Our codebase doesn't contain the package-lock.json and there are reasons for that. Due to this ever time we clean build we create package-lock.json file.

**Comment by jlholtus** [comment]
Please re-open this issue. There is a security issue with sockjs 0.3.20. The issue is fixed in sockjs 0.3.21.

Manually updating my lock file would work but bumping the dependency would resolve this issue for everyone. Thank you.
