### ISSUE TITLE
devServer.hot not working.

### ISSUE THREAD

**Issue by oimmc** [webpack/webpack-dev-server#2768]
"webpack": "^5.1.0",
"webpack-cli": "^4.0.0",
"webpack-dev-server": "^3.11.0",

devServer: {
		historyApiFallback: true,
		host: '0.0.0.0',
		port: 8989,
		compress: true,
		noInfo: true,
		useLocalIp: true,
		hot: true,
		open: false
}

"start": "cross-env NODE_ENV=development webpack serve --progress --config webpack.dev.js"

run npm start, hot not working.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
