### ISSUE TITLE
front-end behind webpack-dev-server , Server sent event (event source) doesn't reconnect

### ISSUE THREAD

**Issue by archerbj** [webpack/webpack-dev-server#2769]
# Bug report

**What is the current behavior?**
we have a SPA with front-end using webapck-dev-server as proxy server. Front-end use SSE connects backend through webpack-dev-server. 

When you shut down the backend, the failure of the connection doesn't be raised. But if we use Nginx as the host of the frontend, it works perfectly.

**If the current behavior is a bug, please provide the steps to reproduce.**
1.Setup SSE between frontend and backend, and use webpack dev server as proxy
2.Shutdown backend 
3.See if the onError callback function is called.

**What is the expected behavior?**
the failure of the SSE connection can be detected.

**Other relevant information:**
webpack version:  3.10.0 (webpack-dev-server ^2.9.7)
Node.js version: v14.9.0
Operating System:  Mac
Additional tools:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by evilebottnawi** [comment]
Update `webpack-dev-server` to latest versions

**Comment by eviltik** [comment]
At the opposite, client disconnection are not forwarded to the backend server by default, you have to add this in your devserver proxy conf

```
onProxyReq: (proxyReq, req, res) => {
   res.on('close', () => proxyReq.destroy() )
},
```

Not sure if it should be something by default. Nginx default behavior handle client disconnection properly. Webpack should.

**Comment by alexander-akait** [comment]
I think we have this, what is `webpack-dev-server` version?

**Comment by eviltik** [comment]
Always up to date, so v4.13.3. I can make a repo for testing this if you want.

**Comment by yoyo837** [comment]
> Always up to date, so v4.13.3. I can make a repo for testing this if you want.
> 
> ```
> devServer:{
>    server:'https',
>    allowedHosts:'all',
>    liveReload:true,
>    historyApiFallback:{
>      rewrites: [ { from:/^\/backoffice/, to:'/backoffice/index.html' } ],
>      index: 'index.html'
>   },
>   compress:false,
>   port:44380,
>   static:[
>     {
>        directory:path.join(__dirname, 'public),
>        publicPath:'/',
>        serveIndex: true
>     },
>     proxy:{
>        '/stream':{
>           target:'http://streamd:8080',
>           // very short timeout, for testing : SSE sent ping message every sec
>           proxyTimeout:1000 * 5, 
>           timeout:1000 * 5,
>           xfwd:true,
>           
>           // without this onProxyReq setup, client disconnection are not forwarded to the backend.
>           
>           onProxyReq: (proxyReq, req, res) => {
>             res.on('close', () => proxyReq.destroy() )
>           }
>        }
>     }
> }
> ```

It is not works for me. `webpack@5`
