### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by OlegRomashov** [webpack/webpack-dev-server#2770]
Good afternoon. 
Error: Cannot find module 'webpack-cli/bin/config-yargs'
  "devDependencies": {
    "html-webpack-plugin": "^4.5.0",
    "webpack": "^5.1.0",
    "webpack-cli": "^4.0.0"
  }
This solution doesn't work in my case.
"start": "webpack-dev-server --mode development --open" 
->
"start": "webpack serve --mode development --open"

what can I do?

**Comment by bino98** [comment]
I am suffering from the same problem.

Apparently,

https://github.com/webpack/webpack-dev-server/blob/bbe410e6f257ae45e65ca97c708118c8d7ec01ce/bin/webpack-dev-server.js#L56-L62

This part is no longer compatible with webpack-cli@4.0.0.

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-cli/issues/1948
