### ISSUE TITLE
add compatible types with webpack@5

### ISSUE THREAD

**Issue by tiagolisalves** [webpack/webpack-dev-server#2776]
- Operating System: Ubuntu 18
- Node Version: 12.0.0
- NPM Version: 6.4.1
- webpack Version: 5.1.2
- webpack-dev-server Version: 3.8.1
- Browser: Chrome 79

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Starting with webpack@5 it's no longer needed to install @types/webpack [#10599](https://github.com/webpack/webpack/pull/10599). webpack-dev-server should have a types.d.ts file similar to the one on [DefinetelyTyped](https://www.npmjs.com/package/@types/webpack-dev-server). 

Currently if you try to used @types/webpack-dev-server@3.11.0 with webpack@5.1.3, you'll receive errors like:  

```ssh
// webpack.config.js
node_modules/@types/webpack-dev-server/index.d.ts:295:25 - error TS2694: Namespace 'exports' has no exported member 'Options'.

295         stats?: webpack.Options.Stats;
                            ~~~~~~~

node_modules/@types/webpack-dev-server/index.d.ts:340:32 - error TS2694: Namespace 'exports' has no exported member 'WatchOptions'.

340         watchOptions?: webpack.WatchOptions;
```

If we'd add types to this project, those incompatibilities should be adjusted as well.

**Comment by evilebottnawi** [comment]
We don't have types

**Comment by pvarga-dni** [comment]
@tiagolisalves Did you open a bug about this over at DefinitelyTyped? (Couldn't find one but don't want to make a dupe)
