### ISSUE TITLE
Console output with --no-info

### ISSUE THREAD

**Issue by mrakjos** [webpack/webpack-dev-server#278]
Webpack with this settings (noInfo: true) show only error messages:

![screen shot 2015-09-23 at 14 22 05](https://cloud.githubusercontent.com/assets/7734088/10044931/c883de88-61fe-11e5-846d-9107b8314f9c.png)

When is build module successful, this message stay on the display. This is little confusing.

It is possible clear console before every build?

**Comment by mcrawshaw** [comment]
+1

**Comment by krtr** [comment]
+1

**Comment by rimunroe** [comment]
I think a better option would be for it to provide some way of reporting on successful builds as well, but without dumping an enormous amount of info to the console. The reason I turn no info or quiet on is that the output on every build is a little overwhelming and usually not very useful. I think the ideal solution for me would be for webpack or the dev server to expose some api for attaching event handlers.

**Comment by valerybugakov** [comment]
+1

**Comment by FiNGAHOLiC** [comment]
+1

**Comment by SpaceK33z** [comment]
PR welcome.

**Comment by SpaceK33z** [comment]
This is actually a problem in webpack-dev-middleware. It supports a `reporter` option now, so you can build your own custom reporter that fixes this. If anyone is still interested, please make an issue at [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/issues).
