### ISSUE TITLE
Passing --env to webpack serve

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [webpack/webpack-dev-server#2782]
- Operating System: Windows 10
- Node Version: 12.16.3
- NPM Version: 6.14.4
- webpack Version: 5.1.3
- webpack-dev-server Version: 3.11.0
- Browser: n/a

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Now that webpack-dev-server must be invoked via `webpack serve`, it would be nice if `webpack serve` accepted `--env` flags, like `webpack-dev-server` used to. @mybrainishuge mentioned this in https://github.com/webpack/webpack-dev-server/issues/2759#issuecomment-706788555, and I think it's worth discussing.

As he said:

How are environment options passed to webpack serve when exporting a function in the webpack config? With `webpack-dev-server`, I passed environment variables:

```
webpack-dev-server --env.mode development
```

Passing the same argument to webpack serve errors:
```
[webpack-cli] Unknown argument: --env.mode
[webpack-cli] Unknown argument: development
```
I'm not seeing how to pass anything other than booleans to webpack serve, but I want to pass strings:
```
webpack serve --env mode
```

**Comment by snitin315** [comment]
@Bosch-Eli-Black  you can do `webpack serve --env mode=development`, for more info you can see https://github.com/webpack/webpack-cli/pull/1939

**Comment by evilebottnawi** [comment]
Answer above, plus it is out of scope webpack-dev-server

**Comment by Bosch-Eli-Black** [comment]
That worked. Thanks, @snitin315 ! 🙂
