### ISSUE TITLE
Webpack 5 dev server doesn't show detail error in overlay

### ISSUE THREAD

**Issue by xkelvinx666** [webpack/webpack-dev-server#2786]
# Bug report

the dev server doesn't show detail error in overlay in webpack 5

**What is the current behavior?**

the overlay message doesn't show the compiler error, maybe the error scheme change in webpack 5?
 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15306173/96970774-beec8e00-1546-11eb-974c-14d49496d06b.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/cvgellhorn/webpack-boilerplate
vi webpack.dev.js # add overlay in devServer
npm run dev
```

**What is the expected behavior?**

show the detail error like webpack4

**Other relevant information:**
webpack version:  5.2.0
Node.js version:  14.8.0
Operating System:  mac os 10.14.6
Additional tools: npm v6

**Comment by thormeier** [comment]
Just encountered the exact same and tracked it down to `client/overlay.js:L115`:

```js
function showMessage(messages) {
  ensureOverlayDivExists(function (div) {
    // Make it look similar to our terminal.
    div.innerHTML = "<span style=\"color: #".concat(colors.red, "\">Failed to compile.</span><br><br>").concat(ansiHTML(entities.encode(messages[0])));
  });
}
```

Inspecting the error messages shows that they are actually objects containing a `message` key. It's working when I change it to:

```
    div.innerHTML = "<span style=\"color: #".concat(colors.red, "\">Failed to compile.</span><br><br>").concat(ansiHTML(entities.encode(messages[0].message)));
```

**Comment by evilebottnawi** [comment]
Yes, but we need to keep compatibility with webpack@4, so need to check `messages[0].message? messages[0].message : messages[0]`

**Comment by xkelvinx666** [comment]
> Yes, but we need to keep compatibility with webpack@4, so need to check `messages[0].message? messages[0].message : messages[0]`

Would you plan to fix it?

**Comment by ckken** [comment]
Would you plan to fix it?

**Comment by snitin315** [comment]
I will send a fix.

**Comment by evilebottnawi** [comment]
Fixed in v4

**Comment by jimblue** [comment]
Hi @alexander-akait,
Is it possible to re open this issue as V4 isn't released yet.
Thank you 😄

**Comment by alexander-akait** [comment]
We already have the issue for v4

**Comment by jimblue** [comment]
ok great, thank you

**Comment by coderars** [comment]
Hmm.. Reading the above it should be ok/fixed in Webpack 5.26.1 (I'm using now), but I see "Failed to compile." only. Is it only for me?

**Comment by jimblue** [comment]
@coderars when @alexander-akait was telling above that **this issue will be fixed in V4**, he was talking about **webpack-dev-server V4**

**Comment by neemzy** [comment]
Is it supposed to be fixed in `webpack-dev-server@3`? I'm facing this issue right now.

**Comment by jimblue** [comment]
> Is it supposed to be fixed in `webpack-dev-server@3`? I'm facing this issue right now.

@neemzy  If you're using Webpack 5 you have to use webpack dev server with the latest beta version.

**Comment by jordanbtucker** [comment]
I agree with @neemzy. How about releasing the fix has a hotfix for v3 while everyone waits for v4 to get released?

**Comment by EvgenyLeukhin** [comment]
I think, this is not Webpack 5 problem, this is problem with version of `webpack-dev-server.`
You may try to install `"webpack-dev-server": "^4.0.0-beta.3"` to fix it.

**Comment by neemzy** [comment]
@EvgenyLeukhin I understand, but as I stated above, I don't see any good reason for encouraging people to use a beta version of the dev server with a stable version of Webpack rather than backporting the fix.
