### ISSUE TITLE
socket option is ignored if server not started via cli

### ISSUE THREAD

**Issue by Roang-zero1** [webpack/webpack-dev-server#2787]
- Operating System: Ubuntu 20.04
- Node Version: v14.14.0
- Yarn Version: 1.22.10
- webpack Version: 5.2.0
- webpack-clie Version: 4.1.0
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 86.0.4240.111

- [X] This is a **bug**
- [ ] This is a **modification** request

webpack-dev-server does not adhere to the socket option when not used via cli but imported via the `Server` library (e.g. webpack-cli).

### Code

Repository with minimal example code: https://github.com/Roang-zero1/webpack-dev-server-unix-socket-bug

### Expected Behavior

When using `yarn run serve` ("serve": "webpack serve") , the server should start and serve from `/var/run/webpack/webpack.sock`.

### Actual Behavior

When using `yarn run serve`, the server starts and serves from the default localhost:8000

### For Bugs; How can we reproduce the behavior?

1. Clone the https://github.com/Roang-zero1/webpack-dev-server-unix-socket-bug repository
1. Run `yarn install`
1. Use `yarn run serve` to start the server
1. Server is now available under localhost:8000

### Investigation

This behavior is caused by the following setup:

* In the client the socket option is correctly parsed: https://github.com/webpack/webpack-dev-server/blob/v3.11.0/bin/webpack-dev-server.js#L118-L140
* In the server options socket is listed https://github.com/webpack/webpack-dev-server/blob/v3.11.0/lib/options.json#L356-L358
* In the server the socket option is never parsed and only if the user passes the socket to the `server.listen` functions `port` parameter will it be adhered to (https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L774)

**Comment by Roang-zero1** [comment]
Further comment: The startup information incorrectly states that webpack-dev-server is listening on the socket:
```
ℹ ｢wds｣: Listening to socket at /var/run/webpack/webpack.sock
```

**Comment by evilebottnawi** [comment]
Sorry, socket was removed, don't use it, we need update docs

**Comment by Roang-zero1** [comment]
Ok that's disappointing, but thanks for the feedback.

**Comment by evilebottnawi** [comment]
@Roang-zero1 You can emulate this behavior using simple wrapper, using unix sockets is a problem on node :disappointed:

**Comment by Roang-zero1** [comment]
Yes probably, but I'd rather stick to official functions to reduce complexity.
