### ISSUE TITLE
--no-progress option doesn't disable progress output

### ISSUE THREAD

**Issue by jasonkarns** [webpack/webpack-dev-server#2790]
- Operating System: macos
- Node Version: v14.13.1
- NPM Version: 6.14.8
- webpack Version: 4.43.0 (via vue-cli)
- webpack-dev-server Version: 3.11.0 (via vue-cli)
- Browser: safari

- [x] This is a **bug**
- [x] This is a **modification** request

(Both because I'm not entirely sure if `--no-progress` is an option. Documentation indicates that `--progress` is a command line option, and that it is a boolean. Which implies `--no-progress` exists as the negation of said boolean.)

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

Expected the webpack compilation progress output to be omitted.

### Actual Behavior

Webpack compilation output continues to be printed.

### For Features; What is the motivation and/or use-case for the feature?

Many tools are built atop web-dev-server, (the various *-cli tools for different frameworks) and pass arguments through to wds unmodified. vue in particular seems to enable `--progress` by default. And since wds documents that option as a boolean, it stands to reason the negation would be `--no-progress`.

**Comment by evilebottnawi** [comment]
> For Bugs; How can we reproduce the behavior?

Do not ignore this. Why? Because I am starting ask questions and waste your and my time.

Do you have `ProfilePlugin`? Why you run it? What version you are use? What is options you have?

**Comment by evilebottnawi** [comment]
When you fixed the problems with issue I will reopen it.
