### ISSUE TITLE
security issue with node-forge before v0.10.0

### ISSUE THREAD

**Issue by alokissunny** [webpack/webpack-dev-server#2796]
- Operating System: windows 
- Node Version: 10.15.0
- NPM Version: 6.4.1
- webpack Version: 4:40.2
- webpack-dev-server Version: 3.11.0
- Browser: chrome

The package node-forge before 0.10.0 is vulnerable to Prototype Pollution via the util.setPath function. this is a in direct dependency. 

Its a security vulnerablity

**Comment by evilebottnawi** [comment]
Update your lock file, fixed for v4, release will be in near future
