### ISSUE TITLE
Feature request: allow custom overlay implemenetation

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack-dev-server#2800]
- Operating System: Not related
- Node Version: 14
- NPM Version: 6
- webpack Version: 4.44
- webpack-dev-server Version: 3.11
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Our environment doesn't work with the default overlay implementation. I hope if webpack-dev-server can add an API to let us define our own overlay.

For example, webpack-dev-server overlay runtime can try to use a global variable `$webpack_dev_server_custom_overlay$()` when a new message is going to show/discard.

**Comment by evilebottnawi** [comment]
> Our environment doesn't work with the default overlay implementation.

It should work.

**Comment by Jack-Works** [comment]
I'm using it to develop web extension. I believe it is not the normal case and not officially supported by WDS. If I can customize it, I can change it to work in my environment.

**Comment by evilebottnawi** [comment]
> I'm using it to develop web extension. I believe it is not the normal case and not officially supported by WDS. If I can customize it, I can change it to work in my environment.

Maybe we shouldn't increase options and create support issues in the future, but just fix compatibility with web extensions?

**Comment by Jack-Works** [comment]
Ok let me investigate that how to make it work later...

**Comment by Jack-Works** [comment]
The first problem is

```
Uncaught SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'chrome-extension:' is not allowed.
    at new SockJS (sockjs.js?9be2:683)
    at new SockJSClient (SockJSClient.js?0a33:43)
    at initWDSSocket (WDSSocket.js?b288:17)
    at Object.eval (ErrorOverlayEntry.js?e51d:76)
```

`resourceQuery` is `""` so `getSocketUrlParts` returns `/sockjs-node`. When it's passed to SockJS, it throwed because the parsed URL becomes `"chrome-extension://jkoeaghipilijlahjplgbfiocjhldnap/sockjs-node"`

**Comment by Jack-Works** [comment]
Oh wait, that code belongs to `@pmmmwh/react-refresh-webpack-plugin`

**Comment by Jack-Works** [comment]
moved to pmmmwh/react-refresh-webpack-plugin#238
