### ISSUE TITLE
Support webpack-dev-middleware ^4.0.0 for webpack 5

### ISSUE THREAD

**Issue by ranquild** [webpack/webpack-dev-server#2803]
Currently in master there is this dependency: 
```
"webpack-dev-middleware": "^3.7.2",
```
However, webpack 5 is supported in `webpack-dev-middleware` from `4.0.0` and above. Please update the dependency constraint so this package could be used with webpack 5.

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

This package can be used with webpack 5.

### Actual Behavior

This package cannot be used with webpack 5.

### For Features; What is the motivation and/or use-case for the feature?

To be used with webpack 5.

**Comment by evilebottnawi** [comment]
It was reported a lot of time, please use search, we are wokring on it
