### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by LP1994** [webpack/webpack-dev-server#2806]
- Operating System: Windows 10
- Node Version: 15.0.1
- NPM Version: 6.14.8
- webpack Version: 5.3.2
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome 86.0.4240.111

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
There is no such warning.

### Actual Behavior
The above warning appears.

### For Bugs; How can we reproduce the behavior?
This warning appears when the proxy has more than 10 websocket requests (ws: true).

### For Features; What is the motivation and/or use-case for the feature?
When the proxy has more than 10 websocket requests (ws: true).

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Fill out all fields.
