### ISSUE TITLE
webpack-dev-server 3.11.0 is not fully compatible to webpack 5

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack-dev-server#2807]
"webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".

Are there any plans to upgrade to webpack-dev-middleware@4 soon?

**Comment by csvan** [comment]
Seems like webpack-dev-middleware hit 4.0 which has full WP5 compatibility just 3 days ago, hopefully this will follow soon

https://github.com/webpack/webpack-dev-middleware/blob/master/CHANGELOG.md

**Comment by evilebottnawi** [comment]
Yes, we will focus on latest compatibility issues with webpack-dev-server on the next

**Comment by HomyeeKing** [comment]
> Yes, we will focus on latest compatibility issues with webpack-dev-server on the next

hurry up bro! guys waiting~~

**Comment by ckken** [comment]
hurry up bro! guys waiting~~

**Comment by csvan** [comment]
@HomyeeKing @ckken if you can't wait, helping out is always an option

**Comment by ylemkimon** [comment]
@HomyeeKing @ckken webpack is **an open-source software**, that is maintained by _volunteers_. Pushing them doesn't help. If you sincerely support the project, contribute by [sponsoring](https://opencollective.com/webpack) or [opening a pull request](https://github.com/webpack/webpack-dev-server/blob/master/CONTRIBUTING.md). Furthermore, please use gender-neutral language, not "bro" or "guys".

**Comment by evilebottnawi** [comment]
webpack-dev-middleware@4 was released with full compatibility with webpack@5, next is webpack-dev-server

**Comment by jantimon** [comment]
Thanks a lot for all your work 👍

**Comment by csvan** [comment]
@evilebottnawi amazing work!

**Comment by HomyeeKing** [comment]
> @HomyeeKing @ckken webpack is **an open-source software**, that is maintained by _volunteers_. Pushing them never helps. If you sincerely support the project, contribute by [sponsoring](https://opencollective.com/webpack) or [opening a pull request](https://github.com/webpack/webpack-dev-server/blob/master/CONTRIBUTING.md). Furthermore, please use gender-neutral language, not "bro" or "guys".

you take this too much, I'm not the tone you thought , just an **EASY HUMOROUS** way...  , not pushing 

I'd like to help out, but I am not that level for now, I'm working to reach that level, I respect all the excellent engineer, 

so @evilebottnawi take a break bro, guys can wait   💆‍♂️💆‍♂️💆‍♂️

**Comment by csvan** [comment]
@evilebottnawi can I help with anything here?

**Comment by bluepeter** [comment]
Love to get this one wrapped up 👍

**Comment by evilebottnawi** [comment]
@csvan yep, sorry for delay, we need update deps and fix tests for v4 branch

**Comment by csvan** [comment]
@evilebottnawi no worries, thanks for all your hard work <3 Let me know if I can assist in any way

**Comment by evilebottnawi** [comment]
You can help us with this, just clone repo, switch on v4, install deps and run them, then start to fix tests, some PRs with fixes already sent

**Comment by ylemkimon** [comment]
@evilebottnawi Is there a WIP PR, or can I start from scratch?

**Comment by evilebottnawi** [comment]
v4 branch

**Comment by evilebottnawi** [comment]
Let's close, it is fixed, hope we will do release on this week

**Comment by csvan** [comment]
Awesome work @evilebottnawi and @ylemkimon ❤️

**Comment by bevacqua** [comment]
@evilebottnawi Any luck with releasing this soon? 🙇 Appreciate the work here

**Comment by evilebottnawi** [comment]
ETA is this week, I am working with two hands

**Comment by csvan** [comment]
Woop!!

https://github.com/webpack/webpack-dev-server/compare/v3.11.0...v4.0.0-beta.0
