### ISSUE TITLE
Please stop spam, we known about the problem and we provide solution above, we need additional try/catch in our bin and provide friendly error

### ISSUE THREAD

**Issue by cyberpunk1971** [webpack/webpack-dev-server#2808]
Please stop spam, we known about the problem and we provide solution above, we need additional try/catch in our bin and provide friendly error

_Originally posted by @evilebottnawi in https://github.com/webpack/webpack-dev-server/issues/2759#issuecomment-708519289_

**Comment by cyberpunk1971** [comment]
What solution. You say it's above but there are a lot of answers. Btw, none of them worked for me.

**Comment by evilebottnawi** [comment]
Using `webpack serve`
