### ISSUE TITLE
Can't find the changelog

### ISSUE THREAD

**Issue by alexilyaev** [webpack/webpack-dev-server#281]
I can't find the changelog for this repo, and there's nothing in the docs as well.

**Comment by SpaceK33z** [comment]
That's because there is no changelog ;). You can read the commits between releases relatively easy.

**Comment by alexilyaev** [comment]
Hmm, any chance we would have a changelog? :-)

**Comment by SpaceK33z** [comment]
There is a [changelog](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md) now :).

**Comment by govorov** [comment]
Seems like the changelog is gone again.

**Comment by sontek** [comment]
ChangeLog is definitely gone again.

**Comment by shellscape** [comment]
Please see the [releases](https://github.com/webpack/webpack-dev-server/releases)
