### ISSUE TITLE
Usage With NPM Scripts modify "serve": "webpack serve"

### ISSUE THREAD

**Issue by blackraccoon000** [webpack/webpack-dev-server#2813]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// README.md
"scripts": {
  "start:dev": "webpack-dev-server"
}
```

```js
// modify code
Case:webpack-cli 3
package.json

{
  "scripts": {
    "serve": "webpack-dev-server"
  },
  "devDependencies": {
    "webpack-cli": "^3.3.12"
  }
}

Case:webpack-cli 4
package.json

{
  "scripts": {
    "serve": "webpack serve"
  },
  "devDependencies": {
    "webpack-cli": "^4.0.0"
  }
}

```

### For Features; What is the motivation and/or use-case for the feature?
Beginners get confused by the guide when using webpack-dev-sercer.
This change can reduce the burden on the answer.

https://github.com/webpack/webpack-cli/issues/1948
https://github.com/webpack/webpack-dev-server/issues/2029#issuecomment-707034614

**Comment by anshumanv** [comment]
yep, will update

**Comment by alexander-akait** [comment]
Fixed
