### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by LP1994** [webpack/webpack-dev-server#2816]
- Operating System:
- Node Version: 15.1.0
- NPM Version: 6.14.8
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome V86.0.4240.183 X64

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
When there are more than 11 websocket agents, the following warning will not appear:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit.

### Actual Behavior
When there are more than 11 websocket agents, the following warning appears:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit.

### For Bugs; How can we reproduce the behavior?
Here is the main code:

module.exports = {
    // other codes
    devServer: {
        // other codes
        proxy: {
            // The warning mentioned above will appear when the following example code appears more than 11 times.
            '/ws4DevURL8081A/subscriptions': {
                pathRewrite: ( path, req ) => '/subscriptions',

                target: 'ws://192.168.1.168:8081',
                ws: true,
                secure: false,
                changeOrigin: true,
            },

            // such as:
            '/ws4DevURL8082A/subscriptions': {
                pathRewrite: ( path, req ) => '/subscriptions',

                target: 'ws://192.168.1.168:8082',
                ws: true,
                secure: false,
                changeOrigin: true,
            },
            '/ws4DevURL8083A/subscriptions': {
                pathRewrite: ( path, req ) => '/subscriptions',

                target: 'ws://192.168.1.168:8083',
                ws: true,
                secure: false,
                changeOrigin: true,
            },
            '/ws4DevURL8084A/subscriptions': {
                pathRewrite: ( path, req ) => '/subscriptions',

                target: 'ws://192.168.1.168:8084',
                ws: true,
                secure: false,
                changeOrigin: true,
            },
            // ......
        },
    },
};

### For Features; What is the motivation and/or use-case for the feature?
Use cases are on top.

**Comment by LP1994** [comment]
This is just a warning from nodejs, and I want to know how to make it not issue this warning when meeting the requirements.
What I need is: set up more than 11 websocket agents!!!

**Comment by evilebottnawi** [comment]
Nothing, it is warning from `http-proxy-middleware`, setup more listener in own config

**Comment by LP1994** [comment]
> Nothing, it is warning from `http-proxy-middleware`, setup more listener in own config

OK.
