### ISSUE TITLE
Dependency has package with known vulnerability

### ISSUE THREAD

**Issue by Ivan-Strahovsky** [webpack/webpack-dev-server#2819]
- Operating System:
MacOS
- Node Version:
v12.14.0
- NPM Version:
6.14.4
- webpack Version:
4.44.2
- webpack-dev-server Version:
3.11.0
- Browser:

- [ ] This is a **bug**
- [ x] This is a **modification** request

### Code
Just perform `npm i` or `npm audit` with webpack-dev-server as a dependency.

### Expected Behavior
No vulnerabilities reported by `npm audit`

### Actual Behavior
Npm audit find high severity issue.
 High                  │  Prototype Pollution in node-forge 
 Package            │  node-forge    
 Dependency of │  webpack-dev-server [dev] 
 Path                   │  webpack-dev-server > selfsigned > node-forge 
 More info           │  https://npmjs.com/advisories/1561

### For Features; What is the motivation and/or use-case for the feature?
To fix get rid of known secuity issue.

**Comment by evilebottnawi** [comment]
Update you lock file
