### ISSUE TITLE
Issues with Yarn2 PNP / Webpack V5 / rebuild loop

### ISSUE THREAD

**Issue by grbd** [webpack/webpack-dev-server#2820]
- Operating System: Windows 10
- Node Version: v14.13.1
- NPM Version: 6.14.4
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0
- Browser: Firefox (although not used here)

- [ X] This is a **bug**
- [ ] This is a **modification** request

Hi,
I've noticed that when using Yarn V2 (PNP) and Webpack V5 in combination
causes webpack-dev-server to go into a rebuild loop.

  * yarn v2 pnp / webpack v4 (with pnp plugin) - works fine
  * yarn v2 pnp / webpack v5 - goes into a loop
  * yarn v1 no pnp / webpack v5 - works fine

This might be related to https://github.com/webpack/webpack-dev-server/issues/2807
I'm not sure, should be interesting to see what happens when this is updated

Note I've been using the command "webpack serve --mode development --env development"
instead of "webpack-dev-server" which fixes the issue with the latest webpack-cli

```
i ｢wdm｣: Compiling...
i ｢wdm｣: assets by status 5.79 MiB [cached] 1 asset
cached modules 3.78 MiB (javascript) 24.8 KiB (runtime) [cached] 416 modules
webpack 5.4.0 compiled successfully in 191 ms
i ｢wdm｣: Compiled successfully.
No issues found.
i ｢wdm｣: Compiling...
i ｢wdm｣: assets by status 5.79 MiB [cached] 1 asset
cached modules 3.78 MiB (javascript) 24.8 KiB (runtime) [cached] 416 modules
webpack 5.4.0 compiled successfully in 172 ms
i ｢wdm｣: Compiled successfully.
No issues found.
i ｢wdm｣: Compiling...
i ｢wdm｣: assets by status 5.79 MiB [cached] 1 asset
cached modules 3.78 MiB (javascript) 24.8 KiB (runtime) [cached] 416 modules
webpack 5.4.0 compiled successfully in 173 ms
i ｢wdm｣: Compiled successfully.
```

**Comment by evilebottnawi** [comment]
Please provide reproducible test repo

**Comment by grbd** [comment]
Ok put one up here
https://github.com/Hecatron/Example.WebpackDevserver1

**Comment by evilebottnawi** [comment]
Sorry for delay, I will look at this tomorrow

**Comment by alexander-akait** [comment]
No problems with webpack or webpack-dev-server, just comment `ForkTsCheckerWebpackPlugin` and no problems, spent 1 hour on debug :disappointed: , please try latest version of https://github.com/TypeStrong/fork-ts-checker-webpack-plugin, locally fixed the problem, of you still ahve the problem , please open an issue in `fork-ts-checker-webpack-plugin` repo, thanks

**Comment by grbd** [comment]
Cool thanks for looking into this
I can confirm as soon as I upgraded from 6.0.0 to 6.0.5 for fork-ts-checker-webpack-plugin it fixed it
sorry I would have raised the issue there if I'd known but figuring that one out was beyond my abilities
