### ISSUE TITLE
Broken symlink crashes webpack-dev-server

### ISSUE THREAD

**Issue by last-partizan** [webpack/webpack-dev-server#2821]
- Operating System: Linux
- Node Version: v15.1.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- webpack-dev-server Version: 3.11.0
- Browser: None

- [x] This is a **bug**
- [ ] This is a **modification** request

### Description
I have broken symlink in my home directory, `~/.steampath`, and somehow webpack-dev-server on build error tries to access it and crashes with following exception:

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'nonexistent' in '/home/serg/test-build/src'
 @ ./src/index.js 1:0-20
ℹ ｢wdm｣: Failed to compile.
node:internal/process/promises:199
        triggerUncaughtException(err, true /* fromPromise */);
        ^

[Error: ENOENT: no such file or directory, stat '/home/serg/.steampath'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/serg/.steampath'
}
```
I was thinking something tries to steal my steam account, but looks like it crashes on any broken link.

### Expected Behavior
- It should not crash;
- It should not scan files inside my home directory.

### Actual Behavior
- It crashes.
- It scans files in my home directory.

### For Bugs; How can we reproduce the behavior?

For reproduction, do this:

```sh
mkdir -p test-crash/src; cd test-crash;
echo 'import "nonexistent"' > src/index.js
ln -s ~/nonexistent-path ~/broken-symlink
yarn add webpack@4 webpack-cli@3 webpack-dev-server
NODE_OPTIONS='--unhandled-rejections=strict --trace-warnings' yarn webpack-dev-server
```

If you testing this in `/tmp`, create broken symlink in `/tmp`, looks like it scans not home, but any parent directory.

Note: on webpack 5 with `webpack serve` this bug is not present.

**Comment by evilebottnawi** [comment]
> Note: on webpack 5 with webpack serve this bug is not present.

Because it was bug on webpack side too, unfortunately we can't fix it in v4, my recommendation - update webpack to latest version, sorry
