### ISSUE TITLE
Security Vulnerability in Dependency (sockjs)

### ISSUE THREAD

**Issue by morozr** [webpack/webpack-dev-server#2825]
- Operating System: Windows 10
- Node Version: 12.16.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- webpack-dev-server Version: 3.11.0
- Browser: Chrome 86.0.4240.111

- [x] This is a **bug**
- [ ] This is a **modification** request

A recent security scan run on a product I am working on detected a vulnerability in one of the dependencies used by webpack-dev-server. The scan indicated that  webpack-dev-server/3.11.0 uses sockjs/0.3.20 which contains a security vulnerability in faye-websocket. The most recent version of sockjs (0.3.21) fixes this issue. Would it be possible to update the dependency to use sockjs version 0.3.21?

**Comment by evilebottnawi** [comment]
Fixed in v4, release will be soon
