### ISSUE TITLE
**Facing issues when try to use 'webpack-cli' version upper than 3.3.8**

### ISSUE THREAD

**Issue by nikiqta** [webpack/webpack-dev-server#2826]
**Facing issues when try to use 'webpack-cli' version upper than 3.3.8**

Hello, everyone

- Operating System: Windows
- Node Version: 12.16.1
- NPM Version: 
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0
- 'webpack-cli': 4.2.0
- Browser: Chrome

I have a launch configuration that use this setting:

![image](https://user-images.githubusercontent.com/33606495/98807032-bd660580-2422-11eb-8888-9bd0e69d2eb3.png)

And package.json file with:
![image](https://user-images.githubusercontent.com/33606495/98807101-d5d62000-2422-11eb-9765-5a9e75657a11.png)

But now when trying to build my devServer I get the following error:

![image](https://user-images.githubusercontent.com/33606495/98807373-38c7b700-2423-11eb-8dfd-6cc8d36b7299.png)

I did check in the node_modules and found that the structure of webpack-cli has changed.

![image](https://user-images.githubusercontent.com/33606495/98807573-83e1ca00-2423-11eb-9162-9446461829dc.png)

And there is no longer the old path available -> webpack-cli/bin/config-yargs OR webpack-cli/bin/config/config-yargs

Could you tell me If I can use something alternative or I should stay on webpack-cli version of 3.3.8
![image](https://user-images.githubusercontent.com/33606495/98807978-2601b200-2424-11eb-917b-59a4eb93a1fa.png)

Thanks in advance

**Comment by evilebottnawi** [comment]
Please use search, migrate on `webpack serve` command, you need to install webpack-cli for this

**Comment by evilebottnawi** [comment]
Never use path to bin, it is unsafe and can be changed in any time

**Comment by nikiqta** [comment]
Okay thanks, a lot.
