### ISSUE TITLE
browserslist lead to live reloading & HMR stop working

### ISSUE THREAD

**Issue by Clloz** [webpack/webpack-dev-server#2829]
- Operating System: macOS 10.15.3
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0
- webpack-cli Version: 4.2.0
- Browser: Chrome Version 86.0.4240.198 (Official Build) (x86_64)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports = {
    entry: entry,
    output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].js',
    },
    mode: 'development',
    module: {
        rules: [...],
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new CleanWebpackPlugin(),
        new FriendlyErrorsWebpackPlugin(),
    ].concat(htmlWebpackPlugins),
    devServer: {
        contentBase: './dist',
        hot: true,
        stats: 'errors-only',
    },
    devtool: 'source-map',
};
```

### Expected Behavior
After starting the dev server, hot module replacement & live reloading should work for all JS and CSS files from all webpack entries.

### Actual Behavior
if the project's root dictionary has a `.browserslistrc` or package.json has a `browserslist` field, HMR & live reloading will not work, Compiled successfully, but I have to refresh the browser page manually to see the change. When I delete the `.browserslistrc` and `browserslist` in package.json, It works well.

**Comment by evilebottnawi** [comment]
Already reported, please use search

**Comment by raiskila** [comment]
Can't find any recent open issue with the search query "live reloading". Is the relevant issue really the one from 2019?

**Comment by raiskila** [comment]
Apparently it's #2758
