### ISSUE TITLE
Added webpack/hot/dev-server.js to the end of file ruin umd packages while developing

### ISSUE THREAD

**Issue by EloB** [webpack/webpack-dev-server#2831]
- Operating System: Windows 10
- Node Version: v14.15.0
- Yarn Version: 1.22.10
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
{
  entry: './src/node.js',
  output: {
    libraryTarget: "umd",
    writeToDisk: true
  },
  devServer: {
    hot: true
  }
}
```

In my outputted file I get this and you see that node_modules/webpack/hot/dev-server.js is returned instead of my package because of node_modules/webpack/hot/dev-server.js is added to the end of entry.
```js
/************************************************************************/
/******/ 	// module cache are used so entry inlining is disabled
/******/ 	// startup
/******/ 	// Load entry module and return exports
/******/ 	__webpack_require__(__webpack_require__.s = "./src/node.js");
/******/ 	return __webpack_require__(__webpack_require__.s = "../../node_modules/webpack/hot/dev-server.js");
```

### Expected Behavior
I expect that `node_modules/webpack/hot/dev-server.js` isn't added as  the last entry because it breaks umd packages while developing.

### Actual Behavior
I expect src/node to be the last entry so I can export things from my file.

**Comment by ylemkimon** [comment]
Possible duplicate of #2484.

**Comment by EloB** [comment]
@ylemkimon I love you!
