### ISSUE TITLE
Possibility to mute Browser console and terminal console logs but still having the progress or others

### ISSUE THREAD

**Issue by joacub** [webpack/webpack-dev-server#2833]
Possibility to mute Browser console and terminal console logs but still having the progress or others events in the client and in the terminal. to use in other integrations different to default console outputs or terminal outputs.

Thanks.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
