### ISSUE TITLE
Cannot read property 'length' of undefined during npm install

### ISSUE THREAD

**Issue by Zerotask** [webpack/webpack-dev-server#2851]
## THIS IS A NPM ERROR
**Temporary solutions:**
- Use `--legacy-peer-deps`
- Use Node.js 14.x / NPM 6.x

## Initial Issue

- Operating System: Windows 10 64bit
- Node Version: 15.2.1
- NPM Version: 7.0.8
- webpack Version: 5.6.0
- webpack-dev-server Version: (latest)
- Browser: -

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
I want to install webpack-dev-server with: `npm i -D webpack-dev-server`

### Expected Behavior
Succesful installation without any errors.

### Actual Behavior
I receive an error during installation.
```
npm ERR! code ERESOLVE
npm ERR! Cannot read property 'length' of undefined
```

[2020-11-21T14_49_45_952Z-debug.log](https://github.com/webpack/webpack-dev-server/files/5577801/2020-11-21T14_49_45_952Z-debug.log)

### For Bugs; How can we reproduce the behavior?
Create a new folder, run `npm i -D webpack webpack-cli webpack-dev-server`

I can install webpack and webpack-cli without errors.

**Comment by stephanmantler** [comment]
Seeing the same issue on macOS.
Node 15.2.1
npm 7.0.10
webpack 5.6.0

[2020-11-22T15_22_46_154Z-debug.log](https://github.com/webpack/webpack-dev-server/files/5579731/2020-11-22T15_22_46_154Z-debug.log)

**Comment by stephanmantler** [comment]
Probably related: npm/cli#1749

And indeed, `--legacy-peer-deps` allows webpack-dev-server to be installed.

**Comment by evilebottnawi** [comment]
Yes, it is npm bug

**Comment by evilebottnawi** [comment]
Not sure how we can fix it on our side

**Comment by isaacguerreir** [comment]
I have the same issue, I downgrade my node version 14.15.1 using [nvm](https://github.com/nvm-sh/nvm) and worked. This is not a solution, but can help if someone don't know that to do.

**Comment by evilebottnawi** [comment]
Please open an issue again in `npm`, their latest innovations are just crazy, a lot of regressions, even it is require `--legacy-peer-deps` they should provide friendly error, not like `Cannot read property 'length' of undefined`, we can't fix something here, even you will write `+1` or `same here` will not allow to solve the issue

**Comment by Zerotask** [comment]
I updated my initial post to provide temporary solutions for others who will search for this error.

**Comment by Ameensam1** [comment]
This fixed it for me for now at least : npm i --save-dev webpack-dev-server  --legacy-peer-deps

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0
