### ISSUE TITLE
NPM v7 needs webpack-dev-middleware@^4 - peerDep webpack v5

### ISSUE THREAD

**Issue by martinoppitz** [webpack/webpack-dev-server#2852]
![image](https://user-images.githubusercontent.com/6279703/99886234-2b88a480-2c3b-11eb-8431-b8c08afe377b.png)

https://github.com/leanupjs/leanup/issues/35

node ^15
npm ^7
win ^10

**Comment by csvan** [comment]
This is probably a problem in npm7, I have seen the same thing in other packages: https://github.com/npm/cli/issues/2120

**Comment by evilebottnawi** [comment]
And please use search before posting issue, it was already reporeted

**Comment by evilebottnawi** [comment]
And release will be on this week

**Comment by micheilsgrey** [comment]
and i still have a similar issue

**Comment by csvan** [comment]
@micheilsgrey are you using v4 beta?
