### ISSUE TITLE
Upgrade yargs peer dependency to v16 to remediate prototype pollution vulnerability issue

### ISSUE THREAD

**Issue by jjloneman** [webpack/webpack-dev-server#2854]
- Operating System: **macOS Catalina (10.15.7)**
- Node Version: **15.2.1**
- NPM Version: **7.0.12**
- webpack Version: **4.44.2**
- webpack-dev-server Version: **3.11.0**
- Browser: **Chrome 87**

- [x] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior

No vulnerability issues.

### Actual Behavior

Vulnerability issues.

### For Bugs; How can we reproduce the behavior?

```
$ npx snyk test webpack-dev-server

Testing webpack-dev-server...

✗ High severity vulnerability found in y18n
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/SNYK-JS-Y18N-1021887
  Introduced through: yargs@13.3.2
  From: yargs@13.3.2 > y18n@4.0.0



Organization:      jjloneman
Package manager:   npm
Open source:       yes
Project path:      webpack-dev-server

Tested webpack-dev-server for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.
```

### For Features; What is the motivation and/or use-case for the feature?

**webpack-dev-server@3.11.0** has a peer dependency on **yargs@13.3.2** which pulls in **y18n@4.0.0** which is subject to prototype pollution - a high severity vulnerability which is reported in https://snyk.io/test/npm/webpack-dev-server/3.11.0.

The automatic enterprise dependency management tool that I use at work, when trying to request **react-scripts@4.0.1**, rejected my request due to **react-script**'s peer dependency on this version of **webpack-dev-server** which transitively pulls in the vulnerable **y18n** library (https://snyk.io/test/npm/react-scripts/4.0.1)

**webpack-dev-server** vulnerability report:

> ## Prototype Pollution
> Vulnerable module: y18n
> * **Introduced through:** yargs@13.3.2
> ### Detailed paths
> * **Introduced through:** webpack-dev-server@3.11.0 › yargs@13.3.2 › y18n@4.0.0
> Remediation: Upgrade to yargs@16.0.0.

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0, please try and put feedback
