### ISSUE TITLE
Add garbage collector support

### ISSUE THREAD

**Issue by nhayun** [webpack/webpack-dev-server#2860]
Is there a way to run with garbage collector enabled? 
I want to run this piece of code on my server:
```
try {
	if (global.gc) {
		global.gc();
	}
} catch (e) {
	process.exit();
}
```
Something like 'npm run dev --expose-gc'?
Seems like the command above doesn't work.

I am using the library in Node JS version v14.15.1 - NPM version 6.14.8

**Comment by evilebottnawi** [comment]
out of scope webpack-dev-server
