### ISSUE TITLE
contentBase property deprecated?

### ISSUE THREAD

**Issue by johnrichardrinehart** [webpack/webpack-dev-server#2866]
- Operating System: Ubuntu 20.10
- Node Version: v15.3.0
- NPM Version: 7.0.14 (but I'm using `yarn berry`) 
- webpack Version:  5.7.0 (CLI version 4.2.0)
- webpack-dev-server Version:  https://github.com/webpack/webpack-dev-server.git#v4  (ecf2fe1800814daf963a868a2b6ec2b79b8f2f35)
- Browser: Chrome (but I'm not at the execution stage, only the compilation stage)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: "production",
  entry: ["./src/index.js"],
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000,
    hot: true,
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/i,
        use: {
          loader: "html-loader",
        },
      },
    ]
  },
  plugins: [new HtmlWebpackPlugin({
    template: "./public/index.html",
    filename: "./index.html",
  })],
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'index_bundle.js'
  },
};
```

```js
// additional code, remove if not needed.
```

### Expected Behavior
The dev server would read the code in `dist` and hot/live reload as necessary.

### Actual Behavior
The compiler breaks with the following stack trace.

https://gist.github.com/johnrichardrinehart/c8ec6ab1e60f39fc3b8dc738db649ec0

### For Bugs; How can we reproduce the behavior?

Make a `package.json` look like the below, install `yarn berry` and run `yarn run serve` with some files in `src` and `public`.

```json
{
  "name": "app",
  "scripts": {
    "serve": "yarn run webpack serve",
    "build": "yarn run webpack --config webpack.config.js"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "babel-loader": "^8.2.1",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "next",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "webpack": "^5.7.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "https://github.com/webpack/webpack-dev-server.git#v4"
  },
  "private": true
}
```

**Comment by johnrichardrinehart** [comment]
It looks like `contentBase` got [replaced with `static`](https://github.com/webpack/webpack-dev-server/commit/19b793ff5ade1d720d66820136dd6a04443d8fd5). Is that right? 

By changing the `contentBase` property to `static` the server is running fine, now.

**Comment by alexander-akait** [comment]
Yes, now it is `static` (with a lot of features) we will update docs after release

**Comment by johnrichardrinehart** [comment]
@alexander-akait For sure. Thanks for the ping. Do you have an estimated release date that I might circle back and update my `package.json` to base off `master` (say, 2 months)?

**Comment by alexander-akait** [comment]
Today we will do `webpack-dev-server@4-beta.1`

**Comment by alexander-akait** [comment]
We have couple breaking changes, but they are not big, so `webpack-dev-server@4-beta.1` was stable for use

**Comment by johnrichardrinehart** [comment]
I'm using the `static` property, now. When will this code be merged into `master`/`main`?

**Comment by alexander-akait** [comment]
Today we will do merge

**Comment by johnrichardrinehart** [comment]
Ah, I see. Thanks!
