### ISSUE TITLE
v4.0.0-beta.0: Observations. Notes about incorrect configuration documentation and suggestions.

### ISSUE THREAD

**Issue by kroko** [webpack/webpack-dev-server#2875]
- Operating System: macOS 10.15.7 (19H2)
- Node Version: v14.15.1
- NPM Version: 6.14.9
- webpack Version: 5.9.0
- webpack-dev-server Version: v4.0.0-beta.0 (actually, master branch at <https://github.com/webpack/webpack-dev-server/commit/910133d0a2383823504b3a0c2fd21b5a86e733a4>)
- webpack-cli Version: 4.2.0
- Browser: Chrome 87.0.4280.67

- [ ] This is a **bug**
- [x] This is a **modification** request

#### Case 1

According to [v4.0.0-beta.0 changelog](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0)

> the disableHostCheck and allowedHosts options were removed in favor of the firewall option

and configuration is given as beeing under `dev` key

```javascript
module.exports = {
  // ...
  devServer: {
    dev: {
      // Can be
      // firewall: ['192.168.0.1', 'domain.com']
      firewall: false,
    },
  },
};
```

#### Case 2

`headers` currently can be both specified in `devServer` and `devServer.dev`, seemingly having the same effect. For example.

```javascript
module.exports = {
  // ...
  devServer: {
    dev: {
      headers: {
        'Access-Control-Allow-Origin': '*'
      },
    },
  },
};
```

```javascript
module.exports = {
  // ...
  devServer: {
    headers: {
      'Access-Control-Allow-Origin': '*'
    },
  },
};
```

#### Case 1

Specifying `firewall` under `dev` will not work and throw.

```
Invalid options object. Dev Middleware has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'firewall'. These properties are valid:
   object { mimeTypes?, writeToDisk?, methods?, headers?, publicPath?, serverSideRender?, outputFileSystem?, index? }
```

and rightly so, as [webpack-dev-middleware lacks such key](https://github.com/webpack/webpack-dev-middleware).

Specifying it under `devServer` key has expected effect

```javascript
module.exports = {
  // ...
  devServer: {
    firewall: ['.test', 'localhost'],
  },
};
```

#### Case 2

Is there a _hidden_ reason to be able to specify `headers` in two places? If not suggestion is to remove it from `devServer` key and allow `headers` only in `devServer.dev` as [webpack-dev-middleware option](https://github.com/webpack/webpack-dev-middleware#headers).

### For Bugs; How can we reproduce the behavior?

See actual behaviour.

### For Features; What is the motivation and/or use-case for the feature?

* To have clean configuration when v4 comes out.
* To have correct documentation for configuration when v4 comes out.

**Comment by alexander-akait** [comment]
Because you can add headers on server level or for webpack assets (webpack-dev-middleware), it is for different cases, in 99% cases you don't need headers on webpack-dev-middleware

**Comment by alexander-akait** [comment]
I.e. `dev.headers` if you want to add headers for webpack assets, `headers` for any request to dev server
