### ISSUE TITLE
Add base url for server

### ISSUE THREAD

**Issue by SonofNun15** [webpack/webpack-dev-server#288]
Our SPA is located on a sub path underneath the host name. We use the `<base href="/subpath/">` tag to communicate this to the ui router.

All of our scripts are requested from this sub path folder because of this base tag. `<script type="text/javascript" src="assets/js/my-vendor-script.js"></script>` makes a request against `http://localhost:8080/subpath/assets/js/my-vendor-script.js"`, which fails because the dev server is hosting the file at `http://localhost:8080/assets/js/my-vendor-script.js`.

Can I set something on the webpack-dev-server that will cause it to host the content on child route instead of directly on hostname:port?

Would like to hit the index (and other content) at `http://localhost:8080/subpath/index.html` and etc.

**Comment by jedwards1211** [comment]
someone correct me if I'm wrong, but couldn't you just put `publicPath: '/subpath/assets/'` in your `devServer` config?

**Comment by SonofNun15** [comment]
I tried that and it appeared to only change where the JavaScript bundle was hosted.

**Comment by SonofNun15** [comment]
So if I set `publicPath: '/subpath/'` then I could load the bundle from `http://localhost:8080/subpath/bundle.js`, but the index and other static assets from contentBase would still be served at `http://localhost:8080/index.html`

**Comment by jedwards1211** [comment]
Perhaps have all of your static assets in a `subpath` folder inside your `contentBase`?

**Comment by SonofNun15** [comment]
Yeah that works pretty well. Not quite what I was hoping for, but a passable solution. Now I can't get the proxy option to work. :see_no_evil:

**Comment by SonofNun15** [comment]
Currently the only solution to this issue is putting the static assets in a sub folder under the contentBase. This is a workable solution. Any thoughts on providing a baseUrl property long term on the webpack-dev-server settings? Not worthwhile?

**Comment by finbarmaginn** [comment]
What is the easiest way to remove `webpack-dev-server/` from the url?

**Comment by SonofNun15** [comment]
@finbarmaginn: Add `--inline` to the command and you will be able to hit the server without `webpack-dev-server`

**Comment by grantcarthew** [comment]
I'm having trouble with this now. It's not stale.
Some way of defining the base url would be perfect.

**Comment by grantcarthew** [comment]
For reference: https://github.com/vuejs-templates/webpack/issues/546

**Comment by teledirigido** [comment]
As an option you can try using a middleware for BrowserSync: https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/pathRewrite.md

**Comment by grantcarthew** [comment]
That was a few years ago @teledirigido thanks. It's all good now in the Vue.js cli config.
