### ISSUE TITLE
Security Vulnerability flagged by Snyk in 3.11.0

### ISSUE THREAD

**Issue by apank** [webpack/webpack-dev-server#2884]
- Operating System: Linux
- Node Version: v14.4.0
- NPM Version: 6.14.5
- webpack Version: 5.1.3
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [X ] This is a **modification** request

### Code

A dependency in the yargs package y18n is causing a security vulnerability; would it be possible to bump yargs to 16
[https://snyk.io/test/npm/webpack-dev-server/3.11.0](https://snyk.io/test/npm/webpack-dev-server/3.11.0)

**Comment by hiroppy** [comment]
hmm how is the status of migration to webpack-cli? /cc @alexander-akait 
we want to remove yargs from this project...

**Comment by hiroppy** [comment]
Oops, I've caught up with this issue. we are going to release next version and yargs will be removed from this project. 
Thank you for issuing but please wait for a moment.
