### ISSUE TITLE
[beta] fix examples

### ISSUE THREAD

**Issue by hiroppy** [webpack/webpack-dev-server#2885]
- Operating System: osx
- Node Version: 12
- NPM Version: 6.14
- webpack Version: 5.9
- webpack-dev-server Version: beta
- Browser: N/A

- [x] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior

run examples on beta version.

### Actual Behavior

```
[webpack-cli] You need to install 'webpack-dev-server' for running 'webpack serve'.
Error: Cannot find module 'webpack-dev-server'
Require stack:
- /Users/hiroppy/webpack/webpack-dev-server/node_modules/@webpack-cli/serve/lib/index.js
- /Users/hiroppy/webpack/webpack-dev-server/node_modules/webpack-cli/lib/utils/package-exists.js
- /Users/hiroppy/webpack/webpack-dev-server/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/hiroppy/webpack/webpack-dev-server/node_modules/webpack-cli/lib/bootstrap.js
- /Users/hiroppy/webpack/webpack-dev-server/node_modules/webpack-cli/bin/cli.js
- /Users/hiroppy/webpack/webpack-dev-server/bin/webpack-dev-server.js
```

### For Bugs; How can we reproduce the behavior?

npm run webpack-dev-server

**Comment by hiroppy** [comment]
I checked this and this error occurs on webpack-cli side.

**Comment by shaodahong** [comment]
`yarn link` and `yarn link webpack-dev-server`

**Comment by hiroppy** [comment]
I've already tried npm link but I can't run this.

**Comment by hiroppy** [comment]
Resolved
