### ISSUE TITLE
v4.0.0-beta.0: clientLogLevel is removed without replacement

### ISSUE THREAD

**Issue by akphi** [webpack/webpack-dev-server#2887]
- Operating System: MacOS 11.0.1 (Big Sur)
- Node Version: 14.13.0
- NPM Version: 6.14.8
- Yarn version: 1.22.5
- webpack Version: 5.9.0
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: Chrome Version 87.0.4280.67

- [ ] This is a **bug**
- [x] This is a **modification** request

### Expected Behavior
In version 3, we can specify the `clientLogLevel` option to remove info logging from WDS directly to Chrome console.

### Actual Behavior
This option has been removed, and when I read the changelog, I tried to follow by setting `infrastructureLogging.level` to `none` as well as setting `stats.logging` to `none` but Chrome console still show messages like

```
[HMR] Waiting for update signal from WDS...
[webpack-dev-server] Hot Module Replacement enabled.
[webpack-dev-server] Live Reloading enabled.
[webpack-dev-server] App updated. Recompiling...
[webpack-dev-server] App updated. Recompiling...
[webpack-dev-server] Content base changed. Reloading...
Navigated to http://127.0.0.1:3000/ide
[HMR] Waiting for update signal from WDS...
[webpack-dev-server] Hot Module Replacement enabled.
[webpack-dev-server] Live Reloading enabled.
```

### For Features; What is the motivation and/or use-case for the feature?
Could we bring back a way to hide these noisy messages or at least show them as debug-level messages in Chrome?

**Comment by hiroppy** [comment]
Did you try to use `client.logging`?

**Comment by akphi** [comment]
@hiroppy my bad here for not checking for all the possible ways. I was trying to read the code and arrived at this.

Thank you, I'll close this now

**Comment by hiroppy** [comment]
No worries. I want to improve to respect `infrastructureLogging.level` when client.logging is empty.

**Comment by akphi** [comment]
@hiroppy that being said, are you aware of any way for us to customize the format of `infrastructureLogging`?

From the doc, there seems to be no way since infra logging is no in the stats object. but I would like to customize what I see in the terminal without having to do what `create-react-app` does which is to implement its own dev server client

**Comment by hiroppy** [comment]
at V3, you were able to customize a logger but from v4, we decided to use infrastructureLogging so you can't customize it.
see https://github.com/webpack/webpack/blob/master/lib/logging/createConsoleLogger.js

So... if you want to customize the logger, it's better to suggest this to webpack repo I think.
