### ISSUE TITLE
Please update `webpack-cli` to v4 and use `webpack serve` to run webpack-dev-server

### ISSUE THREAD

**Issue by Imprasna** [webpack/webpack-dev-server#2895]
Please update `webpack-cli` to v4 and use `webpack serve` to run webpack-dev-server

_Originally posted by @alexander-akait in https://github.com/webpack/webpack-dev-server/issues/2759#issuecomment-706753844_

**Comment by Imprasna** [comment]
My server is the latest V4.2 
but still, when I run (npm run start) I run into this error
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Can I get a solution to get this fixed please

**Comment by alexander-akait** [comment]
It means you still use old version of webpack-dev-server, I think you have globally installed webpack-dev-server, double check it
