### ISSUE TITLE
Silently ignores incorrect `path` and serves local filesystem instead

### ISSUE THREAD

**Issue by Danon** [webpack/webpack-dev-server#2899]
- Operating System: Windows 10
- Node Version: v14.5.0
- NPM Version: 6.14.5
- webpack Version: 4.44.2
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

Can't say

### Code

I used what now I know is incorrect webpack config, since I presume there can't be `".."` in the `output.path`.

```js
module.exports = (env, args) => ({
    entry: './index.jsx',
    output: {
        filename: '[name].[hash].js',
        publicPath: '/',
        path: __dirname + '/../bundle',
    },
```

This one however works as expected
```js
module.exports = (env, args) => ({
    entry: './index.jsx',
    output: {
        filename: '[name].[hash].js',
        publicPath: '/',
        path: require('path').resolve(__dirname, '..', 'bundle'),
    },
```

When I used the `__dirname + '/../bundle'` i didn't see the compiled template and minified JS and CSS. It simply served static files from the content root. I could see `localhost:8080/package.json` for example, and I saw `<%= =>` of HtmlWebpackPlugin in the `index.html`.

There was no error message, not failed build, everything looked normally, apart from the fact that the application didn't work.

When I opened http://localhost:8080/webpack-dev-sever to see what's going on I saw all the right files, but when I cliked on them, I got 404 `Cannot GET/435234655463456.js` for example.

### Expected Behavior

When using incorrect paths for `output.path` there should be a failed build or at least an error message.

### Actual Behavior

No info about invalid path whatsover, application served from devServer doesn't work.

### For Bugs; How can we reproduce the behavior?

Place the output folder outside of your content root (for example in `foo/bundle`, but source in `foo/src), and use a relative `__dirname + '/../bundle` path for your `output.path` in `webpack.config.js`. 

### For Features; What is the motivation and/or use-case for the feature?

I spent 35 minutes debugging.

**Comment by alexander-akait** [comment]
Sorry it is out of scope webpack-dev-server, it is valid to use `..` and many projects do it, I don't think there is problem with our code, you can open an issue in docs repo and improve it for debug

**Comment by Danon** [comment]
@alexander-akait Here's a reproducible demo: https://github.com/Danon/devServerBug

You're right, it's not about `..` in path, but it is about something. Can you take a look?
