### ISSUE TITLE
Silently ignores incorrect `path` and serves local filesystem instead

### ISSUE THREAD

**Issue by Danon** [webpack/webpack-dev-server#2901]
- Operating System: Windows 10
- Node Version: v14.5.0
- NPM Version: 6.14.5
- webpack Version: 4.44.2
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

Can't say

### Code

Here's a reproducible demo: https://github.com/Danon/devServerBug 
The instruction for reproduction are in `ReadMe.md`

### Expected Behavior

Webpack dev server works normally; or gives error message / fails the build if it can't.

### Actual Behavior

Webpack dev server doesn't work (doesn't serve files) without any error messages.

### For Bugs; How can we reproduce the behavior?

The instruction for reproduction are in `ReadMe.md` in reproducible demo: https://github.com/Danon/devServerBug 

### For Features; What is the motivation and/or use-case for the feature?

I spent 35 minutes debugging.

**Comment by alexander-akait** [comment]
Sorry it is out of scope webpack-dev-server, all paths are valid and we can't say what is wrong

**Comment by Danon** [comment]
@alexander-akait Where should I pose the issue then? Core webpack?

**Comment by alexander-akait** [comment]
There is nothing to fix, all paths is valid, you can send a PR to docs if something was misleading for you

**Comment by Danon** [comment]
@alexander-akait The paths are valid yet the application doesn't work as supposed to. The webpack doesn't serve the files.

**Comment by alexander-akait** [comment]
Because paths is wrong, but they are valid

**Comment by Danon** [comment]
I don't understand.

How come these are valid:
```
path = __dirname + 'bundle' // works
path = __dirname + '/bundle' // works
path = __dirname + '../bundle' // works
```
but this isn't:
```
path = __dirname + '/../bundle' // doesn't work
```

**Comment by alexander-akait** [comment]
You should:
- never use `+` for directories, please read `path.resolve`
- `__dirname + '/../bundle'` point to directory that is not exists, it is valid path, but invalid configuration
