### ISSUE TITLE
Hot Reloading does not work after Upgrade to Webpack5 and 4.0.0-beta.0

### ISSUE THREAD

**Issue by ajaybeniwal** [webpack/webpack-dev-server#2911]
- Operating System:MacOS
- Node Version:v12.13.0
- NPM Version:6.12.0
- webpack Version:5.10.0
- webpack-dev-server Version:4.0.0-beta.0
- Browser:Edge

- [ ] This is a **bug**
- [x ] This is a **modification** request

### Code

devServer: {
		port: 4006,
		static: [
			path.resolve(__dirname, 'dist'),
		],
		headers: {
			'Access-Control-Allow-Origin': '*',
		},
		firewall: false,
	},

```js
/* eslint-disable no-undef */
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin').CleanWebpackPlugin;
const { ContextReplacementPlugin } = require('webpack');
const supportedLocales = [
	'en',
	'en-gb',
	'ja',
	'fr',
	'de',
	'pl',
	'es',
	'it',
	'nl',
	'pt',
	'pt-br',
	'tr',
	'ru',
	'bg',
	'zh-cn',
	'ko',
];
module.exports = {
	entry: path.resolve(process.cwd(), `src/ui-components.js`),
	output: {
		path: path.resolve(process.cwd(), 'dist'),
		libraryTarget: 'system',
		filename: 'bundle.js',
		uniqueName: `ecp_components`,
		publicPath: "",
	},
	module: {
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: [/node_modules/],
				use: ['babel-loader'],
			},
			{
				test: /\.css$/,
				use: [
					'style-loader', // creates style nodes from JS strings
					'css-loader', // translates CSS into CommonJS
					'less-loader', // compiles Sass to CSS, using Node Sass by default
				],
			},
			{
				test: /\.less$/,
				use: [
					{
						loader: 'style-loader',
					},
					{
						loader: 'css-loader',
					},
					{
						loader: 'less-loader',
						options: {
							lessOptions: {
								modifyVars: {
									'font-family': 'proxima_novaregular',
								},
								javascriptEnabled: true,
							},
						},
					},
				],
			},
			{
				test: /\.(jpg|jpeg|png|gif|mp3|svg|eot|ttf|woff|woff2)$/,
				use: {
					loader: 'file-loader',
				},
			},
		],
	},
	externals: ['single-spa', 'react', 'moment', 'styled-components', 'lodash', 'react-dom', /^@ecp\/.*/],
	plugins: [
		new CleanWebpackPlugin(),
		new ContextReplacementPlugin(/moment[\/\\]locale$/, new RegExp(supportedLocales.join('|'))),
	],
};

```

```js
// additional code, remove if not needed.
```

### Expected Behavior
Hot Reloading should work after upgrade

[WDS] App updated. Recompiling...
reloadApp.js:19 [WDS] App hot update...
log.js:24 [HMR] Checking for updates on the server...

### Actual Behavior
Hot Reloading does not work after ugprade
WebsocketClient.js:42 WebSocket connection to 'ws://localhost:3000/ws' failed: Error during WebSocket handshake: Unexpected response code: 200
log.js:1 [webpack-dev-server] Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}

**Comment by ajaybeniwal** [comment]
The issue got fixed after adding host and port options inside the client option client: {
			host: "localhost",
			port: 4006,
		},

**Comment by ghiscoding** [comment]
@ajaybeniwal 
I have the same problem and I tried what you suggested but that doesn't seem to do anything on my side. Would you mind sharing your full `devServer` config? Is that the place where to put the `client` options into?

**Comment by WJB3** [comment]
> @ajaybeniwal
> I have the same problem and I tried what you suggested but that doesn't seem to do anything on my side. Would you mind sharing your full `devServer` config? Is that the place where to put the `client` options into?

I had the same problem

**Comment by WJB3** [comment]
> @ajaybeniwal
> I have the same problem and I tried what you suggested but that doesn't seem to do anything on my side. Would you mind sharing your full `devServer` config? Is that the place where to put the `client` options into?

Have you solved it yet? Looking forward to your reply

**Comment by ajaybeniwal** [comment]
@ghiscoding  @WJB3  yes i have solved this problem pls find my webpack file 

```
/* eslint-disable no-undef */
const merge = require('webpack-merge');
const path = require('path');
const common = require('./webpack.common.config.js');
const { NoEmitOnErrorsPlugin } = require('webpack');
module.exports = merge(common, {
	mode: 'development',
	devtool: 'inline-source-map',
	devServer: {
		port: 4006,
		static: [
			path.resolve(__dirname, 'dist'),
		],
		headers: {
			'Access-Control-Allow-Origin': '*',
		},
		firewall: false,
		client: {
			host: "localhost",
			port: 4006,
		},
	},
	plugins: [new NoEmitOnErrorsPlugin()],
});
```
