### ISSUE TITLE
webpack-dev-server v4 tries to inject into web workers 

### ISSUE THREAD

**Issue by sportshead** [webpack/webpack-dev-server#2916]
- Operating System: Windows 10 Version 1909
- Node Version: v12.19.0
- NPM Version: 6.14.8
- webpack Version: 5.10.0
- webpack-dev-server Version: 4.0.0-beta.0 
- Browser: Chrome 87.0.4280.88

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require("path");
const webpack = require("webpack");

const TerserPlugin = require("terser-webpack-plugin");
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
    mode: "development",
    entry: {
        "main": "./src/index.tsx",
        "editor.worker": "monaco-editor/esm/vs/editor/editor.worker.js",
    },
    plugins: [
        new webpack.ProgressPlugin(),
        new CopyPlugin({
            patterns: ["src/assets/index.html", "src/assets/favicon.svg"],
        }),
    ],

    module: {
        rules: [
            {
                test: /\.(ts|tsx)$/,
                loader: "ts-loader",
                include: [path.resolve(__dirname, "src")],
                exclude: [/node_modules/],
            },
            {
                test: /.(scss|css)$/,

                use: [
                    {
                        loader: "style-loader",
                    },
                    {
                        loader: "css-loader",

                        options: {
                            sourceMap: true,
                        },
                    },
                    {
                        loader: "sass-loader",

                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
            {
                test: /\.ttf$/,
                use: ["file-loader"],
            },
        ],
    },

    resolve: {
        extensions: [".tsx", ".ts", ".js"],
        alias: {
            swat: path.resolve(__dirname, 'src/')
        }
    },

    optimization: {
        minimizer: [new TerserPlugin()],

        splitChunks: {
            cacheGroups: {
                vendors: {
                    priority: -10,
                    test: /[\\/]node_modules[\\/]/,
                },
            },

            chunks: "async",
            minChunks: 1,
            minSize: 30000,
            name: false,
        },
    },

    output: {
        globalObject: "self",
        filename: "[name].bundle.js",
        path: path.resolve(__dirname, "dist"),
    },
};
```

### Expected Behavior
webpack-dev-server ignores workers (or provides a blob option to detect workers) and does not try to inject

### Actual Behavior
webpack-dev-server attempts to injects, which causes a `ReferenceError: window is not defined` error to be thrown

### For Bugs; How can we reproduce the behavior?
1. Load a web worker in your code
2. Start webpack-dev-server
3. Open http://127.0.0.1:8080/ or wherever
4. Observe how an error is thrown

**Comment by alexander-akait** [comment]
You need to manually disable hot for this chunk

**Comment by sportshead** [comment]
> You need to manually disable hot for this chunk

How does that work?

**Comment by sw1tchdev** [comment]
> You need to manually disable hot for this chunk

Also interesting, how do that. I need to disable injecting client code only for serviceWorker chunk

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack-dev-server/blob/v3.11.0/lib/options.json#L158 as function

**Comment by alexander-akait** [comment]
Anyway it is invalid, you need to use multi compiler mode with `target: 'webworker'`, other you can get broken code, for webpack@5 you can use `new Worker(new URL('./path/to.worker.ext'), import.meta.url)`

**Comment by sw1tchdev** [comment]
> https://github.com/webpack/webpack-dev-server/blob/v3.11.0/lib/options.json#L158 as function

I tried, but it's not help with specific entry, it's affect whole entries

> Anyway it is invalid, you need to use multi compiler mode with `target: 'webworker'`, other you can get broken code, for webpack@5 you can use `new Worker(new URL('./path/to.worker.ext', import.meta.url))`

I created config for multi compiler mode, and in `injectClient` i can specify compilation for target which is `webworker`. Thanks for help.

**Comment by alexander-akait** [comment]
Feel free to feedback, `web` and `webworker` targets are very different, you need always specify `target: ['webworker']` for webworker environment (using multi compiler mode) or use `new Worker(new URL('./path/to.worker.ext', import.meta.url))` (if you use `webpack` v5), otherwise webpack generate runtime code for `web` target and it will not work in webworker environment, in future we want to implement `target: ['universal']` so you can use code in any environment, i.e. `web`/`webworker`/`node`/etc, but it is hard task and we solve it around 70-80%, nothing to fix here
