### ISSUE TITLE
v4.0.0-beta.0 IE11 log.js error

### ISSUE THREAD

**Issue by davidspiess** [webpack/webpack-dev-server#2918]
- Operating System: Windows 10
- Node Version: 14.15.1
- NPM Version: 6.14.5
- webpack Version: 4.44.2
- webpack-dev-server Version: v4.0.0-beta.0
- Browser: IE11

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
{
  mode: "development",
  devServer: {
    static: path.resolve(__dirname, "public"),
    hot: "only",
    transportMode: "sockjs",
  },
  stats: "minimal",
}
```

### Expected Behavior

It works in IE11. I enabled `sock.js` transportMode.

### Actual Behavior

It throws an error in IE11 in the following file:

`'Symbol' is undefined`

`https://github.com/webpack/webpack-dev-server/blob/master/client-src/transpiled-modules/log.js`

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/2904, (name is some misleading)

**Comment by junhengDeng** [comment]
I have the same problem,

In the same version, webpack-dev-Server under IE11 will report that the Symbol is undefined

The following example can be reproduced

```
"@babel/core": "^7.12.10",
"@babel/preset-env": "^7.12.11",
"babel-loader": "^8.2.2",
"core-js": "^3.8.1",
"html-webpack-plugin": "^4.5.0",
"webpack": "^5.11.1",
"webpack-cli": "^4.3.0",
"webpack-dev-server": "^4.0.0-beta.0"

// .babelrc
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "usage",
                "corejs": 3
            }
        ]
    ]
}

// .browserslistrc
> 1%
last 10 versions
not ie <= 8`

//webpack.config.js
module: {
      rules: [
          {
              test: /\.(js)$/,
              exclude: /(node_modules)/,
              use: [
                  {
                      loader: 'babel-loader',
                  }
              ]
          }
      ]
  },
```
