### ISSUE TITLE
hot reloading is refreshing the whole page always

### ISSUE THREAD

**Issue by luisrudge** [webpack/webpack-dev-server#292]
Whenever I change any file of my code, the entire page is refreshed. I'm seeing this error:

![pasted image at 2015_10_07 04_43 pm](https://cloud.githubusercontent.com/assets/941075/10350649/98f65e84-6d1b-11e5-8450-dec180373e82.png)

**Comment by kevinsimper** [comment]
You have to post a little more, because it could be a problem with your webpack.config.js :+1: 

Can you perhaps post an example on how to get this problem?

**Comment by luisrudge** [comment]
hehe. sorry. It probably was an issue with my config file. I started another one from scratch and it's working :)

**Comment by kevinsimper** [comment]
@luisrudge It is okay :) Good you solved it!
