### ISSUE TITLE
Uninitialized Buffer Allocation vulnerability `websocket-driver`

### ISSUE THREAD

**Issue by manishy** [webpack/webpack-dev-server#2922]
- Operating System: All
- Node Version: 12.16.3
- NPM Version: 6.14.4
- webpack Version: ^4.41.3
- webpack-dev-server Version: 3.11.0
- Browser: All

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

Dependency tree for `websocket-driver` in `webpack-dev-server` is as  below  --

└─┬ `webpack-dev-server@3.11.0`
       ├─┬ `sockjs@0.3.20`
       │  └── `websocket-driver@0.6.5`
       └─┬ `sockjs-client@1.4.0`
              └─┬ `faye-websocket@0.11.3`
                     └── `websocket-driver@0.7.0`

### Expected Behavior

**Fixed versions and patches --** 
Affected versions: 0.1.0-0.7.0
SourceClear recommends updating `webpack-dev-server` to: 0.7.1 (or newer)

**Note-** `sockjs@0.3.21` has been upgraded with the `websocket-driver@^0.7.4` which is a non-vuln version.
**Maybe fix would be to use `sockjs@0.3.21` instead of using `sockjs@0.3.20` **

### Actual Behavior

`webpack-dev-server@3.11.0` is using `sockjs@0.3.20` which is using `websocket-driver@0.6.5` and `websocket-driver@0.6.5` has **Uninitialized Buffer Allocation vulnerability**

`webpack-dev-server@3.11.0` --> `sockjs@0.3.20` --> `websocket-driver@0.6.5`

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0`
