### ISSUE TITLE
Cannot mute `[HMR] Waiting for update signal from WDS...` in browser console

### ISSUE THREAD

**Issue by noelebrun** [webpack/webpack-dev-server#2932]
- Operating System: macOS 11.1
- Node Version: v14.12.0
- NPM Version: v6.14.8
- webpack Version: v5.10.1
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: Chrome & Safari

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
{
  ...
  devServer: {
    client: {
      logging: 'none',
     ...
    },
    ...
  },
}
```

### Expected Behavior

Setting client logging to `none` should suppress completely all client log, including from the hot chunk.

### Actual Behavior

The log `[HMR] Waiting for update signal from WDS...` is still outputted to browser console when loading the page.

### For Bugs; How can we reproduce the behavior?

Simply start webpack-dev-server with any kind of configuration (just don't pass `hot: false`), and check the browser console when the page has loaded.

From what I understood, that's because [the default logging level of the hot chunk is `info`](https://github.com/webpack/webpack/blob/master/hot/log.js#L1), and it is overwritten by webpack-dev-server client by calling [the exported `setLogLevel` function](https://github.com/webpack/webpack/blob/master/hot/log.js#L45).

But that function is only called once the webpack-dev-server client receives [a `logging` command](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L73) that is send [when creating the socket server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L560). That only happens [after the web server has been started and is listening](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L687).

That specific logging happens [as soon as the hot chunk is loaded](https://github.com/webpack/webpack/blob/master/hot/dev-server.js#L58), which is before the webpack-dev-server client receives that `logging` command from the socket server.

I don't have enough context to know which would be the best way to solve this, but let's start a discussion about it in here.

**Comment by noelebrun** [comment]
I guess it wouldn't make sense for the hot chunk to wait for anything from webpack-dev-server client before logging since the whole purpose of this log is that inform that it's waiting for that.

Maybe simply adding a timeout and changing the log to something like `Nothing received from WDS after *X*s` if nothing was received by then?

**Comment by alexander-akait** [comment]
We should run this https://github.com/webpack/webpack/blob/911ec1aa67011e25aa1449610f5b0b557edd5459/hot/log.js#L45, no need to timeouts or other unnecessary hacks

**Comment by noelebrun** [comment]
> We should run this https://github.com/webpack/webpack/blob/911ec1aa67011e25aa1449610f5b0b557edd5459/hot/log.js#L45, no need to timeouts or other unnecessary hacks

I'm not sure to understand how that would solve the issue? Until you receive the socket command. you don't know what's the actual logging configuration so you would have a default value.

If that default value isn't `none`, that doesn't solve the issue. And if it is, then it simply remove the whole purpose of that log (which I think is valuable, it shows that the client has been loaded properly even if something went wrong with webpack-dev-server).

**Comment by alexander-akait** [comment]
You can use `warn` or `error`, if you need keeping errors and warnings

**Comment by noelebrun** [comment]
If the client is loaded, but webpack-dev-server doesn't and so just doesn't send anything, would there be any kind of logs/warning? Because in that case I would suggest just getting rid of this log completely then.

**Comment by alexander-akait** [comment]
We can't because it is part of webpack, not webpack-dev-server. I have an idea (we can pass options from webpack to client entry, like we do for web socket host/port/etc and avoid sending unnecessary web socket message, I think it will be easy to solve), but this is not high priority, you can send a PR if you need it in the next release
