### ISSUE TITLE
Documentation for users migrating to Webpack v5

### ISSUE THREAD

**Issue by thw0rted** [webpack/webpack-dev-server#2935]
- Operating System: N/A
- Node Version: N/A
- NPM Version: N/A
- webpack Version: 5.10.1
- webpack-dev-server Version: 3.11.0
- Browser: N/A

- [ ] This is a **bug**
- [ ] This is a **modification** request
- [X] This is a **documentation** request

I just upgraded from Webpack v4 to Webpack v5.  From other issues on the tracker, it looks like I'm supposed to upgrade to `webpack-dev-server@4-beta`, but there is no mention of the Webpack 4-to-5 transition, either on the front page of this repo, or on the [dev-server docs at js.org](https://webpack.js.org/configuration/dev-server/#devserver), or in the [v5 migration guide](https://webpack.js.org/migrate/5/).

Webpack v5 is a big breaking change for most users.  If the 3.x branch of `webpack-dev-server` isn't going to be supported under Webpack v5, the docs should clearly say that, in at least one of the places mentioned above.  (If 3.x continues to be officially supported under v5, it wouldn't hurt to say that explicitly as well.)

**Comment by alexander-akait** [comment]
webpack-dev-server doesn't update docs because it is not ready yep, webpack-cli update them

**Comment by wangmeijian** [comment]
m

**Comment by Judahmeek** [comment]
webpack-dev-server 3.10.0+ supports webpack v5: https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes-4

**Comment by thetumper** [comment]
> webpack-dev-server 3.10.0+ supports webpack v5: https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes-4

This link is now invalid; anchor numbers change following additional releases.  As of today, see:
https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes-7
