### ISSUE TITLE
* ./src/main.js in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

### ISSUE THREAD

**Issue by FZW502** [webpack/webpack-dev-server#2937]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by yogithesymbian** [comment]
i have try to remove laravel package from laravel + vuejs , and got this issue
