### ISSUE TITLE
the webpack serve generates multiple Websockets and receives compilation notifications and triggers hot updates at the same time

### ISSUE THREAD

**Issue by wangmeijian** [webpack/webpack-dev-server#2939]
# Bug report

**What is the current behavior?**
Webpack creates as many WebSockets as webpack entry files

**If the current behavior is a bug, please provide the steps to reproduce.**
[my-react-app.zip](https://github.com/webpack/webpack/files/5733633/my-react-app.zip)

**What is the expected behavior?**
The Webpack Serve creates only one WebSocket

**Other relevant information:**
webpack version:  5.11.0
Node.js version: 10.21.0
Operating System: macOS Catalina 10.15.4
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/2792, you need to set `optimization: { runtimeChunk: 'single' }` https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432
