### ISSUE TITLE
Webpack Dev Server won't run. Advice on what versions will be compatible and don't give audit warnings.

### ISSUE THREAD

**Issue by JGFMK** [webpack/webpack-dev-server#2941]
- Operating System: OS/X Mojave 10.14.6 
- Node Version: 13.14.0
- NPM Version: 7.3.0
- webpack Version: 5.11.0
- webpack-dev-server Version: 3.11
- Browser: Chrome 87.0.4280.88

- [ x] This is a **bug**
- [ ] This is a **modification** request

### Code

// package.json 

[package.txt](https://github.com/webpack/webpack-dev-server/files/5739842/package.txt)

```js



// webpack.config.js
```

const path = require('path'); //From node

module.exports = {
  //mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
         test: /\.js$/,
         exclude: /node_modules/,
         loader: 'babel-loader'
      }
    ]
  },
  devtool: 'eval-cheap-module-source-map',
  devServer: {
    contentBase: path.join(__dirname, 'public')
  }
};
```js
// additional code, remove if not needed.
```

### Expected Behavior

When I run npm run dev command works

### For Bugs; How can we reproduce the behavior?
run npm install using attached package.json yields following output:

----
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

added 662 packages, and audited 663 packages in 48s

41 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

---
source-map-resolve@0.5.3 uses:
  urix@0.1.0:
  resolve-url@0.2.1:

update to source-map-resolve version 0.6.0 or later

 source-map-resolve used by base@0.11.2 which is used by snapdragon@0.8.2 which is used by braces@2.3.2 which is used by chokidar@2.1.8

chokidar@2.1.8 uses fsevents@1.2.13:

Comment:
Using node v13.14.0 not v14+

webpack-dev-server@3.11.0 uses chokidar@2.1.8 

npm run dev 'now' complains about:

---
> webpack-react-baseline@1.0.0 dev
> webpack-dev-server

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code 1
npm ERR! path /Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline
npm ERR! command failed
npm ERR! command sh -c webpack-dev-server

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgf/.npm/_logs/2020-12-24T15_29_17_548Z-debug.log

This may be a related issue:
https://github.com/mzgoddard/jest-webpack/issues/27
---

Earlier I added items one at a time - following this video:
https://www.youtube.com/watch?v=ydDUm1yPZs0&t=8s
Made change on this line (eval changes in webpack  to 5)
devtool: 'eval-cheap-module-source-map',
@17:46 he does npm i -D webpack-dev-server
@18:46 script for dev to webpack-dev-server added to package.json
I also added the .babelrc in the package,json instead.
@19:08 npm run dev
That's where things go awry.
Doing the series of npm i 's in the sequence the guy in the video did it, yielded a different result (I didn't make the babel-loader typo he did either),
Very similar to this:
https://github.com/npm/cli/issues/2082

I also tried this:
https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0
But then Promise errors abounded.

Can you advise.
I'm happy to help out if I can be of assistance and spin up a Zoom

### For Features; What is the motivation and/or use-case for the feature?
I can't get webpack-dev-server to install on a version where I don't get some sort of audit flags or the program won't run and serve up code a la live-server.

**Comment by alexander-akait** [comment]
Update webpack-cli to the latest version

**Comment by JGFMK** [comment]
According to https://www.npmjs.com/package/webpack-cli I am on the latest cli 
See it in my node-modules folder:
<img width="952" alt="Screenshot 2020-12-24 at 16 02 39" src="https://user-images.githubusercontent.com/14791808/103098102-7eba9200-4601-11eb-89bd-3c1aea081d05.png">

**Comment by alexander-akait** [comment]
How you run `webpack-dev-server`? It should be `webpack serve`

**Comment by JGFMK** [comment]
Thanks will give that a shot

**Comment by JGFMK** [comment]
> webpack-react-baseline@1.0.0 dev
> webpack server

[webpack-cli] Compilation finished
assets by status 0 bytes [cached] 1 asset

ERROR in main
Module not found: Error: Can't resolve 'server' in '/Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline'

webpack 5.11.0 compiled with 1 error in 168 ms
npm ERR! code 1
npm ERR! path /Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline
npm ERR! command failed
npm ERR! command sh -c webpack server

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jgf/.npm/_logs/2020-12-24T16_08_20_723Z-debug.log

---
content of the log: Now this is similar to what I had when I had added commands one at a time.
---
verbose cli [
0 verbose cli   '/Users/jgf/.nvm/versions/node/v13.14.0/bin/node',
0 verbose cli   '/Users/jgf/.nvm/versions/node/v13.14.0/bin/npm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v13.14.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/jgf/.nvm/versions/node/v13.14.0/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/jgf/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/Users/jgf/.nvm/versions/node/v13.14.0/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 488881857fc34958
20 timing npm:load Completed in 14ms
21 timing command:run-script Completed in 1476ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/Users/jgf/.nvm/versions/node/v13.14.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1026:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
23 verbose pkgid webpack-react-baseline@1.0.0
24 verbose cwd /Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline
25 verbose Darwin 18.7.0
26 verbose argv "/Users/jgf/.nvm/versions/node/v13.14.0/bin/node" "/Users/jgf/.nvm/versions/node/v13.14.0/bin/npm" "run" "dev"
27 verbose node v13.14.0
28 verbose npm  v7.3.0
29 error code 1
30 error path /Users/jgf/Desktop/Notes/JavaScript/React/webpack-react-baseline
31 error command failed
32 error command sh -c webpack server
33 verbose exit 1

**Comment by alexander-akait** [comment]
**serve**, not **server**

**Comment by JGFMK** [comment]
You are a star sir. Thanks and have a great Xmas.
