### ISSUE TITLE
Suggestion: Deprecate options that were moved/removed/grouped/renamed instead of generate errors in v4

### ISSUE THREAD

**Issue by pedrofurtado** [webpack/webpack-dev-server#2942]
Hey guys! @alexander-akait @hiroppy  👍 

I have a suggestion, to provide a better upgrading process to devs from v3 to v4 of webpack-dev-server. Instead of a set of breaking changes at once, a deprecation warnings and future breaking changes (in 5.x, or even 4.1 for example) could be a great deal, because of fact that the upgrade to webpack v5 (and the JS libs like this one) itself is a nighmare in many scenarios 😄.

Many options of dev-server were removed or moved/renamed/grouped. Isn't it better to allow old options (with deprecation logs and so on), and in future versions to remove it completely in fact?

We are working, for example, in `webpacker` gem (example of one issue: https://github.com/rails/webpacker/issues/2832) to provide compatibility with webpack v5 and webpack-cli v4. With this breaking changes in webpack-dev-server v4, the work is more hard to make this transition of upgrade.

Any help in this will be so awesome 🎉  Anyway, Thanks for your hard work on this great lib 🤝 🏆  And Merry Christmas! 🎅 🎄

**Comment by alexander-akait** [comment]
It will be great, but many options can't be compatibility between webpack-dev-server@3 and webpack-dev-server@4, I would even say that this is not possible, plus it create a lot of legacy code (reduce perf and readable code). Honestly, I think this is the last version that is undergoing such a big change.

**Comment by pedrofurtado** [comment]
Thanks for feedback @alexander-akait ! Anyway, is there a planned date for release of 4.x version (official release)? 🤝 😄

**Comment by alexander-akait** [comment]
I was really hoping to do it this month, but spent a lot of time on webpack-cli, especial integration webpack-cli and webpack-dev-server,but I think there will be a couple of beta releases in the near future, and then rc/stable, there is not much work left, I just don't have enough time for everything (unfortunately we don't have enough many for paid work https://opencollective.com/webpack :disappointed: and I need to do extra work to earn money for food and rent)

**Comment by alexander-akait** [comment]
Here migration https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md, unfortunately we need do many changes to move improve our code base, in future it will be not many breaking changes and prefer to deprecated instead remove
