### ISSUE TITLE
vue-cli2&&webpack3升级到webpack4使用的webpack-dev-server版本是3.2.0以上的就会报错

### ISSUE THREAD

**Issue by yangzhaoyuCSDN** [webpack/webpack-dev-server#2959]
- Operating System:win10
- Node Version:12.16.0
- NPM Version:6.13.4
- webpack Version:4.8.3
- webpack-dev-server Version:3.9.0
- Browser:

- [ 
Uncaught TypeError: Cannot read property 'call' of undefined
] This is a **bug**
- [x ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
