### ISSUE TITLE
How to detect hot with webpack v5, devserver v3?

### ISSUE THREAD

**Issue by simPod** [webpack/webpack-dev-server#2962]
- webpack Version: 5.12.2
- webpack-dev-server Version: 3.11.1

### Code

I used to do
```js
// webpack.config.js
module.exports = (env, argv) => {
  const isHot = argv.hot;
```

when running dev server with `--hot` option.

The option now seems to be gone. How can I set and detect whether it's hot or not?

**Comment by alexander-akait** [comment]
Not related to webpack-dev-server

**Comment by alexander-akait** [comment]
Bug on webpack-cli and fixed in master, release will be soon
