### ISSUE TITLE
Routing not working with copy-webpack-plugin

### ISSUE THREAD

**Issue by yutopio** [webpack/webpack-dev-server#2968]
- Operating System: Windows 10 20H2 (19042.746)
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 5.15.0
- webpack-dev-server Version: 3.11.2
- Browser: Chrome 87.0.4280.141 (Official Build) (64-bit)

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Minimum reproducing code is fully available at: https://github.com/yutopio/webpack-issue . The relevant part is extracted below:

package.json
```json
{
  "name": "some-code",
  "version": "0.0.1",
  "scripts": {
    "start": "webpack serve",
    "build": "webpack --mode production"
  },
  "devDependencies": {
    "copy-webpack-plugin": "^7.0.0",
    "webpack": "^5.15.0",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "^3.11.2"
  }
}
```

webpack.config.js
```js
const path = require('path')
const CopyPlugin = require("copy-webpack-plugin");

const DIST = path.resolve(__dirname, 'dist')

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: DIST,
    publicPath: DIST,
  },
  devServer: {
    contentBase: DIST,
    port: 8080,
    writeToDisk: true,
  },
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: 'src',
          globOptions: {
            ignore: ['**.js']
          },
        },
      ],
    }),
  ],
}
```

In this repository's root, please run `yarn && yarn start`.

### Expected Behavior

When you open `http://localhost:8080` in browser, you'll see the content of the first page, saying "index.html". You follow the link in the page, and you'll see the other page saying "Hello world!"

### Actual Behavior

Even after following the link, you'll continue to see the same page.

### For Bugs; How can we reproduce the behavior?

1. Please clone the repository from the link in the code section above.
2. `yarn && yarn start`
3. Open `http://localhost:8080/`
4. Click the link in the page.

---

Thank you for your help!

**Comment by alexander-akait** [comment]
Can't reproduce all works fine
![Screenshot from 2021-01-21 18-37-32](https://user-images.githubusercontent.com/4567934/105373488-ca1f8a80-5c17-11eb-8797-7fc88c5463c8.png)
![Screenshot from 2021-01-21 18-37-35](https://user-images.githubusercontent.com/4567934/105373490-cab82100-5c17-11eb-84e5-1e7df4ce255b.png)
