### ISSUE TITLE
webpack-dev-server v4 -window is not defined

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack-dev-server#2970]
- Operating System: MacOS
- Node Version: 12.17.0
- NPM Version: 6.14.4
- webpack Version: 5.13.0
- webpack-dev-server Version:4.0.0-beta.0
- Browser: Chrome

- [X] This is a **bug**
- [ ] This is a **modification** request

### Expected Behavior
When adding an entry to webpack5 with chunkLoading: 'import-scripts', the code should run inside the webworker. Yet, code from the webpack-dev-server is added that requires the window object. This leads to an error.
### Actual Behavior
As mentioned [here](https://stackoverflow.com/questions/65626352/webpack-dev-server-v4-window-is-not-defined), the window is undefined. The configuration in the stackoverflow question is missing the entries. For me the entry causing the issue is an entry setup with importScripts and used as a worker. Then this worker has this logic appended:
```
// startup
/******/ 	// Load entry module
/******/ 	__webpack_require__("./node_modules/webpack-dev-server/client/default/index.js?http://0.0.0.0&port=8080");
/******/ 	
```
Inside the index.js (webpack:///xxx.node_modules/webpack-dev-server/client/default/index.js?) is the window necessary. That is not working, even after adapting the globalObject to `'this'` or this:
```
globalObject: `(() => {
             if (typeof self !== 'undefined') {
                 return self;
             } else if (typeof window !== 'undefined') {
                 return window;
             } else if (typeof global !== 'undefined') {
                 return global;
             } else {
                 return Function('return this')();
             }
         })()`)
```
 in my webpack configuration.
Since there were no useful answers on stackoverflow I thought this would be a valid issue, which I am now also having to be brought up to here. 
Thank you for your input.

**Comment by janlent1** [comment]
Patching your code in index.ts with the 
```
(() => {
             if (typeof self !== 'undefined') {
                 return self;
             } else if (typeof window !== 'undefined') {
                 return window;
             } else if (typeof global !== 'undefined') {
                 return global;
             } else {
                 return Function('return this')();
             }
         })()
```
made the code run, so this should be maybe somehow adopted in the index.ts!

**Comment by alexander-akait** [comment]
We don't have `index.ts`

**Comment by janlent1** [comment]
@alexander-akait  Sorry I meant client/default/index.js

**Comment by alexander-akait** [comment]
Feel free to send a PR

**Comment by janlent1** [comment]
Should I just replace it with that or is there a fancier way of fixing that?

**Comment by janlent1** [comment]
@alexander-akait will do though! :) cool

**Comment by alexander-akait** [comment]
I think `self || window` will be enouth to fix, no need `global`, because it is code for browsers, `Function` can be problem

**Comment by janlent1** [comment]
@alexander-akait [here](https://github.com/webpack/webpack-dev-server/pull/2971) it is :)
