### ISSUE TITLE
WP5: Warnings logged as objects in browser

### ISSUE THREAD

**Issue by olee** [webpack/webpack-dev-server#2973]
I upgraded webpack to version 5 and now warnings and errors are logged broken as objects in browser console:
![image](https://user-images.githubusercontent.com/6547794/105368020-5d00fa80-5c01-11eb-8e03-f97c247ce67c.png)

Before wordpress 5 upgrade it looked like this:
![image](https://user-images.githubusercontent.com/6547794/105367775-1a3f2280-5c01-11eb-9bec-d47685fe554c.png)

I could track this error down to [this location](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L916) (which is logged in the client [here](https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L116).
It seems that warnings from the stats object are now returned as object `{ file: string; message: string; }` instead of just strings like before.

I did not check if any plugin might be responsible for this and did not try a minimal sample yet.

Does any1 else experience the same issue?

**Comment by alexander-akait** [comment]
Fixed in webpack-dev-server@4-beta.0, we are working on the stable release and please don't ignore the issue template in future

**Comment by olee** [comment]
1. I didn't find any information about that beta on the github page - I actually searched quite a lot about this issue and couldn't find any hints.  
Maybe you should add that to the github readme.
2. I didn't get an issue template shown because I created the issue from a source location - didn't know it would just completely ignore issue templates in that case, sorry.

**Comment by alexander-akait** [comment]
> I didn't find any information about that beta on the github page - I actually searched quite a lot about this issue and couldn't find any hints.
> Maybe you should add that to the github readme.

Yep, we include it in the next release

**Comment by alexander-akait** [comment]
Can you provide example?

**Comment by olee** [comment]
Well, I have a really large project here, but I can try to provide relevant parts:

devServer config:
```js
{
        port: env.devServerPort,
        host: '0.0.0.0',
        hot: true,
        compress: true,
        static: [paths.appPublic],
        transportMode: 'ws',
        overlay: {
            errors: true,
            warnings: false,
        },
        historyApiFallback: {
            disableDotRule: true,
        },
    }
```

webpack config:
```js
{
    target: 'web',
    devServer,
    stats: { /* ... */ },
    plugins: [
      // stuff like ForkTsChecker, html, CaseSensitivePaths, DuplicatePackageChecker, 
      // MiniCssExtract, CopyWebpackPlugin, HotModuleReplacement,, etc. 
      // No other reporting plugins
    ],
    // ...
}
```

**Comment by alexander-akait** [comment]
Can you provide screenshot (it will be enough)

**Comment by olee** [comment]
You mean of the error log?
![image](https://user-images.githubusercontent.com/6547794/105384004-064fec80-5c12-11eb-8e77-e83a9b44581e.png)

It definitely looks different from before (it has that `[webpack-dev-server]` in front of it) so it should prove it's using the beta, but the message is still an object.

**Comment by alexander-akait** [comment]
Very weird, we fixed it in beta...

**Comment by olee** [comment]
Can you point me to the commit / code lines? Because when I looked at the code I could not find where the transformation from objects to strings was handled. If I know where to look I could try to find the issue myself.

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L131 in source core and you should found this in `dist` client directory inside `node_modules`

**Comment by olee** [comment]
Hm... but shouldn't it look something like this
```
errors.map((error) => stripAnsi(error.message));
```
instead of this?
```
errors.map((error) => stripAnsi(error));
```

**Comment by alexander-akait** [comment]
Yes, but we support webpack@4 too, so I think `errors.map((error) => stripAnsi(error.message ? error.message : error));`

**Comment by olee** [comment]
Will you make a commit to fix this?

**Comment by alexander-akait** [comment]
Feel free to send a PR, fixing problem with webpack-dev-server in my roadmap on this weekends, but I am glad any help

**Comment by olee** [comment]
Yeah I just think it's way easier for you to commit that one small adjustment rather than me having to go full blown with a PR here 😏

**Comment by petercpwong** [comment]
Any chance you can backport this fix to v3?
