### ISSUE TITLE
Unable to load dynamically content served from another webpack-dev-server

### ISSUE THREAD

**Issue by Thebarda** [webpack/webpack-dev-server#2974]
- Operating System: Windows 10
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: ^5.15.0
- webpack-dev-server Version: ^3.11.2
- Browser: Chrome

- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Hello there, I'm playing with Module federation along side webpack-dev-server and I'm asking if it is possible to load served content from another webpack-dev-server.

For example, I have 3 applications:
- app2: serves a module on this URL (http://localhost:3001/remoteEntry.js) with Module federation and WDS
- app3: serves two modules on this URL (http://localhost:3001/remoteEntry.js) with Module federation and WDS
- app1: consumes those three modules with Module federation. It also use WDS to serve his own content.

Note: I've found a workaround -> app2 and app3 write their changes inside a folder on disk then app1 can detect any changes using `contentBase` and `watchContentBase` but this is not de straight thing that I want.

### Code

Here is the repo : [https://github.com/Thebarda/ModuleFederationExample](https://github.com/Thebarda/ModuleFederationExample)

### Expected Behavior

Modules served from app2 and app3 URLs must be watched by app1 and any changes have to be detected by URLs watch by app1.

### Actual Behavior

app1 does not consumes the changes made inside app2 or app3's modules.

Thank you in advance for your reply.

**Comment by alexander-akait** [comment]
No bidirectional changes right now, I think it is impossible, in this way, we can implement `watchFiles` option for this case

**Comment by Thebarda** [comment]
Excuse me, what is the purpose of the `watchFiles` option ? :)

**Comment by alexander-akait** [comment]
place where you want to watch files where you expected changes

**Comment by alexander-akait** [comment]
Can be solved using `watchFiles`, bidirectional changes will be in future
