### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by Andrey-Bushman** [webpack/webpack-dev-server#2975]
I saw this issue [#2029](https://github.com/webpack/webpack-dev-server/issues/2029) and [#2967](https://github.com/webpack/webpack-dev-server/issues/2967). Both are closed, but the problem exists still.

Operating System: Windows 10
Node Version: v14.15.1
NPM Version: 6.14.8
"webpack": "^5.17.0"
"webpack-cli": "^4.4.0",
"webpack-dev-server": "^3.11.2"
Browser: Google chrome

My script in the *package.json* file:
`"start": "npx webpack-dev-server --mode development --open"`

My settings for *webpack-dev-server* in the *webpack.config.js* file:
```
devServer: {
   port: 4200
}
```

Error message:
> Error: Cannot find module 'webpack-cli/bin/config-yargs'

**Comment by snitin315** [comment]
Please use - 

`webpack serve --mode development`

**Comment by Andrey-Bushman** [comment]
> Please use -
> 
> `webpack serve --mode development`

Thank you!
