### ISSUE TITLE
devServer can not show html but dir, with module.exports=array

### ISSUE THREAD

**Issue by lornally** [webpack/webpack-dev-server#2977]
- webpack version:  5.4.0
- Node.js version:  15.5.0
- Operating System:  macos bigsur 11.1
- Additional tools: vscode, coffeescript
- NPM Version:7.3.0
- webpack-dev-server Version: 3.11.0
- Browser: chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```coffeescript
# webpack.config.coffee
cmd = # here is another config

html = # here is config for html
	entry: d1: './src/d1.js'
	output:
		path: path.resolve __dirname, 'dist/html'
		filename: '[name].[contenthash].js'
	plugins: [
		new HtmlWebpackPlugin	title: 'Development'
	]
	devServer: contentBase: './dist/html'

module.exports=[html,cmd] # if i use this line, http://localhost:8080/ is ~/
module.exports=[html] # if i use this line, http://localhost:8080/ is right
```

### Expected Behavior
http://localhost:8080/ show '~/', it should show the index.html of the website.

### Actual Behavior
when i use  "webpack serve", http://localhost:8080/  only show: '~/' (the blank directory)

### For Bugs; How can we reproduce the behavior?
- webpack serve
- visit: http://localhost:8080/ 

- ref: https://github.com/webpack/webpack/issues/12499

**Comment by alexander-akait** [comment]
Again - with **normal** reproducible test repo, I can't help you having only part of configurations, I will reopen it when you fix it

**Comment by lornally** [comment]
thank you, this is my first issue:) now, this is my git: https://github.com/lornally/weppackserveissue

**Comment by lornally** [comment]
how about it? do you need me push more?

**Comment by alexander-akait** [comment]
```
devServer: contentBase: './dist/html', publicPath: '/dist/html'
```

**Comment by lornally** [comment]
thank you:)

**Comment by lornally** [comment]
do you really try this? this can not fix the bug. i have push it in git :  https://github.com/lornally/weppackserveissue

**Comment by alexander-akait** [comment]
What do you want? It shows `index.html`, please describe your issue, I can't understand you

**Comment by lornally** [comment]
# with this, http://localhost:8080/ allways show dir / , this is wrong
# i have up pic to git: https://raw.githubusercontent.com/lornally/weppackserveissue/main/printscreen/devserver.png
devServer:
	contentBase: './dist/html'
	publicPath: '/dist/html'


# if export this http://localhost:8080/ is right show index.ejs, this is right
# i have up pic to git: https://raw.githubusercontent.com/lornally/weppackserveissue/main/printscreen/show_index.png
module.exports= html

# if export this http://localhost:8080/ is only show dir ./, this is wrong
# i have up pic to git: https://raw.githubusercontent.com/lornally/weppackserveissue/main/printscreen/array_show_dir.png
module.exports = [ cmd, html ]


if you can not see the pic, pls down it from git

**Comment by alexander-akait** [comment]
`webpack serve --config-name site`

**Comment by lornally** [comment]
thank you very much,  but i got this error:
- Configuration with name "site" was not found.

**Comment by alexander-akait** [comment]
```
html =
        name: 'site'
	mode: 'development'
	devtool: 'inline-source-map'
	entry:
		d1: './src/d1.js',
		d2: './src/d2.js'
```

**Comment by lornally** [comment]
wow, thank you so much, "site" is key setting for this, thank you again, and where i can find relative doc for this?

**Comment by alexander-akait** [comment]
https://webpack.js.org/api/cli/#configuration-options maybe we need couple examples, feel free to send a PR

**Comment by lornally** [comment]
really really thank you for your patient and time, thank you:)
