### ISSUE TITLE
webpack-dev-server compile twice on startup with my custom plugin

### ISSUE THREAD

**Issue by WanderWang** [webpack/webpack-dev-server#2978]
- Operating System:
- Node Version:v12.13.0
- NPM Version:6.12.0
- webpack Version:5.17.0
- webpack-dev-server Version:4.0.0-beta.0

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports = {
    //...otherConfig,
    plugins:[ new MyPlugin()]
}
```

```js
// MyPlugin.ts

export default class ThemePlugin {

    constructor() {

    }
    public apply(compiler: webpack.Compiler) {
        compiler.hooks.afterCompile.tap(pluginName, (compilation) => {
            const missingFilePath = path.join(compiler.context, 'missing-file.json');
            //compilation.fileDependencies.add(missingFilePath);

            const existedsFilePath = path.join(compiler.context, 'package.json');
            //compilation.fileDependencies.add(existedsFilePath );

            const existedDir = path.join(compiler.context,'mydir');
            //compilation.contextDependencies.add(existedDir);
        });
    }
}



```

### Expected Behavior

1. execute ```webpack-dev-server```
2. webpack-dev-server should be compiled once on startup

### Actual Behavior

1. when I open ```compilation.fileDependencies.add(missingFilePath);```  or ```compilation.contextDependencies.add(existedDir);``` , webpack-dev-server compiled twice on startup
2. when I open ```compilation.fileDependencies.add(existedsFilePath );``` , webpack-dev-server compiled once on startup ( no bug )

### For Bugs; How can we reproduce the behavior?
Yes

**Comment by alexander-akait** [comment]
It means you added directory/files where you write/put new assets, so watch see changed and rerun compilation, you ignore `For Bugs; How can we reproduce the behavior?`, so I can't help, sorry

**Comment by WanderWang** [comment]
I create a repo which can reproduce the behaviour

https://github.com/WanderWang/webpack-dev-server-compile-twice

**Comment by WanderWang** [comment]
sorry I cannot reopen this issue @alexander-akait

**Comment by alexander-akait** [comment]
```js
const missingFilePath = path.join(compiler.context, 'missing-file.json');

compilation.fileDependencies.add(missingFilePath);
```

You **should not do it**, webpack wait this file so run compilation again

**Comment by alexander-akait** [comment]
Same for this:
```js
const existedDir = path.join(compiler.context, 'mydir');
compilation.contextDependencies.add(existedDir);
```

Avoid adding missing files or directories, if they doesn't exists after compilation

**Comment by WanderWang** [comment]
thank u alex .
In fact, my requirement is  "trigger a complication when file in  resource-folders changed". 
now I know , I should not implement this requirement with " complication.contextDependencies.add("resource-folders"),  but how to implement correctly ?

**Comment by WanderWang** [comment]
sorry , i know what happened
