### ISSUE TITLE
"browserslist" is missing as target to auto-inject client/hot runtimes

### ISSUE THREAD

**Issue by cdoublev** [webpack/webpack-dev-server#2980]
- Operating System: Debian Buster
- Node Version: 15.5.0
- NPM Version: 7.3.0
- webpack Version: 5.18.0
- webpack-dev-server Version: 3.11.2 / 4.0.0-beta-0
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/cdoublev/webpack-dev-server-issue

### Expected Behavior

Hot Module Replacement enabled.

### Actual Behavior

Waiting for update signal from WDS.

### For Bugs; How can we reproduce the behavior?

Run `npm start` after cloning the repo, and open console.

### Additional

I believe `'browserslist` (default webpack config `target`) is missing [here](https://github.com/webpack/webpack-dev-server/blob/v3.11.2/lib/utils/addEntries.js#L121) (3.11.2) and [here](https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/DevServerPlugin.js#L132) (4 beta), as well as in the corresponding tests.

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/DevServerPlugin.js#L132 this code for webpack@4, no `browserslist` target in webpack v4, for webpack@5 we use https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/DevServerPlugin.js#L131, webpack-dev-server v3 has some limitations with webpack@5, we are working on stable webpack-dev-server v4, release will be soon

**Comment by cdoublev** [comment]
Alright, thank you, and sorry for the wrong report concerning wepback@v4.
