### ISSUE TITLE
webpack-dev-server serving files from disk instead of from memory

### ISSUE THREAD

**Issue by maxloh** [webpack/webpack-dev-server#2982]
- Operating System: Windows 10
- Node Version: v14.7.0
- NPM Version: 6.14.11
- webpack Version: 5.18.0
- webpack-dev-server Version: 3.11.2
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const RemarkHTML = require('remark-html');

module.exports = {
  mode: 'production',
  entry: ['./src/js/app.js', './src/scss/style.scss'],
  output: {
    path: path.resolve('./assets/js/'),
    filename: 'app.bundle.js',
    environment: {
      arrowFunction: false,
      destructuring: false,
      forOf: false
    }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: [
          // \\ for Windows, / for Mac OS and Linux
          /node_modules[\\/]core-js/,
          /node_modules[\\/]webpack[\\/]buildin/,
          /node_modules[\\/]github-buttons/
        ],
        use: {
          loader: 'babel-loader',
          options: {
            presets: [['@babel/preset-env', { targets: 'defaults' }]]
          }
        }
      },
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'resolve-url-loader',
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              sassOptions: { includePaths: ['node_modules'] }
            }
          }
        ]
      },
      {
        test: /\.html$/,
        use: 'html-loader'
      },
      {
        test: /\.md$/,
        use: [
          'html-loader',
          {
            loader: 'remark-loader',
            options: {
              remarkOptions: { plugins: [RemarkHTML] }
            }
          }
        ]
      },
      {
        test: /\.(gif|png|svg)/,
        type: 'asset/inline'
      }
    ]
  },
  devtool: 'source-map',
  devServer: {
    compress: true,
    port: 80,
    open: true
  },
  plugins: [new MiniCssExtractPlugin({ filename: '../css/style.css' })]
};
```

### Expected Behavior

webpack-dev-server compile files, save them in memory, and serve them to browser.

### Actual Behavior

With my existing config, webpack works fine on building my project. It takes `src/js/app.js` and `src/scss/style.scss` as entry point, build the files, and then output js and css file to `assets/js/app.js` and `assets/scss/style.css` respectively.

However, when I run `webpack serve` and edit source files, webpack-dev-server outputs to the console as if it has compiled `assets/js/app.js` and `assets/css/style.css` successfully, but instead of newly compiled result from memory, it keep serving old versions of these files from disk. If I delete these two files from disk, webpack-dev-server returns 404.

### For Bugs; How can we reproduce the behavior?

- Clone https://github.com/maxloh/maxloh.github.io/
- Checkout `webpack-error` branch
- Run `webpack serve`
- `assets/js/app.js` and `assets/css/style.css` returns 404 not found

**Comment by alexander-akait** [comment]
You don't have `output` option, change:
```
path: path.resolve('./assets/js/') -> path: path.resolve('./'),
filename: 'app.bundle.js' -> filename: 'assets/js/app.bundle.js',
plugins: [new MiniCssExtractPlugin({ filename: '../css/style.css' })] -> plugins: [new MiniCssExtractPlugin({ filename: './assets/css/style.css' })]
```

Please use `html-webpack-plugin` it will do right URL without example setup.

Images are not work because webpack doesn't handle `index.html`, you need `html-webpack-plugin` or you can use `copy-webpack-plugin` to copy them in `assets` directory.

`webpack serve` it is server so you need to setup right `output.path` and `publicPath` to work correctly.

For debug you can use `http://localhost:8080/webpack-dev-server` and webpack-dev-server show you where files are stored

**Comment by maxloh** [comment]
@alexander-akait I changed `output` config according to your advice and dev server works like a charm.

It may worth documenting if dev server only works when `output.path` being set to the working directory.

**Comment by alexander-akait** [comment]
`output.path` can be any, you can use `publicPath` with more complex cases, yep we can improve it, where you want to see it?

**Comment by maxloh** [comment]
> `output.path` can be any, you can use `publicPath` with more complex cases,

@alexander-akait I am a little bit confused

Why `{ path: path.resolve('./assets/js/'), filename: 'app.bundle.js' }` won't work, but `{ path: path.resolve('./'), filename: 'assets/js/app.bundle.js' }` does?

Shouldn't both of them output bundle to `assets/js/app.bundle.js`?

> yep we can improve it, where you want to see it?

Maybe we can add a troubleshooting section, like [babel-loader does](https://webpack.js.org/loaders/babel-loader/#troubleshooting)

**Comment by alexander-akait** [comment]
Because `webpack-dev-server` (`webpack-dev-middleware` under the hood) uses `output.path` as serve entry point for request, i.e. `output.path` + `request` = `filesystem path` (simplified)

**Comment by maxloh** [comment]
@alexander-akait Can I understand it as "webpack-dev-server uses output.path as the root path of the compiled contents"?

So with `{ path: path.resolve('./assets/js/'), filename: 'app.bundle.js' }`, app.bundle.js will be available at http://localhost:[port]/app.bundle.js, instead of http://localhost:[port]/assets/js/app.bundle.js?

**Comment by alexander-akait** [comment]
Here logic https://github.com/webpack/webpack-dev-middleware/blob/master/src/utils/getFilenameFromUrl.js, just debug it, it will be easier for you to understand

**Comment by alexander-akait** [comment]
Maybe you can even found some ideas how we can improve it

**Comment by maxloh** [comment]
@alexander-akait I made a pull request for documenting this behaviour.

Can you help review it? https://github.com/webpack/webpack.js.org/pull/4519

> Maybe you can even found some ideas how we can improve it

I think it would be better if we determine virtual directory of generated files based on both `output.path` and `devServer.contentBase`.

Like in my case, if I set `output.path` to `path.resolve('./assets/js/')` and `devServer.contentBase` to `path.resolve('./')`, then dev-server could determine bundle files should be under `./assets/js/` folder.

**Comment by alexander-akait** [comment]
> I think it would be better if we determine virtual directory of generated files based on both output.path and devServer.contentBase.

Generated assets and static assets is not the same
