### ISSUE TITLE
v3.11.2 vulnerability from execa@1.0.0

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack-dev-server#2984]
- Operating System: Mac
- Node Version: 12.19.1
- NPM Version: 6.14.8
- webpack Version: 4.46.0
- webpack-dev-server Version: 3.11.2
- Browser:

- [x] This is a **bug**
- [ ] This is a **modification** request

### Actual Behavior

sonatype-2019-0206 vulnerability found through:

```
webpack-dev-server@3.11.2 -> internal-ip@^4.3.0 -> default-gateway@^4.2.0 -> execa@^1.0.0
```

sonatype-2019-0206 | 9.8 | execa : 0.7.0 | 2.0.1+

Example of npm tracking it: https://github.com/npm/cli/issues/1490

**Comment by alexander-akait** [comment]
We can't fix it without breaking change, sorry

**Comment by alexander-akait** [comment]
Fixed for v4 https://github.com/webpack/webpack-dev-server/blob/master/package.json#L49
