### ISSUE TITLE
Hot reloading tested in different ways and is not working properly

### ISSUE THREAD

**Issue by Ridermansb** [webpack/webpack-dev-server#2985]
- **Operating System:** _macOS Big Sur 11.2_
- **Node Version:** _v14.15.4_
- **NPM Version:** _6.14.10_
- **webpack Version:** _^5.19.0_
- **webpack-dev-server Version:** _^4.0.0-beta.0_
- **Browser:** _Google Chrome Version 88_

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Repository link: https://github.com/Ridermansb/webpack5Hot

 - [`master`](https://github.com/Ridermansb/webpack5Hot) branch it's using only basic webpack-dev-server configuration without any plugins
 - [`react-hot-loader`](https://github.com/Ridermansb/webpack5Hot/tree/react-hot-loader) branch it's using [react-hot-loader](https://github.com/gaearon/react-hot-loader) plugin. **[Pull Request #1](https://github.com/Ridermansb/webpack5Hot/pull/1)**
 - [`react-refresh-webpack-plugin`](https://github.com/Ridermansb/webpack5Hot/tree/react-refresh-webpack-plugin) branch it's using [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) webpack plugin. **[Pull Request #2](https://github.com/Ridermansb/webpack5Hot/pull/2)**

### Expected Behavior

In all case... should not reload the page and only reload the portion that's changed

### Actual Behavior

It's Always reloading the entire page.

### For Bugs; How can we reproduce the behavior?

Just clone the repository [ridermansb/webpack5Hot](https://github.com/Ridermansb/webpack5Hot) 

 - `npm install`
 - `npm start`

And try update `Header` component

**Comment by alexander-akait** [comment]
`react-hot-loader` is not compatibility with webpack@5 https://github.com/gaearon/react-hot-loader/issues/1449

**Comment by alexander-akait** [comment]
You don't have entry, so webpack-dev-server doesn't know how to attach hot reloading

**Comment by Ridermansb** [comment]
> `react-hot-loader` is not compatibility with webpack@5 [gaearon/react-hot-loader#1449](https://github.com/gaearon/react-hot-loader/issues/1449)

And about [react-refresh](https://github.com/Ridermansb/webpack5Hot/tree/react-refresh-webpack-plugin) ?
Same happening with [react-refresh plugin](https://github.com/Ridermansb/webpack5Hot/pull/2)

**Comment by alexander-akait** [comment]
Something wrong in configuration...

**Comment by alexander-akait** [comment]
Change:
```
"start": "webpack serve --mode development --hot --host localhost --static public"
```

`static` bug was fixed, `host` problem will fixed too in near future, `--hot only` is no need for you, now `hot` is working, but still not reload modules (you can see it in console)

Why it is still not work? I don't know, also I found your duplicate the issue https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/303, don't do it in future, be patient

**Comment by Ridermansb** [comment]
@alexander-akait the problem is that I don't know if this issue is on webpack-dev-server, react-hot-loader or on react-refresh
That's the reason I duplicated the issue.


--------

About your recommendation, after I made this change... the UI is not updating

![comment01](https://user-images.githubusercontent.com/725337/106642483-2adb8b00-6567-11eb-98f7-e5a92cd54cd3.gif)

**Comment by alexander-akait** [comment]
Problem from `react-refresh-webpack-plugin`

**Comment by Edge00** [comment]
webpack-dev-server Version: ^4.0.0-beta.0
whole page refreshed on vue project

**Comment by ankurk91** [comment]
webpack-dev-server Version: ^4.0.0-beta.1
still a full page reaload on a vue v2 project.

**Comment by alexander-akait** [comment]
@ankurk91 Please provide reproducible test repo, your information is not help to help you

**Comment by ankurk91** [comment]
HMR is working fine for me now, with webpack-dev-server beta 2, and vue v2

**Comment by alexander-akait** [comment]
Fixed in beta, stable release will be soon
