### ISSUE TITLE
webpack serve keeps running in the bg after Ctrl+C

### ISSUE THREAD

**Issue by anilanar** [webpack/webpack-dev-server#2986]
- Operating System: ArchLinux (NixOS)
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 5.19.0
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: -

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```bash
webpack serve
```

### Expected Behavior
webpack process is killed after Ctrl+C.

### Actual Behavior
It keeps running in the background until the build is complete (at least once). Using `htop`, I can find a process subtree called `webpack` that contains like 8 `webpack` subprocesses. 

### For Bugs; How can we reproduce the behavior?
Just run `webpack serve` in a large project. I cannot realistically provide a minimal reproduction because it's only observable when webpack build takes very long time. Minimal reproductions have 5 second build time so the bug is not observable.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/1479, feel free to help us
