### ISSUE TITLE
Webpack dev server cannot serving file

### ISSUE THREAD

**Issue by thanhtung6824** [webpack/webpack-dev-server#2989]
Now I'm using Webpack 5 to bundle and serving my html static page. But it not serving my index.html
Here is what I've tried:

webpack.config.js

    module.exports = {
        mode: 'development',
        entry: './src/index.js',
        output: {
            path: path.resolve(__dirname, 'dist'),
            filename: '[name].[fullhash].js',
            publicPath: '/'
        },
        module: {
            rules: [
                {
                    test: /\.css$/,
                    use: ['style-loader', 'css-loader'],
                },
            ],
        },
        plugins: [
            new CleanWebpackPlugin(),
            new HtmlWebpackPlugin({
                title: 'HMR',
                template: path.resolve(__dirname, 'src/index.html'), // template file
                filename: 'index.html', // output file
            }),
        ],
        devServer: {
            contentBase: path.resolve(__dirname, 'dist'),
            hot: true,
            open: true,
        },
        optimization: {
            moduleIds: 'deterministic',
            runtimeChunk: 'single',
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        test: /[\\/]node_modules[\\/]/,
                        name: 'vendors',
                        chunks: 'all',
                    },
                },
            },
        },
    };

When I open browser I get:
HTTP ERROR 404 Not Found

Need helps

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
