### ISSUE TITLE
SHA-1 hash is deprecated

### ISSUE THREAD

**Issue by MrEfrem** [webpack/webpack-dev-server#299]
I run webpack-dev-server with --https option. See this error in browser console:
```
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]
```

It is necessary to replace the certificate with sha-256 hash, because SHA-1 is deprecated.

**Comment by kpe** [comment]
as a local workaround one can use the --cert, --cacert, --key options to specify a custom certificate.

**Comment by SpaceK33z** [comment]
@MrEfrem or @kpe, can you verify that #572 works for you?

**Comment by MrEfrem** [comment]
yes, thanks. in a week I will be able to check.

**Comment by MrEfrem** [comment]
Please do backwards changes to weback 1.x branch.
