### ISSUE TITLE
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies

### ISSUE THREAD

**Issue by raphael10-collab** [webpack/webpack-dev-server#3016]
Installing webpack-dev-server I encountered this warning:

`warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies`

- O.S.: Ubuntu 18.04.4 Desktop
- node: v14.5.0

**Comment by alexander-akait** [comment]
Fixed for v4 (beta-0), no need to duplicate

**Comment by jeffrson** [comment]
Well, I think the problem is that v4 hasn't been released yet and webpack-dev-server as well as, for instance, react-scripts is still not compatible with node 14.

**Comment by yoyo837** [comment]
I agree with @jeffrson. 🙋‍♂️

**Comment by alexander-akait** [comment]
> I wonder if it wouldn't have been better to release 3.12 with just (some) updated dependencies.

It is impossible due breaking changes
