### ISSUE TITLE
[question] /webpack-dev-server file list endpoint not working

### ISSUE THREAD

**Issue by olee** [webpack/webpack-dev-server#3023]
Accessing http://localhost:<port>/webpack-dev-server to show list of bundled files as the documentation describes:
![image](https://user-images.githubusercontent.com/6547794/108350075-0b3d9700-71e4-11eb-80a6-52a1780b88b8.png)

- Operating System: Windows 10
- webpack Version: 5.21.2
- webpack-dev-server Version: 4.0.0-beta.0

```js
// webpack.config.js
{
    // ...
    devServer: {
        port: devServerPort,
        hot: true,
        compress: true,
        static: [paths.appPublic],
        transportMode: 'ws',
        writeToDisk : true,
        overlay: {
            errors: true,
            warnings: false,
        },
        historyApiFallback: {
            disableDotRule: true,
        },
    }
}
```

### Expected Behavior
Show list of files

### Actual Behavior
Index html is served

**Comment by alexander-akait** [comment]
Yep, bug, send a fix

**Comment by olee** [comment]
Anything new on this? Still looking bad as ever the console output.

**Comment by alexander-akait** [comment]
PR, exist, will be fixed for new rc release (hope today)

**Comment by olee** [comment]
When can we expect a release with this fix?

**Comment by alexander-akait** [comment]
Today
