### ISSUE TITLE
`devServer.injectClient` setting causes the browser not to refresh when the file is changed

### ISSUE THREAD

**Issue by liby** [webpack/webpack-dev-server#3036]
- Operating System: macOS Catalina@10.15.7
- Node Version: v12.20.1
- NPM Version: v6.14.10
- webpack Version: ^5.23.0
- webpack-dev-server Version: ^3.11.2
- Browser: Chrome@88.0.4324.182

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

[A sample repo](https://github.com/liby/Webpack_Demo)

### Expected Behavior

- When the file changes, the browser refreshes

### Actual Behavior

- The dev-server reload/refresh the page when file change is detected, but the browser is not refreshed.

### For Bugs; How can we reproduce the behavior?

- Explicitly set `devServer.injectClient` to `false`. Note: The [documentation](https://webpack.js.org/configuration/dev-server/#devserverinjectclient) mentions that this setting defaults to `false`.

### Recording screen

https://user-images.githubusercontent.com/38807139/108605278-1401b900-73ee-11eb-814c-285f87c91794.mp4

----

https://user-images.githubusercontent.com/38807139/108605264-01877f80-73ee-11eb-9eaa-c5aa15bab2bb.mp4

**Comment by alexander-akait** [comment]
> When the file changes, the browser refreshes

You should not touch `injectClient` in this case, client contain logic for HTML and liver reload

> defaults to false

No, it is possible `enum`

**Comment by liby** [comment]
@alexander-akait 

> You should not touch injectClient in this case, client contain logic for HTML and liver reload

This is just a simple example. In our actual project, the `devServer.transportMode: 'ws'` is set.
Setting `injectClient` to `false` is to prevent the WS client from getting injected as we're already including `webpackHotDevClient`.
