### ISSUE TITLE
How to detect from within a plugin whether the webpack is running a single build or a webpack-dev-server?

### ISSUE THREAD

**Issue by gajus** [webpack/webpack-dev-server#305]
This plugin should only work when webpack is executed as a webpack-dev-server, https://github.com/gajus/write-file-webpack-plugin.

How do I detect within the plugin script whether the webpack is running a single build or a webpack-dev-server?

**Comment by SpaceK33z** [comment]
I have a very hacky workaround for this:

```js
const IS_DEV_SERVER = process.argv[1].indexOf('webpack-dev-server') >= 0;
```

**Comment by gajus** [comment]
This will not work if webpack-dev-server is started programmatically.

**Comment by Luminess** [comment]
Why would you need to detect this? You're programmatically starting the webpack dev server so you should know when it's being ran.

**Comment by SpaceK33z** [comment]
@gajus, do you need this also for webpack-dev-middleware users? If so, you could check `compiler.outputFileSystem`. See also [this line](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L56).

**Comment by gajus** [comment]
@SpaceK33z thats what we are already doing

https://github.com/gajus/write-file-webpack-plugin/blob/b5ec5c82b06109dd4d68b2bab4904845262290f3/src/index.js#L17

It feels a bit hacky though.

Otherwise, it works.

**Comment by aight8** [comment]
Whats about setting a simple environment variable?
