### ISSUE TITLE
[Webpack 5] No color in console when using `devServer.stats` option

### ISSUE THREAD

**Issue by dehghani-mehdi** [webpack/webpack-dev-server#3059]
- webpack Version: `5.24.2`
- webpack-dev-server Version: `4.5.0`

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
stats: {
    entrypoints: false,
    errorDetails: false,
    hash: false,
    version: false,
    assets: false,
    chunks: false,
    builtAt: false,
    modules: false
},
```

### Expected Behavior
Colored messages in command line, e.g error in red

### Actual Behavior
Messages shown with no color (while)

### For Bugs; How can we reproduce the behavior?
Just use the `state` as shown above

**Comment by alexander-akait** [comment]
Please create reproducible test repo, colors works everywhere

**Comment by dehghani-mehdi** [comment]
@alexander-akait I got this, is that okay? I expected this error message in red.

![ww](https://user-images.githubusercontent.com/9152330/109538353-3756f300-7ad5-11eb-9ca0-231425950ae6.png)

**Comment by alexander-akait** [comment]
Try:
```
stats: {
    entrypoints: false,
    errorDetails: false,
    hash: false,
    version: false,
    assets: false,
    chunks: false,
    builtAt: false,
    modules: false,
    colors: true
}
```

**Comment by dehghani-mehdi** [comment]
Now I got this.
![xxx](https://user-images.githubusercontent.com/9152330/109539044-0f1bc400-7ad6-11eb-9b1c-b2e3dfd70a77.png)

Colors added but I think is not correct, I think the whole error message should be in red.

**Comment by alexander-akait** [comment]
Do you use `webpack-cli`? What is version of `webpack-cli`? How you run webpack?

**Comment by dehghani-mehdi** [comment]
> Do you use webpack-cli? 

Yes

> What is version of webpack-cli?

`4.5.0`

> How you run webpack?

`webpack serve --profile --progress --mode development`

**Comment by alexander-akait** [comment]
What is `devServer` option?

**Comment by dehghani-mehdi** [comment]
```
    contentBase: path.join(__dirname, 'public'),
    disableHostCheck: true,
    hot: true,
    historyApiFallback: true,
    compress: true,
    port: 8080,
    sockPort: 8080,
    headers: { 'Access-Control-Allow-Origin': '*' },
    stats: {
        entrypoints: false,
        errorDetails: false,
        hash: false,
        version: false,
        assets: false,
        chunks: false,
        builtAt: false,
        modules: false,
        colors: true
    },
```

**Comment by alexander-akait** [comment]
I see, fixed in v4 (beta) (inside `webpack-dev-middeware` v4), right now please use this workaround, in future you can remove it

**Comment by dehghani-mehdi** [comment]
Great, thanks, by workaround you mean `colors: true`?

**Comment by alexander-akait** [comment]
Yes

**Comment by dehghani-mehdi** [comment]
It adds too much colors and also the result is not correct.
As you can see in shown screenshot, the whole error message should be in red, instead few words are in red and too many in green. is that correct to you?
The final result produce same result as `colors: true`?

**Comment by alexander-akait** [comment]
Yes

**Comment by dehghani-mehdi** [comment]
Okay, I'll open another issue about that then.
