### ISSUE TITLE
--env option doesn't work

### ISSUE THREAD

**Issue by MikielAgutu** [webpack/webpack-dev-server#3061]
- Operating System: Windows 10
- Node Version: v15.5.0
- NPM Version: 7.3.0
- webpack Version: 5.10.0
- webpack-dev-server Version: 3.11.0
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

package.json
```js
...
"scripts": {
  "start:development": "webpack serve --env CONTEXT=staging",
}
...
```

### Expected Behavior
Environment variables injected.

It says here https://github.com/webpack/webpack-dev-server#with-the-cli:

```
Usage: webpack serve|s [entries...] [options]
....
--env <value...>           Environment passed to the configuration when it is a function.
```

### Actual Behavior
```
> webpack serve --env CONTEXT=staging

error: unknown option '--env'
```

### For Bugs; How can we reproduce the behavior?

- Run `webpack serve` with the `--env` flag

### For Features; What is the motivation and/or use-case for the feature?
n/a

**Comment by alexander-akait** [comment]
Update `webpack-cli` to the latest version

```
webpack serve --env CONTEXT=staging
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/evilebottnawi/IdeaProjects/webpack-cli
```
