### ISSUE TITLE
Webpack Dev Server not opening files in incognito window

### ISSUE THREAD

**Issue by TimeTerminal** [webpack/webpack-dev-server#3066]
- Operating System: macOS Catalina
- Node Version: 14.2.0
- NPM Version: 7.5.6
- webpack Version: 5.24.2
- webpack-dev-server Version: 3.11.2
- Browser: N/A

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.dev.js

devServer: {
    contentBase: path.join(__dirname, "dist"),
    open: {
      app: ["firefox", '--incognito'],
    },
    port: 9090,
  },
```

I have also tried 

```js
app: ["google chrome", '--incognito']
```

### Expected Behavior

Webpack Dev Server should open an incognito browser window.

### Actual Behavior

Webpack Dev Server instead opens the app in a regular Chrome or Firefox window. 

### For Bugs; How can we reproduce the behavior?

Use the config pasted above (as seen in the documentation here: https://webpack.js.org/configuration/dev-server/#devserveropen).

**Comment by jeffgore00** [comment]
I am also seeing this behavior, thanks for writing up this issue properly.

**Comment by alexander-akait** [comment]
> app: ["google chrome", '--incognito']

is invalid, name of binaries can be different, try to `google-chrome`, `chrome`, you can find more information here https://stackoverflow.com/questions/50138615/webdriverexception-unknown-error-cannot-find-chrome-binary-error-with-selenium

> app: ["firefox", '--incognito'],

invalid, `firefox` doesn't have `--incognito` option, you need use `app: ["firefox", '--private-window'],`

**Comment by TimeTerminal** [comment]
I also tried:

Firefox: `app: ["firefox", "--private-window"]`

Chrome: `app: ["chrome", "--incognito"]` and `app: ["google-chrome", "--incognito"]`

None of them worked.

Please reopen the issue as it is still broken.

**Comment by alexander-akait** [comment]
Tested right now and all works fine, nothing to fix here, if you need I can provide screenshots/video

**Comment by TimeTerminal** [comment]
Can you share your config please. It seems I'm not the only one who's having this problem.

**Comment by alexander-akait** [comment]
Only changes above, again you have different name, try to open CLI, and run `firefox --private-window`

**Comment by jeffgore00** [comment]
The issue is not how to open firefox in incognito. It is not a chrome binary that cannot be found. 

It is that we are following the documentation exactly and yet Chrome is opening in a regular window, not an incognito window.

**Comment by jeffgore00** [comment]
It should be noted that the current latest version of webpack-dev-server, 3.11.2, is dependent on the older version of open, `opn`, which is deprecated.

And as it turns out, there is an outstanding defect in that library related to incognito mode:
https://github.com/sindresorhus/open/issues/41

**Comment by alexander-akait** [comment]
oh, yep, fixed in `beta-1`, can be fixed in old version due `opn` deprecation

**Comment by TimeTerminal** [comment]
So is the idea to just wait for https://github.com/jeffgore00/ts-react-node-project-skeleton/issues/25 to be closed when the fix is applied to the stable release of webpack-dev-server?

**Comment by alexander-akait** [comment]
Yep, here fix https://github.com/webpack/webpack-dev-server/pull/3137/

**Comment by TimeTerminal** [comment]
Sweet, looking forward to it. Thanks for the update.
