### ISSUE TITLE
which WebpackEvent fire dev-server to delete dist folder？it s too early maybe

### ISSUE THREAD

**Issue by cuihee** [webpack/webpack-dev-server#3076]
- Operating System:not matter
- Node Version:not matter
- NPM Version:not matter
- webpack Version:5.18.0
- webpack-dev-server Version:3.11.2
- Browser:not matter

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

 我使用自定义的webpack插件来完成一个指定的动作。将我的文件合并成另一个文件。
我的webpack插件运行时机是compiler.hooks.afterEmit.tap(...)，这是我能找到的最早的可行的时机了，再早的话，文件还没有产生。

仅使用webpack的打包功能而不启动测试服务器，一切正常。

启动测试服务器，则会发生我的插件找不到指定文件的问题。我猜测是测试服务器插件过早的删除了dist文件夹。

特来求证，若是，则可否推迟测试服务器删除dist文件夹的时机或者可配置

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

delay dev-server del dist folder OR let user config its timing to delete dist folder

### Actual Behavior

(dev-server delete dist folder) too early to run my webpack plugin

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use english
