### ISSUE TITLE
Allow function as a devServer parameter to not be executed on `webpack -p` at all

### ISSUE THREAD

**Issue by extempl** [webpack/webpack-dev-server#3085]
- Operating System: OSX
- Node Version: 12.7
- NPM Version: 7.6.0
- webpack Version: 4.42.0
- webpack-dev-server Version: 3.11.2
- Browser: any

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

Basically the minimal valid code for understanding the issue is:
```js
  devServer: {
    port: new URL(process.env.SITE_URL).port || ''
  }
```

### Expected Behavior
Build as usual

### Actual Behavior
Failed build due to exception in `new URL` constructor because for other environments there are may be other strings in the env variables, like `` (empty), `/` or even a placeholder like `\_\_\_SITE_URL___`. All of these may be valid for build and not valid for dev environment (for which this config is at the first place).

So, I'd suggest possibility to pass function to the `devServer` to not be parsed on building at all, because now I have to create illogical function wrappers for situations like above, which does not have any sense on dev environment.

**Comment by alexander-akait** [comment]
You need to handle it on own side, out of scope webpack-dev-server
