### ISSUE TITLE
Unknown properties with v4

### ISSUE THREAD

**Issue by dlabrecq** [webpack/webpack-dev-server#3091]
- Operating System: Mac
- Node Version: v12.18.4
- NPM Version: 6.14.6
- webpack Version: 5.24.3
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: ersion 89.0.4389.82

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```
devServer: {
      stats,
      contentBase: false,
      historyApiFallback: {
        index: `${publicPath}index.html`,
      },
      // hot: !isProduction,
      hot: false, // default is true, which currently does not work with Insights and federated modules?
      port: 8002,
      disableHostCheck: true,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization',
      },
    },
```

### Expected Behavior

Expecting `disableHostCheck`, `contentBase`, and `stats` to be supported.

### Actual Behavior

> [webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
>  - configuration has an unknown property 'disableHostCheck'.
>  - configuration has an unknown property 'contentBase'. 
>  - configuration has an unknown property 'stats'.

Without the `disableHostCheck`, we encounter an "Invalid Host header" error in our UI.

### For Bugs; How can we reproduce the behavior?

This is our build target

"start": "webpack serve -c ./webpack.config.js",

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0
