### ISSUE TITLE
Update chokidar dependency to version 3 to remove deprecation warnings

### ISSUE THREAD

**Issue by KenEucker** [webpack/webpack-dev-server#3097]
- Operating System: Mac OS X
- Node Version: 15
- NPM Version: 7
- webpack Version: 5
- webpack-dev-server Version: 3.11.2
- Browser: Chrome

- [ x ] This is a **modification** request

### Code

```npm install webpack-dev-server```

### Expected Behavior
For webpack-dev-server to install without deprecation warnings.

### Actual Behavior
```
➜  react-testing-starter git:(production) ✗ npm ls urix
react-testing-starter@ /Users/keneucker/Dev/react-testing-starter
└─┬ webpack-dev-server@3.11.2
  └─┬ chokidar@2.1.8
    └─┬ braces@2.3.2
      └─┬ snapdragon@0.8.2
        └─┬ source-map-resolve@0.5.3
          └── urix@0.1.0

➜  react-testing-starter git:(production) ✗ npm ls resolve-url
react-testing-starter@ /Users/keneucker/Dev/react-testing-starter
└─┬ webpack-dev-server@3.11.2
  └─┬ chokidar@2.1.8
    └─┬ braces@2.3.2
      └─┬ snapdragon@0.8.2
        └─┬ source-map-resolve@0.5.3
          └── resolve-url@0.2.1
```

### For Bugs; How can we reproduce the behavior?

List out the dependencies to see what is including the deprecated code, with `npm ls resolve-url` or the like.

### For Features; What is the motivation and/or use-case for the feature?

chokidar version 3 is supposed to have "15x less dependencies than version 3", so it seems to be a good update overall. I think it's important for a package used by millions of projects to not have any warnings upon installation. This is an easier win than others in that regard.

**Comment by alexander-akait** [comment]
Fixed in beta-0

**Comment by KenEucker** [comment]
@alexander-akait do you mean certain 4 beta 0? Because this is a simple dependency update and the currently published version of this package is not 4 beta 0. 

When will v4 be released? My thoughts are that waiting for this simple change in v4 is unreasonable when this deprecation warning has been present for months now.

**Comment by alexander-akait** [comment]
Because it is impossible, it is breaking change

**Comment by alexander-akait** [comment]
Fixed in master, stable v4 release will be by the end of the month
