### ISSUE TITLE
Bad opened url with 4.0.0-beta.0

### ISSUE THREAD

**Issue by martonx** [webpack/webpack-dev-server#3100]
- Operating System: latest Windows 10
- Node Version: v14.15.4
- NPM Version: 6.14.10
- webpack Version: 5.26.3
- webpack-dev-server Version: 4.0.0-beta.0
- Browser: Chrome

- [X] This is a **bug**
- [ ] This is a **modification** request

```js
devServer: {
  https: true,
  static: [
	  {
		  directory: path.resolve(__dirname, 'wwwroot'),
		  publicPath: '/dist/',
	  },
  ],
  open: true,
  openPage: 'hu-HU',
  port: 8090,
  proxy: {
	  target: 'http://localhost:51001/',
	  secure: false,
	  context(pathname, req) {
		  // See Vue-cli codebase for a real example
		  // https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/prepareProxy.js 
  
		  // Do not proxy requests to public files or hot reload web-socket
		  if (!mayProxy(pathname)) return false;
		  // Directly proxy non-GET requests
		  if (req.method !== 'GET') return true;
		  // Do not proxy requests to root "/". Let them be handled by 
		  // webpack-dev-server which will return the index.html
		  return pathname !== "/";
	  }
  }
},
```

### Expected Behavior
open https://localhost:8090/hu-HU

### Actual Behavior
open https://[::]:8090/hu-HU

### For Bugs; How can we reproduce the behavior?
I'm pretty sure, you can reproduce this [::] instead of localhost behaviour easily with any default webpack template on windows 10. Before webpack 5 (and dev server of course) update my opened url was https://localhost:8090/hu-HU and now it is https://[::]:8090/hu-HU

Why? What else should I configure?

**Comment by alexander-akait** [comment]
Bug, fixed in master, release will be today
