### ISSUE TITLE
Automatically open browser

### ISSUE THREAD

**Issue by claycephas** [webpack/webpack-dev-server#311]
Please add a flag to `webpack-dev-server` that will automatically open the browser to the configured url.

**Comment by SpaceK33z** [comment]
Can you test if #329 works as you would expect?

**Comment by craigcosmo** [comment]
should have option to define which browser to use

**Comment by Milewski** [comment]
and is it possible to open open something else?... let`s say open `/something/else`

**Comment by MattyBalaam** [comment]
https://github.com/webpack/webpack-dev-server/pull/749

**Comment by bennyn** [comment]
Is `--open` exposed to webpack's Node.js API? I would like to do this:

```javascript
new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: true,
  historyApiFallback: true,
  inline: true,
  stats: { colors: true },
  headers: { 'Access-Control-Allow-Origin': '*' },
  open: 'http://localhost:8081'
}).listen(8081, 'localhost', function (err, result) {
  if (err) {
    return console.log(err);
  }
  console.log('Listening at http://localhost:8081/');
});

```

**Comment by wesleymostien** [comment]
@bennyn did you manage to do this ?

**Comment by Lamorale** [comment]
In my webpack.config.js:
`devServer: {
    open: false
}`
does not prevent webpack to open app in new page.
I am using webpack 3.6.0 webpack-dev-server 2.9.1

Does it work for anyone?

**Comment by cyrusmith** [comment]
For me ```devServer: { open: false }``` doesn't work eaither.

**Comment by emilio-martinez** [comment]
@SpaceK33z I'm trying to use the `open` option on a webpack config via the Node API based on https://webpack.js.org/configuration/dev-server/#devserver-open. However, it won't work. Is this supposed to work outside of the CLI?

**Comment by njleonzhang** [comment]
devServer: { open: false } doesn't work either.

**Comment by gluons** [comment]
@emilio-martinez I face the same problem as you.

Seems that `open` option is only used in CLI.

https://github.com/webpack/webpack-dev-server/blob/d0725c98fb752d8c0b1e8c9067e526e22b5f5134/bin/utils.js#L41-L89

https://github.com/webpack/webpack-dev-server/blob/d0725c98fb752d8c0b1e8c9067e526e22b5f5134/bin/webpack-dev-server.js#L30-L36

https://github.com/webpack/webpack-dev-server/blob/d0725c98fb752d8c0b1e8c9067e526e22b5f5134/bin/webpack-dev-server.js#L404

https://github.com/webpack/webpack-dev-server/blob/d0725c98fb752d8c0b1e8c9067e526e22b5f5134/bin/webpack-dev-server.js#L419

So, no way to open browser via Node API. ☹️
