### ISSUE TITLE
webpack-dev-server@4.0.0-beta.1, ie 11 error, SCRIPT5009: 'Symbol' is not defined.

### ISSUE THREAD

**Issue by demonguyj** [webpack/webpack-dev-server#3110]
- Operating System: windows 10
- Node Version: 12.18.3
- NPM Version: 6.14.9
- webpack Version: 5.28.0
- webpack-dev-server Version: 4.0.0-beta.1
- Browser: IE11

- [ ] This is a **bug**
- [V] This is a **modification** request

### Code

```js
// webpack.config.js
```
target = `browserslist`
browserslist: last 3 versions, > 5%, not dead
devServer = {
		compress: true,
		dev: {
			publicPath: `/`,
		},
		host: `localhost`,
		hot: false,
		// liveReload: false,
		open: true,
		openPage: `${configMode}/html/`,
		port: 8080,
		static: path.resolve(__dirname, ``),
	}

```js
// additional code, remove if not needed.
```

vendor.js
![image](https://user-images.githubusercontent.com/3590419/112597564-9c8dd200-8e50-11eb-89dc-77ea838449da.png)

![image](https://user-images.githubusercontent.com/3590419/112597548-9697f100-8e50-11eb-80c9-52e321441141.png)

### Expected Behavior
Errors not showing.

### Actual Behavior
Errors show and not working.

**Comment by alexander-akait** [comment]
You need polyfill `Symbol`
