### ISSUE TITLE
onBeforeSetupMiddleware server isn't accessible

### ISSUE THREAD

**Issue by jimblue** [webpack/webpack-dev-server#3121]
- Operating System: MacOS v11.2.3
- Node Version: v15.12.0
- NPM Version: v7.7.5
- webpack Version: v5.28.0
- webpack-dev-server Version: v4.0.0-beta.1
- Browser: Chrome ARM v89.0.4389.90

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

When I was using `webpack-dev-server v3`, I was configuring the before option  like below.

```js
// webpack.config.js

 before(app, server) {
    const files = [
      path.resolve(rootFolder, 'resources/views/**/*.html.twig'),
      path.resolve(rootFolder, 'content/collections/**/*.md')
    ]

    // Reload the browser on content/template files change
    chokidar.watch(files).on('all', () => {
      server.sockWrite(server.sockets, 'content-changed')
    })
  },
```

Since I've upgrade to `webpack-dev-server v4.0.0-beta.1` this is not working even if I've follow the release notes.
I'm getting an error : `TypeError: Cannot read property 'sockWrite' of undefined`
I've looked at the source code to understand how the new `onBeforeSetupMiddleware` but sadly, nothing I've tried worked...

Any help would really appreciated, thank you 😅 !

```js
// webpack.config.js

 onBeforeSetupMiddleware({ server, sockets }) {
    const files = [
      path.resolve(rootFolder, 'resources/views/**/*.html.twig'),
      path.resolve(rootFolder, 'content/collections/**/*.md')
    ]

    // Reload the browser on content/template files change
    chokidar.watch(files).on('all', () => {
      server.sockWrite(sockets, 'content-changed')
    })
  },
```

**Comment by alexander-akait** [comment]
hm, it is private API, why you need this?

**Comment by jimblue** [comment]
hi @alexander-akait, to automatically reload the browser when I change a `Twig` template file or a `mardown` content file.
It speed up dev workflow a lot by preventing to manually reload the browser on a any changes.

**Comment by jimblue** [comment]
If you want to keep this API private, we could maybe add an option to handle this case internally ?

**Comment by alexander-akait** [comment]
hm, we can implement option `watchFiles: string | { paths, options }`, so you can watch files without dirty hacks

**Comment by jimblue** [comment]
That would be awesome and cleaner for sure 😄

**Comment by anshumanv** [comment]
https://github.com/webpack/webpack-dev-server/blob/cd39491ea395c985f2014dfc03379db5c894f711/lib/Server.js#L989 should work for this case, right? we can just read the watch files from the option and pass it to this watcher or is this specific for static option?

**Comment by alexander-akait** [comment]
Yep, easy to implement, just pass this options to `watchFiles`, i.e. `const watchers = watchFiles.map((item) => watchFiles(item.path, item.options))`, move this code to `setupWatchFiles` method, don't forget to close them in `close` method and add CLI option for this

**Comment by anshumanv** [comment]
got it, thanks

**Comment by jimblue** [comment]
> got it, thanks

Can I help you ?

**Comment by anshumanv** [comment]
Thanks but PR is ready 😄

**Comment by jimblue** [comment]
Can't believe how fast this feature as been implemented, thank you guys ❤️

**Comment by alexander-akait** [comment]
Anyway you can fix your code (should work):
```js
onBeforeSetupMiddleware(devServer) {
    const files = [
      path.resolve(rootFolder, 'resources/views/**/*.html.twig'),
      path.resolve(rootFolder, 'content/collections/**/*.md')
    ]

    // Reload the browser on content/template files change
    chokidar.watch(files).on('all', () => {
      devServer.sockWrite(sockets, 'content-changed')
    })
  },
```

**Comment by jimblue** [comment]
Hey @alexander-akait in the above code `socket` is not defined.
But even by fixing it by using `devServer.sockets` instead, it doesn't work because it returns an empty array.

```
onBeforeSetupMiddleware(devServer) {
    // Reload the browser on content/template files change
    chokidar.watch([WEBPACKER_SETTINGS.files.template, WEBPACKER_SETTINGS.files.content], { ignoreInitial: true }).on('all', () => {
      devServer.sockWrite(devServer.sockets, 'content-changed')
    })
  },
```

Anyway, I can totally wait for a new release with the merge PR to use this feature now 😄  !

**Comment by alexander-akait** [comment]
`devServer.sockets` is empty only on initial stage, after it should contain array of socket contentions... I think I will do release tomorrow/after tomorrow

**Comment by flyyang** [comment]
The new release seems not work for me. I tried the sockWrite option，but the this.socketServer seems to be undefined.

  sockWrite(sockets, type, data) {
    sockets.forEach((socket) => {
      this.socketServer.send(socket, JSON.stringify({ type, data }));
    });
  }

**Comment by alexander-akait** [comment]
@flyyang because you need wait when socket server starts

**Comment by jimblue** [comment]
Perfectly working ! Thank you so much @alexander-akait / @anshumanv ❤️

**Comment by llwor94** [comment]
FYI if anyone is here with this question on version 4.2.1, `devServer.sockWrite` has been renamed to `devServer.sendMessage` and you'll want to use `devServer.webSocketServer.clients` instead of `devServer.sockets` !!

```
devServer.sendMessage(devServer.webSocketServer.clients, 'content-changed');
```

**Comment by alexander-akait** [comment]
Why you use internal API?

**Comment by llwor94** [comment]
Live reload federated micro-app in host application:

```
devServer.app.get('/mfe-change', (req, res) => {
    devServer.sendMessage(devServer.webSocketServer.clients, 'content-changed');
    res.sendStatus(200);
  });
```

**Comment by alexander-akait** [comment]
we have built-in `/webpack-dev-server/invalidate` route for this case

**Comment by llwor94** [comment]
I'll check it out, thanks!

**Comment by sbussard** [comment]
> Why you use internal API?

To get it to work with `ibazel`

**Comment by DimaGashko** [comment]
@alexander-akait 

> Why you use internal API?
> /webpack-dev-server/invalidate

We need to restart our API server when change .tmpl, .go files and only then reload the page.
Built-in route like `/webpack-dev-server/invalidate` would be great, but it looks like it's just loggin to the console: 

`[HMR] Nothing hot updated. [HMR] App is up to date.`

Have I missed something?

**Comment by nitin-io** [comment]
> FYI if anyone is here with this question on version 4.2.1, `devServer.sockWrite` has been renamed to `devServer.sendMessage` and you'll want to use `devServer.webSocketServer.clients` instead of `devServer.sockets` !!
> 
> ```
> devServer.sendMessage(devServer.webSocketServer.clients, 'content-changed');
> ```

When I am using this code and changing anything in HTML it refreshes the page instead of HMR?
```onBeforeSetupMiddleware(devServer) {
      chokidar
        .watch(resolve(__dirname, 'src', 'index.html'))
        .on('all', () =>
          devServer.sendMessage(
            devServer.webSocketServer.clients,
            'content-changed'
          )
        );
    },```

**Comment by joemaller** [comment]
The websocket message to trigger a reload was changed in v5. At the very bottom of the [v4 -> v5 Migration Guide's Breaking Changes](https://github.com/webpack/webpack-dev-server/blob/master/migration-v5.md#-breaking-changes):

> The `content-changed` method was removed in favor of the `static-changed` method from `onSocketMessage`.

This code still works perfectly once the message string is changed to **`static-changed`**:

```js
devServer.sendMessage(devServer.webSocketServer.clients, 'static-changed');
```
