### ISSUE TITLE
allowedHost, disableHostCheck not available with function export

### ISSUE THREAD

**Issue by devkral** [webpack/webpack-dev-server#3133]
- Operating System: linux
- Node Version: v10.19.0
- NPM Version: 6.14.4
- webpack Version: 5.28
- webpack-dev-server Version: 4.0.0-beta.1
- Browser: x

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Fails:
```js
// webpack.config.js
module.exports = (env, options) => {
  return {
       devServer: {
        allowedHosts: ["fooo"],
        disableHostCheck: true
    }
  }
}
```

Works:
```js
// webpack.config.js
module.exports = {
       devServer: {
        allowedHosts: ["fooo"],
        disableHostCheck: true
    }
  }
```

### Expected Behavior

Should accept the options like with an static export

### Actual Behavior

Crashes with: 
Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'allowedHosts'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }

### For Bugs; How can we reproduce the behavior?
see example

**Comment by devkral** [comment]
could solve the issue: options are renamed to firewall, no-firewall. But still this is inconsistent and should be fixed.

**Comment by snitin315** [comment]
I am unable to reproduce. `allowedHosts` doesn't work in both cases as expected.

**Comment by alexander-akait** [comment]
> But still this is inconsistent and should be fixed.

Don't see what is inconsistent, you can enable disable and you can specify it using `firewall: ['allowed', 'host']`
