### ISSUE TITLE
Index page is invalid when contentBasePublicPath contains duplicate item

### ISSUE THREAD

**Issue by pandanoir** [webpack/webpack-dev-server#3135]
- Operating System: Mac
- Node Version: 14.16.0
- NPM Version: 6.14.11
- webpack Version: 5.28.0
- webpack-dev-server Version: 3.11.2
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
module.exports = {
  // ...
  devServer: {
    contentBase: [
      path.join(__dirname, 'js1'),
      path.join(__dirname, 'js2'),
      path.join(__dirname, 'css'),
    ],
    contentBasePublicPath: ['/static/js', '/static/js', '/static/css'],
  },
};
```

### Expected Behavior

- `/static/js` shows whole js1 and js2 items.

### Actual Behavior

- `/static/js` shows only js1 items.

**Comment by alexander-akait** [comment]
Yep, it is bug, fixed  in `beta-1`, please use the `static` option, stable release soon
