### ISSUE TITLE
v4.0.0-beta.1 how can i set mimeTypes

### ISSUE THREAD

**Issue by ckken** [webpack/webpack-dev-server#3139]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- webpack-dev-server Version:
- Browser:

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by alexander-akait** [comment]
Please use `dev.mimeTypes`

**Comment by ckken** [comment]
do not work, has some example for it

**Comment by alexander-akait** [comment]
`dev.mimeTypes` setup mimeTypes for webpack files, in other case you need own middleware

**Comment by ckken** [comment]
like this? https://github.com/efoxTeam/emp/blob/98fbd479ed6269394128f73934d5f917cc891b6c/packages/emp-cli/webpack/config/devServer.js#L8

**Comment by alexander-akait** [comment]
If it is file from webpack - yes, if it is file from `static`, you need setup `staticOptions`

**Comment by ckken** [comment]
no work : https://github.com/efoxTeam/emp/blob/6ac56424f64739e01870f4e66da6d10146697af1/packages/emp-cli/webpack/config/devServer.js#L46

**Comment by alexander-akait** [comment]
Sorry, won't fix, you missing the issue template

**Comment by ckken** [comment]
https://github.com/webpack/webpack-dev-server/blob/cd39491ea395c985f2014dfc03379db5c894f711/lib/Server.js#L310

**Comment by ckken** [comment]
https://github.com/webpack/webpack-dev-server/blob/cd39491ea395c985f2014dfc03379db5c894f711/lib/Server.js#L310
https://github.com/efoxTeam/emp/blob/d6abb7000e4c8400cf3e819ba3379cc2e393beaf/packages/emp-cli/webpack/config/devServer.js#L47
fixed it
