### ISSUE TITLE
new webpack.NamedModulesPlugin() Error after Upgrading

### ISSUE THREAD

**Issue by JF0001** [webpack/webpack-dev-server#3147]
- Operating System: Ubuntu 18.04
- Node Version: v10.16.0
- NPM Version: 6.14.7
- webpack Version: 5.30.0
- webpack-dev-server Version: 3.11.2
- Browser: Latest Chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Actual Behavior

I have upgraded webpack from version 2.7.0 to 5.30.0 and webpack-dev-server from version 2.11.5 to 3.11.2. Upon building my project, I am now obtaining the following error:

new webpack.NamedModulesPlugin(), TypeError: webpack.NamedModulesPlugin is not a constructor

I understand that this plugin has been deprecated, but I am not finding anywhere on how to properly remove it from my config file. If I comment it out, I obtain another error.

More generally, is there a way to have the build process re-create the config file without me having to edit it manually? I have tried removing it from the folder, but this doesn't work.

Thank you. J.

**Comment by alexander-akait** [comment]
`NamedModulesPlugin` was removed, you need, please read https://webpack.js.org/migrate/5/#update-outdated-options when you update webpack

**Comment by JF0001** [comment]
Thank you @alexander-akait Yes, I had read this info. However, I am not sure how to fix it in my config file. Sorry, I am new to node.js.

**Comment by alexander-akait** [comment]
Just remove `webpack.NamedModulesPlugin` from `webpack.config.js` or provide link on webpack.config.js and will help

**Comment by JF0001** [comment]
Thanks again. Yes, I had tried this, but then I receive the following error:

node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:104
throw new _ValidationError.default(errors, schema, configuration);
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.

**Comment by alexander-akait** [comment]
You need update options for `copy-webpack-plugin`
