### ISSUE TITLE
Using the bypass proxy for routing results in the loss of POST parameters.

### ISSUE THREAD

**Issue by jsonhet** [webpack/webpack-dev-server#3164]
**Sorry, my English is poor. I hope I can describe the problem clearly.**
**bug:**
Using the bypass proxy for routing results in the loss of POST parameters.
**bug recurrence：**
Back-end server address: http://localhost:8066
vue web server address: http://localhost:8080  (This question doesn't seem to have anything to do with whether the project is Vue or Angular)
Routing post request need agent to the backend on port 8066, but the http://localhost:8080/login get request don't need agent to the backend port 8066, or of else the vue login page is gone.This problem can be the reference document: https://webpack.js.org/configuration/dev-server/#devserver-proxy using bypass can solve the problem, this is very good.But I found the backend application http://localhost:8066/login Parameter lost when route receives POST request., such as the following pictures show:
![image](https://user-images.githubusercontent.com/31009976/113955151-c631fa80-984d-11eb-81fd-2ed636ac79c2.png)

 This is the submitted data ‘|’

![image](https://user-images.githubusercontent.com/31009976/113955191-d6e27080-984d-11eb-9d78-9a51be093df3.png)

This is the request that was received by the back end, and you can see that the POST data has been lost.

Maybe this is a real bug.
Webpack, as a mature tool, may have a good solution but I don't know.If so, please provide me with some help. Thank you.

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by pastelmind** [comment]
I'm experiencing a similar bug in a create-react-app setup. webpack-dev-server (running at `localhost:3000`) is stripping out my form parameters in a POST request before proxying it to the backend at `localhost:60080`.

**Comment by jsonhet** [comment]
@pastelmind  Have you solved the problem yet? How is it configured?

**Comment by pastelmind** [comment]
@jsonhet My server was custom-built on top of low-level TCP/IP APIs. Previously, it didn't know that HTTP headers are case-insensitive. So it parsed `Content-Length: 1000` fine but didn't recognize `content-length: 1000`.

If you're using a Node.js server, this is probably unrelated to whatever problem you are facing.

**Comment by alexander-akait** [comment]
Answered
