### ISSUE TITLE
No way to enable hot mode without using deprecated hot: true in config

### ISSUE THREAD

**Issue by zeen** [webpack/webpack-dev-server#32]
If I run with --hot and/or with the HotModuleReplacementPlugin, options.hot in Server.js remains undefined.

I tried tracking this in webpack-dev-server.js:
##### When using `--hot` and `HotModuleReplacementPlugin`:

`optimist.argv.hot == true &&
wpOpt.hot == undefined &&
options.hot == undefined`
##### When using `hot:true` in config:

`optimist.argv.hot == true &&
wpOpt.hot == true &&
options.hot == true`

**Comment by Sawtaytoes** [comment]
I just started getting this error after an update yesterday.

Did something change recently? If I don't put `hot: true`, I don't get hotloading even w/ the plugin there.
