### ISSUE TITLE
4.0.0beta.2 breaks in IE11 on `punycode` arrow function

### ISSUE THREAD

**Issue by gersomvg** [webpack/webpack-dev-server#3209]
- Operating System: MacOS Big Sur
- Node Version: 14.15.3
- NPM Version: 6.14.11
- webpack Version: 5.33.2
- webpack-dev-server Version: 4.0.0-beta.2
- Browser: IE11

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
  const { preprocess } = require('../../svelte.config')(wallpaperPath);

  const uiRoot = path.resolve(__dirname, '../../');
  const outputPath = path.resolve(wallpaperPath, 'dist/development');

  const config = {
    entry: {
      bundle: path.resolve(uiRoot, 'src/wallpaper/main.js'),
    },
    context: uiRoot,
    resolve: {
      modules: [
        path.resolve(uiRoot, 'node_modules'),
        path.resolve(wallpaperPath, 'node_modules'),
      ],
      alias: {
        wallpaper: wallpaperPath,
      },
      extensions: ['.mjs', '.js', '.svelte'],
      mainFields: ['svelte', 'browser', 'module', 'main'],
    },
    output: {
      path: outputPath,
      filename: '[name].[contenthash].js',
      chunkFilename: '[name].[contenthash].js',
      assetModuleFilename: '[name].[contenthash][ext]',
    },

    module: {
      rules: [
        {
          test: /\.m?jsx?$/,
          use: {
            loader: 'babel-loader',
            options: babelLoaderOptions,
          },
          include: [
            {
              and: [uiRoot],
              not: [path.resolve(uiRoot, 'node_modules')],
            },
            {
              and: [wallpaperPath],
              not: [path.resolve(wallpaperPath, 'node_modules')],
            },
          ],
          resolve: {
            fullySpecified: false,
          },
        },
        {
          test: /\.svelte$/,
          use: [
            {
              loader: 'babel-loader',
              options: babelLoaderOptions,
            },
            {
              loader: 'svelte-loader',
              options: {
                preprocess,
                compilerOptions: {
                  dev: mode !== 'production',
                },
                emitCss: false,
                hotReload: mode !== 'production',
              },
            },
          ],
        },
        {
          test: /\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf|mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
          type: 'asset',
        },
      ],
    },

    mode,

    plugins: [
      new webpack.DefinePlugin({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode),
      }),

      new HtmlWebpackPlugin({
        template: path.resolve(__dirname, '../wallpaper/index.html'),
        inject: 'body',
      }),

      new CopyPlugin({
        patterns: [
          {
            from: path.resolve(wallpaperPath, 'static'),
            to: path.resolve(outputPath, 'static'),
            noErrorOnMissing: true,
          },
        ],
      }),
    ],

    devtool: mode === 'production' ? false : 'source-map',
  }
```

```js
// Dev server config
const options = {
      port: 8000,
      dev: { publicPath: '/wallpaper/' },
      liveReload: false,
      hot: false,
      client: {
        needClientEntry: false,
        needHotEntry: false,
        overlay: false,
        logging: 'none',
      },
      static: [
        path.resolve(__dirname, '../preview-frame'),
      ]
    };

    const devServer = new WebpackDevServer(compiler, options);

    console.log('Starting server at http://localhost:8000');

    devServer.listen(options.port, 'localhost', (e) => {
      if (e) console.error(e);
    });
```

### Expected Behavior

Expected this to work in IE11, especially since `liveReload` and `hot` are disabled in this test.

### Actual Behavior

IE11 breaks on this arrow function:

```js
// @memberOf punycode.ucs2
const ucs2encode = array => String.fromCodePoint(...array);
```

### For Bugs; How can we reproduce the behavior?

I find it hard to pinpoint a 100% for sure if this `punycode` package is coming from webpack-dev-server, but without webpack-dev-server (using a older browsersync setup) the code runs fine in IE11.

**Comment by gersomvg** [comment]
Hm, `target: "es5"` in the webpack config seems to solve it. Which is weird because I have a .browserslistrc set up with:

```
> 0.5%, last 2 versions, Firefox ESR, not dead
```

**Comment by gersomvg** [comment]
Unrelated question now that we're at IE11 anyway: is the client supposed to not break in IE11 or was the aim to have actual LiveReload / HMR working as well? Because now that it doesn't break for me, those last two still don't work.

Just wondering out of curiosity, because I'm already super happy that it works to begin with in IE11; I can now just use CMD-R while developing there.

**Comment by alexander-akait** [comment]
@gersomvg What is broken? Please when you write about error/bug provide more infromation, tested in IE9 and latest chrome and all works fine :confused:

**Comment by gersomvg** [comment]
@alexander-akait You're right, I could've done a better job narrowing this down.

I made a minimal reproduction in this repo:
https://github.com/gersomvg/wds-ie11

I did get it to work actually in IE11 as well! The error I encountered can be reproduced by commenting out this line:
https://github.com/gersomvg/wds-ie11/blob/main/bundler/getWebpackCompiler.js#L45

As it is quite common to exclude node_modules from babel transpilation, it is kind of unexpected that this specific dependency needs to be included.

I'm wondering how it looks like in your setup? Do you include node_modules completely, or are you also whitelisting specific dependencies?

**Comment by alexander-akait** [comment]
If you node_modules contains ES6+ code you need enable `babel-loader` for this, I recommend to use allowed list if you use many deps, but if you don't want to bother you can apply this to the whole code, i.e. transpile `node_modules`

**Comment by gersomvg** [comment]
Correct! I was already whitelisting `svelte` in my project. I was just not aware of the need to whitelist `punycode` as well. This is a dependency of:

```
webpack-dev-server -> url -> punycode
```

Maybe we should add this to a IE9-11 readme? I saw some docs regarding polyfilling `fetch` and `promise` separately for WDS but that was mentioned in a CHANGELOG only.

Thanks for chiming in anyway @alexander-akait and for your work on this repo. The fact that HMR works at all now in IE11 far exceeded my expectations lol 😅

**Comment by alexander-akait** [comment]
hm, give me time to check

**Comment by alexander-akait** [comment]
Do you have local `punycode`? Can you run `npm ls punycode`?

**Comment by gersomvg** [comment]
```
foobar@0.0.30-3 /Users/me/projects/foobar
├─┬ babel-loader@8.2.2
│ └─┬ schema-utils@2.7.1
│   └─┬ ajv@6.12.6
│     └─┬ uri-js@4.4.1
│       └── punycode@2.1.1
├─┬ jest@26.6.3
│ └─┬ @jest/core@26.6.3
│   └─┬ jest-config@26.6.3
│     └─┬ jest-environment-jsdom@26.6.2
│       └─┬ jsdom@16.5.3
│         ├─┬ request@2.88.2
│         │ └─┬ tough-cookie@2.5.0
│         │   └── punycode@2.1.1  deduped
│         ├─┬ request-promise-native@1.0.9
│         │ └─┬ tough-cookie@2.5.0
│         │   └── punycode@2.1.1  deduped
│         ├─┬ tough-cookie@4.0.0
│         │ └── punycode@2.1.1  deduped
│         └─┬ whatwg-url@8.5.0
│           └─┬ tr46@2.0.2
│             └── punycode@2.1.1  deduped
└─┬ webpack-dev-server@4.0.0-beta.2
  └─┬ url@0.11.0
    └── punycode@1.3.2
```

**Comment by alexander-akait** [comment]
Found problem, you change ` mainFields: ["browser", "module", "main"],`, don't touch this if you don't undestand why do you do it, now you prefer `module` over `main`, so in your bundle es6 code and you need babel to fix problems in old browsers

**Comment by alexander-akait** [comment]
In future most of packages will use https://nodejs.org/api/packages.html#packages_conditional_exports, so when we use `require` we will use `require` version and this problem was solved on ecosystem level

**Comment by gersomvg** [comment]
Hm, this originated in the official boilerplate I cloned last August: https://github.com/sveltejs/template-webpack/blob/master/webpack.config.js. I usually don't add stuff myself before I understand it fully 😅 

I guess that that boilerplate (and Svelte in general) doesn't try to be compatible with older browsers.

Good find! 🙏🏻  I'll try and switch those two around to see if it doesn't introduce any new issues.

Thanks for your time 😊

**Comment by gersomvg** [comment]
@alexander-akait Btw, I tried this and switching `main` and `module` doesn't work. The `main` (commonjs) version also has arrow functions.

The docs of `punycode` states this:

> This project was bundled with Node.js from v0.6.2+ until v7 (soft-deprecated).
> 
> The current version supports recent versions of Node.js only. It provides a CommonJS module and an ES6 module. For the old version that offers the same functionality with broader support, including Rhino, Ringo, Narwhal, and web browsers, see v1.4.1.

So whitelisting it for babel is the way to go!
