### ISSUE TITLE
chokidar package is outdate having glob-parent as vulnerable package version.

### ISSUE THREAD

**Issue by prashant93** [webpack/webpack-dev-server#3216]
npm ls glob-parent:

+-- @angular-devkit/build-angular@0.1102.10
| +-- copy-webpack-plugin@6.3.2
| | +-- fast-glob@3.2.5
| | | `-- glob-parent@5.1.2  deduped
| | `-- glob-parent@5.1.2  deduped
| +-- webpack@4.44.2
| | `-- watchpack@1.7.5
| |   `-- watchpack-chokidar2@2.0.1
| |     `-- chokidar@2.1.8
| |       `-- glob-parent@3.1.0
| `-- webpack-dev-server@3.11.2
|   `-- chokidar@2.1.8
|     `-- glob-parent@3.1.0
+-- @angular/compiler-cli@11.2.11
| `-- chokidar@3.5.1
|   `-- glob-parent@5.1.2  deduped
`-- eslint@6.8.0
  `-- glob-parent@5.1.2

**Comment by prashant93** [comment]
When webpack is planning to realease the updated version.

**Comment by alexander-akait** [comment]
Update `copy-webpack-plugin`, update webpack v5 and you can update `webpack-dev-server@4-beta` (stable release soon)
