### ISSUE TITLE
Send all arguments from the progress to the client, not only the first one.

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack-dev-server#3217]
@alexander-akait webpack-dev-server should probably send all arguments from the progress to the client, not only the first one. There would be a plugin name in the selected message, but it's not shown here.

_Originally posted by @sokra in https://github.com/webpack/webpack/issues/12102#issuecomment-825148086_

**Comment by snitin315** [comment]
on it 👍🏻
