### ISSUE TITLE
overflow error text rendered light-on-white

### ISSUE THREAD

**Issue by 0x80** [webpack/webpack-dev-server#322]
When using webpack-dev-server iframe view, the error text is rendered so that it overflows. The text is light gray on a red background, but because the html body is white it becomes hard to read when you scroll to the right.

Making the body background-color something like black or the same color red would solve this?

Ideally the pre element rendering the text would wrap the lines to stay inside the width of the viewport, but I don't know if that is possibe.

![screenshot 2015-11-19 11 41 06](https://cloud.githubusercontent.com/assets/1193520/11268992/5acca176-8eb4-11e5-8e72-91dccdb744c6.png)

**Comment by SpaceK33z** [comment]
This issue should be fixed with #330.
