### ISSUE TITLE
This trailing slash after publicPaths

### ISSUE THREAD

**Issue by 205g0** [webpack/webpack-dev-server#3225]
- Operating System: ubuntu 20.04
- Node Version: 15.14
- NPM Version: pnpm 
- webpack Version: 5.35.1
- webpack-dev-server Version: 3.11.2
- Browser: Firefox 88

- [ ] This is a **bug**
- [x] This is a **modification** request

Since it's documented I guess it's not a bug but I find this behavior counter-intuitive creating some confusion. So, if there isn't a technical reason for having this oddity why not change it.

### Code

```
 devServer: {
   compress: true,
   host: '0.0.0.0',
   public: 'example.com',
   publicPath: `/somePath/`,
   sockPath: `/somePath/sockjs-node`,
 },
```

### Expected Behavior

`webpack-dev-server`/`webpack serve` needs to have this trailing `/` in the `publicPath` definition and when you enter the URL into your browser, e.g. you have to enter `example.com/route/` and can't use `example.com/route` to get to `example.com/route`'s index page.

People would expect that a plain `example.com/route` would bring them to `example.com/route`'s index page.

### Actual Behavior

You have to enter `example.com/route/` and can't use `example.com/route` to get to `example.com/route`'s index page.

### For Features; What is the motivation and/or use-case for the feature?

Better UX/UI.

**Comment by alexander-akait** [comment]
Not related to webpack-dev-server, it is based how you setup own app, you can handle `/route` and `route/` as one request or handle in different way, we don't change your application logic or something else. You can set `publicPath: '/some-path'` with trailing slash, but in most cases it is wrong and invalid.
