### ISSUE TITLE
HMR not work if css changed

### ISSUE THREAD

**Issue by wiseadme** [webpack/webpack-dev-server#3227]
If I'll change any css rules HMR don't reload the page, but if I'll change HTML document it works fine.

- Operating System:
- Node Version: 12.22.1
- NPM Version: 7.9.0
- webpack Version: 5.35.1
- webpack-dev-server Version: 4.0.0-beta.2
- Browser: Chrome

https://github.com/wiseadme/hmr-problem

- [x ] This is a **bug**

### Expected Behavior
it should reload page on scss update

### Actual Behavior
hot reload not work on style updates

### For Bugs; How can we reproduce the behavior?
1) clone repository https://github.com/wiseadme/hmr-problem.git
2) install dependencies 
3) npm run dev
4) change scss variable $main-color in src/styles/main.scss

### For Features; What is the motivation and/or use-case for the feature?
for comfortable work on any project

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please answer on all questions. There are a different things can break your hot realoding. I will reopen the issue after your fix it, thanks

**Comment by wiseadme** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Please answer on all questions. There are a different things can break your hot realoding. I will reopen the issue after your fix it, thanks

I changed the description of the problem and i hope that you can help me to solve it

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/mini-css-extract-plugin/issues/444, do not use `[hash]` in development mode, we will improve it in the next major release of mini-css-extract-plugin, because it is breaking change, sorry for this problem, CSS is not simple for bundling and HMR

**Comment by wiseadme** [comment]
> Duplicate [webpack-contrib/mini-css-extract-plugin#444](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/444), do not use `[hash]` in development mode, we will improve it in the next major release of mini-css-extract-plugin, because it is breaking change, sorry for this problem, CSS is not simple for bundling and HMR

Ok. Thank you!
