### ISSUE TITLE
v4.0.0-beta.2 proxy logLevel silent does not work

### ISSUE THREAD

**Issue by jasperkuperus** [webpack/webpack-dev-server#3234]
- Operating System: macOS
- Node Version: v12.16.2
- NPM Version: 6.14.4
- webpack Version: 5.26.0
- webpack-dev-server Version: 4.0.0-beta.2
- Browser: Chrome

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
{
  // ...
  devServer: {
    proxy: {
      '/my-path': {
        target: 'http://localhost:1234',
        logLevel: 'silent',
      },
    },
  },
}
```

### Expected Behavior

IF any errors occur in this proxy rule (in my case they sometimes do happen, which is OK), I expect the `logLevel: 'silent'` to silent them. In the previous version of `webpack-dev-server` I used (`3.11.2`), this was in fact the case.

### Actual Behavior

Now it ignores the `logLevel: 'silent'` for the proxy and logs the error:

```
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:8080/config to http://localhost:1234 [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

The error is correct, but I want it to be silenced, as it was possible in `3.11.2`.

### For Bugs; How can we reproduce the behavior?

The easiest way to reproduce it, is add a `proxy` in the `devServer` section with an invalid `target` and set `logLevel: 'silent'`.

**Comment by noharashinchan** [comment]
I will try to look into it
