### ISSUE TITLE
Not static path for middleware

### ISSUE THREAD

**Issue by bsideup** [webpack/webpack-dev-server#325]
Hi!

We use cache busting, so after deployment path to JS file will looks like this:
`/static/ab13c758e1f/app.js`

Is it possible to configure WDS + middleware to proxy such URLs for local development?
Currently we see only one way of doing such things - check latest path to the resource and put it to the `publicPath` property, but this is flaky as hell and can't be comited :)

Thanks!

**Comment by SpaceK33z** [comment]
Why would you need this cache busting in development? For development you could just use a 'fixed' string instead of a dynamic path.

Also see #438 for some information about how to handle this.
