### ISSUE TITLE
Version 2.11.5 has Problem fetching Large Data

### ISSUE THREAD

**Issue by gamenic-dipendra** [webpack/webpack-dev-server#3256]
- Operating System: MacOS BigSur
- Node Version: 10.24.1
- NPM Version: 6.14.12
- webpack Version: 3.10.0
- webpack-dev-server Version: 2.11.5
- Browser: Microsoft Edge Version 90.0.818.51 (Official build) (64-bit)

- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.dev.config.js
devServer: {
    clientLogLevel: 'warning',
    historyApiFallback: true,
    hot: true,
    compress: true,
    host: HOST || config.dev.host,
    port: PORT || config.dev.port,
    open: config.dev.autoOpenBrowser,
    overlay: config.dev.errorOverlay
      ? { warnings: false, errors: true }
      : false,
    publicPath: config.dev.assetsPublicPath,
    proxy: config.dev.proxyTable,
    quiet: true, // necessary for FriendlyErrorsPlugin
    watchOptions: {
      poll: config.dev.poll,
    },
    https: true
  },
```

```js
// additional code
axios.post('/get_rows', args)
        .then(({data}) => {
          console.log(data)
```

### Expected Behavior
<img width="488" alt="Screen Shot 2021-05-06 at 7 31 32 PM" src="https://user-images.githubusercontent.com/73150082/117309055-ce5b7500-aea1-11eb-877d-b2a822ab897f.png">

### Actual Behavior
<img width="647" alt="Screen Shot 2021-05-06 at 7 31 59 PM" src="https://user-images.githubusercontent.com/73150082/117309162-e632f900-aea1-11eb-9852-32388c9bd8df.png">

### For Bugs; How can we reproduce the behavior?
When I was using `webpack-dev-server@2.9.7`, then it was working fine.
But, there is [`npm` vulnerability](https://www.npmjs.com/advisories/725), 
So, I upgrade `webpack-dev-server` version to `2.11.5`
When I upgraded, then vulnerability was gone, 
But, when I tried to `axios` fetch large rows (more than 30 rows), then the result part is converted into string. 
I tried using `JSON.parse(data)`, but it fails, because string is incomplete, which means, it has random length for the same data. And not closed properly at the end. e.g. it does not have such closing syntax like `"}'`.
In the previous version, I could easily get `axios` response for more than 500 rows.

**Comment by alexander-akait** [comment]
`webpack-dev-server@2` is deprecated and don't supported, please update to v3
