### ISSUE TITLE
BUG: Error: Cannot find module '../lib/polyfills'

### ISSUE THREAD

**Issue by AnishDe12020** [webpack/webpack-dev-server#3269]
- Operating System: Ubuntu 20.04 WSL2, same error on Windows 10 20H2 as well
- Node Version: v10.19.0
- NPM Version: v7.12.0
- webpack Version: v5.36.2
- webpack-dev-server Version: v3.11.2
- Browser: Microsoft Edge but the error comes in the terminal during compiling

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
Gist - https://gist.github.com/AnishDe12020/d3f6bd4653b6a6be4281adf07c40bde5

```js
// additional code, remove if not needed.
```
This is the example code from the MDC 101 offered by google.
Link - https://codelabs.developers.google.com/codelabs/mdc-101-web/#0
GitHub repository - https://github.com/material-components/material-components-web-codelabs

### For Bugs; How can we reproduce the behavior?
Well, I just need my code to compile and run

**Comment by AnishDe12020** [comment]
The repo for the finished project should be this one - https://github.com/material-components/material-components-web-codelabs/tree/master/mdc-101/complete

**Comment by alexander-akait** [comment]
Sorry, I can't reproduce, all works fine, feel free to feedback
