### ISSUE TITLE
Expose a way to pass params for `express.static`?

### ISSUE THREAD

**Issue by dickeylth** [webpack/webpack-dev-server#327]
In <https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L203>,

```js
// route content request
app.get("*", express.static(contentBase), serveIndex(contentBase));
```

Now I want to pass param `{index: false}` to `express.static` so that it looks like `express.static(contentBase, {index: false})` to disable directory indexing, because it makes me feel inconvenient to access other html files under the directory.

Thank you!

**Comment by SpaceK33z** [comment]
Fixed with #385, which will be part of the next 1.x release.
