### ISSUE TITLE
HMR WS Not Using Proper Location

### ISSUE THREAD

**Issue by natewiebe13** [webpack/webpack-dev-server#3290]
- Operating System: Ubuntu 20.04
- Node Version: 12.13.1
- NPM Version: 6.12.1
- webpack Version: 5.28.0
- webpack-dev-server Version: 4.0.0-beta.3
- Browser: Chrome 90.0.4430.93 / Firefox 88.0.1

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
devServer: {
  static: { directory: '/home/node/app/public' },
  headers: { 'Access-Control-Allow-Origin': '*' },
  compress: true,
  historyApiFallback: true,
  liveReload: false,
  client: { host: '0.0.0.0' },
  firewall: false
},
```

### Expected Behavior

When running the command below, the websocket should connect using the following url (or similar as sockjs was removed in beta 0): `wss://mydevserver.com:8080/sockjs-node/531/m3al2ujw/websocket`

```bash
yarn encore dev-server --host=0.0.0.0 --port=8080 --public="https://mydevserver.com:8080"
```

### Actual Behavior

A websocket connection is being attempted to `wss://0.0.0.0:8080/ws` which fails to connect since it's invalid.

My understanding is that the host setting is meant for the dev server to bind to, but that's not necessarily the same place as where the browser could connect to.

### For Bugs; How can we reproduce the behavior?

Attempt to use hot module reloading, not necessarily with a remote server, where the public path is specified and allow the dev server to listen to all IPs. The ws connection in the browser will attempt to connect out to `0.0.0.0` instead of the public hostname specified or the location in the browser.

**Comment by alexander-akait** [comment]
Don't specify `client: { host: '0.0.0.0' }`, you need this only when your proxy dev server, it is rewrite host of server for websocket client, we need show it in docs

**Comment by alexander-akait** [comment]
If you want to set host:
```
devServer: {
  static: { directory: '/home/node/app/public' },
  headers: { 'Access-Control-Allow-Origin': '*' },
  compress: true,
  historyApiFallback: true,
  liveReload: false,
  host: '0.0.0.0',
  firewall: false
},
```

**Comment by natewiebe13** [comment]
Thanks for the quick response, this work for me.
