### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by Inchill** [webpack/webpack-dev-server#3304]
Each time I installed webpack, webpack-cli and webpack-dev-server in this order, this error is bound to occur. Actually I found the webpack-cli's bin dir, it is upgraded and only exists the cli.js file, but webpack-dev-server still imports config-yargs file. I am very confused why webpack-der-server not to upgrade to support the latest version of webpack-cli?

- Operating System: MacOS
- Node Version: 14.7.0
- NPM Version: 7.12.1
- webpack Version: 5.37.0
- webpack-dev-server Version: 3.11.2
- Browser: chrome

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by snitin315** [comment]
What's the version of `webpack-cli` you are using?

**Comment by alexander-akait** [comment]
Install the lastest webpack-cli and use `webpack serve` to run webpack dev server instead `webpack-dev-server`

**Comment by paulsmithkc** [comment]
Seeing this same bug on with:

```
    "webpack": "^5.46.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
```

Its looking for `node_modules/webpack-cli/bin/config-yargs` and this file does not exist.

**Comment by alexander-akait** [comment]
Please run dev server using “webpack serve”
