### ISSUE TITLE
--https- namespaced CLI commands don't seem to work. --https-key --https-cert .  ] TypeError: Cannot create property 'cert' on boolean 'true'

### ISSUE THREAD

**Issue by oller** [webpack/webpack-dev-server#3306]
- Operating System: OS X
- Node Version: 14.15.3
- NPM Version: 6.14.9
- webpack Version: 5
- webpack-dev-server Version: 4.0.0.beta.3
- Browser: Brave

- [x] This is a **bug**
- [x] This is a **modification** request

### Code

Running webpack serve via the CLI with https cert options seems to error

```
webpack serve --https --https-cert ./.ssl/cert.pem --https-key ./.ssl/key.pem",
```
The above will error with:
```
[webpack-cli] TypeError: Cannot create property 'cert' on boolean 'true'
```

I tried omitting the `--https` as I wasn't sure if that was not necessary due to the namespced key and cert options being passed.  That gets past that previous point of error in the compilation but then errors 

```
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'stats'. These properties are valid:
   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
```

### Expected Behavior

Be able to pass `--https --https-key ../path --https-cert ../path` options

### Actual Behavior

Errors

**Comment by snitin315** [comment]
@oller don't pass `--https` along with other `https` flags, Use  `--https-key ../path --https-cert ../path` instead.

**Comment by oller** [comment]
> @oller don't pass `--https` along with other `https` flags, Use  `--https-key ../path --https-cert ../path` instead.

Hi thanks for reply, I tried that as mentioned above. I then get a different error?

**Comment by snitin315** [comment]
Please share error stack.

**Comment by snitin315** [comment]
`webpack serve --https-cert ./.ssl/cert.pem --https-key ./.ssl/key.pem`

**Comment by oller** [comment]
ah ok, the remaining errors seem related to my config.  So the issue was defining `https` along with `https-cert` and `https-key`.  With this namespacing change and that cryptic error, I imagine I won't be the only person to get a little unstuck here, not sure if there's a possibly to catch and throw a more meaningful error.

**Comment by snitin315** [comment]
> [webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
> - configuration has an unknown property 'stats'. These properties are valid:

It looks like you need to update your webpack config, `devServer.stats` was removed.

**Comment by oller** [comment]
> > [webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
> > 
> > * configuration has an unknown property 'stats'. These properties are valid:
> 
> It looks like you need to update your webpack config, `devServer.stats` was removed.

That's right, I'll close this issue for now then, someone can re-open it if they encounter the same issue in the future, perhaps scope for a more specific msg.  Thanks for the prompt replies and help @snitin315 !

**Comment by snitin315** [comment]
Let's keep it open, we should improve the error here, I will update it in the near future.
