### ISSUE TITLE
Bring back unix socket support

### ISSUE THREAD

**Issue by findoff** [webpack/webpack-dev-server#3308]
- [ ] This is a **bug**
- [X] This is a **modification** request

> Please note that we are NOT accepting FEATURE requests at this time.

It's not a new feature...

### For Features; What is the motivation and/or use-case for the feature?

As already answered(#2787) socket support was removed. But i feel it as major regress.

With version 3 i have nginx configuration to automatic listen SOCKET_NAME.example.com without global port catalog services to serve multiple developer's applications with easy regexp based permissions.

External wrapper disadvantages:
- external wrapper instead of just specify standard option
- for dynamic application, need global port catalog service instead of just nginx conf + many application from different non-administrative users with socket in folder
- no POSIX permission support (no simple ways to restrict app port for group of users)
- port to socket proxy overhead

Unix socket it's only way to listen **named** application.
I see removing it was strange in 2021 when most peoples comes to named services when it's possible...

Many years earlier some libraries not support unix sockets, but i used port options to do it with some tricks and know many peoples who do same.

But as i can see 4th version have too many tricks with hostname and port options to prevent this trick.

I think complexity reduction may be reason for this only if remove all other thinks like https certificate support and just pass-though host:port to node http server (that support socket...)

Sorry for my English and may be too many emotions in text.

**Comment by alexander-akait** [comment]
You can use Node.js API and implement this, sorry we don't want to get it supported again, there are lot of other approaches to solve it

**Comment by alexander-akait** [comment]
@findoff Anyway if you want support, please open an issue in `webpack-cli`, we don't have binary here for v4, also please describe what is problem do you want solve and why you can't solve it without unix sockets, and why you can't use Node.js API to solve it

**Comment by alexander-akait** [comment]
@findoff I don't wanna say no unix socket, we just can't do it here (because we have only flags here for CLI here, and it should be implemented in webpack-cli) and need some more information

**Comment by findoff** [comment]
I was solved this problem only with dropping webpack-dev-server completely using express and dev+hot webpack middle-wares directly.

It's requires me to using code instead of declarative config...

My use-cases described at first message. And i steel think it's about webpack-dev-server because as i can see it's create own express app.
And as i can see in documentation, options like port related to devServer section and dev-server have listen function with binding by port.
I have no own arguments to open this issue at webpack-cli.

**Comment by alexander-akait** [comment]
> I have no own arguments to open this issue at webpack-cli.

No need to negative, as maintainer of `webpack-cli` I ask you about it, I see your examples, but I don't understand them a little, so I ask you to show an example of setup so that I can study everything in more detail.

Again, we don't have binaries here and can't control CLI usage, and even if I wanted to help you, we just can't do it here, we can solve this only in `webpack-cli`

**Comment by findoff** [comment]
https://github.com/webpack/webpack-cli/issues/2752
