### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jhabdas** [webpack/webpack-dev-server#334]
Thoughts on adding some tests to help prevent things like https://github.com/webpack/webpack-dev-server/issues/326 from happening again?

**Comment by SpaceK33z** [comment]
How would you test a websocket connection failing? Sure, it's possible to test small part of this repo, but I think it's very hard to add fully automatic tests.

I think it would be useful to document what you should (manually) test after changing something.

For instance, in `example/` there are two html files `index.html` and `inlined.html`. You need to verify both of these still work (With PR #302 I forgot to test `inlined.html`, which caused #326).

**Comment by jhabdas** [comment]
Even a light process sounds good given there are thousands of people using
this software every day.

**Comment by SpaceK33z** [comment]
True that. Do you have time to put together a PR? Maybe start with `client/` first, I think that is the most easy and a fairly important part.

**Comment by jhabdas** [comment]
Given I lost a couple hours last week I'll consider it. I'd love to hear
more ideas on approach to find something effective and simple.

**Comment by jhabdas** [comment]
@SpaceK33z Do you have time to put together a roadmap, so we can add Unit Tests to it for one-dot-oh?

**Comment by SpaceK33z** [comment]
@jhabdas, 9 months later, I'm starting to work on this :). I've opened #581 for this to have a clean start.

Closing this in favor of #581.
