### ISSUE TITLE
dns-packet Dependency - Security bump required for webpack-dev-server 3.11.2

### ISSUE THREAD

**Issue by guedesantonio** [webpack/webpack-dev-server#3340]
Operating System: MacOS 11.2.3

Node Version: v14.16.1

NPM Version: 6.14.12

webpack Version: 5.4.0

webpack-dev-server Version: 3.11.2

Browser: Chrome 87.0.4280.141

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Dependency dns-packet has a security advisory: https://www.npmjs.com/advisories/1745

| High | Memory Exposure |
| --------------- | ----------- |
| Package | dns-packet |
| Patched in | >=5.2.2 |
| Dependency of | webpack-dev-server [dev] |
| Path | webpack-dev-server > bonjour > multicast-dns > dns-packet |
| More info | https://npmjs.com/advisories/1745 |

### RELATED:

There is a issue in Bonjour npm dependency about dns-packet as well : https://github.com/watson/bonjour/issues/63

### For Bugs; How can we reproduce the behavior?

Run npm-audit

**Comment by noppa** [comment]
If anyone has their builds failing because of this or something and happens to be using yarn, 
```json
  "resolutions": {
    "multicast-dns": "7.2.3"
  }
```
in package.json remediates the audit error. That could be a breaking change for some multicast-dns-using features of webpack-dev-server of course, but at least basic dev server functionality is still working fine for us.

**Comment by alexander-akait** [comment]
We can't fix it on our side https://github.com/watson/bonjour/issues/63

**Comment by apepper** [comment]
> We can't fix it on our side, please track it here watson/bonjour#63

`bonjour` was last updated five years ago. I have my doubts that it will release a new version. I haven't looked into it, but maybe there is a more up-to-date package that could replace `bonjour`.

**Comment by kjg** [comment]
https://www.npmjs.com/package/@homebridge/ciao could be a possible bonjour replacement

**Comment by daynewright** [comment]
Also there is an active fork that might be a possibility: https://github.com/onlxltd/bonjour-service

**Comment by alexander-akait** [comment]
If the problem will not be fixed to our `stable` v4 release, we will migrate on fork

**Comment by apepper** [comment]
Maybe `mulitcast-dns` can be convinced to release an update version 6: https://github.com/mafintosh/multicast-dns/issues/75.

**Comment by mafintosh** [comment]
v6 is fixed as of yesterday, if you reinstall deps. It's tracking dns-packet v1 to which I backported a fix.

**Comment by mdidon** [comment]
> Also there is an active fork that might be a possibility: https://github.com/onlxltd/bonjour-service
> (mentioned in this PR as well: [watson/bonjour#62](https://github.com/watson/bonjour/pull/62))

@daynewright Can confirm this issue has now been addressed in https://github.com/onlxltd/bonjour-service v1.0.8.
Hope this helps

**Comment by alexander-akait** [comment]
Fixed https://www.npmjs.com/advisories/1745/versions, update deps locally `1.3.4` is no affected
