### ISSUE TITLE
High vulnerabilities - How is the plan?!

### ISSUE THREAD

**Issue by deleonio** [webpack/webpack-dev-server#3343]
https://snyk.io/test/npm/webpack-dev-server/3.11.2

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/3340

**Comment by deleonio** [comment]
It is not solved

**Comment by deleonio** [comment]
https://github.com/webpack/webpack-dev-server/issues/3407
