### ISSUE TITLE
Hot reload when another webpack dev server reloaded

### ISSUE THREAD

**Issue by cjnoname** [webpack/webpack-dev-server#3355]
- [ ] This is a **bug**
- [x] This is a **modification** request

### For Features; What is the motivation and/or use-case for the feature?

Hi,

Is there a way to monitor another dev server running on local and reload the current app together with it?

I use module federation plugin on Webpack 5 and it's running different apps from local.
For example the container app is running on localhost:3000 and a child app is running on localhost:3001 with both running on webpack dev server.

If I made a change on the the app on 3001, then it will reload. But I want to find a way to reload the app on 3000 at the same time.

Any suggestions on this?

Thanks
CJ

**Comment by alexander-akait** [comment]
No way, it is on roadmap, but you can do it in client, send a signal using websocket and say what you need reload, but it is not easy

**Comment by cjnoname** [comment]
> No way, it is on roadmap, but you can do it in client, send a signal using websocket and say what you need reload, but it is not easy

Thanks for your reply. Looking forward for this feature.

**Comment by alexander-akait** [comment]
It is not feature, you should do it on your side, we have web socket api, you can use it for this, send this message https://github.com/webpack/webpack-dev-server/blob/master/client-src/index.js#L131 or you can use webpack API and invalid compilation when something was changed inside your custom plugin, it is rare case so we will not implement it in core
