### ISSUE TITLE
No data received ERR_EMPTY_RESPONSE webpack

### ISSUE THREAD

**Issue by KhaledMohamedP** [webpack/webpack-dev-server#336]
I am trying to run webpack-dev-server, but when I go to `http://localhost:8080/` the browser returns 

    No data received 
    ERR_EMPTY_RESPONSE

**Solution**

I was able to resolve this issue by explicitly telling webpack to use port 3000 

    webpack-dev-server --port 3000

go ->  `http://localhost:3000/`

It's not clear why the server didn't run in the defaulted port number?

**Comment by marconak** [comment]
+1

**Comment by AdamGustavsson** [comment]
+1

**Comment by KayBeSee** [comment]
+1

**Comment by SpaceK33z** [comment]
Dupe of #183, which also contains a lot more information about how to fix this.
