### ISSUE TITLE
Critial Dependency: the request of a dependency is an expression when upgrading to 4.0.0-beta.3 from beta.2

### ISSUE THREAD

**Issue by ZachMayry** [webpack/webpack-dev-server#3361]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin')
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')

const babelLoaderOptions = {
  rootMode: 'upward',
  plugins: [['react-refresh/babel', { skipEnvCheck: true }]],
}

const extensions = ['.tsx', '.ts', '.js']

module.exports = {
  mode: 'development',
  entry: ['./src/index.js', './src/index.scss'],
  output: {
    publicPath: '/',
  },
  stats: 'errors-only',
  devServer: {
    client: {
      overlay: true,
    },
    historyApiFallback: true,
    port: 3000,
    static: false,
  },
  plugins: [
    new HtmlWebpackPlugin({ template: 'raw-loader!src/index.html' }),
    new webpack.HotModuleReplacementPlugin(),
    new ReactRefreshWebpackPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: babelLoaderOptions,
          },
          {
            loader: 'ts-loader',
            options: {
              projectReferences: true,
            },
          },
        ],
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: babelLoaderOptions,
        },
      },
      {
        test: /\.s?css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
            },
          },
        ],
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: 'ejs-html-loader',
          },
        ],
      },
      {
        test: /\.(ico|png|jpg|jpeg|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 8192,
            },
          },
        ],
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      },
    ],
  },
  resolve: {
    extensions,
    plugins: [new TsconfigPathsPlugin({ extensions })],
  },
}

```

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sample</title>
  </head>

  <body>
    <div id="application" class="root">
      Sample
    </div>
  </body>
</html>
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
<img width="889" alt="image" src="https://user-images.githubusercontent.com/12666484/120013729-bbbaf400-bfa6-11eb-9532-d297af871a22.png">

### Expected Behavior
Loads the website

### Actual Behavior
<img width="866" alt="image" src="https://user-images.githubusercontent.com/12666484/120013588-8adabf00-bfa6-11eb-8416-536a820ab958.png">

### For Bugs; How can we reproduce the behavior?

Not entirely sure other than to use webpack-dev-server 4.0.0-beta.3, with the above webpack configuration.
I'm not able to find out exactly what is causing this issue given the limited output.

**Comment by alexander-akait** [comment]
No related to webpack-dev-server and please do not ignore questions in the issue template

**Comment by alexander-akait** [comment]
You rewrite `require` on `import` using named export, but you need to set `namedExport` to true for `css-loader` and `style-loader` if you want to use named export, in near future we reduce options and will rexport named export always

**Comment by ZachMayry** [comment]
> please do not ignore questions in the issue template

I guess I just thought that the code above was how to reproduce? Not sure what other question I missed

> if you want to use named export, in near future we reduce options and will rexport named export always
Are you saying that in the future that we will need this option? Or that we need it for beta3, but not in the future?

**Comment by ZachMayry** [comment]
So looking at it a bit more, this code does not work at all anyway. But at least the web server doesn't crash with it. 
```js
// index.js
import { white } from '../../theme/_colors.scss'
```

But that still doesn't resolve the fact that this appears
<img width="866" alt="image" src="https://user-images.githubusercontent.com/12666484/120013588-8adabf00-bfa6-11eb-8416-536a820ab958.png">

**Comment by ZachMayry** [comment]
After some more digging. I've found the cause to be related to the experimental plugin `'@pmmmwh/react-refresh-webpack-plugin'`

Upgrading it to 0.5.0-beta.8 loads the site correctly, but produces this overlay error. If that means we can close the issue at this time, then that makes sense to me!

**Comment by alexander-akait** [comment]
If you provide example of repo I can look at code, maybe we need fix the problem in `react-refresh-webpack-plugin`

**Comment by ZachMayry** [comment]
> If you provide example of repo I can look at code, maybe we need fix the problem in `react-refresh-webpack-plugin`

The problem with that is that our repo is private. I'm trying to isolate things in a such a way that I can find the issue. Updating  `react-refresh-webpack-plugin` solves one symptom but I've completely removed that and other plugins to no avail. Is there a way to get more verbose logging than just `Critical dependency: the request of a dependency is an expression`

**Comment by alexander-akait** [comment]
It means you have the same file, I think problem in `resolve` options, can you show me them?

**Comment by ZachMayry** [comment]
```js
  resolve: {
    extensions,
    plugins: [new TsconfigPathsPlugin({ extensions: ['.tsx', '.ts', '.js'] })],
  },
```

**Comment by alexander-akait** [comment]
> Would you consider this a piece of tech debt that we need to resolve before upgrading webpack-dev-sever?

Yep, circular dependencies, we can't fix it here

**Comment by ZachMayry** [comment]
So I guess the thing is, it's a warning on the CLI and doesn't cause any issues. But when using the webpack dev server, it shows as an error that I cannot "X" out of. Turning the overlay off would be the workaround.

**Comment by alexander-akait** [comment]
Please create minimum reproducible test repo, I will look

**Comment by ZachMayry** [comment]
Sure. I’ll post back when I create it

**Comment by ZachMayry** [comment]
https://github.com/ZachMayry/webpack-dev-server-error-reproduction/tree/main

**Comment by ZachMayry** [comment]
Hey there @alexander-akait, have you gotten a chance to look at the repo?

**Comment by alexander-akait** [comment]
Tomorrow (5.06)

**Comment by aerialist7** [comment]
I have the same problem on 4.0.0-beta.3

**Comment by alexander-akait** [comment]
Update ` "@pmmmwh/react-refresh-webpack-plugin": "^0.5.0-rc.0",` and ` "draftjs-md-converter": "^1.5.1",`, then install `"path-browserify": "^1.0.1"`, put:
```
 resolve: {
    fallback: {
      path: require.resolve("path-browserify"),
    }
  },
```

in `webpack.config.js` and all works find

**Comment by ZachMayry** [comment]
@alexander-akait I don't think this is a solution because `draftjs-md-converter@1.5.1` causes too many issues. 
I don't think the developer did some things right becuase we get this error now when trying to open the page with draftjs-md-converter

`process is not defined`

**Comment by alexander-akait** [comment]
I don't have this problem, please check my steps again, anyway this problem with `draftjs-md-converter`, because this package not for browser usage, we can't fix it here

**Comment by ZachMayry** [comment]
I understand that but the "Critical Dependency" is an error on the overlay that you can't close (even though everything works fine) and is a warning when building with the cli. Why the difference?

**Comment by alexander-akait** [comment]
Got it, let's allow to close overlay, now you can use:
```
client: {
      overlay: {
        warnings: false
      },
    },
```

also we have `ignoreWawnings` option in `webpack.config.js` you can filter it

**Comment by ZachMayry** [comment]
Thanks! Adding that package to `ignoreWarnings` definitely helps
