### ISSUE TITLE
The "poll" property name on watchFiles option 

### ISSUE THREAD

**Issue by muzuiget** [webpack/webpack-dev-server#3365]
- [x] This is a **bug**
- [ ] This is a **modification** request

The `watchFiles` option is added #3136, and the testcase code show that we should use the property name `usePolling`.

https://github.com/webpack/webpack-dev-server/blob/12f045f709850ee6879da8e4379510594d3af49c/test/options.test.js#L409

But it isn't work.

After reading the code:

https://github.com/webpack/webpack-dev-server/blob/73896127cef090124f75a1096b2968bda7aa2cb1/lib/Server.js#L976

We should use `poll` instead.

**Comment by anshumanv** [comment]
Good catch, will fix

**Comment by anshumanv** [comment]
I think staticOptions use `.poll` and chokidar options use `usePolling`, we need to handle both properties

**Comment by anshumanv** [comment]
@alexander-akait I think we should use same properties as chokidar options, presently we use `poll` to calculate `internal` option value, we can just read `usePolling` and `interval` and pass it to config, i.e no resolving on our side

**Comment by alexander-akait** [comment]
Ideally we should respect `watchOptions` from webpack, but rename them if needed

**Comment by anshumanv** [comment]
we can add fallback logic to support both maybe -

`usePolling: (!!watchOptions.poll || watchOptions.usePolling)`
