### ISSUE TITLE
Do not overwrite the output.path

### ISSUE THREAD

**Issue by gajus** [webpack/webpack-dev-server#337]
`webpack-dev-server` overwrites the `output.path` parameter of the user supplied config (https://github.com/gajus/write-file-webpack-plugin/issues/1).

* User supplied config should be immutable.
* There is no reason to overwrite the `output.path`.
* This makes the original `output.path` value inaccessible from the plugin.

**Comment by gajus** [comment]
@sokra Any chance of this behaviour changing in 2.0.0?

**Comment by SpaceK33z** [comment]
This also caused the issue in #266, and would be a good first step to fix #106.

@sokra, what's your opinion about this? I'd say that we should require `output.path` to be supplied by the user, and throw an error if it's not set.

**Comment by sokra** [comment]
WDS doesn't use the `output.path`. But I think we could just remove the assignment and it should work fine.

The assignment was originally to enforce linux style paths, because the prev versions of memory-fs doesn't support windows style paths. But as it supports it now it should be fine to remove this.

**Comment by SpaceK33z** [comment]
@sokra, all right, I'll remove that in v2 then.

**Comment by SpaceK33z** [comment]
Removed it in the above commit. Performed a few tests with different setups in the `examples/` dir, and everything still seems to work. Luckily we're running a beta anyway, so we can test this out on our beta users.

**Comment by leodsgn** [comment]
Hey guys! I'm still having the same issue here.

Does the v2 is ready for npm? I'm also having the current versions:
````json
"webpack-dev-server": "~1.16.2",
"webpack-dev-middleware": "~1.8.4"
````

And having the error:

<img width="676" alt="screen shot 2016-10-26 at 13 53 41" src="https://cloud.githubusercontent.com/assets/7218334/19733802/e5f31776-9b83-11e6-80e6-63a018a6af1f.png">

**Comment by dsebastien** [comment]
Just to clarify for me: with Webpack 1.x we had to define outputPath in our devServer config so that we could have the resources written on disk.

Can I now remove outputPath from my devServer config with Webpack 2 rc1 / webpack-dev-server 2 rc1 ?
