### ISSUE TITLE
WebsocketClient.js:39 WebSocket connection to 'ws://localhost:5000/ws' failed:

### ISSUE THREAD

**Issue by mycodedig** [webpack/webpack-dev-server#3382]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
-->

```js
// webpack.config.js
config.devServer = {
        transportMode: 'ws',
        contentBase: path.join(__dirname, './dist'),
        quiet: true,
        noInfo: false,
        inline: false,
        hot: false,
        historyApiFallback: true,
        port: '8080',
        publicPath: '/',
    };
```

```js
// devServer.js
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const config = require('../webpack.config')('development');

module.exports = new WebpackDevServer(webpack(config));
```

```
// For more information
// logs with webpack-dev-server version 3.11.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/index.js`
ℹ ｢wds｣: Project is running at http://localhost:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/Project/dist
ℹ ｢wds｣: 404s will fallback to /index.html
```

```
// logs with webpack-dev-server version 4.0.0-beta.3
[nodemon] starting `node server/index.js`
<w> [webpack-dev-server] The port specified in options and the port passed as an argument is different.
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/, http://127.0.0.1:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/Project/public' directory
2021-06-02T16:16:51.760Z info: Webpack development server is ready
2021-06-02T16:16:51.762Z info: App listening at http://:::5000
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
"webpack":  "^5.30.0"
"webpack-dev-server": "4.0.0-beta.3"

### Expected Behavior
The error comes after upgrading `webpack-dev-server` version from `3.11.2` to `4.0.0-beta.3`. The socket error should not come.

### Actual Behavior
Error should not occur

### For Bugs; How can we reproduce the behavior?
Just having this config above

**Comment by mycodedig** [comment]
After debugging more into this. I found I am not calling the api in a right way.
I have changed my code 
from
`new WebpackDevServer(webpack(config));`
to
`new WebpackDevServer(config.devServer, webpack(config));`

But now I am getting another issue:
```
ValidationError: Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '_assetEmittingWrittenFiles'. These properties are valid:
   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }
```

But in the options I have provided this property. Could someone please help?

**Comment by snitin315** [comment]
We don't have `_assetEmittingWrittenFiles` property in our schema https://github.com/webpack/webpack-dev-server/blob/v3/lib/options.json . Only properties in our schema are allowed

**Comment by mycodedig** [comment]
But I have not provided `_assetEmittingWrittenFiles` in the options. It looks like something is happening internally.
My options are:
```
devServer: {
    static: [ '/Users/appperfect/Desktop/bank-demo09/bank-demo/dist' ],
    quiet: true,
    noInfo: false,
    inline: false,
    hot: false,
    historyApiFallback: true,
    port: 5101,
    publicPath: '/'
  }
```

**Comment by snitin315** [comment]
What is your webpack-dev-server version?

**Comment by snitin315** [comment]
Update it to - 

```js
devServer: { 
    static: [ '/Users/Project/dist' ],
    devMiddleware: {
        publicPath: '/'
     },
    hot: false,
    historyApiFallback: true,
    port: 8080,
}
```

**Comment by snitin315** [comment]
More changes in https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md

**Comment by mycodedig** [comment]
Things are the same after changing the options to have `devMiddleware.publicPath = '/'`.
For more information ->
```
// my webpack.config
{
  mode: 'development',
  stats: { colors: true },
  devServer: {
    static: [ '/Users/Project/dist' ],
    devMiddleware: { publicPath: '/' },
    quiet: true,
    noInfo: false,
    inline: false,
    hot: false,
    historyApiFallback: true,
    port: 8080
  },
  resolve: { extensions: [ '.js', '.jsx' ], modules: [ 'node_modules' ] },
  bail: false,
  entry: {
    app: './main.js',
    vendor: [
      'react',
      'react-dom',
      'redux',
      'spin.js',
      'babel-polyfill',
      'webpack-dev-server/client?http://localhost:8080'
    ]
  },
  output: {
    filename: 'assets/[name].js',
    path: '/Users/Project/dist',
    pathinfo: true,
    publicPath: '/'
  },
  context: '/Users/Project/src',
  devtool: 'source-map',
  module: {
    rules: [ [Object], [Object], [Object], [Object], [Object], [Object] ]
  },
  optimization: { minimizer: undefined },
  plugins: [
    PostCssPlugin {},
    MiniCssExtractPlugin { options: [Object] },
    StatsPlugin { env: 'development', config: [Config] }
  ],
  externals: undefined
}
```

My webpack devServer file
```
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const config = require('../webpack.config')('development');
module.exports = new WebpackDevServer(config.devServer, webpack(config));
```

**Comment by mycodedig** [comment]
My `dist` folder structure is ->

- dist
    - assets
        - app.css
        - app.css.map
        - app.js
        - app.js.map
        - vendor.js
        - vendor.js.map
   - favicon.ico
   - index.html

**Comment by mycodedig** [comment]
I have fixed this issue by changing
from
```
new WebpackDevServer(config.devServer, webpack(config));
```

to
```
new WebpackDevServer(webpack(config), config.devServer);
```

However, the example provided in the repo has the opposite one. Thanks.

**Comment by mycodedig** [comment]
I am referring to this https://github.com/webpack/webpack-dev-server/blob/master/examples/api/middleware/server.js#L9

**Comment by snitin315** [comment]
> Things are the same after changing the options to have devMiddleware.publicPath = '/'.
devServer: {
    static: [ '/Users/Project/dist' ],
    devMiddleware: { publicPath: '/' },
    quiet: true,
    noInfo: false,
    inline: false,
    hot: false,
    historyApiFallback: true,
    port: 8080
  },

Also need to remove `quiet`, `noInfo` and `inline` from options. These are removed in v4.

**Comment by snitin315** [comment]
> I am referring to this https://github.com/webpack/webpack-dev-server/blob/master/examples/api/middleware/server.js#L9

I think this one is not released yet. It will be available after the next release.

**Comment by mycodedig** [comment]
Thanks much @snitin315 for your help.
