### ISSUE TITLE
writeToDisk doesn't work in webpack5

### ISSUE THREAD

**Issue by caojiaquan** [webpack/webpack-dev-server#3385]
"webpack": "^5.38.1",
"webpack-cli": "^4.7.0",
"webpack-dev-server": "^3.11.2",

```
  devServer: {
    writeToDisk: true
  }
```

![image](https://user-images.githubusercontent.com/22867207/120742509-93447400-c529-11eb-8c57-b774d8a00d25.png)

the left result is export by devServer

__webpack_exports is a empty object

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
