### ISSUE TITLE
ws vulnerability in v3 branch

### ISSUE THREAD

**Issue by internalsystemerror** [webpack/webpack-dev-server#3387]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

WS dependency contains a ReDoS vulnerability https://www.npmjs.com/advisories/1748 which is fixed in 7.4.6. Since v4 is not yet released, and v3 requires ws v6, is it possible/are their plans, to make a fix available? I'm not sure how much forcing ws via the resolutions field of package.json will break things since there are breaking changes.

### For Bugs; How can we reproduce the behaviour?

`npm audit` or `yarn audit`

**Comment by alexander-akait** [comment]
Fixed, please use search before posting, and please read https://github.com/webpack/webpack-dev-server/issues/3360#issuecomment-854549609

**Comment by internalsystemerror** [comment]
Apologies, I did search and found nothing hence posting.
