### ISSUE TITLE
webpack-dev-server using ws@6.2.1 with npm vulnerability 1748

### ISSUE THREAD

**Issue by ap-buf** [webpack/webpack-dev-server#3388]
─┬ webpack-dev-server@3.11.2
│   └── ws@6.2.1 

https://www.npmjs.com/advisories/1748

The latest version ws@7.4.6 does not have this vulnerability.

Would it be possible to include an updated version of puppeteer in your next release.

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/issues/3360#issuecomment-854549609
