### ISSUE TITLE
HMR does not work with `target: ['web', 'es5']`

### ISSUE THREAD

**Issue by xobotyi** [webpack/webpack-dev-server#3406]
# Bug report

**What is the current behavior?**
Browser's console stucks on `[HMR] Waiting for update signal from WDS...` stage and do not go on.

**If the current behavior is a bug, please provide the steps to reproduce.**
Set the config's `target` field to `['web', 'es5']`

**What is the expected behavior?**
Should work with `es5` target as it works with default `web` target.

**Other relevant information:**
webpack version:  5.27.1
Node.js version: v16.2.0
Operating System: Windows 10
Additional tools: -

**Comment by alexander-akait** [comment]
Fixed in master, please use https://github.com/webpack/webpack-dev-server/blob/master/package.json#L3, stable release will be soon

**Comment by xobotyi** [comment]
@alexander-akait thanks alot
