### ISSUE TITLE
glob-parent Security Issue

### ISSUE THREAD

**Issue by oze4** [webpack/webpack-dev-server#3407]
- [ ] This is a **bug**
- [x ] This is a **modification** request

### Code
 
Issue not code related.

### Please paste the results of `webpack-cli info` here, and mention other relevant information

Issue not webpack related

### Expected Behavior

No security issues.

### Actual Behavior

Security issue with `glob-parent`

### For Bugs; How can we reproduce the behavior?

`npm audit` or see [here](https://snyk.io/advisor/npm-package/glob-parent)

**Comment by julienw** [comment]
This comes through the chokidar dependency.
Indeed latest stable version (3.11.2) depends on chokidar v2: 
https://github.com/webpack/webpack-dev-server/blob/v3.11.2/package.json#L41
which depends on a too old version of glob-parent (even latest chokidar v2).

The latest master branch depends on chokidar v3 which can be updated to a patched version of glob-parent.

So I think that to fix this we'd need a release v3.11.3 with an update for chokidar only.

Would that be possible?

**Comment by brettwgreen** [comment]
Note chokidar 2.1.8 is also deprecated... https://www.npmjs.com/package/chokidar/v/2.1.8

**Comment by textbook** [comment]
Chokidar 3 [dropped Node 6 compatibility](https://github.com/paulmillr/chokidar/blob/HEAD/.github/full_changelog.md#chokidar-300-apr-30-2019), which WDS 3 supports:

https://github.com/webpack/webpack-dev-server/blob/5cb545fdc64c9d4b8e557ca86e597db93b3f93f3/package.json#L13-L15

That can't be updated as a patch version, looks like WDS 4 is [targeting Node >= 12.13](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#400-beta3-2021-05-06) and already using Chokidar 3.

**Comment by oze4** [comment]
Thanks for looking into this! I really appreciate everything that Webpack has done and is doing.

Please let me know if I should close this out, or if publishing a major version is within reach (possibly create a branch? better than nothing imo but idk) .

**Comment by kamikazebr** [comment]
Can i get some beta package of dev server to test?

**Comment by textbook** [comment]
@kamikazebr it's already available, on the `next` tag: https://www.npmjs.com/package/webpack-dev-server/v/4.0.0-beta.3

**Comment by alexander-akait** [comment]
`glob-parent` has backport (just update deps - `npm update`) also chokidar updated in v4 (rc now, stable will be in very near future)

**Comment by textbook** [comment]
As far as I can tell `glob-parent`'s maintainers haven't (and won't, only 5.x and 6.x are supported and they're already patched) released a fixed version _compatible with WDS@3_ (via Chokidar@2). A fresh install in a a new directory still shows:

```
$ npm ls glob-parent
wds-glob@1.0.0 path/to/wds-glob
└─┬ webpack-dev-server@3.11.2
  └─┬ chokidar@2.1.8
    └── glob-parent@3.1.0
```

**Comment by alexander-akait** [comment]
unfortunately we will not be able to solve it in v3, it was big breaking change, wait v4, it is in rc, so it should be stable to use already

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-rc.0

**Comment by alexander-akait** [comment]
And migration guide https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by textbook** [comment]
> we will not be able to solve it in v3, it was big breaking change

Sure, I pointed that out above. What I mean is that I wouldn't close this until 4.0 went GA - anyone installing WDS until then will see the vulnerability, the backport only applies to the RC version.
