### ISSUE TITLE
webpack 5 / devServer.socket miss

### ISSUE THREAD

**Issue by politsin** [webpack/webpack-dev-server#3409]
The task is to listen with webpack dev-server  normal unix-socket (not a port)

There is no  `devServer.socket` parameter in webpack 5 and there is no mention of it anywhere and no way to work around

## webpack `4` parametrs list
https://v4.webpack.js.org/configuration/dev-server/#devserversocket
```
devServer.socket
devServer.sockHost
devServer.sockPath
devServer.sockPort
```

## webpack `5` parametrs list
https://webpack.js.org/configuration/dev-server/#devserversockhost
```
... =) miss
devServer.sockHost
devServer.sockPath
devServer.sockPort
```
## Docs
* there is no mention about this in the release notes
   - https://webpack.js.org/blog/2020-10-10-webpack-5-release
* there is no mention about this in the migrate docs
   - https://webpack.js.org/migrate/5/

**Comment by politsin** [comment]
when i run `webpack serve --socket /var/run/n/nodejs.socket`
a got result
```
ℹ ｢wds｣: Listening to socket at /var/run/n/nodejs.socket
ℹ ｢wds｣: webpack output is served from /modules/custom/react/js/dist_dev/
ℹ ｢wds｣: Content not from webpack is served from /var/www/html/modules/custom/react/js
ℹ ｢wdm｣: asset main.min.js 1.63 MiB [emitted] (name: main) 1 related asset
...
```
but there is no socket file in /var/run/n directory.
However plain js file works fine and socket exists in folder after `node net.js`
```
// node net.js
'use strict';
const SOCKET = '/var/run/n/nodejs.socket';

const fs = require("fs");
const net = require('net');
const unixSocketServer = net.createServer();

unixSocketServer.on('error', function (e) {
  if (e.code == 'EADDRINUSE') {
    console.log('Address in use, retrying...');
    fs.unlinkSync(SOCKET);
    unixSocketServer.listen(SOCKET, () => {
      console.log('now recoverd');
    });
    setTimeout(function () {
    }, 1000);
  }
});

unixSocketServer.listen(SOCKET, () => {
  console.log('now listening');
});

unixSocketServer.on('connection', (s) => {
  console.log('got connection!');
  s.write('hello world');
  s.end();
});

```

**Comment by snitin315** [comment]
`devServer.socket` will be removed in weboack-dev-server v4 in favor of `--unix-socket` flag which is currently being implemented in webpack-cli -

https://github.com/webpack/webpack-cli/pull/2757

**Comment by politsin** [comment]
do I understand correctly?
* this is not available to work via the unix-socket now
* unix socket will be available if the merge request will be accepted (webpack/webpack-cli#2757)

**Comment by alexander-akait** [comment]
@politsin it is still under development, and in our roadmap, note:
```
devServer.sockHost
devServer.sockPath
devServer.sockPort
```

were renamed to `clinet. webSocketURL` and not related to the `socket` option

**Comment by alexander-akait** [comment]
We return socket support, now it is called `ipc`, can be `true` or path to socket, release will be in near future

**Comment by politsin** [comment]
Спасибо огромное!
пойду попробую запустить

**Comment by politsin** [comment]
не обратил внимание что v4.0.0-beta.3 от 6 May,  т.е. изменения из мастер-ветки ещё не зафиксированы.
подожду пока следующий релиз появится видимо =)

**Comment by alexander-akait** [comment]
release will be on this week

**Comment by politsin** [comment]
спасибо! жду с нетерпением релиз

**Comment by politsin** [comment]
понимаю что для релиза нужно много работы, и возможно есть какие-то блокирующие таски.
но навсякий случай напомню 😇

**Comment by alexander-akait** [comment]
I am working on the latest pr - migration guide for the rc release (after rc we will fix couple small bugs and do stable major release), anyway `rc` should be safe for use, because no breaking change after rc
