### ISSUE TITLE
webpack-dev-server@4.0.0-beta.3:HMR is invalid

### ISSUE THREAD

**Issue by zhaodeezhu** [webpack/webpack-dev-server#3427]
configure:
devServer: {
    hot: true,
    port: '8080',
    historyApiFallback: true
 }

Pages do not hot update

"webpack": "^5.38.1"
"webpack-cli": "^4.7.0"

**Comment by zhaodeezhu** [comment]
supplement：
I use the webpack.ModuleFederationPlugin
new ModuleFederationPlugin({
	filename: "teamA.js",
         name: "teamA",
         library: { type: "var", name: "teamA" },
	 exposes: {
	       "./TestComponent": "./src/TestComponent", 
                "./data": "./src/data"
	 },
         shared: ["react", "react-dom"]
})

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
