### ISSUE TITLE
Found Moderate vulnerability.

### ISSUE THREAD

**Issue by JosephRivera-ngt** [webpack/webpack-dev-server#3444]
<img width="682" alt="Screen Shot 2021-06-16 at 12 05 26 AM" src="https://user-images.githubusercontent.com/84348598/122156229-93e8de80-ce36-11eb-81f0-5e9a0df1e91e.png">

on latest version.

**Comment by sibiraj-s** [comment]
You can do `npm audit --fix` or reinstall the dev server to get rid of this vulnerability.

**Comment by LenhardErwan** [comment]
Note that [v3.11.2](https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.2) contain deprecated modules (#3407)
You can update this module to the latest version, but it is still in BETA and this is a major update.

@sibiraj-s Unfortunately, even with an `npm audit fix --force` and an `npm install webpack-dev-server` the new version may not be taken into account, especially in an existing project. So you have to do `npm install webpack-dev-server:next` OR `npm install webpack-dev-server@4.0.0-beta.3`for the latest version.

**Comment by sibiraj-s** [comment]
> So you have to do `npm install webpack-dev-server:next` OR `npm install webpack-dev-server@4.0.0-beta.3`for the latest version.

Yeah, I was referring to the same. Thanks.

**Comment by PadminRK** [comment]
Do we know when a stable webpack-dev-server v4 would be published?

**Comment by snitin315** [comment]
> Do we know when a stable webpack-dev-server v4 would be published?

@PadminRK  We hope to do it early next month. Most of the things are done, we need to merge some more PRs before release.

**Comment by PadminRK** [comment]
@snitin315 , thanks that helps.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/3407
