### ISSUE TITLE
HMR not working properly when modifying files in node_modules folder

### ISSUE THREAD

**Issue by julien-terral** [webpack/webpack-dev-server#3453]
**OS:** Tried on MacOS, Windows 10, CentOS & Debian10 
**webpack version:**  5.37.1
**webpack-dev-server:** 4.0.0-beta.3

- [x] This is a **bug**
- [ ] This is a **modification** request

When I edit my files in the `src` directory, the live reload happens with the latest modifications.

However when editing my dependency files (in `node_modules`) for dev purposes, the console warned me that the webpack-dev-server hot reloads but my components don't re-render and all my changes are not taken into account (even if I refresh the whole page). I also tried with `npm link` or `yarn link`, but issue was the same.

With webpack 4, I never encountered this issue. I was able to change any file in the `node_modules` folder and had hot reload working (without any specific configuration).

### Code

I've tried to add this config to the devServer options:

```js
devServer: {
    https: false,
    port: 8080,
    open: false,
    watchOptions: {
      ignored: [
        'node_modules',
        '!node_modules/my-module',
      ],
    },
  },
```

and even this one, without success:

```js
devServer: {
    https: false,
    port: 8080,
    open: false,
    watchFiles: 'node_modules/*',
  },
```

This is what's displayed in the console when editing a file in a `node_modules` package (hot reload not working):

<img width="434" alt="121386308-2de9ec00-c94a-11eb-9f54-5b78c5157883" src="https://user-images.githubusercontent.com/27774317/122476474-8cf0d600-cfc6-11eb-9ec8-8ac52187a59e.png">

When editing an `src` file (hot reload working):

<img width="431" alt="121387733-33940180-c94b-11eb-9084-c910c5e8086a" src="https://user-images.githubusercontent.com/27774317/122476501-9da14c00-cfc6-11eb-879b-065359ee403d.png">

I thought the issue was related to Quasar, and opened a ticket but it doesn't seem to be the case. One of the creators suggested me to open a ticket here. (Link to the Quasar issue: https://github.com/quasarframework/quasar/issues/9626)

I checked on your GitHub closed issues and found some similar issues but unfortunately none of the answers did the trick for me.

### Expected Behavior
When writing a console.log or an alert code in a `node_modules`file, changes are detected and the screen is automatically updated.

### Actual Behavior
A change is detected and a new build is made, but the console says "[webpack-dev-server] App hot update..."
Also, the screen is not updated.
After ending the process, you must restart it for the changes to take effect.

### For Bugs; How can we reproduce the behavior?
Link to the reproducing repo: https://github.com/julien-terral/webpack-5-hmr-issue

Video: 

https://user-images.githubusercontent.com/27774317/122480157-9b41f080-cfcc-11eb-93ac-f231475958ed.mov

**Comment by alexander-akait** [comment]
Please use search before create, answered https://github.com/webpack/webpack-dev-server/issues/3338

**Comment by alexander-akait** [comment]
For `watchFiles`, you need to use `node_modules/**/*`, because `watchFiles: 'node_modules/*'` watch only top

**Comment by julien-terral** [comment]
Hi @alexander-akait, I mentioned in my issue that I already found the #3338 answer but it's not working for me.

I tried watchFiles : 'node_modules/**/*', it reloads the page but the my components aren't update. (cf. the new video attached)

https://user-images.githubusercontent.com/27774317/122482285-87988900-cfd0-11eb-9417-6676c7907a18.mov

**Comment by alexander-akait** [comment]
You need set `snapshot.managedPaths: []`

**Comment by julien-terral** [comment]
I already tried with this configuration too:

<img width="531" alt="Capture d’écran 2021-06-18 à 01 04 54" src="https://user-images.githubusercontent.com/27774317/122482624-33da6f80-cfd1-11eb-99eb-286fac2973e8.png">

**Comment by alexander-akait** [comment]
You need set this option here https://github.com/julien-terral/webpack-5-hmr-issue/blob/main/quasar.conf.js#L68, it is not `quasar` option

**Comment by alexander-akait** [comment]
Looks `chain` is not supported `snapshot`, but if you open `node_modules/webpack/lib/config/defaults.js` on `319` line (where we set default value for `snapshot.managedPaths`) and change code on:
```js
A(snapshot, "managedPaths", () => {
  return [];
});
```

all works fine

**Comment by alexander-akait** [comment]
Give me couple minutes I will look at workaround for chain-webpack

**Comment by julien-terral** [comment]
I'll try that, thank you for your time you're awesome!

**Comment by julien-terral** [comment]
Yes, I confirm that it works like a charm with the fix that you provided me (when I'm update the `node_modules/webpack/lib/config/defaults.js` file). If you have a workaround for chain-webpack it'll be perfect!

**Comment by alexander-akait** [comment]
@julien-terral found:
```
chainWebpack (chain) {
        chain.plugin('eslint-webpack-plugin')
          .use(ESLintPlugin, [{ extensions: [ 'js', 'vue' ] }])

        chain.merge({
          snapshot: {
            managedPaths: []
          }
        });
      },
```

**Comment by julien-terral** [comment]
Thank you so much for your time @alexander-akait, it will help me a lot, I was looking for a workaround for days! 🙏

**Comment by nkalinov** [comment]
@alexander-akait We're using Yarn PnP workspaces with a few packages. We have a `core` package that is used by other packages and it's transpiled on the fly by adding its path to babel-loader's `include` prop.

No issues with Webpack4 but after the recent upgrade to WP5 changes to the core package stopped being detected from the largest app?! Yup, change detection works fine from smaller apps and it also works fine if I comment out one of the big chunks part of this large app.

- Tried `snapshot.managedPaths: []` - no success.
- Tried `watchOptions.poll: true` - no success.
- Node - Tried v14, v16 - no difference.
- Yarn 3.2
- webpack 5.57.0
- webpack-dev-server 4.7.4
- MacOS

I know it would be ideal to have a repro but I hope you see given the "size" factor it's not something easy to do.
Any ideas? Anything related to limits on number of files being watched?

Could it be related to Yarn somehow? cc @arcanis 

Thanks!

**Comment by alexander-akait** [comment]
Try to set it on `[]` https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L416, i.e. `immutablePaths`

**Comment by nkalinov** [comment]
Just to be clear, you mean that right?
```
  snapshot: {
    managedPaths: [],
    immutablePaths: [],
  },
```
Not working...

**Comment by alexander-akait** [comment]
@nkalinov Can you provide small example with steps, no need show code, just example of configuration to reproduce the problem, thanks

**Comment by nkalinov** [comment]
Another finding: 
- Works on Windows ✅ 
- Doesn't work on MacOS ❌ 
- Linux - I can't verify...

**Comment by alexander-akait** [comment]
oh, sorry for delay, yes, pnp has problem here, but based on different result on different os, it can be bug in pnp code, do you use the latest version?

**Comment by nkalinov** [comment]
Yes, we are on Yarn 3.2. I can also try the latest master ("from sources") but I don't see anything related to that in their CHANGELOG. Anyways, will report tomorrow. Meanwhile I hope @arcanis would have a minute to give it a thought.

**Comment by arcanis** [comment]
It's difficult to say since there is no repro. Given that it works with X dependencies but not Y I'd tend to think it doesn't come from either Webpack or Yarn (otherwise I'd expect it to always fail), but that's just a guess 🤔
