### ISSUE TITLE
Proxy without target

### ISSUE THREAD

**Issue by lukasgeiter** [webpack/webpack-dev-server#3486]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
devServer: {
    proxy: {
        '/api': {
            target: 'dummy', // shouldn't be necessary
            router: request => ...
        },
    },
},
```

### Expected Behavior

I expect to be able to use the `router` feature of `http-proxy-middleware` without having to specify a `target`.

### Actual Behavior

When `target` is missing, the proxy middleware is not used at all: https://github.com/webpack/webpack-dev-server/blob/516d7b1b5c44ca9b934b91c777120396d895a7d2/lib/Server.js#L281-L283

Which is also noted in the [documentation](https://webpack.js.org/configuration/dev-server/#devserverproxy):
>  Note that some of `http-proxy-middleware`'s features do not require a `target` key, e.g. its `router` feature, but you will still need to include a `target` key in your configuration here, otherwise `webpack-dev-server` won't pass it along to `http-proxy-middleware`).

Recently, the validation in `http-proxy-middleware` has been [updated to allow for configurations without a `target` key](https://github.com/chimurai/http-proxy-middleware/pull/512). I suggest to do the same here and extend the condition to `proxyConfig.target || proxyConfig.router`.

**Comment by anshumanv** [comment]
makes sense, I'll fix it 👍

**Comment by alexander-akait** [comment]
You can use `target '**'`

**Comment by lukasgeiter** [comment]
@alexander-akait As far as I can tell, I can use pretty much any value I want as long as it's truthy. Currently I'm using `'dummy'` which is working fine. The point is, I shouldn't have to specify a target if it's always going to be overridden by `router` anyway.
