### ISSUE TITLE
Get rid of core-js polyfill added in 4.0.0.beta-2

### ISSUE THREAD

**Issue by dispalt** [webpack/webpack-dev-server#3502]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

It works with IE11

### Actual Behavior

I am getting a stack out of space error on IE11 which I think is because of recursion of my core-js symbol polyfill conflicting with your core-js during the Symbol polyfill

### For Bugs; How can we reproduce the behavior?

Since you ask users to polyfill Promise and I think my Symbol polyfill is stepping on your Symbol polyfill maybe the best way is to skip using that and just tell people webpack-dev-server client needs to be transpiled if you want to use it in an old browser.  I tested it with the polyfill I am getting a stack out of space error, without a polyfill it works.

**Comment by alexander-akait** [comment]
Without this polyfill IE11 will not work

**Comment by alexander-akait** [comment]
Please provide steps to reproduce

**Comment by dispalt** [comment]
I thought I had it working and now I can't figure it out, uggh.

I guess what led me down this path is trying this with IE11
- First I tried to use it with IE11 and it would throw a receiver error (I think my babel loader was recompiling it)
- Second I got past that by putting `webpack-dev-server` in the babel loader ignore,
- Third I landed on the error I can't get past which is Out of stack space.   

All these errors seem to appear mostly when polyfills are stepping over each other, which I kinda assumed is happening because I am using present-env with ie11, corejs: 3 and entry mode.  

Now I am starting to doubt this is the issue... I can't reliably get it working again =(

**Comment by alexander-akait** [comment]
Firstly please update to beta.3

> Third I landed on the error I can't get past which is Out of stack space.

Do you have stacktrace? I really can't reproduce it, also you can try to test it locally, go to `node_modules/webpack-dev-server/client/log.js` and comment `require('../modules/logger')`, also change `log: logger.getLogger(name)` on `log: console` then run dev server

**Comment by alexander-akait** [comment]
I think more and more that we need to remove IE11 from support...

**Comment by dispalt** [comment]
Yeah ie11 is such a pain and WDS makes it so much better.  Removing the logging definitely works, FWIW

**Comment by alexander-akait** [comment]
So problems with polyfill?

**Comment by dispalt** [comment]
yeah my original thought was that the polyfill added in the 4.x series is interfering with the polyfill that I include, but I haven't been able to confirm it, because if I remove your polyfill it still doesn't work.

https://github.com/zloirock/core-js/issues/735

**Comment by alexander-akait** [comment]
Maybe you can provide test repo?

**Comment by dispalt** [comment]
Yeah I will work on that, thanks for all the help.  One last question and I think this might clear up a lot for me.

So during the bundling phase the webpack babel-loader processes the webpack-dev-server files after my entrypoint, but I think the webpack-dev-server code is getting called before my code, is that correct?  

I can't quite figure out the order of everything.  Because if it was getting called after my code it wouldn't an issue since the core-js import in my project would have polyfilled `Symbol`

**Comment by alexander-akait** [comment]
> So during the bundling phase the webpack babel-loader processes the webpack-dev-server files after my entrypoint, but I think the webpack-dev-server code is getting called before my code, is that correct?

Sorry, I don't undestand, all files handled by babel-loader (if you don't set `exlcude`) before running webpack-dev-server

**Comment by dispalt** [comment]
So this works great now with IE11! Just rc0 a spin, thank you!

**Comment by alexander-akait** [comment]
:+1:
