### ISSUE TITLE
v4 Feature: Reenable watching node_modules and recompile on change

### ISSUE THREAD

**Issue by susnux** [webpack/webpack-dev-server#3506]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

If you enable `watchFiles` (as a replacement for `watchOptions` from the old version) only static files are served.

```js
// webpack.config.js
   devServer: {
      watchFiles: {paths: ['/node_modules/@mymodules']}
    },
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
I am using  `webpack-dev-server@4.0.0-beta.3`
```
  System:
    OS: Linux 5.12 openSUSE Tumbleweed 20210629
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 24.12 GB / 31.27 GB
  Binaries:
    Node: 16.4.0 - /tmp/yarn--1625228312161-0.8953605594414591/node
    Yarn: 1.22.10 - /tmp/yarn--1625228312161-0.8953605594414591/yarn
    npm: 7.18.1 - /usr/bin/npm
  Browsers:
    Firefox: 89.0.2
  Packages:
    eslint-webpack-plugin: ^2.5.4 => 2.5.4 
    modify-source-webpack-plugin: ^3.0.0-rc.0 => 3.0.0 
    webpack-cli: ^4.7.2 => 4.7.2 
```

### Expected Behavior
Changed modules get recompiled and inserted into served files.

### Actual Behavior
Only static content is reloaded

### For Features; What is the motivation and/or use-case for the feature?
The old behavior with `watchOptions` and `ignored` allowed us to enabled watching for changes of a module in `node_modules`.
So you can develop an extension for your app, e.g. you could develop a library and hotreload changes on the using application.

Or our usage was to develop a Quasar app extension and to have the using application to test it while developing.

This is not possible anymore, as `watchFiles` does not trigger a recompile of the changed module.

**Comment by alexander-akait** [comment]
No, it was answered a lot of time, please use search, here answer https://github.com/webpack/webpack-dev-server/issues/3453
