### ISSUE TITLE
Errors in entry files aren't displayed properly in the browser

### ISSUE THREAD

**Issue by tgrajewski** [webpack/webpack-dev-server#3517]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js

const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  devtool: 'source-map',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  devServer: {
    static: [
      {
        directory: 'dist'
      }
    ]
  }
};
```

```js
// src/index.js
'use strict';

console.logz('Hello World!');  // Intentional typo
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information

```
asset main.js 256 bytes [emitted] (name: main) 1 related asset
./src/index.js 45 bytes [built] [code generated]
webpack 5.43.0 compiled successfully in 68 ms
```

### Expected Behavior

This is how error is displayed with only Webpack, properly showing source of the `index.js` module:

![Screenshot 2021-07-07 154433](https://user-images.githubusercontent.com/4324821/124770005-41cd4180-df3a-11eb-841f-9eeb215766d9.png)

### Actual Behavior

This is how error is displayed with Webpack Dev Server:

![Screenshot 2021-07-07 154312](https://user-images.githubusercontent.com/4324821/124770022-44c83200-df3a-11eb-90cc-c08209d3ea3f.png)

### For Bugs; How can we reproduce the behavior?

Having a typo in an entry file or any file imported by it should be enough to trigger this issue. Used packages:

 * webpack v5.43.0
 * webpack-cli v4.7.2
 * webpack-dev-server v4.0.0-beta.3

**Comment by alexander-akait** [comment]
Expected, I don't see any problems here

**Comment by tgrajewski** [comment]
How it is expected, I don't understand?

**Comment by tgrajewski** [comment]
From the readme file:

> Use webpack with a development server that provides live reloading. This should be used for development only.

So how developers should work with this **development server** if it isn't capable of showing errors in the dev tools properly?

**Comment by alexander-akait** [comment]
This is how JS works, we need to put your code in function(s) to handle this as bundle, so we can't be on the same location

**Comment by tgrajewski** [comment]
So it's not expected, but rather not possible to fix?

**Comment by alexander-akait** [comment]
It is expected because live and hot reload will not work without with code, it is limitations

**Comment by tgrajewski** [comment]
I'm assisting a team of developers and we're switching from Browserify to Webpack. We've previously used this simple dev server Budo, which now seems outdated. Anyway, Budo was showing properly runtime errors in entry files, so it's possible. And it has live reloading, but not HMR. I don't know about the internals, but what are the options here, is it a matter of some Webpack config options, e.g. disabling hot reload maybe?

**Comment by alexander-akait** [comment]
No options for this, sorry, maybe in future we will implement non bundled mode and it will be possible in some cases, but it is other issue and already tracked

**Comment by tgrajewski** [comment]
Are you sure? If an error occurs later, after the initial entry files processing, dev tools show it properly. Can you tell me more about this bundled mode, so I could investigate it on my own? Thanks

**Comment by alexander-akait** [comment]
webpack require runtime to working in browser (not only browser) when you bundle modules in one/two/more files, so we need to add own functions and so you have other location, bundless mode means do not bundle code and output as is, but it will work only for ECMA modules and in modern browser, but it will be in future

**Comment by tgrajewski** [comment]
Yeah, I know the basics of bundling, but thanks for the explanation. I think it's possible to show the error properly when code is bundled, it might be something with source maps then, as the Budo server also bundled code and still displayed errors properly.

**Comment by alexander-akait** [comment]
webpack-dev-server don't touch your source maps, maybe something with publicPath, can you provide example how you test it?

**Comment by tgrajewski** [comment]
I've setup minimal example that showcases this issue: https://github.com/tgrajewski/webpack_error_test

**Comment by tgrajewski** [comment]
Actually I think I've found some kind of solution. So in case of an error, the bootstrap code is shown, because it is executing it and catching the exception, but I think it shouldn't!

![image](https://user-images.githubusercontent.com/4324821/125288387-63ee0780-e31e-11eb-9ee3-8a13c601e3ff.png)

Without the `try` block the error is shown properly.

**Comment by alexander-akait** [comment]
we can't remove try/catch block

**Comment by tgrajewski** [comment]
If the module is not part of the HMR process, then it should be safe to omit the try/catch clause. Can you tell me more why not?

**Comment by alexander-akait** [comment]
due architecture of webpack bundling

**Comment by tgrajewski** [comment]
Yeah, OK, but when I bundle the code with Webpack only, without the webpack-dev-server, the error is shown properly.

**Comment by alexander-akait** [comment]
Yep, as I say above we need this code for hot, we can't apply hot reloading for only some modules, only for whole bundle

**Comment by alexander-akait** [comment]
Set `hot: false` should fix the problem

**Comment by tgrajewski** [comment]
YES!!! Thank you, setting `hot: false` solves the issue and shows the error properly. We'll go with that, sorry for the trouble.
