### ISSUE TITLE
Update dependencies - chokidar to 3.5.2

### ISSUE THREAD

**Issue by harryli256** [webpack/webpack-dev-server#3530]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Expected Behavior

N/A

### Actual Behavior

N/A

### For Bugs; How can we reproduce the behavior?

N/A

### For Features; What is the motivation and/or use-case for the feature?

A dependency of chokidar is reporting security issues when I ran `npm audit`

chokidar needs to be updated to 3.5.2, which has an update to use 5.1.2 of glob-parent

https://npmjs.com/advisories/1751

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/3407
