### ISSUE TITLE
v4 - Unable to hide webpack output log

### ISSUE THREAD

**Issue by sumanbh** [webpack/webpack-dev-server#3543]
It seems like we're unable to hide webpack output in v4 even with infrastructureLogging level set to [none](https://github.com/sumanbh/razzle/blob/webpack-dev-server-v4/packages/razzle/config/createConfigAsync.js#L467). Relevant devServer config [here](https://github.com/sumanbh/razzle/blob/webpack-dev-server-v4/packages/razzle/config/createConfigAsync.js#L837). No such issue in v3 with webpack 5.

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Repo to reproduce this behavior: https://github.com/sumanbh/razzle/tree/webpack-dev-server-v4

```sh
# install deps
yarn

# run start script
yarn start
```

Example webpack output log we still see:
```sh
asset static/js/client.js 1.99 MiB [emitted] (name: client) 1 related asset
asset ../assets.json 220 bytes [emitted]
runtime modules 25.9 KiB 14 modules
modules by path ../../node_modules/ 1.87 MiB 97 modules
modules by path ./src/ 3.39 KiB
...
webpack 5.45.1 compiled successfully in 1460 ms
```

### `webpack-cli info` output
```
  Binaries:
    Node: 14.16.1
    Yarn: 1.22.5
    npm: 6.14.12
  Browsers:
    Chrome: 91.0.4472.164
  Monorepos:
    Yarn Workspaces: 1.22.5
    Lerna: 3.22.1
  Packages:
    html-webpack-plugin: 4.5.2 => 4.5.2 
    webpack: 5.45.1 => 5.45.1 
    webpack-cli: ^4.7.2 => 4.7.2 
    webpack-dev-server: ^4.0.0-rc.0 => 4.0.0-rc.0 
```

### Expected Behavior
No webpack output log.

### Actual Behavior
Webpack outputting logs.

**Comment by alexander-akait** [comment]
`stats: 'errors-warnings'`
