### ISSUE TITLE
Module not found: Cannot resolve module "webpack/hot/dev-server" in "my-work-dir"

### ISSUE THREAD

**Issue by jasonleft** [webpack/webpack-dev-server#355]
When i exec `webpack-dev-server --inline --hot` in windows 7 cmd, I got an error:
```
ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/dev-server' in E:\we
b\htdocs\webpack
 @ multi main
```
I use `-g` flag to install webpack and webpack-dev-server, so can use webpack in any dir.
My webpack.config.js like this:
```
module.exports = {
	entry: './app/index.js',
	output: {
		path: 'build',
		filename: 'bundle.js'
	}
};
```

My project struct like this:
```
E:.
│   package.json
│   webpack.config.js
│
├───app
│       index.js
│       sub.js
│
└───build
        bundle.js
        index.html
```
Someone meet this problem? And how to resolve ?

**Comment by jasonleft** [comment]
My project struct like this:
```
E:.
│   package.json
│   webpack.config.js
│
├───app
│       index.js
│       sub.js
│
└───build
        bundle.js
        index.html
```

**Comment by kevin123de** [comment]
hello!I would like to ask you how to solve this problem.

**Comment by cookcc** [comment]
the above methods that i try fail，finally figure out my problem method is use specific version webpack-dev-sever， like 3.1.0 and on on
