### ISSUE TITLE
Overlay HTML

### ISSUE THREAD

**Issue by joacub** [webpack/webpack-dev-server#3552]
Overlay is showing the html entities instead of html processed by browser.

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/2091228/126585058-05d0de86-599f-4300-a190-eadafa300fa1.png">

**Comment by snitin315** [comment]
Looking into it.

**Comment by alexander-akait** [comment]
Please respect time of other developers, what `normal view`?

**Comment by snitin315** [comment]
The issue here is `'` is being shown as `&apos;` -

for example `Can't -> Can&apos;t` 

<img width="1404" alt="Screenshot 2021-07-22 at 4 44 46 PM" src="https://user-images.githubusercontent.com/46647141/126630716-b2bd61ce-6fc1-43ba-b7a0-8cf8953f55b9.png">

**Comment by alexander-akait** [comment]
oh, I see, let's use `pre` tag for this, maybe it will be even better

**Comment by snitin315** [comment]
> oh, I see, let's use `pre` tag for this, maybe it will be even better

No luck with `pre` tag. 

<img width="1008" alt="Screenshot 2021-07-22 at 5 44 31 PM" src="https://user-images.githubusercontent.com/46647141/126637450-6019a3ed-0694-4e19-a095-09b0a0e07f55.png">

**Comment by joacub** [comment]
> Please respect time of other developers, what is `normal view`?

What do you mean ? Is not enough clear a picture with the html tags in the text ?

why you are so like that ? Don’t even see the picture ?

**Comment by alexander-akait** [comment]
@joacub because using the issue template for everyone it is necessary, I am not like that, you will report a bug so we ask you to use the issue template, this is a banal respect

**Comment by joacub** [comment]
this is a really easy thing html tags are encoded yo htmlentities that's it, should I have to filled a big extensive template for such a simple things,

By the way here is other picture showing the HTML tags, is not just the ', ", is all html, the content is encoded to htmlentities:


<img width="1298" alt="image" src="https://user-images.githubusercontent.com/2091228/126671212-63a701f0-82a9-438e-9097-635bc6719532.png">

**Comment by alexander-akait** [comment]
> this is a really easy thing html tags are encoded to htmlentities that's it, should I have to filled a big extensive template for such a simple things,

Again, it is simple respect, even if the problem is simple, even more there are many repos where bots close issue when the issue template is not used, please understand, other developers, seeing that they not need to use the issue template too, they will decide that they also do not need to for their simple problem, not every problem is actually simple, and it will be the problem for help and create a lot of trash in bug tracker, this is not my whim, this is an experience

**Comment by joacub** [comment]
> > this is a really easy thing html tags are encoded to htmlentities that's it, should I have to filled a big extensive template for such a simple things,
> 
> Again, it is simple respect, even if the problem is simple, even more there are many repos where bots close issue when the issue template is not used, please understand, other developers, seeing that they not need to use the issue template too, they will decide that they also do not need to for their simple problem, not every problem is actually simple, and it will be the problem for help and create a lot of trash in bug tracker, this is not my whim, this is an experience

Good, 🤝
