### ISSUE TITLE
4.0.0-rc.0 crashes when Fiddler is running

### ISSUE THREAD

**Issue by chrisuehlinger-techslice** [webpack/webpack-dev-server#3556]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// snippet from webpack.config.js
  devServer: {
    allowedHosts: ["localhost:8904", ".internal.company.host.com", ".anotherprivatehostname.com"],
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods":
        "GET, POST, PUT, DELETE, PATCH, OPTIONS",
      "Access-Control-Allow-Headers": "*",
    },
    static: {
      directory: i18nPath,
      publicPath: "/i18n",
    },
    host: 'localhost',
    port: 8904,
    historyApiFallback: true,
    hot: false,
    compress: false,
    https: true,
    webSocketServer: "sockjs",
  },
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 17.04 GB / 31.93 GB
  Binaries:
    Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
    Internet Explorer: 11.0.19041.1
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0
    copy-webpack-plugin: ^7.0.0 => 7.0.0
    webpack: ^5.36.0 => 5.45.1
    webpack-bundle-analyzer: ^4.4.1 => 4.4.1
    webpack-cli: ^4.7.0 => 4.7.2
    webpack-dev-server: 4.0.0-rc.0 => 4.0.0-rc.0

### Expected Behavior

Webpack continues to function

### Actual Behavior

The following error shows up in the terminal:
```
C:\Dev\webpack-dev-server-reduced-test-case\node_modules\webpack-dev-server\lib\Server.js:698
        client.terminate();
               ^

TypeError: client.terminate is not a function
    at Server.<anonymous> (C:\Dev\webpack-dev-server-reduced-test-case\node_modules\webpack-dev-server\lib\Server.js:698:16)
    at Server.emit (events.js:327:22)
    at App.emit (C:\Dev\webpack-dev-server-reduced-test-case\node_modules\sockjs\lib\sockjs.js:196:29)
    at C:\Dev\webpack-dev-server-reduced-test-case\node_modules\sockjs\lib\transport.js:111:25
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### For Bugs; How can we reproduce the behavior?

See this reduced test case: https://github.com/chrisuehlinger-techslice/webpack-dev-server-reduced-test-case

**Comment by alexander-akait** [comment]
Why do you use `webSocketServer: "sockjs"? Just interesting

**Comment by chrisuehlinger-techslice** [comment]
> Why do you use `webSocketServer: "sockjs"? Just interesting...But yes, I see the bug, I will fix it

I have to support IE11. I know on paper IE10 is where WebSocket support starts, but in practice I've found that my page won't load in IE11 unless I'm using sockjs.

**Comment by alexander-akait** [comment]
> I have to support IE11. I know on paper IE10 is where WebSocket support starts, but in practice I've found that my page won't load in IE11 unless I'm using sockjs.

Interesting... web socket should works in IE11, Can I use your repo to test it? Or maybe you can provide screenshot/video?

**Comment by chrisuehlinger-techslice** [comment]
Sure thing.

So when I remove that part, restart webpack-dev-server, and open my client's page in IE11, I get the following error (which appears to have no message)
![image](https://user-images.githubusercontent.com/72822856/126678201-f8d503ad-1d43-46ce-a252-7d0910a4617a.png)

And when I click on that line number it takes me here:
![image](https://user-images.githubusercontent.com/72822856/126678323-bc232902-f211-47db-a540-c5a37de90f06.png)

Using sockjs makes this problem go away and everything (up through 4.0.0-beta.3) works fine. Given that my setup (using Fiddler to redirect my customer's JS requests to my local webpack-dev-server when I'm doing local dev) is a bit out of the ordinary, it may be a little tough to make a reduced test case of this (and I don't have other options with this customer's setup). However, since using sockjs works in this case, I'm cool with continuing with this workaround as long as the bug from this issue can get fixed.

**Comment by alexander-akait** [comment]
Anyway you got this produce due `allowedHosts`, your host is not in list

> Using sockjs makes this problem go away and everything (up through 4.0.0-beta.3) works fine. Given that my setup (using Fiddler to redirect my customer's JS requests to my local webpack-dev-server when I'm doing local dev) is a bit out of the ordinary, it may be a little tough to make a reduced test case of this (and I don't have other options with this customer's setup). However, since using sockjs works in this case, I'm cool with continuing with this workaround as long as the bug from this issue can get fixed.

this is due `allowedHosts`, IE 11 is not allowed to connect web socket client to web socket server with different hosts... we need deeply investigate this, I will look at this tomorrow, and try to fix both bugs or describe workaround for IE 11 in this case (if it is not fixable due IE11 internal bugs :smile: )

**Comment by chrisuehlinger-techslice** [comment]
Y'all are awesome, thank you so much.

**Comment by alexander-akait** [comment]
@chrisuehlinger-techslice do you have problems with `ws` in other browsers (chrome/firefox/etc)?

**Comment by chrisuehlinger-techslice** [comment]
> @chrisuehlinger-techslice do you have problems with `ws` in other browsers (chrome/firefox/etc)?

With websockets instead of sockjs, running webpack-dev-server@4.0.0-rc.0, Chrome works fine, IE shows the error screenshotted above, Firefox throws this error (which I have a feeling may be the host issue you referenced earlier): 
![image](https://user-images.githubusercontent.com/72822856/126813589-cb2c9273-1555-4a31-befb-224a0dec1502.png)

**Comment by alexander-akait** [comment]
Yes, look like you need to use `client.webSocketURL: { hostname: '0.0.0.0' }` (will get `self.location.hostname`, also you need proxy web socket requests) to fix it due browsers security problems

**Comment by alexander-akait** [comment]
browsers doesn't allow to connect from your domain to localhost

**Comment by alexander-akait** [comment]
Or you can be it simple `client.webSocketURL: 'auto://0.0.0.0:0/ws'` to get protocol/host/port from browser

**Comment by chrisuehlinger-techslice** [comment]
Part of the problem though is that the site I'm working on isn't being served from localhost, it's on a VM whose hostname is basically "vm-number-that-is-different-for-each-vm.internal.company.host.com"

It's possible that Fiddler has a way to proxy websockets too, I'm looking into that at the moment.

**Comment by alexander-akait** [comment]
> It's possible that Fiddler has a way to proxy websockets too, I'm looking into that at the moment.

Yes, it is right solutions, otherwise you need change web socket client URL, interesting what chrome allow these requests...

**Comment by chrisuehlinger-techslice** [comment]
Dirty problems have dirty solutions! I added an entry to my hostfile that would redirect local-development.clientcompany.com to 127.0.0.1, then used that as `devServer.host`. Now I can work use 4.0.0-rc.0 with websockets turned on and it works in Chrome, Firefox and IE11, thanks a bunch!

Should I keep this issue open until the sockjs issue is fixed and verified?

**Comment by alexander-akait** [comment]
Issue with close sockjs web socket client already fixed here https://github.com/webpack/webpack-dev-server/pull/3562, rc-1 will be today/tomorrow, anyway I recommend to use `ws`, `sockjs` only for IE9, IE8 is not supported :smile: So I think we can close, thanks for detailed issue

**Comment by chrisuehlinger-techslice** [comment]
Thank **you** for this awesome and flexible dev server!
