### ISSUE TITLE
Webpack dev server not reloading on save

### ISSUE THREAD

**Issue by schema0708** [webpack/webpack-dev-server#3558]
**Describe the bug**
Webpack dev server is not reloading on save.

**What is the current behavior?**
When saving my changes nothing happens on save.

**To Reproduce**
Nothing happens when saving

**Expected behavior**
Should reload when saving changes

**Screenshots**
<img width="1792" alt="Screen Shot 2021-07-22 at 5 27 17 PM" src="https://user-images.githubusercontent.com/3027843/126724883-c35759a4-969e-4d27-9114-724c5de3585d.png">

<img width="1434" alt="Screen Shot 2021-07-22 at 5 29 18 PM" src="https://user-images.githubusercontent.com/3027843/126724928-f3a4ac6a-39c5-4202-b486-8d5e7d282eae.png">
**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

webpack.common.js

`const path = require('path');
const webpack = require('webpack');

const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  target: 'web',
  devtool:'inline-source-map',

    entry: './src/index.js',
    plugins: [
      new HtmlWebpackPlugin({
        filename:'index.html',
        template:'./src/index.html',
        inject:false
      }),
      new MiniCssExtractPlugin({
        filename: "[name].css",
        chunkFilename: "[id].css",
      })
    ],

    output: {
      filename: './bundle.js',
      path: path.resolve(__dirname, '../dist'),
      clean:true,
      publicPath: './',
    },
    optimization: {
      minimize: false,
      minimizer: [
        // For webpack@5 you can use the `...` syntax to extend existing minimizers (i.e. `terser-webpack-plugin`), uncomment the next line
        // `...`,
        new CssMinimizerPlugin(),
      ],
    },
    module: {
        rules: [
            // Babel Loader
            {
              test: /\.m?js$/,
              exclude: /(node_modules|bower_components)/,
              use: {
                loader: 'babel-loader',
                options: {
                  cacheDirectory:false,
                  presets: ['@babel/preset-env'],
                  plugins: ['@babel/plugin-proposal-object-rest-spread']
                }
              }
            },

            {
              test: /.s?css$/,
              use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
            },
          // Asset Management for import Images as modules
          {
            test: /\.(png|svg|jpg|jpeg|gif)$/i,
            type: 'asset/resource',
          },
          // Asset Management for loading Fonts
          {
            test: /\.(woff|woff2|eot|ttf|otf)$/i,
            type: 'asset/resource',
          },
          // Asset Management for loading JSON, XML files
          {
            test: /\.(csv|tsv)$/i,
            use: ['csv-loader'],
          },
          {
            test: /\.xml$/i,
            use: ['xml-loader'],
          },
        ]
      }
};`

webpack.dev.json

`const path = require('path');
const { merge } = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'development',
  devServer: {
    historyApiFallback: true,
    contentBase: path.resolve(__dirname, '../dist'),
    open: true,
    compress: true,
    watchContentBase:true,
    hot: true,
    port: 8080,
  },
});`

webpack.prod.json

`const { merge } = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'production',
  devtool: 'source-map',
});`

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
