### ISSUE TITLE
"public" option removed and no docs on replacement for 4.x

### ISSUE THREAD

**Issue by yinzara** [webpack/webpack-dev-server#3565]
When I attempt to use the "public" option of the "devServer" configuration I get the following error:
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
- options has an unknown property 'public'. These properties are valid:
 object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }

https://webpack.js.org/configuration/dev-server/#devserverpublic

The breaking changes documentation for the 4.x version discusses "publicPath" but not "public".  Where was "public" moved?

**Comment by alexander-akait** [comment]
No public anymore, please read https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

> public, sockHost, sockPath, and sockPort options were removed in favor client.webSocketURL option:

**Comment by yinzara** [comment]
Thank you! I read that but must have missed that note. Sorry for the issue!
