### ISSUE TITLE
client GETs the patch.json before webpack is done re-compiling

### ISSUE THREAD

**Issue by jonathanong** [webpack/webpack-dev-server#358]
i've noticed that i always see a 404 when GETing the patch, then i always see `Cannot find update. Need to do a full reload!`

![screen shot 2015-12-30 at 9 24 18 pm](https://cloud.githubusercontent.com/assets/643505/12061460/b33f780e-af3b-11e5-8dd3-1663f22acd70.png)

but if i go to that file, it exists:

![screen shot 2015-12-30 at 9 24 38 pm](https://cloud.githubusercontent.com/assets/643505/12061462/bfca7916-af3b-11e5-9df3-f6d10d0cce8f.png)

my recompiles take 2 seconds - i noticed that the client is GETing the patch before the patch is even written to disk. thus, it 404s and my hot reloading never works.

does anyone have a solution to this?

**Comment by SpaceK33z** [comment]
@jonathanong, do you still have this issue with webpack v2?

**Comment by jonathanong** [comment]
sorry, this was because i configured it wrong. took days to figure out how to configure it correctly. lol.

i haven't tried v2, but will once it's stable. don't wanna spend another few days on that :P

thanks
