### ISSUE TITLE
IMPORTANT July 2021: Chrome private network access restriction with hot module reloading

### ISSUE THREAD

**Issue by FlavioSB** [webpack/webpack-dev-server#3585]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
No code needed, reproducable in Laravel, just setup a Laravel project on a virtual machine service like homestead and run it with HMR (requests will go from private network -> localhost(hmr))
The following error will pop up: 
```
[Deprecation] The website requested a subresource from a network that it could only access because of its users' privileged network position. These requests expose non-public devices and servers to the internet, increasing the risk of a cross-site request forgery (CSRF) attack, and/or information leakage. To mitigate these risks, Chrome deprecates requests to non-public subresources when initiated from non-secure contexts, and will start blocking them in Chrome 92 (July 2021). See https://chromestatus.com/feature/5436853517811712 for more details.
```
I initially posted on the Laravel Mix GitHub because thats where I encountered the issue, they referred to this package.

JeffreyWay/laravel-mix#2987 (first post regarding this issue)
JeffreyWay/laravel-mix#3033 (my post)

### Please paste the results of `webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 6.23 GB / 15.73 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.62)
    Internet Explorer: 11.0.19041.1
```
My example uses laravel and laravel-mix and vue.

### Expected Behavior
- No warning in the console and ongoing support for subresource requests when using this package.
### Actual Behavior
- Warning in console and stopped support for subresource requests as written in the following google posts:
[Google post](https://chromestatus.com/feature/5436853517811712)
[Google dev blog](https://developer.chrome.com/blog/private-network-access-update/)
### For Bugs; How can we reproduce the behavior?
I encountered it in Laravel so: Setup a Laravel project in a private network (E.G. Homestead in my case) and run it with HML. Any request to a page will result in the mentioned warning. Im sure its reproducable in many other ways where this package is used for HMR.

**Comment by alexander-akait** [comment]
Please open an issue in `Laravel` package, not related to webpack-dev-server itself, you do proxy and send requests from public network to local network, you can use https://github.com/chimurai/http-proxy-middleware#http-proxy-options `autoRewrite` and `protocolRewrite` and other `*Rewrite` options, we can't fix it here, it is warning from browser

**Comment by FlavioSB** [comment]
I mentioned in my post that I come from the Laravel GitHub page, they redirected me here, I even linked the original issue pages.

Yes it is a warning from the browser, a warning from the browser which informs you that the hot module reloading functionality (probably one of your most liked implementations) will soon not work anymore with your package. Pretty sure that should be a great concern.

**Comment by alexander-akait** [comment]
@FlavioSB How we can fix it here? We can't rewrite your proxy requests

**Comment by FlavioSB** [comment]
@alexander-akait I only did two things 1. setup a project on homestead and 2. enable your hot module replacement.

Are you saying there just is no fix to this issue at all? Its just google who screws us over?

**Comment by alexander-akait** [comment]
> Are you saying there just is no fix to this issue at all?

It means this problem can be fixed only on your side

> Meaning from now on HMR will only be available for localhost?

No

Just proxy all requests, include http requests and ws, you use different hosts (mixed public and private)

**Comment by FlavioSB** [comment]
So I'd have to proxy my requests which point to e.g. `my-site.test/dashboard` to `localhost/dashboard` so they are in the same network 'class'?

**Comment by alexander-akait** [comment]
Or you can use `0.0.0.0` host

**Comment by FlavioSB** [comment]
Why would I use `0.0.0.0` over `localhost`? HMR already uses a localhost ws. So I'd have to proxy this one to 0.0.0.0 somehow too?

**Comment by alexander-akait** [comment]
> Why would I use 0.0.0.0 over localhost? HMR already uses a localhost ws. So I'd have to proxy this one to 0.0.0.0 somehow too?

When you use `0.0.0.0`, web server client use `window.location` to get valid web socket client URL, but you still need proxy in some cases (public)

**Comment by FlavioSB** [comment]
That would save a lot of time. I'll try that first.
Otherwise I'll use the mentioned package to proxy the requests.
 
Thank you for helping me out!
