### ISSUE TITLE
Better documentation for `injectClient`/`needClientEntry` in migration guide?

### ISSUE THREAD

**Issue by wojtekmaj** [webpack/webpack-dev-server#3587]
- [ ] This is a **bug**
- [x] This is a **modification** request

In 4.0.0-rc.0 release notes we can only read:

> remove entry options (i.e. `hotEntry` and `needClientEntry`) in favor manual setup entries 

and in migration guide:

> * `injectClient` and `injectHot` were removed in favor of manual setup entries.

I find this information a little too cryptic. I have a rather self explanatory piece of config here:

```js
  devServer: {
    client: {
      needClientEntry: isDevelopment,
    },
  }
```

and using the information above I'm not sure how to rewrite this piece.

Please kindly complement the migration guide with a little more details.

**Comment by alexander-akait** [comment]
You can use `client: false`, and include and `entry: [require.resolve("webpack/hot/only-dev-server"), "./path/to/your/entry.js"]`

**Comment by alexander-akait** [comment]
Why you need disable client?

**Comment by wojtekmaj** [comment]
Kinda hacky, but I'm disabling injecting client and hot when isDevelopment = false, so I can use WDS to simulate almost-production build, e.g. for rough page size measurements and other tests.

**Comment by alexander-akait** [comment]
to be honestly it was not designed for this use, anyway solution from above should work

**Comment by wojtekmaj** [comment]
Yep it does. Needed to change true to undefined to use the defaults when I don't need false, but that's it!

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/3598, thanks
