### ISSUE TITLE
[typescript error] Argument of type 'Compiler' is not assignable to parameter of type 'Compiler | MultiCompiler'.

### ISSUE THREAD

**Issue by Tangjj1996** [webpack/webpack-dev-server#3594]
- [x] This is a **bug**
- [ ] This is a **modification** request

```ts
const complier: Compiler = webpack(devOptions);

const server = new WebpackDevServer(complier, {
  hot: true,
  contentBase: path.resolve(__dirname, "../build"),
  publicPath: "/",
});
```

```
Argument of type 'Compiler' is not assignable to parameter of type 'Compiler | MultiCompiler'.
  Type 'Compiler' is missing the following properties from type 'Compiler': _pluginCompat, _plugins, plugin, apply, and 17 more.
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
I use webpack & webpack-dev-server in node with typescript and the package manage is pnpm

### Expected Behavior
not type error by typescript

### Actual Behavior
type error by typescript

I think this error probably because webpack-dev-server devDependencies needs webpack^4.43.0 but I use webpack^5.8.0, however only pnpm manage caugth this error neither npm or yarn

**Comment by alexander-akait** [comment]
Please open an issue in `@types/webpack-dev-server`, we don't have types here right now, it will be in future

**Comment by hmnd** [comment]
@Tangjj1996 while webpack-dev-server doesn't have official typings, I'd suggest this package I made that auto generates types using quicktype: https://www.npmjs.com/package/webpack-dev-server-types.
For these types to take effect, you'll need to remove `@types/webpack-dev-server`. Depending on your TS configuration, you may also need to add `/// <reference types="webpack-dev-server-types" />` to the top of your webpack config.

**Comment by Tangjj1996** [comment]
@hmnd Thanks!
