### ISSUE TITLE
Chokidar package is not update for webpack-dev-server

### ISSUE THREAD

**Issue by vibhor1103** [webpack/webpack-dev-server#3606]
- [ ] This is a **bug**
- [X] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
The glob parent package which is dependent on a module chokidar which is used in project . when the security run on npm module it shows glob parent is vulnerable. 
### Expected Behavior
Show no vulnerability in the project 
### Actual Behavior
Shows vulnerable package as glob parent 

### Solution
Upgrade the package chokidar to it's latest version and fix if any code changes

**Comment by alexander-akait** [comment]
Done in rc, stable release will be on this week
