### ISSUE TITLE
webpack dev server gets stuck if you point it to a dir that doesn't exist yet.

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack-dev-server#361]
While the dev server with hot loading can see file changes and files being created, directories pose a weird problem for it.

The following permanently breaks the dev server run:

- run dev server
- give a file some `require('./dirname')` where the dir doesn't exist yet
- dev server throws an error (correctly)
- make the dir
- dev server throws an error (still, correctly. there is no file to load yet)
- make a file `./dirname/index.js`
- dev server throws an error

This last bit is odd, since both the dir, and the required index.js now exist. Somehow webpack got stuck in a permanent error state (not updating its known dirs/files perhaps?) and needs to be manually killed and restarted before it sees the new, valid, dir with file.

**Comment by SpaceK33z** [comment]
This is most likely related to #462.

**Comment by Pomax** [comment]
No idea, it's been about half a year since I ran into it, but it should be relatively straight forward to bootstrap a webpack config and seeing if this is still the case.

**Comment by SpaceK33z** [comment]
Did a small test, and it seems to work. The author in #462 also says it works now, so closing this. Feel free to re-open if you run into it again.

**Comment by Pomax** [comment]
wfm, thanks
