### ISSUE TITLE
Webpack dev server stuck in hot update or not triggering update on save

### ISSUE THREAD

**Issue by cristisp** [webpack/webpack-dev-server#364]
Hi,

I had some problems even in 0.10 with updates not triggering on file save sometimes but this seems to happen way more often with the latest versions. But my biggest problem is that on hot updates it seems to become stuck and I need to manually refresh the page to get the update on screen.

[WDS] App updated. Recompiling...
client:87 [WDS] App hot update...

Any way around this?

**Comment by jamesdwilson** [comment]
:+1: having same problem

**Comment by Stas404** [comment]
+1

**Comment by danamajid** [comment]
Instead of using the `hot: true` flag, just add the hot module replacement to your `webpack.config.js`

**Comment by Elijen** [comment]
Having the same problem after upgrading to Webpack2. I tried to remove the `--hot` flag and use `new webpack.HotModuleReplacementPlugin()` in `plugins`, but no luck.

@danamajid Do you know if there is anything else I need to do after migrating from Webpack1?

**Comment by alberto2000** [comment]
Any update on this? Having same issue but strangely only when editing html files. JS files trigger HMR correctly 🤔

**Comment by jusefb** [comment]
Having the same issue here with webpack 2

**Comment by jin5354** [comment]
Having the same problem after upgrading to Webpack2.

**Comment by helfi92** [comment]
+1

**Comment by crohlfs** [comment]
Works for me after using both `--hot` and `new webpack.HotModuleReplacementPlugin()` (even though guides seem to say only use either) and having a `webpack/hot/dev-server` entry as outlined [here](https://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement-with-node-js-api)

**Comment by oller** [comment]
Has anyone else got a definitive solution for this, I feel like I've tried every possible combination of:
CLI options `hot/hotOnly/inline` (which I do via grunt-webpack options), adding/removing the `webpack.HotModuleReplacementPlugin()` and adding/removing the `webpack-dev-server` entry points.

Unfortunately I can't replicate @crohlfs success!

The closest I can get is a WDS triggered a page refresh, but it's not hot replacing.  In this scenario i'm changing some `.less` styles, which used to work with webpack1.

**Comment by crohlfs** [comment]
My setup has changed a bit since then, can't remember why. My current solution is:

- `new webpack.HotModuleReplacementPlugin()` in my plugins list
- a `devServer` entry in my `webpack.config.js`, I think you will need to have at least `hot: true` and `inline: true`
- and I run it with `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js` as an npm script

If you have it full refreshing it could mean you aren't watching for/applying the changes properly with the `module.hot.accept` callback. Using ES6 modules I do it as follows:

```js
if (module && module.hot) {
  module.hot.accept('./reducer', () => {
    store.replaceReducer(rootReducer);
  })
}
```

My object `rootReducer` is defined as `import rootReducer from './reducer';`
Inside the callback is it automatically reimported with the hot reloaded changes (or any changes it depends on) and I put a line of code there to tell it how to apply the new rootReducer over the old one. If you ever get it full refreshing like that you should be able to figure out why from the console.

**Comment by mauron85** [comment]
I was facing same problem. In my case I was just missing `webpack-dev-server` dependency. Chrome console was actually showing '[WDS] App hot update...', so I'had feeling everything is ok, but no module was reloaded. Installing `npm i webpack-dev-server --save-dev` resolved my problem.

**Comment by roz0n** [comment]
Hey guys, I ran into this issue today as well with an older React project where I didn't use create-react-app. I stitched together a few solutions from some Stack posts and ultimately did as @mauron85 instructed and it finally works. Here's my code in case others stumble upon this issue.
`
var path = require('path');

module.exports = {
    entry: [
        './src/index.js'
    ],
    devServer: {
      publicPath: "/",
      contentBase: "./dist",
      hot: true
    },
    output: {
        path: path.join(__dirname, '/dist'),
        filename: 'bundle.js',
        publicPath: "/",
    },
    devtool: 'source-map',
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude:   /node_modules/,
                query: { presets: ['react']}
            }
        ]
    }
}

`

**Comment by davvidbaker** [comment]
Ran into this issue tonight too. Solution ended up being the exact same as @mauron85. I have webpack-dev-server installed globally, so the browser console was showing signs of life, but those should not have been trusted! ⚠Beware misleading WDS messages from the console⚠!

**Comment by YangFan789** [comment]
The problem can be solved by cleaning up system temporary files.

**Comment by shellscape** [comment]
Looks like we've got a few solid workarounds for folks. Closing for now.

**Comment by rastogiachyut** [comment]
I fixed this by increasing the number of watchers using:
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by xiayx** [comment]
I forgot to use the command `npm install webpack --save-dev`,
when i installed webpack-dev-server, warn `webpack-dev-server@2.7.1 requires a peer of webpack@^2.2.0 || ^3.0.0 but none was installed.`,  but I thought I had it installed, Actually not

**Comment by nosir** [comment]
Ran into the same issue, @mauron85 's solution solved it

**Comment by krini** [comment]
Removing the --hot flag solved my issue

**Comment by mersanuzun** [comment]
After 5 hours, I solved the problem with removing 'hot: true' from options for WebDevServers constructor.

`const devServer = new WebpackDevServer(compiler, {
      publicPath: `http://0.0.0.0:${this.port}/`,
      hot: true, // Removed
      historyApiFallback: true,
      stats: {
        colors: true,
        chunks: false
      },
      headers: { "Access-Control-Allow-Origin": "*"}
    });`

**Comment by mersanuzun** [comment]
Another issue occurred. When I change style, page is reloaded. I don't want to reload page, only need hot reload.

**Comment by keitetran** [comment]
who can fix this bug :( vuex need hot reload for dev without browser reload :(

**Comment by DevCubeHD** [comment]
Problem still alive, just sayin

**Comment by DevCubeHD** [comment]
https://stackoverflow.com/questions/51813399/static-webpage-webpack-hotloader-does-not-work
