### ISSUE TITLE
Browser rendering bug with Webpack Dev Server Overlay 

### ISSUE THREAD

**Issue by MahdiZerara** [webpack/webpack-dev-server#3648]
- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
- There is a browser rendering bug with Webpack Dev Server overlay as you can see from these two pictures: 

![image](https://user-images.githubusercontent.com/88960606/129469591-94aa180c-1d0c-4f40-9d34-87bb5e2eed5b.png)

![image](https://user-images.githubusercontent.com/88960606/129469601-d8f7e464-9ee2-4ec4-8227-c4ff188e2439.png)

The first picture is the error that I have in my VS Code console and the second is how it is rendered on the Browser 

### Expected Behavior

The overlay is expected to have a styled, clear and easy to read text 

### Actual Behavior

![image](https://user-images.githubusercontent.com/88960606/129469601-d8f7e464-9ee2-4ec4-8227-c4ff188e2439.png)

### For Bugs; How can we reproduce the behavior?

We just need to have any error that can be shown on WDS overlay. Notice that this has been tested with the latest WDS version (4.0.0-rc.0)

**Comment by alexander-akait** [comment]
Fixed in master, release will be soon
