### ISSUE TITLE
Overlay error has html tag

### ISSUE THREAD

**Issue by heart-er** [webpack/webpack-dev-server#3654]
### Version
webpack: 5.50.0
webpack-dev-server: 4.0.0-rc.0

### Code
```js
// webpack.config.js
```
{
    open: true,
    hot: true,
    compress: true,
    client: {
        overlay: true,
    },
    host: '0.0.0.0',
    port: 8090,
};

### Please paste the results of `webpack-cli info` here, and mention other relevant information
none

### Expected Behavior
haven't html tag when errors show

### Actual Behavior
![image](https://user-images.githubusercontent.com/24717511/129663046-96a73f5c-35fb-4726-baa1-ade5ffd83fce.png)

**Comment by alexander-akait** [comment]
Fixed in master, please use search, release will be today
