### ISSUE TITLE
Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null

### ISSUE THREAD

**Issue by ambadyanands** [webpack/webpack-dev-server#3664]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const path = require('path');

module.exports = {
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    port: 9000
  }
};
```

### Please paste the results of `webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 509.27 MB / 15.51 GB
  Binaries:
    Node: 16.6.1 - /tmp/xfs-e6c2604b/node
    Yarn: 3.0.0 - /tmp/xfs-e6c2604b/yarn
    npm: 7.20.5 - /usr/bin/npm
  Browsers:
    Firefox: 90.0.2
```

### Expected Behavior
`webpack serve` works fine without any issues.

### Actual Behavior
`webpack` builds fine without any issues, but `webpack serve` fails with the following error:
```
ERROR in ./.yarn/__virtual__/webpack-virtual-1f668b2097/0/cache/webpack-npm-5.50.0-7f0fb85b9f-293bed1d91.zip/node_modules/webpack/hot/ sync nonrecursive ^\.\/log$
Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
caused by plugins in ContextModule.resolveDependencies
TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
    at URLFS.readdirPromise (.pnp.cjs:14160:5)
    at .pnp.cjs:17356:20
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
 @ ./.yarn/__virtual__/webpack-dev-server-virtual-f91e927911/0/cache/webpack-dev-server-npm-3.11.2-02bc129ea9-d2bfa2e9a3.zip/node_modules/webpack-dev-server/client/index.js?http://localhost:9000 76:17-67
```

**Comment by snitin315** [comment]
What is the version of `webpack-cli` and `webpack-dev-server` are you using? Can you try with `webpack-cli@4.8.0` and `webpack-dev-server@4.0.0-rc.1` ?

**Comment by ambadyanands** [comment]
@snitin315 Oops, sorry for not mentioning the versions. I was using `webpack@5.50.0`, `webpack-cli@4.8.0` and `webpack-dev-server@3.11.2`.

I tried `webpack-dev-serrver@4.0.0-rc.1` and now it is compiling succesfully even if it still shows the following message many times as before.

```
Watchpack Error (initial scan): TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
```

Meanwhile I also did some trial and error and found out that switching to `yarn@3.0.1` (from `3.0.0`) fixes this issue. This is what I did:
```
yarn set version latest
yarn cache clean --all
yarn install
```

So I guess it was an issue with yarn instead of webpack. This is what has changed in `yarn@3.0.1` if it helps: 
> Fixes an edge case with the PnP loader when calling readdir with null as second parameter (instead of undefined).

https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#301

**Comment by ambadyanands** [comment]
I already see 3 similar issues in yarn repo which were already closed:
* https://github.com/yarnpkg/berry/issues/3234
* https://github.com/yarnpkg/berry/issues/3236
* https://github.com/yarnpkg/berry/issues/3237. 

I should have checked there too (but none of the search results from ddg or google showed them up :/).

@snitin315 sorry again and thanks for you time :)
