### ISSUE TITLE
This webpack-dev-middleware will break the devServer.staticOptions

### ISSUE THREAD

**Issue by amit-gshe** [webpack/webpack-dev-server#3670]
- [x] This is a **bug**

### Code

```js
// webpack.config.js
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./index.js",
  mode: "development",
  devtool: "source-map",
  optimization: {
    chunkIds: "named",
    runtimeChunk: "single",
    splitChunks: {
      chunks: "all",
      maxInitialRequests: Infinity,
      minSize: 0,
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: (module) => {
            const packageName = module.context.match(
              /[\\/]node_modules[\\/](.*?)([\\/]|$)/
            )[1];
            return `vendor-${packageName.replace("@", "")}`;
          },
        },
      },
    },
  },
  output: {
    filename: "[name]-[contenthash:6].js",
    chunkFilename: (pathData) => {
      const name = pathData.chunk.id
        .replace(/^src_/, "")
        .replace(/_ts$/, "")
        .replace(/_/g, "/");
      return `${name}-[contenthash:6].js`;
    },
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  devServer: {
    contentBase: path.resolve(__dirname, "dist"),
    port: 3000,
    writeToDisk: true,
    staticOptions: { // This option not works
      etag: false,
      immutable: true,
      maxAge: "7 days",
    },
  },
  plugins: [new HtmlWebpackPlugin()],
};

```

### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information
```
➜  webpack-dev-server-demo git:(master) npx webpack-cli info

  System:
    OS: macOS 11.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 111.98 MB / 8.00 GB
  Binaries:
    Node: 15.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 7.0.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  Packages:
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    webpack: ^5.50.0 => 5.50.0 
    webpack-cli: ^4.8.0 => 4.8.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 

```
```
➜  webpack-dev-server-demo git:(master) npx webpack-cli version                
webpack 5.50.0
webpack-cli 4.8.0
webpack-dev-server 3.11.2
```
### Expected Behavior
- The response header of the static files should have no ETag field
- The response header of the static files should have `Cache-Control: public, max-age=604800, immutable` 
### Actual Behavior
- The response header of the static files contain `ETag` field
- The response header of the static files have no `Cache-Control` field
### For Bugs; How can we reproduce the behavior?
[Here](https://github.com/amit-gshe/webpack-dev-server-demo) is a demo repo can reproduce the behavior

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please respect time of other developers

**Comment by amit-gshe** [comment]
@alexander-akait I edit this issue  but I can't reopen it. Do I need create another issue?

**Comment by alexander-akait** [comment]
What is `webpack-dev-server` version?

**Comment by amit-gshe** [comment]
> What is `webpack-dev-server` version?
```
➜  webpack-dev-server-demo git:(master) npx webpack-cli version                
webpack 5.50.0
webpack-cli 4.8.0
webpack-dev-server 3.11.2
```
@alexander-akait I updated and added version details.

**Comment by alexander-akait** [comment]
Please try `rc-1`, should be fixed

**Comment by amit-gshe** [comment]
> Please try `rc-1`, should be fixed

@alexander-akait I tried `rc-1` but the issue seems not be fixed.

**Comment by alexander-akait** [comment]
Expected, webpack assets !== static assets and handled by other middleware, here issue about supporting cache https://github.com/webpack/webpack-dev-middleware/issues/738
