### ISSUE TITLE
server runing script is not working

### ISSUE THREAD

**Issue by waqaspassu** [webpack/webpack-dev-server#3677]
when I run 

`npx webpack serve`

or setting up a script in package.json

"start":"webpack serve" or "start":"webpack-dev-server" 

it giving other directory name not working

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
