### ISSUE TITLE
webpack-dev-server issue with loading 

### ISSUE THREAD

**Issue by waqaspassu** [webpack/webpack-dev-server#3684]
- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```json
{
  "name": "webpack-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "serve": "webpack serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.51.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.0.0"
  }
}
```

### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information
    "webpack": "^5.51.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.0.0"
### Expected Behavior
when running npm run serve
Need to serve my app on http://localhost:8080/ and not giving any issue as working fine with webpack-dev-server version "3.11.2" 
### Actual Behavior
Serve my app on http://localhost:8080/  but giving this error
Cannot GET /
### For Bugs; How can we reproduce the behavior?
npm run serve

not setting the webpack.config.js. keeping the default setup of webpack

**Comment by alexander-akait** [comment]
> npm run serve

> not setting the webpack.config.js. keeping the default setup of webpack

Sorry, information is not enough to help you, try to remove `output.publicPath`, default value is `auto`

**Comment by waqaspassu** [comment]
I haven't set the public path even the webpack. 
webpack-dev-server is serving from public folder
but by default webpack is bundling the code in dist folder

**Comment by alexander-akait** [comment]
Yes, because static assets !== webpack assets

**Comment by alexander-akait** [comment]
But they can have the same value

**Comment by alexander-akait** [comment]
So you have two variants:
1. Create public dir and put `index.html`
2. Use `html-webpack-plugin` (it generates `idnex.html` to `dist` and will be handled by webpack-dev-middleware)

**Comment by waqaspassu** [comment]
That make sense. Thanks.

**Comment by waqaspassu** [comment]
We need to do extra step here. In version 3.11.2 that webpack-dev-server was also serving from dist folder.

**Comment by alexander-akait** [comment]
we still serve `dist` folder, it is do `webpack-dev-middleware`

**Comment by waqaspassu** [comment]
Okay sure thanks
