### ISSUE TITLE
Typings definition

### ISSUE THREAD

**Issue by PodaruDragos** [webpack/webpack-dev-server#3685]
Is there any plan to ship typing definitions with the package itself ?
`@types/webpack-dev-server` didn't update `4.0.0`. For us users of `webpack.ts` files it would be a great addition if this will also come natively with types

**Comment by alexander-akait** [comment]
Please open an issue in `@types/webpack-dev-server`, we don't have types here, so we can't fix it here

**Comment by alexander-akait** [comment]
Native types in our roadmap and will be in `4.1`/`4.2`

**Comment by PodaruDragos** [comment]
Cool, Thanks for the answer.
