### ISSUE TITLE
Proxy will never take effect when use bypass option

### ISSUE THREAD

**Issue by 0es** [webpack/webpack-dev-server#3686]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

As this commit

https://github.com/webpack/webpack-dev-server/commit/6e2cbde16b0d071b6dd5c243b1b0e867b69575c5#diff-b706bbadb3d2315d99678f05e1f4bfd78a4bb4a7a6c65f3e81f1386fee3c883aR916

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
