### ISSUE TITLE
Proxy will never take effect when use bypass option

### ISSUE THREAD

**Issue by 0es** [webpack/webpack-dev-server#3687]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

As this commit

https://github.com/webpack/webpack-dev-server/commit/6e2cbde16b0d071b6dd5c243b1b0e867b69575c5#diff-b706bbadb3d2315d99678f05e1f4bfd78a4bb4a7a6c65f3e81f1386fee3c883aR916

proxyMiddleware will not generate when use bypass option

### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information

Normal return

### Expected Behavior

proxy take effect

### Actual Behavior

Proxy can't take effect 

### For Bugs; How can we reproduce the behavior?

- pass the proxy option with bypass function

```
proxy: {
  '/': {
    target: 'https://example.com',
    changeOrigin: true,
    secure: false,
    bypass: function(req, res, proxyOptions) {
      if (/\.(js|json|css|html|png|apng|ico|jpg|gif|svga|svg)$/i.test(req.url)) return req.url
    },
  }
}
```
- start dev server
- any request will not be proxied to the specified address normally

**Comment by alexander-akait** [comment]
> For Bugs; How can we reproduce the behavior?

Sorry, I can't reproduce, please respect my and own time, I am not wizard/mage and I don't know what is not working for you, describe your problem clear, no need to put link on source code

**Comment by 0es** [comment]
Sorry for this, and I rewrite the reproduction process

**Comment by alexander-akait** [comment]
Yep, bug, anyway `bypass` will be removed in the next major release, so please migrate on:
```
devServer: {
      proxy: [
        {
          context: (pathname, req) => {
            console.log(req.url);
            
            if (
              /\.(js|json|css|html|png|apng|ico|jpg|gif|svga|svg)$/i.test(
                req.url
              )
            ) {
              return false;
            }
            
            return true;
          },
          target: "https://example.com",
          changeOrigin: true,
          secure: false,
        },
      ],
    },
```

bypass is legacy options when `context` is not support `Function`, but in the next verison, it is possible

**Comment by 0es** [comment]
Understandable, but we have hundreds of projects that use the bypass option. It is very troublesome to synchronize this issue to other developers.
So do we have a compromise solution to fix this problem

**Comment by alexander-akait** [comment]
Yep, I am working on the fix, just note about future migration

**Comment by johnsoncheg** [comment]
@alexander-akait Please fix the problem as soon as possible. LOL~

**Comment by alexander-akait** [comment]
It is already fixed, just not released
