### ISSUE TITLE
websocket trying to connect to currenct URL instead of localhost

### ISSUE THREAD

**Issue by tsarpaul** [webpack/webpack-dev-server#3694]
### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information
webpack 5.51.0
webpack-cli 4.8.0
webpack-dev-server 4.0.0

### Expected Behavior
Chrome extension should speak with the dev server.

### Actual Behavior
I'm developing a chrome extension. The websocket is trying to connect to the current opened tab instead of to localhost.
I'm getting the following error (the websocket is trying to connect to the extension url):
background.bundle.js:12941 WebSocket connection to 'ws://jnlngeheclhhpkgneegdcecmcjolgkhj/ws' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

### For Bugs; How can we reproduce the behavior?
Use the aforementioned packages.
You can use this:
https://github.com/lxieyang/chrome-extension-boilerplate-react
Just change in utils/webserver.js the server variable to:
```
var server =
  new WebpackDevServer(compiler, {
    hot: true,
    static: path.join(__dirname, "../build"),
    port: env.PORT,
    headers: {
      "Access-Control-Allow-Origin": "*"
    },
    devMiddleware: {
      writeToDisk: true
    },
    allowedHosts: 'all'
  });
```

**Comment by alexander-akait** [comment]
Because it is default behavior for web sites, you need to set `client.webSocketURL: { hostname: 'localhost' }`

**Comment by alexander-akait** [comment]
Logic here - https://github.com/webpack/webpack-dev-server/blob/master/client-src/utils/createSocketURL.js#L62

**Comment by alexander-akait** [comment]
But in theory we can improve this, and use `localhost` if it is `extensions`, what is `self.location.protocol`? `chrome-extension`? If yes we can improve this

**Comment by tsarpaul** [comment]
Didn't solve the problem (I used 'host')

**Comment by tsarpaul** [comment]
It didn't solve the issue.

**Comment by alexander-akait** [comment]
What is the error?

**Comment by tsarpaul** [comment]
Same as before, it tries to connect to the local URL. Are you able to reproduce?

**Comment by tsarpaul** [comment]
My bad, this time it uses the local URL as fallback. It fails to connect to localhost:
![image](https://user-images.githubusercontent.com/21146452/130108801-2deb0b34-3324-4fb1-9cbc-2e5c717872c1.png)

**Comment by alexander-akait** [comment]
What is `env.PORT` value?, if not `3000`, you need to set `client.webSocketURL: { hostname: 'localhost', port: 'env.PORT' }`

**Comment by tsarpaul** [comment]
It is 3000

**Comment by tsarpaul** [comment]
I added the env.PORT option regardless, but it's still trying to connect to the local URL (maybe the localhost connection is succeeding now so no error):
![image](https://user-images.githubusercontent.com/21146452/130109730-b5ae0a98-5985-4293-b70c-b3da2b69922f.png)

**Comment by alexander-akait** [comment]
hm, weird, I will check it in near future

**Comment by alexander-akait** [comment]
Here two problems:
1. Bug on our side with extension (WIP on fix)
2. Invalid script:
```js
// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
process.env.ASSET_PATH = '/';

var WebpackDevServer = require('webpack-dev-server'),
  webpack = require('webpack'),
  config = require('../webpack.config'),
  env = require('./env'),
  path = require('path');

var options = config.chromeExtensionBoilerplate || {};

delete config.chromeExtensionBoilerplate;

var compiler = webpack(config);

var server = new WebpackDevServer({
  static: path.join(__dirname, "../build"),
  port: env.PORT,
  headers: {
    "Access-Control-Allow-Origin": "*"
  },
  devMiddleware: {
    writeToDisk: true
  },
  allowedHosts: 'all'
}, compiler);

if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept();
}

server.startCallback(() => {
  // Started
});
```

**Comment by alexander-akait** [comment]
https://github.com/lxieyang/chrome-extension-boilerplate-react is not compatibility with webpack-dev-server v4, they used dirty hacks which was removed in webpack-dev-server v4, so they should refactor own code

**Comment by alexander-akait** [comment]
Try to remove them and show the correct start, wip...

**Comment by alexander-akait** [comment]
Live reload is working:

```js
chromeExtensionBoilerplate: {
    notHotReload: ['contentScript', 'devtools', 'background'],
},
```

```js
// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
process.env.ASSET_PATH = '/';

var WebpackDevServer = require('webpack-dev-server'),
  webpack = require('webpack'),
  config = require('../webpack.config'),
  env = require('./env'),
  path = require('path');

var options = config.chromeExtensionBoilerplate || {};
var excludeEntriesToHotReload = options.notHotReload || [];

for (var entryName in config.entry) {
  if (excludeEntriesToHotReload.indexOf(entryName) === -1) {
    config.entry[entryName] = [
      'webpack-dev-server/client?hostname=localhost&port=' + env.PORT,
    ].concat(config.entry[entryName]);
  }
}

config.plugins = [new webpack.HotModuleReplacementPlugin()].concat(
  config.plugins || []
);

delete config.chromeExtensionBoilerplate;

var compiler = webpack(config);

var server = new WebpackDevServer(compiler, {
  https: false,
  client: false,
  port: env.PORT,
  static: path.join(__dirname, '../build'),
  devMiddleware: {
    writeToDisk: true,
    publicPath: `http://localhost:${env.PORT}`,
  },
  headers: {
    'Access-Control-Allow-Origin': '*',
  },
  allowedHosts: 'all'
});

if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept();
}

server.start();
```

But hmr not, investigate why...

**Comment by alexander-akait** [comment]
Found solution:
1. We need allow to override `hot` and `liveReload` options for client manually (WIP)
2. Configurations:
```js
chromeExtensionBoilerplate: {
    notHotReload: ['contentScript', 'devtools', 'background'],
},
```

I added `background` here, because `hot` is not working for `background`, `background` script has certain specifics, in theory it can be hot module replaced, but `background` script can change content of pages and do other side effects, in this case we should reload the whole page, but here other limitation - `background` script doesn't have own `DOM` (it means it inject all content inside user page), so I think better to use `CTRL + F5`/`F5` when you working on `background` script. Unfortunately my knowledge is not so high in the development of extensions, so it is difficult for me to discuss here about the correct solution. I will be glad to discuss with somebody with mature experience and improve dev server for extension development.

Also here script to run dev server:
```
// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
process.env.ASSET_PATH = '/';

var WebpackDevServer = require('webpack-dev-server'),
  webpack = require('webpack'),
  config = require('../webpack.config'),
  env = require('./env'),
  path = require('path');

var options = config.chromeExtensionBoilerplate || {};
var excludeEntriesToHotReload = options.notHotReload || [];

for (var entryName in config.entry) {
  if (excludeEntriesToHotReload.indexOf(entryName) === -1) {
    config.entry[entryName] = [
      'webpack/hot/dev-server',
      // We need implement `hot=true` here, WIP
      'webpack-dev-server/client?hot=true&hostname=localhost&port=' + env.PORT,
    ].concat(config.entry[entryName]);
  }
}

config.plugins = [new webpack.HotModuleReplacementPlugin()].concat(
  config.plugins || []
);

delete config.chromeExtensionBoilerplate;

var compiler = webpack(config);

var server = new WebpackDevServer(compiler, {
  https: false,
  // We disable hot, because we use manual hot setup, i.e. we adding `webpack/hot/dev-server` and `HotModuleReplacementPlugin` manually (under the hood `hot: true` do the same, but we don't need hot for all entries)
  hot: false,
  // We disable default client in favor `'webpack-dev-server/client?hot=true&hostname=localhost&port=' + env.PORT,`, again because we do it manually
  client: false,
  port: env.PORT,
  static: {
    directory: path.join(__dirname, '../build'),
    // We don't need to watch them on changes, webpack invalidate client itself
    watch: false,
  },
  devMiddleware: {
    publicPath: `http://localhost:${env.PORT}`,
    writeToDisk: true,
  },
  headers: {
    'Access-Control-Allow-Origin': '*',
  },
  allowedHosts: 'all'
});

if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept();
}

// Not is promise
server.start();
```
