### ISSUE TITLE
Cannot reset port after `webpack-dev-server` use

### ISSUE THREAD

**Issue by dmitriz** [webpack/webpack-dev-server#371]
Having run and closed  `webpack-dev-server` I cannot use `localhost:8080` anymore. 

It continues serving the same file!

Is this a bug? 
Any way I can reset this port for other services?

**Comment by SpaceK33z** [comment]
Do you still have this issue? If so, how do you use WDS (CLI or API), and what is your platform? I'm certain this does not happen on OSX or Linux.

**Comment by SpaceK33z** [comment]
This should be fixed with #357. This will be part of the next 1.x release.
