### ISSUE TITLE
Browser console error: WebSocket connection to 'ws://0.0.0.0:3000/sockjs-node' failed

### ISSUE THREAD

**Issue by nikhilnayyar002** [webpack/webpack-dev-server#3712]
- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
            devServer: {
                host: '0.0.0.0',
                port: 3000,
```
The code above results in browser console error:
`WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/sockjs-node' failed: `

## Additional Information
These works without showing the above described error in browser:
```js
// webpack.config.js
            devServer: {
                host: 'local-ip',
                port: 3000,
```
```js
// webpack.config.js
            devServer: {
                host: 'localhost',
                port: 3000,
```

### Please paste the results of `webpack-cli info` and `webpack-cli version` here, and mention other relevant information
webpack-cli info:
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.88 GB / 7.85 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
    Internet Explorer: 11.0.19041.906
  Packages:
    clean-terminal-webpack-plugin: ^3.0.0 => 3.0.0
    css-minimizer-webpack-plugin: ^3.0.2 => 3.0.2
    eslint-webpack-plugin: ^3.0.1 => 3.0.1
    event-hooks-webpack-plugin: ^2.2.0 => 2.2.0
    html-webpack-plugin: ^5.3.2 => 5.3.2
    speed-measure-webpack-plugin: ^1.5.0 => 1.5.0
    terser-webpack-plugin: ^5.1.4 => 5.1.4
    webpack: ^5.51.1 => 5.51.1
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^4.0.0 => 4.0.0
    webpack-merge: ^5.8.0 => 5.8.0
```
webpack-cli version
```
webpack 5.51.1
webpack-cli 4.8.0
webpack-dev-server 4.0.0
```
### Expected Behavior
devServer.host : "0.0.0.0" should work fine like other values : 'local-ip' | 'local-ipv4' | 'local-ipv6'
### Actual Behavior
```js
// webpack.config.js
            devServer: {
                host: '0.0.0.0',
                port: 3000,
```
The code above results in browser console error:
WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/sockjs-node' failed: 

![image](https://user-images.githubusercontent.com/38173563/130314843-362da9a7-fbd7-45e1-8be6-6a27d36aff15.png)

### For Bugs; How can we reproduce the behavior?
Try changing host to "0.0.0.0"
```js
// webpack.config.js
            devServer: {
                host: '0.0.0.0',
                port: 3000,
```
original repo link: https://github.com/nikhilnayyar002/react-min

### For Features; What is the motivation and/or use-case for the feature?
devServer.host : "0.0.0.0" is an important value for local devices to connect to our web application. So if this thing is solved then its nice.

**Comment by alexander-akait** [comment]
Can't reproduce, works fine, if you need help please provide all steps to reproduce, even more `ws://0.0.0.0:3000/sockjs-node` is not valid, our default URL is `ws://<self.location.hostname>:3000/ws`

**Comment by alexander-akait** [comment]
Also please read migration guide, we explicit say what you should not use `new webpack.HotModuleReplacementPlugin()` if hot is true, it is on first lines

**Comment by nikhilnayyar002** [comment]
Yeah I can see this one mentioned in migration guide: 
> webpack-dev-server v3 and webpack-dev-server v4 automatically apply HotModuleReplacementPlugin plugin when you set hot: true, so please check you don't have HotModuleReplacementPlugin in your plugins if you have hot: true/hot: "only"

But the confusion is that if it is enabled by default only when passing `--hot` option using command line or for both when command line as well as webpack.config.js ?

**Comment by nikhilnayyar002** [comment]
This is the repo link:  ​https://github.com/nikhilnayyar002/react-min

commands to reproduce:
```
git clone https://github.com/nikhilnayyar002/react-min.git
npm ci
npm start
```

Weird thing is that the error does not appear in browser console when I ran in Apple Macbook Pro M1 but this is happening in my Windows Laptop.
