### ISSUE TITLE
broken script host detection in the client - Uncaught TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by pbc** [webpack/webpack-dev-server#372]
This commit introduces a broken detection of the script host:

https://github.com/webpack/webpack-dev-server/commit/3d3c000df8889e8b557995e5fe918b29072c377f#diff-895656aeaccff5d7c0f56a113ede9662

The code assumes that all script tags have a "src" attribute.

In my case it breaks the following load script which is the last script tag:

    <script>
        $(function () {
          $.getScript("//localhost:8080/react-build/app_rjs_bundle.js");
        });
    </script>

**Comment by SpaceK33z** [comment]
This was fixed with #447 a while ago.
