### ISSUE TITLE
import.meta error

### ISSUE THREAD

**Issue by abhishekrathore03** [webpack/webpack-dev-server#3730]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Use any in-general webpack config and enable the following
```js
experiments: {
     outputModule: true,
},
```
### Webpack output -
webpack-compiles successfully with the following output `webpack 5.51.1 compiled successfully in 47393 ms`

### Expected Behavior
The build should run properly on web browser

### Actual Behavior
Build throws the following error - 
`Uncaught SyntaxError: Cannot use 'import.meta' outside a module`

Please note that this error occurs only on using webpack-dev-server
If i am hosting the build using http-server the output bundle works fine without any error

**Comment by alexander-akait** [comment]
Not related to webpack, you need `type="module"` on `script` tag
