### ISSUE TITLE
Issue updating to 4.0

### ISSUE THREAD

**Issue by luanvdang** [webpack/webpack-dev-server#3733]
Running into this issue when updating to version 4.0, running on version 3.11.2 works fine.

![Screen Shot 2021-08-23 at 5 01 06 PM](https://user-images.githubusercontent.com/83619148/130534898-e12bbc78-3021-4a9d-9c1f-2caa2b9d6181.png)

**Comment by snitin315** [comment]
`devServer.stats` was removed in favor of webpack stats, you can simply configure `options.stats`. For more changes please read our migration guide - https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
