### ISSUE TITLE
`lvh.me` in self-signed certificate

### ISSUE THREAD

**Issue by ylemkimon** [webpack/webpack-dev-server#3735]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

https://github.com/webpack/webpack-dev-server/blob/135c1f19b78949440a6934adac4388dfd3b34039/lib/Server.js#L611-L618

### Expected Behavior

Remove `lvh.me` and `*.lvh.me` from `subjectAltName`s for the self-signed SSL certificate.

### Actual Behavior

`lvh.me` and `*.lvh.me` are included as `subjectAltName`s for the self-signed SSL certificate. However, `lvh.me` is a privately-owned service and its operation may stop or be compromised anytime. I think there is no reason for webpack-dev-server to include them by default.

**Comment by alexander-akait** [comment]
Sorry, we don't want to do it, it was added previously for some internal reasons
