### ISSUE TITLE
options has an unknown property 'contentBase'.

### ISSUE THREAD

**Issue by superXJg** [webpack/webpack-dev-server#3742]
"webpack": "^5.51.1",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.0.0"

```
devServer: {
       contentBase: path.resolve(__dirname, './src/index.html')
 }
```
**npm run  "webpack serve --open chrome.exe"**

**output :  Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'contentBase'. These properties are valid:**

_So how to replace contentBase?_

**Comment by alexander-akait** [comment]
Please read https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by alexander-akait** [comment]
There are a lot of example how to migrate
