### ISSUE TITLE
Multiple Content Bases needed for whitelabels and other use-cases.

### ISSUE THREAD

**Issue by BerndWessels** [webpack/webpack-dev-server#375]
Hello

At the moment `contentBase` can only take a single source. In many cases that is just not good enough and forces us to build terrible workarounds to support multiple content bases.

An example is whitelabels. We have lots of files that are common to all whitelabels but each whitelabel also has lots of specific files. So what we really want is the separation of the common and each of the whitelabels in different directories - but then served all together as a combined content base.

This is easy to achive for `production builds` via plugins like this:

    if (BUILD) {
      config.plugins.push(
        new CopyWebpackPlugin([
          { from: 'public/common' },
          { from: 'public/' + WHITELABEL }
        ]),

Unfortunately such scenarios are currently not supported by `webpack-dev-server` and that causes a lot of headache for the development process.

But actually to achieve that we only need to allow contentBase to also accept an array of sources.

      contentBase: ['./public/common', './public/whitelabel5']

The change to `webpack-dev-server` is minimal and I created [this pull request](https://github.com/webpack/webpack-dev-server/pull/374) already.

**Comment by sokra** [comment]
merged
