### ISSUE TITLE
4.0.0-rc.1 broke proxy option

### ISSUE THREAD

**Issue by Akryum** [webpack/webpack-dev-server#3757]
- [x] This is a **bug**
- [ ] This is a **modification** request

v4.0.0-rc.1 broke the `proxy` option. We use it for local development of the Vue.js devtools to proxy the `/` (index) page (`http://localhost:8090`) to another url (`http://localhost:8091`).

### Code

https://github.com/vuejs/devtools/blob/89b071056d872c093a60a44f180a3633a39ac20a/packages/shell-dev-vue3/webpack.config.js#L41-L48

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Linux 5.11 elementary OS 6 Odin
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
    Memory: 1.37 GB / 62.79 GB
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.6.1/bin/yarn
    npm: 7.20.5 - ~/.nvm/versions/node/v16.6.1/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
```

### Expected Behavior

Proxy works, get the proxied `index.html` from `localhost:8091`

### Actual Behavior

Proxy doesn't work, get directory listing of `localhost:8090/`

### For Bugs; How can we reproduce the behavior?

1. Clone [`vuejs/vue-devtools`](https://github.com/vuejs/devtools)
2. Change the `resolutions` config in `package.json` with `webpack-dev-server` to `4.0.0-rc.1` or `4.0.0` and run `yarn install`
3. Run `yarn build:watch`
4. In another terminal, run `yarn dev:vue3`
5. Open [http://localhost:8090](http://localhost:8090)
6. Instead of having the dev page with the vue devtools, you'll get the directory listing of `packages/shell-dev-vue3/public`.

You can repeat the steps with `4.0.0-rc.0` to see the expected behavior.

Note that adding this doesn't fix the issue:

```js
static: {
  serveIndex: false
}
```

**Comment by alexander-akait** [comment]
Fixed in master, release (`4.1.0`) will be today
