### ISSUE TITLE
Cannot GET on simple getting started

### ISSUE THREAD

**Issue by wernert** [webpack/webpack-dev-server#3762]
- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
none
```

### results of `npx webpack-cli info` 
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 4.13 GB / 15.93 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.906
  Packages:
    webpack: ^5.51.1 => 5.51.1
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^4.0.0 => 4.0.0

### Expected Behavior
working page

### Actual Behavior
Cannot GET  
error 404

### For Bugs; How can we reproduce the behavior?

follow https://webpack.js.org/guides/getting-started/  first section
index.html in root, index.js in src 
run npx webpack serve
open http://localhost:8080

**Comment by snitin315** [comment]
Because route `/` is not defined, Go to `localhost:8080/main` you will see `Hello Webpack` text.

**Comment by alexander-akait** [comment]
Answered
