### ISSUE TITLE
Invalid options object

### ISSUE THREAD

**Issue by dcd-api** [webpack/webpack-dev-server#3769]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'contentBase'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?,
 onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }

### Expected Behavior
its strange i tried even with this tool https://createapp.dev/ but also tried 2 days to setup it with the newest webpack togheter 
but i get again and again this error i expect its a bug 

### Actual Behavior
i get an error message 

### For Bugs; How can we reproduce the behavior?
create an app react app with https://createapp.dev/ and try to run it

**Comment by dcd-api** [comment]
I hope someone can look at this because i really trying here to have a stable express webpack with hmr setup. 
thanks so much for the effort creating stuff like this

**Comment by alexander-akait** [comment]
Please read https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md, `contentBase` is deprecated in favor `static`, you should report in https://createapp.dev/ to fix it, we can't fix it here, sorry

**Comment by Slapbox** [comment]
@alexander-akait it's not clear from the migration guide that `contentBase` is deprecated. The guide says that it was moved:

> `contentBase`/`contentBasePublicPath`/`serveIndex`/`watchContentBase`/`watchOptions`/`staticOptions` options were moved to static option:

Can you advise how we would update code like ` contentBase: path.join(rootPath, 'dist'),` to work with v4?

**Comment by alexander-akait** [comment]
Just set `static: path.join(rootPath, 'dist')`

**Comment by Slapbox** [comment]
Thanks for your reply! It was indeed required.
