### ISSUE TITLE
webSocketServer undocumented and not working

### ISSUE THREAD

**Issue by KutnerUri** [webpack/webpack-dev-server#3777]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

I'm trying to run WDS in with a proxy. For this reason, I made this setup:

Here is my original setup:
```ts
const webpackConfig = {
  devServer: {
    client: {
      path: `_hmr/teambit.react/react`,
    },
  },
};
```

My new setup, after migrating to v4:
```ts
const webpackConfig = {
  devServer: {
    webSocketServer: {
      options: {
        pathname: `_hmr/teambit.react/react`,
        path: `_hmr/teambit.react/react`,
        // port: 3300, // port of the proxied server, automatic
      },
    },
    client: {
      webSocketURL: {
        pathname: `_hmr/teambit.react/react`,
        // port: 3000, // proxy server, also automatic
      }
    },
  },
};
```

Please advise.
Also, please document the arguments of webSocketServer, the only description comes from the source code (where there is `path` `pathname`, and `prefix`, and they all seem to do the same thing)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
I'm using webpack + WDS programmatically, so I cannot run `npx webpack-cli info`

### Expected Behavior
I'm expecting `ws://localhost:3300/_hmr/teambit.react/react` to be available.

### Actual Behavior
I can't find the correct path WDS is using for the HMR socket.

![Screen Shot 2021-09-02 at 15 43 32](https://user-images.githubusercontent.com/5400361/131845571-c03f5e1d-80b7-45e5-a588-baf1f6bc4a8b.png)

If I remove these configs, the original path `ws://localhost:3300/ws` works correctly:
![Screen Shot 2021-09-02 at 15 45 54](https://user-images.githubusercontent.com/5400361/131845956-b3583733-08b7-438d-8984-8e4448fe5611.png)

**Comment by alexander-akait** [comment]
Described in migration guide https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md, this option only for client, if you need to change server path you need to use

> If you need to set custom path to dev server web socket server, please use:

```js
module.exports = {
  devServer: {
    webSocketServer: {
      options: {
        path: "/my/custom/path/to/web/socket/server",
      },
    },
  },
};
```

**Comment by KutnerUri** [comment]
it's not working. I'm only using
```
config.devServer.webSocketServer.options.path: '_hmr/teambit.react/react'
```

aahh, it needs a `/` prefix! this works:
```
config.devServer.webSocketServer.options.path: '_hmr/teambit.react/react'
```

this is very confusing!

**Comment by alexander-akait** [comment]
it how URL routing works, you should always use `/` before
