### ISSUE TITLE
Watch works exactly once without polling

### ISSUE THREAD

**Issue by mnpenner** [webpack/webpack-dev-server#379]
Here's the scenario: I start up webpack-dev-server and wait for my page to finish loading. Then I edit a .less file on my computer, it gets rsync'd into my Vagrant box where webpack-dev-server is running, WDS picks up the change and HMR refreshes my CSS without a full page reload. However, when I edit my .less *again* then nothing happens. Nothing is logged to Chrome's dev console, and WDS doesn't print anything to the terminal.

If I enable polling,

    watchOptions: {
        aggregateTimeout: 250,
        poll: 50
    },

then everything works fine.

If I had to take a guess, I suspect rsync is recreating the file and that's destroying the [inotify?] watch. At least that would explain why it works once.

**Comment by skylerrichter** [comment]
Ran into this issue today as well.

Adding watchOptions fixes it.

**Comment by sigo** [comment]
The same issue here. Problem was affected at all linux-machine at our office. Explicitly defining watchOptions works.

**Comment by SpaceK33z** [comment]
Jep, `--watch-poll`, or the `watchOptions` equivalent is necessary for Vagrant boxes to work.
