### ISSUE TITLE
cannot get Chinese named file.

### ISSUE THREAD

**Issue by lili21** [webpack/webpack-dev-server#382]
![2016-01-22 2 14 55](https://cloud.githubusercontent.com/assets/4456380/12503744/2ff41cb4-c112-11e5-9530-808dbc23575f.png)

According to the image, the server contains those Chinese named files.

But after I clicked one of those.

![2016-01-22 2 17 44](https://cloud.githubusercontent.com/assets/4456380/12503773/8870d1b6-c112-11e5-992a-aa59c5e0a924.png)

Any idea ?

**Comment by airwin** [comment]
Hey, can you share ur solution? I meet the similar problem too.

**Comment by lili21** [comment]
Sorry . I forget that.

I think I am running `webpack-dev-server` mannual , by node.js api.

[docs](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode-with-node-js-api).

Hope that can be helpful.

**Comment by airwin** [comment]
Thanks.~

**Comment by qq645381995** [comment]
@lili21  我这也不行 你最后怎么弄的？
