### ISSUE TITLE
Local environment breaks when using module federation with splitChunks set to all

### ISSUE THREAD

**Issue by wlshopee** [webpack/webpack-dev-server#3829]
- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

https://github.com/wlshopee/devserver-mod-fed-all-chunks

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.54 MB / 16.00 GB
  Binaries:
    Node: 14.17.3 - ~/.volta/tools/image/node/14.17.3/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.13 - ~/.volta/tools/image/node/14.17.3/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 91.0.1
    Safari: 14.1.2
```

### Expected Behavior

I have two apps, app1 and app2. app1 imports a button from app2 through module federation. 

app2 has "splitChunks" set to "all" in their webpack config:

```js
 optimization: {
    splitChunks: { chunks: 'all' },
  },
```

When I visit app1 (http://localhost:3001), it should load the button from app2 correctly.

### Actual Behavior

When visiting http://localhost:3001, it fails to load app2.

![Screenshot 2021-09-10 at 15 37 33](https://user-images.githubusercontent.com/66941035/132817964-8c03b354-3429-476d-a287-c070b780c925.png)

Further investigation seems to show that, the vendor chunk `vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname...` does not get loaded by `remoteEntry.js`. However, this chunk issue doesn't appear if we build in production mode and run the project without using `webpack-dev-server`.

### For Bugs; How can we reproduce the behavior?

Clone https://github.com/wlshopee/devserver-mod-fed-all-chunks and run `yarn start` on the root directory to get both apps running. When you visit app1 (http://localhost:3001), nothing is shown and the console has the errors.

If I remove just the splitChunk optimization from app2's webpack config, the issue does not surface.

### For Features; What is the motivation and/or use-case for the feature?

N.A.

**Comment by alexander-akait** [comment]
I want to say it is limitation, honestly this problem is not related to dev server, it is in webpack, when you bundle and split library you need to `import` all splited chunks, but dev server is adding client chunk as initial, look here for `app2`, generated HTML:
```html
<script defer src="vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-2d50fa.js"></script><script defer src="main.js"></script><script defer src="remoteEntry.js">
```

but for app1 you use only
```
remoteEntry.js
```

How you can fix it? Go to `app1/dist/index.html` and use
```
<html><head><script defer="defer" src="main.js"></script><script src="http://localhost:3002/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-2d50fa.js"></script></head><body><div id="root"></div></body></html>
```

i.e. we added initial chunk dev server chunk, not sure `splitChunks: { chunks: 'all' }` is good idea at all for module federation, shortly - your extract initial chunks but don't load it

**Comment by alexander-akait** [comment]
Shortly -`remoteEntry.js` need to load `vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-2d50fa.js` before start work because `vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_0_0_0_0_port_-2d50fa.js` is initial chunks added by dev server, but in app1 you don't have it

**Comment by alexander-akait** [comment]
My fully recommendation - do not use `splitChunks: { chunks: 'all' }`, it is not good for optimization and in this case you need to load initial chunks manually

**Comment by yiminghe** [comment]
v3 works, but after upgrading to v4 it breaks

**Comment by alexander-akait** [comment]
@yiminghe your information is not help yo help you

**Comment by alexander-akait** [comment]
Feel free to feedback, unfortunately we can't fix it here, if you still think we do something wrong, please open an issue in webpack repo

**Comment by cansin** [comment]
I couldn't follow the suggested solution for people who want to use `chunks: "all"` @alexander-akait. Should we simply disable optimization on the dev server and keep it only on production?

**Comment by alexander-akait** [comment]
@cansin What is error your got? Can you provide more infromation?
