### ISSUE TITLE
webpack 5: output evaluation no longer returns a module

### ISSUE THREAD

**Issue by falsyvalues** [webpack/webpack-dev-server#3853]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Right after webpack update (from v4 to v5) I noticed that output evaluation no longer returns a module. Not sure if its more related to `webpack bootstrap` code or `webpack-dev-server` wrapper code?

```js
// webpack.config.js
module.exports = env => ({
    entry: {
        app: `./packages/test/src/loader.ts`
    },
    mode: 'development',
    module: {
        rules: [
            {
                test: /\.(ts|js)x?$/,
                use: 'babel-loader',
                exclude: /node_modules/
            }
        ]
    },
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.json'],
        mainFields: ['es2015', 'module', 'main'],
        modules: [path.resolve(__dirname, 'node_modules'), 'node_modules']
    },
    devtool: 'cheap-module-source-map',
    devServer: {
        client: {
            overlay: false
        },
        hot: 'only',
        port: 5000,
        https: true,
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD',
            'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
        }
    },
    plugins: [new CleanWebpackPlugin()],
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: 'https://localhost:5000/'
    }
});

```

```js
// loader.ts
export function test() {
   return 0;
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 4.18 GB / 15.79 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
    Internet Explorer: 11.0.19041.1
  Monorepos:
    Lerna: 4.0.0
  Packages:
    clean-webpack-plugin: 3.0.0 => 3.0.0
    replace-in-file-webpack-plugin: 1.0.6 => 1.0.6
    webpack: 5.52.1 => 5.52.1
    webpack-cli: 4.8.0 => 4.8.0
    webpack-dev-server: 4.2.1 => 4.2.1
    webpack-merge: 5.8.0 => 5.8.0
```

### Expected Behavior

On webpack 4 output evaluation resulted in a module, so it was easy to use exported bits.

```js
fetch('https://localhost:5000/app.bundle.js')
  .then(resp => resp.text())
  .then(script => {
    const result = eval(script);
    // result is not a undefined
    assert(typeof result !== 'undefined');
    // result contains exported bits
    assert(typeof result.test !== 'undefined');
  });
```

### Actual Behavior
```js
fetch('https://localhost:5000/app.bundle.js')
  .then(resp => resp.text())
  .then(script => {
    // this no longer works
    const result = eval(script);
    assert(typeof result === 'undefined');
  });
```

### For Bugs; How can we reproduce the behavior?

Assuming that we have `webpack` configured like above, create a simple module that export a function and try to evaluate it in other env.

**Comment by alexander-akait** [comment]
This is breaking change for webpack v5, if you need build library you need to use `output.library` https://webpack.js.org/configuration/output/#outputlibrary, feel free to feedback

**Comment by alexander-akait** [comment]
Even more it is unsafe, because webpack can remove unused exports

**Comment by falsyvalues** [comment]
@alexander-akait thanks for information. I was going through https://webpack.js.org/migrate/5/ be this article don't mention this change at all, but I guess it could.

**Comment by alexander-akait** [comment]
This use has never been safe, moreover, I don't think anyone has used it, maybe we should add it to the documentation, PR welcome

**Comment by falsyvalues** [comment]
> This use has never been safe, moreover, I don't think anyone has used it, maybe we should add it to the documentation, PR welcome

It weird to read `I don't think anyone has used it` in ticket related to it. I personally think that lots of projects are still on webpack 4 because of dependencies they use, so more issues will pop up sooner or later. I will try to tackle docs.

**Comment by alexander-akait** [comment]
webpack has own logic for loading chunks, it is really dangerous to use own, you need to have plugin for this, no just using `fetch`

**Comment by alexander-akait** [comment]
Or just switch on library generation and all will work fine and expected

**Comment by falsyvalues** [comment]
@alexander-akait Thanks for details I'm aware of that especially after reading docs for webpack 5. I'm already on library generation for now and its compatible with webpack 4 🙌 (at least it looks like).
