### ISSUE TITLE
Build file missing

### ISSUE THREAD

**Issue by Tjorriemorrie** [webpack/webpack-dev-server#386]
I'm running:

> "dev": "webpack-dev-server --port 8989 --devtool eval --progress --colors --content-base gae/src",

When I go to `localhost:8989` my build file is not there. Even after changing a file and webpack building it again there is no build file.

config:
```
var path = require('path');

module.exports = {
    entry: path.resolve(__dirname, 'assets/jsx/Index.jsx'),
    output: {
        path: path.resolve(__dirname, 'gae/src/static/build'),
        publicPath: 'static',
        filename: 'besetfree.js'
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel',
                query: {
                    presets: ['react', 'es2015']
                }
            }
        ]
    }
};
```

Do you mind improving the docs as well: it's really confusing about how to set this up and I'm not even trying hmr

**Comment by MatthiasWinkelmann** [comment]
Webpack-dev-server doesn't write to the fs but serves the requests from memory. See [https://webpack.github.io/docs/webpack-dev-server.html#content-base](https://webpack.github.io/docs/webpack-dev-server.html#content-base).

(+1 on your suggesting to improve the docs, or, even better, uninsanify the config)

**Comment by Tjorriemorrie** [comment]
Thanks. What is the best practice to change your html file to include the webpack-dev-server files instead of the build files when developing?
