### ISSUE TITLE
This plugin ignores file changes if folder name start with watch 

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [webpack/webpack-dev-server#3868]
- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
    "webpack-dev-server": "^3.11.2",
### Expected Behavior
file changes should start compile even if folder name start with watch
### Actual Behavior
if folder name start with watch then this will not trigger file change for all files in this this folder
### For Bugs; How can we reproduce the behavior?
Yes

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

I don't understand the problem, please fill out all fields

**Comment by mandadimuralidharreddy** [comment]
I have filled all the required fields. 
The issue is am using this plugin in my project and i have folder i(folder name watchParty) in my code. This plugin not doing hot reload for file changes in watchParty folder.

**Comment by alexander-akait** [comment]
Because you need to setup watching this directory

**Comment by mandadimuralidharreddy** [comment]
its watching all other folder in src directory but ignoring folder name starts with watch in src dir

**Comment by alexander-akait** [comment]
Please create reproducible test repo
