### ISSUE TITLE
Cannot read properties of undefined (reading 'call') when hot: false, devtool: false, an entry has dependOn

### ISSUE THREAD

**Issue by markjm** [webpack/webpack-dev-server#3869]
Hi @alexander-akait - I have a difficult (for me, at least) bug report:

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code
There seems to be some issue related to the injected WDS client entry when `hot: false`, `devtool: false`, and there are multiple entries linked by `dependOn`.

In the below repro example, it seems that `webpackRuntimeModules` snippet is being injected in `main.js`, while the `__webpack_modules__["webpack-dev-server/client/index.js"]` entry exists in `lead.js`. This works fine when devtool is enabled because, because devtool (EvalDevToolPlugin) triggers `inlineInRuntimeBailout` - which ensures `webpack-dev-server/client/index.js` is **not** inlined (so `main.js` can still execute it). 

When there is no inlining runtime bailout, which happens when `devtool: false`, the code of `webpack-dev-server/client/index.js` is inlined in `loader.js` and so `main.js`'s attempt to execute this code fails. As more evidence that this is due to some inlining, I can go and manually set `allowInlineStartup = false` in `lib/javascript/JavascriptModulesPlugin.js` and see everything working as expected again.

### npx webpack-cli info
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.49 GB / 15.92 GB
  Binaries:
    Node: 16.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
    Internet Explorer: 11.0.19041.1202
  Packages:
    html-webpack-plugin: ^5.3.2 => 5.3.2
    webpack: ^5.52.1 => 5.52.1
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^4.2.1 => 4.2.1
### Expected Behavior
Browser console prints `main` and `lead` to console

### Actual Behavior
webpack runtime error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (lead.js:4040)
    at __webpack_exec__ (main.js:15)
    at main.js:16
    at webpackJsonpCallback (lead.js:4186)
    at Array.forEach (<anonymous>)
    at lead.js:4200
    at lead.js:4202
    at lead.js:4419
```

### For Bugs; How can we reproduce the behavior?

Repro: https://github.com/markjm/demos-by-commit/tree/repro-dev-server-1
Run `yarn` then `yarn webpack serve` and open in browser.

**Comment by alexander-akait** [comment]
Yep, limitation for multiple entries, set:
```
optimization: {
  runtimeChunk: true
},
```

https://github.com/webpack/webpack-dev-server/issues/2792, why https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432

**Comment by alexander-akait** [comment]
I do not close https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432 due this problem, maybe for better DX we need to force set `optimization.runtimeChunk` for multi entries, but it can be unsafe in some cases, so I prefer to keep open until we will found the best solution

**Comment by markjm** [comment]
Hm - thanks for the context. Due to some internal wackyness, runtimeChunk is an unsafe option for us - but I will keep investigating our options. Maybe we can just very fragile-ly keep devtool enabled for now :)

**Comment by alexander-akait** [comment]
let close in favor https://github.com/webpack/webpack-dev-server/issues/2792? If you need feedbakc or help you can write there

**Comment by markjm** [comment]
Sure - though the title of 2792 implies its just HMR, but in this example we are specifically not disabling `hot`

**Comment by alexander-akait** [comment]
Yep, it is how entries embedded in your chunks, as other idea maybe we can do it more smart then we apply Entry plugin and webpack can understand where to put runtime, but let's track it in https://github.com/webpack/webpack-dev-server/issues/2792
