### ISSUE TITLE
do not start connent to web socket server when server socket doesn't start

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack-dev-server#3873]
> `webSocketServer: false` should be enough

Agreed.
But without `client: false`, I noticed that the served js still trying to connect to ws server, but returning 404 as server was disabled by `webSocketServer: false`. This may bother someone with OCD. lol

![image](https://user-images.githubusercontent.com/34376497/134512944-1842b88e-a929-4cb2-9465-a87164af355c.png)

_Originally posted by @fevernova90 in https://github.com/webpack/webpack-dev-server/issues/1430#issuecomment-925806727_

**Comment by fevernova90** [comment]
Awesome! Thank you!
