### ISSUE TITLE
Add a way to customize / replace / suppress info at startup

### ISSUE THREAD

**Issue by jsg2021** [webpack/webpack-dev-server#3875]
- [ ] This is a **bug**
- [x] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
I don't think this tools out is relevant here, but for posterity, I tried... but webpack-cli isn't workspace aware. (npm 7) and cannot find `webpack` :P even though it *is* in the workspace root's node_modules. Attempting to say 'yes' to its prompt to install it fails. anyways... not the point of this ticket.

### Expected Behavior
I would like to change/suppress this message.

### Actual Behavior
This is printed:
![image](https://user-images.githubusercontent.com/577453/134537708-72d96355-8bbd-4d05-a209-90a465f23c4f.png)

### For Bugs; How can we reproduce the behavior?
not a bug.

### For Features; What is the motivation and/or use-case for the feature?

My dev server is running in a plugin of my main service... so the info printed here is confusing to my team... I would like to change the message or hide it. The location and ports are correct for the dev server, but it's behind my app, only the WebSockets are sent to those addresses. (the middleware is added to my express stack)

**Comment by alexander-akait** [comment]
Sorry, out of scope webpack-dev-server, you can suppress them using https://webpack.js.org/configuration/other-options/#level, but if you need real filter, please open an issue in webpack and ask to add `infrastructureLogging.filter` option, we can't do it here

**Comment by jsg2021** [comment]
Oh! I'm sorry. That logging setting looks perfect! thanks!
