### ISSUE TITLE
Why can’t I automatically refresh the html after I modify it

### ISSUE THREAD

**Issue by KK-wang** [webpack/webpack-dev-server#3881]
webpack-dev-server has already been updated, but I ran into some problems.
After configuration, js and css can HMR. But html can't auto-reload.
Here is my code:
![image](https://user-images.githubusercontent.com/59858262/134754702-b71e3c00-e9b4-4346-a793-8f30fffb234d.png)
![image](https://user-images.githubusercontent.com/59858262/134754707-f95109ff-7d50-4362-971a-352c1ec6dbfb.png)
![image](https://user-images.githubusercontent.com/59858262/134754721-cd33b9ae-add5-4fc4-afc4-529211db3da1.png)
****
Here is my directory structure:
![image](https://user-images.githubusercontent.com/59858262/134754747-22de2fa8-2f49-448c-8dbe-14d9d06613ac.png)
**help me plz.**

**Comment by alexander-akait** [comment]
If you want to help please use the issue template, screenshots is not enough to help, sorry, no versions/no examples usage, no configuration, format your issue using the bug template and I will reopen and help you

**Comment by KK-wang** [comment]
> If you want to help please use the issue template, screenshots is not enough to help, sorry, no versions/no examples usage, no configuration, format your issue using the bug template and I will reopen and help you

sorry, this is my first time to create a issue, I will **format** it now.

**Comment by alexander-akait** [comment]
Feel free to ping me when it will be ready

**Comment by KK-wang** [comment]
@alexander-akait Thanks so much for your help. (maybe my format is still **terrible**.

**Comment by alexander-akait** [comment]
@KK-wang Can you create github repo? it will be easier to say what is wrong. And what is meaning `automatically refresh`? Reload page? Note - it is HTML page, HMR is impossible

**Comment by KK-wang** [comment]
@alexander-akait I am sorry to reply you now... well here is my repo:

`https://github.com/KK-wang/tie-project-front`

And "automatically refresh" means reload page when I modify the html code.
(My mother tongue is not English, forgive my poor grammar and expression...)

**Comment by alexander-akait** [comment]
Because you need to be told what to do with changes for `component/navbar/index.html`, you can use `watchFiles: ['src/component/**/*.html']`, duplicate https://github.com/webpack/webpack-dev-server/issues/3794
