### ISSUE TITLE
Server Timeout 

### ISSUE THREAD

**Issue by yjcxy12** [webpack/webpack-dev-server#391]
I was working with video and serve the file from local file system. If the video length is more than 2 minutes, the server gives net::ERR_CONTENT_LENGTH_MISMATCH error.

It was due to express server default timeout is 2 minutes. My temporary solution was to change manually to Server.js -> listeningApp to set timeout to 0.

Is there a better way to solve the problem? If not, is there going to be a configurable option for server timeout in the future?

Thanks

**Comment by sokra** [comment]
a PR for ranges was merged

**Comment by revathskumar** [comment]
@sokra Is this settings available on webpack 1.x?

**Comment by ShadowManu** [comment]
@sokra any reference to the PR? angular/angular-cli seems to have an error about this and I'm searching for information about it.

**Comment by patrick-ivers** [comment]
@sokra Any reference to the PR?

**Comment by mohankumarv2005** [comment]
@yjcxy12, it worked perfectly, thanks!

node_modules\webpack-dev-server\lib\Server.js

this.listeningApp.timeout = 600000; //10 Minutes

**Comment by asfernandes** [comment]
I'm still having a timeout with a reconnect after 2 minutes with webpack-dev-server 2.11.1.

**Comment by catchin** [comment]
I also had the problem of 2 minutes timeout for a proxy request and I could solve the problem with the following webpack-dev-server configuration for http-proxy:

    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        proxyTimeout: 5 * 60 * 1000,
        onProxyReq: (proxyReq, req, res) => req.setTimeout(5 * 60 * 1000)
      }
    }

See [webpack-dev-server](https://webpack.js.org/configuration/dev-server/#devserver-proxy), [http-proxy](https://github.com/chimurai/http-proxy-middleware#options) and [node http api](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_request_settimeout_timeout_callback) documentations.

**Comment by fuadmuhtaz** [comment]
If you want no timeout you can set 0 to proxyTimeout and onProxyReq.

**Comment by ryanhaney** [comment]
I've tried all of these suggestions, no dice. The browser disconnects after 2 minutes. Any other suggestions?

**Comment by abhishekkovuri** [comment]
As I use axios for making api calls. so eventually i was trying to set timeout there.
I was also in a assumption that setting a time out there would work but it was not working tried number of ways.
Finally i have created a html and tried axios there then i realised that i need to make changes in my webpack.
adding proxyTimeout would solve the issue
  proxy: {
            '/api/**': {
                target: 'http//localhost:8888/',
                proxyTimeout: 10 * 60 * 1000,
                onProxyReq: (proxyReq, req, res) => req.setTimeout(10 * 60 * 1000),
                changeOrigin: true
            }
        },
