### ISSUE TITLE
makeAssimilatePrototype invokes getters when copying methods

### ISSUE THREAD

**Issue by BorelTung** [webpack/webpack-dev-server#393]
I meet the same problem when using `webpack-dev-server`. Please take a look at it.
[ISSUE](https://github.com/gaearon/react-hot-loader/issues/131)

**Comment by sokra** [comment]
Closing because this is not related to webpack-dev-server, but to webpack instead.

> Note: I'm cleaning up the issues list. For questions please use [stackoverflow](http://stackoverflow.com/tags/webpack), or for issues file them on the [webpack](https://github.com/webpack/webpack) repository
