### ISSUE TITLE
liveReload bug?

### ISSUE THREAD

**Issue by robatrain** [webpack/webpack-dev-server#3946]
- [X] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```
const path = require('path')
// const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    mode: 'development',
    entry: {
        index: '/src/index.js',
        print: './src/print.js',
    },
    devtool: 'inline-source-map',
    devServer: {
        static: './public',
    },
    // plugins: [
    //     new HtmlWebpackPlugin({
    //         title: 'Development',
    //     }),
    // ],
    output: {
        filename: '[name].bundle.js',
        path: path.join(__dirname, 'public', 'dist'),
        clean: true,
    },
}
```js
// additional code, remove if not needed.
```
**index.js**

import _ from 'lodash'
import printMe from './print'

function component() {
    const element = document.createElement('div')
    const btn = document.createElement('button')

    element.innerHTML = _.join(['Hello', 'webpack'], ' ')
    element.classList.add('hello')

    btn.innerHTML = 'Click me and check the console!'
    btn.onclick = printMe

    element.appendChild(btn)

    // const btn1 = document.createElement('button')
    // btn1.innerHTML = 'Click me too and check the console!'
    // btn1.onclick = printMe
    // element.appendChild(btn1)

    return element
}

document.body.appendChild(component())

---------------------------

**print.js**
export default function printMe() {
    console.log('I get called from print.js!');
}

---------------------------

**package.json**
{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack serve --open",
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "html-webpack-plugin": "^5.3.2",
    "webpack": "^5.58.1",
    "webpack-cli": "^4.9.0",
    "webpack-dev-server": "^4.3.1"
  },
  "dependencies": {
    "lodash": "^4.17.21"
  }
}

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 46.13 GB / 64.00 GB
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 93.0
    Safari: 15.0
  Packages:
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    webpack: ^5.58.1 => 5.58.1 
    webpack-cli: ^4.9.0 => 4.9.0 
    webpack-dev-server: ^4.3.1 => 4.3.1 
### Expected Behavior
Expect hot reload to add a second button.
### Actual Behavior
No reload and receive error in browser console (Firefox): 
Uncaught TypeError: currentUpdate is undefined. jspon chunk loading:44
### For Bugs; How can we reproduce the behavior?
My file structure is *slightly* different than the webpack documents; otherwise it is the exact same code. The dist folder lives in public, index.html lives in public, and public gets served by webpack-dev-server. I was having reload problems with my main program and decided to walk through the guide again to see if I could figure out why and stumbled across this. 

To reproduce:
1. Build with webpack (I use npm run build which just runs webpack)
2. Start server (I use npm start which runs webpack server --open)
3. Uncomment btn1 in index.js and save.

Unless I've missed a currentUpdate in my own programming (for which I'm sorry for wasting your time) I believe webpack/webpack-dev-server is throwing the error.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-dev-server/issues/2792, please use `runtimeChunk: single`
