### ISSUE TITLE
fix: `Protocol error (Network.setUserAgentOverride): Target closed.` in CI

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-dev-server#3964]
### Bug report
CI experiencing this error randomly, Race conditions. Needs to be fixed. 

### Actual Behavior
CI fails due to this sometimes.

### Expected Behavior
CI does not fail on this error.

### How Do We Reproduce?
Randomly occurs on CI. Race condition between processes.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
N/A

**Comment by alexander-akait** [comment]
We already investigate in this, it starts happens after update puppeteer, I think it is regression on their side

**Comment by snitin315** [comment]
> We already investigate in this, it starts happens after update puppeteer, I think it is regression on their side

Could be possible. We can try downgrading puppeteer.
