### ISSUE TITLE
Can webpack dev server support proxy config reload without server restart in webpack.config.js?

### ISSUE THREAD

**Issue by wood3n** [webpack/webpack-dev-server#3996]
My project requires frequent changes to the `proxy` configuration items, after change them, i need to restart the application, can this support proxy config reload without restart?
```js
module.exports = {
  //...
  devServer: {
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        pathRewrite: { '^/api': '' },
      },
    },
  },
};
```

**Comment by alexander-akait** [comment]
Yes, you need to restart, like you change nginx/apache configurations
