### ISSUE TITLE
Alternative isAbsoluteURL solution

### ISSUE THREAD

**Issue by jimmywarting** [webpack/webpack-dev-server#4037]
https://github.com/webpack/webpack-dev-server/blob/497e615f24d5a16266f0faa8db1063f1b0ec2b82/lib/Server.js#L53-L62
```js
 static isAbsoluteURL(url) { 
   try { return new URL(url), true } catch(e) {}
   return false
 } 
```
then you can use both a URL class and a strings and weird domain names that are very special

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
```
 static isAbsoluteURL(url) { 
   try { new URL(url) } catch(e) { return false }
   return true
 } 
```

Will be better to read

**Comment by jimmywarting** [comment]
how about the c:\ ?

 static isAbsoluteURL(url) { 
   try { url = new URL(url) } catch(e) { return false }
   return url.protocol !== 'c:'
 }

**Comment by alexander-akait** [comment]
I think we don't use it for paths, so fine to avoid it

**Comment by alexander-akait** [comment]
Closed due https://github.com/webpack/webpack-dev-server/pull/4038
