### ISSUE TITLE
Just a typo in Support section of Readme.md . 

### ISSUE THREAD

**Issue by niharikamahajan02** [webpack/webpack-dev-server#4041]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Your Proposal for Changes
In first line it's written "We do our best to keep Issues in the ......"
Replacing I in Issues with i is a better option

**Comment by niharikamahajan02** [comment]
Should I make a pull request for this issue?

**Comment by alexander-akait** [comment]
No need to open an issue, just send a PR

**Comment by niharikamahajan02** [comment]
Yup , had send a PR but a comment pointed that "My commit is not authorized under a signed CLA."
Since I am contributing to webpack first time , so can you tell , do I need to authorize myself under this CLA for further PR to be merged?

**Comment by alexander-akait** [comment]
Already fixed https://github.com/webpack/webpack-dev-server/pull/4042#issuecomment-974132027

**Comment by snitin315** [comment]
> Since I am contributing to webpack first time , so can you tell , do I need to authorize myself under this CLA for further PR to be merged?

Yes, you need to sign CLA so that we can accept your contributions.

**Comment by niharikamahajan02** [comment]
> > Since I am contributing to webpack first time , so can you tell , do I need to authorize myself under this CLA for further PR to be merged?
> 
> Yes, you need to sign CLA so that we can accept your contributions.

Okkk , thanks!
