### ISSUE TITLE
V5 - allowedHosts suddenly stopped working

### ISSUE THREAD

**Issue by zachsa** [webpack/webpack-dev-server#4049]
Hi,

I have a dev server config that looks like this:

```
host: 'localhost',
open: ['http://localhost:3001'],
allowedHosts: ['.localhost, localhost'],
static: {
  staticOptions: {
    contentBase: path.join(ROOT, output),
  },
},
...
```

This worked on `webpack v5.61.0`. But updating to `webpack v5.64.2`, when I try to access 'test.localhost' I suddently get "Invalid Host header" as a response. I can still use `allowedHosts: 'all'`. But `allowedHosts: 'auto'` also doesn't work.

**Comment by alexander-akait** [comment]
We don't change this logic in webpack (this logic not in webpack), please use the issue template and I will help
