### ISSUE TITLE
After upgrading to Webpack v5.64.2, The `allowedHosts` functionality seems to be broken

### ISSUE THREAD

**Issue by zachsa** [webpack/webpack-dev-server#4050]
### Bug report
After upgrading to Webpack v5.64.2, The `allowedHosts` functionality seems to be broken

### Actual Behavior
With a Webpack dev server configuration like this:

```
host: 'localhost',
open: ['http://localhost:3001'],
allowedHosts: ['.localhost, localhost'],
static: {
  staticOptions: {
    contentBase: path.join(ROOT, output),
  },
},
...
```

Going to `test.localhost:3001` gives me an "Invalid Host Header" response. Changing to `allowedHosts: 'auto` also doesn't work. Changing to `allowedHosts: 'all'` DOES work (but this is explicitly recommended against in the docs).

This previously did not occur in webpack v5.61.0

### Expected Behavior
I did not expect the `allowedHosts` functionality to change when I updated Webpack

### How Do We Reproduce?
(Please let me know if I should include the webpack configuration, and I will)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz
    Memory: 1.70 GB / 9.73 GB
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Packages:
    babel-loader: ^8.2.3 => 8.2.3 
    copy-webpack-plugin: ^10.0.0 => 10.0.0 
    css-loader: ^6.5.1 => 6.5.1 
    file-loader: ^6.2.0 => 6.2.0 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    sass-loader: ^12.3.0 => 12.3.0 
    style-loader: ^3.3.1 => 3.3.1 
    url-loader: ^4.1.1 => 4.1.1 
    webpack: ^5.64.2 => 5.64.2 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-dev-server: ^4.5.0 => 4.5.0 
```

**Comment by zachsa** [comment]
From https://github.com/webpack/webpack-dev-server/issues/4049

**Comment by alexander-akait** [comment]
```
static: {
  staticOptions: {
    contentBase: path.join(ROOT, output),
  },
},
```

is not valid setup, please look at docs how to setup it

Also - we don't change this logic a long time, please create reproducible test repo

**Comment by zachsa** [comment]
okay - thank you for pointing out that staticOptions isn't correct (I seem to recall having to change to this structure for Webpack 5 but probably just made a mistake somewhere). I'm not sure why the allowedHosts configuration stopped working then.

**Comment by alexander-akait** [comment]
What is the error message? What is stoped?

**Comment by zachsa** [comment]
As I mentioned - after updating webpack this morning, going to `test.localhost:3001` resulted in an error message: "Invalid Host Header". That is with `allowedHosts: ['.localhost, localhost'],`

When I change that to `allowedHosts: 'all',`, then I can go to `test.localhost:3001`. I don't know why this is the case. But I'm happy, for now to just continue. Sorry that I can't be more helpful - and I also can't be sure that this isn't my own error.

If no code has been changed in webpack dev server that might result in this error, then I don't know what the problem is. 

(I should mention that I'm working in a WSL environment)

**Comment by alexander-akait** [comment]
hm weird, it should work https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L2035, maybe you can provide reproducible example, no need to show projects, just example of the problem
