### ISSUE TITLE
Do not hardcode output path using *nix separator; use path.sep variable

### ISSUE THREAD

**Issue by gajus** [webpack/webpack-dev-server#406]
Example of where it is hardcoded:

* https://github.com/webpack/webpack-dev-server/blob/3dd3e2abfe2f914764a7e89bda5b7bee9f31bd84/bin/webpack-dev-server.js#L138
* https://github.com/webpack/webpack-dev-server/blob/3dd3e2abfe2f914764a7e89bda5b7bee9f31bd84/bin/webpack-dev-server.js#L142

Use https://nodejs.org/api/path.html#path_path_sep

**Comment by gajus** [comment]
@sokra I will happily raise a PR if this is accepted.

**Comment by sokra** [comment]
It's the path in the in-memory filesystem, not on the real fs. So it's fine to use *nix paths here.

**Comment by SpaceK33z** [comment]
@gajus, is there something not working because of this?

**Comment by SpaceK33z** [comment]
ping @gajus

**Comment by gajus** [comment]
> @gajus, is there something not working because of this?

It was something to do with https://github.com/gajus/write-file-webpack-plugin. However, there are no open issues & I cannot recall what was the problem.

Closing it. Will re-open if I remember the issue.

**Comment by gajus** [comment]
Just noticed that there is an associated PR.

https://github.com/gajus/write-file-webpack-plugin/pull/18

Seems like we have solved it by hardcoding the path too.

**Comment by SpaceK33z** [comment]
Ah okay. Note that `output.path = '/'` in the webpack-dev-server CLI was removed in the latest beta (see also #337, but you probably already know that haha), so that is probably not necessary anymore.
