### ISSUE TITLE
What is the sense in sockjs?

### ISSUE THREAD

**Issue by zdm** [webpack/webpack-dev-server#4066]
### Modification Proposal

Why `sockjs` is provided as alternative transport to the `ws`. As I know, `sockjs` is also websockets based.
What is the sense to keep two parts of the similar functionality?

**Comment by alexander-akait** [comment]
Because some developers still need old browsers support

**Comment by zdm** [comment]
Without websockets? Sockjs will not work on that browsers.

**Comment by alexander-akait** [comment]
IE10, IE11 support and some other legacy playrooms

**Comment by zdm** [comment]
https://caniuse.com/websockets

ie since v10
ff since v4
etc..

are you sure, that somebody still have this browsers (they are not support javascript ;-)) )?

**Comment by alexander-akait** [comment]
Here list of supported browsers https://github.com/sockjs/sockjs-client#supported-transports-by-browser-html-served-from-http-or-https, IE 10 starts support it not with first versions, but it was implemented a long time ago

**Comment by alexander-akait** [comment]
Also please note - not all browsers supports specification and can work with bugs, sockjs uses other transport to fix it, anyway `websocket` used by default, so just don't enable it

**Comment by zdm** [comment]
I see here https://github.com/webpack/webpack-dev-server/issues/3862 that you dropped ie11 support.
Less outdated items - less problems. People should move forward.
I understand you, thanks.

**Comment by alexander-akait** [comment]
It will be only for the next major release, but not right now

**Comment by alexander-akait** [comment]
Let's close, it will be removed in the next major release
