### ISSUE TITLE
Is 2.0.0-beta supposed to support hot reloading?

### ISSUE THREAD

**Issue by aaugustin** [webpack/webpack-dev-server#407]
I just tried upgrading a project to webpack 2.0.0-beta7.

I installled webpack-dev-server 2.0.0-beta.

I'm running it with:

    webpack-dev-server --config path/to/webpack.dev.js --inline --hot

Whenever I modify source file and hot reloading triggers, I see an error in the console, for example:

    Uncaught (in promise) SyntaxError: Unexpected identifier(…)
    (anonymous function) @ 4.cedcfaeaa4ac935bf478.js:2047
    __webpack_require__ @ website.cedcfaeaa4ac935bf478.js:556
    fn @ website.cedcfaeaa4ac935bf478.js:98
    (anonymous function) @ router.jsx?9e14:2
    (anonymous function) @ 4.cedcfaeaa4ac935bf478.js:296
    __webpack_require__ @ website.cedcfaeaa4ac935bf478.js:556
    fn @ website.cedcfaeaa4ac935bf478.js:98'

After restarting `webpack-dev-server`, the page loads fine.

I'm pretty sure this bug report doesn't contain enough information to be actionable, but I have no idea how to investigate this :-/

**Comment by lemieux** [comment]
Pretty sure it's related to webpack 2.0 and not to webpack-dev-server because it's happening to me on webpack-dev-server 1.14.1 with webpack 2.0-beta4. I'll try to downgrade to webpack 1 .

**Comment by aaugustin** [comment]
You're probably right.

In my project, this doesn't seem to happen anymore with webpack 2.1.0 beta.
