### ISSUE TITLE
TypeError: fsevents.watch is not a function

### ISSUE THREAD

**Issue by DerekSeverson** [webpack/webpack-dev-server#4070]
### Bug report

`webpack-dev-server` crashes due to a `TypeError: fsevents.watch is not a function` exception being thrown.  Below is the output: 

```
> webpack serve --open

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.21.3.127:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from './dist' directory
/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:93
  const stop = fsevents.watch(path, callback);
                        ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:149:16)
    at FsEventsHandler._watchWithFsEvents (/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:351:18)
    at FsEventsHandler.initWatch (/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:427:23)
    at FsEventsHandler._addToFsEvents (/Users/Severson/Projects/react-essentials-with-luna/node_modules/chokidar/lib/fsevents-handler.js:516:12)
```

### Actual Behavior

Crashes upon running `webpack serve --open` due to the exception posted above. 

### Expected Behavior

`webpack serve --open` should be run without throwing said exception.  

### How Do We Reproduce?

My setup was working when running Node.js v12, but when I upgraded to Node.js v16.13, I'm receive the exception up above.  FYI - I did start with a clean `node_modules` and `package-lock.json` after upgrading (aka: I deleted both, and recreated them via `npm i`). 

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
❯ npx webpack-cli info

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 776.18 MB / 32.00 GB
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Edge: 96.0.1054.34
    Safari: 15.1
  Packages:
    babel-loader: 8.2.3 => 8.2.3 
    css-loader: 6.5.1 => 6.5.1 
    html-webpack-plugin: 5.5.0 => 5.5.0 
    postcss-loader: 6.2.1 => 6.2.1 
    react-hot-loader: 4.13.0 => 4.13.0 
    sass-loader: 12.3.0 => 12.3.0 
    style-loader: 3.3.1 => 3.3.1 
    webpack: 5.64.4 => 5.64.4 
    webpack-cli: 4.9.1 => 4.9.1 
    webpack-dev-server: 4.6.0 => 4.6.0 
```

Webpack Configration
```
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
  mode: 'development',
  entry: {
    app: './src/index.jsx'
  },
  devtool: 'source-map',
  devServer: {
    static: './dist'
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    clean: true
  },
  module: {
    rules: [{
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader'
      }
    }, {
      test: /\.(css|scss)$/,
      exclude: /node_modules/,
      use: [
        // 'style-loader',
        MiniCssExtractPlugin.loader,
        'css-loader',
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              ident: 'postcss',
              plugins: [
                require('autoprefixer')()
              ]
            }
          }
        },
        'sass-loader'
      ]
    }]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'styles/[name].css'
    }),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, './src/index.html'),
      filename: 'index.html',
      inject: 'body'
    })
  ],
  resolve: {
    extensions: ['.js', '.jsx']
  }
}

```

**Comment by alexander-akait** [comment]
Please open an issue in `chokidar` (look at stack trace), something wrong with your environment due `macOS`, also try to reinstall deps (also look at package manager output), sorry, we can't fix it here

**Comment by alexander-akait** [comment]
> when I upgraded to Node.js v16.13

Reinstall deps, because `fsevents-handler` is platform and Node.js versions have different API

**Comment by DerekSeverson** [comment]
> FYI - I did start with a clean node_modules and package-lock.json after upgrading (aka: I deleted both, and recreated them via npm i).

**Comment by alexander-akait** [comment]
In this case please open an issue in `chokidar`, we can't fix it here, sorry

**Comment by DerekSeverson** [comment]
Would you be able to point me to where `webpack-dev-server` is using `chokidar`?  I pin point exactly where its being used or configured when searching within this repository.  It would help me write out the issue.

**Comment by alexander-akait** [comment]
Nothing special https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L2233

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/152913685-8b3fe2b3-011c-4225-9929-2a912720f27f.png)

**Comment by yoyo837** [comment]
ref https://github.com/npm/cli/issues/3846

**Comment by wkeese** [comment]
Bug against chokidar was paulmillr/chokidar/issues/1180, solved by updating webpack and webpack-dev-server.  I would guess that indirectly updated chokidar.

**Comment by jauntyjocularjay** [comment]
> webpack and webpack-dev-server

ran,

```npm update webpack && npm update webpack-dev-server```

This worked for me. I ran into this via vite.

Mac OSX 15.2

**Comment by javier-lunaWGU** [comment]
I had the same issue on Mac, I uninstalled webpack & webpack-cli and installed them again

**Comment by baron04** [comment]
I tried to delete package-lock.json file and node_modules folder, then reinstall dependencies. It worked for me.
