### ISSUE TITLE
version>=4.0 throw Error SCRIPT1014: Invalid character error  in ie11

### ISSUE THREAD

**Issue by xxxace** [webpack/webpack-dev-server#4072]
### Bug report
if version is less than 4.0.0 is normal
i found the error that may be  caused by html-entities ^2.3.2
  "devDependencies": {
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.4",
        "babel-loader": "^8.2.3",
        "clean-webpack-plugin": "^4.0.0",
        "core-js": "^3.19.2",
        "html-webpack-plugin": "^5.5.0",
        "ts-loader": "^9.2.6",
        "typescript": "^4.5.2",
        "webpack": "^5.64.4",
        "webpack-cli": "^4.9.1",
        "webpack-dev-server": "4.6.0"
    }
### Actual Behavior
 SCRIPT1014: Invalid character error
![cfdbcce954bddb25c572610b047f0fc](https://user-images.githubusercontent.com/60084325/144572990-3fcaebe3-970e-45fb-b1c0-5f371a85aac0.png)

### Expected Behavior
normal

**Comment by snitin315** [comment]
Please follow the issue template and provide the steps to reproduce.
