### ISSUE TITLE
version>=4.0 throw Error SCRIPT1014: Invalid character error in ie11

### ISSUE THREAD

**Issue by xxxace** [webpack/webpack-dev-server#4075]
### Bug report
if version is less than 4.0.0 is normal
i found the error that may be caused by html-entities ^2.3.2

### Actual Behavior
SCRIPT1014: Invalid character error in ie11

### Expected Behavior
normal to use in ie11
### How Do We Reproduce?
package.json:
```
    "devDependencies": {
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.4",
        "babel-loader": "^8.2.3",
        "clean-webpack-plugin": "^4.0.0",
        "core-js": "^3.19.2",
        "html-webpack-plugin": "^5.5.0",
        "ts-loader": "^9.2.6",
        "typescript": "^4.5.2",
        "webpack": "^5.64.4",
        "webpack-cli": "^4.9.1",
        "webpack-dev-server": "3.11.0"
    }
```
webpack.config.js:
```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");

const config = {
    mode: "production",
    entry: "./src/index.ts",
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: "bundle.js",
        environment: {
            arrowFunction: false
        }
    },
    module: {
        rules: [{
            test: /\.ts$/,
            use: [{
                loader: "babel-loader",
                options: {
                    presets: [
                        ["@babel/env", {
                            targets: {
                                ie: "11"
                            },
                            corejs: "3",
                            useBuiltIns: "usage"
                        }]
                    ]
                }
            }, "ts-loader"],
            exclude: /node_modules/
        }]
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: "ace-world",
            favicon: "./public/favorite.ico",
            template: "./public/index.html"
        }),
        new CleanWebpackPlugin()
    ],
    resolve: {
        extensions: [".js", ".ts"]
    },
    devServer: {
        port: 8089,
        compress: true,
    }
}

module.exports = config
```
```
 System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 8.40 GB / 15.95 GB
  Binaries:
    Node: 14.15.1 - D:\app\node\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - D:\app\node\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.18362.1533.0)
    Internet Explorer: 11.0.18362.1
  Packages:
    babel-loader: ^8.2.3 => 8.2.3
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    html-webpack-plugin: ^5.5.0 => 5.5.0
    ts-loader: ^9.2.6 => 9.2.6
    webpack: ^5.64.4 => 5.64.4
    webpack-cli: ^4.9.1 => 4.9.1
    webpack-dev-server: 3.11.0 => 3.11.0
```

**Comment by snitin315** [comment]
Please share a repo reproducing this issue.

**Comment by xxxace** [comment]
> Please share a repo reproducing this issue.

https://github.com/xxxace/ts-demo.git

**Comment by snitin315** [comment]
Thanks, we will look into it soon.

**Comment by xxxace** [comment]
> Thanks, we will look into it soon.

i already resolve it with the include: /html-entities/  .........

**Comment by xxxace** [comment]
{
            test: /\.js$/,
            use: [{
                loader: "babel-loader",
                options: {
                    presets: [
                        ["@babel/env", {
                            targets: {ie: "11"},
                            corejs: "3",
                            useBuiltIns: "usage"
                        }]
                    ]
                }
            }],
            include: /html-entities/,
            exclude: /node_modules/
        }

**Comment by alexander-akait** [comment]
Please update `webpack-dev-server` to v4, v3 accepts only security fixes, yes, there is can be problem with IE, based on your configuration, you can remove `compress: true`, because it is by default and no more changes, feel free to feedback

**Comment by xxxace** [comment]
> Please update `webpack-dev-server` to v4, v3 accepts only security fixes, yes, there is can be problem with IE, based on your configuration, you can remove `compress: true`, because it is by default and no more changes, feel free to feedback

Sorry. did you check the reproduction? in this issues i paste the local package.json. and the v3 is ok with ie11.

**Comment by xxxace** [comment]
@alexander-akait  Sorry. did you check the reproduction? in this issue i'm paste the local package.json with v3.but actually i'm used the v4.6 and v3 is ok with ie11.

**Comment by alexander-akait** [comment]
Note:
```
environment: {
  arrowFunction: false
}
```

is not help to ie11, please set `browserslist`, not only arrow functions generated by webpack v6, if you don't have browsers, you can set `target: ['web', 'es5']`

**Comment by alexander-akait** [comment]
You have `const` in you code, in future you can check code using `es-check`, set:
```
devtool: false,
optimization: {
        minimize: false
},
```

And look at code or run `es-check`

**Comment by alexander-akait** [comment]
How to fix? Create file `.browserslistrc` and put:
```
defaults
IE 11
```

Note - ideally you should set minimum version of browsers, `defaults` is not good choose

**Comment by xxxace** [comment]
@alexander-akait  thank you so much! the `.browserslistrc` file is efficient way to fix that problem
