### ISSUE TITLE
devServer.overlay: false with  webpack-dev-server 3.11.2 is inneficient

### ISSUE THREAD

**Issue by kopax-polyconseil** [webpack/webpack-dev-server#4111]
### Bug report

 `devServer.overlay: false` does show overlay in development

I think I am hitting the bug with create-react-app and not webpack-dev-server, as explained here: https://github.com/facebook/create-react-app/issues/4685

### Actual Behavior

It should not open overlay in development.

## Reproduction

`serverConfig` [here](https://github.com/pass-culture/pass-culture-app-native/blob/master/web/scripts/start.js#L89) is configured with `overlay: false`, this is the configuration passed to `webpack-dev-server@3.11.2`:

```
{
  disableHostCheck: true,
  compress: true,
  clientLogLevel: 'none',
  contentBase: '/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/public',
  contentBasePublicPath: '/',
  watchContentBase: true,
  hot: true,
  transportMode: 'ws',
  injectClient: false,
  sockHost: undefined,
  sockPath: undefined,
  sockPort: undefined,
  publicPath: '',
  quiet: true,
  watchOptions: {
    ignored: /^(?!\/home\/dka\/workspace\/github\.com\/pass\-culture\/pass\-culture\-app\-native\/src\/).+\/node_modules\//g
  },
  https: false,
  host: '0.0.0.0',
  overlay: false,
  historyApiFallback: { disableDotRule: true, index: '/' },
  public: '192.168.1.102',
  proxy: {
    '/native': {
      target: 'https://backend.testing.passculture.team',
      changeOrigin: true
    },
    '/saml': {
      target: 'https://backend.testing.passculture.team',
      changeOrigin: true
    }
  },
  before: [Function: before],
  after: [Function: after]
}
```

### Expected Behavior

It should disable the overlay as explained [here](https://webpack.js.org/configuration/dev-server/) and [here](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md)

Seems related to https://github.com/electron-userland/electron-forge/issues/2413

Perhaps it is also this bug : https://github.com/facebook/create-react-app/issues/4685

**Comment by alexander-akait** [comment]
Sorry v3 is not supported anymore and can contains bugs and security problems, please consider to update to v4, it is fixed in v4, sorry, v3 accept only security fixes
