### ISSUE TITLE
Can't disable or custom console output

### ISSUE THREAD

**Issue by flute** [webpack/webpack-dev-server#4123]
### Bug report

webpack-dev-server console output can't disabled or customed. I can't find anyway todo this on document.

![image](https://user-images.githubusercontent.com/5842406/146734584-dd7b2584-7425-4695-94a6-2146e7c41801.png)

### Actual Behavior

Just can't do anything with output on console

### Expected Behavior

Console output should be configable, can be disabled or customed.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 39.38 MB / 16.00 GB
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
  Packages:
    babel-loader: ^8.2.2 => 8.2.3
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    css-loader: ^5.0.1 => 5.2.7
    eslint-webpack-plugin: ^3.1.0 => 3.1.1
    file-loader: ^6.2.0 => 6.2.0
    html-webpack-plugin: ^5.3.1 => 5.5.0
    less-loader: ^8.1.1 => 8.1.1
    postcss-loader: ^6.1.1 => 6.2.1
    style-loader: ^3.3.0 => 3.3.1
    url-loader: ^4.1.1 => 4.1.1
    webpack: ^5.59.0 => 5.65.0
    webpack-cli: ^4.9.1 => 4.9.1
    webpack-dev-server: ^4.3.1 => 4.6.0
    webpack-merge: ^5.8.0 => 5.8.0
    webpackbar: ^5.0.0-3 => 5.0.2
```

**Comment by alexander-akait** [comment]
Please use https://webpack.js.org/configuration/other-options/#infrastructurelogging to setup it
