### ISSUE TITLE
options has an unknown property 'disableHostCheck'.

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [webpack/webpack-dev-server#4142]
### Bug report

![image](https://user-images.githubusercontent.com/32830366/147625872-03b07626-5b24-486e-a91e-1f9b18cdaff7.png)

### Actual Behavior

```
  devServer: {
    port: 3001,
    disableHostCheck: true,
    headers:{'Access-Control-Allow-Origin':'*'}
  },
```

![image](https://user-images.githubusercontent.com/32830366/147625889-c3f334c1-4b01-4ec4-9da1-87e75ed5f2fb.png)

### Expected Behavior

don't have error

### How Do We Reproduce?

    "webpack": "5.65.0",
    "webpack-cli": "4.9.1",
    "webpack-dev-server": "4.7.1"

**Comment by godky** [comment]
The `disableHostCheck` option was removed in favor `allowedHosts: 'all'` in webpack-dev-server@4

v3:
```
module.exports = {
  devServer: {
    disableHostCheck: true,
  },
};
```
v4:
```
module.exports = {
  devServer: {
    allowedHosts: "all",
  },
};
```

**Comment by zjjjjjjjjjjd** [comment]
> The `disableHostCheck` option was removed in favor `allowedHosts: 'all'` in webpack-dev-server@4
> 
> v3:
> 
> ```
> module.exports = {
>   devServer: {
>     disableHostCheck: true,
>   },
> };
> ```
> 
> v4:
> 
> ```
> module.exports = {
>   devServer: {
>     allowedHosts: "all",
>   },
> };
> ```

thanks
