### ISSUE TITLE
Add an option to abort on compilation failure

### ISSUE THREAD

**Issue by marekdedic** [webpack/webpack-dev-server#4155]
### Feature Proposal

Hi, I'd like there to be an option to abort the dev-server if compilation fails. I found no way to do this...

### Feature Use Case

I am using `webpack-dev-server` for my tests through `start-server-and-test`. If it happens that somebody somehow commits a change that causes the app to no longer build, the dev server simply says `webpack 5.65.0 compiled with 1 error in 406 ms`, however, it continues to run and my tests fail one by one over something like 10 minutes (due to timeouts in tests...).

So I'd like there to be an option to just abort the server if it fails to compile - that way, the test would fail much faster instead of trying to reach a broken server for 10 minutes.

```sh
$ npx webpack-cli info

  System:
    OS: Linux 5.15 Debian GNU/Linux bookworm/sid
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.58 GB / 15.38 GB
  Binaries:
    Node: 14.18.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Firefox: 95.0.1
  Packages:
    @jsdevtools/coverage-istanbul-loader:  3.0.5
    css-loader: ^6.5.1 => 6.5.1
    gas-webpack-plugin: ^2.1.0 => 2.1.0
    html-webpack-plugin: ^5.5.0 => 5.5.0
    sass-loader: ^12.4.0 => 12.4.0
    style-loader: ^3.3.1 => 3.3.1
    svelte-loader: ^3.0.0 => 3.1.2
    ts-loader: ^9.2.6 => 9.2.6
    webpack: ^5.65.0 => 5.65.0
    webpack-cli: ^4.9.1 => 4.9.1
    webpack-dev-server: ^4.7.1 => 4.7.1
    webpack-stream: ^7.0.0 => 7.0.0
  Global Packages:
    webpack-cli: 4.9.1
    webpack: 5.65.0
```

**Comment by alexander-akait** [comment]
Sorry out of scope webpack-dev-server, you can solve this on your test code side, just close server if something was failed

**Comment by marekdedic** [comment]
Hi,
thanks for the reply. Could you please explain why this is out-of-scope? I would think this would be the most appropriate repo for this request...

Also, I could close the server if something failed... If I had a way to detect that - but the cli returns no error code on failure...

Thanks

**Comment by alexander-akait** [comment]
> Could you please explain why this is out-of-scope?

Because it is exotic usage for tests, it is not commonly used, we have API to solve this, so please use API.

> If I had a way to detect that - but the cli returns no error code on failure...

Why you use `CLI` for tests, webpack has Node.js API, so I recommend to use it for tests, anyway you can configure `stats` to output all errors/warnings and parse them from `stderr`

**Comment by alexander-akait** [comment]
If you don't need errors/warnings text, you can parse `webpack 5.65.0 compiled with 1 error` using RegExp and close CLI process when you need it
