### ISSUE TITLE
HTTP OPTIONS requests fail with a 404 response

### ISSUE THREAD

**Issue by donaldmcn** [webpack/webpack-dev-server#4159]
### Bug report

When using webpack-dev-server to serve content on local host, and OPTIONS HTTP request for any of the served content fails with a 404 response. This prevents CORS preflight requests from a browser from working, for example.

In version 3.11.3, the same request would work correctly, and return a 200 OK. Starting in version 4.5.0 OPTIONS requests fail with a 404.

### Actual Behavior

An OPTIONS request for any hosted content returns a 404 response

### Expected Behavior

An OPTIONS request should return a 200 response

### How Do We Reproduce?

Using the following webpack config:
`const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },

  devServer: {
      client: {
          logging: 'verbose'
      },
      static: {
          directory: path.join(__dirname, 'public'),
      },
      compress: true,
      port: 9000,
      magicHtml: false,
      devMiddleware: {
          methods: ['GET', 'HEAD', 'OPTIONS']
      }
  }
};
`
And the following package.json
`{
  "name": "webpack-cors-test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "start": "webpack serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.65.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.5.0"
  },
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
`
Add/have a public folder in your project with some static content, for example the logo from a default create react app project.
\public\logo192.png

Start webpack dev server: npm run start

Try sending: OPTIONS http://localhost:9000/logo192.png

The response will be a 404.

Setting the webpack-dev-server to version 3.11.3, and updating the webpack.config.js file to have the old settings format:
`  devServer: {
      contentBase: path.join(__dirname, 'public'),
      compress: true,
      port: 9000
  }
`
will result in the same request returning a 200 response.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

asset main.js 554 KiB [emitted] (name: main)
runtime modules 1.25 KiB 6 modules
cacheable modules 532 KiB
  ./src/index.js 274 bytes [built] [code generated]
  ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
webpack 5.65.0 compiled successfully in 392 ms

**Comment by alexander-akait** [comment]
Sorry, I'm afraid this is not entirely true due https://github.com/expressjs/serve-static/blob/master/index.js#L73, `serve-static` (used for `static`) supports only `GET` and `HEAD` methods, I don't know how you got `200`, If you need answer, please create reproducible example with old configuration and I will investigate, perhaps you have additional middlewares, using our configuration with 3 version have the same `404`

**Comment by donaldmcn** [comment]
Here is a webpack.config.js and package.json that works with an OPTIONS request (200 OK response)

webpack.config.js
`const path = require('path');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },

  devServer: {
      contentBase: path.join(__dirname, 'public'),
      compress: true,
      port: 9000
  }
};
`

And Package.json
`
{
  "name": "webpack-cors-test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "start": "webpack serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.65.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^3.11.3"
  },
  "dependencies": {
    "lodash": "^4.17.21"
  }
}
`

The rest of the project is the same as the above repro case when using webpack-dev-server version 4.5.0 and above.

The project structure is basically:

root
   public
      index.html
      logo192.png
   src
      index.js
   package.json
   webpack.cofig.js


I can zip up the project and share it if that helps.

**Comment by alexander-akait** [comment]
Please use github for this, it is better

**Comment by donaldmcn** [comment]
Here is a github repo that will reproduce the issue

It has both webpack configs to show OPTIONS works with webpack-dev-server 3.11.3, and does not work with 4.5.0

https://github.com/donaldmcn/webpack-cors-test

**Comment by alexander-akait** [comment]
I see, there is the problem https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L3032, now we handle only `GET` and `HEAD` requests, we want to remove this options because it is very bad for performance, why you need this, can you describe? Maybe better to create own middleware (we support `setupMiddlewares`, so you can integrate any logic)?

**Comment by donaldmcn** [comment]
OPTIONS is used by browsers for CORS preflight requests for content such as images. We are developing a web app that has multiple independent parts, which we serve from different localhost ports for development and testing.

Without support for OPTIONS working none of the content that requires a preflight check will work.

Also, in the repro case when using web-pack-devsever 4.5.0, I have set magicHtml to false in the webpack config. Based on what I see, that should skip that check at server.js line 3032.

**Comment by alexander-akait** [comment]
I mean you relied on an option that was actually design for a completely different purpose, and yes we are going to remove this option in the future, and so it has some changes in v4, I recommend to create own middleware for this feature

**Comment by donaldmcn** [comment]
Modern browsers use HTTP OPTIONS for CORS preflight, and web-pack-devserver supported this up until version 4.5.0.

For now, I will just use webpack-dev-server 3.11.3 and consider creating a new middleware in the future if needed.

**Comment by donaldmcn** [comment]
FYI, for my purposes of needing to just support CORS preflight requests, adding the following to the setupMiddlewares section of the webpack-dev-server makes things work:

           // Allow OPTIONS requests (i.e. CORS preflight)
           middlewares.push({
                name: 'cors-preflight',
                path: '/images',
                middleware: (req, res) => {
                    res.send('GET, HEAD');
                },
            });
