### ISSUE TITLE
Upstream Prototype Pollution vulnerability from selfsigned 1.10.11 -> node-forge 0.10.0

### ISSUE THREAD

**Issue by clinejj** [webpack/webpack-dev-server#4167]
### Bug report

There is an open CVE for `node-forge` 0.10.0, which webpack-dev-server includes via `selfsigned` 1.10.11. 
- https://github.com/advisories/GHSA-5rrq-pxf6-6jx5
- https://github.com/advisories/GHSA-gf8q-jrpm-jvxq

Updating to `selfsigned` 1.10.13 will address the issue and is a backwards compatible update. This was attempted to be fixed in https://github.com/webpack/webpack-dev-server/pull/4162 by @wcedmisten-reify, but they could not sign the CLA. Setting up issue for another contributor who can make the change.

### Actual Behavior

Message from dependabot about the security issue:
```
The latest possible version that can be installed is 0.10.0 because of the following conflicting dependency:
webpack-dev-server@4.7.2 requires node-forge@^0.10.0 via selfsigned@1.10.11
The earliest fixed version is 1.0.0.
```

### Expected Behavior

N/A

### How Do We Reproduce?

N/A

**Comment by alexander-akait** [comment]
PR https://github.com/webpack/webpack-dev-server/pull/4144/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R60, anyway you can update deps locally, because we use `^`

**Comment by alexander-akait** [comment]
Oh, I see, we need to update `selfsigned@2`, WIP

**Comment by alexander-akait** [comment]
Please update to `4.7.3`

**Comment by clinejj** [comment]
Thanks for the quick fix, can confirm it addressed the issue
