### ISSUE TITLE
host: local-ip cannot visit with localhost

### ISSUE THREAD

**Issue by kingller** [webpack/webpack-dev-server#4172]
### Bug report

```
{
    devServer: {
        host: 'local-ip',
        port,
        proxy: {
            '/app': { target: `http://localhost:${port}`, pathRewrite: { '$': '.html' } },
        },
        open: ['/app'],
    },
}
```

### Actual Behavior

When I set host with local-ip, cannot visit it with localhost, and I don't know the ip, so how to set the proxy as above?
And when I set host with 0.0.0.0, then the open url is not ip address.

### Expected Behavior

Open url with local ip, and can be visited with localhost.

**Comment by alexander-akait** [comment]
You can use `const localIP = DevServer.getHostname("local-ip")` and reuse it in any string

**Comment by kingller** [comment]
Thanks very much
