### ISSUE TITLE
[hash] is not supported in publicPath

### ISSUE THREAD

**Issue by kouhin** [webpack/webpack-dev-server#418]
`[hash]` is supported in publicPath, =>  https://webpack.github.io/docs/long-term-caching.html

However when using webpack-dev-server, and set the config as follows: 

```
  entry: {
    main: './client'
  },
  output: {
    path: path.join(distPath, 'assets', '[hash]'),
    publicPath: CDN_PATH + '/assets/[hash]/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[hash].js'
  },
```

Start webpack-dev-server, the serving URL of main.js is `http://localhost:3001/assets/[hash]/main.8bb84eb7765fd7cabc43.js`.

**Comment by sokra** [comment]
No this doesn't work. It also recommended to NOT use `[hash]` in a dev-server configuration. Use a `CDN_PATH` is propably also wrong. Caching is not an issue in development.

**Comment by kouhin** [comment]
@sokra Yes，I understand. Thank you.

Now, I’m using git-rev-sync instead of [hash], it works perfect.
