### ISSUE TITLE
Dependency to old version of chokidar results in using a old version of glob-parent inkluding a high vulnerability

### ISSUE THREAD

**Issue by pweibbre** [webpack/webpack-dev-server#4182]
### Bug report

webpack-dev-server@3.11.3 has dependency to old chokidar version 2.1.8 which has dependency to glob-parent@3.1.0 which has a high vulnerabilty

### Actual Behavior

i'm using Angular 12 with the latest version of @angular-devkit/build-angular@12.2.15.
the dependencies leads to the use of webpack-dev-server@3.11.3 which is the latest one for Angular 12.
in package.json there is a dependency to a rather old verion of chokidar:
"chokidar": "^2.1.8"
this leads to the use of glob-parent@3.1.0
```
+-- @angular-devkit/build-angular@12.2.15
| +-- copy-webpack-plugin@9.0.1
| | +-- fast-glob@3.2.10
| | | `-- glob-parent@5.1.2
| | `-- glob-parent@6.0.2
| `-- webpack-dev-server@3.11.3
|   `-- chokidar@2.1.8
|     `-- glob-parent@3.1.0
`-- @angular/compiler-cli@12.2.15
  `-- chokidar@3.5.2
    `-- glob-parent@5.1.2
```

the resulting glob-parent is marked as having a high vulnerability:
``` 
 High            Regular expression denial of service                          

  Package         glob-parent                                                   

  Dependency of   @angular-devkit/build-angular [dev]                           

  Path            @angular-devkit/build-angular > webpack-dev-server >          
                  chokidar > glob-parent                                        

  More info       https://github.com/advisories/GHSA-ww39-953v-wcq6            
 ``` 
can you please check the possibility of using chokidar in version ^3.5.2 ?

### Expected Behavior

no high vulnerabilties caused by webpack-dev-server dependencies

### How Do We Reproduce?

Use Angular12:
```
Angular CLI: 12.2.15
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 ia32

Angular: 12.2.15
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.15
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            12.2.15
@angular-devkit/schematics      12.2.15
@schematics/angular             12.2.15
rxjs                            6.6.7
typescript                      4.3.5
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
$ npx webpack-cli info
npx: Installierte 50 in 13.261s

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) ia32 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 4.10 GB / 15.34 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.18362.1593.0)
    Internet Explorer: 11.0.18362.1766

**Comment by alexander-akait** [comment]
Sorry, it is not fixable, please update dev server to v4, v4 supports webpack v4 and webpack v5, just update
