### ISSUE TITLE
webpack-dev-server can't find localhost

### ISSUE THREAD

**Issue by em-cd** [webpack/webpack-dev-server#420]
I'm running Yosemite on a mac. I installed the webpack server ok but when I run the command `webpack-dev-server` I get the error:

`events.js:154`
    `  throw er; // Unhandled 'error' event`
  `    ^`

`Error: getaddrinfo ENOTFOUND localhost`
  `  at errnoException (dns.js:26:10)`
  `  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)`

I've checked the hosts file and localhost is correctly listed there. I am also using MAMP for another project on port 80, so I tried running the server on a different port with the command `webpack-dev-server --port 3001` but got the exact same error. Any ideas why this is happening?

**Comment by em-cd** [comment]
nvm, /etc/hosts was messed up after all. my bad!

**Comment by nebiljabari** [comment]
If it can help someone with the same annoying error : https://github.com/angular/angular-cli/issues/2227#issuecomment-285955502

**Comment by Chewiwehavecompany** [comment]
I tried to run the command ng serve in terminal and I get this error

getaddrinfo ENOTFOUND localhost
Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Help please
