### ISSUE TITLE
[webpack-dev-server]: Setting Websocket Connection invoked twice

### ISSUE THREAD

**Issue by rkovalyov** [webpack/webpack-dev-server#4224]
### Bug report
Setting Websocket Connection invoked twice

### Actual Behavior

invoked 2 request for setting websocket connection (see in Network Tab of DevTools )

<img width="600" alt="Webpack Template 2022-01-25 22-51-14" src="https://user-images.githubusercontent.com/4090779/151057743-f089fa64-dade-4df5-921e-41dbf14d769f.png">

### Expected Behavior
invoked 1 request for setting websocket connection

### How Do We Reproduce?

[Repo for reproduce](https://github.com/rkovalyov/webpack-react-refresh)
1. `yarn`
2. `yarn start`

**Comment by alexander-akait** [comment]
It was created by `react-refresh-webpack-plugin`, please reopen an issue, look at stack trace.

First connection:
```
  | WebSocketClient | @ | WebSocketClient.js:16
-- | -- | -- | --
  | initSocket | @ | socket.js:21
  | ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=localhost&port=8080&pathname=%2Fws&logging=info&reconnect=10 | @ | index.js:273
  | options.factory | @ | react refresh:6
  | __webpack_require__ | @ | bootstrap:24
  | (anonymous) | @ | startup:5
  | (anonymous)
```

Second:
```
WebSocketClient | @ | WebSocketClient.js:16
-- | -- | --
  | initWDSSocket | @ | WDSSocket.js:23
  | initSocket | @ | ErrorOverlayEntry.js:83
  | executeWithRetryAndTimeout | @ | retry.js:9
  | runWithRetry | @ | retry.js:17
  | setupOverlay | @ | ErrorOverlayEntry.js:82
  | runWithPatchedUrl | @ | patchUrl.js:29
  | ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=8080&sockProtocol=http | @ | ErrorOverlayEntry.js:77
  | options.factory | @ | react refresh:6
  | __webpack_require__ | @ | bootstrap:24
  | (anonymous) | @ | startup:7
  | (anonymous)
```

look at `| ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=8080&sockProtocol=http | @ | ErrorOverlayEntry.js:77`

If you set:
```
new ReactRefreshPlugin({
  overlay: false
}),
```

no double connection 

@pmmmwh can you provide more infromation

**Comment by pmmmwh** [comment]
Hi, this can be closed, we haven't updated the implementation yet but I'll do it soon.

**Comment by alexander-akait** [comment]
@pmmmwh Feel free to any feedback and PRs if you need to expose more
