### ISSUE TITLE
Allow proxy's bypass to stop handler chain

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack-dev-server#4230]
### Feature Proposal

We are working with a "proxy and cache" feature, in which we'd like to proxy a request the first time it appears and cache the response, after then we immediately respond from cache and not to proxy it to target server.

After some investigation we find `proxy`'s `bypass` function is a suitable place to check the cache existence, we can also `response.end` in it, however we are unable to stop further request handlers whatever we return from `bypass` function, the request may further be handled by others like `history-fallback-middleware` and throws or responds incorrect content.

By inspecting both source codes of `webpack-dev-server` and `http-proxy-middleware` I believe this cannot be archived using `context` or `router` option as function, both of them are not able to stop calling `next()` handler.

I'd like to suggest we allow a special return value for `bypass` like `true` or `{type: 'stop'}` to stop calling `next()`.

And also, I'm wondering how this functionality should go after `bypass` is deprecated in the next release.

### Feature Use Case

In the case we upgraded `bypass` function, we may have some config like:

```js
proxy: {
    '/api': {
        target: 'http://some-host',
        bypass: (req, res) => {
            const mock = MOCK_CACHE.find(req);
            if (mock) {
                // Handle headers
                res.end(mock.body);
                // Stop next handler
                return true;
            }
            
            return null;
        },
        onProxyRes: async (proxyRes, req, res) => {
            const body = await consumeResponseData(proxyRes);
            // Add to cahce on first response
            MOCK_CACHE.add(req, {headers: proxyRes.headers, body});
            res.end(body);
        },
    },
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

Not using `webpack-cli` but have `envinfo`:

```
  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 131.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/76613_1642945172661/bin/node
    Yarn: 3.1.0 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/76613_1642945172661/bin/yarn
    npm: 8.3.0 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/76613_1642945172661/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Safari: 15.2
  npmPackages:
    webpack: ^5.66.0 => 5.66.0
    webpack-dev-server: ^4.7.3 => 4.7.3
```

**Comment by alexander-akait** [comment]
I think better to use custom middleware in this case, there are other cases which we don't cover, also we want to remove `bypass` in the next major release, because it is slow down proxy in dev env

**Comment by otakustay** [comment]
Totally understand that, the main reason I request for this is `webpack-dev-server` has a quite complex logic to parse routes from `proxy` options, and `http-proxy-middleware` also has a complex context matching mechanism, it's not easy to setup generic custom middleware from various `proxy` options.

I will try to implement it using a custom middleware
