### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by davidblurton** [webpack/webpack-dev-server#425]
Can we get some more maintainers on this repo? It's a valuable part of the webpack ecosystem but has 27 PRs waiting for attention. Perhaps you could use some help?

**Comment by davidblurton** [comment]
It's been two months with no commits, please ask for help maintaining this important project.

**Comment by sokra** [comment]
Any volunteer?

**Comment by SpaceK33z** [comment]
@sokra, I want to volunteer to help maintain this project. I'm using it full-time at my work, and want to contribute something back :).

**Comment by SpaceK33z** [comment]
@davidblurton, I'm now a maintainer for this repo and [webpack-dev-middleware](webpack/webpack-dev-middleware). I'll be looking into the PR's and bring the issue count down.
