### ISSUE TITLE
Potential memory leak in windows CI

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-dev-server#4251]
### Bug report

Recently, CI is flaky for windows and failing with the following error - 

<img width="984" alt="Screenshot 2022-02-04 at 7 59 41 AM" src="https://user-images.githubusercontent.com/46647141/152462555-e4d7a387-ebe8-453e-af6f-244811faa0b0.png">

 

### Actual Behavior

CI `Error: Process completed with exit code 1.`

### Expected Behavior

CI should not fail with this error.

### How Do We Reproduce?

https://github.com/webpack/webpack-dev-server/runs/5060845474?check_suite_focus=true

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
CI environment

**Comment by alexander-akait** [comment]
@snitin315 Let's try to increase memory usage for tests

**Comment by snitin315** [comment]
@alexander-akait  How can we do that with jest?

**Comment by alexander-akait** [comment]
Just increase node memory limit

**Comment by alexander-akait** [comment]
Let's close, I think we solved it (or packages in our deps solved it :smile: )
