### ISSUE TITLE
Web Sockets are breaking on Docker for Actioncable after upgrade from webpack-dev-server ^3 to 4.7

### ISSUE THREAD

**Issue by RailsCod3rFuture** [webpack/webpack-dev-server#4255]
- [ x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
const { webpackConfig } = require('shakapacker')

// See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.

module.exports = webpackConfig
```
webpacker.yml

```
Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: []

  cache_manifest: false

  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .tsx
    - .ts
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
    - .html
    - .scss

development:
  <<: *default
  compile: true
  check_yarn_integrity: false

  dev_server:
    https: false
    host: 0.0.0.0
    port: 3035
    sockPort: 3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true

staging:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
```
`
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

System:
    OS: macOS 11.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 24.24 MB / 16.00 GB
  Binaries:
    Node: 16.0.0 - ~/.asdf/installs/nodejs/16.0.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Safari: 14.1.2
  Packages:
    babel-loader: 8 => 8.2.3
    compression-webpack-plugin: 9 => 9.2.0
    pnp-webpack-plugin: 1 => 1.7.0
    terser-webpack-plugin: 5 => 5.3.0
    webpack: 5 => 5.67.0
    webpack-assets-manifest: 5 => 5.1.0
    webpack-cli: 4 => 4.9.2
    webpack-dev-server: ^4.7.3 => 4.7.3
    webpack-merge: 5 => 5.8.0

### Expected Behavior

WebSocket connection upgrades and successfully completes actioncable request

### Actual Behavior

WebSocket connection to wss://hostname/cable' failed

### For Features; What is the motivation and/or use-case for the feature?

We weren't aware of the switch from sockjs to ws for webpack-dev-server 4.7.3, and its breaking sockets in our docker container. What configuration is required to return back to sockjs, as it was in webpack-dev-server 3?

**Comment by alexander-akait** [comment]
Please fix your URL to web sockets, we provide options for this (look at https://webpack.js.org/configuration/dev-server/#websocketurl), sorry you don't provide configuration so I can't help you
