### ISSUE TITLE
CI: add job to check if types are up-to-date

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-dev-server#4279]
### Modification Proposal

Add job to check if `types` are up-to-date. 

A possible solution is to build types on CI and check if there are modifications to the types folder/files. This can be a part of the lint job.

### Expected Behavior / Situation

CI will fail if the PR author doesn't update types. 

### Actual Behavior / Situation

No check present.

**Comment by alexander-akait** [comment]
Yep, PR welcome
