### ISSUE TITLE
target is not defined error in 2.0.0-beta when you specify a proxy

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack-dev-server#428]
@jamsesso, @sokra 

1. npm install webpack-dev-server@v2.0.0-beta

2. Modify webpack.config.js to include a proxy.

3. Run `webpack-dev-server`  

`ReferenceError: target is not defined`

See -
https://github.com/webpack/webpack-dev-server/blame/master/lib/Server.js#L151
https://github.com/webpack/webpack-dev-server/commit/efd32a05944499b0c8165da6ff75519fb8fe21a6

**Comment by chimurai** [comment]
#392 should fix this issue.

**Comment by joshunger** [comment]
Excellent, thanks!  ... didn't see that other issue.
