### ISSUE TITLE
Error when installing npm install webpack-dev-server -g

### ISSUE THREAD

**Issue by sudanvellakovilkanakavel** [webpack/webpack-dev-server#429]
I get the following error when installing    npm install webpack-dev-server -g

/Users/kanaks/msite/lib
├── UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
└─┬ webpack-dev-server@1.14.1 
  └── UNMET PEER DEPENDENCY webpack@>=1.0.0 <3
what does it mean.Kindly help me to solve this issue.I am new to Node.js and React

**Comment by sudanvellakovilkanakavel** [comment]
Ifinally found the solution.my global in stallion  path was the problem

npm config set prefix ~/.npm-global
npm install -g babel webpack webpack webpack-dev-server

**Comment by dandv** [comment]
I get a similar error without any global installation or "stallion path" (?)

> UNMET PEER DEPENDENCY webpack@2.1.0-beta.25

```js
"devDependencies": {
  "webpack": "^2.1.0-beta.25",
  "webpack-dev-server": "^1.16.1"
}
```

**Comment by SpaceK33z** [comment]
@dandv, that is because you should also use the v2 beta for dev-server (`2.1.0-beta.8`).

**Comment by dandv** [comment]
Correct, the solution was to specify the dev server at the beta too:

```js
{
   "webpack": "^2.1.0-beta.25",
    "webpack-dev-server": "^2.1.0-beta.8"
  }
```
