### ISSUE TITLE
Receiving new type of error from WebSocket.js

### ISSUE THREAD

**Issue by RailsCod3rFuture** [webpack/webpack-dev-server#4294]
### Actual Behavior

```
Uncaught TypeError: __webpack_require__.n is not a function
    at Object../node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=localhost&port=3035&pathname=%2Fws&logging=info&reconnect=10 (WebSocketClient.js:57:1)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (application.js:1:1)
    at application.js:1:1
    at Function.__webpack_require__.O (chunk loaded:25:1)
    at application.js:1:1
    at webpackJsonpCallback (jsonp chunk loading:19:1)
    at application.js:1:65
```

### Expected Behavior

WebSocket.js should compile without throwing error.

### How Do We Reproduce?

Install the latest webpack-dev-server and shakapacker 6.0 gem for rails

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: macOS 11.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 26.08 MB / 16.00 GB
  Binaries:
    Node: 16.0.0 - ~/.asdf/installs/nodejs/16.0.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Chrome: 98.0.4758.102
    Firefox: 96.0.2
    Safari: 14.1.2
  Packages:
    babel-loader: 8 => 8.2.3 
    compression-webpack-plugin: 9 => 9.2.0 
    dotenv-webpack: ^7.1.0 => 7.1.0 
    pnp-webpack-plugin: 1 => 1.7.0 
    terser-webpack-plugin: 5 => 5.3.0 
    webpack: 5 => 5.67.0 
    webpack-assets-manifest: 5 => 5.1.0 
    webpack-cli: 4 => 4.9.2 
    webpack-dev-server: ^4.7.4 => 4.7.4 
    webpack-merge: 5 => 5.8.0

**Comment by RailsCod3rFuture** [comment]
When I'm on a local domain, it doesn't happen. But, when I use a sub domain it does.

**Comment by alexander-akait** [comment]
Please open an issue in `shakapacker`
