### ISSUE TITLE
Cannot disable client overlay

### ISSUE THREAD

**Issue by iMoses-Apiiro** [webpack/webpack-dev-server#4298]
### Bug report

Trying to disable the client overlay fails

### Actual Behavior

```js
devServer: { client: { overlay: false } }

devServer: { client: { overlay: { errors: false, warnings: false } } }

webpack serve --no-client-overlay
```

All these options seems to be ignored and the overlay screen still appears on a client-side error

### Expected Behavior

overlay should be disabled and not appear at all :shrug: 

### How Do We Reproduce?

Any simple app will do. Add a `throw Error('test')` to one of the loaded components and see the overlay screen

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Linux 5.14 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 15.91 GB / 62.56 GB
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.1.2 - /usr/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 97.0.1
  Packages:
    babel-loader: ^8.2.3 => 8.2.3 
    case-sensitive-paths-webpack-plugin: ^2.4.0 => 2.4.0 
    clean-webpack-plugin: ^4.0.0 => 4.0.0 
    copy-webpack-plugin: ^10.2.0 => 10.2.0 
    css-loader: ^6.5.1 => 6.5.1 
    css-minimizer-webpack-plugin: ^3.3.1 => 3.3.1 
    error-overlay-webpack-plugin: ^1.1.0 => 1.1.0 
    eslint-import-resolver-webpack: ^0.13.2 => 0.13.2 
    eslint-webpack-plugin: ^3.1.1 => 3.1.1 
    file-loader: ^6.2.0 => 6.2.0 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    postcss-loader: ^6.2.1 => 6.2.1 
    webpack: ^5.69.1 => 5.69.1 
    webpack-cli: ^4.9.1 => 4.9.2 
    webpack-dev-server: ^4.7.3 => 4.7.4 
    webpack-react-component-name: ^5.0.2 => 5.0.2 
```

note: `error-overlay-webpack-plugin` is listed but not used, and when used both overlay screens appear on the client

**Comment by alexander-akait** [comment]
Because you use `error-overlay-webpack-plugin`

**Comment by alexander-akait** [comment]
Yes, `@pmmmwh/react-refresh-webpack-plugin` has own logic for overlay, so it can be broken, I am afraid no problems with overlay here (we have a lot of test on it using puppeteer), we better integration with `@pmmmwh/react-refresh-webpack-plugin` we have https://github.com/webpack/webpack-dev-server/issues/4261

**Comment by iMoses-Apiiro** [comment]
@alexander-akait ok, i'll take your word for it and re-open if I found anything that contradicts
I have noticed their overlay, seems reasonable that the problem is coming from there

thanks
