### ISSUE TITLE
New option `application` to allow developers to use their custom server application

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-dev-server#4303]
### Feature Proposal

New option `application: { type: "connect", options: ...options }` (default value is `express`)

### Feature Use Case

> we need application: { type: "connect", options: ...options } (default value is express) in the long term we should migrate on connect or maybe something more simple, express is not get updated a long time, but we need to support http2/https without any problems and workarounds, I think now we can setup our tests and fix code for connect and them add this options, so we can have two-three PRs

Please refer https://github.com/webpack/webpack-dev-server/pull/4068#issuecomment-998635537

**Comment by alexander-akait** [comment]
Let's close in favor of https://github.com/webpack/webpack-dev-server/issues/4741 (there are more comments)
