### ISSUE TITLE
add ability to specify content-type charset utf-8

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack-dev-server#432]
Is it possible to define the Content-Type with a charset of UTF-8 for responses?  I don't see it when webpack-dev-server serves content from the content base.  This causes encoding issues because the bundle.js is UTF-8.

**Comment by sokra** [comment]
you can add a meta tag into the HTML.

**Comment by joshhunt** [comment]
What about for assets that arent HTML?

**Comment by ericlau-solid** [comment]
I notice that webpack-dev-server's bundle.js is encoded using Windows-1252 while webpack's build output .js files are encoded in UTF-8. This discrepancy is causing some characters to show up one way during development but another on build.

How do you force webpack-dev-server to create bundle.js using UTF-8 encoding? Adding a meta tag in HTML has no effect.

**Comment by mikekolganov** [comment]
+1 @ericlau-solid

**Comment by wildeyes** [comment]
@sokra how do you that?

**Comment by SpaceK33z** [comment]
Does this also happen when outputting a bundle with `webpack`?

**Comment by SpaceK33z** [comment]
Is this still happening, and if so, can someone provide more info?

**Comment by joshunger** [comment]
Did it not repro for you?

**Comment by SpaceK33z** [comment]
No, I can't find a simple way to reproduce this. A PR is welcome.

**Comment by joshunger** [comment]
I'm not on my.comouter for a few days. what content type header do you see on the bundle request?

**Comment by SpaceK33z** [comment]
The content type header for `bundle.js` is `Content-Type: application/javascript`. You want `Content-Type: application/json; charset=utf-8` I suppose?

**Comment by joshunger** [comment]
I'm on Mac too. :) It's only non ASCII (?) special characters that mess you up. Yes. I'm assuming you can look up the content type and dynamically add. That would be great!

**Comment by SpaceK33z** [comment]
I added `¢Ö` in the `index.html`, and in my entry file. Both ways seem to work, without setting the encoding anywhere. Tested on Chrome, Safari and FF.

**Comment by joshunger** [comment]
In JavaScript?

**Comment by SpaceK33z** [comment]
Yeah, in `examples/modus-inline/app.js`, I changed `It's working.` to `It's working.¢Ö`. It correctly displayed the special characters without changes.

I noticed that the Javascript file is called with `<script src="/bundle.js" type="text/javascript" charset="utf-8"></script>`, but even after removing `charset="utf-8"`, the special chars work.

**Comment by joshunger** [comment]
Ah. Right what is the header on your html file? I believe the browser
defaults the charset to J's files loaded to the charset of the loaded html
file. Send confusing.

**Comment by SpaceK33z** [comment]
Interesting, the header of the html file is `Content-Type:text/html; charset=UTF-8`. This html file is served by the `contentBase` option. Do you also use `contentBase`, or do you use html-webpack-plugin?

**Comment by joshunger** [comment]
Yeah I don't think we use content base. We have a couple of different
projects that use either html plugin, handlebar template, or nginx.

I believe angular is a good example of a special characters that fails
loading but I can't find the stock overflow post that talked about. They
used a Unicode character for a constant for something.

Apologies for typos.

**Comment by SpaceK33z** [comment]
Technically this is an issue in webpack-dev-middleware, that package takes care of making a response. [This line](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L231) is responsible for generating the `Content-Type`.

I'm not sure though if we can just add `charset=UTF-8` to ALL responses, without breaking something.

**Comment by joshunger** [comment]
Yeah how do you look up charset webpack is using?

**Comment by SpaceK33z** [comment]
As far as I can tell, it's only possible to change it with [webpack-encoding-plugin](https://github.com/quackes/webpack-encoding-plugin). [This PR](https://github.com/webpack/webpack/pull/1797/files) from the webpack repo also assumes utf-8.

**Comment by joshunger** [comment]
Ah is there a constants file we can just reference? Then we can fix the pr?
Is that what you're thinking?

**Comment by SpaceK33z** [comment]
I'm not sure yet, but after that PR linked above, I'm thinking webpack always assumes utf-8.

**Comment by callumacrae** [comment]
Is there any workaround or fix to this yet?

After being built with webpack:

<img width="354" alt="screen shot 2016-10-04 at 12 06 48" src="https://cloud.githubusercontent.com/assets/472830/19072230/fe726518-8a2b-11e6-8255-33ab5b23057e.png">

Being served with webpack-dev-server:

<img width="356" alt="screen shot 2016-10-04 at 12 10 31" src="https://cloud.githubusercontent.com/assets/472830/19072235/047ebc22-8a2c-11e6-9553-0b2cc16c038d.png">

**Comment by SpaceK33z** [comment]
@callumacrae, yes it would be nice if you can help with this.

The real issue is in webpack-dev-middleware, to be precise on [this line](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L243). *Probably*, it is enough to add `;charset=UTF-8` after the mime lookup.

You could test out if that works. If it works, send a PR. We would still need to find out if it breaks stuff, but we could do a beta release and let some people test it. If it doesn't work, search for other places where `Content-Type` is set (or should be set) without `charset=UTF-8`.

**Comment by callumacrae** [comment]
@SpaceK33z: That fixes the issue for me. I've sent a PR: https://github.com/webpack/webpack-dev-middleware/pull/136

**Comment by zhengtulymGh** [comment]
在html里面引用`<script type="text/javascript" src="/static/js/vendor.dll.js" charset="UTF-8"></script>`，使用webpack-dev-server启动的时候发现返回的是html文件怎么破？
