### ISSUE TITLE
Module not found: Error, with "node_modules\webpack-dev-server\client\index.js". 

### ISSUE THREAD

**Issue by CastleCB** [webpack/webpack-dev-server#4326]
### Bug report
Seem to be a similar issue with #3221.But no "webpack.common.js" file could be found under node_module.

### Actual Behavior

Session contents restored from 3/2/2022 at 9:43:17 PM 
Failed to compile.

Module not found: Error: Can't resolve 'D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10' in 'D:\Documents\self_S\C#.NET\Reactivities\client-app'
assets by path static/ 1.32 MiB
  asset static/js/bundle.js 1.31 MiB [emitted] (name: main) 1 related asset
  asset static/js/C_NET_Reactivities_client-app_node_modules_web-vitals_dist_web-vitals_js.chunk.js 7.14 KiB [emitted] 1 related asset
  asset static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg 2.57 KiB [emitted] (auxiliary name: main)
asset index.html 1.67 KiB [emitted]
asset asset-manifest.json 666 bytes [emitted]
cached modules 1.19 MiB (javascript) 31.3 KiB (runtime) [cached] 105 modules

ERROR in Module not found: Error: Can't resolve 'D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10' in 'D:\Documents\self_S\C#.NET\Reactivities\client-app'
resolve 'D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10' in 'D:\Documents\self_S\C#.NET\Reactivities\client-app'
  using description file: D:\Documents\self_S\C#.NET\Reactivities\client-app\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\package.json (relative path: ./client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10 doesn't exist
      .web.mjs
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.web.mjs doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.mjs doesn't exist
      .web.js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.web.js doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.js doesn't exist
      .web.ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.web.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.ts doesn't exist
      .web.tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.web.tsx doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.json doesn't exist
      .web.jsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.web.jsx doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10.jsx doesn't exist
      as directory
        D:\Documents\self_S\C#.NET\Reactivities\client-app\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&reconnect=10 doesn't exist
  using description file: D:\Documents\self_S\C#.NET\Reactivities\client-app\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    No description file found in D:\Documents\self_S or above
    no extension
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C doesn't exist
    .web.mjs
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.web.mjs doesn't exist
    .mjs
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.mjs doesn't exist
    .web.js
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.web.js doesn't exist
    .js
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.js doesn't exist
    .web.ts
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.web.ts doesn't exist
    .ts
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.ts doesn't exist
    .web.tsx
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.web.tsx doesn't exist
    .tsx
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.tsx doesn't exist
    .json
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.json doesn't exist
    .web.jsx
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.web.jsx doesn't exist
    .jsx
      Field 'browser' doesn't contain a valid alias configuration
      D:\Documents\self_S\C.jsx doesn't exist
    as directory
      D:\Documents\self_S\C doesn't exist

webpack 5.69.1 compiled with 1 error in 10712 ms

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please provide steps to reproduce and your webpack config.

**Comment by CastleCB** [comment]
Thanks.
Misclicked the submit button before I complete my editing of this issue. Will recreate the issue with your templates.
