### ISSUE TITLE
Is there an inline: true option now?

### ISSUE THREAD

**Issue by sunyang713** [webpack/webpack-dev-server#433]
On this page in the documentation, it says "there is no `inline: true` option" https://webpack.github.io/docs/webpack-dev-server.html

But I've recently seen a lot of repos and a lot of reputable webpack guides specify an `inline: true` option in the devServer configuration.

Do I still need to do this (specifying entry points):

```javascript

module.exports = {
  . . .
  devServer: {
    . . .
    hot: true,
    . . .
  },
  . . .
  entry: [
    "webpack-dev-server/client?http://localhost:8080/",
    "webpack/hot/dev-server",
    path.resolve(srcPath, "index")
  ],
  . . .
  plugins: [
    . . .
    new webpack.HotModuleReplacementPlugin(),
    . . .
  ]
}

```

or can I do this:
```javascript

module.exports = {
  . . .
  devServer: {
    . . .
    inline: true,
    hot: true,
    . . .
  },
  . . .
  entry: path.resolve(srcPath, "index"),
  . . .
  plugins: [
    . . .
    new webpack.HotModuleReplacementPlugin(),
    . . .
  ]
}

```

**Comment by sokra** [comment]
Yes this will work for the CLI. The API has no inline option.
