### ISSUE TITLE
Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'vscode-webview' is not allowed

### ISSUE THREAD

**Issue by tjx666** [webpack/webpack-dev-server#4338]
- VS Code Version: 1.66.0-insider
- OS Version: MacOS 12.2.1

I try to develop VSCode webview with webpack + HMR. After configure the right CSP, it seems webpack-dev-server can't make a WebSocket Object.

Steps to Reproduce:

1. clone project https://github.com/tjx666/scripting-listener
2. install dependencies by `npm install`
3. open debugger panel, click `Run Extension`
4. go to Extension Development Host workspace
5. open webview panel by call command `Open Scripting Listener Log Viewer`
6. open devtools, will show following screenshot error message

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158300681-132a3cb4-4c56-4b40-bd19-7b1895c2b81b.png">

I had configured the CSP to allow `ws://localhost:3000`, check details [here](https://github.com/tjx666/scripting-listener/blob/master/src/LogViewer.ts#L56):

**Comment by tjx666** [comment]
What's your meaning set client option?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158432752-c718628e-37b1-4686-ab79-1344588ad653.png">

**Comment by alexander-akait** [comment]
Look here https://webpack.js.org/configuration/dev-server/#websocketurl

**Comment by tjx666** [comment]
I think here WebSocket had been connected because the response code is 101.And I manulay create the WebSocket instance in console at the place which error happen is no problem.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158468135-3c40bd57-eb62-4a3a-a45e-1a330ae4b81d.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158468243-11157a3b-3e78-4f7a-9b4a-c8f03ad77235.png">


Don't know why throw this error. Error point to:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/158467610-75a25720-e277-4b69-985a-6cea2979342b.png">

**Comment by alexander-akait** [comment]
Because internal window uses `vscode-webview` protocol

**Comment by tjx666** [comment]
After I manually set the protocol, the same issue still exits:

![image](https://user-images.githubusercontent.com/41773861/158531132-971ccc19-43b5-464f-a7e5-cbab0bb0f62c.png)

**Comment by tjx666** [comment]
Somw info may help: https://github.com/microsoft/vscode/issues/145093#issuecomment-1068749058

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here, we use `new WebSocket(...)` constructor and it accepts only ws/wss protocols, but webview uses non standard, I think you need custom client to working with vscode webview

**Comment by tjx666** [comment]
Fixed it by custom devServer client option in entry url and adjust the public path:

https://github.com/tjx666/scripting-listener/commit/34ace884434794db21d4772c6712d3bfd3725de5

**Comment by b2whats** [comment]
> Sorry, we can't fix it here, we use `new WebSocket(...)` constructor and it accepts only ws/wss protocols, but webview uses non standard, I think you need custom client to working with vscode webview

its wrong, constructor websocket accept not only ws and wss, also http and https

[url](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket#url)
The URL of the target WebSocket server to connect to. The URL must use one of the following schemes: ws, wss, http, or https, and cannot include a [URL fragment](https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Fragment). If a relative URL is provided, it is relative to the base URL of the calling script.

**Comment by alexander-akait** [comment]
@b2whats Looks like now it is true, do you want to send a fix?
