### ISSUE TITLE
webpack can not serve files from the bundle parent (..) folder

### ISSUE THREAD

**Issue by mitya** [webpack/webpack-dev-server#434]
Given that my bundle looks like this:

    src/
    www/
      /static-dir-1
      /static-dir-2
      /bundle # (generated by webpack)
         /all.js
         /all.css
         ... 
      /index.html # (generated by HtmlWebpackPlugin)

The `index.html` is placed outside of the bundle using the `HtmlWebpackPlugin` with option `{filename: '../index.html'}`.

And the problem is that running `webpack-dev-server` like this:

    webpack-dev-server --content-base www

doesn't serve the `index.html`. Which is intended to be the index file for the `www` directory.

Playing with `publicPath` doesn't resolve it.

**Comment by sokra** [comment]
content-base is the wrong option here. It serves files from the real filesystem, not from the virtual webpack filesystem.

You can provide a publicPath to the dev-server for specify which virtual directory should be served. In your case you need two different publicPaths, one for webpack and one for the dev-server

**Comment by mitya** [comment]
Well, actually, two different public paths haven't helped here: no matter what public path I've used — the `webpack-dev-server` serves all its content from that public path, while I've wanted everything but the `index.html` to be served from the `bundle`, and `index.html` to be served from the root dir.

Instead, I've generating the bundle using `webpack`, which writes the `index.html` into the file system, and then `webpack-dev-server` uses the `index.html` from the file system and all the other files from memory. That works for me, as my `index.html` doesn't use the asset hashes, but if somebody's `index.html` is dynamic it will not work.
