### ISSUE TITLE
hardcoded sockjs iframe url

### ISSUE THREAD

**Issue by Zekfad** [webpack/webpack-dev-server#4348]
Why this is hardcoded? 
https://github.com/webpack/webpack-dev-server/blob/95e26fea168440c0f694c16478aae672091d06a3/lib/servers/SockJSServer.js#L46

In our project this is failing because we have a different from `__webpack_dev_server__` path.

**Comment by snitin315** [comment]
Hmm, we can add an option for this.

**Comment by Zekfad** [comment]
> Hmm, we can add an option for this.

That would be nice!

**Comment by alexander-akait** [comment]
Why you need to change it? It is potential security problem

**Comment by Zekfad** [comment]
Because we have only a few restricted paths lead to a webpack server backend in development.
Also its a security problem *not* to change it, as it can be a really easy for scanners and so on.

**Comment by alexander-akait** [comment]
Okay PR welcome
