### ISSUE TITLE
Form-data: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by kongakong** [webpack/webpack-dev-server#435]
I added the package `form-data` to package.json. 

When I start up `webpack-dev-server`, I got this error

       webpack-dev-server.js:1 ./~/form-data/~/mime-db/db.json  
      Module parse failed: /Users/antkong/dev/zeetings/webview/wall/node_modules/form-        data/node_modules/mime-db/db.json Line 2: Unexpected token :
      You may need an appropriate loader to handle this file type.
      | {
      |   "application/1d-interleaved-parityfec": {
      |     "source": "iana"
      |   },
      @ ./~/form-data/~/mime-db/index.js 11:17-37

![image](https://cloud.githubusercontent.com/assets/40389/14009345/fdfc462a-f1de-11e5-9194-a83cda1799ad.png)

How can fix the webpack dev server configuration?

**Comment by sokra** [comment]
Closing because this is not related to webpack-dev-server, but to webpack instead.

> Note: I'm cleaning up the issues list. For questions please use [stackoverflow](http://stackoverflow.com/tags/webpack), or for issues file them on the [webpack](https://github.com/webpack/webpack) repository

**Comment by gebin** [comment]
@kongakong  
Have you solved the problem? I am also troubled by the problem.
Can you tell me about the way how to solve?
