### ISSUE TITLE
Latest (4.7.4) dev server still uses bonjour

### ISSUE THREAD

**Issue by jschuler** [webpack/webpack-dev-server#4352]
I saw that this commit changed from bonjour to bonjour-service
https://github.com/webpack/webpack-dev-server/pull/4310

But as of today, version 4.7.4 still is using `"bonjour": "^3.5.0",`

**Comment by jschuler** [comment]
I see, thanks, will wait for next release then

**Comment by alexander-akait** [comment]
Release will be today
