### ISSUE TITLE
"public" option deprecated but documentation unclear about workarounds

### ISSUE THREAD

**Issue by leemun1** [webpack/webpack-dev-server#4354]
I was previously using webpack-dev-server v3, where I had the following configs:

```js
  devServer: {
    port: 8080,
    disableHostCheck: true,
    public: 'https://some.custom.domain',
    hot: true,
  },
```

According to the [migration guide to v4](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md), the `public` option was replaced by `client.webSocketURL`, so I modified my config like so:

```js
  devServer: {
    port: 8080,
    allowedHosts: 'all', // replaces `disableHostCheck: true`
    client: {
      webSocketURL: 'https://some.custom.domain',
    },
    hot: true,
  },
```

But this doesn't seem to work, am I using the option incorrectly?

Previously, with the `public` option, I got the following output when I started my dev server:
```
 App running at:
  - Local:   http://localhost:8080/ 
  - Network: https://some.custom.domain/
```

Now I get this:
```
 App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.10:8080/
```

Unfortunately I couldn't find any documentation around how to use custom domains for dev servers for v4, and the resources that I found all referred to the `public` option, which won't work anymore.

**Comment by alexander-akait** [comment]
What is your URL in browser when you are working with app?

**Comment by leemun1** [comment]
I would go to `https://some.custom.domain`

**Comment by alexander-akait** [comment]
Set ` webSocketURL: 'wss://some.custom.domain',`

But logs only says real IPs, your `some.custom.domain` is local configuration, we can't get it for console output, also you can have more domains for local setup

**Comment by leemun1** [comment]
!!!!!!!!!!!!!!!!!!

setting `webSocketURL: 'wss://some.custom.domain'` indeed made it work!

The dev server still outputs
```js
 App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.10:8080/ // instead of https://some.custom.domain
```
but I can actually go to the custom domain and use my app.

Thank you!!

**Comment by alexander-akait** [comment]
As I written above, starting with v4 we output the real IP, not your domain, because we can't know your domain, previously we got public option, but some developers says it is confused, so we change it on your API, you can use the `open` option if you want to automatically open your domain

**Comment by leemun1** [comment]
Ah I see that makes sense. Just to confirm before closing the issue, is there no other way to have the console display the custom domain then?

**Comment by alexander-akait** [comment]
You can create small simple plugin using https://webpack.js.org/api/compiler-hooks/#watchrun and output what you need

**Comment by alexander-akait** [comment]
Feel free to any feedback, closed
