### ISSUE TITLE
How access page in browser after config multi page build during dev?

### ISSUE THREAD

**Issue by jackchoumine** [webpack/webpack-dev-server#4360]
env:
```bash
"webpack": "^5.70.0",
 "webpack-cli": "^4.9.2",
 "webpack-dev-server": "^4.7.4"
```
my multi pages dir:
![image](https://user-images.githubusercontent.com/21340150/161013048-8eaa8669-30fc-458d-8ffb-f7160f364083.png)

dist output 

![image](https://user-images.githubusercontent.com/21340150/161013411-8d2f0b9f-283f-4669-89ee-4a7156cc0197.png)

build no problem. 

I open `http://localhost:8080/` in browser , it is 404. 

I dont know how to access the html during dev? I dont confg dev server anything.

**Comment by alexander-akait** [comment]
Check you publicPath
