### ISSUE TITLE
v4.7.3 - Overlay doesn't show in the browser if server type is HTTPS

### ISSUE THREAD

**Issue by pdrgnclvs** [webpack/webpack-dev-server#4370]
### Bug report

I'm developing a small personal website in Vue 3 (3.2.13 to be precise), and when I changed a few settings in vue.config.js related to the development server, the overlay doesn't seem to show up when I change the server type from HTTP to HTTPS as the docs explain.

### Actual Behavior

The website loads fine without any apparent problems but the overlay doesn't show as it would on the HTTP type, even if I change something in the code to trigger an error or a warning.

### Expected Behavior

The overlay should show up as normal since everything else inside vue.config.js doesn't cause any problem, only when the server type is changed.

### How Do We Reproduce?

1. On a Vue 3 project, change the devServer option to the following:

```javascript
module.exports = defineConfig({
  devServer: {
    client: {
      overlay: true,
    },
    host: "localhost",
    open: true,
    server: {
      type: "https",
      options: {
        key: fs.readFileSync(path.join(__dirname, "..", "localhost-key.pem")),
        cert: fs.readFileSync(path.join(__dirname, "..", "localhost.pem")),
      },
    },
  },
});
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```text
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 1.08 GB / 3.83 GB
Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.5.3 - ~/.nvm/versions/node/v16.14.0/bin/npm
Packages:
    sass-loader: ^12.0.0 => 12.6.0
```

This is being used through WSL 2, also webpack-dev-server is at version 4.7.3 🤔

**Comment by alexander-akait** [comment]
Can you create reproducible test repo, vue-cli uses own overlay, so maybe something broken

**Comment by pdrgnclvs** [comment]
Sorry for the delay @alexander-akait, here you go: https://github.com/pdrgnclvs/webpack-dev-server-issue-overlay 👍

It only has two commits: the first one is automatically created by the Vue CLI on project creation so the repo is basically a fresh new project, and the second one has the code in `vue.config.js` that seems to mess with the overlay...

If it runs as HTTPS the overlay doesn't show on error, but as soon as you run as HTTP it shows 🤨

To trigger an error just insert a few line breaks inside `HelloWorld.vue` and the overlay will appear since ESLint/Prettier will complain about unnecessary line breaks 🤔

Anyway, thanks for reaching out 😉

**Comment by alexander-akait** [comment]
Please open an issue in `@vue/cli-service`, I think somewhere bug on their side, without `vue-cli` all works fine, I think they have wrong logic somewhere around https

**Comment by pdrgnclvs** [comment]
Thanks for your help @alexander-akait, I'm going to close this issue now and open one in Vue CLI's repo tomorrow, then link it back here so that your insight can be taken into account 😉
