### ISSUE TITLE
Missing anymatch dependencies for typing

### ISSUE THREAD

**Issue by pcorpet** [webpack/webpack-dev-server#4372]
### Bug report

Checking TypeScript types declarations in my project depending on `webpack-dev-server` fails.

Running `tsc`.

### Actual Behavior

I get this error:
```
node_modules/webpack-dev-server/types/lib/Server.d.ts:3481:37 - error TS7016: Could not find a declaration file for module 'anymatch'. '/usr/app/node_modules/anymatch/index.js' implicitly has an 'any' type.
```

### Expected Behavior

It should not raise an error (probably by pulling the `anymatch` in the dependencies).

### How Do We Reproduce?

I'm not sure, I feel like a simple repository using `webpack-dev-server` without any package loading `anymatch` and testing types.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.13 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 287.63 MB / 15.30 GB
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/app/node_modules/.bin/npm
  Packages:
    babel-loader: ^8.x.x => 8.2.3 
    css-loader: ^6.x.x => 6.6.0 
    eslint-import-resolver-webpack: ^0.13.x => 0.13.2 
    eslint-loader: ^4.x.x => 4.0.2 
    html-webpack-plugin: ^5.x.x => 5.5.0 
    img-loader: ^3.x.x => 3.0.2 
    json-loader: ^0.5.x => 0.5.7 
    null-loader: ^4.x.x => 4.0.1 
    react-hot-loader: ^4.x.x => 4.13.0 
    style-loader: ^3.x.x => 3.3.1 
    svg-transform-loader: ^2.x.x => 2.0.13 
    terser-webpack-plugin: ^5.x.x => 5.3.1 
    webpack: ^5.x.x => 5.68.0 
    webpack-cli: ^4.x.x => 4.9.2 
    webpack-dev-server: >=4.7.1 => 4.7.4 
```

**Comment by alexander-akait** [comment]
Please check your tsconfig.json or provide reproducible example, sorry I can't reproduce

**Comment by pcorpet** [comment]
OK, I'll try to reproduce today

**Comment by alexander-akait** [comment]
@pcorpet I release `4.8.1` with fixes

**Comment by pcorpet** [comment]
I'm going to try 4.8.1 directly on my larger example failing.
