### ISSUE TITLE
File watcher doesn't work in docker after upgrading from 3.11.2 to 4.8.1

### ISSUE THREAD

**Issue by BassOfBass** [webpack/webpack-dev-server#4379]
### Bug report

Recently I've updated my dependencies and `webpack-dev-server` along with them.
`3.11.2` config:
```javascript
const devServer = {
  host: "0.0.0.0",
  port: 3450,
  writeToDisk: true,
  watchOptions: {
    poll: 500,
    aggregateTimeout: 500
  },
  contentBase: path.resolve(__dirname, "static"),
  watchContentBase: true,
  hot: false,
  liveReload: true,
  overlay: true
}
```

`4.8.1` config:
```javascript
const devServer = {
  host: "0.0.0.0",
  port: 3450,
  hot: false,
  liveReload: true,
  static: {
    directory: path.resolve(__dirname, "static"),
    watch: {
      poll: 500,
      aggregateTimeout: 500
    },
  },
  devMiddleware: {
    writeToDisk: true,
  }
};
```
I was using it in a simple way by writing the output files into docker-compose shared volume and reading it off by the backend server. Also using `copy-webpack-plugin` to haul the non-webpack assets there.
The new config worked fine, as in it didn't crash on startup, but I found out the files don't get recompiled on changes.

I've dug a little further and observed these:
1. The files do get updated between docker stack restarts.
2. The files within the webpack container do not get updated live.
3. The files do get updated just fine when ran standalone. There is no recompile message anymore it seems, but the new log entries do get appended on recompile. Whereas in docker not even new log entries get generated.
4. The files also update just fine when ran on the old version of dependencies with exact the same docker-compose config.

With all these things considered, I can assume with 99% chance the problem is not the details of the docker setup but with the new `webpack-dev-server` watcher not liking something about shared docker volumes.

There is a [similar issue](https://github.com/webpack/webpack-dev-server/issues/3483) which is closed but not technically resolved.
I can't provide a repro atm because the compose setup is over-engineered and I would rather exhaust the ways to debug it without creating another docker setup first. So what do I have to do to debug it further?

### Actual Behavior
Webpack dev server recompiling just fine after updating its major version.

### How Do We Reproduce?
No reproduction atm.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  Binaries:
    Node: 12.22.1
    npm: 6.14.13
  Packages:
    babel-loader: ^8.2.4 => 8.2.4
    copy-webpack-plugin: ^10.2.4 => 10.2.4
    css-loader: ^6.7.1 => 6.7.1
    html-webpack-plugin: ^5.3.1 => 5.5.0
    postcss-loader: ^6.2.1 => 6.2.1
    sass-loader: ^12.6.0 => 12.6.0
    style-loader: ^3.3.1 => 3.3.1
    webpack: ^5.71.0 => 5.71.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-server: ^4.8.1 => 4.8.1
    webpack-manifest-plugin: ^5.0.0 => 5.0.0
    webpack-merge: ^5.8.0 => 5.8.0

**Comment by alexander-akait** [comment]
I would help you find a bug in Node.js or chokidar but there is no reproducible repo so it's not possible
