### ISSUE TITLE
Sockjs live reloading migration from v3 to v4 unclear

### ISSUE THREAD

**Issue by WisaniShilumani** [webpack/webpack-dev-server#4382]
Documentation Is:

- [x] Missing

### Please Explain in Detail...

Webpack-dev-server config options migration from v3 to v4 is not clear with regards to changes to websocket options; particularly when using `sockjs` protocol, given the new defaulting to the `ws` protocol. 

When the sockjs protocol is provided in options, the SockJS server is bound to the `'/ws'` path.

This is fixed by adding the webSocketServer options as such:
```
webSocketServer: {
  type: 'sockjs',
  options: {
    path: '/sockjs-node'
  }
}
```

### Your Proposal for Changes
This should be communicated in docs, or the `defaultWebSocketServerOptions` in lib/Server.js [line 1517] currently:
`const defaultWebSocketServerOptions = { path: '/ws' }`

should have the path be equal to `client.webSocketURL` or `client.webSocketURL.pathname`

**Comment by alexander-akait** [comment]
Socksjs supports `ws` and versa vice too, it was replaced in runtime based on supporting

**Comment by WisaniShilumani** [comment]
Alright, if it doesn't warrant a docs update, happy if we close the issue!

**Comment by WisaniShilumani** [comment]
Thanks @alexander-akait I will open a PR shortly!
