### ISSUE TITLE
AWS Inspector Vulnerability Scan | async, minimist, portfinder

### ISSUE THREAD

**Issue by RailsCod3rFuture** [webpack/webpack-dev-server#4398]
I don't know exactly where to post this issue, but some dependencies for the webpack-dev-server are being picked up as major vulnerability risk by AWS. Can you please review the packages that that I are included in the title.

**Comment by alexander-akait** [comment]
Done in master, release will be in near future

**Comment by sap-anawaz** [comment]
Hi @alexander-akait, thank you for solving this. Any idea when the release will be published?

**Comment by alexander-akait** [comment]
I am waiting it https://github.com/webpack/webpack-dev-server/pull/4404 but if it will not be solved in a couple days I will do release
