### ISSUE TITLE
Dev server doesnt rebuild html when a template file is saved

### ISSUE THREAD

**Issue by Miodec** [webpack/webpack-dev-server#4401]
I would like to start by saying that im not sure if this fully applies to the dev server, but im thankful in advance for any pointers / alternative solutions on how to fix this.

### Bug report

Im using html templating to reduce the size of my single page app. My index.html looks like this:
```html

<html lang="en">
  <%= compilation.assets["html/head.html"].source() %>

  <body>
    <%= compilation.assets["html/warnings.html"].source() %>

    <div id="ad_rich_media" class="hidden"></div>
    <div class="customBackground"></div>
...
```

When I save `index.html` dev server reacts correctly, updates the html and refreshes the site. However, when i save any of the files inside the `html` directory, (like `head.html` as visibible above) dev server does not refresh the page. On top of that, `index.html` is not rebuilt, meaning for example the contents of `head.html` are not inserted into the file.

I tried using the `devServer.watchFiles` option and adding the html directory there, which did cause the page to be refreshed on save of one of the template files, but the main index was not rebuilt.

### Actual Behavior

The `index.html` is not built with up to date HTML template files.

### Expected Behavior

The `index.html` should be rebuilt with most recent content of the html template files.

### How Do We Reproduce?

Link to webpack configs: https://github.com/Miodec/monkeytype/blob/dev/frontend/webpack

(config.dev.js is the one using devServer)

```
npx webpack-cli info

System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 84.41 MB / 8.00 GB
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0.1
    Safari: 15.4
  Packages:
    copy-webpack-plugin: 10.2.4 => 10.2.4 
    css-loader: 6.7.1 => 6.7.1 
    css-minimizer-webpack-plugin: 3.4.1 => 3.4.1 
    eslint-webpack-plugin: 3.1.1 => 3.1.1 
    html-minimizer-webpack-plugin: 3.5.0 => 3.5.0 
    html-webpack-plugin: 5.5.0 => 5.5.0 
    json-minimizer-webpack-plugin: 3.3.0 => 3.3.0 
    remove-files-webpack-plugin: 1.5.0 => 1.5.0 
    sass-loader: 12.6.0 => 12.6.0 
    string-replace-loader: 3.1.0 => 3.1.0 
    ts-loader: 9.2.6 => 9.2.6 
    webpack: ^5.68.0 => 5.68.0 
    webpack-bundle-analyzer: 4.5.0 => 4.5.0 
    webpack-cli: 4.9.2 => 4.9.2 
    webpack-dev-server: 4.7.4 => 4.7.4 
    webpack-merge: 5.8.0 => 5.8.0
```

Again, sorry if this is not the appropriate repository.

**Comment by alexander-akait** [comment]
Sorry, bug in `html-webpack-plugin`, please open an issue there, we can't fix it here
