### ISSUE TITLE
Files are not reloaded when required with module syntax

### ISSUE THREAD

**Issue by lucassouza1** [webpack/webpack-dev-server#441]
When using `resolve.root` and requiring a local module as `require('local/module')`, after making some changes in the file, `webpack --watch` or `webpack-dev-server --hot` do not recompile it. However, using `require(./local/module)` syntax, works fine.

**Comment by SpaceK33z** [comment]
If it also happens in `webpack --watch`, it is not a problem in webpack-dev-server. Please make a ticket in the webpack repo for this.
