### ISSUE TITLE
Importing native window functions breaks in IE when using devtool : 'eval'

### ISSUE THREAD

**Issue by flut1** [webpack/webpack-dev-server#442]
Sometimes function aliases exported by other modules will break in IE with an "invalid calling object" error because the function is not executed on the "window" scope. 

### To reproduce:

 - Set the devtool option to 'eval'
 - Export a window function from a JS module (this often happens with npm modules that provide polyfills). For example:
```
// test.js 
module.exports = typeof window !== 'undefined' ? window.open : null
```
 - Import the module using the require syntax and execute it
```
const test = require('./test');

test('https://github.com/');
```
 - Run the page in IE11 (have not tested other versions yet) and notice the "invalid calling object" error. 

The issue does not occur when using another browser (i.e.Chrome, FF)

**Comment by flut1** [comment]
Note:

IE will throw an error on the line where you execute the function. It will not throw an error if you explicitly execute it against the window scope using bind() _or_ call()
```
module.exports = typeof window !== 'undefined' ? window.open.bind(window) : null
```

```
test.call(window, 'https://github.com/');
```

**Comment by SpaceK33z** [comment]
This is not an issue of webpack-dev-server, the dev-server only serves the files from memory. You should report this in the webpack repo.

**Comment by volokolamskspb** [comment]
change your webpack.config to this:
```js 
const path = require('path');
module.exports = {
  devtool: "source-map",
  entry: ['babel-polyfill', path.resolve(__dirname, './yourjs.js')],
  mode: 'production',
  output: {
    path: __dirname+'/draft.iml.ru/static/main/js/',
    filename: 'yout.js'
  }
};
```
You have to to add ```devtool : "source-map" ``` option.
