### ISSUE TITLE
DEP_WEBPACK_DEV_SERVER_HTTPS 

### ISSUE THREAD

**Issue by jscptman** [webpack/webpack-dev-server#4433]
I am prompted to update to the devServer.server option when I use the devserver.https: true option,
![image](https://user-images.githubusercontent.com/48516756/168462541-5a492161-bd99-49d6-b01e-d775f3b5af89.png)
However, when I updated to this option and started my Vue project, an error was reported:
![image](https://user-images.githubusercontent.com/48516756/168462555-17689852-5734-4bb5-9a67-2b86cb21daaf.png)

**Comment by snitin315** [comment]
Please share steps to reproduce and your webpack config.

**Comment by snitin315** [comment]
Are you using any third-party plugin like [`error-overlay-webpack-plugin`](https://github.com/gregberge/error-overlay-webpack-plugin), it is possible that the plugin is not compatible with `ws` itself.

See https://github.com/gregberge/error-overlay-webpack-plugin/issues/96 for example.
