### ISSUE TITLE
Don't reload on proxy errors

### ISSUE THREAD

**Issue by nhjk** [webpack/webpack-dev-server#446]
I proxy /api/* requests to a backend server. There was an error proxying the request, but webpack-dev-server reloaded every time it got this proxy error, making it very difficult to even see as devtools would refresh before I could see the error. I had no idea if the error was in my frontend code, webpack, webpack-dev-server etc.. until I was finally able to screenshot the console before it refreshed.
![webpack error](https://cloud.githubusercontent.com/assets/3460415/14306003/766c5392-fb90-11e5-91ab-a82be31872fd.png)

**Comment by MarkPieszak** [comment]
Just a tip, you can preserve console logs inside chrome with the checkbox.

**Comment by phillipj** [comment]
@nhjk I stumbled upon this my self, so I opened #478. Fingers crossed it'll get merged :)

**Comment by nhjk** [comment]
@MarkPieszak thanks for the tip, can't believe I've been missing that checkbox this whole time.
@phillipj looking forward to the merge as well! I'm closing this issue because that pull request will resolve it.
