### ISSUE TITLE
upgrade error：Can't resolve 'webpack/hot/log.js、ansi-html-communit、html-entities、webpack/hot/emitter.js

### ISSUE THREAD

**Issue by hcxmj** [webpack/webpack-dev-server#4511]
"webpack": "^5.73.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.9.3",

<img width="990" alt="image" src="https://user-images.githubusercontent.com/58494807/177733720-bbeb43dc-e9ad-451b-88d7-762444ce2cb6.png">

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
