### ISSUE TITLE
Cannot get  / with webpack-dev-server

### ISSUE THREAD

**Issue by fourglobe302500** [webpack/webpack-dev-server#4528]
### Bug report

I have this project https://github.com/fourglobe302500/TheGrindGame/tree/new-content where when I can bundle it up for production without probelm but when I run the webpack it gets the files it should serve but it doen't serve then

### Actual Behavior

It maps two files for static serving app.js and index.html (can verify by the /webpack-web-server route) but does not serve either

### Expected Behavior

It should serve the index.html file that runs the app.js file

#### Needs dotnet and yarn

* Copy the repo https://github.com/fourglobe302500/TheGrindGame
* Checkout to branch ```git checkout new-content```
* run ```dotnet tool restore```
* run ```dotnet run -- Bundle``` for bundling and host the deploy/public folder with anything (live server for vscode for example)
* run ```dotnet run``` for the webpack dev server and open localhost:8080
  * to check serving files go to localhost:8080/webpack-dev-server

 ``` 
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 2.15 GB / 7.78 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.22000.120
  Packages:
    babel-loader: ^8.2.5 => 8.2.5
    copy-webpack-plugin: ^11.0.0 => 11.0.0
    css-loader: ^6.7.1 => 6.7.1
    fable-loader: ^2.1.8 => 2.1.9
    file-loader: ^6.2.0 => 6.2.0
    html-webpack-plugin: ^5.5.0 => 5.5.0
    sass-loader: ^13.0.0 => 13.0.0
    source-map-loader: ^4.0.0 => 4.0.0
    style-loader: ^3.3.1 => 3.3.1
    webpack: ^5.73.0 => 5.73.0
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-dev-server: ^4.9.0 => 4.9.3 
```

**Comment by alexander-akait** [comment]
Why you set `publicPath` for static?

**Comment by fourglobe302500** [comment]
@alexander-akait I tested both with and without `publicPath` defined since it is setup to in the future also bundle a backend server based on asp.net that will reroute / on another port to this one of the webpack (could be the problem but I don't have any reason to write the server for now and I can't find any configuration style that isn't setup for that and works on my project with multiple compilation targets for dotnet)

**Comment by alexander-akait** [comment]
Remove the `publicPath` everywhere, you don't need `publicPath: './'` to have relative public path

**Comment by fourglobe302500** [comment]
It worked, thanks (I had that mainly because the html templater was having trouble linking files but not having it was the solution) thank you very much
