### ISSUE TITLE
[Support] Unable to find physical bundle file, for further detection by Karma test runner

### ISSUE THREAD

**Issue by Kamilius** [webpack/webpack-dev-server#453]
I'm trying to integrate Karma to a local dev environment, which is running with WebpackDevServer:

```javascript
const server = new WebpackDevServer(webpack(webpackConfig), {
    contentBase: 'dist',
    hot: true,
    stats: {
      colors: true,
    },
  });
```

The thing is, that environment works great, while making code changes. But when I look into 'dist' directory, it stays clear of any files. Is there any chance to output everything what devServer serves, physically each time?

**Comment by SpaceK33z** [comment]
This is because webpack-dev-server serves files from memory. It can't output these to disk, and will not do that. Also see [this comment](https://github.com/webpack/webpack-dev-server/issues/62#issuecomment-58856998), which explains why this wouldn't make sense.
