### ISSUE TITLE
Enabling the experimental option experiments.buildHttp will cause HMR to not work.

### ISSUE THREAD

**Issue by LP1994** [webpack/webpack-dev-server#4532]
### Actual Behavior
Enabling the experimental option experiments.buildHttp will cause HMR to not work.

### Expected Behavior
Enable experimental option experiments.buildHttp. HMR also works fine.

### How Do We Reproduce?
1、I've provided a small library of examples to reproduce the problem:
https://github.com/LP1994/experiments_buildHttp_hmr.git
2、After downloading the project, go to the project root directory and execute the commands in the following order:
1)webpack init
2)npm run dev

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
webpack version:
webpack 5.74.0

Node.js version:
node 18.6.0

Operating System:
Windows 11 Professional Edition 21H2 22000.832

Additional tools:
npm 8.15.1

My demo library:
https://github.com/LP1994/experiments_buildHttp_hmr.git

**Comment by LP1994** [comment]
However, I found that if you manually import 'webpack/hot/dev-server.js' and 'webpack-dev-server/client/index.js' into the entry point, you can use both experiments.buildHttp and HMR.

**Comment by LP1994** [comment]
> However, I found that if you manually import 'webpack/hot/dev-server.js' and 'webpack-dev-server/client/index.js' into the entry point, you can use both experiments.buildHttp and HMR.

However, it should not be done as I mentioned above, because webpack already provides the hot option and the HMR plugin to enable HMR. And this obviously goes against the "out of the box" philosophy of webpack 5.

**Comment by alexander-akait** [comment]
Please do not duplicate, original issue created in webpack, so wait for answer there, thank you

We will answer near future

**Comment by LP1994** [comment]
> Please do not duplicate, original issue created in webpack, so wait for answer there, thank you
> 
> We will answer near future

OK,Thanks in advance, I will go to webpack to add more details for your reference.
