### ISSUE TITLE
urls with dots are treated as fileNames

### ISSUE THREAD

**Issue by matanwerbner** [webpack/webpack-dev-server#454]
Hi,

we have urls such as 
http://localhost:8080/search/192.168.1.0

on browser refresh, dev server is trying to serve a file, rather then serving the content base.

can you add a flag for ignoring dots in the url? ty

**Comment by ChrisJamesC** [comment]
A possible fix is in #303

**Comment by ChrisJamesC** [comment]
An alternative fix is to replace the historyApiFallback=true line in the server config with:

```
historyApiFallback: {
    rewrites: [
        {
            from: /^\/app\/.*$/,
            to: function() {
                return 'index.html';
            }
        }
    ]
},
```
This will make any page with a dot in the /app path to be redirected to index.html (as it should be if it were not considered as a file)
See https://github.com/bripkens/connect-history-api-fallback#rewrites for more info

**Comment by SpaceK33z** [comment]
@matanwerbner, did the above fix your issue?

**Comment by SpaceK33z** [comment]
Closing this issue, since it is out of our control, and `connect-history-api-fallback` has a config option to fix this (see above).
