### ISSUE TITLE
What to "Graduate" to after development is stable and ready to integrate with backend project?

### ISSUE THREAD

**Issue by mathieusteele** [webpack/webpack-dev-server#455]
The documentation clearly states:

THIS SERVER SHOULD BE USED FOR DEVELOPMENT ONLY!
DO NOT USE IT IN PRODUCTION!

Looking to incorporate the javascript code in html page served by backend framework of choice- in my case Python (Django). Why do I need to run the dev server in order for my app to work? Shouldn't the compiled app be able to run locally or anywhere as an html file and javascript file?

**Comment by bebraw** [comment]
You should set up a separate configuration for production usage (no HMR, minified etc.). I go through basic techniques [here](http://survivejs.com/webpack/introduction/).

You can use whatever solution you are comfortable with for serving the build result. You can even generate a simple *index.html* with [html-webpack-plugin](https://www.npmjs.org/package/html-webpack-plugin). Alternatively you can achieve the same by utilizing webpack stats feature. That provides you enough information for writing references to your template.

**Comment by mathieusteele** [comment]
Thank you!
