### ISSUE TITLE
content-base with proxy

### ISSUE THREAD

**Issue by brusand** [webpack/webpack-dev-server#456]
Hi

u use webpackdevserver with the --content-base and --host options, but how can i set the proxy for api backends ?
wich is mininal config file withiout webpack build ?

thanks
Bruno

**Comment by MarkPieszak** [comment]
Please use stackoverflow for such issues as this is not an issue with webpack-dev-server itself.

**Comment by SpaceK33z** [comment]
The documentation provides some [nice examples](https://webpack.github.io/docs/webpack-dev-server.html#proxy) on how to handle this. If you still have this issue after reading the documentation, feel free to re-open.
