### ISSUE TITLE
Open chrome in same tab

### ISSUE THREAD

**Issue by malcolm-kee** [webpack/webpack-dev-server#4573]
### Feature Proposal

Reuse chrome tab for `--open` options, by using [this script](https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openChrome.applescript) from create-react-app.

### Feature Use Case

This is arguably better DX compared to always open a new tab, based on the observation where both CRA and Vite also implement the same behavior.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

I'm happy to create a PR on this, provided this is something desired.

**Comment by snitin315** [comment]
PR welcome. Duplicate https://github.com/webpack/webpack-dev-server/issues/1400

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-dev-server/issues/1400
