### ISSUE TITLE
webpack-dev-server proxy dosen't work

### ISSUE THREAD

**Issue by Authorlove** [webpack/webpack-dev-server#458]
I want to proxy /v1/** to http://myserver.com,  and here is my devServer configration,
```javascript
 devServer: {
        historyApiFallBack: true,
        // progress: true,
        hot: true,
        inline: true,
        // https: true,
        // port: 8081,
        contentBase: path.resolve(__dirname,'public'),
        proxy: {
            '/v1/**': {
                target: 'http://api.in.uprintf.com/',
                secure: false
                // changeOrigin: true
            }
        }
    },
```
but it results in 404 not found error, and here is the response,
```
Request URL:http://localhost:8080/v1/address/school?keyword=scut&_=1460968888999
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:8080
Response Headers
view source
connection:close
content-encoding:gzip
content-type:text/html
date:Mon, 18 Apr 2016 08:41:34 GMT
server:nginx/1.4.6 (Ubuntu)
transfer-encoding:chunked
X-Powered-By:Express
```
It seems to proxy to my ubuntu nginx server, since i use mac os locally， but i don't use express in my remote server.

**Comment by Authorlove** [comment]
when i set proxy option: `changeOrigin: true`, it works.
From the node-http-proxy's document, it says,  
'changeOrigin: true/false, Default: false - changes the origin of the host header to the target URL'. Does the changeOrigin option depend on the remote backend server framework?

**Comment by MikaAK** [comment]
@Authorlove try  
```javascript
proxy: [{
      path: `/v1/*`,
      target: 'http://api.in.uprintf.com'
}],
````

**Comment by MarkPieszak** [comment]
Have you had any luck getting HMR to work through a proxy? I kept noticing HMR was still sending through the original port when I tried this :(

**Comment by fractalf** [comment]
+1
Can't get proxy to work, no matter what i put in proxy options.

Server.js:
````
options.proxy.forEach(function (proxyOptions) {
	proxyOptions.ws = proxyOptions.hasOwnProperty('ws') ? proxyOptions.ws : true;
	app.all(proxyOptions.path, function (req, res, next) {
		var bypassUrl = typeof proxyOptions.bypass === 'function' ? proxyOptions.bypass(req, res, proxyOptions) : false;
		if (bypassUrl) {
			req.url = bypassUrl;
			next();
		} else {
			if(typeof proxyOptions.rewrite === 'function') proxyOptions.rewrite(req, proxyOptions);
			if (proxyOptions.host) {
				req.headers.host = proxyOptions.host;
			}
			proxy.web(req, res, proxyOptions, function(err){
				var msg = "cannot proxy to " + proxyOptions.target + " (" + err.message + ")";
				this.sockWrite(this.sockets, "proxy-error", [msg]);
				res.statusCode = 502;
				res.end();
			}.bind(this));
			if (proxyOptions.configure) {
				proxyOptions.configure(proxy);
			}
		}
	}.bind(this));
}.bind(this));
````

The code inside app.all doesn't seem to run at all..
Would be great with a **working example**

**Comment by busbyk** [comment]
I'm experiencing a potentially related issue. I'm trying to use the rewrite option and the function I pass it does not seem to fire. I tested the code separately to make sure the function wasn't just working incorrectly and the code works. 

If the above comment is true and the code inside of app.all isn't firing that would explain my issue. But, definitely not ideal...

**Comment by Authorlove** [comment]
Because I use nginx as my server, it needs Host header filed, so when i set changeOrigin: true, it works. And my case is done.

**Comment by vinhlh** [comment]
Yo guys, let's try to change * to **. It works for me with latest `webpack-dev-server` (latest commit).
Check `wildcard path matching` in https://github.com/chimurai/http-proxy-middleware

**Comment by KingScooty** [comment]
@vinhlh this saved me! Wish there was an upgrade doc for webpack 2.0.

**Comment by ljwagerfield** [comment]
@vinhlh also worked for me.

Neither of the following worked:
`proxy: {'*': 'http://localhost:3000'}`
`contentBase: {target: 'http://localhost:3000'}`

But this does: `proxy: {'**': 'http://localhost:3000'}` 

👍

**Comment by zbowhay** [comment]
May be helpful for some,
I was able to get my proxy to a express server by using this config:
`proxy:{
            '/api/**': {
                target: 'http://localhost:4001',
                secure: false,
            }
        }
`

in my case adding http:// and /** resolved my issues.

**Comment by SpaceK33z** [comment]
@Authorlove can this be closed?

**Comment by pgangwani** [comment]
Although this is closed issue, Need some guidance.

I dont know how much I am screwing up. Can any one of you help me in my configuration, I wish to 
proxy all "/api/**" request to "jsonplaceholder.typicode.com". For example: "localhost:3001/api/users/1" to "jsonplaceholder.typicode.com/users/1"
My configurations : 
`proxy: {
'/api/**': { 
                // target: "http://localhost:9000",
                target: {
                    'host': 'jsonplaceholder.typicode.com',
                    'port': 80,
                    'protocol': 'http:'
                }, 
                secure: false, 
                changeOrigin: true, 
                                pathRewrite: {
                    '^/api': ''
                }
}`


I am just suferring from trail of 404s.
Kindly response if you can identify the issue.

**Comment by SpaceK33z** [comment]
@pgangwani, Did you try without the trailing slash in `/api/` (so `/api`)? In all the examples in [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware), I see they do it like that, so it could be that with the trailing slash it only proxies if the url has a exact match.

**Comment by pgangwani** [comment]
That returns 404 .
I guess same path is passed to target path '/api' should be removed before sending to target.
Any configuration ?

**Comment by SpaceK33z** [comment]
@pgangwani, yeah `pathRewrite` is for that, but you already have that in your config. Are you using `webpack-dev-server@1.15.0`?

**Comment by pgangwani** [comment]
No. webpack@2.1.0-beta.6

**Comment by pgangwani** [comment]
Can any one else help?

**Comment by bivvo** [comment]
@pgangwani 
Try this. Was able to get this to run.

```
proxy:{
      '/api/*' : {
        target: 'http://jsonplaceholder.typicode.com/', 
        changeOrigin: true,
        pathRewrite: {
        '^/api': ''
        }
      }
    }
```

**Comment by pgangwani** [comment]
Not working.
I think there is some other issue not a  configuration.

**Comment by BrendanDougan** [comment]
My previously working for 6 months config has stopped working on an npm install. webpack-dev-server 1.15,0

**Comment by SpaceK33z** [comment]
@pgangwani, I copy/pasted @bivvo's code in the `example/webpack.config.js` of this repo to test this, and then browsed to `http://localhost:8080/api/users`. It worked. With what url are you testing this?

**Comment by johnelliott** [comment]
Thanks @vinhlh.

For others fiddling with this, here's what I ended up with to get hot module reloading working and still able to hit my API server:

I began here: https://github.com/chimurai/http-proxy-middleware#context-matching, looking at pattern matching:

> * wildcard path matching

> For fine-grained control you can use wildcard matching. Glob pattern matching is done by micromatch. Visit micromatch or glob for more globbing examples.

Initially it appeared that I could specify a quoted array as the key for the proxy property of the webpack config e.g. `"['/a', '/b']": {target, secure, etc}` to match `/a` and `/b/`, but this turned out not to be the case and brace expansion was the way.

My solution was just to use whatever bits of the `glob` library would work in the webpack config. In https://www.npmjs.com/package/glob#glob-primer I used two things, the `!` and the `{}` brace expansion. 

`{}` brace expansion:
```
!/**/*.css
!/**/*.js
!/**/*.hot-update.json
```
Then, according to the `glob` docs:
> !(pattern|pattern|pattern) Matches anything that does not match any of the patterns provided.

So any path not ending in these three extensions would match and thus be proxied.

```js
  devServer: {
    // progress: true,
    hot: true,
    inline: true,
    // https: true,
    // port: 8081,
    contentBase: path.resolve(__dirname,'public'),
    proxy: {
      '!/**/*.{css,js,hot-update.json}': {
        target: 'http://localhost:3000',
        secure: false
        // changeOrigin: true
      }
    }
  },
```

There's surely a better way, but this is working for now.

**Comment by zcoding** [comment]
webpack@1.14.1
```json
{"changeOrigin": true}
```
works for me

**Comment by MPDroid** [comment]
webpack-dev-server: 2.1.0-beta.9, webpack: 2.1.0-beta.25 and express for backend api server

Objective is to redirect api requests from localhost:3000/api/*  to localhost:3030/*. Followed the example in this repository as @SpaceK33z suggested.


It worked for me with the following config (pathRewrite) :
         proxy: {
        "/api/**": {
        target: "http://localhost:3030/",
        _pathRewrite: {
					"^/api": ""
				}_
      }

**Comment by mrsufgi** [comment]
@mproid that config worked for me too! 

```js 
var apiProxy = proxy('/api/**', {
    target: 'https://api.instagram.com/v1/',
    pathRewrite: {
      "^/api": ""
    },
    changeOrigin: true,
    logLevel: 'debug',
  });
```

pathRewrite is a must here since we don't wont to prefix requests with an actual '/api' 
Thanks

**Comment by YuyangWitness** [comment]
@bivvo 
Thank you very much, I have solved this problem finally.
when I add `pathRewrite`, this problem was solved!!!

**Comment by erosenberg** [comment]
I'm unable to get any of these options to work 👎 
My main server that serves HTML/ejs is: localhost:3000
My `webpack-dev-server` is localhost:9000

Here is my config at the moment:

```
const DEV_SERVER_PORT = 9000;
const DEV_HOST = 'http://localhost';

const config = _.merge(baseConfig, {
  entry: {
    bundle: [
      `webpack-dev-server/client?${DEV_HOST}:${DEV_SERVER_PORT}`,
      'webpack/hot/only-dev-server',
      'react-hot-loader/patch',
      paths.indexPath,
    ],
  },
  output: {
    filename: 'bundle.js',
    path: paths.buildPath,
    publicPath: '/static/build/',
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: [paths.nodeModulesPath],
      loader: 'babel-loader',
    }],
  },
  devtool: 'eval-source-map',
  devServer: {
    contentBase: paths.buildPath,
    // publicPath: `http://lopcalhost:3000/${path.buildPath}`,
    publicPath: '/static/build/',
    hot: true,
    host: '0.0.0.0',
    port: DEV_SERVER_PORT,
    historyApiFallback: true,
    proxy: {
      // '/static/build/**': 'http://[::1]:3000/static/build',
      '**': 'http://[::1]:3000/static/build',
      secure: false,
      changeOrigin: true,
    },
  },
  resolve: {
    extensions: ['.js', '.json'],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
    new HtmlWebpackPlugin({
      template: path.resolve(paths.staticPath, 'index.ejs'),
    }),
  ],
});
```

My HTML markup contains a script tag that is looking for a local `bundle.js` file.

```
<script src="/static/build/bundle.js"></script>
```

What I would like and expect to happen is when I go to request `localhost:9000/static/build/bundle.js/` I am proxied to `localhost:3000/static/build/bundle.js`.

What am I missing here? I'm also using the following:

OSX
` "webpack": "^3.5.5",`
` "webpack-dev-server": "^2.7.1",`

**Comment by granmoe** [comment]
I've tried every combination here and none are working for me. Here's my config:

```javascript
const webpack = require("webpack");
const path = require("path");

const IS_DEV = process.env.NODE_ENV === "development";

module.exports = {
	devtool: IS_DEV ? "inline-source-map" : "eval",
	entry: "./src/index.js",
	output: {
		filename: "app.js",
		path: path.resolve(__dirname, "dist")
	},
	resolve: {
		modules: [
			path.resolve(__dirname, "src"),
			"node_modules"
		],
		extensions: [".json", ".js"]
	},
	module: {
		rules: [
			{
				test: /\.html$/,
				exclude: /node_modules/,
				loader: "ractive-loader"
			}, {
				test: /\.js$/,
				exclude: /node_modules/,
				loader: "babel-loader"
			}, {
				test: /\.css$/,
				exclude: /node_modules/,
				loaders: [
					"style-loader",
					"css-loader"
				]
			}
		]
	},
	devServer: {
		contentBase: "./dist",
		hot: true,
		proxy: {
			"/ext_api/**": {
				target: "http://foo.bar/" // obscured to hide my employer
			}
		}
	},
	plugins: [new webpack.HotModuleReplacementPlugin()]
};
```

**Comment by tarunjuneja** [comment]
Just to explicit - In my case mistakenly i have placed proxy at the root however i was suppose to keep it in devServer 

here is my final configuration
  devServer: {
    outputPath: path.join(__dirname, "dist"),
    historyApiFallback: true,
    stats: "minimal",
    proxy: {
      "/rest/**":  {
        target: "https://10.98.0.1/",
        secure: false
      }
    },    
  }

**Comment by anson-GH** [comment]
npm install webpack -g
npm install vue-cli -g
npm install
npm run dev

after run these restart your pc, sometimes need to fresh all again.

**Comment by luddens** [comment]
Ugh. None of this works:
`  devServer: {
    index: '', // specify to enable root proxying
    host: '...',
    contentBase: '...',
    proxy: {
      '/api': {
        context: () => true,
        target: 'http://localhost:3000',
        changeOrigin: true,
        pathRewrite: {
        '^/api': ''
        },
        secure: false
      }
    },`

**Comment by johnelliott** [comment]
@luddens what are you trying to do here?

This is more a matter of understanding and configuring https://github.com/chimurai/http-proxy-middleware than anything about web pack or this dev server. [Here](https://github.com/chimurai/http-proxy-middleware#context-matching) under path matching I see something similar to your example with `/api`. The quickest way forward was trying lots of things, even ones that seemed a bit silly to understand how it all worked before going to my particular problem.

**Comment by davidgolden** [comment]
@wulichenyang Yep that did it for me.

Removed `app.all('/', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    next();
});` from my `server.js`

My webpack config looks like this:
`proxy: {
            '/api': {
                target: 'http://localhost:5000',
                pathRewrite: {'^/api': ''},
            }
        }`

I'm on webpack-dev-server version 3.2.1

**Comment by imzubair10** [comment]
This should work:

```
devServer: {
    contentBase: path.join(__dirname, "/dist"),
    historyApiFallback: true,
    publicPath: '/',
    inline: true,
    port: 8080,
    stats: { colors: true },
    hot: true,
    proxy: {
      '/api/**': {
        target: 'http://localhost:44310',
        pathRewrite: { '^/api': '' },
        secure: false,
        changeOrigin: true
      }
    }
}
```

**Comment by 9jaswag** [comment]
I'm facing same problem on a project. I have tried a lot of different config options and none seem to be working for me.

```
- Node Version: v10.15.0
- NPM Version: 6.4.1
- webpack Version: 4.42.1
- webpack-dev-server Version: 3.10.3
```

Wepback config: https://gist.github.com/9jaswag/8f18ca33f2c89132610eb04deffae098

The request keeps going to http://localhost:8080/api/users/signin instead of http://localhost:3000/api/users/signin

**Comment by Jammmes** [comment]
Hi @pgangwani! If you resolved this issue, could you show me the solution, please?

**Comment by tarunjuneja** [comment]
Hey what's the version of webpack you are using.
I would say answer will depend on that.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Jammmes** [comment]
Hi,
I'm using webpack v. 4.35.3
webpack-dev-server v. 3.7.2

,Regards
Evgenii Verhinin

**Comment by aamustapha** [comment]
I'm also having this trouble...
```
devserver: {
  proxy: {
    '/': 'https://app.staging.com',
    changeOrigin: true
  }
}
```

But I still get `DEPTH_ZERO_SELF_SIGNED_CERT`
