### ISSUE TITLE
Should not try to proxy client websockets connection

### ISSUE THREAD

**Issue by zdm** [webpack/webpack-dev-server#4588]
### Actual Behavior

I want to proxy everything to the api backend, including websockets connections.
So, I am using following proxy configuration:
```
proxy: {
    "/": {
                    "target": "http://devel/",
                    "ws": true,
                },
}
```
This works fine for http and websockets.
But with one problem - it also tries to proxy webpack client websockets connection `ws://localhost/ws`.

### Expected Behavior

I am expecting, that webpack client connections will be excluded from proxy.

### How Do We Reproduce?

Please, use config above and you will see, that webpack ws connection is not established, because it tries to proxy it to the backend.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 2.66 GB / 15.78 GB
  Binaries:
    Node: 18.9.1 - d:\devel\node\node.exe
    npm: 8.19.2 - ~\.npm\npm.cmd
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.50)
  Packages:
    babel-loader: ^8.2.2 => 8.2.5
    webpack: ^5.56.0 => 5.74.0
    webpack-bundle-analyzer: ^4.4.2 => 4.6.1
    webpack-cli: ^4.8.0 => 4.10.0
    webpack-dev-server: ^4.3.0 => 4.11.1
```

**Comment by alexander-akait** [comment]
You need to filter in this case, please use to setup this https://github.com/chimurai/http-proxy-middleware#pathfilter-string-string-glob-glob-function

**Comment by zdm** [comment]
This not works, `pathFilter` is just not called.

```
proxy: {
"/": {
                    "target": "http://devel/",
                    "ws": true,
                    pathFilter (path) {
                        console.log( "---", path )
                    }
}
```

**Comment by zdm** [comment]
`bypass` function also not called.

**Comment by alexander-akait** [comment]
You can't use `target` and `pathFilter` options https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L2178, please use `router`

**Comment by alexander-akait** [comment]
Or just avoid using `target` and `route`

**Comment by zdm** [comment]
this works:
```
{
                "ws": true,
                "target": this.#devServerProxyUrl,
                context (path) {
                    if (path === "/ws") return false;
                    // console.log( "---", path );

                    return true;
                },
```

But this is not documented. I guessed.

**Comment by alexander-akait** [comment]
Most of abilities of proxy are not documented because it is out of scope, we just create `createProxyMiddleware` and pass your options - https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L2175, but yes, feel free to improve now docs

**Comment by zdm** [comment]
Ok, thank, 
My problem is solved.
