### ISSUE TITLE
 [webpack-dev-server] [HPM] ECONNRESET: Error: socket hang up

### ISSUE THREAD

**Issue by Nick-Hopps** [webpack/webpack-dev-server#4602]
### Actual Behavior

My devServer config: 

```
const devServerOptions = {
    setupMiddlewares: (middlewares, devServer) => {
      if (!devServer) {
        throw new Error('webpack-dev-server is not defined');
      }

      devServer.app.get('/mock/:name', (req, res) => {
        const filePath = path.join(cwd, 'mock', req.params.name);
        setTimeout(() => {
          res.sendFile(filePath);
        }, 1000);
      });

      middlewares.unshift({
        path: '/adc-studio-ui',
        middleware: (req, res, next) => {
          ...
        },
      });

      return middlewares;
    },
    host: host,
    port: port,
    proxy: [
      {
        context: [...],
        target: 'https://' + devEnv.addr,
        changeOrigin: true,
        secure: false,
        ws: true,
        logLevel: 'debug',
        headers: {
          Cookie: '',
        },
      }
    ],
    client: {
      logging: 'error',
      overlay: false,
    },
    static: {
      directory: webpackConfigBase.resolve('dev'), 
      watch: true,
    },
    allowedHosts: 'all',
    hot: true, 
  }
```

After executing and load data from server (via proxy), it shows:

```
<e> [webpack-dev-server] [HPM] ECONNRESET: Error: socket hang up
<e>     at connResetException (internal/errors.js:639:14)
<e>     at TLSSocket.socketCloseListener (_http_client.js:449:25)
<e>     at TLSSocket.emit (events.js:412:35)
<e>     at net.js:686:12
<e>     at TCP.done (_tls_wrap.js:564:7) {
<e>   code: 'ECONNRESET'
<e> }
```

However this error seems not affecting the app's functions.

### Expected Behavior

Error meesage not occur.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 16.74 GB / 31.78 GB
  Binaries:
    Node: 14.20.0 - ~\scoop\apps\nodejs14\current\node.EXE
    npm: 6.14.17 - ~\scoop\apps\nodejs14\current\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.19041.1566
  Packages:
    babel-loader: ^8.2.5 => 8.2.5
    cache-loader: ^4.1.0 => 4.1.0
    case-sensitive-paths-webpack-plugin: ^2.4.0 => 2.4.0
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    copy-webpack-plugin: ^6.4.1 => 6.4.1
    css-loader: ^5.2.7 => 5.2.7
    file-loader: ^6.2.0 => 6.2.0
    friendly-errors-webpack-plugin: ^1.7.0 => 1.7.0
    html-webpack-plugin: ^4.5.2 => 4.5.2
    less-loader: ^7.3.0 => 7.3.0
    postcss-loader: ^4.3.0 => 4.3.0
    speed-measure-webpack-plugin: ^1.5.0 => 1.5.0
    thread-loader: ^3.0.4 => 3.0.4
    url-loader: ^4.1.1 => 4.1.1
    vue-loader: ^15.10.0 => 15.10.0
    vue-style-loader: ^4.1.3 => 4.1.3
    webpack: 4.46.0 => 4.46.0
    webpack-bundle-analyzer: ^4.6.1 => 4.6.1
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-dev-server: ^4.11.1 => 4.11.1
    worker-loader: ^3.0.8 => 3.0.8

**Comment by alexander-akait** [comment]
> How Do We Reproduce?

Please fill out it, I will reopen

**Comment by Nick-Hopps** [comment]
Ok, I'll check the server side, thx.

**Comment by Nick-Hopps** [comment]
Found the problem, I have to add some params to opening url to tell backend I've logged in.

**Comment by kciy** [comment]
> Found the problem, I have to add some params to opening url to tell backend I've logged in.

Hey could you maybe describe what exactly you added for those who have the same problem :)
