### ISSUE TITLE
no reload with index.js implicit imports

### ISSUE THREAD

**Issue by cyberxndr** [webpack/webpack-dev-server#462]
Live reload doesn't work in case when component is imported implicitly from the **index.js** file.

In this case live reload for Menu source file works:
`import Menu from '../components/menu/index.js'`

And in this case it doesn't:
`import Menu from '../components/menu/'`

Seems like file should be imported directly in order to be watched by webpack-dev-server

**Comment by SpaceK33z** [comment]
I just tested this, and it does seem to work (webpack-dev-server ^2.1.0-beta, OS X).

- What OS are you using?
- What version of the dev-server?
- Does it work correctly after a page-refresh, or after killing and starting the dev-server process again?

**Comment by cyberxndr** [comment]
I can't reproduce this at the moment (@1.15.0). Both scenarios seems to work fine. I'll reopen this, if there will be additional details.
