### ISSUE TITLE
it shows i don't installl webpack-dev-server even i have installed it in devdependence!

### ISSUE THREAD

**Issue by lgr-123** [webpack/webpack-dev-server#4620]
For using 'serve' command you need to install: 'webpack-dev-server' package
[webpack-cli] Would you like to install 'webpack-dev-server' package? (That will run 'npm install -D webpack-dev-server')

- [ ] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js
```

```js
// additional code, remove if not needed.
```

**Comment by alexander-akait** [comment]
Please install `webpack-dev-server` to use the `serve` command
