### ISSUE TITLE
内部依赖不支持ie

### ISSUE THREAD

**Issue by huangpiqiao** [webpack/webpack-dev-server#4632]
### Feature Proposal

sockjs-client@1.6.1不支持ie，但是他们不怎么维护，是否可以把内部依赖的sockjs-client "^1.5.0"改成sockjs-client "~1.5.0"

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
