### ISSUE TITLE
SockJS crashes session

### ISSUE THREAD

**Issue by tquetano-r7** [webpack/webpack-dev-server#465]
I am getting frequency crashes due to an apparent SockJS session timeout:

```
/home/tquetano/git/platform-js/node_modules/webpack-dev-server/node_modules/sockjs/lib/trans-websocket.js:157
      return this.session.close(3000, 'No response from heartbeat');
                         ^

TypeError: Cannot read property 'close' of null
    at WebSocketReceiver.heartbeat_timeout (/home/tquetano/git/platform-js/node_modules/webpack-dev-server/node_modules/sockjs/lib/trans-websocket.js:157:26)
    at null._onTimeout (/home/tquetano/git/platform-js/node_modules/webpack-dev-server/node_modules/sockjs/lib/trans-websocket.js:75:24)
    at Timer.listOnTimeout (timers.js:92:15)

npm ERR! Linux 4.4.0-18-generic
npm ERR! argv "/home/tquetano/.nvm/versions/node/v4.2.2/bin/node" "/home/tquetano/.nvm/versions/node/v4.2.2/bin/npm" "run" "dev"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! platform@4.0.0 dev: `NODE_ENV=development ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the platform@4.0.0 dev script 'NODE_ENV=development ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress'.
npm ERR! This is most likely a problem with the platform package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress
npm ERR! You can get their info via:
npm ERR!     npm owner ls platform
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tquetano/git/platform-js/npm-debug.log

```

Is there a way to configure to increase the timeout, or at least check for the existence of the session object before attempting to use its close property? This is happening very frequently, in some cases in as little as a few minutes after very basic usage

**Comment by Igogrek** [comment]
Having exact same issue after migrating to another machine. In my case it crashes right after the initial loading (which works absolutely fine).

**Comment by tquetano-r7** [comment]
Yeah no dice for me... it still crashes with regularity.

**Comment by orzechowskid** [comment]
I'm seeing this crash really frequently as well.  I'm using webpack-dev-server 1.14.1 and node 4.2.2 on Ubuntu 14.04 LTS (x86_64 2.16.0-70-generic).  Setting the devServer options in my webpack config file didn't seem to make a difference.

**Comment by skozin** [comment]
I'm seeing this too, several times an hour; makes `webpack-dev-server` completely unusable.

Here is the related SockJS issue: https://github.com/sockjs/sockjs-node/issues/201. They say it's fixed in sockjs-node v0.3.17.

**Comment by csaintc** [comment]
Getting the same issue

**Comment by byCedric** [comment]
Same problem over here...

**Comment by skozin** [comment]
@csaintc @byCedric btw, removing your `node_modules` directory and doing fresh `npm install` should fix the issue as well, as the new `sockjs` version `0.3.17` matches the semver `^0.3.15` specified in webpack-dev-server's package.js.

I suggest updating semver in dev-server's package.json only to enforce installation of the new sockjs version in all cases, e.g. behind a caching npm proxy.

**Comment by byCedric** [comment]
I did update it just before lunch, and it didn't crash a single time until now! So I guess the new version worked like a charm! Thanks for the heads up @skozin

**Comment by SpaceK33z** [comment]
@tquetano-r7, do you still have this issue?

**Comment by tquetano-r7** [comment]
Nope, sorry I should have closed this a while ago.
