### ISSUE TITLE
Nested paths do not work on Windows

### ISSUE THREAD

**Issue by ljani** [webpack/webpack-dev-server#466]
`GET /maps.json HTTP/1.0` works fine, but `GET /nested/maps.json HTTP/1.0` does not work at all on Windows. The reason seems to be that something ([`webpack`](https://github.com/webpack/webpack), [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware) or [`CopyWebpackPlugin`](https://github.com/kevlened/copy-webpack-plugin)?) in the pipeline is outputting backslashes instead of forward slashes:
![Screenshot](http://i.imgur.com/TCk5nw7.png)
In the screenshot above, `details` is a file copied to the memory filesystem using [`CopyWebpackPlugin`](https://github.com/kevlened/copy-webpack-plugin) (for mocking API access for now). As a workaround I can configure `express` to serve the files from the original static directory:

```
config.devServer = {
    setup: app => app.use("/maps", require("express").static(path.resolve(__dirname, "src/static/maps/")))
};
```

EDIT: `GET /nested\maps.json HTTP/1.0` does not work either

**Comment by SpaceK33z** [comment]
I tested if the nested paths get created correctly in Windows, and it works. Did some digging, and it turns out this was an issue in copy-webpack-plugin; https://github.com/kevlened/copy-webpack-plugin/issues/29.
