### ISSUE TITLE
Node-forge license issue as it is installed as dependency

### ISSUE THREAD

**Issue by AshishUpadhyayCivica** [webpack/webpack-dev-server#4665]
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

I am facing a problem of licensing((BSD-3-Clause OR GPL-2.0)) when I am using webpack-dev-server.
The issue is regarding one of the package that is installed as part of dependency.
Consider below

![node-forge license dependency](https://user-images.githubusercontent.com/119533725/205044897-551bab75-185b-418c-b9fc-76782bd95481.jpg)

So I am installing webpack-dev-server and all of its dependent packages are installed under MIT license except node-forge.
My security scan detects this as problem as we don't want to use BSD-3-Clause license.

I expect the node-forge should be removed as part of dependency of @nrwl/angular as this is creating lot of problems of licensing whilst using webpack-dev-server.

**Comment by alexander-akait** [comment]
Please open an issue in `node-forge` or `selfsigned` (because they are under MIT and use non MIT dependency), we can't refuse to use `selfsigned` and implement alternative solution (we don't have developers to do it), sorry, we can't solve it here, feel free to feedback
