### ISSUE TITLE
Cannot GET /data

### ISSUE THREAD

**Issue by ecSpl01t** [webpack/webpack-dev-server#471]
Hello!
I have a problem with server.
When I did refresh page and I get to 'Cannot GET /data', I searched in Internet and I found this comment
```
app.route('/*').get(function(req, res) { 
    return res.sendFile(path.join(config.root, 'index.html')); 
});
```
but I dont know how to change, where is the change this ?!
maybe may to add some line in webpack.config.js to fixed this problem ?

ps. app in Angular

**Comment by TheLarkInn** [comment]
This doesn't appear to be webpack-dev-server related.
