### ISSUE TITLE
constant 100% CPU usage with node v6.0.0

### ISSUE THREAD

**Issue by 1000hz** [webpack/webpack-dev-server#472]
Not sure if this is happening to anyone else, but when I try to run webpack-dev-server with node 6, it pegs my cpu until I kill the process. Older versions of node would only use 100% CPU during active compilations. This kills my battery life. It might also be related to a loader (I've got my suspicions about node-sass).

Anybody else running into this?

**Comment by mbroadst** [comment]
I'm more at like 20-35% steady cpu usage, still pretty awful. Only noticed when my lap started getting pretty hot 😄

**Comment by micky2be** [comment]
I have 100% of CPU with Node 5.x

**Comment by JeffAMcGee** [comment]
I'm seeing the same problem. I think it may be the same issue as https://github.com/webpack/webpack-dev-middleware/issues/40 .

**Comment by nathanmarks** [comment]
I had 135% CPU with Node v6.3 -- reinstalling `node_modules` helped a TON.

**Comment by thetalecrafter** [comment]
Changing the node major version probably trips up the native fsevents, so does it fall back to pulling badly? Reinstalling fixed it for me as well.

**Comment by SpaceK33z** [comment]
Also see https://github.com/webpack/webpack-dev-middleware/issues/40.

**Comment by gbakernet** [comment]
When I upgraded from node 6 to node 8, I had the same problem, excessive cpu usage.

Deleting `node_modules` and reinstalling was the solution.
