### ISSUE TITLE
version 2.0 issue with output.path

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack-dev-server#473]
I'm using `webpack@2.1.0-beta.6` (latest beta) and `webpack-dev-server@2.0.0-beta` and having trouble with `output.path`. I set `output.path` to a `dist` directory. When I run `webpack`. The bundle gets generated and placed in the `dist` directory as expected. But when I run `webpack-dev-server` the bundle is served from the root (as if no `output.path` is specified). Any ideas?

Here's [a repo](https://github.com/kentcdodds/es6-todomvc/tree/help/path) that reproduces the issue.

Here's the `webpack.config.js`:

```javascript
const {resolve} = require('path')
module.exports = {
  entry: './js/app.js',
  output: {
    filename: 'bundle.js',
    path: resolve(__dirname, 'dist'),
    pathinfo: true,
  },
  context: __dirname,
  devtool: 'eval',
  module: {
    loaders: [
      {test: /\.js$/, loader: 'babel!eslint', exclude: /node_modules/},
      {test: /\.css$/, loader: 'style!css'},
    ],
  },
}
```

Here's a gif demonstrating the issue:

![problem](https://cloud.githubusercontent.com/assets/1500684/14975418/b8845a16-10be-11e6-9333-c7704470ffdc.gif)

Let me know if you need any more information. I'm in the process of creating a video course about Webpack and I'll be using Webpack 2. I'd really like this to work. Help is definitely appreciated! Let me know if there's anything I can do! Happy to submit a PR with a little direction.

**Comment by kentcdodds** [comment]
Ok, so I [solved it](https://github.com/kentcdodds/es6-todomvc/commit/96667b0de785a58c4d6ed7842c2cc6aed625c171) by using `--content-base` as @xyyjk suggested, but was also required to add a `prebuild` and `prestart` script which deletes the `dist` and copies the `index.html` and `favicon.ico` over to the `dist` directory as well. I still feel like this behavior could be a bug though, so I'll leave the issue open.

**Comment by LegNeato** [comment]
Sounds like the same as https://github.com/webpack/webpack/pull/2376...

**Comment by kentcdodds** [comment]
Thanks for looking into this @LegNeato! Unfortunately it doesn't appear to solve my issue :-( https://github.com/kentcdodds/es6-todomvc/pull/2/files

**Comment by LegNeato** [comment]
Ah, darn...the symptoms sounded a bit similar :-(

**Comment by SpaceK33z** [comment]
Hey @kentcdodds, I think this is actually a dupe of #337. It seems that the CLI does something like `output.path = '/'`.

Can you confirm this?

**Comment by kentcdodds** [comment]
Hi @SpaceK33z! It's been a while, and I got it working eventually. I'm thinking this is a dupe of #337, so I'm going to close this one. Thanks!
