### ISSUE TITLE
Force quit of webpack-dev-server is not working on Cmd/Ctrl + C server is not quitting immediately, it took several seconds

### ISSUE THREAD

**Issue by shubham-latiyan** [webpack/webpack-dev-server#4732]
### Actual Behavior

On trying to kill the server, it is not quitting, it takes several seconds, while in message it says to force quite press Ctrl + C again but it's not working

### Expected Behavior

Just quits the server immediately, like in older versions it was working fine

### How Do We Reproduce?

Start any webpack-dev-server, and try to force quit it by pressing Cmd/Ctrl + C.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

https://user-images.githubusercontent.com/25565585/218048096-5168bcb4-aaa1-4ec1-ae28-10934a790002.mov

**Comment by alexander-akait** [comment]
Expected, because webpack-dev-server it trying to safely shutdown (some plugins can have opened files/resources, so we need to close them), you can press again and webpack-dev-server forcely close itself, feel free to feedback
