### ISSUE TITLE
environment variable to indicate the presence of hot-loading

### ISSUE THREAD

**Issue by AprilArcus** [webpack/webpack-dev-server#4733]
It would be convenient for Webpack to set an environment variable such as `process.env.WEBPACK_HOT`, akin to `process.env.WEBPACK_SERVE` and `process.env.WEBPACK_WATCH`, which would definitively indicate the availability of hot-loading (i.e. respecting both the `--no-hot` command-line argument and the `devServer: { hot: false }` config). This could then be read inside a babel config to enable or disable transforms relevant to hot loading.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Hard to implement without hacks (because we know you are using hot only from your configuration), please consider to use `--env`
