### ISSUE TITLE
[webpack-dev-server and webpack-dev-middleware] Enable use other than express

### ISSUE THREAD

**Issue by anonrig** [webpack/webpack-dev-server#4741]
### Feature Proposal

I recommend migrating to Fastify rather than using Express. The performance impact will be 7x (according to fastify readme), and I think it would be a lot beneficial for everybody.

### Feature Use Case

I didn't understand why I need to write my system information while proposing a feature, but...

```
  System:
    OS: macOS 13.2.1
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.3
```

**Comment by ScriptedAlchemy** [comment]
+1 on this, would improve startup times alot and the middleware apis are very similar if i recall. 

@alexander-akait - thoughts?

**Comment by snitin315** [comment]
We do have similar plans as mentioned in https://github.com/webpack/webpack-dev-server/issues/4303. However, this is not yet prioritized. We will gladly accept a PR.

**Comment by anonrig** [comment]
@alexander-akait Is there a specific reason to keep support for Express? I don't see the point of supporting Express.js since it might create unnecessary abstraction and maintenance burdens.

**Comment by alexander-akait** [comment]
@anonrig for dev server we don't need it, but webpack-dev-middleware should, because it is used for custom dev servers and we should support as much as possible, otherwise some developers will be angry :smile:

**Comment by silverwind** [comment]
Personally, I prefer to just use node core `http` with [router](https://github.com/pillarjs/router) for the routing. Great performance, and supports express-compatible middleware out of the box without the cruft that express itself brings 😉.

**Comment by alexander-akait** [comment]
@silverwind And you're right too, I think the best solution would be an abstract API, it takes time, but allow to use very fast and any other solutions. 

Somebody want to try it (I will help), I personally think this is the right direction.

**Comment by alexander-akait** [comment]
Fixed:
- webpack-dev-middleware supports all popular servers - https://github.com/webpack/webpack-dev-middleware?tab=readme-ov-file#other-servers
- webpack-dev-server supports `connect` compatibility HTTP server frameworks - https://github.com/webpack/webpack-dev-server/pull/5156

**Comment by alexander-akait** [comment]
Now we have tests only for express and connect I will add `router` and also add a http2 supports

**Comment by alexander-akait** [comment]
In the next major release we will migrate from `express` to `connect` or `router`

**Comment by alexander-akait** [comment]
Also will be great to have basic support of `honojs` (https://github.com/webpack/webpack-dev-server/issues/5258), because close it

**Comment by alexander-akait** [comment]
Fixed - https://github.com/webpack/webpack-dev-server/pull/5275/, also we have two examples - https://github.com/webpack/webpack-dev-server/tree/master/examples/app, anyway we supports any `connect` compatibility frameworks, also you can now setup any server own middlewares for them, it should works, if you need help feel free to feedback
