### ISSUE TITLE
App is reloaded continuously if proxy target server sends "Connection: close" header

### ISSUE THREAD

**Issue by nicolayr** [webpack/webpack-dev-server#475]
It the target of one or more proxy settings responds with a `Connection: close` header, the app is continuously reloaded even though no real problem exists.

This is caused by a bug in node-http-proxy that prevents `Connection: close` headers from being handled correctly (see https://github.com/nodejitsu/node-http-proxy/issues/1000). I've submitted a pull request to node-http-proxy, but I'm reporting it here as well since the problem will persist in webpack-dev-server until the dependency is updated.

See also #446.

**Comment by SpaceK33z** [comment]
Closing this issue since we're now using [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware), and WDS will no longer reload on a proxy error.
