### ISSUE TITLE
add an "afterSetup" option

### ISSUE THREAD

**Issue by oliverzy** [webpack/webpack-dev-server#476]
Right now, dev server has a "setup" option that allow some customization for express app. But it will be executed right before all other middlewares.

This feature request is add an "afterSetup" option that will be executed after all other middlewares.

**Comment by SpaceK33z** [comment]
A PR is welcome.

**Comment by SpaceK33z** [comment]
Thought about this some more, but I think it's not really necessary. If you want this, you can always pass `features: ["headers", "middleware", "proxy", "historyApiFallback", "magicHtml", "contentBase", "setup"]`.

This causes the `setup` option to be called on the end. An additional advantage is that you can exactly control when it is called.
