### ISSUE TITLE
Add webpack as optional peer dependency

### ISSUE THREAD

**Issue by hardfist** [webpack/webpack-dev-server#4776]
### Feature Proposal
Rspack use webpack-dev-server internally to compatible with devServer functionality but it will cause install warning because lack of webpack. see https://github.com/web-infra-dev/rspack/issues/2318
```sh
└─┬ @rspack/cli 0.1.1
  └─┬ @rspack/dev-server 0.1.1
    ├─┬ webpack-dev-server 4.11.1
    │ ├── ✕ missing peer webpack@"^4.37.0 || ^5.0.0"
    │ └─┬ webpack-dev-middleware 5.3.3
    │   └── ✕ missing peer webpack@"^4.0.0 || ^5.0.0"
    └─┬ @rspack/dev-middleware 0.1.1
      └─┬ webpack-dev-middleware 6.0.0
        └── ✕ missing peer webpack@^5.0.0
Peer dependencies that should be installed:
  webpack@">=5.0.0 <6.0.0"
```
we are wondering whether webpack-dev-server could list webpack as optional peer dependency to help avoid this warning in rspack

### Feature Use Case
support use webpack-dev-server in rspack
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
none

**Comment by alexander-akait** [comment]
Because now we have `rspack` let's do it, previously only webpack can be used, so it don't make sense :smile: , do you want to send a PR?
