### ISSUE TITLE
[feat] allow to filter runtime errors/errors/warning in overlay

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack-dev-server#4777]
The idea:
```
client: {
 errors?: boolean | (error: Error) => boolean
 warnings?: boolean | (warn: unknown) => boolean
 runtimeErrors?: boolean | (error: Error) => boolean
}
```

But let's implement boolean firstly, so you can disable it if you need, and then we can look at serilization

_Originally posted by @alexander-akait in https://github.com/webpack/webpack-dev-server/issues/4771#issuecomment-1472913070_

**Comment by malcolm-kee** [comment]
@alexander-akait I thought boolean already supported? Or the intention is to move it from `client.overlay.[messageType]` to `client.[messageType]`?

**Comment by alexander-akait** [comment]
@malcolm-kee Yeah, boolean already supports, I mean we need to allow to filter them, i.e. pass function to our client (serilized) and use (deserilize) in the client code, so some errors can be filtered without filly disable functional of `errors`/`warnings`/`runtimeErrors`, for example:
```
client: {
  runtimeErrors: (error) { 
   return !/Any custom/.test(error.message);
  }
}
```

**Comment by malcolm-kee** [comment]
@alexander-akait I would love to work on this but quite clueless how to do this, as all current options are JSON values. Do you have any pointer, such as plugins with similar capabilities that I can take inspiration from?

**Comment by CarryOnHxy** [comment]
Very looking forward to see this new feature when i saw the constant ```ResizeObserver``` problem on the screen!!

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-dev-server/pull/4813, release will be soon

**Comment by malcolm-kee** [comment]
This is now documented: https://webpack.js.org/configuration/dev-server/#overlay
