### ISSUE TITLE
Tries to connect to a websocket on the wrong port

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [webpack/webpack-dev-server#4791]
### Bug report
This happens when webpack thinks it's on a certain port (like `8080`) but the website is accessed through a different port (like `80`)

### Actual Behavior
Error connecting to websocket, have to reload to see changes

### Expected Behavior
- No errors
- When you change the code, the page updates without having to reload

### How Do We Reproduce?
Follow the instructions in https://github.com/ChocolateLoverRaj/webpack-dev-server-bug

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Celeron(R) CPU N3450 @ 1.10GHz
    Memory: 1.71 GB / 2.72 GB
  Binaries:
    Node: 18.15.0 - ~/.config/nvm/versions/node/v18.15.0/bin/node
    npm: 9.6.2 - ~/.config/nvm/versions/node/v18.15.0/bin/npm
  Packages:
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    webpack: ^5.76.3 => 5.76.3 
    webpack-cli: ^5.0.1 => 5.0.1 
    webpack-dev-server: ^4.13.1 => 4.13.1
```

**Comment by alexander-akait** [comment]
Sorry, output of scope dev server, you need manually to set port, we can't detect your `forward-tcp` util

**Comment by ChocolateLoverRaj** [comment]
> Sorry, output of scope dev server, you need manually to set a port, we can't detect your `forward-tcp` util

Why can't it just use `window.location.host`? In the browser side it can be coded to use `ws://${window.location.host}/ws`

**Comment by alexander-akait** [comment]
Because it is not safe, you can do it using option for a client, our logic is simple https://github.com/webpack/webpack-dev-server/blob/master/client-src/utils/createSocketURL.js#L75

**Comment by alexander-akait** [comment]
Just set `port: 0` for client https://webpack.js.org/configuration/dev-server/#websocketurl
