### ISSUE TITLE
configuration.plugins[11] misses the property 'apply'.

### ISSUE THREAD

**Issue by DinosaurCoder** [webpack/webpack-dev-server#4798]
### Bug report

When i use @sentry/webpack-plugin,webpack report an error:configuration.plugins[11] misses the property 'apply';But the plugin has apply methods and CleanWebpackPlugin can running;

### Actual Behavior

 WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.plugins[11] misses the property 'apply'.
   function
   -> The run point of the plugin, required method.

### Expected Behavior

code:
vue.config.js
      configureWebpack: {
        devtool: 'source-map',
        resolve: {
          extensions: ['.js', '.vue'],
          alias: {
            '@@': path.resolve(__dirname, './common'),
          },
        },
        plugins: [
          new SentryCliPlugin({
            include: [`../../dist/static/vue/open-platform/${projectName}/`],
            ignore: ['node_modules', 'vue.config.js'],
            cleanArtifacts: true,
          }),
          // new CleanWebpackPlugin(),
        ],
      },
package.json
{
  "name": "doctor-ecology",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "create": "node scripts/create.js",
    "serve": "node scripts/serve.js",
    "serve:dev": "sh scripts/serve.sh --dev",
    "serve:biz": "sh scripts/serve.sh --biz",
    "serve:prod": "sh scripts/serve.sh --prod",
    "serve:mock": "sh scripts/serve.sh --mock",
    "micro:dev": "sh scripts/start_micro.sh --dev",
    "micro:biz": "sh scripts/start_micro.sh --biz",
    "micro:prod": "sh scripts/start_micro.sh --prod",
    "micro:mock": "sh scripts/start_micro.sh --mock",
    "lint": "sh scripts/lint.sh",
    "lint:fix": "sh scripts/lint_fix.sh",
    "lint-scss": "sh scripts/lint_scss.sh",
    "lint-scss:fix": "sh scripts/lint_scss_fix.sh",
    "ls-lint": "ls-lint",
    "prettier": "sh scripts/prettier.sh",
    "build": "sh scripts/build.sh",
    "build:test": "sh scripts/build_test.sh",
    "analyze": "sh scripts/analyze.sh",
    "analyze:test": "sh scripts/analyze.sh --test",
    "commit": "git-cz",
    "p:dev": "sh scripts/publish_test.sh --dev",
    "p:biz": "sh scripts/publish_test.sh --biz",
    "p:test": "sh scripts/publish_test.sh --test",
    "p:all": "sh scripts/publish_test.sh --all",
    "p-micro:dev": "sh scripts/publish_test.sh --dev all",
    "p-micro:biz": "sh scripts/publish_test.sh --biz all",
    "p-micro:test": "sh scripts/publish_test.sh --test all",
    "p-micro:all": "sh scripts/publish_test.sh --all all",
    "publish": "sh scripts/publish_online.sh",
    "release": "lerna version --conventional-commits --no-changelog --yes --no-push"
  },
  "devDependencies": {
    "@cyys/eslint-config-vue": "^1.0.0",
    "@cyys/stylelint-config-cy": "^1.0.2",
    "@ls-lint/ls-lint": "1.10.0",
    "@vue/cli-plugin-babel": "^4.5.9",
    "@vue/cli-plugin-eslint": "^4.5.9",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "css-loader": "^3.5.3",
    "cz-conventional-changelog": "^3.2.0",
    "eslint": "^6.7.2",
    "eslint-plugin-jsdoc": "^30.7.9",
    "eslint-plugin-vue": "^6.2.2",
    "lerna": "^3.22.1",
    "lint-staged": "^9.5.0",
    "prettier": "1.19.1",
    "sass": "^1.26.3",
    "sass-loader": "^8.0.2",
    "stylelint": "^13.3.3",
    "vue-template-compiler": "^2.6.11",
    "@rails/webpacker": "5.4.0",
    "webpack": "^4.46.0"
  },
  "gitHooks": {
    "pre-commit": "lint-staged && yarn run ls-lint"
  },
  "lint-staged": {
    "*.{js,jsx,vue}": "vue-cli-service lint --no-fix",
    "*.{vue,css,scss}": "stylelint"
  },
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
  "dependencies": {
    "@sentry/webpack-plugin": "^1.20.0",
    "async": "^3.2.0",
    "chalk": "^4.1.0",
    "clean-webpack-plugin": "3.0.0",
    "consolidate": "^0.16.0",
    "deepmerge": "^4.2.2",
    "execa": "^5.0.0",
    "fs-extra": "^9.0.1",
    "inquirer": "^7.3.3",
    "metalsmith": "^2.3.0",
    "ora": "^5.1.0",
    "raven-js": "^3.27.2"
  }
}

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out, because information from code from the issue is not enough to help you

> How Do We Reproduce?

And I can help
