### ISSUE TITLE
Reflect pushState updates

### ISSUE THREAD

**Issue by chollier** [webpack/webpack-dev-server#48]
Ideally I would like webpack-dev-server to reflect the pushState updates of my app, example :

If I hit `http://localhost:8080/webpack-dev-server/jobs/1234` I'll get redirect to the right page of my app.
However if I navigate from `http://localhost:8080/webpack-dev-server/` to a job details page, then make a modification on my code, the page will reload but I'll be redirected to the home page. 

FYI here is my config, I run a middleware server.js :
```javascript
var server = require('pushstate-server');

server.start({
  port: process.env.PORT || 8090,
  directory: './local'
});
```

webpack.config.js :
```javascript
var webpack = require("webpack");

module.exports = {
  entry: ['./src/js/app/app.coffee'],

  output: {
    path: __dirname + "/local/js/",
    filename: 'bundle.js',
    publicPath: 'http://localhost:8080/js/',
    sourceMapFilename: '[file].map'
  },

  resolve: {
    extensions: ['', '.js', '.jsx', '.jsx.coffee', '.coffee']
  },

  module: {
    loaders: [
      { test: /\.jsx.coffee$/, loader: 'jsx!coffee' },
      { test: /\.coffee$/, exclude: /\.jsx.coffee$/, loader: 'coffee-loader' },
      { test: /\.json$/, loader: "json" }
    ]
  },

  devServer: {
    stats: {colors: true},
    contentBase: 'http://localhost:8090'
  },

  devtool: "source-map"

};
```

**Comment by kentcdodds** [comment]
@chollier, is that server working for you? I've tried several variations and I can't seem to get it to work for me. My folder structure is:

- project-root
  - app
    - index.html
  - scripts
    - server.js

My content base is `'./app'` and my index.html is looking for `bundle.js` as a sibling to itself (`script="bundle.js"`).
