### ISSUE TITLE
Feature request: expose errors to plugins

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack-dev-server#481]
By now errors in Webpack is handled like this, an error message:

``` js
        errors: function(errors) {
            status.text("App updated with errors. No reload!");
            okness.text("Errors while compiling.");
            $errors.text("\n" + stripAnsi(errors.join("\n\n\n")) + "\n\n");
            header.css({borderColor: "#ebcb8b"});
            $errors.show(); iframe.hide();
        },
```

If that code is exposed then we may get error messages like this with plugins, and it can be quite convenient, as it already was in ClojureScript projects.

![](https://camo.githubusercontent.com/b667870d8c1820794e361866908ae7930acb9c77/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f626861756d616e2d626c6f672d696d616765732f666967776865656c5f696d6167652e706e67)
---

update:

I made a prototype https://github.com/mvc-works/webpack-hud

**Comment by SpaceK33z** [comment]
Did you look at #542? It has a nice example of how to listen to socket changes. Bit hacky, but it works.

**Comment by SpaceK33z** [comment]
I exposed some events to the window now with 06c7773e9b6a0e3dbe43e53f605dbc221edc4e29. An example of how to use it:

```js
window.addEventListener('message', function onWebpackMessage (msg) {
	if (!msg.data || !msg.data.type) return;
	switch(msg.data.type) {
		case 'webpackOk':
			console.log('bundle compiled ok');
			break;
		case 'webpackErrors':
			console.log('There were some errors', msg.data.data);
			break;
	}
}, false);
```

**Comment by jiyinyiyong** [comment]
Looks good to me https://github.com/mvc-works/webpack-hud/tree/with-new-api

Still want to ask if I can get the stripped string, since in the browser people are unlikely to need ANSI escape code. Then I should not need to strip by myself:

```js
const errorMsg = webpackMsg.data.map((s) => stripAnsi(s)).join('\n');
```

**Comment by SpaceK33z** [comment]
Sure, can you make a PR for that? Busy atm.

**Comment by SpaceK33z** [comment]
Closing this since the feature has been implemented. Let me know if you don't like the API or want to make some changes.
