### ISSUE TITLE
after implementing webpack  apis are failing with 404 and after giving proxy in dev server failing with500

### ISSUE THREAD

**Issue by TajSaida** [webpack/webpack-dev-server#4814]
[](`const path = require('path')
const HtmlWebPackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const webpack = require('webpack');
const setupProxy = require('./src/setupProxy.js');
const proxy = require('http-proxy-middleware');

module.exports = {
    mode:"development",
    entry: "./src/index.js",
    output: {
        filename: "bundle.js",
        path: path.resolve(__dirname, 'dist'),
        clean: true,
        assetModuleFilename: 'images/[hash][ext][query]',
        publicPath:'/'
        
    },
    plugins: [
        new HtmlWebPackPlugin({
            template: './public/index.html'
        }),
        new MiniCssExtractPlugin(),
        new webpack.HotModuleReplacementPlugin()
     
    ],
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-react', '@babel/preset-env']
                    }
                }
            },
            {
              test: /\.scss$/,
              use: [
                'style-loader',
                'css-loader',
                'sass-loader',
              ],
            },
            {
              test: /\.css$/,
              use: [
                'style-loader',
                'css-loader',
              ],
            },
            {
                test:/\.(png|jpg|gif)$/,
                type:"asset/resource"
            },
            {
              test: /\.(woff(2)?|eot|ttf|otf|svg|)$/,
              type: 'asset/inline',
              
            },

        ]
    },
    devServer: {
        static: {
            directory: path.join(__dirname, 'dist')
        },
        onBeforeSetupMiddleware: function(app) {
          setupProxy(app);
        },
        // historyApiFallback: true,
        hot: true,
        // inline: true,
      
        // host: 'localhost', // Defaults to `localhost`
        port: 3002,
        open:true,
        // proxy: {
        //   '/': {
        //     target: 'http://localhost:3080/',
        //     // secure: false,
        //     changeOrigin: true
        //   }
        // },
        proxy: {
          "*": "http://[::1]:3080",
          "secure": false,
          "changeOrigin": true
        },
        // proxy: {
        //   '/api': 'http://localhost:3080',
        // },
        
        // proxy:{

        //         '*':"http://localhost:3002/"
          
        //       },
          
          // proxy: {
          //   // '/': {
          //   //   target: 'http://localhost:3080/',
          //   //   // pathRewrite: {'^/': ''},
          //   //   changeOrigin: true,
          //   // },
          //   onAfterSetupMiddleware: function(devServer) {
          //     devServer.app.use(
          //       '/',
          //       proxy({
          //         target: 'http://localhost:3080/',
          //         // pathRewrite: {'^/api': ''},
          //         changeOrigin: true,
          //       })
          //     );
          //   },
          // },
          
       
    }

}`)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Plese respect time other developers, thank you

**Comment by TajSaida** [comment]
can i you just tell me what are you looking for exactly
