### ISSUE TITLE
The cause of SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Elemino** [webpack/webpack-dev-server#486]
Hello, 

When I run 'npm run start' I get the following error:

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/thefreedom/Desktop/react-starter/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/thefreedom/Desktop/react-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! react-starter@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starter@1.0.0 start script 'webpack-dev-server'.
npm ERR! This is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thefreedom/Desktop/react-starter/npm-debug.log

I am not sure if this is a Webpack issue per se; 

Any help will be appreciated! Thank you.

**Comment by Elempower** [comment]
Haven't been able to fix this. Project Abandoned. Would be nice to know what might have caused this. Thanks!

**Comment by othyn** [comment]
Sorry if this is raking up the past, but I've just come across this issue when implementing CI.

The build environment by default was set to Node v0.10, which I failed to notice and thus the build failed.

Once I realised, I brought the version up to my dev env of v6.9.1.

Sorted.

**Comment by Elemino** [comment]
Sorry. forgot about this issue. But interested in trying it out. Will update once I install dev env.
