### ISSUE TITLE
Support for multiple dev servers exported from a single webpack config

### ISSUE THREAD

**Issue by ryancole** [webpack/webpack-dev-server#487]
I'm using webpack CLI with a .js config file. The config file exports an array of configurations. Each configuration provides some dev server settings, using unique ports. When I start webpack dev server and point it to that webpack config, it launches a single server and chooses the last exported webpack config.

Would it be possible to make webpack dev server see these multiple exported configs and launch X number of needed servers?

**Comment by SpaceK33z** [comment]
Launching x number of needed servers should not happen in webpack-dev-server. You can write a simple script that launches those. There is [npm-run-all](https://github.com/mysticatea/npm-run-all), which can run multiple scripts in parallel.
