### ISSUE TITLE
live reload looping in Safari MacOS and Safari Mobile

### ISSUE THREAD

**Issue by Cervenka** [webpack/webpack-dev-server#4870]
### Bug report

When a pack gets changed reloadApp gets called repeatedly.  The page reloads in a loop.

The value for currentHash does not seem to get updated.

Safari Version 16.5 (18615.2.9.11.4)
Safari Technology Preview Release 170 (Safari 16.4, WebKit 18616.1.14.5)

### Actual Behavior

The page reloads in a loop.

### Expected Behavior

The page should only be reloaded once.

### How Do We Reproduce?

Have live reload enabled. Go to a page in Safari. Make a change to a pack.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 90.63 GB / 128.00 GB
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Chrome Canary: 115.0.5790.1
    Edge: 113.0.1774.35
    Firefox: 113.0.1
    Safari Technology Preview: 16.4
  Packages:
    babel-loader: 8 => 8.3.0 
    compression-webpack-plugin: 9 => 9.2.0 
    css-loader: 6 => 6.7.3 
    eslint-loader: 4.0.2 => 4.0.2 
    exports-loader: ^1.1.1 => 1.1.1 
    expose-loader: ^1.0.3 => 1.0.3 
    imports-loader: ^1.2.0 => 1.2.0 
    mustache-loader: ^1.4.3 => 1.4.3 
    rails-erb-loader: ^5.5.2 => 5.5.2 
    sass-loader: ^13.2.0 => 13.2.0 
    terser-webpack-plugin: 5 => 5.3.6 
    thread-loader: ^3.0.1 => 3.0.1 
    ts-loader: ^8.3.0 => 8.4.0 
    webpack: 5 => 5.75.0 
    webpack-assets-manifest: 5 => 5.1.0 
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0 
    webpack-cli: 4 => 4.10.0 
    webpack-dev-server: ^4.15.0 => 4.15.0 
    webpack-merge: 5 => 5.8.0

**Comment by alexander-akait** [comment]
> How Do We Reproduce?
> Have live reload enabled. Go to a page in Safari. Make a change to a pack.

Please provide reproducible test repo or video/screenshots

**Comment by Cervenka** [comment]
Is seems that it has to do with some packs being deferred and others not.

https://github.com/Cervenka/webpack-dev-server-reload-issue/

**Comment by alexander-akait** [comment]
@Cervenka You use `shakapacker`, please open an issue in `shakapacker`, our pure setup dev server without `shakapacker` works fine in Safari, so it maybe related to `shakapacker`, feel free to ping me in the opened issue and I will assist you, thank you
