### ISSUE TITLE
Webpack adding duplicates of runtime into bundle

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/webpack-dev-server#489]
Does anyone know why I am getting duplicates of the webpack runtimes in the bundle? 

It's adding multiple numbers after the ? and the browser is seeing them as new files.

- dev-server.js?
- dev-server.js?52d4
- dev-server.js?53d4*

![webpack-dupes](https://cloud.githubusercontent.com/assets/13709948/15556492/faa8f818-2282-11e6-9214-bfd8e551e55b.png)

See the file tree on the left:
![webpack-dupes2](https://cloud.githubusercontent.com/assets/13709948/15556549/3f384240-2283-11e6-934d-f5ce6826371e.png)

Why is it doing this? I just want one copy of the file in the bundle.

**Comment by IAMtheIAM** [comment]
I think this is a bug. A fellow dev pointed out that [in the webpack-dev-server code](https://github.com/webpack/webpack-dev-server/blob/a77eac516dace7f5072740206eda474a8141055b/bin/webpack-dev-server.js#L248), it explicitly duplicates the WDS runtime for each entry point. This should not happen. We should be able to have infinite entry points and only 1 WDS and HMR runtime in 1 of the bundles.

**Comment by SpaceK33z** [comment]
So the problem is that you're using a hash in your filename, but webpack-dev-server doesn't know when it can delete the previous one, right? I also had issues with that, and fixed it with this:

```js
const IS_DEV_SERVER = process.argv[1].indexOf('webpack-dev-server') >= 0;

module.exports = {
    output: {
        filename: `[name]-${IS_DEV_SERVER ? 'dev' : '[hash:7]'}.js`,
    }
};
```

Note that everywhere where you use a `[hash]` or `[chunkhash]` you need to use the same trick.

**Comment by garygreen** [comment]
> I think this is a bug. A fellow dev pointed out that in the webpack-dev-server code, it explicitly duplicates the WDS runtime for each entry point

@IAMtheIAM  I know this issue is pretty ancient but do you happen to know if Webpack 4 has the same problem? I'm still on V3 so wondering if it's worth the upgrade
