### ISSUE TITLE
Unhelpful error message when running `npx webpack --mode=development serve`

### ISSUE THREAD

**Issue by Feuermurmel** [webpack/webpack-dev-server#4905]
### Modification Proposal

I just had a frustrating experience. I assume that the trap I have fallen into might also catch other people. This proposal doesn't suggest a specific change to be made, because I believe that to do that, I would first have to understand what the underlying cause for my problem was.

The problem seems obvious to me: I got an error message that mentions many thing that don't have anything to do with what I needed to change to solve my problem, and that only left me astray when looking for a solution. I'm writing this in the hope that the situation can be improved for future users.

I was following the instructions under https://www.npmjs.com/package/webpack-dev-server?activeTab=readme#getting-started:

```
$ mkdir test
$ cd test
$ mkdir src
$ touch src/index.js
$ npm install webpack webpack-cli webpack-dev-server --save-dev

added 309 packages, and audited 310 packages in 2s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Then I started the dev server. It told me that I did not specify a _mode_:

```
$ npx webpack serve
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.169:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/public' directory
asset main.js 123 KiB [emitted] [minimized] (name: main) 1 related asset
orphan modules 31.6 KiB [orphan] 12 modules
runtime modules 27.2 KiB 12 modules
cacheable modules 177 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 71.8 KiB
    ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0....(truncated) 42.4 KiB [built] [code generated]
    + 3 modules
  modules by path ./node_modules/webpack/hot/*.js 5.3 KiB
    ./node_modules/webpack/hot/dev-server.js 1.94 KiB [built] [code generated]
    + 3 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.6 KiB
    ./node_modules/html-entities/lib/index.js 7.74 KiB [built] [code generated]
    + 3 modules
  ./src/index.js 1 bytes [built] [code generated]
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/events/events.js 14.5 KiB [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.87.0 compiled with 1 warning in 698 ms
^C<i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
```

So I terminated a server and tried again:

```
$ npx webpack --mode=development serve
asset main.js 662 bytes [emitted] (name: main)

ERROR in main
Module not found: Error: Can't resolve 'serve' in '/Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test'
resolve 'serve' in '/Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test'
  Parsed request is a module
  using description file: /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules
        single file module
          using description file: /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/package.json (relative path: ./node_modules/serve)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules/serve doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules/serve.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules/serve.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules/serve.wasm doesn't exist
        /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/test/node_modules/serve doesn't exist
      /Users/michi/Documents/Projects/Engineer_Of_The_People/Stuff/node_modules doesn't exist or is not a directory
      /Users/michi/Documents/Projects/Engineer_Of_The_People/node_modules doesn't exist or is not a directory
      /Users/michi/Documents/Projects/node_modules doesn't exist or is not a directory
      /Users/michi/Documents/node_modules doesn't exist or is not a directory
      /Users/michi/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.87.0 compiled with 1 error in 31 ms
```

I tried looking into this issue for about an hour. I still do not understand the error message, but I figured out that `npx webpack serve --mode=development` works, while what I tried above didn't.

### Expected Behavior / Situation

I would have expected `npx webpack --mode=development serve` (or an equivalent command under `"scripts"` in `package.json`) to either do what I want (i.e. a start the dev server with _mode_ set to `development`) or to give me an error message that I understand. Something like `webpack` can't take options when a sub-command is specified, or whatever makes sense in this case.

### Actual Behavior / Situation

See error message above.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
$ npx webpack-cli info

  System:
    OS: macOS 12.6.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 65.78 MB / 32.00 GB
  Binaries:
    Node: 18.4.0 - ~/opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/opt/homebrew/bin/yarn
    npm: 8.12.1 - ~/opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 94.0.992.38
    Firefox: 112.0.2
    Safari: 16.5
  Packages:
    webpack: ^5.87.0 => 5.87.0 
    webpack-cli: ^5.1.4 => 5.1.4 
    webpack-dev-server: ^4.15.1 => 4.15.1 
```

**Comment by alexander-akait** [comment]
You should write sumcommands after `webpack`, that's how every CLI tool works and how args parser works (like you use `git fetch`/`git push`/etc), sorry we can't change it, any things after commands will be considered as entries, it is a specific syntax.

**Comment by Feuermurmel** [comment]
I do want to note, that `git` handles this case better. If I use `git --depth=100 fetch` instead of `git fetch --depth=100`, I get a far better error message:

```
$ git --depth=100 fetch
unknown option: --depth=100
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [--super-prefix=<path>] [--config-env=<name>=<envvar>]
           <command> [<args>]
```

So your statement tht every CLI tool works like this is wrong.

**Comment by alexander-akait** [comment]
@Feuermurmel webpack-dev-server doesn't have CLI, again - webpack-cli handle unknown args after the main command as entries, what you are asking will break this logic, we don't know what is `serve` - it can be a file, it can be alias, it can be a link in your fs, it can be virtual module, it can be anythings, so we pass it to webpack to try to resolve, that is why you see this error message

**Comment by Feuermurmel** [comment]
TBH I don't understand what you are writing. I'm trying to explain what I understand. You are writing:

> webpack-dev-server doesn't have CLI, Webpack-CLI handles unknown args after the main command as entries, what you are asking will break this logic […]

My command was `npx webpack --mode=development serve`. So what do you mean by "unknown args after the main command"? `--mode=development` is an option (like `--depth=100` in my previous reply) and `serve` is the "main command" (like `fetch` in my previous reply). So there are no unknown args. What am I misunderstanding?

If webpack-dev-server doesn't have CLI, how does `npx webpack serve --mode=development` work? If webpack-dev-server doesn't process command line arguments and `--mode=development` is passed after `server`, shouldn't it be passed to the `serve` command, which doesn't handle it, which should result in an error? What am I misunderstanding?

In your original response, you wrote:

> […] any things after commands will be considered as entries, it is a specific syntax.

I don't understand what you mean by "things after commands". There is nothing after the `serve` command? Or what do you mean by "commands"? Which arguments in my command above. I don't get it.

> > So your statement tht every CLI tool works like this is wrong.
> 
> Where? I said what CLI tools ask to write a subcommand after the main command, git does the same and other CLIs too

You wrote:

> You should write sumcommands after webpack, that's how every CLI tool works

I understood that as you saying that in a CLI that has subcommands, like `git`, that there can't be any options between the main command and the subcommand, as in `git diff` is supported, but `git --no-pager diff` isn't. I think I still don't understand what you meant by that statement then.
