### ISSUE TITLE
proxy bad gateway

### ISSUE THREAD

**Issue by brusand** [webpack/webpack-dev-server#495]
Hi the community,

i have an issue with the proxy . I have redirect mya api backend via a corporate proxy and i have always "bad gateway"

var HttpsProxyAgent = require('https-proxy-agent');

var proxyServer ='https://proxypac.si.francetelecom.fr:8080';

module.exports = require('../webpack.make')({
    output: 'dev',
    config: 'config/config.dev.json',
    proxy: {
        '/api*': {
       
            target: 'https://integ.m2m.orange.com',
            //toProxy: 'https://proxypac.si.francetelecom.fr:8080/',
            //changeOrigin: true,
            agent:  new HttpsProxyAgent(proxyServer),
            secure: false 
        },
        '/qrcode*': {
            target: 'https://integ.m2m.orange.com',
            secure: false
        },
        '/captcha*': {
            target: 'https://integ.m2m.orange.com',
            secure: false
        }
    },
    quiet: false,
    noInfo: false,
    inline: true,
    profile: {
    }
});

any idea to solve an/or debug ?

Many thx

best regards
Bruno

**Comment by tomascharad** [comment]
Hi @brusand,

How did you manage to solve this?

**Comment by brusand** [comment]
yes i solved it via HttpsProxyAgent

Bruno

2016-06-07 5:56 GMT+02:00 Tomás Charad <notifications@github.com>:
