### ISSUE TITLE
Please support `server: 'quic'`

### ISSUE THREAD

**Issue by mozhuanzuojing** [webpack/webpack-dev-server#4976]
### Feature Proposal

Since node `18.17.1` updated `OpenSSL 3.0.10`,  `quic` is already available, can `dev-server` support it.

### Feature Use Case

want to have faster web page opening speed in local development.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 14.25 GB / 19.54 GB
  Binaries:
    Node: 18.16.0 - /usr/local/lib/nodejs/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/lib/nodejs/v18.16.0/bin/yarn
    npm: 9.5.1 - /usr/local/lib/nodejs/v18.16.0/bin/npm
  Packages:
    clean-webpack-plugin: 4.0.0 => 4.0.0 
    copy-webpack-plugin: 11.0.0 => 11.0.0 
    css-loader: 6.8.1 => 6.8.1 
    esri-loader: 3.7.0 => 3.7.0 
    html-webpack-plugin: 5.5.3 => 5.5.3 
    less-loader: 11.1.3 => 11.1.3 
    open-browser-webpack-plugin: 0.0.5 => 0.0.5 
    postcss-loader: 7.3.3 => 7.3.3 
    style-loader: 3.3.3 => 3.3.3 
    swc-loader: 0.2.3 => 0.2.3 
    webpack: 5.88.2 => 5.88.2 
    webpack-cli: 5.1.4 => 5.1.4 
    webpack-dev-server: 4.15.1 => 4.15.1 
    webpack-hot-middleware: 2.25.4 => 2.25.4 
    webpack-merge: 5.9.0 => 5.9.0 
    webpackbar: 5.0.2 => 5.0.2

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Close due https://github.com/nodejs/node/pull/44325 is not ready, anyway in the next release we will support custom `server`, so you can use any (like http2, spdy, any custom which compatibility with `net.Server`)
