### ISSUE TITLE
GET http://localhost:8081/ 404 (Not Found)

### ISSUE THREAD

**Issue by navalega0109** [webpack/webpack-dev-server#4985]
GET http://localhost:8081/ 404 (Not Found)

### Bug report

After running the npm serve : it got successfully executed but when try to check localhost it displays 404 not found error.

### Actual Behavior

Error: GET http://localhost:8081/ 404 (Not Found)

### Expected Behavior

Ideally it should load the bundle.js file.

### How Do We Reproduce?

try to run: npm run serve

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.15 GB / 11.79 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
  Packages:
    ts-loader: ^9.4.4 => 9.4.4
    webpack: ^5.88.2 => 5.88.2
    webpack-cli: ^5.1.4 => 5.1.4
    webpack-dev-server: ^4.15.1 => 4.15.1

**Comment by snitin315** [comment]
Please provide a GitHub repo to reproduce.

**Comment by stoefln** [comment]
Got the same problem
