### ISSUE TITLE
Upgraded to v2 and proxy now doesn't as expected?

### ISSUE THREAD

**Issue by KingScooty** [webpack/webpack-dev-server#501]
I'm using an almost identical setup to the one written in the article here => http://ctheu.com/2015/05/14/using-react-hot-loader-with-a-webpack-dev-server-and-a-node-server/

Everything was working great, all my requests were being proxied to my node server.

However, since upgrading to webpack 2.0 and devserver 2.0, the proxying has stopped working. It now just loads the webpack filesystem page, and i can't figure out what's changed to cause it.

Can anyone point me in the right direction? Is there an upgrade guide i'm missing?

```js
// server

  require('babel-register')();
  require('babel-polyfill');
  require('./src/server');

  // we start a webpack-dev-server with our config
  let webpack = require('webpack');
  let WebpackDevServer = require('webpack-dev-server');
  let config = require('./webpack.config');

  const back_server = new WebpackDevServer(webpack(config), {
    hot: true,
    historyApiFallback: true,
    proxy: {
      '*': 'http://localhost:3000'
    }
  });

  back_server.listen(3001, 'localhost', function (err, result) {
    if (err) {
      console.log(err);
    }

    console.log('Listening at localhost:3001');
  });
```

```js
// webpack.config

var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    'webpack-dev-server/client?http://127.0.0.1:3001/',
    'webpack/hot/only-dev-server',
    'babel-polyfill',
    './src/client.js'
  ],
  output: {
    path: path.join(__dirname, 'src/dist/'),
    filename: 'bundle.js'
  },
  resolve: {
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loaders: ['react-hot', 'babel'] // ,
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(en)$/)
  ],
  devtool: 'inline-source-map'
};

```

**Comment by owieboy** [comment]
I encountered the same issue when I tried upgrading to 2.1.0-beta. It seems like regex in proxy configuration is still not working. There's a pending pull request for supporting regex #148.

**Comment by kurdin** [comment]
if somebody else has this problem with proxy not working correctly after upgrading to 2.1.0-beta here is how to fix it:

in 2.1.x webpack-dev-server uses http-proxy-middleware that expect '**' instead of '*' to proxy all requests.

in your config: 
```
proxy: {
  '*': 'http://localhost:3000'
}
```
change to 
```
proxy: {
  '**': 'http://localhost:3000'
}
```

**Comment by allienx** [comment]
@kurdin thanks! Good link :+1:

**Comment by SpaceK33z** [comment]
@KingScooty, does the above fix your problem?

**Comment by SpaceK33z** [comment]
Closing this issue, since the problem has been solved with the last release. Using `*` does the same as `**` now.
