### ISSUE TITLE
Error When installing npm

### ISSUE THREAD

**Issue by sandyksit** [webpack/webpack-dev-server#502]
13649 error Windows_NT 6.1.7600
13650 error argv "C:\\Program Files\\NodeJS\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
13651 error node v4.4.5
13652 error npm  v2.15.5
13653 error code EPEERINVALID
13654 error peerinvalid The package webpack@2.1.0-beta.7 does not satisfy its siblings' peerDependencies requirements!
13654 error peerinvalid Peer globalize-webpack-plugin@0.3.4 wants webpack@^1.9.0
13654 error peerinvalid Peer istanbul-instrumenter-loader@0.1.3 wants webpack@1.x.x
13654 error peerinvalid Peer sass-loader@3.2.0 wants webpack@^1.12.6
13654 error peerinvalid Peer skip-amd-webpack-plugin@0.0.2 wants webpack@^1.9.0
13654 error peerinvalid Peer webpack-dev-middleware@1.6.1 wants webpack@1 || ^2.1.0-beta
13654 error peerinvalid Peer babel-loader@6.2.4 wants webpack@1 || ^2.1.0-beta
13654 error peerinvalid Peer karma-webpack@1.7.0 wants webpack@^1.4.0
13654 error peerinvalid Peer webpack-dev-server@1.14.1 wants webpack@>=1.3.0 <3
13655 verbose exit [ 1, true ]

"please help anybody, I am trying to install but not able to install"

**Comment by t246246** [comment]
I think you will need npm v3.

**Comment by SpaceK33z** [comment]
It looks like you're using webpack v1 (which is the stable release), but installing the webpack-dev-server that is compatible with webpack v2 (in beta). To force webpack-dev-server to the v1 compatible version, use `npm install webpack-dev-server@1.14.1 --save-dev`.

**Comment by TheLarkInn** [comment]
Dupe #541
