### ISSUE TITLE
Proxy Configuration Failure with Angular 15, Node 18, and TLS 1.2

### ISSUE THREAD

**Issue by Neizan93** [webpack/webpack-dev-server#5022]
### Bug report

Upon setting up a local development environment with Angular 15 and Node 18, I encountered a significant issue with the proxy configuration in webpack-dev-server. The proxy setup within the Angular CLI, which relies on webpack-dev-server, fails to function as expected when attempting to target HTTPS backends that are configured with TLS 1.2. This issue seems to be a direct result of the shift to OpenSSL 3 in Node 17 and above, which restricts connections to remote endpoints using TLS versions lower than 1.3 for security reasons.

### Actual Behavior

The proxy configuration fails to allow connections to backends utilizing TLS 1.2, rendering an error and preventing the communication between the local development environment and the backend. This disrupts the workflow significantly as it hinders the ability to work with backends that are yet to upgrade to TLS 1.3.

### Expected Behavior

The proxy configuration should function correctly, facilitating the communication between the local development environment and the backend, irrespective of the TLS version used by the backends. This functionality is crucial for local development, testing, and debugging processes.

### How Do We Reproduce?

Set up a local development environment with Angular 15 and Node 18.
Configure the proxy settings in Angular CLI to point to a backend using HTTPS with TLS 1.2.
Attempt to access the backend via the proxy from the local development environment.
Observe the failure in proxy configuration, preventing access to the backend due to TLS 1.2 restriction.

**Comment by mbonaci** [comment]
Possibly related: https://github.com/webpack/webpack-dev-server/issues/4828
