### ISSUE TITLE
Update to webpack-dev-middleware 7.0.0

### ISSUE THREAD

**Issue by reaktivo** [webpack/webpack-dev-server#5027]
### Bug report
Currently `webpack-dev-server` throws errors when used with Node >20 due to a old memfs being referenced as a transitive dependency.

`webpack-dev-middleware` has already been updated as of [this PR](https://github.com/webpack/webpack-dev-middleware/pull/1693).

Now the last remaining piece is for `webpack-dev-server` to point to latest `webpack-dev-middleware`.

### Actual Behavior

Throws the following error:

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (/Users/x/dev/client/node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (/Users/x/dev/client/node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
```
 

### Expected Behavior

Should not throw memfs errors

**Comment by alexander-akait** [comment]
We will do it in the next major release to avoid breaking changes, it will be soon

**Comment by alexander-akait** [comment]
Done in the master/main, release will be soon
