### ISSUE TITLE
Is the Http Proxy Middleware now in webpack dev server ? Which version ?

### ISSUE THREAD

**Issue by ianjohnspain** [webpack/webpack-dev-server#503]
Hi,

I believe there has been some work on integrating the http-proxy-middleware (https://github.com/chimurai/http-proxy-middleware)  with webpack-dev-server but I can't find any information about weather its included in the latest release. NPM installing has the new proxy ?

Just trying to figure out if I should be using the proxy config or not ?

Does anyone have any examples on configuring the new proxy or should I just check the https://github.com/chimurai/http-proxy-middleware for implementation details ?

Thanks in advance

**Comment by bryandowning** [comment]
https://github.com/webpack/webpack-dev-server/pull/359

**Comment by SpaceK33z** [comment]
It was released in `1.15.0`.
