### ISSUE TITLE
Why writeToDisk cannot work in webpack-dev-server 3.1.9

### ISSUE THREAD

**Issue by zhangzhuang15** [webpack/webpack-dev-server#5036]
Hello everyone!

I got a confusion recently. I use webapck@4.19.0， webpack-dev-server@3.1.9 and webpack-cli@3.1.2. Follow the v4 document of webpack, I open the `writeToDisk` config:
```txt
{
   devServer: {
     writeToDisk: true
   }
}
```
other configs are not important, so I ignore them

there is a error when run `webpack-dev-server --hot --config webpack.config.my.js`: 
```txt
✖ ｢wds｣: webpack Dev Server Invalid Options
options should NOT have additional properties
```

Are there some compatible problems between webpack and webpack-dev-server ? For example, if I use webpack 4, I have to use webpack-dev-server 4.

Any tips will be appreciated!

**Comment by alexander-akait** [comment]
If you want to use the `writeToDisk` option please update `webpack-dev-server` to the latest stable `3.x`
