### ISSUE TITLE
Overlay.runtimeErrors doesn't work

### ISSUE THREAD

**Issue by zhiyuc123** [webpack/webpack-dev-server#5037]
### Actual Behavior

Runtime errors always show, no matter what set to `runtimeErrors`(false or filter function).

### Expected Behavior

Runtime errors should be filtered as configed.

### How Do We Reproduce?

Run overlay example.([examples/client/overlay](https://github.com/webpack/webpack-dev-server/tree/master/examples/client/overlay)). Click to throw ingored error.

![image](https://github.com/webpack/webpack-dev-server/assets/46096473/e545bfbe-35a8-4b10-8dc3-2e7cc9487e40)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
 System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 53.09 MB / 8.00 GB
  Binaries:
    Node: 16.20.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 16.5.1
  Global Packages:
    webpack-dev-server: 4.15.1
```

**Comment by zhiyuc123** [comment]
```shell
npx webpack serve --open --client-overlay
```
find out that I use cli option `client-overlay` to run the example.

**Comment by whatisthis-dot** [comment]
# HTTP POST vs PUT Methods in RESTful APIs

## HTTP POST

### Description
The HTTP POST method is used to submit data to be processed to a specified resource. It often results in the creation of a new resource or the processing of data.

### Usage
- **Creating Resources**: When you want to create a new resource on the server.
- **Non-idempotent Operations**: Each request might result in a different outcome (e.g., creating a new record every time).

### Characteristics
- **Non-idempotent**: Calling POST multiple times may produce different results.
- **Request Body**: Contains the data to be processed or stored.
- **URL**: Typically points to a collection (e.g., `/users` to create a new user).

### Example
```http
POST /users HTTP/1.1
Host: example.com
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}
```

## HTTP PUT

### Description
The HTTP PUT method is used to update an existing resource or create a resource if it does not exist. It is often used to replace the resource with the data provided in the request body.

### Usage
- **Updating Resources**: When you want to update an existing resource.
- **Idempotent Operations**: Multiple identical requests should produce the same result.
- **Creating/Overwriting Resources**: Can be used to create a resource if it does not exist.

### Characteristics
- **Idempotent**: Calling PUT multiple times will have the same effect as calling it once.
- **Request Body**: Contains the data to be updated or created.
- **URL**: Typically points to a specific resource (e.g., `/users/123` to update user with ID 123).

### Example
```http
PUT /users/123 HTTP/1.1
Host: example.com
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}
```

## Key Differences

| Aspect              | POST                                                | PUT                                               |
|---------------------|-----------------------------------------------------|---------------------------------------------------|
| Idempotency         | No                                                  | Yes                                               |
| Common Usage        | Create a new resource                               | Update an existing resource or create if not exists |
| URL                 | Points to a collection                              | Points to a specific resource                     |
| Request Action      | Submits data for processing                         | Replaces the resource with the provided data      |
| Multiple Requests   | Can result in multiple resources being created      | Results in the same resource state                |

## Summary
- **POST** is best for creating new resources where each request results in a new resource.
- **PUT** is best for updating existing resources or creating a resource if it does not exist, ensuring that the operation is idempotent.
