### ISSUE TITLE
Webpack-dev-server :command not found 

### ISSUE THREAD

**Issue by Laleeth** [webpack/webpack-dev-server#504]
I have done installing webpack-dev-server globally and locally 

#Here is my package.json file 
  **"devDependencies":** {
    **"babel-loader":** "^6.2.4",
    **"babel-preset-es2015":** "^6.9.0",
   **"webpack":** "^1.13.1",
    **"webpack-dev-server": "^1.14.1"
  **}**

![screenshot 3](https://cloud.githubusercontent.com/assets/14369362/15939471/66e14706-2e95-11e6-88cc-99aea3a82608.png)

var webpack = require('webpack');
var path = require('path');

module.exports = {
    devtool: 'inline-source-map',
    entry: [
        'webpack-dev-server/client?http://127.0.0.1:8080/',
        'webpack/hot/only-dev-server',
        'bootstrap-loader',
        './src'
    ],
    output: {
        path: path.join(__dirname, 'public'),
        filename: 'bundle.js'
    },
    resolve: {
        modulesDirectories: ['node_modules', 'src'`'.js',]`    extension: ['', '.js',]
    },
    module: {
        loaders: [
        {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel',
            query: {
                presets: ['es2015']
            }
    }
    ],
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ],
    devServer: {
        hot: true,
        proxy: {
            '*': 'http://localhost:3000'
        }
    }
};

**Comment by t246246** [comment]
When you install modules locally, it is located `node_modules/.bin`.
```
$ cd your-folder-that-have-packages.json
$ node_modules/.bin/webpack-dev-server
```

Or if you add package.json
```
	"scripts": {
		"start": "webpack-dev-server"
	},
```
```
$ npm run start
```
will invoke webpack-dev-server

**Comment by Laleeth** [comment]
Thank you :)
