### ISSUE TITLE
Deep unmet peerDependency warnings from `memfs`

### ISSUE THREAD

**Issue by himynameisdave** [webpack/webpack-dev-server#5041]
### Feature Proposal

Latest `webpack-dev-server` comes with a slew of deeply nested peer dependency warnings, coming from `memfs`. While these aren't blockers, they aren't actionable by consumers of this package and simply act as noise.

<img width="741" alt="image" src="https://github.com/webpack/webpack-dev-server/assets/4298089/0ece2b41-9d5d-4b06-bb08-a513cc6cd6b6">

### Feature Use Case

It would be nice to not have these warnings.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
➜ npx webpack-cli info

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.85 GB / 32.00 GB
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 2.15.12 - ~/fossa/FOSSA/node_modules/.bin/npm
  Browsers:
    Chrome Canary: 123.0.6296.0
    Firefox: 122.0.1
    Firefox Developer Edition: 115.0
    Safari: 17.3
  Packages:
    babel-loader: ^9.1.3 => 9.1.3
    cache-loader: ^4.1.0 => 4.1.0
    css-loader: ^6.10.0 => 6.10.0
    css-minimizer-webpack-plugin: ^5.0.0 => 5.0.1
    less-loader: ^7.3.0 => 7.3.0
    postcss-loader: ^8.1.0 => 8.1.0
    react-content-loader: ^6.2.1 => 6.2.1
    style-loader: ^2.0.0 => 2.0.0
    ts-loader: ^9.5.1 => 9.5.1
    webpack: ^5.90.1 => 5.90.1
    webpack-bugsnag-plugins: ^1.8.0 => 1.8.0
    webpack-cli: ^5.1.4 => 5.1.4
    webpack-dev-server: ^5.0.0 => 5.0.0
```

**Comment by himynameisdave** [comment]
Relevant issue from `memfs`: https://github.com/streamich/memfs/issues/979

**Comment by G-Rath** [comment]
> they aren't actionable by consumers of this package and simply act as noise.

Yes they are, you're meant to install those packages as they peer dependencies which means they should be supplied by the top of the dependency tree.

(I'm a semi-maintainer of `memfs` and will also look into your issue over there, but just wanted to flag they're not really `webpack-dev-server`'s problem)

**Comment by alexander-akait** [comment]
> I'm a semi-maintainer of memfs and will also look into your issue over there, but just wanted to flag they're not really webpack-dev-server's problem

Yeah, memfs had release, so just update your deps - https://github.com/webpack/webpack-dev-middleware/pull/1734

**Comment by himynameisdave** [comment]
> Yes they are, you're meant to install those packages as they peer dependencies

If `memfs` (or `json-joy`) is supposed to be installed as a peerDep by consumers of `webpack-dev-server`, that should be documented in this readme.
