### ISSUE TITLE
Types in lib/Server referring to non-existing Request_1 and Response_1 interfaces

### ISSUE THREAD

**Issue by cascornelissen** [webpack/webpack-dev-server#5054]
### Actual Behavior

Types in `webpack-dev-server/types/lib/Server.d.ts` refer to non-existing `Request_1` and `Response_1` interfaces.

```
node_modules/webpack-dev-server/types/lib/Server.d.ts:1770:40 - error TS2552: Cannot find name 'Request_1'. Did you mean 'Request'?

1770   devMiddleware?: DevMiddlewareOptions<Request_1, Response_1> | undefined;
                                            ~~~~~~~~~

node_modules/webpack-dev-server/types/lib/Server.d.ts:1770:51 - error TS2552: Cannot find name 'Response_1'. Did you mean 'Response'?

1770   devMiddleware?: DevMiddlewareOptions<Request_1, Response_1> | undefined;
```

### Expected Behavior

Types refer to existing interfaces.

### How Do We Reproduce?

Import `Configuration` from `webpack-dev-server` (5.0.0 or 5.0.1) and look at the types of `Configuration['devMiddleware']`. I've prepared [this Codesandbox](https://codesandbox.io/p/sandbox/jolly-frog-jlys6v?file=%2Fnode_modules%2F.store%2Fwebpack-dev-server%405.0.1%2Fnode_modules%2Fwebpack-dev-server%2Ftypes%2Flib%2FServer.d.ts%3A1764%2C6) that points directly to the offending type. For some reason the direct link doesn't consistently work for me so an alternative is to go to [this link](https://codesandbox.io/p/sandbox/jolly-frog-jlys6v?file=%2Fsrc%2Findex.ts), which points to a different file in the same Codesandbox, and then right-click `Configuration` and select _Go to Definition_.

<img width="696" alt="image" src="https://github.com/webpack/webpack-dev-server/assets/1304939/9c37d3e3-52dc-4d49-9509-871913ad048f">

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
$ npx webpack-cli info

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 905.86 MB / 64.00 GB
  Binaries:
    Node: 21.6.0 - /opt/homebrew/bin/node
    npm: 10.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 121.0.6167.160
    Firefox: 122.0.1
    Safari: 17.3
  Packages:
    babel-loader: ^9.1.3 => 9.1.3
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    compression-webpack-plugin: ^11.0.0 => 11.0.0
    copy-webpack-plugin: ^12.0.2 => 12.0.2
    css-loader: ^6.10.0 => 6.10.0
    html-webpack-plugin: ^5.6.0 => 5.6.0
    html-webpack-skip-assets-plugin: ^1.0.3 => 1.0.3
    node-polyfill-webpack-plugin: ^3.0.0 => 3.0.0
    postcss-loader: ^8.1.0 => 8.1.0
    resolve-url-loader: ^5.0.0 => 5.0.0
    sass-loader: ^14.1.0 => 14.1.0
    style-loader: ^3.3.4 => 3.3.4
    terser-webpack-plugin: ^5.3.10 => 5.3.10
    ts-loader: ^9.5.1 => 9.5.1
    val-loader: ^6.0.0 => 6.0.0
    val-loader-modernizr: ^1.0.1 => 1.0.1
    warnings-to-errors-webpack-plugin: ^2.3.0 => 2.3.0
    webpack-cli: ^5.1.4 => 5.1.4
    webpack-dev-server: ^5.0.1 => 5.0.1
    webpack-merge: ^5.10.0 => 5.10.0
```

**Comment by alexander-akait** [comment]
Hm, that's intresting, sounds like a bug in ts...
