### ISSUE TITLE
How to output .html to disk using Webpack-dev-server and HTML-webpack-plugin?

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/webpack-dev-server#508]
I use `webpack` and `html-webpack-plugin` to update my index.html file with the generated script bundle, such as `bundle.[hash].js`.

Then I have to run `webpack-dev-server` so I can load that bundle into memory and take advantage of Hot Module Replacement.

This makes the code compile twice.

However, what I would like is for `webpack-dev-server` to also be able to update the index.html file with the new `bundle.[hash].js`, because now I have to run `webpack` followed by `webpack-dev-sever`. It seems weird to compile twice.

Again, the only reason I run `webpack` is to get my index.html file updated with the new hash of the bundle. If I could get `webpack-dev-server` to output an updated index.html to disk, then I could drop the `webpack` command altogether. 

Is this possible? If so, what would the webpack config change be? My webpack config is very long so I didnt think it would help to post it here.

**Comment by anri-asaturov** [comment]
webpack-dev-server compiles and outputs your sources in-memory, including index.html. Also why would you need hash in dev builds(although possible)? Tell me if you need me to show a working config for you.

**Comment by SpaceK33z** [comment]
Answered nicely above, so closing.

**Comment by mmospanenko** [comment]
How to config live reload with HtmlWebpackPlugin (w/o webpack-dev-server.js) and http://localhost/webpack-dev-server/bundle path where live reloading works but w/o my index.html (uses default empty)?

**Comment by lemind** [comment]
Hi @anri-asaturov 
Could you give me more details about this case? 
I have index.html in root folder and use it for webpack-dev-server
But I want to use hashes for prod version.

**Comment by anri-asaturov** [comment]
@lemind Well you will not use webpack-dev-server in production, right. So you need a production configuration that has a `[hash]` in file name configuration. Refer to documentation please: https://webpack.js.org/configuration/output/#output-filename

**Comment by anri-asaturov** [comment]
@lemind HtmlWebpackPlugin should automatically pick up correct name.  https://github.com/jantimon/html-webpack-plugin

**Comment by lemind** [comment]
@anri-asaturov  I have read this. Problem is webpack-web-server does not invoke html-webpack-plugin.
Essentially it does but server made index.html version in memory I suppose and I see version index.html which locate in root folder.

**Comment by anri-asaturov** [comment]
@lemind webpack-dev-server is for development, you need different configuration for prod.

**Comment by lemind** [comment]
@anri-asaturov I got it. But how could I insert my *.css/*.js src links in develop mode?

**Comment by anri-asaturov** [comment]
@lemind `plugins: [new HtmlWebpackPlugin({inject: true})]` read the html-webpack-plugin docs

**Comment by leosj** [comment]
compiler.outputFileSystem.readFileSync(compiler.outputPath+'/index.html');

**Comment by ElvisWang27** [comment]
You can try to use 'html-webpack-harddisk-plugin' to output the html to disk

**Comment by euclid1990** [comment]
I have released a plugin that solved this problem

https://github.com/euclid1990/write-assets-webpack-plugin
