### ISSUE TITLE
 Consider editing repository setings to remove "Packages" section

### ISSUE THREAD

**Issue by matkoniecz** [webpack/webpack-dev-server#5095]
### Expected Behavior / Situation

Pointless "Packages No packages published" section on github profile page is not shown

### Actual Behavior / Situation

"Packages No packages published" is displayed right now, fortunately this pointless section can be removed.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

"Packages No packages published" is displayed right now, fortunately this pointless section can be removed.

Edit repo page config to remove it (cog next to the description).

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)

 `npx webpack-cli info` is irrelevant here

**Comment by alexander-akait** [comment]
Fixed
