### ISSUE TITLE
WDS disconnect

### ISSUE THREAD

**Issue by lixinliang** [webpack/webpack-dev-server#512]
![image](https://cloud.githubusercontent.com/assets/9375027/16253796/274f9706-386c-11e6-9d47-c1a51ec3da00.png)

I do not want to see that, so how should i do?

my command like that.

![image](https://cloud.githubusercontent.com/assets/9375027/16253800/309cf3f8-386c-11e6-8301-2efdae6f23ea.png)

and my webpack.dev file just use these setting.

![image](https://cloud.githubusercontent.com/assets/9375027/16253830/622ce1bc-386c-11e6-982b-b8f4f48a54be.png)

**Comment by SpaceK33z** [comment]
When exactly do you see that error? And does the rest (reloading) work correctly?

**Comment by lixinliang** [comment]
If I open the website in browser with the localhost that it will work.
But, It will show this error when I open the website in the other address by proxy tool.

**Comment by SpaceK33z** [comment]
What is this proxy tool? It probably blocks the websocket from communicating.

**Comment by lixinliang** [comment]
Charles.
For example, I map `web.me.yy.com/index.html` to `172.26.129.111:8080/index.html`.
Then I open `web.me.yy.com/index.html` on my phone, and I can see the request `web.me.yy.com:8080/sockjs-node/info?t=xxx` in Charles.
And the log show `Disconnected`.
I know the request will be failed because I only map the address instead of domain.

I can dev the website and see the result immediately on Chrome because webpack hot reload.
But, I need to ensure the website is ok on mobile.
So I will check again on my phone.

Is there any configuration that hide the `Disconnected` log and keep the hot reload working?

**Comment by SpaceK33z** [comment]
Ah, if you're port forwarding to another port, you can't use `--inline`. I also had this problem using vagrant, and to fix it you will need to manually include the webpack-dev-server script.

In `index.html` (generated using `html-webpack-plugin`), I added `<script src="/webpack-dev-server.js"></script>`. Also make sure that your proxy allows websockets to pass through.

**Comment by lixinliang** [comment]
Well, I've got it, probablely.. I will try it later. THX.
