### ISSUE TITLE
dev server failed to serve requests with domain name

### ISSUE THREAD

**Issue by richdyang** [webpack/webpack-dev-server#513]
I start dev server in localhost:3000.

When I accessed my AngularJS app with http://localhost:3000, all things went well.

But then I used a chrome extension 'Host Switch Plus" to make a domain "example.com" map to localhost:3000.

Now when I open my index page with http://example.com/, the index page was loaded successfully, but the embedded js and css were loaded failed.

For example, this is the request of http://example.com/polyfills.bundle.js

- Request

```text
GET http://example.com/polyfills.bundle.js HTTP/1.1
Host: example.com
Proxy-Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2777.0 Safari/537.36
Accept: */*
Referer: localhost:3000
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4
```

- Response

```text
HTTP/1.1 404 Not Found
X-Powered-By: Express
Access-Control-Allow-Origin: *
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 51
Date: Sun, 26 Jun 2016 06:22:46 GMT
Connection: keep-alive
```

But when I accessed this js with http://localhost:3000/polyfills.bundle.js, I can load it.

What's the cause? And does webpack dev server support domain binding?

**Comment by SpaceK33z** [comment]
`webpack-dev-server --host 0.0.0.0` should fix this.
