### ISSUE TITLE
http/2?

### ISSUE THREAD

**Issue by kevinSuttle** [webpack/webpack-dev-server#516]
I'm sure this has been documented somewhere, but I would love to see http/2 as the default in Webpack 2.x.

**Comment by SpaceK33z** [comment]
That would be very nice :)!

**Comment by SpaceK33z** [comment]
I think it would make more sense to only enable it when `--https` is passed, because http/2 requires a secure connection.

**Comment by kevinSuttle** [comment]
I believe localhost allows non-secure?

**Comment by SpaceK33z** [comment]
No, it also needs https on localhost unfortunately (see also the example on [node-http2](/molnarg/node-http2)).

I tried setting this up, but [apparently the `http2` package does not work with Express yet](/molnarg/node-http2/issues/100).

**Comment by SpaceK33z** [comment]
Update on this situation the [`spdy`](https://github.com/indutny/node-spdy) package actually supports http/2. The name is very confusing, as SPDY itself is dead, but it works with HTTP/2 and Express. So that's very interesting...

**Comment by SpaceK33z** [comment]
https://github.com/indutny/node-spdy/issues/276 is probably the last roadblock before we can begin implementing this.

**Comment by SpaceK33z** [comment]
Above issue was fixed. Unfortunately another blocker: https://github.com/sockjs/sockjs-node/pull/213
I tested everything, and after that PR is merged it works :).

**Comment by SpaceK33z** [comment]
Done! See 25cbf8437aa08bf70d6d6304158dac90c10df8cc.
