### ISSUE TITLE
watch-poll uses a lot of CPU in Windows 7 x64

### ISSUE THREAD

**Issue by davewthompson** [webpack/webpack-dev-server#517]
Using the --watch-poll option of the dev server uses 30% of CPU.

Using the standard --poll option uses normal CPU.

Windows 7 x64, 32GB RAM.

**Comment by SpaceK33z** [comment]
This is a problem in watchpak, and there is already a ticket for that over here: webpack/watchpack#2. But if `--poll` works, then it is always better to use that, because it uses native file listeners to check for updates.

**Comment by oscdeveloper** [comment]
Open file:
`\node_modules\watchpack\lib\DirectoryWatcher.js`
Go to line: 52, it's about:
```
	this.watcher = chokidar.watch(directoryPath, {
		ignoreInitial: true,
		persistent: true,
		followSymlinks: false,
```
Add this:
`ignored: /node_modules/,`

Save file and run again webpack with ---watch-polls option.
Ex:
`gulp.task('webpack', plugins.shell.task('webpack --config ./config/webpack.dev.js  --watch --watch-poll'));`
