### ISSUE TITLE
Reload code even with white-space changes

### ISSUE THREAD

**Issue by dizzyn** [webpack/webpack-dev-server#524]
Can I force the reload even if "Nothing changed" from code functionality point of view. When I modify whitespace for eslint rules like "no-trailing-spaces" etc. The dev-server will skip the reload process.

I use:
- webpack-dev-server (1.14.1)
- eslint-loader (1.3.0)
- eslint (2.9.0)

My configuration looks this way:

```
loaders: [
            {
                test: /\.js?$/,
                exclude: /(node_modules)/,
                loader: ['babel-loader', 'eslint-loader']
            },
```

Thank you.

**Comment by SpaceK33z** [comment]
Do you also have this issue when using `eslint-loader` in `preLoaders` (see [docs](https://github.com/MoOx/eslint-loader#usage))?

**Comment by dizzyn** [comment]
Hi, yes. It does the same even with the configuration:

	module: {
		loaders: [{
				test: /\.js?$/,
				exclude: /(node_modules)/,
				loader: ['babel-loader']
			},		
		],
		preLoaders: [
  			{test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
		]
	}

**Comment by SpaceK33z** [comment]
Okay, a PR is welcome to fix this. For inspiration, look at #510.

**Comment by SpaceK33z** [comment]
I was wondering, is this really necessary? Because if you see 'nothing changed', you know that there are no errors anymore, right? Or does it still say that even when there are still errors?

**Comment by dizzyn** [comment]
yes. if there is an error for the eslint and i fix that, it says 
'no chnges' but the error is still reported.

**Comment by SpaceK33z** [comment]
We should wait on https://github.com/webpack/webpack/pull/3427 for this, after that perhaps a manual flag isn't necessary anymore.

**Comment by shellscape** [comment]
While we'd still love to get a PR for this enhancement, this issue is very old and for that reason and inactivity we're going to close. It doesn't appear to be affecting many users to the point where there's an urgent call for this change.
