### ISSUE TITLE
Make webpack server listen on both locahost addresses

### ISSUE THREAD

**Issue by sherlock1982** [webpack/webpack-dev-server#5260]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

DevServer has a host parameter. I'd like it to listen on both IPv4 and IPv6 addresses which I belive should be the default behavior. But I can't. The issue is developers access it like http://localhost:port and depending on the DNS either IPv4 or IPv6 is selected causing request to stale much longer. 

If host=:: it works for both 127.0.0.1 and ::1 but also listens on all possible IPs which I don't want. But this is the closest I can get.
If host=127.0.0.1 or host=::1 it listens on corresponding IP only and not what i want
If host=localhost (or default) it listens on ::1 only

### Your Proposal for Changes

If host=localhost (or default) it should listen on both ::1 and 127.0.0.1

**Comment by alexander-akait** [comment]
> If host=:: it works for both 127.0.0.1 and ::1 but also listens on all possible IPs which I don't want. But this is the closest I can get.
> If host=127.0.0.1 or host=::1 it listens on corresponding IP only and not what i want
> If host=localhost (or default) it listens on ::1 only

That like `listen` works - https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback

If you want to improve it please open an issue in `Node.js` repo, we can't fix it here. 

More precisely, there is a solution, but I don’t think it’s worth the effort. We can do the same https://github.com/fastify/fastify/issues/3536, but we are a dev server, so ipv6 is not widely used, the solution also requires additional memory consumption, that is bad for dev server. 

Anyway feel free to feedback.
