### ISSUE TITLE
How to force refresh from another script?

### ISSUE THREAD

**Issue by PierBover** [webpack/webpack-dev-server#528]
So the server does auto refresh when JS files are modified. Cool.

But I'm also working with other files such as Sass files. These have its own script watching for changes to compile the CSS. Of course when this happens the server doesn't auto refresh.

So is there way to tell the server to refresh from another node script?

**Comment by SpaceK33z** [comment]
I know it's not a real solution to your problem, but is it not possible to let webpack compile these Sass files?

**Comment by PierBover** [comment]
Since I don't use `require()` or `import` of CSS files I'm not sure Webpack would compile those. Would it?

Also I'm using `bourbon` and other sass libraries which makes sass compiling last a few seconds. I wouldn't want Webapck to compile sass every time there is a JS change.

I don't think I'd have much control over those things with Webpack compared to Gulp or simple Node scripts.

**Comment by SpaceK33z** [comment]
In your entry JS file, you can import your Sass like `import 'styles/style.scss'`. If you install the [sass-loader](https://github.com/jtangelder/sass-loader), it will pickup this file and build it as a separate file. When devving, it will only re-compile your sass when something has changed.

**Comment by PierBover** [comment]
Sounds great.

But then how can I tell `sass-loader` to build to a specific file?

**Comment by SpaceK33z** [comment]
For that, you'd need [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin). The setup and documentation is a bit cryptic, but if you search on `webpack sass example`, you'll surely find some nice examples.

**Comment by SpaceK33z** [comment]
@PierBover, can you close this issue if you're satisfied?
