### ISSUE TITLE
Access to CSS props via javascript object when HOT and INLINE set?

### ISSUE THREAD

**Issue by ianjohnspain** [webpack/webpack-dev-server#529]
Hi,

My production build creates a separate CSS file so the following works great at production runtime.

```
import '../../images/icon.png';

console.log(styles); // outputs object  in production but empty object in dev server run
console.log(styles.mydiv);  // outputs object  in production but undefined in dev server run

// using ES 2015 string interpolation, notice back ticks
    `<div class="${styles.mydiv}">`
```

On a dev server run, the variables are NOT available but the class is loaded via css as i see it. The javascript object isn't getting populated probably due to the fact that I am not passing modules to the css-loader - I presume?

Here is the command i am using

`      "webpack-dev-server --history-api-fallback --inline --hot --progress"`

```
config.devServer = {
        contentBase: './src',
        stats: 'minimal',
        port: port
 }
```

In dev mode I have the following, 
`ExtractTextPlugin.extract('style', 'css?sourceMap&localIdentName=[local]!postcss')`

and production the following (notice the modules being passed in)
`ExtractTextPlugin.extract('style', 'css?modules&sourceMap&localIdentName=[local]!postcss');`

If I change the dev mode to add the modules to the querystring, then sure enough it now works BUT it causes a refresh of the browser everytime I load.

A little stuck, can anyone help ?

Thanks

**Comment by ianjohnspain** [comment]
Oh, I forgot to mention, I am using Angular v1 with the above :-)

**Comment by SpaceK33z** [comment]
If you leave `modules` out of the query string, the CSS doesn't get parsed as a CSS module, causing `styles` to be empty.

CSS hot reloading doesn't work with `ExtractTextPlugin` unfortunately. See also #542 about this.
