### ISSUE TITLE
local-ip host choice wrong IP from the bridge0 network adapter and not more from en0

### ISSUE THREAD

**Issue by xelaz** [webpack/webpack-dev-server#5293]
### Bug report

After update to the version 5.1.0 the local-ip as hostname is not the same. Before update if i choice local-ip for the devServer.host, IP was taken from the en0 Adapter.

### Actual Behavior
If i set on Mac/Win the devServer.host as local-ip the IP will be get from the brige0 Newtork Adapter.
This is the probleme if i work in my company Network, the devServer is not more available and is only local pn my machine

### Expected Behavior
In the last it was every time the IP from the en0 Network Adapter.
Now if i want run devServer on the en0 Adapter i must set the devServer.host as 0.0.0.0

If this is what you want, then I would also like to read it in the ChangeLogs

**Comment by alexander-akait** [comment]
This is expected change due https://github.com/webpack/webpack-dev-server/issues/4630 and if you need to return the old behaviour you can use https://github.com/silverwind/default-gateway and use it in `host`
