### ISSUE TITLE
issues with 'lazy:true' 

### ISSUE THREAD

**Issue by necolas** [webpack/webpack-dev-server#53]
(webpack-dev-server 1.6.1)

Using the example in the docs - http://webpack.github.io/docs/webpack-dev-server.html#api - displayed `Connecting to socket.io server...` and didn't serve or build assets. I tried hitting the expected paths for all the assets (because it's meant to rebuild only on request for entry file), but no joy.

Removing `lazy:true` from the config fixed the problem.

**Comment by SpaceK33z** [comment]
@necolas, do you still have this issue? It's fairly old, and a lot has changed since 2014 :).

**Comment by necolas** [comment]
I don't know
