### ISSUE TITLE
Server can't be accessed via IP 

### ISSUE THREAD

**Issue by honger05** [webpack/webpack-dev-server#530]
see #147 

How did I use express to do?

````js
var devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  hot: true,
  stats: {
    colors: true,
    chunks: false
  }
})

// use express
app.use(devMiddleware)

app.listen(port, host, function (err) {
  if (err) {
    console.log(err)
    return
  }
  console.log('Listening at ' + host + ':' + port + '\n')
})
````

It didn't work!

**Comment by honger05** [comment]
sorry,    It works.  

There is another error case...

**Comment by sytpb** [comment]
how to do with Express + react ?　　which file to change ?      it didn't work when i adding   "devServer": {
    "contentBase": ".",
    "host": "0.0.0.0",
    "port": 3001,
    "disableHostCheck": true
  } to my client package.json
