### ISSUE TITLE
proxy converts headers to lowercase

### ISSUE THREAD

**Issue by philjones88** [webpack/webpack-dev-server#534]
Scenario:

Angular2 app uses the Location header returned by our API. When developing using the webpack-dev-server and proxying to the proper server and it's API the header is parsed `location` but when accesses via the proper server (OWIN Self Host) it's `Location` and my code breaks due to the casing difference.

Normally it's pretty easy to code around this but I'm using Angular2 header's `has('string here')` method to check headers and I don't want to muddy my code.

Is there a setting to turn on to stop this conversation to lowercase?

Versions:
```
"webpack": "1.13.1",
"webpack-dev-server": "1.14.1",
```

**Comment by chimurai** [comment]
**HTTP message header field names** are case-insensitive according to the specs:
- https://tools.ietf.org/html/rfc7230#section-3.2
- https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

From https://nodejs.org/api/http.html :
HTTP message header keys are lowercased.

**Comment by SpaceK33z** [comment]
What @chimurai said makes sense. This is not a problem in WDS, and it wouldn't make sense to fix this here because of a very specific use-case in Angular.
