### ISSUE TITLE
Deduplicate some of the error messages?

### ISSUE THREAD

**Issue by alexzherdev** [webpack/webpack-dev-server#540]
As mentioned in https://github.com/facebookincubator/create-react-app/issues/263, it would be nice if we could get rid of some of the repetition in the error messages like `[WDS] Disconnected!`. Would it be something that you could be interested in? I can try to come up with a PR. (it would also be nice to know if there are any other messages apart from the one above that could benefit from deduplication)

**Comment by SpaceK33z** [comment]
This would be very nice to have! The duplicated messages interfere with searching for actual logs.

**Comment by SpaceK33z** [comment]
Related: #109

**Comment by tudorgergely** [comment]
How about adding an option like --suppress-logs ? That would actually make them optional (so maybe if someone wants to see the logs he can still do so)

**Comment by SpaceK33z** [comment]
Closing in favor of #109, but a PR is still welcome!
