### ISSUE TITLE
emits all chunks after every change

### ISSUE THREAD

**Issue by ouqinglai** [webpack/webpack-dev-server#546]
can whick file change whick chunk emit?

**Comment by SpaceK33z** [comment]
Could you explain this in more detail?

**Comment by ouqinglai** [comment]
@SpaceK33z webpack.config.js `entry : { a : [a.js] , b : [b.js] }`  when I change a.js file ,then webpack-dev-server will bundle the b.js again? I want only a.js file bundle , like `webpack --watch`  thanks!
