### ISSUE TITLE
Cant run webpack-dev-server inside of a docker container?

### ISSUE THREAD

**Issue by ShashankaNataraj** [webpack/webpack-dev-server#547]
Everything works fine when I want to run this through my local webpack server. I want to pack [this project](https://github.com/ShashankaNataraj/todolist-nodejs-react) into a docker container.

The main page does get served with all the CSS assets intact, but none of the javascript within seems to have come through. I get this error message on my chrome console:

<img width="1289" alt="screen shot 2016-08-03 at 6 20 26 pm" src="https://cloud.githubusercontent.com/assets/650317/17392032/363132a0-5a38-11e6-9e2a-0f018dd6a544.png">

My Dockerfile looks like this:

```
FROM node

# Prepare app directory
RUN mkdir -p /usr/src/app
ADD . /usr/src/app

# Install dependencies
WORKDIR /usr/src/app
RUN npm install

# Build the app
RUN npm build

# Expose the app port
EXPOSE "80:3000"
EXPOSE 885
EXPOSE 3001

# Start the app
CMD node build/server.js
```

Im using docker compose with the following config:
```
web:
  build: .
  ports:
    - '80:3000'
    - '885:885'
    - '3001:3001'
  command: npm start
```
Do I need to expose any other ports? Is there a workaround to this?

**Comment by SpaceK33z** [comment]
Did you read "[Webpack and Docker for Development and Deployment](https://medium.com/@andyccs/webpack-and-docker-for-development-and-deployment-ae0e73243db4#.v0vhqvvjl)"? It explains the setup quite well.

**Comment by ShashankaNataraj** [comment]
I just lifted over the .dockerfile and .dockerignore from that post and everything works now. Thanks for the tip!

**Comment by SpaceK33z** [comment]
Cool! Could you close this issue?

**Comment by merapi** [comment]
can be helpful for somebody:
change the binding address to 0.0.0.0

`"start": "node_modules/.bin/webpack-dev-server --host 0.0.0.0",`
or
```
  devServer: {
    host: '0.0.0.0',
    port: 80,
    ...
}
```

**Comment by adamhenson** [comment]
Since you're using docker-compose with a container name `web`, the hostname `web` within the network created would be available. [Documentation on the networking feature of docker-compose here](https://docs.docker.com/compose/networking/). You could use it in a similar way to @merapi's answer:
```
devServer: {
    host: 'web',
    ...
}
```

**Comment by kamil-kielczewski** [comment]
@merapi what if I wanna use subdomains eg my-project.local:3002 ?

**Comment by grebenyuksv-preply** [comment]
https://github.com/jakedeichert/react-starter/issues/19#issuecomment-299155489

**Comment by JeremyXu555** [comment]
> can be helpful for somebody:
> change the binding address to 0.0.0.0
> 
> `"start": "node_modules/.bin/webpack-dev-server --host 0.0.0.0",`
> or
> 
> ```
>   devServer: {
>     host: '0.0.0.0',
>     port: 80,
>     ...
> }
> ```

works like a charm!!!

**Comment by nacengineer** [comment]
> Did you read "[Webpack and Docker for Development and Deployment](https://medium.com/@andyccs/webpack-and-docker-for-development-and-deployment-ae0e73243db4#.v0vhqvvjl)"? It explains the setup quite well.

Linking to a paid article as the solution to a question in an open source forum, while understandable, is sus.

**Comment by Jacrys** [comment]
>Linking to a paid article as the solution to a question in an open source forum, while understandable, is sus.

As is not understanding that the web, and the resultant sites on there, change over time. In ***2016***, when this was written, Medium was not a subscription service, and subsequently, neither was this article.  Medium went partially sub in 2017, doubled down in 2018 and 2019.   I feel it would be more useful to the conversation for one to contribute a useful alternative for people finding this rather than criticizing someone for the current state of a contribution made 4 years ago in a landscape that evolves daily.
