### ISSUE TITLE
Need option for setting title of tab/window

### ISSUE THREAD

**Issue by EmKayDK** [webpack/webpack-dev-server#549]
When running multiple instances of webpack-dev-server, you have to remember which port is used for which of your sites.
![webpack-dev-server](https://cloud.githubusercontent.com/assets/2813397/17474855/66adeee6-5d58-11e6-9079-867b106d8d41.png)

If it was possible to set a title for the tab/window, it would greatly improve usability.
I'm thinking something like
`webpack-dev-server --window-title "Application 1"`

**Comment by tudorgergely** [comment]
You should not need that. Just set the title attribute of the HTML document you are serving

**Comment by EmKayDK** [comment]
It has already been set, but since it is served through an iframe it does not find its way all the way to the title of the tab/window.

**Comment by Klotair** [comment]
A more generic asking would be: Is there any way to pass a parameter to the webpack-dev-server cmd and retreive it in my page as a global javascript variable?
I'm searching a solution to get which profile "dev" or "prod" was used in my application.

**Comment by SpaceK33z** [comment]
In v2 beta, the iframe has been removed, so this is not a problem anymore. I don't think it's important enough to fix this in v1.
