### ISSUE TITLE
How to catch errors with webpack-dev-server.js

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack-dev-server#55]
I'm wondering how to catch errors with webpack-dev-server.js.  I simply want to be able to show an alert error message if the browser console is closed.  I seem to remember sokra posting some code for that but I can't find it.  Basically I want to be able to be able to run a bit of code from my server template if it is in devel mode.

**Comment by SpaceK33z** [comment]
Old ticket, but if you're still interested: #542 has a nice example of how to listen to messages from the Node server. You'd need to find out what data is sent exactly when there is a disconnect, but it should be possible...

**Comment by SuperOl3g** [comment]
Hi there!
Faced with same problem. Does exist any solution to show pretty disconnect message on page for today?
