### ISSUE TITLE
setup option is not documented

### ISSUE THREAD

**Issue by mjomble** [webpack/webpack-dev-server#553]
A very useful `setup` option was added in 6e0e95c5f0

But it's not yet documented [here](http://webpack.github.io/docs/webpack-dev-server.html), so I didn't find out about it until I actually read the source code.

Would be helpful to document it. I may be able to submit a PR if needed.

**Comment by SpaceK33z** [comment]
You can edit the doc page you've linked by clicking `Edit` at the top-right corner. This repo doesn't contain the docs.

**Comment by mjomble** [comment]
Ah. In any case, I'd be more comfortable with the developers documenting it. But if they are too busy, I can have a go at it.

**Comment by SpaceK33z** [comment]
Yeah they are very busy. Also note that work has started to completely overhaul the docs ([webpack/webpack.io](webpack/webpack.io)), but that will take a while, so I think it's worth it to add this to the current docs.

**Comment by mjomble** [comment]
Ok, I've edited the wiki page.
