### ISSUE TITLE
Integration with browsersync

### ISSUE THREAD

**Issue by Devric** [webpack/webpack-dev-server#56]
Im using gulp + browsersync

Is it possible to use hot loading with the stack?

**Comment by timkelty** [comment]
I'm in the same boat - I need a callback for rebuild to send to browsersync to trigger a refresh.

Anyone know how to achieve this?

**Comment by Va1** [comment]
Have a look at this: https://github.com/Va1/browser-sync-webpack-plugin

**Comment by ucorina** [comment]
It seems that this is actually possible using `webpack-dev-middleware` and `webpack-hot-middleware`. BrowserSync provides a nice recipes on how to set this up here: https://github.com/BrowserSync/recipes/tree/master/recipes/webpack.react-hot-loader

**Comment by morlay** [comment]
A Simple CLI:
https://github.com/morlay/webpack-browser-sync

**Comment by koistya** [comment]
One more example in [React App SDK](https://github.com/kriasoft/react-app)
>
>
