### ISSUE TITLE
listeners added with `addEventListener` do not fire in 1.15.0

### ISSUE THREAD

**Issue by neight-allen** [webpack/webpack-dev-server#564]
Attempt at simple steps to reproduce:

#### Setup
`webpack.config.json` and `package.json` from [this repo](https://github.com/turingschool-examples/client-side-storage)

lib/index.js:
```js
document.addEventListener('click', function() {
  console.log('click!');
}
```

1. `npm install` (installs webpack-dev-server 1.15.0)
1. Start dev server (with `npm start`)
2. Visit http://localhost:8080/webpack-dev-server/
3. Click anywhere in the window

#### Expected result

console has `click!` logged

#### Actual result

console is empty

#### Known workarounds

- Visit http://localhost:8080/ instead
- Use webpack-dev-server 1.14.1

**Comment by SpaceK33z** [comment]
Thanks for the nice bugreport! Could you check if the workaround in #559 works for you?

**Comment by neight-allen** [comment]
As a matter of fact, it does! The workaround in #559 also fixes keydown events, which weren't working. I think possibly because you could never focus the iframe prior to the workaround.

**Comment by SpaceK33z** [comment]
Okay, awesome. There will be a patch release in not too long.

**Comment by SpaceK33z** [comment]
@fkrauthan, yes.

**Comment by SpaceK33z** [comment]
Closing since there was a `1.15.1` and `2.1.0-beta.2` release.
