### ISSUE TITLE
Is there a way to hot reloading clear console ?

### ISSUE THREAD

**Issue by ale-batt** [webpack/webpack-dev-server#565]
When the code is hot reload, is there a chrome/firefox plugin or anything to show the seperation from the reload in the console ?

Or add something like `console.log("--------------------------------------");` to separate them ?

**Comment by SpaceK33z** [comment]
You could hack into hot reload messages like this:

```js
window.addEventListener('message', function onWebpackMessage (e) {
  // do something
});
```

**Comment by ale-batt** [comment]
Awesome ! It's perfectly work !

**Comment by tavurth** [comment]
For copy pasters:
Add this to your apps `index.js`:

```
// Clear after module reload
window.addEventListener('message', e => {
    if ('production' !== process.env.NODE_ENV) {
        console.clear();
    }
});
```

**Comment by szalapski** [comment]
This works, but I think most would want to clear BEFORE the reload, so that any errors during the reload would still be shown.

**Comment by alex3683** [comment]
@szalapski I'm using vue-cli and don't know if it changes something on the messages sent by the webpack-dev-server, but in my case this works:

```js
window.addEventListener('message', e => {
  if (process.env.NODE_ENV !== 'production' && e.data && e.data.type === 'webpackInvalid') {
    console.clear();
  }
});
```
So the console will be cleared as soon as webpack detects the change (at least that's what I think `webpackInvalid` is used for ...).

**Comment by szalapski** [comment]
I don't appear to ever have "e.data".  I have e.payload and e.source, and nothing in them seems to distinguish a HMR-reload event from any other.

**Comment by alex3683** [comment]
@szalapski Which version of the dev server are you running? Mine is the latest, `3.1.8`.

**Comment by szalapski** [comment]
How do I find that?  I don't see a "devServer" anywhere in my .js files.

**Comment by szalapski** [comment]
This seemed to work better for me.

`if (module.hot) {
    module.hot.accept() // already had this init code 

    module.hot.addStatusHandler(status => {
        if (status === 'prepare') console.clear()
    })
}`

See also https://stackoverflow.com/a/53933757/7453 .
