### ISSUE TITLE
No module factory available for dependency type: CommonJsRequireDependency

### ISSUE THREAD

**Issue by aarkerio** [webpack/webpack-dev-server#573]
**Problem**: if I run "webpack" command in the command line all works fine and the bundle.js file is generated, but if I run  "webpack-dev-server" I'm getting: 

**Error: No module factory available for dependency type: CommonJsRequireDependency**  

If I remove the "new GlobalizePlugin" section (but I left "webpack.ProvidePlugin jQuery" section) in my webpack.config.js file, I can launch webpack-dev-server successfully. So I'm guessing GlobalizePlugin is the problem here.  

**Error message:**

manuel@linux$ webpack-dev-server --content-base build
 http://localhost:8080/webpack-dev-server/
webpack result is served from /app/assets/
content is served from /home/manuel/entwicklung/rails/chipotle/schnell/app/assets/frontend/javascripts/build
/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:151
				throw e;
				^
Error: No module factory available for dependency type: CommonJsRequireDependency
    at Compilation.addModuleDependencies (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:181:20)
    at Compilation.processModuleDependencies (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:170:7)
    at /usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:320:12
    at /usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/usr/local/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)

My webpack.config.js file:

```
var path = require('path');
var webpack = require('webpack');

var GlobalizePlugin = require('globalize-webpack-plugin');

module.exports = {
  entry: {
    app: ["./entry.js"]
  },
  output: {
    path: path.resolve(__dirname, "build"),
    publicPath: "/app/assets/",
    filename: "bundle.js"
  },
  module: {
    loaders:  [
                {test: /\.jsx?$/, loader: 'babel', exclude: /node_modules/,  query: {
                                 cacheDirectory: true,
                                 presets: ['react', 'es2015', 'stage-0', 'survivejs-kanban']
                                }, include: path.app
                },
                { test: /\.css$/, loader: 'style-loader!css-loader'},
                { test: /\.js$/, loader: 'babel', exclude: /node_modules/},
                { test: /\.less$/, loader: 'style!css!less' },
                { test: /\.scss$/, loader: 'style!css!sass' },
                { test: /\.json$/, loader: "json-loader" },
                { test: /\.woff(2)?(\?v=[0-9].[0-9].[0-9])?$/, loader: "url-loader?mimetype=application/font-woff" },
                { test: /\.(ttf|eot|svg)(\?v=[0-9].[0-9].[0-9])?$/, loader: "file-loader?name=[name].[ext]" },
                { test: /\.gif$/, loader: "url-loader?mimetype=image/png" }
              ]
  },
  node: {
     fs: "empty"
  },
  plugins: [
       new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        }),
        // Globalize modules are wrapped by UMD offering AMD, CJS and global choices. Webpack tries to use AMD (the one that appears first) 
        // and can't resolve paths correctly. globalize-webpack-plugin makes webpack to use CJS over AMD in globalize packages, 
        new GlobalizePlugin({
           production: false,
           messages: "messages/[locale].json", // messages (not optional)
           developmentLocale: "en",
           supportedLocales: ["en"],
         output: "i18n/[locale].[hash].js"
    })
    ]
}; 

```

**Comment by SpaceK33z** [comment]
As you say yourself, this seems to be a problem in the globalize plugin, not webpack-dev-server.

**Comment by aarkerio** [comment]
Thanks a lot SpaceK33z,  my mistake. I think this issue can be closed.
