### ISSUE TITLE
webpack-dev-server 1.15.1 proxy error: depth_zero_self_signed_cert 

### ISSUE THREAD

**Issue by eyakcn** [webpack/webpack-dev-server#583]
Because I configure dev server to proxy to a back-end API which uses a self-signed certification.

I tried to set:

NODE_TLS_REJECT_UNAUTHORIZED = 0

but with no luck to avoid such error. I know it's unsafe, but I only want to allow it in my develop environment

**Comment by SpaceK33z** [comment]
Have you tried adding `secure: false` in the proxy config? E.g. `proxy:{ '/api/**': { target: 'https://localhost:4001', secure: false } } `

**Comment by SpaceK33z** [comment]
Also see config options for proxy: https://github.com/chimurai/http-proxy-middleware

**Comment by eyakcn** [comment]
Oh, yes, it works. Thank you for your help
