### ISSUE TITLE
Flexible reconnection timeout

### ISSUE THREAD

**Issue by just-boris** [webpack/webpack-dev-server#585]
> Originally from [this tweet](https://mobile.twitter.com/dan_abramov/status/771765006950141952).

When development server gets disconnected, your console will be full or error messages.
 
<img height="300" src="https://cloud.githubusercontent.com/assets/812240/18218906/03c38fa8-7166-11e6-89b4-18a67de63985.png">

Now it reconnects every two seconds, so you will get about 30 errors in a minute. It would be better to have increasing intervals after each attempt. The example of this approach you can find in the [`got`](https://github.com/sindresorhus/got) npm-module, that has smart logic of retries, see [description](https://github.com/sindresorhus/got#retries)

**Comment by SpaceK33z** [comment]
Haha, I made a ticket for exactly this 4 hours ago, #584.

**Comment by SpaceK33z** [comment]
Thanks for the link to `got` btw, I ended up using the exact same "algorithm" for my PR (#589).
