### ISSUE TITLE
Create issue & PR template

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack-dev-server#587]
There are some consistent problems with issues and PR's. I've inventoried the most common problems.

Issues often:

- Lack version information.
- Lack a minimal example.
- Are not webpack-dev-server issues. 
- Are questions, not bugs / feature requests.

PR's often:

- Don't describe a use-case for the scenario.
- Break other use-cases (with the new `examples/` folder this should be less of an issue).
- Are too specific to one person's need.

Next step: create a GitHub issue template.

**Comment by bebraw** [comment]
You can likely adapt one from the main repository. See [here](https://github.com/webpack/webpack/tree/master/.github).
