### ISSUE TITLE
Zombie process webpack-dev-server

### ISSUE THREAD

**Issue by lamo2k123** [webpack/webpack-dev-server#591]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 1.13.2 
webpack-dev-server: 1.15.1

**Please tell us about your environment:**
OSX 10.x / Linux

After stop webpack-dev-server remains process webpack-dev-server zombie.

**Comment by lamo2k123** [comment]
SIGINT 
ctrl+c / cmd+c

**Comment by SpaceK33z** [comment]
Weird, I'm on OS X too and I never had this bug. Does this also happen when you add `--stdin` as a flag?

**Comment by lamo2k123** [comment]
Command `webpack-dev-server --config webpack --hot --inline`

**Comment by SpaceK33z** [comment]
> Does this also happen when you add `--stdin` as a flag?

**Comment by lamo2k123** [comment]
You can reproduce this bug using this project: https://github.com/lamo2k123/bp.

command: npm i && npm run development

**Comment by SpaceK33z** [comment]
Okay, but can you please give an answer to my question?

**Comment by lamo2k123** [comment]
not work --stdin

**Comment by SpaceK33z** [comment]
I can reproduce the problem in your repo, but if I comment `new DaemonCommandPlugin('start')`, it works. So I don't think this is a problem of the dev-server.

**Comment by lamo2k123** [comment]
oh lol ))
