### ISSUE TITLE
contentBase in webpack.config is ignored

### ISSUE THREAD

**Issue by wouterverweirder** [webpack/webpack-dev-server#597]
webpack: 2.x 
webpack-dev-server: 2.1.0-beta.3
OSX 10.x

**Current behavior:**

When specifying a contentBase in your webpack.config file (and running webpack-dev-server from the command line, without any arguments), it is ignored & overwritten with the current path

**Expected/desired behavior:**

contentBase from the config file should be used

This bug was introduced by commit be9efdaa2e4539cd90eab27494a965c500c03320

**Comment by MoOx** [comment]
The thing is: the [default config defined by yarg create an argv["content-base"]](https://github.com/webpack/webpack-dev-server/blob/02db2005cc93dbb27076a22d5a8db1b9f6fe8fe9/bin/webpack-dev-server.js#L93) so indeed, when you define contentBase via webpack.config.js devServer section, your option is overridden by [the code testing the argv](https://github.com/webpack/webpack-dev-server/blob/02db2005cc93dbb27076a22d5a8db1b9f6fe8fe9/bin/webpack-dev-server.js#L187).
