### ISSUE TITLE
use proxy  can not hot update

### ISSUE THREAD

**Issue by beliefgp** [webpack/webpack-dev-server#600]
webpack: 1.10.x
webpack-dev-server: 1.15.x
OSX 10.x 

```
// webpack-dev-server/lib/Server.js code
sockServer.installHandlers(this.listeningApp, {
     prefix: '/sockjs-node'
});
```

this prefix is unchangeable；
when i use browser proxy，request.url include hostname, it can not work.

example： local.com:2222/sockjs-node/info.js

not use proxy,it can matched an work
`request.url = /sockjs-node/info.js`

use proxy ,it can not matched
`request.url = local.com:2222/sockjs-node/info.js`

**Comment by SpaceK33z** [comment]
So what would your proposed fix be? I'm not sure I understand what you're trying to do here.

**Comment by beliefgp** [comment]
the sockServer prefix can configurable  or  auto match current host

thanks。

**Comment by SpaceK33z** [comment]
Is there an easy way to reproduce this behavior? I've never seen this before.

**Comment by beliefgp** [comment]
my local environment ：  chrome   install  SwitchyOmega ,  config ： http   127.0.0.1   2222

then use  webpack-dev-server

**Comment by SpaceK33z** [comment]
Could you check if https://github.com/webpack/webpack-dev-middleware/pull/80 works for you? The quickest way to test this would be to go to `node_modules/webpack-dev-middleware/middleware.js`, and copy/paste the [new code](https://github.com/ijse/webpack-dev-middleware/blob/4d8c4af2c0f1703d85695aa235443cc3c8d53ec1/middleware.js).

**Comment by beliefgp** [comment]
I am sorry that not this.  The same reason，but not one  problem, but Sockjs on this scheme can be used。

**Comment by SpaceK33z** [comment]
And is it not possible to exclude your dev domain from the proxy? SwitchyOmega seems to have an option for this:

![switchyomega_options](https://cloud.githubusercontent.com/assets/533616/18382741/9bbc612e-7682-11e6-8853-f83d61dea190.png)

**Comment by beliefgp** [comment]
is my current solution。 I just want to make it more simple

**Comment by SpaceK33z** [comment]
I think this is the way it should work, the dev server should not be proxied like that.

**Comment by beliefgp** [comment]
I agree, but it is complex （ configuration host,proxy, and exclude dev server ） when use proxy。
For new user, it is easy to forget.

Thank you anyway。

**Comment by SpaceK33z** [comment]
Yeah I agree, the configuration of dev-server can be (too) complicated. We're working on that though, with stricter validation of the configuration.
