### ISSUE TITLE
feature: Multiple base directories for webpack-dev-server

### ISSUE THREAD

**Issue by gertcuykens** [webpack/webpack-dev-server#603]
I need to serve multiple base directories like [browsersync](https://www.browsersync.io/docs/options#option-server) or polymer-cli do, so I can serve a polymer [element](https://github.com/PolymerElements/seed-element) that has two basedirectories (cwd and bower_components)

As far as I can tell, only one basedirectorie is supported in [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html#content-base)

**Comment by SpaceK33z** [comment]
`contentBase` supports an array of directories.

**Comment by gertcuykens** [comment]
I followed the guidelines and there was no reference in the documentation that contentBase takes a array instead of a string. So it was a feature request. Please make it clear in the [api](https://webpack.github.io/docs/webpack-dev-server.html#api) or [documentation](https://webpack.github.io/docs/webpack-dev-server.html#content-base) that `contentBase` can take a string or array. I will test this now and reopen the issue if it's not the case.
