### ISSUE TITLE
Is 'hot: true' necessary when you've added HotModuleReplacementPlugin?

### ISSUE THREAD

**Issue by rightaway** [webpack/webpack-dev-server#606]
I'm using webpack 1.13.2 and webpack-dev-server 1.15.2 on Linux. Specifying `hot` under `devServer` isn't getting recognized. When I run `webpack-dev-server` the browser console shows `Uncaught Error: [HMR] Hot Module Replacement is disabled`. To eliminate the error message I need to run `webpack-dev-server --hot`.

The other options under `devServer` seem to be recognized though because the port is correctly running as specified there.

```
module.exports = {
  entry: './src/index.js',
  output: {
    path: __dirname + '/build/',
    publicPath: 'build/',
    filename: 'build.js',
  },
  devServer: {
    hot: true,
    inline: true,
    port: 8081,
  },
};
```

**Comment by SpaceK33z** [comment]
This is documented explicitly in the docs, under [API](https://webpack.github.io/docs/webpack-dev-server.html#api);

```
  // Use "webpack/hot/dev-server" as additional module in your entry point
  // Note: this does _not_ add the `HotModuleReplacementPlugin` like the CLI option does. 
```

**Comment by rightaway** [comment]
Interesting, in fact it works if I just add

```
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ],
```

I don't even need to add `webpack/hot/dev-server` or any other entry points, and strangely I don't even need to add `hot: true` under `devServer` and hot reloading still seems to work fine. The only difference when I don't add `hot: true` is that these lines no longer get output to the browser console

```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
```

**Comment by fanyer** [comment]
as for me, it shows [HMR] and [WDS] infos
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
```
 ,however it didn't change the view.......what a fuck!!
Are there any poor guys experienced like me? how to solve it!!!!
