### ISSUE TITLE
when refresh page : localhost:8080/docs/angular~2.0_typescript cant match route

### ISSUE THREAD

**Issue by wangfaxi1985** [webpack/webpack-dev-server#610]
## when refresh page : localhost:8080/docs/angular~2.0_typescript cant match route
when i use history.push({pathname:'/docs/angular~2.0_typescript/'}) can go corrent page
but when i refresh whole page with : http://localhost:8080/docs/angular~2.0_typescript/

chrome page display: 'Cannot GET /docs/angular~2.0_typescript/'

webpack-dev-server config is:
`"start": "webpack-dev-server --config config/webpack/index.js --content-base ./build --history-api-fallback --no-info --open",`

any idea?

webpack: 1.13.0
webpack-dev-server: 1.14.1
 Linux

**Comment by SpaceK33z** [comment]
See https://github.com/webpack/webpack-dev-server/issues/571#issuecomment-242768988.
