### ISSUE TITLE
Setting `devServer.hot` in webpack config does not add HMR plugin

### ISSUE THREAD

**Issue by megapctr** [webpack/webpack-dev-server#611]
**webpack and webpack-dev-server version:**
webpack: 1.13.2 
webpack-dev-server: 1.16.1

**Please tell us about your environment:**
Ubuntu 16.04

**Current behavior:**
hot module replacement is not enabled after modifying `webpack.config.js` like so:
```
  ...
  devServer: {
    hot: true,
    ...
  },
```

HMR _does_ get enabled when I run `webpack-dev-server --hot`.

In fact, I added a simple console log in `bin/webpack-dev-server.js`:

<pre>
if(options.inline) {
  ...
}

<b>console.log(wpOpt, options)</b>

new Server(webpack(wpOpt), options).listen(options.port, options.host, function(err) {
  ...
}
</pre>

and compared output both cases (`--hot` flag not passed, and passed)

```
@elm ~/yak ⌛ > diff a.txt b.txt
22a23
>   plugins: [ HotModuleReplacementPlugin {} ],
```

**Expected/desired behavior:**
setting `devServer.hot` to `true` actually enables HMR

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration. Be sure to specify how you are running the server.** 

webpack config:
```
module.exports = {
    devServer: {
        hot: true,
    },
}
```
Really, this is enough. (maybe the bug happens when the config does not have any plugins? which is also my case)
I run `npm start` which just runs `webpack-dev-server` (or `webpack-dv-server --hot` in the other case)

**Comment by SpaceK33z** [comment]
The [docs](https://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement) state that you also need to add `new webpack.HotModuleReplacementPlugin()` to your `plugins`.

**Comment by megapctr** [comment]
I see, thanks. I thought that the command line arguments translated directly into `.devServer` config

**Comment by alexilyaev** [comment]
Now properly documented:  
https://webpack.js.org/configuration/dev-server/#devserver-hot
