### ISSUE TITLE
Inline stream-cache code, use another module, or convince maintainer to republish

### ISSUE THREAD

**Issue by exogen** [webpack/webpack-dev-server#618]
The current version of `stream-cache` was published with a version of npm that didn't have the benefit of today's default `.npmignore`. As a result the package mistakenly contains ~220K of backup/undo files, which every `webpack-dev-server` user is unfortunately getting.

<img width="846" alt="screen shot 2016-09-21 at 12 43 56 pm" src="https://cloud.githubusercontent.com/assets/53522/18726745/a7e68e4e-7ffa-11e6-82ff-70c9b2764038.png">

I've opened an issue with `stream-cache` [here](https://github.com/felixge/node-stream-cache/issues/3), but it's possible it may never be republished.

I wonder if there's a more modern module that does the same thing, or whether equivalent code would be simple to inline in `webpack-dev-server`?

**webpack and webpack-dev-server version:**
webpack-dev-server: 1.15.x and 2.x

**Comment by SpaceK33z** [comment]
Would you have time to do a PR for this? I'll review it asap.

**Comment by exogen** [comment]
@SpaceK33z Can't today but I'll try this week!

**Comment by SpaceK33z** [comment]
@exogen, what is your plan with this? Since the author of `stream-cache` probably isn't going to do anything. Are you going to look into other packages, or write something yourself?

**Comment by SpaceK33z** [comment]
Apparently the `stream-cache` package isn't even necessary at all. Less code in `lib/Server.js` + one less dependency = win :).
