### ISSUE TITLE
Suppress [HMR] Waiting for update signal from WDS Message

### ISSUE THREAD

**Issue by danielstern** [webpack/webpack-dev-server#624]
This message is useful but once you know HMR is working, the console statement just gets in the way. Can we set a flag to suppress said messages?

**Comment by SpaceK33z** [comment]
You can use `clientLogLevel` for this, see [the changelog](https://github.com/webpack/webpack-dev-server/blob/webpack-1/CHANGELOG.md#1160-2016-09-17) for more info. I think this hasn't been documented yet in docs.

**Comment by SpaceK33z** [comment]
It's documented now, so closing this.
