### ISSUE TITLE
Web worker support

### ISSUE THREAD

**Issue by oskarer** [webpack/webpack-dev-server#628]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.25
webpack-dev-server: 2.1.0-beta.6

**Current behavior:**
`window` is not defined in a web worker

**Expected/desired behavior:**
Check if `window` is defined and/or use `self` when in a worker

By doing this fix; https://github.com/oskarer/webpack-dev-server/commit/2c73af8db3ffd32a1ce78e48b84db764f371c146, I was able to get my React app to hot reload inside a web worker using React Hot Loader. I also used this; https://github.com/web-perf/react-worker-dom/tree/r-15.

Do you have any thoughts about a long term solution?

**Comment by SpaceK33z** [comment]
Hm, I thought we had support for web workers. We're definitely interested in a fix for this. Do you have time for a PR?

**Comment by oskarer** [comment]
I replicated the issue here; https://github.com/oskarer/webpack-dev-server-webworker-test.

The case I have is that I want to hot reload code inside the web worker, not in the main code. Which works fine if `window` is changed to `self`; as seen here https://github.com/oskarer/webpack-dev-server/commit/2c73af8db3ffd32a1ce78e48b84db764f371c146. [`window` and `self` is essentially the same thing in the main thread](https://developer.mozilla.org/en-US/docs/Web/API/Window/self), so this should not break anything.

Do you want me to make a PR with this fix?

**Comment by SpaceK33z** [comment]
@oskarer, yes, a PR would really be appreciated.

**Comment by oskarer** [comment]
https://github.com/webpack/webpack-dev-server/pull/632

**Comment by oskarer** [comment]
Included in v2.1.0-beta.8
