### ISSUE TITLE
devServer.port not working with 2.1.0-beta.6

### ISSUE THREAD

**Issue by nareshbhatia** [webpack/webpack-dev-server#629]
**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.21 
webpack-dev-server: 2.1.0-beta.6

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
devServer.port property is being ignored. App is served on port 8080.

**Expected/desired behavior:**
devServer.port property is honored

**Detail:**
Before upgrading to this version, the following webpack configuration correctly served the app on port 3000:

    devServer: {
        port: 3000,
        inline: true,
        hot: true,
        historyApiFallback: true,
        stats: 'minimal'
    },

This property is now being ignored.

Also I think that the server is spitting out too much info/stats when it is starting up. Is this controlled using devServer.stats?

I can't find either `port` or `stats` documented anywhere. What's the best way to find these?

**Comment by SpaceK33z** [comment]
`port` works for me. I tested this by cloning this repo, going to `examples/modus-inline`. I added `devServer: { port: 3001 }` to the webpack config, and then followed the README to start it. Can you provide more information?

The `stats` option is not really documented. You can find more about it here https://github.com/webpack/webpack/issues/1191. I personally always use `stats: 'errors-only'` in `devServer`.

**Comment by nareshbhatia** [comment]
Thanks, @SpaceK33z. I figured out the issue. My env variable was undefined and hence it was not picking up the correct configuration. My bad!
