### ISSUE TITLE
Uncaught Error: Incompatibile SockJS!

### ISSUE THREAD

**Issue by devrockzz** [webpack/webpack-dev-server#633]
I am using angular cli the latest build and i have tried expected solution for it but it not working plz help   me out  and the webpack version is 2.1.0-beta.22

  I am getting this error on the console loge . 
->sockjs.min.js:2 Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.1", the iframe: "1.0.1".

**Comment by SpaceK33z** [comment]
Please update your post to include the information that is asked when making a new ticket.

**Comment by SpaceK33z** [comment]
Closing issue due to lack of information.
