### ISSUE TITLE
ProxyTable doesn't take port into account

### ISSUE THREAD

**Issue by MadDV** [webpack/webpack-dev-server#634]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 1.12.x
webpack-dev-server: 1.15.x

**Please tell us about your environment:**
OSX 10.11.4
Webpack Vue Cli

**Current behavior:**
When you proxy a url inside webpack config, it doesn't take into account the port of the url you are proxying to. 

Example
`   proxyTable: {
      '/api' : 'http://localhost:4567',
    },`
Will re-route the request to localhost, and not localhost:4567.

* **What is the motivation / use case for changing the behavior?**
So that it works.

 Code:
` dev: {
    env: require('./dev.env'),
    port: 8080,
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {
      '/api' : 'http://localhost',
      '/socket.io' : 'http://localhost/api'
    },`

**Comment by SpaceK33z** [comment]
I tested this using `examples/proxy-simple`, but this does work correctly in webpack-dev-server.

You're using an old version of dev-server (`1.16.1` is already out). Try updating it to see if that resolves the issue.

If that doesn't resolve it, please file an issue on Vue Cli.

**Comment by MadDV** [comment]
Alright I'll try that out, and if it doesn't, file an issue over at the Vue Cli, thanks.
