### ISSUE TITLE
[1.10.x] SFTP file replace doesn't always trigger file watch

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack-dev-server#635]
I'm having difficulty finding an ideal environment suitable for development.  I'm using Gnome Files to mount my VM paths with both NFS and SFTP but there are issues with both of them.  The NFS issue causes the mount to go crazy at 25% CPU when it is inactive for a while.  So I switched to SFTP mount and it works good and I can live without inotify support but the issue is that the files are being replaced instead of modified and this can cause Webpack to lose track of them and to not update.  Then when I SSH into the VM and use vim to modify the file it will cause Webpack to update the resources but then no amount of saving from within Atom will cause Webpack to ever rebuild again on that file.  I can add completely new content and it won't fire off even though I can see that there was a new file there.  When this is broken like this I can modify the up-to-date file with vim (it does get sent over from Atom -> VM file system) and it will then update the webpack build.  This doesn't happen every time but once Webpack breaks then no amount of new file creation will fix it.

I'd rather not use polling methods so for now I'm using NFS and working around this other non-Webpack related issue.

**Comment by SpaceK33z** [comment]
This repository doesn't watch for file changes itself, so unfortunately it is not possible to fix it here. The "watcher" is provided by the [webpack](https://github.com/webpack/webpack) repo, which in turn uses the [watchpack](https://github.com/webpack/watchpack) repo, which uses the [chokidar](https://github.com/paulmillr/chokidar) repo to watch for file changes.

So if you want the underlying issue fixed, your best chances are creating an issue on chokidar.

That said, there are a couple of things you can try:

A) Use polling after all. It its possible to set this with a timeout of e.g. 1000ms, so it's less system intensive;

```js
watchOptions: {
  poll: 1000
}
```

B) Tryout SSHFS, I am not completely sure if that works, but I've used it in the past and it worked for me.
