### ISSUE TITLE
configure fallback path

### ISSUE THREAD

**Issue by oferh** [webpack/webpack-dev-server#636]
**I'm submitting a feature request**

**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.25
webpack-dev-server: 2.1.0-beta.8

**Please tell us about your environment:**
OSX 10.x
Running server via CLI

**Current behavior:**
At the moment fallback path is set to `/index.html` 

**Expected/desired behavior:**
Allow the user to set the path of the fallback 
```
 devServer: {
      historyApiFallback: '/path/to/index.html',
      ...
}
```

**What is the motivation / use case for changing the behavior?**
At the moment when the `contentBase` is not in the root folder the fallback path is set to current directory and not to `contentBase` root. 
by using this option the location of the fallback can be changed and will give a more general solution to the problem.

**Comment by SpaceK33z** [comment]
Isn't this [already possible](https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option)?

**Comment by oferh** [comment]
AFAIK it's only a boolean value:
```
--history-api-fallback: enables support for history API fallback.
```
it might be that it's just the documentation that needs fixing

**Comment by SpaceK33z** [comment]
No, if you follow the link in my previous comment, you'll see that it is documented.

**Comment by oferh** [comment]
You are right, missed it, thanks for pointing me to the right place.
