### ISSUE TITLE
Broken historyApiFallback functionality in 2.1.0-beta.6 and later.

### ISSUE THREAD

**Issue by WillooWisp** [webpack/webpack-dev-server#642]
I'm submitting a bug report

webpack: 2.1.0-beta.22
webpack-dev-server: 2.1.0-beta.2

Windows 10
Running server via CLI / Node.js API

**Current behavior:**
Refreshing browser with 404 error where it should fallback to index.html (using historyApiFallback) does fallback to a non-generated (unevaluated using html-webpack-plugin) index.html.

**Expected/desired behavior:**
It should fallback to a generated (evaluated using html-webpack-plugin) index.html file as it used to before 2.1.0-beta.6.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration. Be sure to specify how you are running the server.** 
Simply clone the angular2-webpack-starter, https://github.com/angularclass/angular2-webpack-starter.git and use npm run start:hmr. Navigate to any page and refresh browser.

* **What is the expected behavior?**
Redirect / fallback on 404 error to a correctly generated index.html file.

* **What is the motivation / use case for changing the behavior?**
It has worked before it was broken in 2.1.0-beta.6.

**Comment by Foxandxss** [comment]
I just reported it at #640 and I believe it is the same issue.

**Comment by SpaceK33z** [comment]
Jep, it's the same issue. Thanks for the extra info though.
