### ISSUE TITLE
Failures with ipv6

### ISSUE THREAD

**Issue by Nek-** [webpack/webpack-dev-server#643]
**I'm submitting a bug report**

### webpack and webpack-dev-server version:
webpack: 1.10.x
webpack-dev-server: 1.x

### Please tell us about your environment:
Linux / Ubuntu
Running server via webpack CLI.

### Current behavior:

*Webpack run the server as expected and it looks that it's up and remotely accessible. This part is right.*

But when it uses the ip in the page, it uses it as a classic ip, which is wrong since you need to add `[]` around the IP to make it work in an URI.

### Expected/desired behavior:

Detection of the kind of the ip and addition of brakets where needed.

### Reproduce

* Change `host` option to your ipv6
* Run webpack server

### What is the expected behavior?

No errors with reloading etc.

### What is the motivation / use case for changing the behavior?

 Be ready for the futuuuuure !

**Comment by SpaceK33z** [comment]
Fair enough. A PR is welcome.

**Comment by SpaceK33z** [comment]
Fixed by #644.
