### ISSUE TITLE
Https without a defined ca file throws error

### ISSUE THREAD

**Issue by eldh** [webpack/webpack-dev-server#651]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
"webpack": "2.1.0-beta.25",
"webpack-dev-server": "2.1.0-beta.8",

**Please tell us about your environment:**
OSX 10.11 Sierra
Running server via CLI

**Current behavior:**

**Expected/desired behavior:**

Hey! I'm having some trouble with the latest webpack-dev-server beta and https. Previously I enabled https through cli `—https —key [key] —cert [cert]`. This now causes `net::ERR_SPDY_PROTOCOL_ERROR`. So I changed to use the config file like this: 
```
https: {
  key: '[key],
  cert: '[cert]',
},
```
This caused the following error: 
```
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:68:17)
    at Server (_tls_wrap.js:749:25)
    at Server (https.js:26:14)
    ...
```
From reading the source I would guess I am expected to supply a ca file. Is that necessary? Is there somehting else could be the problem here?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration. Be sure to specify how you are running the server.** 
Here's my config (slightly simplified): 
https://gist.github.com/eldh/d2dcea7088590afa38f80950a073208d

* **What is the expected behavior?**
I'd expect it to either work like it did in previous versions or provide an error explaining how I need to change my config.

* **What is the motivation / use case for changing the behavior?**
To make it easier to correctly set up https. Https is awesome.

**Comment by SpaceK33z** [comment]
Okay, that should be fixed. A PR is welcome.

**Comment by eldh** [comment]
I'll see what I can do. :)

**Comment by SpaceK33z** [comment]
I tried to reproduce this, but it appears to work. I cloned the webpack-dev-server repo and executed these commands:

```bash
cd examples/https
openssl req -newkey rsa:2048 -x509 -nodes -keyout server.pem -new -out server.pem -subj /CN=localhost -sha256
node ../../bin/webpack-dev-server.js --open --https --key server.pem --cert server.pem
```

This opened the browser, and the page loaded successfully.

Can you provide more information?

**Comment by SpaceK33z** [comment]
friendly ping @eldh

**Comment by eldh** [comment]
Hey, sorry I was awol. I've tried finding a reproducible example, but failed. So best to close this now, if I manage to get an example working I can re-open. Thanks for the help @SpaceK33z
