### ISSUE TITLE
Listen to socket

### ISSUE THREAD

**Issue by resure** [webpack/webpack-dev-server#659]
**I'm submitting a feature request**

**webpack and webpack-dev-server version:**
"webpack": "^2.1.0-beta.25"
"webpack-dev-server": "^2.1.0-beta.9"

It would be really nice to have ability to run webpack-dev-server listening to a socket. There is a StackOverflow answer that suggesting [passing socket as port param](http://stackoverflow.com/questions/33398936/can-webpack-dev-server-run-on-a-unix-domain-sockets) but seems like it doesn't work in the current version.

**Comment by SpaceK33z** [comment]
A PR is welcome.

**Comment by SpaceK33z** [comment]
Fixed by PR #661 :).
