### ISSUE TITLE
App reloads on proxy fail

### ISSUE THREAD

**Issue by istrau3** [webpack/webpack-dev-server#664]
The issue below seems to be happening again (I have the 2.1.0-beta.9 version):
https://github.com/webpack/webpack-dev-server/issues/446

When my proxy server is not on the page reloads indefinitely. Instead I would expect it to error out so that I can see the 404 in the network tab.

**Comment by SpaceK33z** [comment]
That is extremely unlikely, the code that enabled this in the past is gone in webpack-dev-server 2.1.0-beta.9. Are you sure that you are running that version? You can verify by going to `node_modules/webpack-dev-server/package.json` and looking at the value after `"_id"`.

**Comment by SpaceK33z** [comment]
ping @istrau3 ;).

**Comment by SpaceK33z** [comment]
Closing this because it really can't be happening in webpack v2 anymore since the code is completely gone. Feel free to re-open if it really still happens with the latest beta `2.1.0-beta.10`, but please provide more information if you do so.
