### ISSUE TITLE
Domain URL is not passed through proxy

### ISSUE THREAD

**Issue by dnutels** [webpack/webpack-dev-server#666]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.25
webpack-dev-server: 1.16.2

**Please tell us about your environment:**
Windows 10

**Current behavior:**

`proxy` configuration for Webpack Dev Server doesn't re-route domain root URL to the BE server.

So, this *abriged* Webpack Dev Server configuration within Webpack configuration file:

```
const config = {
    entry: {
       ...
    },
    output: {
        ...
    },
    devServer: {
        contentBase: PUBLIC_DIR,
        port: 3000,
        proxy: {
            '/': 'http://localhost:4000',
        }
    }
}
```

doesn't redirect `localhost:3000` to the server at `localhost:4000`, but does redirect anything else, like `localhost:3000/anything-at-all`.

If Webpack Dev Server replaced by an Express server:

```
const express = require('express');
const httpProxyMiddleware = require('http-proxy-middleware');

const app = express();

const proxy = httpProxyMiddleware({
    target: 'http://localhost:4000'
});

app.use('/', proxy);

app.listen(3000, () => {
    console.log(`Listening on 3000`);
});
```

everything works as expected.

**Expected/desired behavior:**

All URLs to be re-routed to BE server.

**Comment by SpaceK33z** [comment]
Can you update to the webpack-dev-server beta? I didn't even know webpack-dev-server 1.16.x worked with webpack v2 ;p.

**Comment by dnutels** [comment]
Absolutely.

**Upgraded to 2.1.0-beta.9**

Still exhibits the same behavior.

**Comment by SpaceK33z** [comment]
Okay. Do you have an `index.html` file? So if you would remove the proxy temporarily, does something display on `http://localhost:3000`?

**Comment by dnutels** [comment]
I do.

Anyway... I've created a repo demonstrating the issue - 

https://github.com/zen-experiments/webpack-dev-server-issue-666

`npm i`
`npm start`

Access http://localhost:3000 -> you should see ROOT printed
Access http://localhost:3000/aaa -> you should see SERVER printed

Server does this:

```javascript
pageRouter.get('*', (req, res) => {
    res.write('SERVER');
    res.end();
});
```

**Comment by SpaceK33z** [comment]
This is because of [this line](https://github.com/zen-experiments/webpack-dev-server-issue-666/blob/master/webpack.config.js#L27). `contentBase` takes preference above `proxy`. I suggest to either

1) disable `contentBase`
2) move `index.html` to another location
3) rename `index.html`

**Comment by dnutels** [comment]
Disabling contentBase did nothing. I am not positive how that would work with HTML.

The point was to have `webpack-dev-server` re-load (perhaps even through HMR) on changes, while still having SSR from the FE server it proxies to.

I expected such a setting to make `webpack-dev-server` a one-way street, so to speak. Where it will push updates to the browser, but defer to the FE server it proxies on any HTTP requests (or perhaps some).

I imagine that's what you were going for with 1), but it didn't work for me. Instead it fired a loop of refresh-rebuild sequences that eventually stopped.

```
Child html-webpack-plugin for "index.html":                 
    chunk    {0} index.html 537 kB [entry]                  
         + 4 hidden modules                                 
webpack: bundle is now VALID.                               
webpack: bundle is now INVALID.                             
webpack: wait until bundle finished: /app.js                
Hash: f5ae2c990bf76853cece                                  
Version: webpack 2.1.0-beta.25                              
Time: 38ms                                                  
chunk    {0} app.js (app) 232 kB [entry]                    
   [35] ./src/client/index.js 73 bytes {0} [built]          
     + 79 hidden modules                                    
Child html-webpack-plugin for "index.html":                 
    chunk    {0} index.html 537 kB [entry]                  
         + 4 hidden modules                                 
webpack: bundle is now VALID.                               
webpack: bundle is now INVALID.                             
Hash: f5ae2c990bf76853cece                                  
Version: webpack 2.1.0-beta.25                              
Time: 39ms                                                  
chunk    {0} app.js (app) 232 kB [entry]                    
   [35] ./src/client/index.js 73 bytes {0} [built]          
     + 79 hidden modules                                    
Child html-webpack-plugin for "index.html":                 
    chunk    {0} index.html 537 kB [entry]                  
         + 4 hidden modules                                 
webpack: bundle is now VALID.                               
webpack: bundle is now INVALID.                             
Hash: f5ae2c990bf76853cece                                  
Version: webpack 2.1.0-beta.25                              
Time: 44ms                                                  
chunk    {0} app.js (app) 232 kB [entry]                    
   [35] ./src/client/index.js 73 bytes {0} [built]          
     + 79 hidden modules                                    
Child html-webpack-plugin for "index.html":                 
    chunk    {0} index.html 537 kB [entry]                  
         + 4 hidden modules                                 
webpack: bundle is now VALID.                               
webpack: bundle is now INVALID.                             
Hash: f5ae2c990bf76853cece                                  
Version: webpack 2.1.0-beta.25                              
Time: 40ms                                                  
```

**Comment by dnutels** [comment]
OK. Have to disable `publicPath` as well for your suggestion to work.

Renaming the HTML to `index-dev.html` seems to have the desired effect as well.

Hmm... Perhaps add this to the documentation?
