### ISSUE TITLE
Doesn't build on sub-path (win64) ?

### ISSUE THREAD

**Issue by remoe** [webpack/webpack-dev-server#67]
I try to run webpack-dev-server with the following config:

```javascript
module.exports = {
  entry: ['./lib/boot/index.js'],
  output: {
    path: __dirname + '/build',
    filename: "build.js"
  },
  module: {
    loaders: [
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'} // inline base64 URLs for <=8k images, direct URLs for the rest
    ]
  }
};
```

when I start the server it shows this:

```shell
Version: webpack 1.4.5
Time: 38ms
   Asset  Size  Chunks             Chunk Names
build.js  1634       0  [emitted]  main
chunk    {0} build.js (main) 49 [rendered]
    [0] multi main 28 {0} [built]
    [1] ./lib/boot/index.js 21 {0} [built]
webpack: bundle is now VALID.
```

But it doesn't generate any build.js file in build folder! 

It works when I run "webpack" on console.

**Comment by amaschas** [comment]
I think I'm having a similar problem, which I noted in #485. I think one of the big problems here is that the documentation on publicPath is incredibly vague, both in the webpack docs and the webpack-dev-server docs. I'm not sure what exactly I'm supplying a path to, and I've tried many strings for the path, but none of the results in HMR working if contentBase is more than one level below the root dir.

**Comment by jhnns** [comment]
`publicPath` will be pre-pended to every request when requesting chunks, hot module updates, etc. It should reflect the `pathname` as seen by the browser (like `location.pathname`).

**Comment by SpaceK33z** [comment]
Closing because of staleness, and all questions are answered. Feel free to comment if you think otherwise.
