### ISSUE TITLE
Can I use `DllReferencePlugin` with `webpack-dev-server`?

### ISSUE THREAD

**Issue by mrdulin** [webpack/webpack-dev-server#671]
How to inject my `dll.bundle.js` to `index.html`?

In chrome console, it give `Uncaught ReferenceError: vendor is not defined`  and `Uncaught TypeError: __webpack_require__(...) is not a function` error.

I know the reason, because my `dll` does not inject to `index.html` .

I don't want to use `express` or `node` server to host my static. I just want to use `webpack-dev-server` .

https://github.com/mrdulin/react-juhe-tools here is my project. 

Somebody help me. Thanks very much.

**Comment by SpaceK33z** [comment]
As the GitHub issue template clearly says, please ask questions on StackOverflow. You will get better help there.

**Comment by mrdulin** [comment]
@SpaceK33z OK, thanks. sorry for that.
