### ISSUE TITLE
Return server instance for close method access. 

### ISSUE THREAD

**Issue by michaelBenin** [webpack/webpack-dev-server#674]
I'm running a couple servers at the same time, I'd like to close them all gracefully including webpack-dev-server. 
 
Making a pr.

**Comment by SpaceK33z** [comment]
Is it not possible to use [`close()`](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L410)? Because if you would do this manually, you'd also need to close the webpack-dev-middleware instance manually.

**Comment by michaelBenin** [comment]
Hi, I'm building a repro case for this. 

I'm instantiating the server as so: 

```
const server = new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true
  }).listen(3000, 'localhost', (err /* , result*/) => {
    if (err) {
      return console.log(err); // eslint-disable-line no-console
    }
    console.log('Listening at http://localhost:3000/'); // eslint-disable-line no-console
    return callback();
  });
```

Then on this method: 

```
 process.on('SIGINT', () => {
    log('Process interrupted');
    server.close()
    process.exit();
  });
```

I get an error on server.close.

I'm going to try not chaining listen and see if that works. I'll more investigating. Will close now and reopen if I'm able to recreate.

**Comment by michaelBenin** [comment]
Unable to close this way either:

```
gulp.task('webpack-dev-server', function runWebpackDevServer(callback) {
  const server = new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true
  });
  const activeServer = server.listen(3000, 'localhost', (err /* , result*/) => {
    if (err) {
      return console.log(err); // eslint-disable-line no-console
    }
    console.log('Listening at http://localhost:3000/'); // eslint-disable-line no-console
    return callback();
  });

  process.on('SIGINT', () => {
    activeServer.close();
    log('Process interrupted');
    process.exit();
  });
});
```

**Comment by michaelBenin** [comment]
Modifying this line fixed it: 

```
// delegate listen call and init sockjs
Server.prototype.listen = function() {
	return this.listeningApp.listen.apply(this.listeningApp, arguments);
```

Going to make another PR.

**Comment by michaelBenin** [comment]
Yea this is fixed in 2.1 Beta. I'll just use the beta release. Thanks and sorry.

**Comment by SpaceK33z** [comment]
Oh okay nice, no worries ;).

**Comment by michaelBenin** [comment]
So i had some issues with peer deps etc with npm. I'm using this branch if anyone else needs this functionality and maintain backwards compat with other libs: https://github.com/michaelBenin/webpack-dev-server/commit/8baf6a11f2a35d21ae2d7b2f382f8ceafe36deb1
