### ISSUE TITLE
run webpack-dev-server 

### ISSUE THREAD

**Issue by angusjiang** [webpack/webpack-dev-server#677]
Attempting to run webpack-dev-server --inline results in:

```
`[root@localhost vue]# webpack-dev-server
 http://localhost:8080/
webpack result is served from /static/build/
content is served from /vagrant/vue
404s will fallback to /index.html
Hash: 1783784827fcdfaf2e1c
Version: webpack 1.12.14
Time: 1346ms
    Asset      Size  Chunks             Chunk Names
detail.js   74.6 kB       0  [emitted]  detail
  home.js   74.7 kB       1  [emitted]  home
 home.css  48 bytes       1  [emitted]  home
chunk    {0} detail.js (detail) 49.9 kB [rendered]
    [0] multi detail 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:8080 3.97 kB {0} {1} [built] [1 error]
    [2] (webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} {1} [built]
    [3] (webpack)/~/node-libs-browser/~/punycode/punycode.js 14.7 kB {0} {1} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} {1} [built]
    [5] (webpack)/~/node-libs-browser/~/querystring-es3/index.js 127 bytes {0} {1} [built]
    [6] (webpack)/~/node-libs-browser/~/querystring-es3/decode.js 2.51 kB {0} {1} [built]
    [7] (webpack)/~/node-libs-browser/~/querystring-es3/encode.js 2.54 kB {0} {1} [built]
    [8] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} [built] [1 error]
    [9] (webpack)/hot/dev-server.js 1.85 kB {0} {1} [built]
   [10] (webpack)/hot/log-apply-result.js 813 bytes {0} {1} [built]
   [11] ./js/detail.js 18 bytes {0} [built]
chunk    {1} home.js, home.css (home) 50 kB [rendered]
    [0] multi home 52 bytes {1} [built]
    [1] (webpack)-dev-server/client?http://localhost:8080 3.97 kB {0} {1} [built] [1 error]
    [2] (webpack)/~/node-libs-browser/~/url/url.js 22.3 kB {0} {1} [built]
    [3] (webpack)/~/node-libs-browser/~/punycode/punycode.js 14.7 kB {0} {1} [built]
    [4] (webpack)/buildin/module.js 251 bytes {0} {1} [built]
    [5] (webpack)/~/node-libs-browser/~/querystring-es3/index.js 127 bytes {0} {1} [built]
    [6] (webpack)/~/node-libs-browser/~/querystring-es3/decode.js 2.51 kB {0} {1} [built]
    [7] (webpack)/~/node-libs-browser/~/querystring-es3/encode.js 2.54 kB {0} {1} [built]
    [8] (webpack)-dev-server/client/socket.js 856 bytes {0} {1} [built] [1 error]
    [9] (webpack)/hot/dev-server.js 1.85 kB {0} {1} [built]
   [10] (webpack)/hot/log-apply-result.js 813 bytes {0} {1} [built]
   [12] ./js/home.js 48 bytes {1} [built]
   [13] ./css/home.css 41 bytes {1} [built]

ERROR in (webpack)-dev-server/client?http://localhost:8080
Module not found: Error: Cannot resolve module 'strip-ansi' in /tmp/no_manage/node_modules/webpack-dev-server/client
 @ (webpack)-dev-server/client?http://localhost:8080 2:16-37

ERROR in (webpack)-dev-server/client/socket.js
Module not found: Error: Cannot resolve module 'sockjs-client' in /tmp/no_manage/node_modules/webpack-dev-server/client
 @ (webpack)-dev-server/client/socket.js 1:13-37
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.74 kB [rendered]
        [0] /tmp/no_manage/~/css-loader!./css/home.css 230 bytes {0} [built]
        [1] /tmp/no_manage/~/css-loader/lib/css-base.js 1.51 kB {0} [built]
webpack: bundle is now VALID.
`
```

why  ?  Cannot resolve module 'sockjs-client'  and   Cannot resolve module 'strip-ansi'

 [root@localhost client]# ls
index.bundle.js  live.bundle.js  live.js    socket.js  web_modules
index.js         live.html       page.jade  style.css  webpack.config.js

**Comment by angusjiang** [comment]
{
  "name": "h5.online.fontend",
  "version": "1.0.0",
  "scripts": {
    "dev": "webpack-dev-server --host 0.0.0.0 --port 8080 --inline --hot --quiet",
    "build": "export NODE_ENV=production && webpack --progress --hide-modules"
  },
  "license": "MIT",
  "dependencies": {
    "mint-ui": "^0.2.8",
    "vue-core-image-upload": "^0.9.5",
    "vue-progressbar": "^0.2.4",
    "vuerify": "^0.2.1",
    "webpack": "^1.13.2"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.2.0",
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-runtime": "^6.1.18",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-0": "^6.3.13",
    "babel-runtime": "^5.8.0",
    "bootstrap": "^3.3.6",
    "css-loader": "^0.23.0",
    "echarts": "^3.1.3",
    "file-loader": "^0.8.5",
    "jquery": "^2.2.1",
    "jsx-loader": "^0.13.2",
    "less": "^2.6.0",
    "less-loader": "^2.2.2",
    "mint-ui": "^0.2.7",
    "style-loader": "^0.13.0",
    "superagent": "^1.7.2",
    "url-loader": "^0.5.7",
    "vue": "^1.0.10",
    "vue-hot-reload-api": "^1.2.2",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^7.1.7",
    "vue-resource": "^0.5.1",
    "vue-router": "^0.7.7",
    "vue-strap": "^1.0.2",
    "vuerify": "^0.2.1",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  }
}

**Comment by angusjiang** [comment]
var webpack = require('webpack');
//添加分类css插件
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var hotModuleReplacementPlugin = require("webpack/lib/HotModuleReplacementPlugin");
module.exports = {
    entry: {
        home: "js/home",
        detail: "js/detail"
    },
    output: {
        path: "assets",                   //打包输出目录
        publicPath: "/static/build/",     //webpack-dev-server访问的路径
        filename: "[name].js",            //输出文件名
        chunkFilename: "bundle-[id].js"   //输出chunk文件名
    },
    resolve: {
        modulesDirectories: ['.']
    },
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader:  ExtractTextPlugin.extract("style-loader", "css-loader")
            },
        ]
    },
    plugins: [
        new ExtractTextPlugin("[name].css"),
        new webpack.HotModuleReplacementPlugin()
    ],
    devServer: {
        historyApiFallback: true,
        hot: true,
        inline: true,
        progress: true
    }
}

**Comment by SpaceK33z** [comment]
What node and npm version do you have? I can't reproduce this, and I know for sure it's working for many people.

**Comment by angusjiang** [comment]
@SpaceK33z  
 [root@localhost vue]# node -v
v4.0.0
[root@localhost vue]# npm -v
2.14.2

I have node and npm version.

**Comment by angusjiang** [comment]
node_modules 


```
autoprefixer-loader             file-loader            vue-hot-reload-api
babel-core                      html-webpack-plugin    vue-html-loader
babel-loader                    http-proxy-middleware  vue-infinite-scroll
babel-plugin-transform-runtime  jquery                 vue-loader
babel-preset-es2015             jsx-loader             vue-progressbar
babel-preset-stage-0            less                   vue-resource
babel-preset-stage-2            less-loader            vue-router
babel-runtime                   mint-ui                vue-strap
bootstrap                       opn                    vue-style-loader
connect-history-api-fallback    style-loader           webpack
css-loader                      superagent             webpack-dev-middleware
echarts                         url-loader             webpack-dev-server
eventsource-polyfill            vue                    webpack-hot-middleware
express                         vue-cli                webpack-merge
extract-text-webpack-plugin     vue-core-image-upload
```

**Comment by SpaceK33z** [comment]
@angusjiang, ah I think I know where your problem is.

In your webpack config, you have this:

```js
resolve: {
        modulesDirectories: ['.']
},
```

However, that isn't valid and by specifying the `modulesDirectories` without `node_modules` in it, the client script can't compile. For more information why `.` is not valid, see [the docs](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories).

So to fix it, I would suggest to either remove `modulesDirectories`, or to add `'node_modules'` to it.

**Comment by angusjiang** [comment]
Thank you for your suggest,But I have  a new problem.

```
home.js:4940 GET http://localhost:8080/sockjs-node/info?t=1478226568062 net::ERR_CONNECTION_ABORTEDAbstractXHRObject._start @ home.js:4940(anonymous function) @ home.js:4829
home.js:1151 [WDS] Disconnected!
```

**Comment by angusjiang** [comment]
I got it, use "webpack-dev-server --host 0.0.0.0 --port 8080 --inline --hot --quiet"  instead of  "webpack-dev-server".

and  add two attribute :

     watch: true,

    watchOptions: {
      poll: true
    },


so, it works...
Thank you again for guidance.
