### ISSUE TITLE
webpack-dev-server doesn't send changed files on Docker for Windows

### ISSUE THREAD

**Issue by MichalPodeszwa** [webpack/webpack-dev-server#678]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 1.12.11
webpack-dev-server: 1.12.1

Windows 10
Docker
Running server via CLI

**Current behavior:**

When you update a file on host (via mounted directory) the file changes on docker (confirmed by `cat`-ing it). Webpack-dev-server picks up changes (I've got legacy polling enabled), recompiles, but sends the old file to browser.

**Expected/desired behavior:**

Webpack should send the new - changed - file.

**Comment by SpaceK33z** [comment]
Note that this *does* work, but is a configuration issue.

> legacy polling

How do you use this exactly? With `--watch-poll` or ...?

Also, do you still have the built files that you got when running `webpack`? If so, try to delete these files and see what happens then. It's possible it actually uses those files.

**Comment by MichalPodeszwa** [comment]
I don't have webpack built files. I'm using legacy by watchOptions.poll in
webpack.config.js

pt., 28.10.2016, 13:56 użytkownik Kees Kluskens <notifications@github.com>
napisał:

**Comment by SpaceK33z** [comment]
Okay, did you try to upgrade to a newer version of webpack and webpack-dev-server? You're using fairly old versions.

If that doesn't work, please post your config here.

**Comment by MichalPodeszwa** [comment]
I tried updating `webpack` to 1.13.3 and `webpack-dev-server` to 1.16.2. No change there.

I can still see in the terminal that the change has been picked up, App recompiled. In chrome dev tools I see:

```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
[WDS] App updated. Recompiling...
[WDS] App hot update...
```
And nothing else comes up.


My `webpack.config.js`:
```javascript
// https://github.com/jtangelder/sass-loader/issues/208#issuecomment-210576342
require.extensions['.scss'] = () => { return; };
require.extensions['.css'] = () => { return; };

var ExtractTextPlugin = require("extract-text-webpack-plugin");
var JasminePlugin = require('jasmine-webpack-plugin');
var CopyPlugin = require('copy-webpack-plugin');
var webpack = require('webpack');
var path = require('path');


function buildPlugins () {
    let plugins = [
        new CopyPlugin([
            {
                from: '/node_modules/alloyeditor/dist/alloy-editor',
                to: 'alloy-editor'
            }
        ]),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(process.env.NODE_ENV)
            }
        }),
    ];

    if (isProduction()) {
        plugins = plugins.concat([
            new ExtractTextPlugin("css/style.css")
        ]);
    } else {
        plugins = plugins.concat([
            new JasminePlugin(),
            new CopyPlugin([
                {
                    from: '/node_modules/jasmine-core',
                    to: 'node_modules/jasmine-core'
                }
            ])
        ]);
    }
    return plugins;
}

function buildLoaders () {
    let loaders = [{
            test: /\.(?:html)$/,
            loader: 'file?name=[name].[ext]',
            query: {
                name: '[name].[ext]'
            }
        }, {
            test: /\.(?:eot|woff|woff2|otf|ttf|svg|gif|jpg|png)$/,
            include: /node_modules/,
            loader: "url-loader?limit=1000000"
        }
    ];

    const cssLoaderQuery = "camelCase&localIdentName=[local]--[hash:base64:5]"

    if (isProduction()) {
        loaders = loaders.concat([{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loaders: ['babel?presets[]=react&presets[]=es2015&presets[]=stage-0']
            }, {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style', 'css')
            }, {
                test: /\.scss$/,
                exclude: /node_modules/,
                loader: ExtractTextPlugin.extract('style', `css?${cssLoaderQuery}!autoprefixer!sass`)
            }
        ])
    } else {
        loaders = loaders.concat([{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loaders: ['babel?presets[]=react&presets[]=es2015&presets[]=stage-0&presets[]=react-hmre']
            }, {
                test: /\.css$/,
                loaders: ['style', 'css']
            }, {
                test: /\.scss$/,
                exclude: /node_modules/,
                loaders: ['style', `css?${cssLoaderQuery}`, 'autoprefixer', 'sass']
            }
        ])
    }

    return loaders;
}


function isProduction () {
    return process.env.NODE_ENV == "production";
}



module.exports = {
    context: __dirname + '/app',
    entry: {
        spec: '../spec.webpack.js',
        app: './js/app',
        html: './index.html'
    },
    module: {
        loaders: buildLoaders(),
    },
    output: {
        path: __dirname + '/dist',
        filename: 'js/[name].js'
    },
    plugins: buildPlugins(),
    externals: {
        'cheerio': 'window',
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true
    },
    devServer: {
        stats: {
            chunks: false
        }
    },
    watchOptions: {
        poll: 1000
    }
};
```

**Comment by SpaceK33z** [comment]
Ah, you're using hot reload, that was a detail I was missing.

According to the [documentation](https://webpack.github.io/docs/webpack-dev-server.html), you need to do this:

> To teach webpack to make requests (for chunk loading or HMR) to the webpack-dev-server you need to provide a full URL in the output.publicPath option.

**Comment by MichalPodeszwa** [comment]
Would that explain why the exact same setup works on both Linux and OS X?

Sorry on missing this detail, but it doesn't work after reloading either.
(or even opening in different browsers)

pt., 28.10.2016, 20:23 użytkownik Kees Kluskens <notifications@github.com>
napisał:

**Comment by SpaceK33z** [comment]
I'm just debugging here, since I don't have a Windows VM with Docker on it and don't have time to set that up at the moment.

So does it work in Linux and OSX *with Docker*? Because if so, that would definitely be a weird bug.

**Comment by MichalPodeszwa** [comment]
Yes, that's correct.
We've been successfully using this setup for several months now. I'm trying
to get it working on Windows, but I stumbled upon this rather weird bug.

pt., 28.10.2016, 20:32 użytkownik Kees Kluskens <notifications@github.com>
napisał:

**Comment by MichalPodeszwa** [comment]
In the mean time, I also tried running webpack with --watch. It didn't work
either, which makes me wonder if it's not webpack problem, instead of dev
server's

pt., 28.10.2016, 20:34 użytkownik Michał Podeszwa <michal.podeszwa@gmail.com>
napisał:

**Comment by SpaceK33z** [comment]
Okay, if it's not working with `webpack --watch` it's definitely not a webpack-dev-server problem. In #143 there are a lot of solutions to some Docker problems, maybe try that out.

I would suggest to try to migrate to webpack v2, even if it's still in beta. It's pretty stable. [This upgrade guide](https://webpack.js.org/how-to/upgrade-from-webpack-1/) is pretty good. If it still happens then, you could make an issue in the webpack main repo.

**Comment by MichalPodeszwa** [comment]
Ok. Thank you for your help.
I think we can close this issue then

pt., 28.10.2016, 20:44 użytkownik Kees Kluskens <notifications@github.com>
napisał:

**Comment by SpaceK33z** [comment]
Allright. By the way, I would maybe first post this on StackOverflow, because you'll probably get a quicker reply there.

**Comment by MichalPodeszwa** [comment]
Just to let you know. Turns out, everything works now. I must've had the built project **somehow** there.
