### ISSUE TITLE
Medium level of logging

### ISSUE THREAD

**Issue by chanon** [webpack/webpack-dev-server#68]
I'm not sure if this is already supported, but right now the logging levels of webpack-dev-server are either lots and lots or none at all.

What I mean is, on startup and whenever changes are detected, hundreds (thousands maybe?) of lines are output to the console (i'm using the API not the CLI). The problem with this is it pushes useful app code originated logging lines out of the console scroll buffer.

I tried using the noInfo option and what happens is that there is nothing logged from webpack-dev-server at all.

What I would like to see is just the 
```
webpack: bundle is now INVALID.
webpack: bundle is now VALID.
```
lines and also any errors that occurred and nothing more, so I know that webpack has detected changes and finished processing them.

**Comment by steida** [comment]
My config:

```js
// It suppress error shown in console, so it has to be set to false.
quiet: false,
// It suppress everything except error, so it has to be set to false as well
// to see success build.
noInfo: false,
stats: {
  // Config for minimal console.log mess.
  assets: false,
  colors: true,
  version: false,
  hash: false,
  timings: false,
  chunks: false,
  chunkModules: false
}
```

**Comment by maspwr** [comment]
The example config @steida gave is very helpful. That seems more or less the requested behavior (in lieu of something like logging levels). Perhaps this is just a documentation bug to explain the `stats` options better?

**Comment by steida** [comment]
@maspwr Feel free to copy/past from or into github.com/steida/este

**Comment by maspwr** [comment]
@steida Very cool. Thanks for the link!

**Comment by kentcdodds** [comment]
Just verifying @steida, what you provided isn't supposed to work today right? You were just suggesting that as an API. I just tried it and it didn't work for me, so that's why I'm just checking that I'm not missing anything...

**Comment by kikoanis** [comment]
Based on some experiments I did this would work within a gulp task with both webpack and webpack-dev-server. I was not able to produce the same result using webpack on its own. 

```
gulp.task('webpack:build', (callback) => {
  webpack(webpackConfig, (err, stats) => { // webpackConfig object --> should be defined somewhere (i.e file..maybe)
    if (err) throw new gutil.PluginError('webpack:build', err);
    gutil.log('[webpack:build]', stats.toString(
    {
      // Config for minimal console.log mess.
              assets: true,
              colors: true,
              version: true,
              modules: false,
              hash: false,
              timings: false,
              chunks: true,
              chunkModules: false,
              reasons : true,
              cached : true,
              chunkOrigins : true
    }));
    callback();
  });
});

gulp.task('webpack-dev-server', (callback) => {
  new WebpackDevServer(webpack(webpackConfig), {
    contentBase: `http://localhost:${port}`,
    publicPath: webpackConfig.output.publicPath,
    stats: { 
              // Config for minimal console.log mess.
              assets: true,
              colors: true,
              version: true,
              modules: false,
              hash: false,
              timings: false,
              chunks: true,
              chunkModules: false,
              reasons : true,
              cached : true,
              chunkOrigins : true
           },
    noInfo : false,
    hot: true,
    devtool : 'source-map',
    inline: true,
    progress : true,
    watch : true,
    keepalive: true,
    historyApiFallback: true,
  }).listen(port, 'localhost', (err, result) => {
    if (err) throw new gutil.PluginError('webpack-dev-server', err);
    gutil.log('[webpack-dev-server]', `http://localhost:${port}`);
  });
});
```

**Comment by kikoanis** [comment]
Here is what I got...

![capture](https://cloud.githubusercontent.com/assets/615849/9145316/9751d6e8-3d10-11e5-8774-aabbaafefae4.PNG)

**Comment by ntdb** [comment]
@steida Thank you, this is exactly what I was looking for.

@kentcdodds The `stats` config definitely works for me. My [frontend scaffold](https://github.com/ntdb/quickstart) is a lightweight example (webpack version 1.10.1).

**Comment by chanon** [comment]
I think using the stats config is the correct solution. Closing this issue.

**Comment by bjunix** [comment]
Where is the `stats` config option documented? If it's not documented, is there in issue for the missing documentation?

**Comment by SpaceK33z** [comment]
https://webpack.js.org/configuration/stats/#stats

**Comment by dmk255** [comment]
Sorry for commenting on an old thread.

If others end up here looking for a way to show the startup url on webpack-dev-server initialization (e.g. `localhost:3000`) but not have a mess in the console this config worked for me:

```JS
  stats: {
      all: false,
      // Show the url we're serving at
      wds: true,
      // Config for minimal console.log mess.
      assets: false,
      colors: true,
      version: false,
      hash: false,
      timings: false,
      chunks: false,
      chunkModules: false,
    },
```

The `wds` key is not documented so far as I can tell.
