### ISSUE TITLE
Add clientLogLevel support to HMR output

### ISSUE THREAD

**Issue by VladShcherbin** [webpack/webpack-dev-server#682]
It would be great if `clientLogLevel` would apply to HMR output as well.

**Comment by SpaceK33z** [comment]
That's unfortunately not possible in webpack-dev-server, since the HMR script lives in the [webpack repo](https://github.com/webpack/webpack/tree/master/hot).

**Comment by VladShcherbin** [comment]
Oh, that's sad.

Thank you.
