### ISSUE TITLE
Stop previous existing server on specific port or all ports?

### ISSUE THREAD

**Issue by asdfadrian** [webpack/webpack-dev-server#684]
node v7 
npm is v3.10.8

So Im following a react-redux tutorial template based off of (https://github.com/buckyroberts/React-Redux-Boilerplate). I have ran a server on port 3000 previously without an issue. I have since then accidentally deleted the project and cannot stop the server. So now when I pulled a backup of the project it prevents me from running the server at port 3000. How can I stop or kill the current 3000 server so that I maybe restart it using 'npm install' and 'npm start' like before?

**Comment by SpaceK33z** [comment]
Note this is not an issue in webpack-dev-server. You haven't mentioned your OS, so I can't give you a good answer, but if you google for `kill node process <OS name>` you'll find how to fix this.
