### ISSUE TITLE
Show splash page while webpack compiling

### ISSUE THREAD

**Issue by davidnormo** [webpack/webpack-dev-server#686]
At the moment when you start up the dev server, the user waits for the compile to end before they see anything in the browser. It would be nice if the user sent an HTTP request before the build has finished, they see a holding page, a splash screen. You could even show some compiler output.

**Comment by SpaceK33z** [comment]
I'm not sure about this. You can clearly see that it's loading because your browser shows it as loading. I don't know if a splash screen would add value if you already know it's loading.

**Comment by SpaceK33z** [comment]
The events that are necessary to render a splash page are exposed now. It is relatively easy to make a package for it or include it directly in your app (in this case I would suggest to use a separate entry point).

An example of how this would work: https://github.com/webpack/webpack-dev-server/issues/481#issuecomment-258610429.
