### ISSUE TITLE
how to Error event in Node APi

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [webpack/webpack-dev-server#687]
like this:

```javascript
new WebpackDevServer(webpack(CONFIG)).on('error', function(err){
  Growl.notify(err.message)
})
```

**Comment by SpaceK33z** [comment]
```js
var server = new WebpackDevServer(compiler, {...});
server.listen(8080, "localhost", function(err) {
  // do your thing
});
```

Note that the issue template very clearly says that questions should be asked on StackOverflow, so I'm closing this.

**Comment by uMaxmaxmaximus** [comment]
This function is not called every time an error occurs. and it is called only when the server can not start.

We need it to be called every time the assembly failed!
Immediately reopen the ticket!

**Comment by uMaxmaxmaximus** [comment]
do not worry, I created a new issue
https://github.com/webpack/webpack-dev-server/issues/688
