### ISSUE TITLE
DEV SERVER ERROR HANDLER BUG !

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [webpack/webpack-dev-server#689]
I FOUND BUG!!!!!!!!!!!!!!!

THIS IS FUNCTION CALL ONE TIME WHEN SERVER STARTED!! BUT AUTOR WEBPACK TELL ME THiS FUNCTION CALL EVERY TIME WHEN  BUILD ERROR!! IF I PRESS CTRL + S AND BUILD ERROR THiS FUNCTION NOT CALL!! I FOUND BUG!

```javascript
new WebpackDevServer(webpack(CONFIG)).listen(8080, 'localhost', function(err){
  Growl.notify(err.message)
})
```

QUESTIONS???
THiS CODE NOT REACTING IN BUILD ERROR. JUST ON SERVER START ERROR/!

IS A JUST SERVER ERROR BNOT BUILD ERROR!

**Comment by indri-indri** [comment]
NICE BUG TNX 4 SHARING !!!!!!!!

**Comment by uMaxmaxmaximus** [comment]
his tel me this function call in EVERY BUILD ERRORS https://github.com/webpack/webpack-dev-server/issues/687

**Comment by indri-indri** [comment]
he is liar!!!!

**Comment by uMaxmaxmaximus** [comment]
MAYBE HE IS NOT THE RIGHTS AND THIS FUNCTION SHOULD NOT called each time the faulty build?

**Comment by uMaxmaxmaximus** [comment]
please tell me. i need crate error notifer cuz notifer plugins not working for me...

**Comment by SpaceK33z** [comment]
Sorry, I'm not going to help you like this. As I said in your previous issue, you should ask questions on StackOverflow. You'll get better help there.

Note that if you make an issue again like this, I'll report this as Spam/Abuse.
