### ISSUE TITLE
Headers (e.g. Access-Control-Allow-Origin) on requests to contentBase

### ISSUE THREAD

**Issue by tdeekens** [webpack/webpack-dev-server#69]
Hi,

I've jumped onto `webpack` and the `webpack-dev-server` quite recently and have been really enjoying developing with it.

Lately I ran into a scenario in which we have multiple (3-4) sub-projects all running an own `webpack-dev-server` on different ports. The bundles are then included in on one of the projects (being served over a dev-server) having an aggregating `index.html` including the other projects' bundles. Whenever another sub-project now starts requesting resources over its contentBase it obviously runs into CORS issues as its not running under the same port. 

I've seen the dev-server having a `header` configuration option. Still, as far as I understand, this header is only for a request to the bundle not the `index.html` nor any other static resources which are being served via `serveMagicHtml()` in the `lib/Server.js`. Is there any way of accomplishing this through configuration or is it a scenario which is just not intended?

Cheers.

**Comment by crucialfelix** [comment]
You can close this now. PR was merged.

**Comment by jhnns** [comment]
Thx

**Comment by JulianIsrael** [comment]
I think this is still happening for me, I'm currently on 1.16.2

**Comment by tsm91** [comment]
i think i still got this problem as well

```
  config.devServer = {
    contentBase: AOT ? './src/compiled' : './src',
    port: CONSTANTS.PORT,
    historyApiFallback: {disableDotRule: true},
    host: '0.0.0.0',
    headers: { 'Access-Control-Allow-Origin': '*' },
    watchOptions: DEV_SERVER_WATCH_OPTIONS
  };
```

```
XMLHttpRequest cannot load http://localhost:3030/api/v1/cli/ssh. Redirect from 'http://localhost:3030/api/v1/cli/ssh' to 'http://localhost:3000/offline.html' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```


```
General
Request URL:http://localhost:3030/api/v1/cli/ssh
Request Method:GET
Status Code:307 OK (from ServiceWorker)
Remote Address:127.0.0.1:3000

Response Headers
location:http://localhost:3000/offline.html

Request Headers
Provisional headers are shown
Referer:http://localhost:3000/cli/add-project
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36
```

```
if (evt.request.headers.get('x-sw') === SW_TYPES.nav) {
    evt.respondWith(Response.redirect('/offline.html', 307));
  }
```

**Comment by sheprdinc** [comment]
i'm using axios, but could use fetch... to be honest, i care far more about why this issue is happening in production rather than in dev mode, but unfortunately all of my google searches return solutions only for devServer ... any one figured this out with a production setting in webpack? this cors issue is killing me, trying to get data from google maps api using restful endpoint, gmaps library not an option

**Comment by yanlee26** [comment]
How about chrome's extensions??

**Comment by ar-dehghan-a** [comment]
> How about chrome's extensions??

https://developer.chrome.com/docs/extensions/develop/concepts/cross-origin-isolation
