### ISSUE TITLE
Undefined request when using dev server

### ISSUE THREAD

**Issue by foxbunny** [webpack/webpack-dev-server#692]
**webpack and webpack-dev-server version:**
webpack: 1.13.3
webpack-dev-server: 1.16.2

**Please tell us about your environment:**
OSX 10.11.6
Running server via CLI
[configuration](https://gist.github.com/foxbunny/1762ed6f61d753a6a31612b61768db73)
Directory layout:

```
  conf/
    webpack.config.js
  src/
    index.js
  pub/
    index.html
```

Command (npm script) used to run the server:

```
webpack-dev-server --port 8888 --hot --inline --content-base pub --conf conf/webpack.config.js
```

**Current behavior:**

When webpack is used to build the source using the same configuration file build succeeds. When the dev server command is run, the following traceback is shown:

```
/Users/yamasaki/Code/react-test/node_modules/webpack/lib/NormalModuleFactory.js:72
			var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
			                      ^

TypeError: Cannot read property 'replace' of undefined
    at /Users/yamasaki/Code/react-test/node_modules/webpack/lib/NormalModuleFactory.js:72:26
    at /Users/yamasaki/Code/react-test/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /Users/yamasaki/Code/react-test/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/yamasaki/Code/react-test/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/Users/yamasaki/Code/react-test/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /Users/yamasaki/Code/react-test/node_modules/webpack/lib/Compilation.js:214:11
    at /Users/yamasaki/Code/react-test/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/yamasaki/Code/react-test/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/yamasaki/Code/react-test/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/yamasaki/Code/react-test/node_modules/webpack/lib/Compilation.js:185:8)
```

After a bit of digging around, I was able to determine that the `MultiEntryPlugin` is being instantiated with an array that contains `undefined`, but I'm not able to find out where `undefined` comes from. I could find out more if someone could point me in the right direction.

**Comment by SpaceK33z** [comment]
Could you try using an absolute path in `output.path`?

**Comment by foxbunny** [comment]
OMG, I feel so stupid. I was using `--conf` instead of `--config` as the command line argument. (facepalm)

**Comment by SpaceK33z** [comment]
Haha don't worry, webpack should have given you a clear error message. I just checked, in webpack v2 this has been fixed at least :). If you would've used `--conf` there, it would have errored with "Unknown argument: conf". It's still in beta, but will be stable in a few months.

**Comment by foxbunny** [comment]
Incidentally, there does not seem to be a check for the case where the `wpOpt.entry` key is `undefined`. Is that going to be in for 2.0 or shall I report a feature request? Or is that simply not considered important?

I'm referring to this part of the code:

```
	[].concat(wpOpt).forEach(function(wpOpt) {
		if(typeof wpOpt.entry === "object" && !Array.isArray(wpOpt.entry)) {
			Object.keys(wpOpt.entry).forEach(function(key) {
				wpOpt.entry[key] = devClient.concat(wpOpt.entry[key]);
			});
		} else {
			wpOpt.entry = devClient.concat(wpOpt.entry);
		}
	});
```

**Comment by SpaceK33z** [comment]
Yeah since v2 `entry` will be required. webpack v2, but also webpack-dev-server v2, have a strict configuration validation which will throw an error if you try to use an option that is not existent, or when you use the wrong values for an option.
