### ISSUE TITLE
clientLogLevel 'none' is invalid 2.1.0-beta.11

### ISSUE THREAD

**Issue by stevewillard** [webpack/webpack-dev-server#693]
Version:
webpack-dev-server: 2.1.0-beta.11

In my webpack config I have:
```
  devServer : {
    clientLogLevel: 'none'
  },
```

With the latest webpack-dev-server I get this:
```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration.clientLogLevel should be one of these:
   "info" | "warning" | "error"
   Controls the log messages shown in the browser.
```

is 'none' a valid configuration?

**Comment by SpaceK33z** [comment]
Whoops, fixed. I'll wait a few days before releasing a new version to see if there are more issues with the new schema validation.

**Comment by josh18** [comment]
I also was having this issue until I found what it was via trial and error. This is the error message I was getting:
```
.../node_modules/webpack-dev-server/lib/Server.js:25
throw new OptionsValidationError(validationErrors);
^
```
Any idea what I am doing different?
node v7.0.0 npm v3.10.8

**Comment by stevewillard** [comment]
You just have to downgrade WDS and wait until the next version is released.

**Comment by josh18** [comment]
I'm just trying to figure out why you got an actual error message but I just got `throw new OptionsValidationError(validationErrors);`? It looks like it failed on "throw"? Might have nothing to do with WDS though so I'll do some research and see what I can find.

**Comment by SpaceK33z** [comment]
Fix released in v2.1.0-beta.12.

**Comment by josh18** [comment]
By the way the error doesn't get thrown properly in Node v7 for some reason (it might well be Nodes fault). It only show the stack trace and not the message. It works fine on Node v6 or if you put [this line](https://github.com/webpack/webpack-dev-server/blob/c4ba655f01094d0e6fdd2dd0a910bd83f90ff7fb/lib/OptionsValidationError.js#L5) at the bottom of the function.

**Comment by SpaceK33z** [comment]
Yeah there are many issues with Node.js v7. A few minutes ago I put a warning on the README, because the Node.js v7 issues seem endless and are not the fault of webpack-dev-server most of the time.

**Comment by josh18** [comment]
Ah ok, good to know.
