### ISSUE TITLE
webpack-dev-server stops

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack-dev-server#700]
I've generated my distribution files on `dist` folder. I've also installed `webpack@2.1.0-beta.22` and `webpack-dev-server@2.1.0-beta.2` globally.

When I perform `webpack-dev-server --context-base=./dist`:

    http://localhost:3000/
    webpack result is served from /
    content is served from D:\projects\living\user-platform\project\dist
    404s will fallback to /index.html
    [default] Checking started in a separate process...

After last message is shown `webpack-dev-server` stops.

Any ideas?

**Comment by SpaceK33z** [comment]
`[default] Checking started in a separate process...` -> this is not something fromw ebpack-dev-server as far as I know, are you using some plugins or something else that could cause this?

Also, please try to upgrade to the latest beta's of both webpack and webpack-dev-server. Debugging an old beta version is useless ;).

**Comment by jeusdi** [comment]
I've just installed `webpack@2.1.0-beta.27` and `webpack-dev-server@2.1.0-beta.11`.

Nevertheless, it's telling me that:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOp
tions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     ]
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursiv
e?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by SpaceK33z** [comment]
Ah yes, since webpack beta 25 there is configuration validation. See [this issue](https://github.com/wbuchwalter/tslint-loader/issues/38) to fix the `tslint` error. For the rest you'll need to read through the [upgrade guide](https://webpack.js.org/how-to/upgrade-from-webpack-1/).

**Comment by SpaceK33z** [comment]
Also note that `--context-base=./dist` is invalid, it should be `--content-base=./dist`.

**Comment by jeusdi** [comment]
I keep failing to figure out why `webpack-dev-server` stops. It doesn't leave any log and only tells me that:

```
[default] Checking started in a separate process...
```

I'm able to work fine with `webpack` command and it seems to generate artifacts correctly.
Any ideas?

**Comment by SpaceK33z** [comment]
@jeusdi, were you able to figure out your issue?

**Comment by jeusdi** [comment]
Yes, it's solved.
