### ISSUE TITLE
404 on loading referenced scripts

### ISSUE THREAD

**Issue by StefanRiedmann** [webpack/webpack-dev-server#702]
The page scripts polyfills.ts, vendor.ts main.ts and images.ts are rendered successfully when starting webpack-dev-server. But when opening the page (index.html is available), on loading the referenced scripts, I just get 404 in the output window when trying to load the referenced js files.

Here the configuration (same code base works perfectly for other team members). 
[webpack.common.js](https://gist.github.com/StefanRiedmann/31304750e6a41f308ecf4dbf8b8ae418#file-webpack-common-js)
[webpack.dev.js](https://gist.github.com/StefanRiedmann/31304750e6a41f308ecf4dbf8b8ae418#file-webpack-dev-js)

Windows Server 2008
webpack 1.13.1
webpack-dev-server 1.16.2

**Comment by SpaceK33z** [comment]
I don't have a Windows Server 2008 VM lying around, so you'll need to debug this a bit further on your own. The config seems fine.

**Comment by StefanRiedmann** [comment]
Ok understandable. But I don't know how to dig deeper into this... Do you think it can be particular behaviour on Windows Server 2008? My collegues work with Windows 10. But.... it worked fine for me until a week ago. I could not reproduce any steps I took when this error to appeared. 

One question: Where are the generated files (js) supposed to be when the server is running? Or are they being held in memory?

**Comment by stevewillard** [comment]
@StefanRiedmann webpack-dev-server holds them in memory.

It's hard to see exactly what's going on based on your config, but 404s sometime are related to a misconfigured publicPath property in your `output` block. I noticed you have it set as ```''```.

You could try setting publicPath to ```http://localhost:3000/``` or whatever port you're listening on with webpack-dev-server.

**Comment by StefanRiedmann** [comment]
That solved it! Thanks so much, I should have contacted you guys much earlier :-)
