### ISSUE TITLE
devServer hotOnly confusing error message

### ISSUE THREAD

**Issue by mulles3008** [webpack/webpack-dev-server#703]
Having configured `webpack/hot/dev-server` as an entry point as well as set `hot` to `true` (inside the `devServer` configuration object) leads to the error message:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.
```
The same accounts for `webpack/hot/only-dev-server` and `hotOnly` flag.

This error message seems inappropriate/diffcult to interprete.

**Comment by SpaceK33z** [comment]
Are you using the CLI or Node.js API?

**Comment by mulles3008** [comment]
CLI. Sorry, I should have mentioned.

**Comment by SpaceK33z** [comment]
In that case you should not add the entry point manually. I couldn't reproduce your issue. The error is confusing, but previously the server would start with a not correctly working config. With #615 we'll be working on better validation for this.

**Comment by SpaceK33z** [comment]
I'm assuming this worked for you since you reacted with a thumbs up, feel free to re-open if there is still an issue.
