### ISSUE TITLE
Continuous re-bundling, VALID state never reached

### ISSUE THREAD

**Issue by mischkl** [webpack/webpack-dev-server#705]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Oftentimes when a file is changed, webpack re-bundles, says the bundle is VALID then INVALID, rebundles again, again says VALID then INVALID, and over and over. The only way to interrupt the process is to press Ctrl-C and try again.

**If the current behavior is a bug, please provide the steps to reproduce.**
This issue occurs when using the following configuration:
https://gist.github.com/mischkl/cf7ab4b10df9763aa698a5b885f700cd

**What is the expected behavior?**
After max a couple of re-bundles the status changes to VALID

**Please mention your webpack and Operating System version.**
Webpack: 2.1.0-beta.26
OS: Windows 7 Enterprise x64

**Comment by SpaceK33z** [comment]
Note that webpack-dev-server doesn't control any of the watching, so the issue can't be fixed here. You could verify this with `webpack --watch`.

Do you have any special characters in your path? There are a couple of known issues with this (see https://github.com/webpack/webpack/issues/2258).

It could also be the same issue as https://github.com/webpack/webpack/issues/2320.

Or it could be https://github.com/webpack/watchpack/issues/25. I also have this issue sometimes, but very rarely.

**Comment by mischkl** [comment]
@SpaceK33z there are no special characters as in webpack/webpack#2258 and the output doesn't look like in webpack/webpack#2320. I guess it could be webpack/watchpack#25, although the files in question were not newly created...

**Comment by SpaceK33z** [comment]
Okay, I'm going to close this because we can't do anything about this in dev-server unfortunately.
