### ISSUE TITLE
webpack-dev-server Windows 10 consistent error

### ISSUE THREAD

**Issue by juanmagomezmayoral** [webpack/webpack-dev-server#706]
I'm not able to run a webpack-dev-server on the same repo my colleagues are using seamlessly.

I'm the only one using Windows 10. Others use either mac or Ubuntu.

My conf an the error I'm getting is:

```
PS D:\GitHub\frontagregador> npm -v
3.10.9
PS D:\GitHub\frontagregador> node -v
v7.1.0
PS D:\GitHub\frontagregador> npm run dev

> test-front-end-agregador@1.0.0 dev D:\GitHub\frontagregador
> webpack-dev-server --content-base src --inline --hot

 http://localhost:8080/
webpack result is served from /
content is served from D:\GitHub\frontagregador\src
404s will fallback to /index.html

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! test-front-end-agregador@1.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
npm ERR! Exit status 3221226505
npm ERR!
npm ERR! Failed at the test-front-end-agregador@1.0.0 dev script 'webpack-dev-server --content-base src --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test-front-end-agregador package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base src --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test-front-end-agregador
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test-front-end-agregador
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\frontagregador\npm-debug.log
```

**Comment by SpaceK33z** [comment]
Please try to narrow it down a bit more. Does it happen on node v6? Can you try running `node_modules/.bin/webpack-dev-server` directly?

**Comment by juanmagomezmayoral** [comment]
Thank you SpaceK33z for your answer. Running it directly is not a problem:

PS D:\GitHub\frontagregador> node_modules/.bin/webpack-dev-server
 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from D:\GitHub\frontagregador
404s will fallback to /index.html

and my versions are (as I've posted already) 

PS D:\GitHub\frontagregador> npm -v  
3.10.9

and 

PS D:\GitHub\frontagregador> node -v
v7.1.0

**Comment by juanmagomezmayoral** [comment]
The contents of the file are:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle test-front-end-agregador@1.0.0~predev: test-front-end-agregador@1.0.0
6 silly lifecycle test-front-end-agregador@1.0.0~predev: no script for predev, continuing
7 info lifecycle test-front-end-agregador@1.0.0~dev: test-front-end-agregador@1.0.0
8 verbose lifecycle test-front-end-agregador@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle test-front-end-agregador@1.0.0~dev: PATH: D:\GitHub\frontagregador\node_modules\.bin;D:\nodejs\node_modules\npm\bin\node-gyp-bin;D:\nodejs\;C:\Users\juanm\AppData\Roaming\npm (AND other not related paths)
10 verbose lifecycle test-front-end-agregador@1.0.0~dev: CWD: D:\GitHub\frontagregador
11 silly lifecycle test-front-end-agregador@1.0.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server --content-base src --inline --hot' ]
12 silly lifecycle test-front-end-agregador@1.0.0~dev: Returned: code: 3221226505  signal: null
13 info lifecycle test-front-end-agregador@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: test-front-end-agregador@1.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
14 verbose stack Exit status 3221226505
14 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid test-front-end-agregador@1.0.0
16 verbose cwd D:\GitHub\frontagregador
17 error Windows_NT 10.0.14393
18 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error test-front-end-agregador@1.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
22 error Exit status 3221226505
23 error Failed at the test-front-end-agregador@1.0.0 dev script 'webpack-dev-server --content-base src --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test-front-end-agregador package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --content-base src --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test-front-end-agregador
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test-front-end-agregador
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SpaceK33z** [comment]
I knew that your Node.js version was v7, but I wanted you to try if it worked on v6. It looks like this isn't a problem I can fix in webpack-dev-server, since running it directly does work as you said.

**Comment by juanmagomezmayoral** [comment]
ok, sorry, didn't undertand you.  I've run it on v6 node and it works (lots of non-related errors like 
ERROR in ./src/layouts/footer/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/css-loader/index.js in D:\GitHub\frontagregador/src\layouts\footer
 @ ./src/layouts/footer/styles.scss 4:14-199 but the webserver is up)

It seems to be an issue related to node v7 then...

thanks
J

**Comment by SpaceK33z** [comment]
Okay, I'm going to close this for now since we have many other issues with the watch functionality and node v7 anyway.
