### ISSUE TITLE
Hot Reloading jsx not working for past couple days.

### ISSUE THREAD

**Issue by Orbyt** [webpack/webpack-dev-server#708]
**What is the current behavior?**

As of about 2 days ago, hot reloading of react code does not seem to be working for me. It does however seem to continue to reload css changes just fine.

I performed no config changes.

Versions:
Node: 6.9.1
webpack-dev-server: 1.16.1 as well as tested on 1.16.2

**Comment by SpaceK33z** [comment]
You'll need to give much more info than that, there hasn't been a release on webpack-dev-server 1.16.x for weeks...

**Comment by Orbyt** [comment]
Let me know what info you need. As stated, I haven't performed any config changes.

Webpack is v1.13.3 installed locally, webpack-dev-server is installed as a dev dependency. Im not sure how I can further debug. The only added packages i've recently added have been `axios` and `got`. I doubt they would cause a conflict, but I will remove them and test again.

**Comment by Orbyt** [comment]
I've tried removing the above packages, though the issue persists. For thoroughness, i've also tried deleting the node_modules directory and reinstalling dependencies. That also did not fix the issue.

As mentioned, it still reloads CSS, but seems to be ignoring changes in my react code.

**Comment by SpaceK33z** [comment]
What React and react hot loader versions do you have? Make sure these are both the latest. React recently had an upgrade that makes it no longer work with old versions of react hot loader.

**Comment by Orbyt** [comment]
React version is 15.4.1. Not using react-hot-loader.

**Comment by SpaceK33z** [comment]
What are you using for hot loading React then?

**Comment by Orbyt** [comment]
@SpaceK33z My npm watch script is simply: `"watch": "webpack-dev-server --hot --inline",`. Considering you're comments, It sounds like I shouldn't of had hot reloading without react-hot-loader, so I am not sure how it was working.

**Comment by SpaceK33z** [comment]
Correct, hot reloading for React components can't work without something that "accepts" the hot module and forces your component tree to re-render. [react-hot-loader](https://github.com/gaearon/react-hot-loader) should take care of this for you. For css, this is built-in the style-loader, hence this works out-of-the-box. If css hot reloading still works, it's definitely not an issue in webpack-dev-server.

**Comment by Orbyt** [comment]
I wonder if perhaps something built into electron was aiding it. Tutorial like [these](https://medium.com/@Agro/developing-desktop-applications-with-electron-and-react-40d117d97564#.ypefws23x) don't mention react-hot-loader either. Odd.

Regardless, I'll go ahead and close this, as it must not be an issue with webpack-dev-server.

**Comment by Orbyt** [comment]
@SpaceK33z Noticed something interesting. While my React views will not hot reload, other .jsx files will hot reload (eg, `router.jsx`). Again, `react-hot-loader` is not implemented. Why would that file be able to hot reload while the `.jsx` files for my view components are not?
