### ISSUE TITLE
Proxy errors should return 504

### ISSUE THREAD

**Issue by graingert** [webpack/webpack-dev-server#712]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Proxy errors return 500

**If the current behavior is a bug, please provide the steps to reproduce.**
configure dev server proxy to a host that does not respond

**What is the expected behavior?**
Proxy errors return 504

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
webpack 2, Linux

**Comment by SpaceK33z** [comment]
This could be an error in [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware).

Are you interested in doing a PR?

**Comment by graingert** [comment]
yup it's here: https://github.com/chimurai/http-proxy-middleware/blob/7d1865c84f4339ced230b0292db42c4d45376f1a/lib/handlers.js#L53

**Comment by graingert** [comment]
@SpaceK33z here's the PR: https://github.com/chimurai/http-proxy-middleware/issues/131

**Comment by SpaceK33z** [comment]
Closing since your PR was merged.

**Comment by graingert** [comment]
Nice, can you bump the version?

**Comment by chimurai** [comment]
A fresh `npm install` after removing `node_modules` should fetch the newer HPM v0.17.3

---

"http-proxy-middleware": "~0.17.1"
https://semver.npmjs.com/
