### ISSUE TITLE
Entries with relative paths for names not creating bundles in WDS

### ISSUE THREAD

**Issue by travislaynewilson** [webpack/webpack-dev-server#715]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm using Webpack to bundle an Angular 2 app. I need my bundles placed in different folders of the target folder, so I'm using relative paths for the name of each of my entry:
```javascript
entry: {
    '/lib/polyfills': './src/polyfills.browser.ts',
    '/lib/vendor': './src/vendor.browser.ts',
    '/v/app/main': './src/main.browser.ts'
}
```
I know this isn't documented, but I've seen this solution online and it works well for me. All is working when using `webpack`, but when I use `WDS`, the bundles are never created.

**What is the expected behavior?**
Similar to how Webpack places the bundles in the path specified by the entry name, I'd expect WDS to do the same in memory.

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://gist.github.com/travislaynewilson/d8f680989cf7641f353d9be44f41d9bd 

**Webpack Dev Server version**
2.1.0-beta.11

**Webpack version**
2.1.0-beta.27

**Operating system**
Windows 10

**Comment by SpaceK33z** [comment]
This is probably a bug in webpack-dev-middleware. There is a test suite for generating these kind of url's, [see here](https://github.com/webpack/webpack-dev-middleware/blob/master/test/GetFilenameFromUrl.test.js).

Would you be interested in creating a PR for this? Best way to do this would be to add a failing test case and try to fix it. If you can't fix it, submitting a failing test case is also fine.

**Comment by shellscape** [comment]
Closing due to age and inactivity.
