### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack-dev-server#717]
I'm getting this error message from `webpack-dev-server`:

    ERROR in multi main
    Module not found: Error: Can't resolve 'D:\projects\living\user-platform\project\src' in 'D:\projects\living\user-platfo
    rm\project'
     @ multi main

Currently, my webpack config files are:

* [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7)
* [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092)
* [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)

Current directory structure:

    ├───.vscode
    ├───config
    │   ├───html-elements-plugin
    │   └───modules
    └───src
        ├───app
        │   ├───another
        │   ├───dashboard
        │   ├───error
        │   ├───layout
        │   │   ├───chat-sidebar
        │   │   │   └───chat-message
        │   │   ├───navbar
        │   │   ├───notifications
        │   │   ├───pipes
        │   │   ├───sidebar
        │   │   └───widget
        │   ├───login
        │   ├───profile
        │   ├───scss
        │   ├───signin
        │   └───validate
        └───assets
            ├───css
            ├───demo
            │   └───notifications
            ├───fonts
            │   ├───font-awesome
            │   ├───glyphicons
            │   └───google
            ├───icon
            ├───img
            │   └───people
            └───mock-data

**Comment by SpaceK33z** [comment]
Could you please ask this on StackOverflow? This is a support question, not a bug in webpack-dev-server.

**Comment by jeusdi** [comment]
Posted on:
http://stackoverflow.com/questions/41218553/webpack-module-not-found-error-cant-resolve-folder-src

**Comment by SpaceK33z** [comment]
Thanks. Let's reopen if it turn outs to be a webpack-dev-server bug.
