### ISSUE TITLE
there will be no error when no webpack-dev-server installed

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack-dev-server#729]
![image](https://cloud.githubusercontent.com/assets/1060733/21585910/6c0e886c-d104-11e6-8275-b86fe359848c.png)

i haven't installed webpack-dev-server in my package
and then i run the command `npm run dev`
as you can guess,it couldn't success
but there was no error shown in the console
it's a pain

**Comment by SpaceK33z** [comment]
If you don't even have webpack-dev-server installed, how can it be the fault of webpack-dev-server that it doesn't give an error? Please do some research first and then ask on StackOverflow.

**Comment by zzzgit** [comment]
i mean only globally installed but without a local installation,and there will be no error for that
