### ISSUE TITLE
Socket.io 0.9.7

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack-dev-server#73]
Perhaps socket.io could be updated to 1.2.

**Comment by abrkn** [comment]
:+1:

**Comment by TeffenEllis** [comment]
:+1:

**Comment by uipoet** [comment]
No wonder, I've been seeing so many issues with the connection dropping. This is a must fix before I will try depending on this server for development again.

**Comment by jhnns** [comment]
Send a PR :)
