### ISSUE TITLE
Add option to enable client overlay (like one that 'webpack-hot-middleware' provides).

### ISSUE THREAD

**Issue by stsiarzhanau** [webpack/webpack-dev-server#735]
**Do you want to request a *feature* or report a *bug*?**
Request a *feature*.

**What is the current behavior?**
Error messages are shown in terminal and browser devTools console.

**What is the expected behavior?**
If an error occurs a semi-transparent overlay containing error message is shown in browser window (in addition to error messages in terminal and browser devTools console).

**If this is a feature request, what is motivation or use case for changing the behavior?**
Just a nice way to provide information about errors (sometimes it's not convenient to keep terminal window and browser devTools opened).

**Please mention your webpack and Operating System version.**
webpack 2.2.0-rc.3
webpack-dev-server 2.2.0-rc.0
Windows 10

**Comment by SpaceK33z** [comment]
This is definitely an interesting feature, and I have thought about this before. What I'm not sure about though is if webpack-dev-server should include a script like this, or if this should be handled in user-land (e.g. as a separate package or in your own bundle). webpack-dev-server already has the required hooks for this, see https://github.com/webpack/webpack-dev-server/issues/481#issuecomment-258610429 for an example API.

**Comment by stsiarzhanau** [comment]
In my opinion it should be included and configured just like other options ( --overlay or overlay: true). webpack-dev-server is like an all-in-one and ready-to-use solution (it includes [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback),  [compression](https://www.npmjs.com/package/compression) and other useful stuff). Why not to add another cool feature? I think that list of devDependencies in modern projects is long enough to create separate package that will be used primarily with webpack-dev-server.

 What are the cons of such solution?

**OFFTOP:** In webpack 2 docs there's an [example](https://webpack.js.org/guides/hmr-react/). It's reccommended to include line like this `'webpack-dev-server/client?http://localhost:8080'` into entries array. But I skim through WDS source code and it seems like WDS handle this automatically. So there's no need to hardcode it in webpack config. And, as WDS can find another port (if 8080 is in use), it's better to not hardcode. Am I right?

**Comment by SpaceK33z** [comment]
Closing since in 2.3.0 we actually released [this feature](https://github.com/webpack/webpack-dev-server/releases/tag/v2.3.0). Completely forgot about this issue.
