### ISSUE TITLE
change style will not reflect in browser

### ISSUE THREAD

**Issue by craigcosmo** [webpack/webpack-dev-server#738]
webpack-dev-server 2.2.0-rc.0

description:
Change style and the browser won't refresh. Even I'm running --inline --hot

Please refer the issue in the vid below

https://youtu.be/kiUF9eUGydY

reproducing: https://github.com/craigcosmo/webpack-dev-server-2-bug

**Comment by SpaceK33z** [comment]
Repository gives a 404... Also note that this most likely isn't a bug with webpack-dev-server, it does almost nothing with hot reloading. most of that code is in webpack/webpack.

**Comment by craigcosmo** [comment]
@SpaceK33z my bad, the repo is now accessible. Please check again.

**Comment by SpaceK33z** [comment]
Did this ever even work? AFAIK CSS reloading doesn't work with extract-text-plugin. You have to use style-loader in development for that, because style-loader contains the necessary code to actually perform the hot reload part. Also see https://github.com/webpack/extract-text-webpack-plugin/issues/30

**Comment by craigcosmo** [comment]
actually that set up work well in webpack 1 and web dev server 1. 

You can try and see: https://github.com/craigcosmo/demo-for-onibag

**Comment by SpaceK33z** [comment]
Hmm, I tested your repo and it doesn't really hot reload, it just refreshes the page. Are you using hot reloading for React? From your repo it doesn't look like it. In that case you should remove `--hot`. After that it will probably properly reload your page again after a CSS change.

**Comment by craigcosmo** [comment]
no in my demo repo just shared with you, I'm not using hot reload for react. I use web dev server HMR which the `--hot` flag. My css always refresh when I change it.

**Comment by SpaceK33z** [comment]
> no in my demo repo just shared with you

So in your real repo you're not using hot reload too? I don't get why you're using `--hot`...

**Comment by craigcosmo** [comment]
yes, I don't use hot reload in any repos or project. the only thing I use is the `--inline --hot` flag. My css has been refreshing with no problem until I use web pack 2. But base on your suggestion, removing the --hot flag, the browser now refreshed to my css changes.

So, apparently the `--hot` in web pack 2 and 1 is quite different, despite the same name
