### ISSUE TITLE
Enhancement request: Custom url for --open flag

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack-dev-server#739]
Would it be possible to add the ability to specify a custom url to open in the browser with the --open flag? 

webpack-dev-server --host 0.0.0.0 --open somealias.com

i sometimes use an alias for localhost to communicate what environment i'd like my app to run in.

**Comment by SpaceK33z** [comment]
Have you tried using `--public somealias.com`? Not sure if it fits your use-case.

**Comment by bdwain** [comment]
i think that just affects the code that webpack injects into the page to talk to the dev server. I was looking for a way to open somealias.come in the browser when the page opens, but i'd still like to have the host be 0.0.0.0 so other computers on my network can access my dev server.

**Comment by SpaceK33z** [comment]
Okay, fair enough. The PR #725 attempts to fix this, but only for `localhost`. Could you perhaps file a PR to do it with the `--public` flag? I'll close #725 then.

**Comment by bdwain** [comment]
sure i can do that

**Comment by shellscape** [comment]
It appears that #749 fixed this issue, so closing. please ping me if that's not the case and we'll reopen the discussion.
