### ISSUE TITLE
Proxy bypass doesn't work with Angular2 routing?

### ISSUE THREAD

**Issue by atalis** [webpack/webpack-dev-server#743]
I'm implementing login for our Angular2 application. When the Login button is clicked, an HTTP request to "/doLogin" is issued. The Webpack-dev-server is configured to proxy that URL segment (together with a couple of others) to the backend server:

```
  proxy: [{
    context: ['/doLogin', ...],
    target: 'http://mybackendserver.com',
    secure: false
  }]
```
On successful authentication the backend server redirects the response to '/dashboard'. (Note that we're using the PathLocationStrategy, no hashes.) But in some situations, based on a command-line argument, I want to bypass auth and go directly to the Dashboard when the Login button is clicked.  So I added a bypass option for login:

```
  proxy: [{
    context: ['/doLogin', ...],
    target: 'http://mybackendserver.com',
    secure: false,
    bypass: function(req, res, proxyOptions) {
      if (req.url == '/doLogin' && SKIP_LOGIN) {
        return '/dashboard';
      }
    }
  }]
```

However, the dashboard is never loaded. The page is reloaded with the default fallback route (which is the login page again). I tried debugging into the Angular routing code, and I'm pretty sure '/dashboard' never shows up there.

Am I missing something or is there a bug in the proxy implementation?

We're currently using webpack v. 2.1.0-beta.22, webpack-dev-server v. 2.1.0-beta.2 and webpack-dev-middleware v. 1.6.1, although I tried with various combinations of more recent versions, including webpack-dev-server 2.2.0-rc.0, but they all behave the same way with regard to proxy bypass.

**Comment by SpaceK33z** [comment]
I don't think you can use `bypass` like that. You want to let it behave as a 301 redirect, but this `bypass` the path you return in `bypass` is mapped to a file in the memory file system. So you could e.g. return `/index.html` there. We use [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) for the proxying, so you could search that documentation for it.

**Comment by atalis** [comment]
Thanks for your response.  The problem is, that with a single page application index.html is the only thing there is, the rest is just relative paths, so loading index.html is not very helpful.  I will look at http-proxy-middleware, as you suggested.
