### ISSUE TITLE
How can I change http://localhost:8080/index.html to just http://localhost/

### ISSUE THREAD

**Issue by atulrpandey** [webpack/webpack-dev-server#75]
Great work there! From the docs, I see webpack-dev-server is express 3.x server and I was trying to replace `/index.html` with just a slash (`/`) but I couldn't.

Any way to do it? I tried `server.app.get("/", ...)` but that doesn't work.

**Comment by altano** [comment]
Try setting the --history-api-fallback option (https://github.com/webpack/webpack-dev-server/tree/master/example#history-api-fallback)

**Comment by SpaceK33z** [comment]
The [historyApiFallback](https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option) does this exactly.
