### ISSUE TITLE
proxy limit

### ISSUE THREAD

**Issue by dantegg** [webpack/webpack-dev-server#750]
i want to connect two backends by using webpack-dev-server proxy config  
```
proxy: [{
      path: `/v1/*`,
      target: 'http://192.168.1.1',
      secure:false,
      rewrite: function(req) {
           req.url = req.url.replace(/^\/v1/, '');
      }
},{
  path: `/v2/*`,
      target: 'http://192.168.1.2',
      secure:false,
      rewrite: function(req) {
              req.url = req.url.replace(/^\/v2/, '');
            }
}],  
```   
but this is useless
so is it true that i can only use one rule in proxy config?

**Comment by SpaceK33z** [comment]
> so is it true that i can only use one rule in proxy config?

no that is not true. We use the package http-proxy-middleware for proxying, please see its [docs](https://github.com/chimurai/http-proxy-middleware). You need to use `pathRewrite`.
