### ISSUE TITLE
Specifying browser for --open flag

### ISSUE THREAD

**Issue by TrySound** [webpack/webpack-dev-server#753]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Opens default browser which is not always dev browser

**What is the expected behavior?**

Adding ability to specify browser like

`webpack-dev-server --open chrome`

**If this is a feature request, what is motivation or use case for changing the behavior?**

Different environments

**Comment by SpaceK33z** [comment]
Good idea. Looks like the `opn` package [supports it](https://github.com/sindresorhus/opn#usage). PR welcome!

**Comment by carloscuatin** [comment]
support names of package `opn` example for:

```bash
macOS: google chrome
Linux: google-chrome
Windows: chrome
```

or support `chrome` for all S.O ?

**Comment by typerory** [comment]
I just downloaded [https://polypane.rocks](url) and came running here to see how I can have webpack open that up (dev browser) instead of my default 'browsing' browser.

**Comment by Kilian** [comment]
@typerory creator of Polypane here, let me see if I that's something I can do :)
