### ISSUE TITLE
Using socket.io in the dev-server?

### ISSUE THREAD

**Issue by ArnoBuschmann** [webpack/webpack-dev-server#76]
I wanted to use socket.io in my project, so I added this to the express server.js file:
```javascript
/**
 * Initialize socket.io
 */
var http = require('http').Server(app);
var io = require('socket.io')(http);
io.on('connection', function(socket){
        console.log('neue Socket-Connection');
        socket.on('event', function(data){});
        socket.on('disconnect', function(){});
});
```
Now when creating a production build, the socket communication between client and server works nicely as expected.

But: Unfortunately it is not working when running the Webpack dev server :(

Has anyone an idea how that could be fixed?

**Comment by wmertens** [comment]
@jhnns wouldn't it be a better solution to configure webpack-dev-server so it doesn't intercept `/socket.io-client` but instead uses e.g. `/__webpack-dev`? Then proxying would work normally.

**Comment by ocyedwin** [comment]
Hi @ArnoBuschmann , did you manage to find a good solution? I'm having the same problem.

**Comment by wmertens** [comment]
@ocyedwin yes, simply rename the path of your own socket. Right now the hot-loader is using `/socket` which captures everything starting with socket.

**Comment by ocyedwin** [comment]
@wmertens okay, thanks!

**Comment by raineroviir** [comment]
I wasn't able to use socket.io + webpack-dev-server.  But like @jhnns mentioned using webpack-dev-middleware in addition to https://www.npmjs.com/package/webpack-hot-middleware gives you hot-reloading without webpack-dev-server

**Comment by scottmcnab** [comment]
I think this issue could be fixed if #220 was implemented? Then the hot loader could listen to a custom url path that does not conflict with the app, such as /__webpack-dev/socket.io

**Comment by wmertens** [comment]
Yup.

On Sat, Aug 8, 2015, 18:53 scottmcnab <notifications@github.com> wrote:

> I think this issue could be fixed if #220
> <https://github.com/webpack/webpack-dev-server/issues/220> was
> implemented? Then the hot loader could listen to a custom url path that
> does not conflict with the app, such as /__webpack-dev/socket.io
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpack/webpack-dev-server/issues/76#issuecomment-129012023>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by mlucool** [comment]
I am running into the same problem, is there any better solution than rename the apps io path (which will likely leads to more problems down the road)?

**Comment by SpaceK33z** [comment]
As of v0.13 (#302) socket.io is replaced with sockjs, so you would no longer have this problem.
