### ISSUE TITLE
Configuration.port should be a number

### ISSUE THREAD

**Issue by ismay** [webpack/webpack-dev-server#761]
When initialising webpack-dev-server 2.2.0 I get the following error:

```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration.port should be a number.
error Command failed with exit code 1.
```

I'm reading the port from an environment variable (with the contents `8080`). Using `port: parseInt(process.env.DEV_PORT)` ([here](https://github.com/forecastxl/prototype/blob/develop/webpack.config.dev.js#L53)) solves the problem, but I was just wondering if this is meant to work like this, as I have no way to influence whether the environment variable reads as a string or a number, other than using parseInt.

**Comment by SpaceK33z** [comment]
I'm not completely sure about this. Technically an integer is the most correct form, but an integer also works. `parseInt()` is the way to go, at least for now.
