### ISSUE TITLE
webpack-dev-server 2.2.0 keeps reloading on Firefox 50

### ISSUE THREAD

**Issue by gfx** [webpack/webpack-dev-server#762]
**Do you want to request a *feature* or report a *bug*?**

a bug.

**What is the current behavior?**

Firstly, if I open a page that uses JS provided by webpack-dev-server, it works.

When I move to another page, it doesn't work. Seemingly the browser keeps reloading with lots of HTTP requests to the app server. Browser console just says "[WDS] Disconnected!".

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open a web app that uses 
2. Click a link to move another page
3. Seemingly nothing occurs. See the app server logs and browser console.

**What is the expected behavior?**

Moves to another page on clicking a link.

**Please mention your webpack and Operating System version.**

NodeJS: 6.9.4
webpack: 2.2.0
webpack-dev-server: 2.2.0
webpack-dev-middleware: 1.9.0
Firefox: 51.0 (64bit)
macOS: 10.12.2

devServer settings in webpack config:

```js
// ...
  config.devServer = {
    port: devServerPort,
    headers: { 'Access-Control-Allow-Origin': '*' },
    stats: 'minimal',
  };
// ...
```

**Comment by SpaceK33z** [comment]
I will need a minimal repository that reproduces the bug for this, since this does work correctly in my testing.

**Comment by SpaceK33z** [comment]
@gfx are you able to provide a repo to reproduce?

**Comment by gfx** [comment]
@SpaceK33z Because my project is complex, I can't reproduce it in minimum projects.

**Comment by bstrickl** [comment]
We ran into something similar that may be the same issue. Ours seems to be [this issue](https://github.com/sockjs/sockjs-client/issues/308) which looks like it can be resolved if sockjs-client is updated from 1.1.1 to 1.1.2.

**Comment by SpaceK33z** [comment]
I've updated the deps with 9d2925c5c0efe33bea3bdb858e3f59cfad1d87c8, will release a new version soonish.

**Comment by samsch** [comment]
This issue seems similar or a duplicate of #544. I also am seeing this problem on a complex project, and having difficulty narrowing down where the cause is.

I'm using webpack-dev-server 2.4.1, so it doesn't seem that issue is the same. Again, the issue is in Firefox (52), and it works fine in Chrome.

**Comment by smiile** [comment]
Try disabling redux-devtools
