### ISSUE TITLE
Adopt browser support policy

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack-dev-server#767]
At the moment we don't have a browser support policy, so sometimes we get issues that something doesn't work in IE8 / IE9.

We need to think what browsers we need to support, and document that in the README.

Note that webpack itself also has none. It seems to support IE9+ (need to check to be sure).

**Comment by shellscape** [comment]
Since Microsoft has officially ended support for oldIE (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) we can safely close this one. Specific version support can be contributed if the workarounds are reasonable.
