### ISSUE TITLE
Code splitting entry with webpack-dev-server unclear

### ISSUE THREAD

**Issue by awitherow** [webpack/webpack-dev-server#768]
In order for code splitting to work, entry has to be an object.

```
...
entry: {
  main: './index.js',
  vendor: 'moment'
},
```

but in the webpack-dev-server documentation it is displayed as an array to contain the webpack-dev-server stuff.

```
entry: [
  'react-hot-loader/patch',
  'webpack-dev-server/client?http://localhost:8080',
   'webpack/hot/only-dev-server',
   './index.js'
],
 ```
How can these two approaches be combined so that I can split out my vendor files and still have HMR?

**Comment by SpaceK33z** [comment]
```
entry: {
    main: ['webpack-dev-server/client?http://localhost:8080', './index.js']
}
```

But note that if you use the CLI, this will be done automatically for you.

**Comment by awitherow** [comment]
@SpaceK33z thanks! What would the example cli look like?

**Comment by SpaceK33z** [comment]
Just `webpack-dev-server` in the CLI if you use v2, for v1 it's `webpack-dev-server --inline`.
