### ISSUE TITLE
webpack/webpack-dev-server 2 throws `ERROR in json.js - Parenthesized pattern`

### ISSUE THREAD

**Issue by aaronbeall** [webpack/webpack-dev-server#772]
**Do you want to request a *feature* or report a *bug*?**

Report an error. But it could be user error. :)

**What is the current behavior?**

When running `webpack-dev-server` I get the error:

```
ERROR in ./~/json3/lib/json3.js
Module parse failed: /node_modules/json3/lib/json3.js Parenthesized pattern (89:12)
You may need an appropriate loader to handle this file type.
|           if (stringifySupported) {
|             // A test function object with a custom `toJSON` method.
|             (value = function () {
|               return 1;
|             }).toJSON = value;
 @ ./~/sockjs-client/lib/main.js 7:12-28
 @ ./~/sockjs-client/lib/entry.js
 @ (webpack)-dev-server/client/socket.js
 @ (webpack)-dev-server/client?http://localhost:8080
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./main.tsx
```

**If the current behavior is a bug, please provide the steps to reproduce.**

My configuration for a React + TypeScript project:

```
module.exports = {
    context: __dirname + "/src",
    entry: "./main.tsx",
    output: {
        path: __dirname + "/dist",
        filename: "bundle.js"
    },
    devServer: {
     contentBase: __dirname + "/src",
    },
    devtool: "source-map",
    resolve: {
        extensions: [".tsx", ".ts", ".js"]
    },
    module: {
        loaders: [
            {
                test: /\.tsx?$/,
                loader: "ts-loader",
                exclude: /node_modules/
            }
        ]
    }
}
```

This config works without problems using `webpack-dev-server@1` (the only config difference being `""` added to `extensions: ["", ".tsx", ".ts", ".js"]` ).

I am not using `json3` directly in code anywhere. 

**What is the expected behavior?**

No error.

**Please mention your webpack and Operating System version.**

- webpack/webpack-dev-server 2.2.1
- OSX 10.11.4

**Comment by melbourne2991** [comment]
Experiencing the same problem

**Comment by SpaceK33z** [comment]
Can you reproduce this without TypeScript? I didn't manage to reproduce it, but I don't know (and don't want to spend the time) to configure Typescript exactly to reproduce this. Note that if it only occurs with TypeScript, it doesn't belong here.

**Comment by SpaceK33z** [comment]
Try to change `modules.loaders` to `module.rules`.

**Comment by SpaceK33z** [comment]
If that doesn't work, checkout https://github.com/webpack/webpack/issues/4184#issuecomment-277127386

**Comment by yakovkhalinsky** [comment]
I can confirm that installing acorn 4.0.7 manually fixes the issue

**Comment by aaronbeall** [comment]
It seems to have been the acorn issue... I blew away node_modules and re-installed `webpack@2 webpack-dev-server@2` and the problem no longer exists, when I look at the acord package it is using `4.0.8` which apparently fixed the issue.
