### ISSUE TITLE
hot update doesn't update view

### ISSUE THREAD

**Issue by ifree92** [webpack/webpack-dev-server#773]
At first I show you this demonstration project - https://github.com/ifree92/webpack-livereload-bug 

The root of problem is described in README.md 

The problem

After server starts success (with showing compiled files) then ran Google Chrome with http://localhost:8080 and then in chrome dev tools I see this (looks like it's success too):

```
[HMR] Waiting for update signal from WDS...
bundle.js:18591 Download the React DevTools for a better development experience: https://fb.me/react-devtools
bundle.js:13485 [WDS] Hot Module Replacement enabled.
```

After some files are changed, I see this in chrome dev tools:

```
(2) bundle.js:13485 [WDS] App updated. Recompiling...
bundle.js:13485 [WDS] App hot update...
```

but nothing changed in browser. May be I do something wrong?

**Comment by SpaceK33z** [comment]
You should first start with updating webpack-dev-server to `2.2.1`. Could you please ask this on StackOverflow? This is more of a usage question, not a bug report. If you have a reduced test case that shows something is wrong in webpack-dev-server, then it's fine.

**Comment by ifree92** [comment]
@SpaceK33z thanks a lot!
You're right with webpack version.
I have just installed webpack@1.14.0 and it works as well.

Will wait when webpack-dev-server will updates to have nice working with new webpack version.
