### ISSUE TITLE
npm run server:dev

### ISSUE THREAD

**Issue by Cuica20** [webpack/webpack-dev-server#774]
We have a problem when write "npm run server:dev"
npm -v: 4.1.2 
node: v6.7.0

Here the error message:
> npm ERR! node v6.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! smartadmin@0.2.1 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the smartadmin@0.2.1 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smartadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smartadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smartadmin
npm ERR! There is likely additional logging output above.

> Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle smartadmin@0.2.1~start: Returned: code: 1  signal: null
smartadmin@0.2.1~start: Failed to exec start script
Error: smartadmin@0.2.1 start: npm run server:dev
Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\...\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
emitTwo (events.js:106:13)
EventEmitter.emit (events.js:191:7)
ChildProcess.<anonymous> (C:\....\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

package.json

> {
  "name": "smartadmin",
  "version": "0.2.1",
  "license": "WRAPBOOTSTRAP",
  "scripts": {
    "build:dev": "./node_modules/.bin/webpack --config config/webpack.dev.js --progress --profile",
    "build:prod": "./node_modules/.bin/webpack --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci": "npm run lint && npm test && npm run e2e",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean:start": "npm start",
    "clean": "npm cache clean && npm run rimraf -- node_modules doc coverage dist",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "e2e:live": "npm run e2e -- --elementExplorer",
    "e2e": "npm run protractor",
    "github-deploy:dev": "./node_modules/.bin/webpack --config config/webpack.github-deploy.js --progress --profile --env.githubDev",
    "github-deploy:prod": "./node_modules/.bin/webpack --config config/webpack.github-deploy.js --progress --profile --env.githubProd",
    "github-deploy": "npm run github-deploy:dev",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "postversion": "git push && git push --tags",
    "prebuild:dev": "npm run clean:dist",
    "prebuild:prod": "npm run clean:dist",
    "preclean:install": "npm run clean",
    "preclean:start": "npm run clean",
    "pree2e": "npm run webdriver:update -- --standalone",
    "preversion": "npm test",
    "protractor": "protractor",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "./node_modules/.bin/webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "karma start config/karma",
    "tslint": "tslint",
    "typedoc": "typedoc",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.4.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@progress/kendo-angular-buttons": "^0.10.3",
    "@progress/kendo-angular-dialog": "^0.11.0",
    "@progress/kendo-angular-dropdowns": "^0.13.0",
    "@progress/kendo-angular-grid": "^0.13.2",
    "@progress/kendo-angular-intl": "^0.9.0",
    "@progress/kendo-angular-upload": "^0.13.1",
    "@progress/kendo-data-query": "^0.3.5",
    "@telerik/kendo-theme-default": "^1.28.1",
    "X-editable": "github:vitalets/x-editable",
    "angular-in-memory-web-api": "^0.2.1",
    "angular2-busy": "^1.0.2",
    "angular2-jwt": "^0.1.27",
    "angular2-notifications": "^0.4.47",
    "bootstrap": "^3.3.7",
    "bootstrap-colorpicker": "^2.3.5",
    "bootstrap-duallistbox": "github:istvan-ujjmeszaros/bootstrap-duallistbox",
    "bootstrap-markdown": "^2.10.0",
    "bootstrap-progressbar": "^0.9.0",
    "bootstrap-slider": "^9.1.3",
    "bootstrap-tagsinput": "^0.7.1",
    "bootstrap-timepicker": "^0.5.2",
    "chart.js": "^2.3.0",
    "clockpicker": "0.0.7",
    "clone": "~2.0.0",
    "core-js": "^2.4.1",
    "debounce": "^1.0.0",
    "dropzone": "^4.3.0",
    "dygraphs": "^1.1.1",
    "fuelux": "^3.15.8",
    "he": "^1.1.0",
    "highcharts": "^4.2.7",
    "ion-rangeslider": "^2.1.4",
    "jquery": "^2.2.4",
    "jquery-color": "^1.0.0",
    "jquery-jcrop": "^0.9.13",
    "jquery-knob": "^1.2.11",
    "jquery-ui-npm": "^1.12.0",
    "jquery-validation": "^1.15.1",
    "jquery.maskedinput": "^1.4.1",
    "markdown": "^0.5.0",
    "morris.js": "^0.5.0",
    "ng2-auto-complete": "^0.7.4",
    "ng2-bootstrap": "^1.1.16-9",
    "ng2-charts": "^1.5.0",
    "ng2-completer": "^0.2.3",
    "ng2-datepicker": "^1.1.1",
    "ng2-popover": "0.0.13",
    "ng2-redux": "4.2.1",
    "nouislider": "^8.5.1",
    "raphael": "^2.2.1",
    "redux": "^3.6.0",
    "rxjs": "^5.0.3",
    "scriptjs": "^2.5.8",
    "select2": "^4.0.3",
    "smartadmin-plugins": "^1.0.15",
    "summernote": "^0.8.1",
    "to-markdown": "^3.0.1",
    "ts-helpers": "^1.1.1",
    "webpack": "^2.2.0-rc.3",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler": "^2.4.1",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "^2.2.34",
    "@types/node": "^6.0.38",
    "@types/selenium-webdriver": "2.53.33",
    "@types/source-map": "^0.1.27",
    "@types/uglify-js": "^2.0.27",
    "@types/webpack": "^1.12.34",
    "angular-router-loader": "^0.4.0",
    "angular2-template-loader": "^0.6.0",
    "assets-webpack-plugin": "^3.5.0",
    "awesome-typescript-loader": "^2.2.1",
    "codelyzer": "~1.0.0-beta.4",
    "copy-webpack-plugin": "^4.0.0",
    "css-loader": "^0.26.0",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.9.0",
    "gh-pages": "^0.12.0",
    "html-minify-loader": "^1.1.0",
    "html-webpack-plugin": "^2.21.0",
    "ie-shim": "^0.1.0",
    "imports-loader": "^0.6.5",
    "istanbul-instrumenter-loader": "0.2.0",
    "json-loader": "^0.5.4",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-remap-coverage": "^0.1.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "1.8.0",
    "parse5": "^2.2.2",
    "protractor": "^4.0.10",
    "raw-loader": "0.5.1",
    "reflect-metadata": "^0.1.9",
    "rimraf": "~2.5.4",
    "script-ext-html-webpack-plugin": "^1.3.2",
    "script-loader": "^0.7.0",
    "source-map-loader": "^0.1.5",
    "string-replace-loader": "1.0.5",
    "style-loader": "^0.13.1",
    "to-string-loader": "^1.1.4",
    "ts-helpers": "1.1.2",
    "ts-node": "^1.7.0",
    "tslint": "~3.15.1",
    "tslint-loader": "^2.1.5",
    "typedoc": "^0.5.0",
    "typescript": "2.1.1",
    "url-loader": "^0.5.7",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-middleware": "^1.6.1",
    "webpack-dev-server": "^2.3.0",
    "webpack-md5-hash": "^0.0.5",
    "webpack-merge": "~1.0.1"
  },
  "repository": {
    "type": "git",
    "url": "https://bitbucket.org/grigson/smartadmin-angular-2"
  },
  "bugs": {
    "url": "https://bitbucket.org/grigson/smartadmin-angular-2/issues"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}

**Comment by SpaceK33z** [comment]
This is a problem with npm itself, not with webpack-dev-server.
