### ISSUE TITLE
webpackOk causes JSON.parse exception in postmessage

### ISSUE THREAD

**Issue by mdurling** [webpack/webpack-dev-server#776]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Webpack Dev Server sends a `webpackOk` message with an `undefined` data property. This causes a `JSON.parse` exception in `postmessage` which results in a console warning that while not service affecting, does somewhat inhibit debugging by cluttering the console log.

**If the current behavior is a bug, please provide the steps to reproduce.**

<img width="1301" alt="screen shot 2017-02-04 at 12 21 14 pm" src="https://cloud.githubusercontent.com/assets/3439869/22620293/8852a9fe-ead6-11e6-9cab-ce0149d0d465.png">

**What is the expected behavior?**
Properly format the `webpackOk` message to avoid the JSON.parse exception and console warning.

**Please mention your webpack and Operating System version.**
Webpack 2.2.1

**Comment by SpaceK33z** [comment]
Okay. Would you mind submitting a PR?

**Comment by mdurling** [comment]
I am going to close this issue and open one against `postmessage` which should not be attempting to parse messages that were sent using `window.postMessage` directly or by any other means other than using `postmessage`. I don't think this is really a Webpack Dev Server issue.

**Comment by amir-beheshty** [comment]
@mdurling I'm having the same issue. Have you figured out a solution or a workaround?

**Comment by andyjessop** [comment]
I'm experiencing this same issue, but it seems to be hijacking my worker script:
```
const worker = new Worker('./worker.js');

worker.postMessage({ a: 'test' });
```
In the woker I have:
```
onmessage = (event) => {
  debugger;
};
```
And I'm seeing `webpackOk` messages, but not my `{ a: 'test' }`

**Comment by amir-beheshty** [comment]
@andreicek I realized my message wasn't propagating all the way up to the parent window. Perhaps you're dealing with similar issue?

**Comment by andreicek** [comment]
Perhaps this was for @andyjessop

**Comment by shubhamseth29** [comment]
Any luck with the same ? I am doing  a similar thing , I am sending a message from my javaascript file to the iFrame embedded in it which is my angular project. So in angular project when I try to read that message I only get 
data: undefined
type: "webpackOk"

**Comment by chaitanyaankam** [comment]
I am experiencing the same issue with angular. can you guys let me know if there is any workaround?

**Comment by johnhargestam** [comment]
@chaitanyaankam My solution to this problem is to inject a script into the page in my webpack-dev-server webpack config.

```js
const iframe = document.getElementById('iframeId');

iframe.contentWindow.postMessage = (ev, origin) => {
  if (matchesMyMessages(ev, origin)) {
    iframe.contentWindow.onmessage(ev, origin);
  }
  console.log(ev, origin); //message is from webpack
};
```
