### ISSUE TITLE
v2.3.0 - devServer.colors option not working

### ISSUE THREAD

**Issue by sagiavinash** [webpack/webpack-dev-server#777]
**package.json devDependencies**
"webpack": "^2.1.0-beta.25",
"webpack-dev-server": "^2.1.0-beta.0",

i checked the `package.json` present in `node_modules/webpack-dev-server` folder it shows `2.3.0` which is the latest release according to npm.

**webpack devServer config**
```
devServer: {
    hot: true,
    progress: true,
    colors: true,
    host: devServerSettings.FLASH_DEV_SERVER_HOST,
    port: devServerSettings.FLASH_DEV_SERVER_PORT,
},

```

**ERROR:**
```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'colors'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }

npm ERR! Linux 3.19.0-68-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! belong@1.0.0 dev: `webpack-dev-server --config /home/avinash/code/flash/webpack.devoffice.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the belong@1.0.0 dev script 'webpack-dev-server --config /home/avinash/code/flash/webpack.devoffice.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the belong package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config /home/avinash/code/flash/webpack.devoffice.config.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls belong
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/avinash/code/flash/npm-debug.log
```

i checked the `node_modules/webpack-dev-server/bin/webpack-dev-server.js` source
it does have the following code
```
"color": {
    type: "boolean",
    alias: "colors",
    default: function supportsColor() {
        return require("supports-color");
    },
    group: DISPLAY_GROUP,
    describe: "Enables/Disables colors on the console"
},
```

while searching for solutions I came across this issue https://github.com/webpack/webpack-dev-server/issues/609 which was a missing `devServer.progress` issue
is similar fix needed for `devServer.colors`?

**Comment by SpaceK33z** [comment]
Thanks for your clear bugreport! Whether your terminal has color support is now calculated automatically, so you could remove that property from your config. If you want to force it, you can pass `--color` (or `--no-color`). Another options is to add `stats: { colors: true }` in `devServer`, but that shouldn't be necessary.

**Comment by sagiavinash** [comment]
@SpaceK33z i had to remove both the `colors` and `progress` from the `devServer` config to make devServer to have no errors.
but after removing them i don't see any colors in the stats section. when i was using webpack@v1 i used to get a typically green, yellow colorful stats.

**Comment by SpaceK33z** [comment]
Okay, I'll look into this soon.

**Comment by SpaceK33z** [comment]
The `progress` option not working via `devServer` is probably because I followed webpack with that, which also doesn't seem to list it anymore. I wanna keep it that way till I figure out why it is that way in webpack.

About the `colors` option, it's really weird that it doesn't correctly detect your terminal supporting colors. What exit code do you get when you run [supports-color-cli](https://www.npmjs.com/package/supports-color-cli)? If that program exits with 0 (color is supported), could it be that you are overriding the `stats` option? If you want to force it you could add `stats: { colors: true }` in your `devServer`.

**Comment by bebraw** [comment]
@sagiavinash Can you respond to Kees' questions so we can proceed with the issue?

**Comment by shellscape** [comment]
Pruning due to age.
