### ISSUE TITLE
Facing issue while running webpack-dev-server

### ISSUE THREAD

**Issue by nkak3065005** [webpack/webpack-dev-server#781]
ERROR in multi C:/Users/Kabya/AppData/Roaming/npm/~/webpack-dev-server/client?http://localhost:8081 ./src/index.js      Module not found: Error: Can't resolve './src/index.js' in 'C:\Users\Kabya\Desktop\React\git_react'                      @ multi C:/Users/Kabya/AppData/Roaming/npm/~/webpack-dev-server/client?http://localhost:8081 ./src/index.js 

--------------------------------Below is webpack.config.js---------------------------

 module.exports = {
	 
	 entry:[
	   
	   './src/index.js'
	 
	 ],
	 output:{
		 
		 'path':__dirname,
		 'filename':'app/js/main.js'
		 
	 },
	 
	 module:{
		 
		 loaders:[
		 
		 {
			 
			 test:/\.jsx?$/,
			 loader:'babel',
			 exclude:/node_modules/ 			 
			 
		 }
		 
		 ]
		 
		 
	 }	 
	 
	 
 }

**Comment by SpaceK33z** [comment]
Please ask this on StackOVerflow.
