### ISSUE TITLE
How to display syntax highlighting from `overlay`?

### ISSUE THREAD

**Issue by kciter** [webpack/webpack-dev-server#783]
**package.json devDependencies**
"webpack": "^2.2.0"
"webpack-dev-server": "^2.3.0"

**Webpack devServer config**
```
devServer = {
  historyApiFallback: true,
  noInfo: true,
  compress: true,
  quiet: true,
  overlay: true
};
```

**Screenshot**
![image](https://cloud.githubusercontent.com/assets/3623695/22721694/a556c31a-edf5-11e6-8ebf-be622f230b25.png)

**What I want:**
![image](https://cloud.githubusercontent.com/assets/3623695/22721735/cc982270-edf5-11e6-9867-ccbdaa085fd2.png)
From #764.

I want to display syntax highlighting from `overlay`. How can I do? :)
I need help.

Regards,

**Comment by SpaceK33z** [comment]
Do you use Babel? The syntax highlighting in that screenshot comes from Babel.

**Comment by kciter** [comment]
Yes, I use Babel.
![image](https://cloud.githubusercontent.com/assets/3623695/22730953/5d819236-ee2c-11e6-8731-ec867f514b09.png)
Can showing highlight from command line. But can't browser.
Is it `ansi-html`'s problem?

**Comment by SpaceK33z** [comment]
Oh, hmm that's interesting. In my testings I noticed that Babel takes care of the syntax highlighting, and if it works in your CLI then I'd expect it also works in the browser. The error you are showing though is from eslint-loader I think? Perhaps eslint-loader causes the ANSI thingies to be removed. It could also be webpack-dev-servers fault though. Could you investigate that a bit further? I don't have time in the near future to look into this.

**Comment by kciter** [comment]
I will investigate it. :)

**Comment by shellscape** [comment]
Pruning due to age.
