### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by pigcan** [webpack/webpack-dev-server#788]
node@6.2.x npm@3.x

moduleA

package.json

```json
{
  "dependencies": {
     "webpack": "1.x"
  }
}
```
moduleB

```json
{
  "dependencies": {
     "b": "0.x"
  }
}
```

b - package.json

```json
{
  "dependencies": {
     "webpack": "2.2.x",
     "webpack-dev-server": "2.3.x"
  }
}
```

Due to npm3 the installed packages would be flattened, it may looks like

```
.
├── node_modules
│   ├── webpack -> 1.x
│   └── webpack-dev-server -> 2.3.x
│   └── b -> 0.x
│       └── webpack -> 2.2.x
└── utils
```

`Webpack-dev-server` treats webpack as peerDependencies, so such  directory structure  would result in `webpack-dev-server` could not resolve the correct webpack version. 

```
const validationErrors = webpack.validateSchema(optionsSchema, options);
	                                 ^

TypeError: webpack.validateSchema is not a function
```

**Comment by SpaceK33z** [comment]
What do you suggest as a solution? Note that adding `webpack` as a dependency instead of peerDependency is not something we'd want to do.

**Comment by bebraw** [comment]
Why does `moduleA` depend directly on webpack? If it's public, can you link to it.

**Comment by pigcan** [comment]
@bebraw e.g.  [atool-build](https://github.com/ant-tool/atool-build/blob/master/package.json)  [roadhog](https://github.com/sorrycc/roadhog/blob/master/package.json), these packages are building tools which based on  webpack@1

**Comment by bebraw** [comment]
@pigcan Ok. It's a little tricky problem. One way to solve it would be to push scheme validation to a package of its own, but it's likely that's not going to happen (syncing issues).

**Comment by SpaceK33z** [comment]
@bebraw, also that wouldn't really solve this problem. It would work for this specific error, but since webpack-dev-server relies on webpack v2 being present, it can also use other webpack v2-only functions that can throw an error.

**Comment by bebraw** [comment]
@SpaceK33z Yeah. I don't understand why (s)he is using webpack 1 specific tools with webpack 2. There's something obvious I'm missing.

**Comment by bebraw** [comment]
@pigcan Any thoughts on this? Can you explain why you are using webpack 1 tools with webpack 2 setup? I don't think there's any particularly easy solution at WDS for this particular problem.

**Comment by pigcan** [comment]
We developed a electron app  likes [deco-ide](https://github.com/decosoftware/deco-ide)  and due to the development  needs we should support webpack@1 and webpack@2, at the same time we hope that developers can start debugging server as soon as possible,to build-in modules is the easy way, so the problem came.

**Comment by SpaceK33z** [comment]
Okay, understandable. But I don't think we can fix anything in dev-server, this would need to be fixed by letting Node.js resolve the module to webpack v2. No idea how that would work exactly though.
