### ISSUE TITLE
Show warnings in client overlay

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack-dev-server#789]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

Compiler warnings will not be shown in the overlay and there is no option to turn that on.

**What is the expected behavior?**

Compiler warnings should be shown in the overlay, but not by default. As discussed with @bebraw, it could look like this:

```js
overlay: {
  errors: true,
  warnings: true
}
```

`overlay: true` would be the same as `overlay: { errors: true, warnings: false }`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Some people like to fix the warnings first before seeing the result, now you need to look into the DevTools or the terminal to see those warnings. Also, CRA shows them too.

**Comment by bebraw** [comment]
FYI, there's a PR at #790 for this now.

**Comment by SpaceK33z** [comment]
@bebraw thanks for that :). I'll take a look soon.
