### ISSUE TITLE
How to force reloading after build?

### ISSUE THREAD

**Issue by mnn** [webpack/webpack-dev-server#794]
After updating all packages the WDS no longer reloads after compilation. Is just prints to console `Errors while compiling. Reload prevented.`. How to disable this "feature" and force it to reload every time? (Compilation does contain errors, because of broken [webpack](https://github.com/webpack/webpack/issues/3274) and/or [Awesome TypeScript loader](https://github.com/s-panferov/awesome-typescript-loader/issues/262). There is nothing I can do with that other than wait if someone after months finally take a look at it.)

**Comment by Arturszott** [comment]
Similar issue: https://github.com/MoOx/eslint-loader/issues/23

**Comment by mnn** [comment]
My "solution" is to down-grade before breaking change - to version `2.1.0-beta.9`. It would be nice to have an option in WDS to disable this feature (misfeature for some).

**Comment by mribichich** [comment]
any news on this? is there a way to make webpack reload even though there are errors. I'm using typescript ts-loader and the errors should not stop the reloading

**Comment by mnn** [comment]
Both [webpack](https://github.com/webpack/webpack/issues/3274) and [Awesome TypeScript loader](https://github.com/s-panferov/awesome-typescript-loader/issues/262) are ignoring the issue. I see here is the same situation.

No love for TypeScript :-/. :-1:

**Comment by shellscape** [comment]
Closing due to issue age and inactivity. If anyone would like to put together and submit a pull request for this, we'd be happy to take a look at it.

**Comment by mnn** [comment]
Really? It is still an issue, we are not updating this package because of this "feature"... :disappointed:

**Comment by shellscape** [comment]
@mnn we're trying to get the issues queue under control so that we can effectively and efficiently address incoming issues. please remember that folks volunteer their time for the project. some pruning had to happen (and still needs to happen). closing this wasn't unreasonable, and if it gains traction we'd certainly reopen it. but the best course would be to open a PR for the feature.

**Comment by alexander-akait** [comment]
We already can do it, there is an api - `invalidate`
