### ISSUE TITLE
Automatic index.html?

### ISSUE THREAD

**Issue by mightyiam** [webpack/webpack-dev-server#799]
Do I remember that in webpack 1.x the dev-server used to automatically generate an `index.html` on the response to `/` and `/index.html`?

Why was this removed? Not a good idea? I liked it.

**Comment by SpaceK33z** [comment]
This was not removed, but it only works when your bundle filename is "index", since it uses the filename minus `.js`. It could also be you're talking about iframe mode, you can enable that with `--no-inline`.

**Comment by mightyiam** [comment]
Cool. I did not see any mention of this in the docs, though.
