### ISSUE TITLE
--host argument in CLI

### ISSUE THREAD

**Issue by meowgorithm** [webpack/webpack-dev-server#80]
It would be very useful to be able to bind the server to something other than `localhost` (`0.0.0.0`, for example) to allow other devices on the network to reach the dev server.

A common use case would be for testing on mobile devices.

**Comment by wrobel** [comment]
Eh... I don't think my commit was ready for pulling :) Without actually transporting the hostname to the express server in the listen() call it will probably not bind to another host name.

This is probably required in line 114:

`new Server(webpack(wpOpt), options).listen(argv.port, argv.host, function(err) {...`

I'm sorry for leaving this unfinished. It was just a short attempt but I soon realized that I need a different approach to get the webpack-dev-server up and running.
