### ISSUE TITLE
Document automatic index.html

### ISSUE THREAD

**Issue by mightyiam** [webpack/webpack-dev-server#800]
Following #799, I didn't find any documentation of the automatic generation of basic HTML that includes a `script` tag for the bundle.

**Comment by mightyiam** [comment]
https://webpack.js.org/guides/development/#webpack-dev-server instructs to create an html file.

**Comment by SpaceK33z** [comment]
Please file this issue at https://github.com/webpack/webpack.js.org, the documentation lives there. A PR would be very welcome.
