### ISSUE TITLE
Can webpack-dev-server set Host header when proxy to backend?  

### ISSUE THREAD

**Issue by linvar** [webpack/webpack-dev-server#803]
proxy config:
`
proxy: {
   "/api/":  {
        "target": "http://www.b.com/"
   }
}
`

from www.b.com server access log,  the $host is localhost(develop enviroment)
but www.b.com server expected that the $host should be www.b.com.

Can webpack-dev-server set Host header when proxy to backend?  
thanks

**Comment by SpaceK33z** [comment]
See the options in https://github.com/chimurai/http-proxy-middleware. Closing since this is a question.

**Comment by napindc** [comment]
@ActionScripted Do you know why the below doesn't have my headers show up in my browser (when I try to inspect one of my POST requests)? I know the proxy is somewhat working, because when I change the “target” below, I get a bunch of errors.

```
module.exports = webpackMerge(commonConfig({env: ENV}), {
    devtool: 'eval-source-map',
    devServer: {
        contentBase: './target/www',
        proxy: [{
            context: [
                '/api',
                '/auth'
            ],
            target: 'http://localhost:8081',
            secure: false,
            headers: {
                "X-SSO-Roles": "ROLE_USER"
           }
        }],
```

**Comment by svogal** [comment]
For me it worked with Host header, like this:
```
target: 'http://some-host.test:1234',
headers: {
  'Host': 'some-host.test'
}    
```

**Comment by viknes-interana** [comment]
Not sure in which version it was introduced but dev-server version 3.2 and above:
```
target: 'http://some-host.test:1234',
changeOrigin: true,
```

**Comment by Chris3y** [comment]
@ActionScripted. Webpack5 docs say the headers prop is for setting headers on all "_responses_" which has left me confused.

https://webpack.js.org/configuration/dev-server/#devserverheaders

**Comment by kumarsaroj18** [comment]
> Since this is the top result for "webpack dev server proxy headers", here's the solution:
> 
> ```js
> module.exports = {
>   // ... other webpack settings
>   devServer: {
>     proxy: {
>       '**': {
>         target: 'http://some-host.test:1234',
>         headers: {
>           'X-Forwarded-For': '1.2.3.4'
>         }
>       }
>     }
>   }
> };
> ```
> 
> Here we're proxying everything to some-host.text on port 1234 and sending along the `X-Forwarded-For` header with `1.2.3.4`.
> 
> You have to set headers for each proxy object, so if you have several proxy objects to deal with you might create a headers constant and use that with each proxy object:
> 
> ```js
> const proxy_headers = {
>   'X-Forwarded-For': '1.2.3.4',
>   'X-Another-Header': 'Hello'
> };
> 
> module.exports = {
>   // ... other webpack settings
>   devServer: {
>     proxy: {
>       'api1/': {
>         target: 'http://some-host1.test:1234',
>         headers: proxy_headers
>       },
>       'api2/': {
>         target: 'http://some-host2.test:5678',
>         headers: proxy_headers
>       }
>     }
>   }
> };
> ```

In my case, the header values are not getting reflected in the request header of the request.
