### ISSUE TITLE
Dev server stopped working. No errors

### ISSUE THREAD

**Issue by aequasi** [webpack/webpack-dev-server#805]
Not sure what i did to get it to break, but now, when i start my dev server (code below), it never actually starts the server (assets never compile, and are never served). Hoping someone can point me in the right direction.

```
const WebpackDevServer = require('webpack-dev-server'),
      webpack          = require('webpack'),
      config           = require('./webpack.config.development'),
      port             = process.env.PORT || 5000,
      compiler         = webpack(config);

config.output.publicPath = `http://localhost:${port}${config.output.publicPath}`;
const devServerConfig    = {
    contentBase:        config.output.publicPath,
    watchOptions:       {
        aggregateTimeout: 300,
        poll:             1000
    },
    quiet:              false,
    noInfo:             false,
    historyApiFallback: true,
    filename:           'bundle.js',
    publicPath:         config.output.publicPath,
    outputPath:         config.output.path,
    stats:              {colors: true}
};

const server = new WebpackDevServer(compiler, devServerConfig);

server.listen(port, 'localhost', () => {
    console.log(`Now serving assets from http://localhost:${port}/`);
});

process.on('uncaughtException', console.error);

process.on('SIGTERM', () => {
    console.log('Stopping dev server');
    server.close(() => {
        process.exit(0);
    });
});

```

Just sits at this forever:

```
$ yarn start
yarn start v0.20.3
$ NODE_ENV=development node --harmony server.js
Now serving assets from http://localhost:5000/
```

**Comment by aequasi** [comment]
Huh, looks like its actually my development webpack build that just hangs.

**Comment by aequasi** [comment]
Yup, nevermind.

**Comment by abobwhite** [comment]
@aequasi What was your issue? I just switched to webpack v2 and I can get the app to run with webpack-dev-server but after I change a file, my console reads `webpack: Compiling...` and in the browser console, it's `[WDS] App updated. Recompiling...` and it just hangs. Nothing ever gets reloaded and nothing happens after those lines. I've been fighting this for days.

**Comment by aequasi** [comment]
iirc, es-lint was causing issues. I just removed it.

**Comment by abobwhite** [comment]
Thanks - I just figured out the the open-browser-plugin v0.0.4 was causing my issue. Totally unrelated. Cheers!
