### ISSUE TITLE
babel-loader doesn't work for webpack-dev-server

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack-dev-server#806]
when I run webpack-dev-server,babel-loader totally doesn't work.
I've post a quetion on stackover but no one can help me.

https://stackoverflow.com/questions/42396438/babel-loader-doesnt-work-for-webpack-dev-server

**Comment by SpaceK33z** [comment]
It's been only 18 hours since your stackoverflow question. I know for sure this isn't a bug in dev-server since it doesn't have anything to do with Babel + I use babel-loader all the time in my projects.
