### ISSUE TITLE
problems occurred when no local webpack-dev-server is installed

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack-dev-server#809]
https://github.com/webpack/webpack-dev-server/issues/806
https://github.com/webpack/webpack-dev-server/issues/729

I have reported 2 problems,they are both caused by that no local webpack-dev-server is installed.
In this situation,it should give the users a warn or an error in the console.

**Comment by SpaceK33z** [comment]
webpack-dev-server doesn't do _anything_ with loaders, it passes everything to webpack itself. So I can't fix that in here. Also note that I would recommend against installing webpack locally but installing webpack-dev-server globally. That's just asking for trouble.

**Comment by jcrben** [comment]
I recommend closing this.
