### ISSUE TITLE
unable to rewrite root

### ISSUE THREAD

**Issue by Pyrolistical** [webpack/webpack-dev-server#810]
**Do you want to request a *feature* or report a *bug*?**
bug, following instructions here https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback

**What is the current behavior?**
`/` is rewritten to index.html

**If the current behavior is a bug, please provide the steps to reproduce.**
```
devServer: {
    historyApiFallback: {
      rewrites: [
         {
           from: /^\/$/,
           to: '/homepage.html'
         },
         {
           from: /./,
           to: '/index.html'
         },
     ]
   }
```

**What is the expected behavior?**
`/` is rewritten to homepage.html

**Please mention your webpack and Operating System version.**
"webpack": "2.2.1"
"webpack-dev-server": "2.4.1"
mac os x 10.12.1

I think what is going on is devServer.historyApiFallback is truthy and some other middleware is rewriting root and this line gets printed: `404s will fallback to /index.html`

No known workaround

**Comment by Pyrolistical** [comment]
Found the line: https://github.com/webpack/webpack-dev-server/blob/b85a0ceb946589d345c2b41e4d1efb8a5c945f9c/bin/webpack-dev-server.js#L410

That message is incorrect when there are rewrites

**Comment by Pyrolistical** [comment]
OK, found our my issue.

It was because the file index.html was taking precedence over the rewrite rules.

I renamed index.html to main.html and it works.  Might need to add some documentation around this

**Comment by constructivetim** [comment]
> OK, found our my issue.
> 
> It was because the file index.html was taking precedence over the rewrite rules.
> 
> I renamed index.html to main.html and it works. Might need to add some documentation around this

thanks for posting this.  just helped me solve my problem.
