### ISSUE TITLE
webpack-dev-server and valet, not serving files from memory

### ISSUE THREAD

**Issue by hendrikeng** [webpack/webpack-dev-server#811]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

webpack-dev-server won't serve the compiled bundles

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/hendrikeng/44ffcbdc3d00d127a2043e9a966a98d2

**What is the expected behavior?**
dev server loads the valet url, but won't serve the css and js modules, if i run `wepack build -p` before and then `wepack-dev-server --open` it will obviously serve the files as they are written into the folders. 

```
   "scripts": {
        "dev": "webpack-dev-server --hot --inline --open",
        "prod": "webpack -p"
    }
```
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
Osx , webpack@2.2.1 , webpack-dev-server@2.4.1

**Comment by hendrikeng** [comment]
got it working. i had to add ' publicPath: ```http://localhost:8080/assets/' ```

```
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const path = require('path');

module.exports = {
  entry: ['./src/js/index.js'],
  output: {
    filename: 'app.bundle.js',
    path: path.resolve(__dirname, 'src/assets'),
    publicPath: '/assets/',
  },
  devtool: 'source-map',
  module: {
    rules: [{
      test: /\.scss$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'sass-loader'],
        publicPath: '/assets/',
      }),
    }],
  },
  devServer: {
    contentBase: path.resolve(__dirname, 'src'),
    compress: false,
    publicPath: 'http://localhost:8080/assets/',
    // port: 8080,
    watchContentBase: true,
    public: 'app.dev',
    proxy: {
      '/api': {
        target: 'http://app.dev',
        secure: false,
      },
    },
  },
  plugins: [
    new ExtractTextPlugin({
      filename: 'app.css',
      disable: false,
      allChunks: true,
    }),
  ],
};

```

**Comment by hendrikeng** [comment]
...forgot to delete the assets from an older production build, beside the config above webpack is serving via the proxy , but somehow it wont link to the piped development assets , i looked up 
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md#usage-in-laravel aswell and adjusted the publicPath 

```
yarn run v0.19.1
$ webpack-dev-server --open
Project is running at http://app.dev/
webpack output is served from http://localhost:8080/assets/
Content not from webpack is served from /Users/hendrik/Documents/Github/Projects/Hajok/src
```

**Comment by SpaceK33z** [comment]
Please ask this on StackOverflow, this is not a bug in WDS.
