### ISSUE TITLE
Cannot require local node_modules in Electron

### ISSUE THREAD

**Issue by deiucanta** [webpack/webpack-dev-server#812]
In an Electron app, when loading `webpack-dev-server`'s URL, I'm unable to require local dependencies. When I `console.log(global.module.paths)` I get an empty array. However, here should be several path strings.

When I build the code into `bundle.js`, the app works well. The paths array has the proper values.

Therefore, I assume it's an issue with `webpack-dev-server`.

---

After manually investigating the JS output of the dev server, I found a snippet that looks like [this](https://github.com/webpack/webpack/blob/fc1a43b7cbe0847da65c4e81e017e7518e8f5ab2/buildin/module.js). There you can see at line 4 that the `paths` array emptied.

The strange thing is that the output of the normal build also contains the same snippet. I'm afraid that the dev server applies that code even at the "root module" and thus removing the necessary paths.

**Comment by SpaceK33z** [comment]
Note that webpack-dev-server does _nothing_ in regards to compiling your code. It passes everything through to webpack itself, the only two changes being that it enables watch mode and uses an in-memory filesystem instead of the real filesystem.

We'll need to pinpoint the issue a bit more. If you use `webpack --watch`, do you also get this behavior? And are your dev and production configs exactly the same? Often people have a different dev config than prod and that can cause issues. After you've checked these things, can you make a repo reproducing the issue?

Note that I'm going on vacation tomorrow for one week.

**Comment by deiucanta** [comment]
@SpaceK33z thanks for the response!

I have created a repo to showcase this issue better (https://github.com/deiucanta/webpack-electron-issue). Please take a look and let me know if you can pinpoint the cause for this.

**Comment by SpaceK33z** [comment]
I debugged your repo a little. Why are you using `webpack.ExternalsPlugin` for lodash? If I remove that plugin, it works. See also https://github.com/webpack/webpack/issues/2069 for a bit more info on Electron + webpack.ExternalsPlugin

**Comment by deiucanta** [comment]
Lodash is just a simplified example. In Electron you can import native modules on demand. I don't want to bundle all NodeJS modules. Some of the modules can't be bundled easily because they have dynamic requires.

The big question is why the `bundle.js` works and why the `webpack-dev-server` doesn't? Both of them using `webpack.ExternalsPlugin`.

**Comment by SpaceK33z** [comment]
I don't know specifically why lodash doesn't work when using it with webpack-dev-server in this case. But when using the `electron` module like this:

```js
var electron = require('electron');

console.log('electron', electron);
```

and with

```js
new webpack.ExternalsPlugin('commonjs', [
  'electron',
])
```

It does work. What module are you trying to load that doesn't work?

**Comment by deiucanta** [comment]
Last time I checked I couldn't load any module that I installed through npm.

**Comment by shellscape** [comment]
Closing this one due to age and inactivity. But please do continue the discussion and call me out if there is good reason to reopen.
