### ISSUE TITLE
HMR creates incorrect code with --hot command line option

### ISSUE THREAD

**Issue by e110c0** [webpack/webpack-dev-server#817]
"webpack": "^2.2.1",
    "webpack-dev-server": "^2.2.0",

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

when using --hot command line, HMR createst incorrect code:

```
module.hot.accept("../node_modules/css-loader/index.js!../node_modules/sass-loader/lib/loader.js!./app.scss""../node_modules/css-loader/index.js!../node_modules/sass-loader/lib/loader.js!./app.scss", function() {
  var newContent = __webpack_require__("../node_modules/css-loader/index.js!../node_modules/sass-loader/lib/loader.js!./app.scss");
  if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];
  update(newContent);
});
```

the error:
```
SyntaxError: Unexpected string literal "../node_modules/css-loader/index.js!../node_modules/sass-loader/lib/loader.js!./app.scss". Expected ')' to end an argument list.
```

as you can see, the string is included twice: "<string>""<string>"

(see also https://github.com/webpack/webpack/issues/4040)
**If the current behavior is a bug, please provide the steps to reproduce.**

- use official config example, start dev-server with option --hot

it doesnt matter whether the webpack.config.js has devServer.hot: true or not. 

**What is the expected behavior?**

the --hot command line option should produce correct code

**Please mention your webpack and Operating System version.**

    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.2.0",
    "css-loader": "^0.26.2",
    "sass-loader": "^6.0.2",
    "style-loader": "^0.13.2",

macOS 10.12.3

**Comment by alfonsomunozpomer** [comment]
I’m seeing something similar. If I use the `--hot` option I get the following:
```
[HMR] Waiting for update signal from WDS...             vendor.bundle.js:111552:2
SyntaxError: missing ) after argument list              [Learn More]  experimentPicker.bundle.js:21827:169
TypeError: experimentPicker.render is not a function    [Learn More]  html:106:5
[WDS] Hot Module Replacement enabled.
```

When using only `hot: true` in `webpack.config.js`, on the other hand, I have no errors and the browser reloads on recompile.
```
"webpack": "^2.3.3",
"webpack-dev-server": "^2.4.2",
"babel-core": "^6.24.0",
"babel-loader": "^6.4.1"
```

**Comment by alfonsomunozpomer** [comment]
After a lot of tweaking I managed to get it to work following https://github.com/wkwiatek/react-hot-loader-minimal-boilerplate instead of Webpack’s official guide, which in my opinion is quite confusing and adds some unneeded complications along the way. I’m not entirely sure of my `webpack.config.js` when I added my comment, but if you’re interested you can have a look at [our setup](https://github.com/gxa/atlas-heatmap/commit/0a837ceffe874596f3caf27e15dcf39bd2cd6a81).

**Comment by alfonsomunozpomer** [comment]
I pinned down my error to a bad configuration of `babel-loader`. I needed to add, besides the `react` preset, another preset to transform ES6 to browser-compatible JS (`env` did it for me).
