### ISSUE TITLE
node api compile callback

### ISSUE THREAD

**Issue by crobinson42** [webpack/webpack-dev-server#818]
Is there a callback that gets invoked after compile/recompile when using the node api?

Example:
```js
const WebpackDevServer = require('webpack-dev-server')

const server = new WebpackDevServer(
  compiler, 
  {/* webpack devServer options */}, 
  function compilerRunCallback(err, stats) { 
    /* invoked after compile/recompile */ 
  }
);

server.listen(3000, "127.0.0.1", function() {
	console.log("Starting server on http://localhost:3000");
});
```

**Comment by bebraw** [comment]
Nope.

**Comment by williamboman** [comment]
This would be really awesome to have in order to re-run e2e tests in watch mode when I change source files.

**Comment by shellscape** [comment]
We're going to slate this feature for version 3. We'll be making `Server` extend `EventEmitter` that'll allow us to publish a host of events for consumers to use. We'll include the compile event in the slate of first-round events.

**Comment by normancarcamo** [comment]
Just asking: Is this setting available now?

**Comment by shellscape** [comment]
Closing issue as we're adding the afore mentioned `EventEmitter` in version 3 of the module. Given the complexities of doing in this in the 2.x branch, it's not likely to be given priority or acceptance at this time.
