### ISSUE TITLE
Update README reference to v7 issues

### ISSUE THREAD

**Issue by tomkel** [webpack/webpack-dev-server#820]
The issue that the README refers to: 
>Note: There are known issues with Node.js v7 and webpack / webpack-dev-server. Please use Node.js v6 for the moment.

was tracked by nodejs/node#9542, and appears to have been fixed in v7.2. 
Maybe this warning should be removed or edited to specify node < v7.2.

**Comment by swrobel** [comment]
+1, this warning is very scary-sounding and Node 7 has come a long way since it was added. Hopefully it's fixed by now, and if so, this warning should be removed...

**Comment by SpaceK33z** [comment]
Thanks for the heads-up. The issues should indeed be fixed now, so I removed the warning.
