### ISSUE TITLE
webpack devserver fails to start if modules dir is absolute

### ISSUE THREAD

**Issue by cy6erGn0m** [webpack/webpack-dev-server#822]
Let's assume we have cwd `/absolute/path/to/dir`, there is node_modules and webpack.config.js on the right place.

```
    "resolve": {
        "modules": [
            "node_modules" // this works well
            //"/absolute/path/to/dir/node_modules"   // this doens't 
        ]
    }
```

plain webpack works well with both but webpack-dev-server fails with error 

webpack-dev-server 2.4.1
webpack 2.2.1

**Comment by SpaceK33z** [comment]
If you add both, it will work. So `modules: ['node_modules', '/absolute/node_modules']`. webpack-dev-server needs the first item to be present because it compiles some modules in your bundle.
