### ISSUE TITLE
Invalid configuration object when specifying output.filename

### ISSUE THREAD

**Issue by matejkramny** [webpack/webpack-dev-server#826]
```
➜  frontend git:(master) ✗ webpack-dev-server -v
webpack-dev-server 2.4.1
webpack 2.2.1
```

[webpack.js](https://gist.github.com/matejkramny/c47e2e17511817b97bad0269365f67d3)

```
output: { filename: 'main.js' }
```

causes the following error

```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'error'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
```

If i don't set the output filename, it outputs `bundle.js`.. Running `webpack` works fine, `webpack-dev-server` does not.

What is the issue?

**Comment by SpaceK33z** [comment]
I can't reproduce your issue. After copying the files and installing the deps, I get the error `Error: `output.path` needs to be an absolute path or `/`.`, and after fixing that it does work. Please ask this on StackOverflow if you're still having an issue, since this is a configuration issue.
