### ISSUE TITLE
bypass is handling all requests regardless proxy options

### ISSUE THREAD

**Issue by koba04** [webpack/webpack-dev-server#829]
`webpack-dev-server` is very helpful in my development. Thanks!

Currently, There is `bypass` in a `proxy` option. But `bypass` is applied all requests regardless of its a pass.

For instance, a server with the following `webpack.config.js` always returns `api.json` as a response (It depends on order of `Object.keys`).

```js
const path = require('path');
const webpack = require('webpack');

module.exports = env => ({
  entry: './app.js',
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'public'),
  },
  devServer: {
    contentBase: path.join(__dirname, ''),
    proxy: {
      '/foo.html': {
        bypass() {
          return 'foo.txt';
        },
      },
      '/api/': {
        bypass() {
          return 'api.json';
        },
      },
   },
  },
});
```

I think the behavior is a little confusing.

### `bypass` is applied when a proxy has matched

To do that, we need to take a matching logic from `http-proxy-middleware`.

* https://github.com/chimurai/http-proxy-middleware/blob/master/lib/context-matcher.js

But I think it's the best way to solve this problem.

### Move `bypass` option to outside `proxy` options

moving `bypass` options to outside `proxy` as `proxyBypass` is a clear way to tell developers `proxyBypass` is applied all requests regardless of proxy options.
But it seems to need to change `webpack.config.js`, which is painful for users.

### Add a validation for multiple `bypass` options

This doesn't change the current behaviors. Users can notice it might not work well when they put multiple `bypass` options in proxy options

What do you think about this? I'd like to work on this.

Thanks.

**Comment by SpaceK33z** [comment]
Your first proposal does make sense, but I'd prefer to not copy such a file in our repo. Of course we could also directly require that file, but that can be tricky.

Another way could perhaps be to make an issue/PR to [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware), to add such an option in there. Not sure if that makes sense, but could be interesting to see how he thinks about it.

**Comment by shellscape** [comment]
Going to assert the suggestion to make this feature request with `http-proxy-middleware` so we can consume an option rather than implement it standalone in webpack-dev-server. We can revisit this issue should there need to be any work on this end.

**Comment by Halfist** [comment]
@shellscape, is this fixed or should I use `pathRewrite: (path, request) => '/path/to/mock.json'` instead for multiple paths?
