### ISSUE TITLE
Cannot set property 'hot' of undefined

### ISSUE THREAD

**Issue by zackify** [webpack/webpack-dev-server#833]
**What is the current behavior?**

Getting:

```
TypeError: Cannot set property 'hot' of undefined
    at Server (/Users/zach/Projects/hyper-react/node_modules/webpack-dev-server/lib/Server.js:34:11)
    at _default (/Users/zach/Projects/hyper-react/dist/server.js:18:49)
```

When doing:

```js
import Webpack from 'webpack-dev-server';
import WebpackDevServer from 'webpack-dev-server';
import config from './webpack.config';

export default () => {
  var server = new WebpackDevServer(Webpack(config), {
    hot: true,
    host: '0.0.0.0',
    contentBase: resolve(__dirname),
    publicPath: '/',
    historyApiFallback: {
      index: 'index.html',
    },
  });
  
  server.listen(8888, 'localhost', function() {});
};

```

Seems others are getting this too: https://github.com/webpack/webpack/issues/2387

**What is the expected behavior?**

For the dev server to work.

**Please mention your webpack and Operating System version.**

webpack-dev-server 2.4.1, Mac OS Sierra

**Comment by SpaceK33z** [comment]
```
import Webpack from 'webpack-dev-server';
import WebpackDevServer from 'webpack-dev-server';
```

The first one should be `'webpack'`

**Comment by zackify** [comment]
Haha. This is what I get for coding too long. Thanks. This is embarrassing!

**Comment by nsuedu** [comment]
excuse me,i have same problem， can you tell me the solution?

**Comment by nsuedu** [comment]
@zackify

**Comment by nsuedu** [comment]
@SpaceK33z

**Comment by khurram-wasim** [comment]
const express = require('express');
const webpackDevServer = require('webpack-dev-server');
const webpack = require('webpack');
const webpackConfig = require('./webpack.config.js');
const app = express();

const compiler = webpack(webpackConfig);

app.use(express.static(__dirname + '/www'));

app.use(webpackDevServer(compiler, {
  hot: true,
  filename: 'bundle.js',
  publicPath: '/assets/',
  stats: {
    colors: true,
  },
  historyApiFallback: true,
}));

I am getting this error Cannot set property 'hot' of undefined , any help to get rid of it ?

**Comment by ebardajiz** [comment]
I'm still getting this error :(. I'm using the Node API

package.json:

```json
    "webpack": "3.5.5",
    "webpack-dev-server": "2.7.1"
```

usage:

```js
const Webpack = require('webpack')
const WebpackDevServer = require('webpack-dev-server')
const config = require('./webpack.dev.config.js')

const compiler = Webpack(config)

const server = WebpackDevServer(compiler)

server.listen(9000, 'localhost', () => {
  console.log('Bundle available at localhost:9000')
})

**Comment by shellscape** [comment]
@ebardajiz probably 😄  but in all seriousness, try applying your config to a known-working use of the API by forking this repo and copying your config over to https://github.com/webpack/webpack-dev-server/tree/master/examples/node-api-simple. If it works, then it's something else in your project. If it doesn't work, then it's a webpack config issue.

**Comment by ebardajiz** [comment]
Thanks for pointing out the example, made me realize how to properly use it!

```diff
- const server = WebpackDevServer(compiler)
+ const server = new WebpackDevServer(compiler)
```
