### ISSUE TITLE
webpack-dev-server support for POST, PUT, Delete Methods using proxy

### ISSUE THREAD

**Issue by raviroshan** [webpack/webpack-dev-server#839]
**What is the current behavior?**
Not able to override HTTP methods.

**What is the expected behavior?**
Functionality to override HTTP methods.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Flexibility to override the HTTP methods as the API may not support the user requested methods.

**Please mention your webpack and Operating System version.**
webpack - v2
os - windows 10

-------------------------------------------------------------------
I am using webpack-dev-server as a proxy to my original API URL to avoid CORS related issues and dynamically pointing to Dev, UAT, Mock server URL based on the environments.

For Mock dev - I prefer to use the JSON from the local file system and it servers its purpose for all the GET request.

How to to add support for 'POST, PUT, DELETE' so that the local JSON can be served directly?

One possible approach may be - Overriding the HTTP Request methods to GET as I am not passing any payload. But I can't find any configuration for that.

http://stackoverflow.com/questions/42735457/webpack-dev-server-support-for-post-put-delete-methods-using-proxy

**Comment by SpaceK33z** [comment]
> How to to add support for 'POST, PUT, DELETE' so that the local JSON can be served directly?

Do you mean instead of using a mock server that can handle these requests?

**Comment by raviroshan** [comment]
@SpaceK33z : The requirement is to override the HTTP methods. before making a request to actual API using webpack-dev-server proxy.

As we already have the option `target` to dynamically point to different Up-Stream server, do we have any option to override the `http methods` also.

Server 1 may support all the Methods, but 
Server 2 supports only GET.

**Comment by SpaceK33z** [comment]
Why can't you add the methods to "Server 2" then? It's not webpack-dev-server's job to fix that. We use [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) for proxying, perhaps that package provides a way to fix this. If not, you could maybe fill a feature request there.

**Comment by raviroshan** [comment]
@SpaceK33z : I don't have access to Server - 2 write.
It was in line with the `target` option in the proxy object.

You can close this ticket, it would be appropriate to  open a feature request @ http-proxy-middleware.

Thanks :)
