### ISSUE TITLE
how to serve the current directory

### ISSUE THREAD

**Issue by bochen2014** [webpack/webpack-dev-server#840]
Hi there,
with `webpack-dev-server 1.x` I can host my current directory with no problem --- note, I sometime copied the compiled htmls and `bundle.js` directly from build server to do verification, so I don't need to compile them again.  I ran `webpack-dev-server` within the directory and since there is not `webpack.config.js` file in the directly, `wds` just server the file content without compiling, which is what I want.

After upgrading to `webpack-dev-server 2.x`, I got error complaining must provide an entry and output. I have to create a dummy blank `index.js` file and a dummy `webpack.config.js` file with `entry` set to it. I find it clumsy

can we have this nice feature back?
thanks

**Comment by shellscape** [comment]
Pruning due to age and inactivity.

**Comment by bochen2014** [comment]
@SpaceK33z   its not a question. Its a feature request
