### ISSUE TITLE
source maps should use `node_modules` rather than `~`

### ISSUE THREAD

**Issue by nojvek** [webpack/webpack-dev-server#846]
**What is the current behavior?**

sourcemap sources have wave character `~` which corresponds to node_modules

```
webpack:///./~/querystring/index.js
```

should actually be

```
webpack:///./node_modules/querystring/index.js
```

This breaks a whole bunch of tools such as chrome devtools and VSCode.

**Comment by SpaceK33z** [comment]
Please file this issue in the webpack/webpack repo, webpack-dev-server doesn't generate these this.

**Comment by nojvek** [comment]
https://github.com/webpack/webpack/issues/4497
