### ISSUE TITLE
WebSocket continues disconnecting on Chrome but not on FireFox if there is no update

### ISSUE THREAD

**Issue by ryancui-** [webpack/webpack-dev-server#848]
Hi, I'm using webpack and webpack-dev-server to build my front-end project. Everything is ok except the websocket on Chrome. It disconnects when I have no new update on my files. While on Firefox, the same configuration and code, the websocket can have a ping-pong heartbeat to keep it alive.

When I first see this problem, I think maybe I open several tabs (includding pads or phones browser) so the socket has some problem. Then I test it only in one tab, here's the result.
 
### Configuration and code
webpack.config.js
```
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './src/main.js',
  output: {
    path: '/dest',
    filename: 'bundle.js',
    publicPath: '/dest/'
  },
  module: {
    loaders: [{
      test: /\.vue$/,
      loader: 'vue-loader'
    }, {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.css$/,
      use: ExtractTextPlugin.extract({
        use: 'css-loader'
      })
    }]
  },
  plugins: [
    new ExtractTextPlugin('styles.css')
  ]
}
```

webpack-dev-server command
`webpack-dev-server --inline --hot --port 9090 --host 127.0.0.1`

### Chrome
log from console
![image](https://cloud.githubusercontent.com/assets/3788103/23948243/2592ee7c-09bd-11e7-8f91-39d1facf797e.png)

If I do nothing to the source, the websocket will disconnect automatically.
![image](https://cloud.githubusercontent.com/assets/3788103/23948280/4d51c640-09bd-11e7-8849-dd73051f1817.png)

### FireFox
There is heartbeat, so websocket keeps connecting.
![image](https://cloud.githubusercontent.com/assets/3788103/23948650/ea42d9de-09be-11e7-873b-45ab08213c49.png)

### Version info
- webpack: 2.2.1
- webpack-dev-server: 2.4.1
- Chrome: 57.0.2987.98
- Firefox: 46.0.1
- Platform: Windows 10

Do I make mistakes on some configurations? Or other reasons? Thanks.

**Comment by SpaceK33z** [comment]
Please upgrade to the [latest version](https://github.com/webpack/webpack-dev-server/releases/tag/v2.4.2), this should fix your issue.

**Comment by ryancui-** [comment]
I upgraded to v2.4.2, but the problem still exists.

**Comment by steve-king** [comment]
Upgrading fixed it for me...thanks!

**Comment by ryancui-** [comment]
Today I found the problem disappear...without any upgrade of webpack or webpack-dev-server but a Chrome upgrade and Windows 10 upgrade.

Chrome Version: 58.0.3029.81
