### ISSUE TITLE
err::insecure_connection if using an aliased `/etc/hosts` entry

### ISSUE THREAD

**Issue by AlexFrazer** [webpack/webpack-dev-server#849]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Suppose you edit `/etc/hosts` with the following entry:
```
127.0.0.1   dev.totemic.com
```
If you visit `https://dev.totemic.com:3000` directly after running `webpack-dev-server`, it will cause an error in the connection: `err:insecure_connection`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create your webpack config. It should look roughly [like this](https://gist.github.com/AlexFrazer/75f462302dd0ce046df8f662889306c1)
2. Edit your `/etc/hosts` to include an entry as above

```
127.0.0.1   dev.totemic.com
```

3. Run the webpack dev server on whatever port.

```
$ webpack-dev-server
```

4. _directly_ visit the aliased route, i.e.: `https://dev.totemic.com:3000`

You'll notice  `err:insecure_response`

### Extra info
If you visit `https://localhost:3000`, and then subsequently visit `https://dev.totemic.com:3000`, it will clear out this error.

**What is the expected behavior?**
It will run the same as it would on `https://localhost:3000`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
webpack@2.2.0 and OS X (latest)

**Comment by SpaceK33z** [comment]
This is not possible. We can't provide a valid certificate for development. Chrome (and some other browsers perhaps) happen to allow all certificates from localhost.
