### ISSUE TITLE
Webpack-dev-server fails on css changes

### ISSUE THREAD

**Issue by DimitrisNL** [webpack/webpack-dev-server#859]
I run webpack and everything runs smoothly. I run webpack-dev-server for the first time after the webpack command and everything works fine.

After some changes in my files, I get the error : 

`ERROR in ./~/css-loader?{"importLoaders":1}!./~/postcss-loader!./src/main.css
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/--path--/node_modules/css-loader/lib/loader'
    Error: ENOENT: no such file or directory, open '/--path--/node_modules/css-loader/lib/loader'
    Error loading /--path--/node_modules/css-loader/lib/loader as "./lib/loader" from /--path--/node_modules/css-loader/index.js
 @ ./src/main.css 4:14-123
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.jsx`

Obviously I have all the loaders installed. Here's my webpack config. 

```
const path = require('path');
const webpack = require('webpack');

// const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: path.resolve(__dirname, 'src/index.jsx'),
    output: {
        path: path.resolve(__dirname, 'public'),
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['*', '.js', '.jsx']
    },
    devServer: {
        publicPath: "/",
        contentBase: path.resolve(__dirname, 'public')
    },
    module: {
        rules: [
            {
                test: /\.jsx$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                options: {
                    presets: ['es2015', 'react']
                }
            }, {
                test: /\.css$/,
                use: [
                    {
                        loader: "style-loader"
                    }, {
                        loader: "css-loader"
                    }, {
                        loader: 'postcss-loader'
                    }
                ]
            }
        ]
    },
}
```

**Comment by SpaceK33z** [comment]
This is not an issue in webpack-dev-server. Please post this on StackOverflow.
