### ISSUE TITLE
webpack-dev-server does not stop on Ctrl+C

### ISSUE THREAD

**Issue by h6ah4i** [webpack/webpack-dev-server#860]
Hi. I noticed that the latest version v2.4.2 have an issue around process signal handling. Pressing Ctrl+C to stop `webpack-dev-server` does not work **while compiling** assets. (NOTE: Ctrl+C works well after finished compilation.)

Also, I reverted the change of the PR #787 to workaround the issue for now.

OS: macOS 10.12.3
webpack-dev-server 2.4.2
webpack 2.3.2

**Comment by shellscape** [comment]
@h6ah4i please confirm that this is still an issue with 2.7.1

**Comment by h6ah4i** [comment]
@shellscape Yep, I can still reproduce the same issue with 2.7.1.

**Comment by shellscape** [comment]
@h6ah4i thanks, we'll look at fixing this over the coming weeks

**Comment by minya92** [comment]
I use this script (on windows), but it is not good (version 2.7.1)
`taskkill /F /IM node.exe /T`

**Comment by dwjohnston** [comment]
If anyone else is intersested in I'm using: 

```"taskkill //pid `netstat -aon | grep 8000 | grep -P '(?<=LISTENING).*' -o | grep -P '\\d*' -o` //f"```

**Comment by ahlechandre** [comment]
We can improve @dwjohnston suggestion by setting his command as a bash alias to avoid typing the command from scratch every time .

1. Open `.bashrc` file:
```bash
vim ~/.bashrc
```

2. Add alias (port `3000`, in my case):
```bash
alias killwebpack="taskkill //pid `netstat -aon | grep 3000 | grep -P '(?<=LISTENING).*' -o | grep -P '\\d*' -o` //f"
```

3. Restart terminal and run whenever you need:
```bash
killwebpack
```

**Comment by shellscape** [comment]
@h6ah4i @minya92 @dwjohnston @ahlechandre please check out and try this branch: https://github.com/webpack/webpack-dev-server/tree/fix-sigint-edge

I believe I identified a potential race condition between `server.close()` and `process.exit()`. Pull Request #1157 adds a test to confirm that SIGINT detection is working correctly. Outside of that pure Node environment, issues with that are likely going to be tied to the console setup of a particular user.
