### ISSUE TITLE
Hot module / hrm not working anymore?

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack-dev-server#862]
Config example:

```
//webpack config
devServer: {
	port: 9000,
	historyApiFallback: {
		rewrites: [
			{ from: /superadmin*/, to: '/build/superadmin/index.html' },
			{ from: /admin*/, to: '/build/admin/index.html' },
			{ from: /user*/, to: '/build/user/index.html' },
			{ from: /.+?/, to: '/build/visitor/index.html' },
		],
	},
	proxy: {
		'/api': 'http://localhost:8080',
		'/p/api': 'http://localhost:8080',
	},
	compress: true,
	hot: true,
	hotOnly: true,
},
entry: {
	'visitor/app': ['./public/visitor/entrypoint.js'],
	'user/app': ['./public/user/entrypoint.js'],
	'admin/app': ['./public/admin/entrypoint.js'],
	'superadmin/app': ['./public/superadmin/entrypoint.js'],
	'vendor': [
		'react-hot-loader/patch',
		'webpack-dev-server/client?http://0.0.0.0:9000',
		'babel-polyfill',
		'autobind-decorator', 'axios', 'lodash', 'material-ui', 'moment', 'moment-timezone',
		'react', 'react-dom', 'react-tap-event-plugin', 'react-redux', 'react-router', 'redux', 'reflexbox',
	],
},
output: {
	filename: 'build/[name].min.js',
	publicPath: '/',
},
```

//visitor/entrypoint.js
```
document.write('visitor');
console.log('visitor');
```

http://localhost:9000/ shows correctly the visitor bundle/app.
I try to change the word "visitor" with "whatever" but nothing happens, HMR seems to connect correctly but then once the bundle gets updated nothing is changed on browsers.
Here the console: what's wrong? 

![screen shot 2017-03-29 at 16 31 05](https://cloud.githubusercontent.com/assets/2225869/24460018/4cb12222-149d-11e7-8c29-c4efa3a92eb5.png)

**Comment by rvanmil** [comment]
Same issue here, everything seems to be working correctly, but the DOM is not updating.

<img width="516" alt="hmr log" src="https://cloud.githubusercontent.com/assets/991226/24953209/c2963a30-1f7a-11e7-8e0b-386fb5449b45.png">

**Comment by rvanmil** [comment]
I found a solution over here. https://github.com/gaearon/react-hot-loader/issues/511#issuecomment-288673129

**Comment by davecranwell** [comment]
I've been experiencing this too, and discovered that adding `--hot` flag to `webpack-dev-server` works. I'm not clear if it's quite the same kind of refresh that HMR might do though.

**Comment by shellscape** [comment]
Pruning due to age and apparently solution/workaround.

**Comment by PixsaOJ** [comment]
sorry, I am noob here.

> I found a solution over here. gaearon/react-hot-loader#511 (comment)

What is that App in: 
`const NextApp = require('components/App').default;` ?
