### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by jamesmwali** [webpack/webpack-dev-server#864]
I don't know whats causing this issue, but it seems to be breaking a route i've been working on, on prod. My localhost is perfectly fine, i don't even know where to begin to debug this. Please help. 

These are the following errors i'm getting from the console log. 

1. Uncaught SyntaxError: Unexpected token <
2. Dynamic page loading failed Error: Loading chunk 4 failed.
    at HTMLScriptElement.c
3. Uncaught (in promise) Error: Loading chunk 4 failed.
    at HTMLScriptElement.c

Looking at this error a bit closer, i saw that it fails when load chunck 4, so i don't know what the issue is, granted my localhost is fine. i'm using react-boilerplate

**Comment by jcrben** [comment]
It doesn't seem like there's enough information here to really help you.

You're using https://github.com/react-boilerplate/react-boilerplate - why didn't you report it there?
