### ISSUE TITLE
Reload the page when the compilation starts

### ISSUE THREAD

**Issue by BenoitZugmeyer** [webpack/webpack-dev-server#865]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

When using the default configuration, without HMR, with "inline":

* Watch for changes
* On something changes, start compilation
* On compile ends, reload the page
* On page is loaded, JS starts to load

**What is the expected behavior?**

* Watch for changes
* On something changes, start compilation and reload the page
* On page is loaded, JS requests pend until the compilation ends
* On compile ends, do nothing except serving new JS files

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is a small modification but could greatly improve my team workflow. We are in the process of transitioning a big project to webpack, and it takes about 3 seconds to compile when a file changes. Also, the page we are woking on may take a few seconds to load.

If the page would be reloaded when the compilation starts instead of when it ends, both compilation process and page load could be done in parallel and save a few seconds for each changes.

I tried to put a `window.location.reload()` in the `index.js` `invalid` callback and it works like a charm.

**Please mention your webpack and Operating System version.**

* webpack: 2.2.1
* webpack-dev-server: 2.4.2
* ArchLinux (up to date)

**Comment by shellscape** [comment]
Pruning due to age.

**Comment by BenoitZugmeyer** [comment]
This still could be a nice enhancement to the current webpack-dev-server version. I made an issue trying to explain it to the best I can: could I have a comment about this? Maybe it's doable with a plugin?

**Comment by shellscape** [comment]
I believe by doing that you're running the risk of a race condition; the page reload may be triggered too soon and wouldn't reflect changes in compilation for large projects. Just not sure that's a viable feature for everyone. It sounds like you have a viable workaround/solution for your teams, so I'd recommend running with that for the time being.
