### ISSUE TITLE
DevServer + local network + https + Safari mobile = Page reload every seconds

### ISSUE THREAD

**Issue by YoannBureau** [webpack/webpack-dev-server#868]
Hi,

I'm trying to build an app that requires Secure Origins to let me use geolocalisation and other stuffs on a mobile terminal.

My webpack is running on my computer and I added the --https option while executing the server.

The problem: That works great on my PC, but I have a very strange behaviour on my Iphone Safari: my page reloads every seconds, inifinitely.

Here is my webpack.config.js:

> module.exports = {
    entry: './main.js',
    output: {
        filename: './bundle.js'
    },
    devServer: {
        host: "10.61.32.79"
    }
}

I start my server by simply typing `webpack-dev-server --https`

Find in attachments the node project that reproduces the behaviour. Just type npm install, replace the IP adress with yours in the webpack.config.js, type npm start and see the behaviour on an iphone.

[WebpackDevServerHttps.zip](https://github.com/webpack/webpack-dev-server/files/896344/WebpackDevServerHttps.zip)

**Comment by YoannBureau** [comment]
Tested on Mobile Chrome : same behaviour

**Comment by shellscape** [comment]
Closing due to age and inactivity. If someone is able to put together a test case in a repo (rather than a ZIP, those are a little dicey because of trust issues) we can use to reproduce, we'll revisit this one.

**Comment by mimshwright** [comment]
@shellscape I was having the same problem. I created a repo that can reproduce this bug. 
I tried to strip out as much as I could and it appears that it's simply related to using --host x.x.x.x and --https options.

https://github.com/mimshwright/wps-bug

**Comment by shellscape** [comment]
@mimshwright I no longer maintain this project

**Comment by mimshwright** [comment]
OK. well, hopefully someone else will pick this up.
