### ISSUE TITLE
CLI option --hot-only is confusing

### ISSUE THREAD

**Issue by agoldis** [webpack/webpack-dev-server#877]
Using 
* `webpack-dev-server` `2.4.2`
* `webpack` `2.4.1`

According to the [documentation](https://webpack.js.org/configuration/dev-server/#devserver-hotonly-cli-only) CLI option `--hot-only` should:

> Enable Hot Module Replacement (see devServer.hot) without page refresh as fallback in case of build failures.

However, HMR won't work unless `--hot` option is specified as well. The reason is that [webpack/bin/convert-argv.js](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L385) only injects `HotModuleReplacementPlugin` if `--hot` option is set.

CLI help message is a bit better, but still worth mentioning that it must be `--hot` option set:

```bash
./node_modules/.bin/webpack-dev-server -h
...
--hot-only                 Do not refresh page if HMR fails          [boolean]
...
```

May be it's better to implicitly apply `--hot` if `--hot-only` mentioned

**Comment by benwiley4000** [comment]
Agree with this - was about to open the same. Documentation implies `--hot-only` would enable hot module replacement and requiring `--hot` **in addition** seems  needlessly verbose. I can submit a PR to correct this behavior if desired?

**Comment by benwiley4000** [comment]
Looks like this is actually handed [inside of webpack](https://github.com/webpack/webpack/blob/57825153e531a079eb0dbd2528e47f4cbafcc7f2/bin/convert-argv.js#L385) (confusing). So there are two options:

1. Assign `argv['hot']` to `true` before passing `argv` to `webpack/bin/convert-argv` if `argv['hot-only']` is true (seems messy).
2. Check additionally for the `hot-only` arg inside of `webpack/bin/convert-argv.js` (since we're already checking for `hot` this seems ok?).

I prefer option 2.

**Comment by agoldis** [comment]
@benwiley4000 Thank for supporting this request, i am certain that option 2 + documentation fix will make it clearer.
It would be good, thought, to get an input from contributors :)

**Comment by arjunkathuria** [comment]
this bug / issue still around ?

can get started on my contributions : )

**Comment by arjunkathuria** [comment]
@shellscape i have a long weekend coming, will look into it : )

**Comment by shellscape** [comment]
Closing issue as abandoned as it's more than 90 days stale

**Comment by limitedAtonement** [comment]
Just to be sure, I still need to add `--hot` in addition to `--hot-only`? (I'm using a `.js` configuration, so this amounts to

    module.exports = {
        devServer : {
            hotOnly: true,
            hot: true, // Also required!
        },
    };
