### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by wooodchen** [webpack/webpack-dev-server#879]
Start dev server, after save files, it will export warn:
```console
dev-server.js?b7b7:37 [HMR] Update failed: TypeError: Cannot read property '0' of undefined
at hotEnsureUpdateChunk (http://localhost:8080/dist/bundle.js:269:36)
at http://localhost:8080/dist/bundle.js:245:14
```

**Comment by orangeyyy** [comment]
I have got the same problem

**Comment by bebraw** [comment]
Can you set up a standalone project? It's not possible to debug this otherwise.

**Comment by shellscape** [comment]
Going to close this for tag management. Please give the newer versions of both webpack and webpack-dev-server a try. If the issue persist, we'll need a sample app in a repo to be able to reproduce this.
