### ISSUE TITLE
proxy removes double slashes "//" automatically

### ISSUE THREAD

**Issue by Emad-Emami** [webpack/webpack-dev-server#880]
I'm using this proxy config for my react application:
`proxy: {
			"/etc/api/": {
				"target": "http://www.example.com/etc/api/",
				pathRewrite: {
					'^/etc/api/' : ''
				},
				changeOrigin: true,
				secure: false
			}
    	}`
but in some conditions my app sends some get requests which has double slash in URL like (before "key"):
`http://www.example.com/etc/api/getlists//key/45b2606d86dfbdef2bfaed0b5eb5450ac2b8f8da`
It seem proxy method removes "//" automatically. why? is it on purpose or bug?

**Comment by jtesser** [comment]
I have the same exact issue 
config is 
'/api': {
          target: 'http://localhost:8080',
          changeOrigin: false
        },

and I send /api/v1/browsertree/sitename/demo.dotcms.com/uri//
BUT I get this at the webserver
/api/v1/browsertree/sitename/demo.dotcms.com/uri/

**Comment by fmontes** [comment]
I'm having the same issue... maybe there is an option we are missing?

**Comment by bebraw** [comment]
It uses [http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware) underneath. Could you try to set up a standalone test case against that so we can rule out a WDS bug?

**Comment by shellscape** [comment]
Closing due to age and inactivity. If someone is able to put together a test case in a repo we can use to reproduce, we'll revisit this one.
