### ISSUE TITLE
webpack-dev-server :  configuration has an unknown property 'process' 

### ISSUE THREAD

**Issue by xxza** [webpack/webpack-dev-server#905]
npm run dev
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\intall\\node\\node.exe',
1 verbose cli   'D:\\intall\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle react_demo1@1.0.0~predev: react_demo1@1.0.0
6 silly lifecycle react_demo1@1.0.0~predev: no script for predev, continuing
7 info lifecycle react_demo1@1.0.0~dev: react_demo1@1.0.0
8 verbose lifecycle react_demo1@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle react_demo1@1.0.0~dev: PATH: D:\intall\node\node_modules\npm\bin\node-gyp-bin;D:\node-prac\web\node_modules\.bin;D:\intall\git\cmder\bin;D:\intall\git\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\intall\git\cmder\vendor\conemu-maximus5;D:\intall\git\cmder\vendor\conemu-maximus5\ConEmu;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;D:\intall\git\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Enterprise Vault\EVClient\x64\;D:\intall\node\;D:\intall\360se6\Ruby23-x64\bin;C:\Users\xinxu211443\AppData\Local\Microsoft\WindowsApps;D:\intall\搜狐影音\5.0.3.8;D:\intall\avsCode\Microsoft VS Code\bin;C:\Users\xinxu211443\AppData\Roaming\npm;D:\intall\git\Git\usr\bin;D:\intall\git\Git\usr\share\vim\vim74;D:\intall\git\cmder\
10 verbose lifecycle react_demo1@1.0.0~dev: CWD: D:\node-prac\web
11 silly lifecycle react_demo1@1.0.0~dev: Args: [ '/d /s /c', 'webpack-dev-server' ]
12 silly lifecycle react_demo1@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle react_demo1@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: react_demo1@1.0.0 dev: `webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\intall\node\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\intall\node\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react_demo1@1.0.0
16 verbose cwd D:\node-prac\web
17 error Windows_NT 10.0.14393
18 error argv "D:\\intall\\node\\node.exe" "D:\\intall\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error react_demo1@1.0.0 dev: `webpack-dev-server`
23 error Exit status 1
24 error Failed at the react_demo1@1.0.0 dev script 'webpack-dev-server'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the react_demo1 package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack-dev-server
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs react_demo1
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls react_demo1
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by xxza** [comment]
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'process'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }

**Comment by bebraw** [comment]
Based on the error you have `process` field in your configuration. Removing that should resolve the issue.

**Comment by shellscape** [comment]
Pruning due to age and inactivity.
