### ISSUE TITLE
Make server url clickable in terminal

### ISSUE THREAD

**Issue by FriOne** [webpack/webpack-dev-server#908]
**What is the current behavior?**
When you start server you see `Project is running at http://localhost:3002/` which is not clickable.

**What is the expected behavior?**
When you click on link with ctrl (or cmd) os should open an url in browser.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It is very convinient :)

Do not know if it possible with webpack's streams, but when you create a server with angular cli, server url link is clickable.

**Comment by AshikNesin** [comment]
Not sure if that's easy/possible.

We could copy the link to clipboard?

Just like `serve` does.

What do you think? @FriOne

![image](https://cloud.githubusercontent.com/assets/4201088/26096599/52359b48-3a3f-11e7-8975-93c18005b505.png)

**Comment by FriOne** [comment]
@AshikNesin The copying may remove something important that a developer copied previously.
Also, sometimes you close browser tab and then want to open it again.
It is 100% possible, but it may be not so easy with webpack ecosystem.

**Comment by AshikNesin** [comment]
@FriOne Yeah.. Didn't think about that use case. 

Lets see if someone can help us :)

(I'm new to webpack dev ecosystem)

**Comment by schester44** [comment]
on OSX, you can use cmd + double click to open the link.

**Comment by FriOne** [comment]
@schester44 unfortunatly I have windows :) What about Linux?

**Comment by shellscape** [comment]
Unfortunately there isn't a way with cmd.exe. However, there is a way with PowerShell (https://stackoverflow.com/questions/3644940/click-a-hyperlink-using-powershell) and you can always opt to use something like the Hyper terminal (https://hyper.is/) on Windows.

**Comment by FriOne** [comment]
@shellscape I use Git Bash, so why is it possible with angular cli but doesn't with webpack?

**Comment by shellscape** [comment]
@FriOne perhaps they're using some console output formatting that I'm not familiar with. The first stop would be the angular cli project on github, analyze (or ask the team there) and find the code/characters responsible for allowing it to be clickable, and then opening a PR here for allowing the same :)
