### ISSUE TITLE
Inline mode shouldn't add a second WDS client to entry

### ISSUE THREAD

**Issue by jeremejevs** [webpack/webpack-dev-server#913]
This is related to #711. If there is `webpack-dev-server/client` in the `entry` of a Webpack config, then WDS should just skip adding it and/or display a warning. The same should probably be done for `hot`/`hotOnly`. Sometimes, like when [using React Hot Loader](https://webpack.js.org/guides/hmr-react/), you (at the same time) want to:

1. Use `webpack-dev-server` CLI
2. Have `inline` mode enabled (so that it displays a proper "Project is running at")
3. Have an `entry` with `webpack-dev-server/client` defined in it explicitly

**Edit:** Just found #616. My proposed solution is different, but the problem is the same, so, it probably makes sense to merge them. Let me know what's preferred.

**Comment by shellscape** [comment]
I think it makes sense to continue the discussion on #616. Closing this one for now.
