### ISSUE TITLE
It should be possible to prevent inline mode from making assumptions about the location of the client

### ISSUE THREAD

**Issue by jeremejevs** [webpack/webpack-dev-server#914]
I'm talking about [this line](https://github.com/webpack/webpack-dev-server/blob/662bc31a4fc44b6888b5a0baff9ee96fef049cdb/lib/util/addDevServerEntrypoints.js#L7). The query part should be made optional, or at least configurable. Otherwise, it's impossible to have a WDS served from behind a proxy, in CLI with HMR, without either disabling the inline mode (which results in a wrong "Project is running at" + having to adjust `entry` and `plugins` manually) or specifying the `public` URL (which is a poor solution, since it would require one to change the Webpack config every time the URL the app is published on changes, which can happen often with e.g. [ngrok](https://ngrok.com/)).

Alternatively, it should be possible to override [these heuristics](https://github.com/webpack/webpack-dev-server/blob/662bc31a4fc44b6888b5a0baff9ee96fef049cdb/client/index.js#L22).

Related issues: #262, #704, #804

**Comment by shellscape** [comment]
We'd happily review a Pull Request to resolve this issue.

Closing due to age and inactivity.

**Comment by jeremejevs** [comment]
But why close, if it's not a "won't fix"? I don't see how being old/inactive makes this issue obsolete, unless it isn't valid anymore. This isn't even a feature request, it's more of a report of bad UX.

There are good-enough workarounds, and HMR is non-essential for us, so I can't justify spending any billed time on addressing this, I'm afraid. However, this kind of fits [up-for-grabs](http://up-for-grabs.net) / [first-timers-only](http://www.firsttimersonly.com/).

**Comment by shellscape** [comment]
I understand your frustration, I do. Unfortunately we've got new issues coming in every day, very few maintainers to help triage, counsel and fix. And we'd gotten to the point of well over 100 pending issues, a third of which had no replies and were over three months old. At some point pruning was needed. You'll see this kind of thing on other projects, most notably with NPM. The exception being that here, we'll see if/when issues that were closed suddenly gain traction.

I also understand that you can't spend time on this (or justify the time to implement it for billing purposes), that'll happen. Perhaps someone else will see this issue and want to help out. For now, and for the purposes of managing a fairly large project, we're tagging this one as a nice-to-have. I get that's probably not very comforting, but it's an unfortunate necessary step to get the project back to a sane place where issues can be addressed in a timely fashion. Remember, we're all just volunteering extra time we have to pitch in.

**Comment by jeremejevs** [comment]
I understand why this is low priority, but not why it needs to be closed. How is this policy justified in other projects, like NPM? Why do labels not suffice? Isn't "closed" a pretty much universal sign for "solved" or "considered and declined"?
