### ISSUE TITLE
Project path with %20 will not be served (404)

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack-dev-server#915]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Using `webpack-dev-server` on a project with a `%20` in it's path will result in runtime 404.

**If the current behavior is a bug, please provide the steps to reproduce.**
- On a project that uses `webpack-dev-server`, rename the project folder so that it includes `%20` (e.g. `project%20name`).
- Serve the project, and open your browser in the project address.
- Observe the 404 result.

**What is the expected behavior?**
Project path should not affect asset response code.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
- `webpack@2.5.1`
- `webpack-dev-server@2.4.5`
- Windows 10

**Comment by scott-cornwell** [comment]
This is definitely a thing, and also happens on OSX. We were running into this issue on Windows 10 and OSX and found that %20 in the path (path name created by Windows running in a VM on OSX) caused the same issue on both machines. Even worse, webpack-dev-server seems to actually fall back to serving files from the filesystem if a separate dev build was done with the same webpack config. Good news is you can just fix your path and `npm install` and it works.

Not sure if this is actually the fault of webpack-dev-server or node itself.

**Comment by shellscape** [comment]
Closing for now since there's a workaround. We'd also happily review a Pull Request for a workaround in the code.
