### ISSUE TITLE
Configure webpack-dev-server with a corporate proxy

### ISSUE THREAD

**Issue by drewwells** [webpack/webpack-dev-server#919]
**Do you want to request a *feature* or report a *bug*?**

Feature
**What is the current behavior?**
all environment variables are ignored `http_proxy https_proxy HTTP_PROXY HTTPS_PROXY`
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
read the environment and use this for making external requests.
**If this is a feature request, what is motivation or use case for changing the behavior?**
Use webpack-dev-server with a corporate proxy.
**Please mention your webpack and Operating System version.**
webpack 1.14.0
webpack-dev-server 1.16.2

**Comment by chimurai** [comment]
Adding `agent` in your proxy config should do the trick.
Recipe / details can be found here:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md

**Comment by drewwells** [comment]
That looks useful to document in the dev server project!

**Comment by shellscape** [comment]
We'd happily accept an update to the [documentation](https://webpack.js.org/configuration/dev-server/#devserver). Anyone can edit it!
