### ISSUE TITLE
Ability to configure proxy server to retry connection

### ISSUE THREAD

**Issue by jeffreznik** [webpack/webpack-dev-server#920]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**
Webpack proxy server receives ECONNREFUSED error while server it is trying to connect to is restarting and dies.
**Update:** (found the issue was somewhere else) Actually the WDS client makes the request which fails.  Refreshing on the client side will fix it (but this defeats the purpose of using WDS with --hot)

**What is the desired behavior?**
Provide an option to retry the connection a few times (on the server-side) before dying, giving the server it is proxying to a chance to come back up.  

**If this is a feature request, what is motivation or use case for changing the behavior?**
I have a universal (isomorphic) app, and use `webpack-dev-server --hot` to serve up the client files (bundle.js, et al.), and use a combination of `nodemon` and `webpack --watch` to serve my API and recompile as needed.

When I edit/save a component that is shared between the client and server, webpack recompiles which triggers nodemon to restart, while at the same time webpack-dev-server also recompiles and tries to reproxy API requests to my API server.

In the 0.2sec that it takes for the webpack/nodemon combination to complete, webpack-dev-server has already recompiled and tried to reset the proxy server, but fails (~50% of the time) because it was quicker.  If it would just try again 50-100ms later, it would get a successful connection.

**Please mention your webpack and Operating System version.**
webpack 2.6.0 & macOS 10.12.5

**Comment by jeffreznik** [comment]
Actually the issue is occurring in a different place... The Webpack proxy server doesn't die, the client side (browser) tries to reconnect but fails.

Still, either the client or the proxy server could retry a few times before dying.

**Comment by jeffreznik** [comment]
I should also note that I'm proxying to root ('/') because I am also doing server-side rendering.

```
config.devServer = {
  contentBase: "./public",
  publicPath: "/assets/",
  historyApiFallback: true,
  host: '0.0.0.0',
  port: 3001,
  proxy: {
    // Send all requests to express, except WDS will still serve up its version of /assets/bundle.js for HMR to work
    '/': {
      target: 'http://0.0.0.0:3000',
      secure: false
    }
  }
};
```

**Comment by jeffreznik** [comment]
After reviewing the code, it looks like this is functionality that should be added to `http-proxy-middleware` instead.

**Comment by DylanPiercey** [comment]
@jeffreznik did you ever find a solution?
