### ISSUE TITLE
HTTPS server proxying to HTTP should set X-Forwarded-Proto header

### ISSUE THREAD

**Issue by kevinburke** [webpack/webpack-dev-server#933]
If you are running webpack-dev-server in https mode, and proxying to a server listening on http, the proxy should set the X-Forwarded-Proto: https header.

`koa` sets the `request.secure` based on either the presence of terminated TLS (which the proxy is not doing), or the presence of the X-Forwarded-Proto: https header (which webpack-dev-server) is currently not setting.

This means if you try to set a `secure` cookie from the proxy, koa throws a 500 server error. I've asked the koa devs (and the cookie library maintainer) to change this behavior, but neither of them seems particularly willing or interested in doing it.

https://github.com/koajs/koa/issues/974
https://github.com/pillarjs/cookies/issues/87

**Comment by shellscape** [comment]
I believe that header can be set through `headers` https://webpack.js.org/configuration/dev-server/#devserver-headers-

Otherwise, we'd happily review a pull request to resolve this case.

**Comment by pmoleri** [comment]
> I believe that header can be set through headers https://webpack.js.org/configuration/dev-server/#devserver-headers-

According to docs that only sets response headers.

You can pass arbitrary options to the proxy middleware.
Setting `xfwd: true` should do the trick.
