### ISSUE TITLE
hot module replacement `__webpack_hash__ is not defined` on reload

### ISSUE THREAD

**Issue by hellatan** [webpack/webpack-dev-server#94]
Following the webpack dev server guide with hot module replacement using the inline script (`<script src="http://localhost:8080/webpack-dev-server.js"></script>`), it seems like the hot loader is throwing this js error after doing a rebuild:

    Uncaught ReferenceError: __webpack_hash__ is not defined

any clue what is going on ?

**Comment by sokra** [comment]
Are you using the up-to-date versions of webpack and webpack-dev-server?

**Comment by hellatan** [comment]
@sokra i just tried this on a different computer and it seems to work. I'll have to see which versions I have loaded on my home computer to see.  These are the versions I'm using after doing a fresh `npm install` on my work computer:

- webpack v1.4.14
- webpack-dev-server v1.7.0

**Comment by hellatan** [comment]
thanks @sokra. my home version was super old.
