### ISSUE TITLE
Multiple devServer.publicPath

### ISSUE THREAD

**Issue by reda-alaoui** [webpack/webpack-dev-server#945]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
We can only pass one publicPath to devServer options.

**What is the expected behavior?**
Be able to pass multiple publicPaths to devServer options.

**If this is a feature request, what is motivation or use case for changing the behavior?**
My webpack dev server is in front of a tomcat webapp container exposing multiple entry points, `/path-1/index.html` and `/path-2/index.html`. 
`index.html` files should be able to access webpack bundle.js relatively to its current location like this:
```xml
<script src="bundle.js"></script>
```

Passing `/path-1/` and `/path-2/` as publicPath to devServer would allow me to do that.

**Please mention your webpack and Operating System version.**
webpack 2.5.1
webpack-dev-server 2.4.5
ubuntu 17.04

**Comment by shellscape** [comment]
(this is also tracked in #200)

we gave this a lot of thought and consideration. the complexity this introduces between webpack-dev-server and webpack-dev-middleware, combined with the lack of a large community call for the feature, combined with the [workarounds available](https://github.com/webpack/webpack-dev-server/issues/200#issuecomment-139666063) have pointed towards not adding this to the codebase.

please rest assured that this was a tough call and that we really, truly appreciate the time you took and work you put into creating the issues and putting the pull requests together. we're closing this issue, but please feel free to discuss. if there's a large community call for this feature we'd be happy to re-evaluate for v3.
