### ISSUE TITLE
hot-update.json 404 but replay shows file exists

### ISSUE THREAD

**Issue by richardadrian** [webpack/webpack-dev-server#950]
I am getting a 404 when it tries to find the hot-update.json files, but when I go into the network tab I can replay the request and it finds the file.

![image](https://user-images.githubusercontent.com/12628030/27349498-75033f26-55c5-11e7-9db0-35a6cf0f6405.png)

I am using 
    "webpack-dev-server": "^2.4.5",
    "react-hot-loader": "^3.0.0-beta.7",

**Comment by realtebo** [comment]
Sorry, I've the same problem; how did your solved?
