### ISSUE TITLE
Intercept reload event.

### ISSUE THREAD

**Issue by DylanPiercey** [webpack/webpack-dev-server#959]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

Currently there is no clean way to reload a server and the browser at the same time.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Ideally there would be a way to intercept reload events and tell the dev server when we are ready.
Something like this:

```js
new DevServer({
  preReload: (done) => {
    // Restart a server, cleanup some files, do some stuff.
    setTimeout(done, 1000) // Async tell dev server when to actually reload.
  }
})
```

**Please mention your webpack and Operating System version.**
Webpack 3.0, macOS Sierra.

**Comment by shellscape** [comment]
We'd happily accept a PR to implement this feature!

**Comment by DylanPiercey** [comment]
I'll look into it 🙂

**Comment by shellscape** [comment]
@DylanPiercey this ticket is stale at 60+ days and will be closed if there's no response from the community. last chance to weigh in 😅

**Comment by shellscape** [comment]
Closing as abandoned
