### ISSUE TITLE
webpack.config.js, webpack-dev-server open option has bug.

### ISSUE THREAD

**Issue by haegul** [webpack/webpack-dev-server#960]
on the webpack-dev-server@2.5.0. I was set like this.
```
    devServer: {
        hot : true,
        inline: true,
        host: '0.0.0.0',
        disableHostCheck: true,
        port: 3000,
        open : true,  // this is point option
        contentBase : "public",
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        }
    },
```
I expect open **http://localhost:3000/** on browser, but the behavior is **http://localhost:3000/undefined**.
So I tested on webpack-dev-server@2.4.5. It works good. I think @2.5.0 bug. How about reference require('opn'). I guess this module is related  the behavior.

Thanks !

**Comment by JeancaPL** [comment]
+1

**Comment by handonam** [comment]
Can confirm.  I had to downgrade to 2.4 to get it working again.

**Comment by cardenasJC** [comment]
+1

**Comment by JavierLaguna** [comment]
+1

**Comment by awmottaz** [comment]
Same for me. Using the `--open` CLI option still works as expected.

**Comment by agupta1989** [comment]
Use reactions 👍  option if you want to give more value to this issue instead of commenting +1.

**Comment by Em3k** [comment]
Had the same problem with it today. Thanks for solutions!

**Comment by MarioDabrowski** [comment]
+1

**Comment by aprather51** [comment]
+1

**Comment by ThadeuLuz** [comment]
As a quick fix, you can add `openPage: ''` to your options:

```JavaScript
  devServer: {
    host: 'localhost',
    port: 3000,
    contentBase: './dist',
    hot: true,
    open: true,
    openPage: '', // <== Add this
  },
```

**Comment by polettoweb** [comment]
+1

**Comment by haegul** [comment]
@ThadeuLuz 
Thank you for advise!
I expect to fix this bug on next version.

**Comment by goartur** [comment]
+1

**Comment by zhengjunxiang** [comment]
@ThadeuLuz
Thank you for advise

**Comment by scarletgirl** [comment]
+1

**Comment by shellscape** [comment]
@MarioDabrowski @aprather51 @polettoweb @goartur @scarletgirl Please use reactions on the original post in this thread (for example, 👍 ) instead of posting "+1" replies. It doesn't contribute to the discussion and only clutters the issue.

**Comment by awave1** [comment]
also I found that this issue doesn't occur when --open flag is used

**Comment by shellscape** [comment]
#973 resolves this, so when that is merged, this issue will the resolved. locking the convo to avoid more followups.

**Comment by BrahimS** [comment]
Hi everyone,
For those whose struggling with HMR, you can have a look at [BrowserSync plugin for Webpack](https://www.npmjs.com/package/browser-sync-webpack-plugin)

**Comment by ZUCINNI** [comment]
lol) * just chekin my new avatar))) *
