### ISSUE TITLE
Not compatible with webpack 3.0 ??

### ISSUE THREAD

**Issue by gimmi** [webpack/webpack-dev-server#961]
Hi, when upgrading to webpack 3, i get the following warning from NPM:

```
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.
```

Are there some known compatibility problems with webpack 3?
Maybe just a matter of updating `package.json`

**Comment by screendriver** [comment]
You can have a look at pull request https://github.com/webpack/webpack-dev-server/pull/946

**Comment by marcelometal** [comment]
Could you please release a new version with webpack 3 compatibility?

**Comment by Mathspy** [comment]
This should be fixed now
https://github.com/webpack/webpack-dev-server/pull/946#issuecomment-313593956
