### ISSUE TITLE
Docs for `port` says "CLI only" but it works in webpack.config.js

### ISSUE THREAD

**Issue by alexilyaev** [webpack/webpack-dev-server#967]
**Do you want to request a *feature* or report a *bug*?**

Docs clarification

**What is the current behavior?**
Docs for `port` says "CLI only" but it works in webpack.config.js  
https://webpack.js.org/configuration/dev-server/#devserver-port-cli-only

**What is the expected behavior?**
The property works under `devServer` in `webpack.config.js`, so why say it's CLI only?

**Please mention your webpack and Operating System version.**
"webpack": "3.0.0",
"webpack-dev-server": "2.5.0"
Node v6.9.1
macOS 10.12.5

**Comment by shellscape** [comment]
Please do feel free to edit the document for that option. You can do so here: https://github.com/webpack/webpack.js.org/edit/master/content/configuration/dev-server.md

**Comment by alexilyaev** [comment]
Looks like it was already updated a week ago:  
https://github.com/webpack/webpack.js.org/commit/49208bf5a3db37ba2ac801b271b4d02b1278ce1c

:-)
