### ISSUE TITLE
Using ModuleConcatenationPlugin stops watching source files for changes

### ISSUE THREAD

**Issue by rosskevin** [webpack/webpack-dev-server#968]
This _could_ be a duplicate of #949, but note that I **am not** using any hot reloading.

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Presence of the `new webpack.optimize.ModuleConcatenationPlugin()` causes file changes to stop being watched on OSX.  Removing it allows watching to work.

I have verified that `fsevents` is emitting changed file events and it is not some other bug by running this script simultaneous to changing a file:

`watchDebug.js`

```js
#!/usr/bin/env node
// @flow

const fsevents = require('fsevents')
const Logger = require('@alienfast/ui/util/Logger').default

const log = Logger.get('watchDebug')
const watching = __dirname
const watcher = fsevents(watching)
log.info('Watching ', watching, '...')
watcher.on('fsevent', function (path, flags, id) {
  // RAW Event as emitted by OS-X
  log.info('fsevent', path, flags, id)
})
watcher.on('change', function (path, info) {
  // Common Event for all changes
  log.info('change', path, info)
})
watcher.start() // To start observation

setTimeout(() => watcher.stop(), 500000)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. include plugin `new webpack.optimize.ModuleConcatenationPlugin()`
1. run the `watchDebug.js` script above
1. run webpack-dev-server
1. change a file (both watchDebug and webpack-dev-server should see the cange)

**What is the expected behavior?**
webpack-dev-server responds to changed files regardless of use of the `ModuleConcatenationPlugin`

**Please mention your webpack and Operating System version.**

```
[~/p/a/s/d/ui ❯❯❯ yarn list webpack webpack-dev-server fsevents                                                                                                                                                                      ⏎
yarn list v0.24.6
├─ fsevents@1.1.2
├─ webpack-dev-server@2.5.0
└─ webpack@3.0.0
✨  Done in 1.55s.

~/p/a/s/d/ui ❯❯❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

**Comment by shellscape** [comment]
@rosskevin have you found a workaround or solution to this issue?

**Comment by rosskevin** [comment]
@shellscape my only workaround is to only require it in `production`.

**Comment by shellscape** [comment]
Cool. Glad there's a workaround for it. There's been several updates to webpack (and this module) so I'd encourage you to try both updates as well. But that's likely going to be an issue that's better raised with the main webpack project at https://github.com/webpack/webpack, since that's where that module lives, and as others have pointed out this is a specific problem that cropped with up with webpack 3.
