### ISSUE TITLE
historyApiFallback not working 

### ISSUE THREAD

**Issue by chobo2** [webpack/webpack-dev-server#971]
Hi

I keep getting` Cannot GET /task `I tried to modify my webpack with solutions I found here but I still get it.

```
var HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
    entry: './src/app.js',
    output: {
        path: __dirname + '/dist',
        filename: 'app.bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.s?css$/,
                use: ['style-loader', 'css-loader', 'sass-loader']
            }, {
                test: /\.js$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            }, {
                test: /\.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
                loader: 'file-loader?name=fonts/[name].[ext]'
            }
        ]
    },
    devServer: {
        historyApiFallback: {
            index: '/index.html'
        },
        stats: true,
        inline: true,
        progress: true
    }
    plugins: [new HtmlWebpackPlugin({template: './src/index.html'})]
}
```
This happens when I am doing routing. For instance I click a button that loads a "task" component(reactjs) and then I go and make a change in code which causes my page to reload since I am using dev server.

When the page reloads I see that error.

**Comment by shellscape** [comment]
@chobo2 please provide a sample application for folks to use to debug this case.

**Comment by shellscape** [comment]
Since this was asked before we started enforcing the issue template question notice...

> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.

... we let this stay up here for discussion. However, we're going to close due to inactivity. Please do try StackOverflow or the Webpack Gitter.

**Comment by chaddjohnson** [comment]
Using

```javascript
historyApiFallback: true
```

instead of

```javascript
historyApiFallback: {
    index: '/index.html'
}
```

appears to be working for me.
