### ISSUE TITLE
Webpack open config option opens to /undefined

### ISSUE THREAD

**Issue by coltonw** [webpack/webpack-dev-server#972]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug introduced by PR #917 

**What is the current behavior?**
The page opened by webpack-dev-server is /undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

If you use a webpack config file using `devServer.open = true` but have not set `devServer.openPage`, the the opened page will by /undefined

**What is the expected behavior?**
It should open to just /

**Please mention your webpack and Operating System version.**
webpack 2.5 Mac OS X El Capitan

**Also**
PR in progress

**Comment by lerte** [comment]
As a quick fix, you can add openPage: '' to your options:
openPage: '' // <== Add this
https://github.com/webpack/webpack-dev-server/issues/960

**Comment by shellscape** [comment]
I believe we have this fixed in the latest version. And the workaround that @lerte mentioned is valid for older versions.
