### ISSUE TITLE
Show compilation status on overlay

### ISSUE THREAD

**Issue by Wernerson** [webpack/webpack-dev-server#974]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Error messages get display on the overlay and in the terminal. Compilation status only appears in terminal.

**What is the expected behavior?**
Display a little popup when webpack recompiles in watch mode.

**If this is a feature request, what is motivation or use case for changing the behavior?**
You can see the compilation status on the website. This would be great during development because you wouldn't have to switch to the console over and over again :)

**Comment by Wernerson** [comment]
I have a first version which just displays the text you can see in the client console in my forked repo.

**Comment by shellscape** [comment]
@Wernerson please do feel free to open a Pull Request with your proposed changes from your fork and we can go from there.
