### ISSUE TITLE
[Feature] Add option to select output of webpack console warnings/errors

### ISSUE THREAD

**Issue by avrelaun** [webpack/webpack-dev-server#977]
I work on a project with webpack 2.6.1 and webpack-dev-server 2.5.0.

Webpack offers to show warnings & errors on output (eg. for lint) which is great, but it outputs it to both my unix shell and the browser console making it redundant and polluting my other browser console messages.

I'd like to be able to configure it to "shell only" in my use-case, but I guess some people would prefer other options like "browser only" or "both".
I searched such an option in the docs, but couldn't find one.

**Comment by avrelaun** [comment]
In fact there is 3 outputs possibles: shell, browser console, et overlay. The overlay is configurable, why not the others ?

**Comment by shellscape** [comment]
We'd welcome a PR to implement any additional output you'd like to see.
