### ISSUE TITLE
Is there a simple way to run a command when build become INVALID?

### ISSUE THREAD

**Issue by MoOx** [webpack/webpack-dev-server#98]
Can't find anything in the doc about that.
I would like to lint my files when build is invalid (a file has been changed) & think it should be simple to do it .
I don't want to use a loader for that (I'm trying to avoid wrapper & [have issue with peerDep](https://github.com/webpack/webpack/issues/570#issuecomment-65760396) like I had when using gulp + pipe wrapper.
Is there an easy way to use some cli hook or similar ?

**Comment by sokra** [comment]
You can write a plugins for the `invalid` hook.

``` js
plugins: [
  function() {
    this.plugin("invalid", function() {});
  }
]
```

**Comment by MoOx** [comment]
Thanks for the tip.
