### ISSUE TITLE
*bug* Module not found: Error: Can't resolve 'loglevel' in webpack-dev-server/client

### ISSUE THREAD

**Issue by stephonlawrence** [webpack/webpack-dev-server#984]
I think this
https://github.com/webpack/webpack-dev-server/blob/master/package.json#L41
should be in dependencies not devDependencies. It's causing the module not found error, after I do `webpack-dev-server`

I installed with `npm install --save-dev https://github.com/webpack/webpack-dev-server.git`

I needed to do this rather than `npm install --save-dev webpack-dev-server` because I'm trying to get around that `Error: addMembership EHOSTUNREACH` issue.

I'm using Windows 10 64bit
and here's a piece of my package.json file
```
"webpack": "^3.0.0",
"webpack-dev-server": "git+https://github.com/webpack/webpack-dev-server.git"
```

please let me know if I'm doing something wrong.
I believe this is a bug.

**Comment by bkazi** [comment]
I think this is caused since the `loglevel` package being used in `client/index.js` but is listed under `devDependencies` in the `package.json` instead of `dependencies` and hence is not installed
I resolved it by simply running
```bash
npm i loglevel
```

**Comment by chulanovskyi** [comment]
Strange, but after having same error i install `loglevel` under devDependencies and this also solved the problem...

**Comment by sayanriju** [comment]
I was having similar error `Module not found: Error: Can't resolve 'loglevel'` with webpack-dev-server and also solved it by `npm -D loglevel`

**Comment by karthikkrishna611** [comment]
Now with the recent version of webpack-dev-server you must also install loglevel

If you have already globally installed webpack-dev-server. Use command npm install -g loglevel
if you have already locally installed webpack-dev-server. Use command npm install --save-dev loglevel

**Comment by markelog** [comment]
But why? Is this a bug or...?

**Comment by zalishchuk** [comment]
@markelog I personally 99% sure it's a bug and `loglevel` should be moved from devDependencies to dependencies. Pull request with solution is already submitted by @athomann (#1001)

**Comment by DavidNorena** [comment]
Meanwhile we need to manually install loglevel ok ?

**Comment by zalishchuk** [comment]
@DavidNorena I don't see any critical innovations in `webpack-dev-server@2.6.0` to improve developer experience, so if you don't need any of [these updates](https://github.com/webpack/webpack-dev-server/releases/tag/v2.6.0), you can fallback to previous version until the bug is fixed. Or as you said it above, you can manually install `loglevel` mentioned in #sayanriju or if you are using yarn - `yarn add -D loglevel`

**Comment by DavidNorena** [comment]
@zalishchuk  Thank you so much man !

**Comment by rojobuffalo** [comment]
What fallback version doesn't have this bug? I have WDS v2.4.2 in devDependencies and am seeing this.

**Comment by SpaceK33z** [comment]
Fixed in `webpack-dev-server@2.6.1`.

**Comment by stephonlawrence** [comment]
Thanks for the responses. And I will try that version. Sorry I didn't see these responses until today.

**Comment by rojobuffalo** [comment]
Are you sure that it's fixed? I'm still getting the same error with `v2.6.1`. Goes away when I install `loglevel`. Tried `rm -rf node_modules && npm i`. Is `loglevel` supposed to be a peerDependency or is this just a bug?

**Comment by zalishchuk** [comment]
@rojobuffalo `loglevel` package is currently [in dependencies section](https://github.com/webpack/webpack-dev-server/blob/master/package.json#L20), are you sure you are using `2.6.1` version?

**Comment by rojobuffalo** [comment]
@zalishchuk I cleaned everything out and re-installed a second and then a third time. After the third try it's all working. Weird, but seems like you can disregard my comment.

**Comment by vunb** [comment]
`npm install -D loglevel` resolved for me. Thanks!

**Comment by squidfunk** [comment]
Still happening in `3.10.1`. Might be happening because I installed `webpack-dev-server` in a parent directory due to a mono repository architecture.

**Comment by hamed-farag** [comment]
> 
> 
> Still happening in `3.10.1`. Might be happening because I installed `webpack-dev-server` in a parent directory due to a mono repository architecture.

it happens with me if I specify webpack.config.js file location for webpack-dev-server!!

![image](https://user-images.githubusercontent.com/5382471/73054657-a6eebd80-3e93-11ea-9ea7-e7a4c3bd975c.png)
