### ISSUE TITLE
Do we have Node.js API docs?

### ISSUE THREAD

**Issue by OuYancey** [webpack/webpack-dev-server#988]
I know there are many examples in this rep, but I can't find any docs.
Just like [Webpack Node.js API](https://webpack.js.org/api/node/) ?
Anybody can help me ?

**Comment by karataev** [comment]
[Docs](https://webpack.js.org/configuration/dev-server/)

**Comment by OuYancey** [comment]
sorry for bad description. 
what i need is [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware#advanced-api).
