### ISSUE TITLE
WDS.listen only works with an IP host (not a domain)

### ISSUE THREAD

**Issue by appsforartists** [webpack/webpack-dev-server#99]
@sokra, I've encountered a frustrating issue with WDS (that very well could be a problem upstream in Express), but I'm hoping you have some insight:

 - [bikeindex.local](http://bikeindex.local:8080) is routed to `127.0.0.1` in my `hosts` file.  

 - If I call `webpackDevServer.listen(8079, "bikeindex.local")`, my computer can connect to both http://bikeindex.local:8080 (which is powered by [mach](https://github.com/mjackson/mach)) and http://bikeindex.local:8079 (WDS).  Other devices on my network can connect to mach at http://bikeindex.local:8080 just fine, but WDS refuses the connection on http://bikeindex.local:8079.  

 - If I replace the WDS call with `webpackDevServer.listen(8079, 192.168.10.107)`, any device on my network works as expected.

I'm using [Charles Proxy's DNS Spoofing](http://www.charlesproxy.com/documentation/tools/dns-spoofing/) to test an iPad and explicitly pointing the `hosts` file on other devices to 192.169.10.107 for [bikeindex.local](http://bikeindex.local:8080).  In both cases the devices cannot connect to WDS.  (The error is "connection refused".)  Here is a sample request:

```
GET http://bikeindex.local:8079/bundles/jsx.js HTTP/1.1
Host: bikeindex.local:8079
Proxy-Connection: keep-alive
Cache-Control: max-age=0
Accept: */*,image/webp
Referer: http://bikeindex.local:8080/bikes/1035/
User-Agent: Mozilla/5.0 (iPad; CPU OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/40.0.2214.69 Mobile/12B435 Safari/600.1.4
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

My theory is that somehow Express resolves `bikeindex.local` to be 127.0.0.1 and rejects any connections coming from other networks; whereas, mach listens for all incoming traffic and then filters on the HTTP host to determine how to respond.  So, a request to 192.168.10.107 with a `Host: bikeindex.local` header passes mach's muster, but not Express's.  This seems absurd, but it's the most plausible explanation so far.

My Mac is running 10.9.2 and Node 0.11.13.  Thoughts?

**Comment by appsforartists** [comment]
I removed the host in `wds.listen` altogether and that also works.  I still don't understand why `host` is behaving like it is.

**Comment by sokra** [comment]
This is working as expected.

`.listen(8079, "bikeindex.local")` is equal to `.listen(8079, "127.0.0.1")` as you specified it this way in `hosts`. That way other devices cannot connect.

**Comment by appsforartists** [comment]
Since removing the `host` parameter works around this,  I suppose I can close it, but I don't understand the point of `host` if it binds to a particular IP address (as opposed to filtering by the `Host` header).  Which IP address a `host` resolves to is always outside the control of the web server; it's controlled by DNS and/or by the `hosts` file of the requesting machine.  Moreover, that IP almost always belongs to another device (like a load balancer).

When would you ever want to use `.listen(8070, "bikeindex.local")` to bind to a particular IP address, and how would the computer know which address that was?

**Comment by sokra** [comment]
The second arguments to `listen` specifies the interface to socket listens on.
