### ISSUE TITLE
Linux: inotify system call return values should be checked

### ISSUE THREAD

**Issue by mschurr** [webpack/webpack-dev-server#991]
I sat here in confusion for about an hour today wondering why webpack was not detecting my code changes on disk. The file mod times were getting set, and when I restarted the development server entirely, the changes would show up.

I was trying to figure out why file changes weren't being picked up by the dev server, when eventually I tried to use tail and got this:
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling

This suggests to me that the dev server is not checking the return values of the inotify syscalls and is instead just silently continuing onwards even when those system calls fail. 

I'll note the fix to my particular problem (for those who find this) was to increase the limit to something more reasonable in /etc/sysctl.conf:
fs.inotify.max_user_watches = 524288
sysctl -p

I'm filing this issue so that you can add a sensible error message when these system calls fail that will (hopefully) save others some of the time I spent diagnosing the problem.

**Comment by shellscape** [comment]
@mschurr we'd happily review a pull request to resolve this issue.

**Comment by shellscape** [comment]
@mschurr this ticket is stale at 60 days and will be closed if there's no response from the community. last chance to weigh in 😅

**Comment by mschurr** [comment]
I still think it should be fixed. Unfortunately, I don't have time to do it myself.

**Comment by shellscape** [comment]
OK thanks for following up. We'll reopen if someone would like to take on the task.
