### ISSUE TITLE
configuration has an unknown property 'disableHostCheck'.

### ISSUE THREAD

**Issue by StephanBijzitter** [webpack/webpack-dev-server#992]
Related to #882 

**What is the current behavior?**
With `disableHostCheck`, webpack does not compile;
without it, webpack-dev-server gives an "Invalid Host header" message on a different device.

**What is the expected behavior?**
All I want is to just be able to test my application locally on another device.

**Please mention your webpack and Operating System version.**
webpack 3.2.0, webpack-dev-server 2.5.1, OS X latest.

**Comment by StephanBijzitter** [comment]
```
    devServer: {
        disableHostCheck: true,
        // other options
    }
```
Yeah, in the end quite obvious... I had to add it as part of the devServer configuration.

**Comment by antewelec** [comment]
This does the trick!

**Comment by evandrogrm** [comment]
https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a
