### ISSUE TITLE
Assets not being served from 'publicPath'.

### ISSUE THREAD

**Issue by Panoplos** [webpack/webpack-dev-server#995]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
When specifying `publicPath` in the `devServer` config portion of the webpack config, assets are inaccessible from that path. The webpack app entry is served from `MemoryFileSystem`, so I assume there is some conflict with this. This is a problem because most people would like to bundle and serve vendor code separately from the app. (Seems like I see this error reported in some form or another all over the web.)

**If the current behavior is a bug, please provide the steps to reproduce.**

You can see this failing here: https://github.com/Panoplos/react-webpack-hot-reload-boilerplate

**What is the expected behavior?**
Dev server should serve assets from `contentBase` on `publicPath`. Incidentally, all assets from `contentBase` are being served on `/`, so there is a workaround for this, but this is not as advertised and is problematic as production code is not served from the root.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention your webpack and Operating System version.**
Running on Ubuntu 17.04 with webpack details in the referenced git.

**Comment by shellscape** [comment]
@Panoplos can you reference some of the posts around the web that you mention? we'd like to take a look at their use-cases.

if we're able to confirm that behavior doesn't match expectations and we choose to move forward with a change for this, it'll be a breaking change (even though it's a correction) and will have to go into the v3 milestone.

**Comment by shellscape** [comment]
Ah, just recalled #954 (I knew this sounded familiar). Closing this a duplicate, please watch that issue for more details.
