### ISSUE TITLE
Can the latest changes be released?

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack-dev-server#996]
I'm currently blocked from using the latest webpack-dev-server until #980 is released. it was fixed since the last release but there has not been another yet.

Is there anything preventing a patch (or minor) release with the latest changes since 2.5.1?

**Comment by d3viant0ne** [comment]
The host check can simply be disabled in the interim as mentioned [in this comment](https://github.com/webpack/webpack-dev-server/issues/882#issuecomment-296436909)

**Comment by bdwain** [comment]
@d3viant0ne but the change is what exposes the option on the cli, right? so i'd have to change my build process to not use the cli in order to use that option? that's what i'm trying to avoid.

**Comment by d3viant0ne** [comment]
I put out a request in slack, we'll get a patch version out.

**Comment by bdwain** [comment]
thanks @d3viant0ne !

**Comment by bdwain** [comment]
any word on this?

**Comment by bdwain** [comment]
@SpaceK33z is it possible to get a patch release with the latest master? I've seen a few other issues that would also be resolved just with the latest master being released.

**Comment by bdwain** [comment]
It's been a week now and I know a lot of people are blocked by this. Releasing what's already in master seems like a simple request and it's a little frustrating that it's taking this long. 

@d3viant0ne was there any word when you asked the slack channel to do a release?

**Comment by d3viant0ne** [comment]
@SpaceK33z - Is a.f.k with r.l business.

I don't have write nor publish access on this side of the house, so unfortunately all I can do at this point is ask which I have done twice.

**Comment by bdwain** [comment]
@d3viant0ne well thank you for putting in the effort. i do appreciate it.

it seems like more people need write access since @SpaceK33z seems like a bottleneck for releases and when he's got other things going on nothing can get done. not sure where the best place to suggest that would be but it seems like the solution to the current problem.

**Comment by SpaceK33z** [comment]
I released `webpack-dev-server@2.6.0`. @bdwain you seem to imply I am the only one who can release, but note that there are 4 more people who have npm publish rights.

**Comment by bdwain** [comment]
thank you for doing the release @SpaceK33z. I was just suggesting that more members be given write/publish access since I know you're all busy and can't always respond ASAP, but trivial requests can often cause issues for many people at a time.

I appreciate all of the hard work you and everyone else put into this project and I'm sorry if I made it sound like that wasn't the case.
